### ISSUE TITLE
my open pilot is asking me to connect to internet when it is already connected, I can not use open pilot

### ISSUE THREAD

**Issue by camiloepp** [commaai/openpilot#1004]

**Comment by Debreo** [comment]
I had this issue too, but oddly enough after going to the Settings> network > WiFi settings and just reconnecting from more options and then hitting continue. I can’t explain it but it looks like it’s working now lol.

**Comment by pd0wm** [comment]
What is your dongle id? I can check in the logs if the updater is running successfully.

You can also SSH in and run `scripts/update_now.sh`, and check for any output in the normal tmux window. You should see a reason why it's not running the updater.

**Comment by pd0wm** [comment]
Closing this issue since no more information was provided. Feel free to open a new issue with more information.

**Comment by ch1derco** [comment]
Have the same problem. After about 2 weeks, the message "Immediately connect to the internet to check for updates. If you do not connect to the internet, open pilot won't engage in 0 days". Only a factory reset/new install of open pilot software solves the problem for another few weeks, then message comes again.

**Comment by WidgeonRBLX** [comment]
This is also happening to me, tried everything in regard to rebooting, turning off WiFi/on again, will try reinstalling...

**Comment by Zach-Attach** [comment]
I’m having the same issue as well with my EON, connected to a 2017 volt.
