### ISSUE TITLE
Turn on IR led for driver facing camera snapshot

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#1005]
When taking snapshots with the comma connect app, turn on the IR leds.

**Comment by pd0wm** [comment]
@robbederks Does this require panda changes? We would need to be able to turn on IR leds when the panda is in power saving mode.

**Comment by robbederks** [comment]
Yes, it is now not possible to turn on the IR in power savings. They use a lot of power (up to 6W), so we need to make sure that they definitely do not stay on.
I suggest putting them in the same logic as the safety mode (no heartbeat for a few seconds -> turn off)?

**Comment by robbederks** [comment]
Needs changes in boardd too to make sure that they turn off when ignition goes low

**Comment by pd0wm** [comment]
https://github.com/commaai/openpilot/commit/3a65206c8d0400fb22239c806429842236afac2b

**Comment by pd0wm** [comment]
@ZwX1616 Do we need to do anything special on the camera side? Or will starting camerad always fire up the IR leds?
