### ISSUE TITLE
Honda Civic Sedan 2019 not working on Comma2

### ISSUE THREAD

**Issue by ffhspa** [commaai/openpilot#1010]
**Describe the bug**
On Comma2 OP doesnt work on a Honda Civic Sedan 2019 with Bosch Radar. 
ON disqord some Users (Kev!n) tryed to Identify Cars Fingerprint. Then issue was, that following error appers on Comma2, "Gear not D"  
As this Car is Supported by OP, this seams to be a Bug. 

Update: Added new Fingerprint as previous was wrong

**How to reproduce or log data**
Car Fingerprint: 
  57: 3, 148: 8, 228: 5, 308: 5, 316: 8, 330: 8, 344: 8, 380: 8, 399: 7, 419: 8, 420: 8, 426: 8, 427: 3, 432: 7, 441: 5, 450: 8, 464: 8, 470: 2, 476: 7, 477: 8, 479: 8, 490: 8, 493: 5, 495: 8, 506: 8, 507: 1, 545: 6, 597: 8, 662: 4, 773: 7, 777: 8, 780: 8, 795: 8, 800: 8, 801: 3, 804: 8, 806: 8, 808: 8, 815: 8, 824: 8, 825: 4, 829: 5, 837: 5, 862: 8, 881: 8, 882: 4, 884: 8, 887: 8, 888: 8, 891: 8, 902: 8, 918: 7, 927: 8, 929: 8, 983: 8, 985: 3, 1024: 5, 1027: 5, 1029: 8, 1036: 8, 1039: 8, 1064: 7, 1092: 1, 1108: 8, 1115: 2, 1125: 8, 1296: 8, 1302: 8, 1322: 5, 1337: 5, 1361: 5, 1365: 5, 1424: 5, 1600: 5, 1601: 8

Cabana Links: 

https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-01-25--09-42-43&exp=1611509140&sig=A%2F9iUBavlBPOw5M%2Both4Zl%2BjSNnxfnanvIuTgFvCc0I%3D&max=11&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2Fc5e30ba0b150f3d9ba31b26e7efc729c_2020-01-25--09-42-43

https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-01-25--14-17-04&exp=1611509957&sig=AHqEqotiPOY1vnOQEtK9Ul8P9bnE4RFczv4FxeUiJT8%3D&max=2&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2F6eca0fed46329049760d3a35ed72f58e_2020-01-25--14-17-04

https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-01-25--09-42-43&exp=1611509140&sig=A%2F9iUBavlBPOw5M%2Both4Zl%2BjSNnxfnanvIuTgFvCc0I%3D&max=11&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2Fc5e30ba0b150f3d9ba31b26e7efc729c_2020-01-25--09-42-43

https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-01-25--14-17-04&exp=1611509957&sig=AHqEqotiPOY1vnOQEtK9Ul8P9bnE4RFczv4FxeUiJT8%3D&max=2&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2F6eca0fed46329049760d3a35ed72f58e_2020-01-25--14-17-04

https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-01-25--13-56-30&exp=1611510188&sig=KCWvoygOJxZjGPlyJGyADvyiVRTdluk08hKsprs7deg%3D&max=4&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2F595fbce2715f44015a39a298d80ee493_2020-01-25--13-56-30

**Expected behavior**
OP Should Engage on Honda Civic Sedan 2019 

**Device/Version information (please complete the following information):**
 - Device: Comma2
 - Version: 0.7.1 release2
 - Car: Honda Civic Sedan 2019

**Comment by geohot** [comment]
We will address this in 0.7.2

**Comment by ffhspa** [comment]
if you need any further Information, my disqord username is: hondacivicwyde

Thanks a lot!

**Comment by ffhspa** [comment]
My Car has been Portet susccefully to OP thanks to Chris!
He will put in the next time a Pull Request for the changes he made. 

Thanks!

**Comment by pd0wm** [comment]
What fork are you currently running? I'd like to check the modifications made to it.

I also made this PR with your FW versions, so maybe that's all that's needed to support your car: https://github.com/commaai/openpilot/pull/1033

**Comment by ffhspa** [comment]
Chris portet my Car succefully to OP. 
Here is the Link to the Fork he made: https://github.com/csouers/openpilot/tree/19-civic-1.6

**Comment by pd0wm** [comment]
Perfect!
