### ISSUE TITLE
Refactor params to use the same underlying implementation -- $200 bounty

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1041]
Currently there are two (or maybe three in Java):

* selfdrive/common/params.cc
* common/params.py

$200 for a merged PR that follows the spec below.

**Comment by pd0wm** [comment]
Think the python version has the most safe implementation. The C++ implementation needs to be written like the Python one, and then the Python one can become a Cython wrapper around the C++ implementation.

**Comment by LoganxDev** [comment]
Started working on this one.

**Comment by ahowe444** [comment]
Just submitted a PR for this.
