### ISSUE TITLE
Cache docker container in CI build step

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1042]
Why does build take 13 minutes? Can we cache better?

**Comment by pd0wm** [comment]
We can manually push a docker container to the github package registry that can be used a base for the build. We have to manually update that when we make big changes to the dockerfile.

Unfortunately Github actions or Azure pipelines doesn't let you persist the docker cache between workflows.

**Comment by geohot** [comment]
That sounds reasonable, as long as we have an easy script for it. I don't think we change those files much.

**Comment by quillford** [comment]
I think CircleCI does free docker layer caching for open source projects.

**Comment by pd0wm** [comment]
Pushed a container to dockerhub.

I also tried using the github docker registry, but you need to login before you can pull any images, even for public repos. Logging in requires a token which doesn't work on forks.

**Comment by pd0wm** [comment]
Added caching. Went from about 14 minutes to 10 minutes.

For some reason the caching breaks when it loads the Pipfile, it doesn't see that that the file is the same.

**Comment by pd0wm** [comment]
That was built on my local machine. It's not exactly clear from the documentation what metadata it uses.

**Comment by quillford** [comment]
I was able to shave off [~3 minutes](https://github.com/quillford/openpilot/runs/437115077?check_suite_focus=true) (9.5 to 6) after using the image built in CI as the cache source. Not sure what metadata they're using, but I think going forward pushing images built in CI is the way to go, and they're already uploaded as artifacts.

**Comment by pd0wm** [comment]
Thanks! Think there is not much more to gain now in the build step.
