### ISSUE TITLE
too many values to unpack when running fw_versions.py --scan

### ISSUE THREAD

**Issue by illumiN8i** [commaai/openpilot#1057]
**Describe the bug**
The following error been reported to me by two different discord users: brad dongle ID **a2b1d650214053d7** and kevie dongle ID **5d37fcbf464873fa** when running **fw_versions.py --scan**

Traceback (most recent call last):
  File "fw_versions.py", line 193, in <module>
    candidates, fw_vers = get_fw_versions(logcan, sendcan, 1, extra=extra, debug=args.debug, progress=True)
ValueError: not enough values to unpack (expected 2, got 0)

**How to reproduce or log data**
cd /data/openpilot/selfdrive/boardd
pkill ./manager.py
./boardd
Then in another session/window:

cd /data/openpilot/selfdrive/car/
Python fw_versions.py --scan
Start Car when message shows getting Vin

**Expected behavior**
ECU firmware versions should be queried and returned.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Version: 0.7.2 devel-staging 43c07122e24134c5db68c5a224948b034c5b64a0
 - Car make/model 2020 Toyota Prius Prime and 2020 Corolla LE

**Comment by pd0wm** [comment]
Fixed by https://github.com/commaai/openpilot/commit/719e0572e1a6b202a21c2ee6f644c111a2273b83
