### ISSUE TITLE
commaneo fails to build due to android_vendor_oneplus_oneplus3

### ISSUE THREAD

**Issue by ingenieroariel** [commaai/openpilot#106]
I tried to build `commaneos` today and it failed because it could not access a private repo at: https://github.com/commaneos/android_vendor_oneplus_oneplus3/

Note: I filed the issue here because there is no issue tracker on `commaneos/android`

**Comment by espes** [comment]
I've enabled the issue tracked on commaneos/android

Cyanogenmod-based roms typically don't redistribute that repository. You can populate it yourself, see https://wiki.lineageos.org/devices/oneplus3/build#extract-proprietary-blobs

**Comment by qmind** [comment]
Hi,
can you share "extract-files.sh"
