### ISSUE TITLE
 openpilot offroad apk - It does not work

### ISSUE THREAD

**Issue by renat2985** [commaai/openpilot#1069]
Install the application today on /openpilot/apk/ai.comma.plus.offroad.apk
It does not work. An error appears and it closes.
Why? Thanks.
![Screenshot_2020-02-09-14-43-52-901_com miui bugreport](https://user-images.githubusercontent.com/1230815/74102310-1bd81d80-4b4b-11ea-9c04-78ed6747c08d.jpg)

**Comment by geohot** [comment]
It is not designed to be installed on normal Android, only NEOS.
