### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1070]
Before openpilot is 1.0 software, it needs support for multiple languages. We'd need a nice generic way to do this.

I think this will have to be written at first in house, but it should be easy after that to add more languages with pull requests. We should look into what dragonpilot is doing and take what's good.

**Comment by xx979xx** [comment]
I started working on this (not ready yet) https://github.com/xx979xx/openpilot/blob/i18n/selfdrive/controls/lib/alerts.py
plz everyone feel free to critique and contribute

**Comment by fusk-l** [comment]
For the language part, are you going to use something like transifex or similar? I would be more than happy to help with translation.

**Comment by s8321414** [comment]
When i18n and l10n support is ready, I can help to translate it to zh_TW.

**Comment by caginbektas** [comment]
I would love to start contributing by this. Count me in!

**Comment by geohot** [comment]
The UI rewrite should be done with this in mind.

**Comment by xx979xx** [comment]
@fusk-l @s8321414 @caginbektas here all Openpilot translatable texts up-to-date
[messages.po](https://github.com/xx979xx/openpilot/blob/i18n/selfdrive/assets/locales/messages.po)

**Comment by fusk-l** [comment]
> 
> 
> @fusk-l @s8321414 @caginbektas here all Openpilot translatable texts up-to-date
> [messages.po](https://github.com/xx979xx/openpilot/blob/i18n/selfdrive/assets/locales/messages.po)
> here is the code(not ready):
> [i18n.py](https://github.com/xx979xx/openpilot/blob/i18n/selfdrive/common/i18n.py)
> [i18n.h](https://github.com/xx979xx/openpilot/blob/i18n/selfdrive/common/i18n.h)

Just to be sure, we just copy everything, translate msgid and reupload where?

**Comment by eFiniLan** [comment]
@xx979xx does your ui.cc/sidebar.cc translation working? I tried a while ago and couldnt get it to work :(

**Comment by xx979xx** [comment]
@eFiniLan I have not tried it yet
needless to say, this is my first ever C++ code, I am doing it for fun (and learning C++ which I hate so much)
soon you will find out

**Comment by fusk-l** [comment]
Whenever there's an explanation of how this works, i'll be ready. Have already looked through some of the strings.

**Comment by xx979xx** [comment]
@eFiniLan you are right, ui does not translate. I think we have to install gettext package from [termux-packages repo](https://github.com/termux/termux-packages/tree/master/packages/gettext)
I tried but I got this error:
```
$ pkg install gettext
This must NOT be run as root as it will break your environment (root will be required for nearly everything due to changed file permissions)
```

**Comment by grafst** [comment]
I'm willing to translate into german.

**Comment by KristofKekesi** [comment]
I can translate it to Hungarian

**Comment by kengggg** [comment]
I'm happy to translate into Thai. 👌

**Comment by a-maccormack** [comment]
I can translate to Spanish

**Comment by ponzu07** [comment]
I can translate Japanese.

**Comment by royjr** [comment]
I got Arabic!

**Comment by sshane** [comment]
Merged base multilanguage support into master for offroad settings and onroad static text elements.

- [ ] We would still like to dynamically translate without restarting UI
- [ ] Translate alerts (dynamic text requires injecting our own translations with custom contexts into the TS files)

**Comment by sshane** [comment]
Moved improvements to https://github.com/commaai/openpilot/issues/25092
