### ISSUE TITLE
user is not notified if updated is constantly failing

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#1073]
If `updated` is repeatedly failing, ideally we would tell the user that this is happening.

Examples:
- you are on a private repo and there is no git key on the device
- you are on a public repo cloned using ssh and there is no git key on the device
- you are in a detached HEAD state.

When this happens the current messaging indicates you need to connect to the internet, but that won't help.

potential solution:
- `updated` writes out a new param `ConsecutiveUpdateFailures`
  (incremented by exceptions, reset by success)
- create new alert (similar to `Offroad_ConnectivityNeededPrompt`) indicating there is a problem when `ConsecutiveUpdateFailures` >= 5 (updates may normally throw an exception every once in a while due to losing internet connectivity after the connectivity check)
- alert message should indicate that the updater has repeatedly failed and if you don't fix it  you will get locked out of being able to engage openpilot

**Comment by pd0wm** [comment]
We now have `UpdateFailedCount`. So we just need to create the alert.
