### ISSUE TITLE
Go to dashcam mode if locked out

### ISSUE THREAD

**Issue by vanillagorillaa** [commaai/openpilot#1109]
For the update check lockout, openpilot should go to dashcam mode so that you can still at least use stock ADAS. Current behavior keeps in openpilot mode but does not allow engage.

**Comment by jpancotti** [comment]
Thought on giving the lockout a timer? For example, first day of lockout, dashcam mode for 10 mins after boot, second day 20 mins, third day 30...

**Comment by hey24sheep** [comment]
I would like to contribute, Can I get some help to get started?
