### ISSUE TITLE
adjustable car steering or steering not read straight

### ISSUE THREAD

**Issue by johnwaynehacker** [commaai/openpilot#111]
How do adjust actually car steering alignment reading? the blue one is off from straight in the road, it causes the steering to over correct too much and veer off road.

I guess it could be my car alignment maybe off a little ? but I'm still checking. The steering when straight on most road see to read more left on the neos.

What value can adjust the steering reading from car? or does it read straight from dbc? then I just need to add offset?
![img_8780](https://user-images.githubusercontent.com/28834068/27808849-b1c37d24-6018-11e7-8dca-075db61c4a4e.JPG)

what value does the machine learning to read and adjust steering to be small smooth instead of side to side adjustment steering when it drive straight, how can I improve it to be smoother?

**Comment by mwkrieger** [comment]
I'm seeing the same thing. I wish there was some sort of 'trim' function to tweak things slightly.

**Comment by mfd00gie** [comment]
Same problem here 16 civic, alignment is a bit out though

**Comment by CRV-Driver** [comment]
Same here, 2015 CRV. So far OpenPilot is a no-go until it can stay on the road.
I'm not seeing much response from Comma.ai on this.  From July 2017 and as of now it's April 2018. You would think that keeping the car on the road would be a big deal for them???
