### ISSUE TITLE
Hyundai: simplify gasPressed logic

### ISSUE THREAD

**Issue by rbiasini** [commaai/openpilot#1135]
Currently, the logic is:
```
if (cp.vl["TCS13"]["DriverOverride"] == 0 and cp.vl["TCS13"]['ACC_REQ'] == 1):
  pedal_gas = 0
else:
  pedal_gas = cp.vl["EMS12"]['TPS']
ret.gasPressed = pedal_gas > 1e-3
```
This depends on too many signals. Moreover, I believe gasPressed only becomes true when the driver acceleration request exceeds the one from ACC.

Instead, it would be better to use a simple "gas pedal position" signal.
@xx979xx, @tk211x any recommendation?

**Comment by TK211X** [comment]
Such a signal has only been discovered on EVs

**Comment by xx979xx** [comment]
@rbiasini in theory, it should be like this:
```
ret.gas = cp.vl["EMS12"]['PV_AV_CAN']
ret.gasPressed = bool(ret.gas)
```
need test across all working cars

**Comment by TK211X** [comment]
![image](https://user-images.githubusercontent.com/33460783/75069277-dc9cbb80-54be-11ea-9571-43985d5891bc.png)

**Comment by rbiasini** [comment]
@TK211X , based on what you posted, seems like PV_AV_CAN is "user+computer", no?

**Comment by xx979xx** [comment]
I see, yes

**Comment by TK211X** [comment]
I’ll establish a demonstration.

**Comment by xx979xx** [comment]
PV_AV_CAN vs TPS
![tps](https://user-images.githubusercontent.com/40252818/75070487-573bfa00-5504-11ea-8125-cab811493e3e.png)

**Comment by TK211X** [comment]
https://my.comma.ai/cabana/?route=53ac3251e03f95d7%7C2020-02-21--15-40-52&exp=1613853905&sig=eGuSmOTiRhRemSqQsobEFZViLMBdV%2BrGdhIW8I4XfIc%3D&max=1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F53ac3251e03f95d7%2Fa2c993d96520119ee34ca5dcfedfaac7_2020-02-21--15-40-52

Near the start ACC is enabled and set.

Past the 55MPH speed limit sign going onto the bridge I floor the accelerator pedal.

At the end of the bridge I hit the brakes.

**Comment by TK211X** [comment]
![image](https://user-images.githubusercontent.com/33460783/75089594-603ec280-5528-11ea-9632-d98d31a643db.png)
Green = SCC Set
Yellow = Driver Accelerator Pedal Max Action
Red = Driver Brake Action

**Comment by TK211X** [comment]
Actually....... I've spent some time comparing values from the various EMS messages and found a signal that may be of interest to you @rbiasini 

`CF_Ems_AclAct` (EMS16)

It appears to be a flag that's specific to driver accelerator pedal actuation.

![image](https://user-images.githubusercontent.com/33460783/75089781-6df54780-552a-11ea-9601-429e1fb4e98e.png)
![image](https://user-images.githubusercontent.com/33460783/75089871-333fdf00-552b-11ea-84c7-d979a03d4ff9.png)

**Comment by TK211X** [comment]
`CF_Ems_AclAct` (EMS16)

Literally appears to be a signal that says "hey, the driver is using the gas pedal."

Can't get more simple than that.

One thing to keep in mind is that not all vehicles have the same power-plant signals as some messages accomplish specific missions for that model.

Given the nature of this discovery and the fact that HKMC tends to keep signals and their formats universal, albeit, sometimes grouped differently under a different CAN message. I'm sure that finding a similar message for a given model is possible if EMS16 is not present for said model. For example as stated previously in EV's there exists an actual driver accelerator position sensor etc.

**Comment by xx979xx** [comment]
what a wonderful job @TK211X 
so here you have it @rbiasini 
```
ret.gas = cp.vl["EMS12"]['PV_AV_CAN'] / 100
ret.gasPressed = cp.vl["EMS16"]["CF_Ems_AclAct"]
```

**Comment by rbiasini** [comment]
this is great, @TK211X !
Yeah, I'm going to change both gas and gasPressed as you wrote, @xx979xx . 
Nice.

**Comment by rbiasini** [comment]
merged changes. If you end up driving the code, let me know if you have any issues. Thanks!
https://github.com/commaai/openpilot/pull/1152

**Comment by TK211X** [comment]
lol, when is the harness being released. Doubt there would be a reason to use official until it comes out. I hear KU7 said official didn’t even work when he tested it.

**Comment by TK211X** [comment]
![image](https://user-images.githubusercontent.com/33460783/75103976-b49d7d00-55d0-11ea-8a14-c9d665492d6a.png)

**Comment by rbiasini** [comment]
@TK211X , it's ok if you guys are on a custom fork. But I recommend to keep panda code in synch (which is affected by this change).
