### ISSUE TITLE
A whole process guide ----need   for help

### ISSUE THREAD

**Issue by sgong4** [commaai/openpilot#115]
hi:
    i am a new guy, but i am interesting in this.  And i found so many files or guide  in "https://github.com/commaai/openpilot" , 
  so i don't know where should i do first .
  can you update a whole process guide  for new guy.
  like:
  first what should we do .
  second what should we do .
  ......
  at last , the car can self drive.

 thanks.

**Comment by chinlin0924** [comment]
it is not for basic users, I think.
u can begin from panda to analysis your can bus signal first for your car.
