### ISSUE TITLE
Add the ability in OP to shut down eon automatically after some idle time.

### ISSUE THREAD

**Issue by qzhang83** [commaai/openpilot#1154]
I don't have a sim in my EON, so I need to upload data once I get home and connect to my home WIFI. Uploading my day's worth of data maybe 30 minutes. I'd like the EON to be able to do so once connected to my home WIFI, and then when the upload completes, to turn itself off.

My current routine is to turn it off manually after each drive, and then after a few weeks bring the EON inside and plug it in to a usb block while it uploads. This is not convenient for 3 reasons:
- I have to bring it periodically
- I have to manually turn it off after every drive
- If I let someone else drive my car I have to teach them to turn off my EON afterwards.

The alternative is to never turn off the EON, and use whatever little battery power it charged during the drive to upload whatever it could. That's also not ideal as it keeps the EON in a constant discharged state. I think the software update process requires the EON to have at least 35% juice.

**Comment by jpancotti** [comment]
Use comma power
