### ISSUE TITLE
“Openpilot not available, issue with communication processes”

### ISSUE THREAD

**Issue by djjohnny1093** [commaai/openpilot#1156]
Got my comma 2 in mail, installed everything correctly, rechecked all connections. Open pilot wont engage when pressing set. I get the above titled error. 

Tried from rolling start.
Tried on highway at various speeds.

2017 Honda CRV Touring.

Restarted device and car several times...

Panda box says “Good Gps” 

Pushed obd connector in till i heard a click. 

Calibration above 16mph worked.

No pins are bent on anything. Brand new straight out the box.

A little disappointed. 

Please somebody tell me i didn't buy a $1300 paperweight.

**Comment by arne182** [comment]
Don't stress too much. Reach out to us on discord and we will gladly help get you up and running.

**Comment by pd0wm** [comment]
Debugged this issue through discord. Seems like the driver monitoring model was not running. I suspect an issue with the DSP on your comma 2. We will replace the hardware.
