### ISSUE TITLE
Bypass Subaru ACC and enable stop and go - $500 Bounty

### ISSUE THREAD

**Issue by Macc92** [commaai/openpilot#1177]
If there is any way to enable this, I will pay $500 to have this feature enabled on my Subaru 2019 crosstrek. Payment will be made through paypal.

**Comment by geohot** [comment]
The first user bounty! Very cool. I think if others want to tack on they can do here also.

**Comment by alxndrmlr** [comment]
Watching this! Just starting to read up more about the product. I'm in a 2019 Forester, I'd potentially be interested in contributing to this bounty!

**Comment by vanillagorillaa** [comment]
We are consolidating all community bounties to our community bounty page found here, https://community.comma.ai/wiki/index.php/Bounties.
