### ISSUE TITLE
Add ability to OP to steer below 12mph. User Bounty 200$

### ISSUE THREAD

**Issue by ffhspa** [commaai/openpilot#1195]
My Car is a Honda Civic Sedan (Bosch). Unfortunatly OP doesnt have ALC below 12mph. 
I would like to have OP takes steering control from 0mph.
200$ Bounty for the one who solves this issue and makes a PR to upstream. 
Money will be transferred either over Bank or Paypal as per user wish. 
If someone wants to contact me on disqord, my username is: hondacivicwyde

**Comment by pd0wm** [comment]
Unfortunately that is a limitation in the EPS that cannot be solved by openpilot :( Closing this bounty.
