### ISSUE TITLE
Comma does not recognize the vehicle. (kia sorento 2018)

### ISSUE THREAD

**Issue by zent8385** [commaai/openpilot#1199]
**Describe the bug**

**How to reproduce or log data**
Steps to reproduce the behavior, or a explorer/cabana link to the exact drive and timestamp of when the bug occurred.

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: EON Gold (DIY)
 - Version: e.g.0.7.3, or commit hash when on HKG_community
 - Car make/model kia sorento 2018

**Additional context**
Kia Sorento 2018 does not work with this branch. Can you tell me what the problem is?

Comma does not recognize the vehicle.

**Comment by geohot** [comment]
HKG_community is not maintained by us.
