### ISSUE TITLE
Popular Community Bounty: Toyota no-DSU cars need OP Long

### ISSUE THREAD

**Issue by routine88** [commaai/openpilot#1200]
It bugs us that OP long doesn't work on the Toyota Camry or CH-R, so we are banding together to create a community bounty for the betterment of all no-DSU car owners.

Our pledgers have promised a bounty of $1,600 and the number is growing by the day (just like the number of Toyota Camrys/CH-Rs on the road).

We would like this bounty to be featured on the comma.ai bounty page, and to perhaps get a shout out of some sort to promote hackers to get involved. After all, we're talking about some very popular vehicles. 

**Expected behavior (OP Long)**
-A chill driving experience

**Actual Behavior (stock TSS-P ACC)**
-PANIC BREAKING! 

Our community bounty pays the creator of a practical hardware or software solution that enables OP Longitudinal control on no-DSU Camry and CH-R vehicles (model year 2018+). The solution would need to work with EON or Comma 2 users.

Comma already has a $2000 bounty for this issue but our bounty differs in that it allows hardware and software solutions, while Comma only allows software solutions.

DM @rageser to be added to the registry of pledgers, or interested hackers please feel free to inquire. Thanks, and we hope to see our bounty up on Comma.ai.

@rageser discord

**Comment by vanillagorillaa** [comment]
We are consolidating all community bounties to our community bounty page found here, https://community.comma.ai/wiki/index.php/Bounties.

**Comment by routine88** [comment]
> We are consolidating all community bounties to our community bounty page found here, https://community.comma.ai/wiki/index.php/Bounties.

Please post the above information and the bounty amounts below to the Wiki. I can't seem to gain access to post......

Rageser $500
Andybfield $200
Venu $150
Erich $100
apm $100
aLp $100
Hermosa $100
Djt1283 $100
02trackroad $75
Cferra $50
Jadtec $50
Mubimmer $50
Fchen53 $25

Subtotal: $1600

Community Total = $1600 (hardware or software hack)

Comma bounty = $2000 (software only)
