### ISSUE TITLE
How to debug openpilot?

### ISSUE THREAD

**Issue by clepz** [commaai/openpilot#1214]
Hi,
I want to debug openpilot step by step. How can i achieve this?. How did you debug so far?

Thank you in advance.

**Comment by pd0wm** [comment]
Can you be more specific? Do you have a specific issue?

**Comment by maykonpacheco** [comment]
I believe he wanted to understand, for example, what the value of a variable is.
In Javascript we use console.log().
How do I, for example, find the value of signals, on line 87?
 Attached is the image

![image](https://user-images.githubusercontent.com/38124066/151680357-4732a503-c68d-40b8-8c6e-38684e81a2b6.png)
