### ISSUE TITLE
Custom logic for insufficient torque detection should be removed

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1239]
Right now, it can't for example alert when Toyota wind down torque is too much.

We need to move to a localizer/deviation from desired path measurement. This should work without a GPS at all, but is expected to work better with one.

**Comment by HaraldSchafer** [comment]
Torque control has a good alert now, and other torque based cars should move to torque control in time
https://github.com/commaai/openpilot/blob/c3e2d35963a95bfeaf99048decbd6066c52113d8/selfdrive/controls/controlsd.py#L631
