### ISSUE TITLE
Why isn't there visiond in newest version of code?

### ISSUE THREAD

**Issue by mayukuner** [commaai/openpilot#1248]
I am a little confused that in `cereal/service_list.yaml` visiond is mentioned but I cannot find this module in the source codes. 
And when I checked older versions of openpilot such as 7.0, visiond is still there. 
Has the developers decided not to publish visiond?

**Comment by geohot** [comment]
It's split into modeld and camerad. Feel free to update the comments service_list.yaml in a PR
