### ISSUE TITLE
Ubuntu ModuleNotFoundError: No module named 'common.kalman.simple_kalman_impl'

### ISSUE THREAD

**Issue by banjuanshua** [commaai/openpilot#1271]
Ubuntu 16.04, python3.7.3

I run ubuntu_step.sh in tools, then I run replay/ui.py and got:

![a](https://user-images.githubusercontent.com/14140598/77389276-b6c04a80-6dcd-11ea-8437-a1054d57ad82.png)

It seems cant import pyd or pyx in python.

**Comment by HaraldSchafer** [comment]
Did you compile openpilot? You need to run "scons -j10" in the openpilot directory to compile openpilot.

**Comment by banjuanshua** [comment]
THanks，it helps.
