### ISSUE TITLE
error in runtime in carstate.py

### ISSUE THREAD

**Issue by githubuse** [commaai/openpilot#128]
hi all, it's easy to be reproduce, version 0.3.6
openpilot will show exception in "self.brake_switch_ts = cp.ts[0x17C]['BRAKE_SWITCH']" in carstate.py file, because "cp.ts[0x17C]" is just a timestamp instead of a dictionay, we could see where it's filled value in function "update_can" in car_parser.py.
so i think here it should be "self.brake_switch_ts = cp.ts[0x17C]",please help confirm,thanks

**Comment by espes** [comment]
can_parser.py isn't used by default.
