### ISSUE TITLE
OpenPilot not controlling speed of vehicle

### ISSUE THREAD

**Issue by mbuboltz1024** [commaai/openpilot#1281]
OpenPilot is not controlling the speed of my vehicle and is not slowing down for cornering.
If I am incorrect I'm sorry for posting this.

Expected behavior
I was under the impression that OpenPilot controlled steering,brake and acceleration.

Device/Version information:

Device: EON Gold
Version: 0.7.4
Car make/model: 2017 Chrysler Pacifica (Gas)

**Comment by vanillagorillaa** [comment]
In the supported car list (https://github.com/commaai/openpilot#supported-cars) the column for ACC (Adaptive Cruise Control) lists weather stock is left in control of this functionality, or if openpilot can control. As seen for the Chrysler Pacifica, ACC is left to the stock system to handle.
