### ISSUE TITLE
Enable sounds when running openpilot on a computer

### ISSUE THREAD

**Issue by ZwX1616** [commaai/openpilot#1285]
openpilot plays sounds only when running on a phone with the current API. 

Now that we have it working with CARLA and the webcam port, it would be great to have sound effects (e.g. engaging/disengaging, alerts) when running openpilot on the computer too.

**Comment by Abhijnan-Bajpai** [comment]
I would love to work on this part as my first issue. Can I be assigned to this?

**Comment by techasit14607** [comment]
Yes you can.
