### ISSUE TITLE
Want to contribute, Can't find TODO

### ISSUE THREAD

**Issue by astromme** [commaai/openpilot#131]
Hey! I'm interested in helping contribute to openpilot. The readme says:

> We welcome both pull requests and issues on github. See the TODO file for a list of good places to start.

I can't find this TODO file, it doesn't seem to exist in the repository. Can you help point me in the right direction for starter project ideas? I'm taking the udacity SDC nanodegree and have previous experience with tensorflow, python, cpp, computer vision.

**Comment by Andrewngabriel** [comment]
If you look at the source code files, you will see sections labeled TODO above them saying things like '# TODO: Refactor Code'
