### ISSUE TITLE
Please someone add compatibility for PS4 controller to drive the car.

### ISSUE THREAD

**Issue by hemangjoshi37a** [commaai/openpilot#134]
I have been waiting for the moment when I can control my car with PS4 controller, but it seems very close now. I am not too much into selfdriving and linux programming so i cant program it myself but it's a idea if someone wants to make some cool stuff.

**Comment by boystray** [comment]
you can read the news "This Lincoln can be driven with a game controller"
http://www.idgconnect.com/blog-abstract/11574/this-lincoln-driven-game-controller

**Comment by vanillagorillaa** [comment]
See, https://github.com/commaai/openpilot-tools. Closing
