### ISSUE TITLE
"ubuntu_setup.sh doesn't run"

### ISSUE THREAD

**Issue by tom-doerr** [commaai/openpilot#1375]
I saw that the file `tools/ubuntu_setup.sh` has a comment that says:
```
# NOTE: ubuntu_setup.sh doesn't run! only for reading now
```
Would you accept a pull request that fixes the script and adapts it for Ubuntu 20.04?

**Comment by pd0wm** [comment]
maybe create a new one for more recent ubuntu?

You should be able to remove all the pyenv stuff. I got it running with the built in python3 in ubuntu 19.10.
