### ISSUE TITLE
Problem decoding dumpsys connectivity

### ISSUE THREAD

**Issue by dpanych** [commaai/openpilot#1387]
**Describe the bug**
Tmux is showing a constant error for something network related:

Error getting network status
Traceback (most recent call last):
File "/data/openpilot/selfdrive/thermald/thermald.py", line 210, in thermald_thread
network_strength = get_network_strength(network_type)
File "/data/openpilot/common/android.py", line 235, in get_network_strength
out = subprocess.check_output('dumpsys connectivity', shell=True).decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 224: ordinal not in range(128)
**How to reproduce or log data**
Steps to reproduce the behavior, or a explorer/cabana link to the exact drive and timestamp of when the bug occurred.

**Expected behavior**
My SSID is "Encrypted Space 2.4GHz". The first space (after Encrypted) is \x20 and the second space for some reason (after Space) is \xC2. Not sure why router did that..

**Device/Version information (please complete the following information):**
 - Device: EON Gold
 - Version: 0.7.4 release2

**Additional context**
I changed the decoding from ascii to utf8 in /data/openpilot/common/android.p on my own fork and the error seems to have gone away. Any caveats to this?

**Comment by jyoung8607** [comment]
The fix for this was also proposed in #1385 to address a similar problem.
