### ISSUE TITLE
clEnqueueMapBuffer without clEnqueueUnmapMemObject

### ISSUE THREAD

**Issue by deanlee** [commaai/openpilot#1397]
clEnqueueMapBuffer is getting called repeatedly without clEnqueueUnmapMemObject 

https://github.com/commaai/openpilot/blob/28d8b4abac1a97905a74ea126d275125d2e93cd0/selfdrive/modeld/models/commonmodel.c#L36-L54

https://github.com/commaai/openpilot/blob/28d8b4abac1a97905a74ea126d275125d2e93cd0/selfdrive/modeld/models/driving.cc#L103

from the [document](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clEnqueueMapBuffer.html) of clEnqueueMapBuffer:

>if a memory object is currently mapped for reading, the application must ensure that the memory object is unmapped before any enqueued kernels or commands that write to this memory object or any of its associated memory objects (sub-buffer or 1D image buffer objects) or its parent object (if the memory object is a sub-buffer or 1D image buffer object) begin execution; otherwise the behavior is undefined.

**Comment by geohot** [comment]
Hmm, I'm not sure. I think we probably should be unmapping them. Check if the memory space of modeld is growing, or maybe just try printing the ptr addr of net_input_buf and see if it's reused.

Thanks for your pull requests btw!

**Comment by deanlee** [comment]
My pleasure :-)
