### ISSUE TITLE
Stop sending auto generated recruiter messages

### ISSUE THREAD

**Issue by colinwren** [commaai/openpilot#142]
Yesterday I received this auto generated email from one of your recruiters. It is clear that you are scraping/getting data from github and auto emailing people as this sentence doesn't make sense: "Seems like you're doing really cool stuff at Self Employed"

Do you like receiving autogenerated recruiter emails? I can't imagine you do, so please tell your recruiters to stop doing this.

Email I was sent:
> Hi Colin - We are comma.ai, and we have an open source self-driving car you can build today: https://github.com/commaai/openpilot 
> 
> Seems like you're doing really cool stuff at Self Employed but based on your Github, we think you'd be great at comma. To solve self-driving cars, we are currently building the world's best car hacking tools and in-car mobile apps and are looking for React experience and programming chops.
> 
> Do you have 10 minutes to talk on the phone tomorrow? We'd like to bring you in to talk with George Hotz, CEO.
> 
> 
> 
> Recruiter Name
> ops @ comma

**Comment by geohot** [comment]
I'm offended by this. This won't happen again.
