### ISSUE TITLE
kalman SConscript error

### ISSUE THREAD

**Issue by andyluo7** [commaai/openpilot#1450]
aluo@aluo-XPS-8930:~/openpilot$ scons
scons: Reading SConscript files ...
  File "/home/aluo/openpilot/selfdrive/locationd/kalman/SConscript", line 30

    target_files = File([f'generated/{target}.cpp', f'generated/{target}.h'])

                                                 ^

SyntaxError: invalid syntax

**Comment by geohot** [comment]
You have to run scons with python 3.7
