### ISSUE TITLE
Remove prefix or move all capnp to c++

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1454]
Currently we are using a custom version of c-capnproto to hack a "cereal_" prefix on to the C api. https://github.com/commaai/c-capnproto/commit/2e625acacf58a5f5c8828d8453d1f8dacc700a96

It's one more dependency that has to be custom. Can we remove it and use the standard?

**Comment by deanlee** [comment]
I think it's better to move to C++.c-capnproto  is old and not well maintained.

**Comment by pd0wm** [comment]
I support moving everything to C++
