### ISSUE TITLE
Openpilot performance on various cars and calibration module

### ISSUE THREAD

**Issue by hongyuli** [commaai/openpilot#149]
Hi,

I noticed (1) on demo videos, openpilot did a great job on lane keeping, (2) comma AI is also trying to extend the compatibility to more vehicles. I'm just curious about what would be the performance of openpilot on different cars? Or, the question might be how could openpilot maintain a good performance for various cars?

To adapt openpilot to different cars, a couple of parameters will affect the end to end driving performance, such as camera pose, camera/smartphone mounting position, steering ratio, etc. Steering ratio might be easy to calibrate. However, for camera pose and camera/smartphone mounting position, they may largely affect the model performance.  So, I'm wondering

(1) Does openpilot/NEO have to be mounted on a specific fixed location? I checked the NEO tutorial, it seems the 3D printed case has to be mounted on a specific location as shown in https://www.youtube.com/watch?v=GzrHNI6eCHo . However, in this demo video https://www.youtube.com/watch?v=PwOnsT2UW5o&t=204s even though a general phone mount is used, the system could also work.

(2) What is the calibration process of openpilot? Does current open source code include any calibration functionality? Is it included in currently black boxed visiond, or a sperate model not open sourced yet, or comma ai has a large training dataset including various camera mounting positions and poses? Just curious about how to make the model to have such a good compatibility.

Thanks a lot.

**Comment by legonigel** [comment]
Your EON should be mounted roughly center of the windshield where it can see the whole road. For example see some community guides [here](https://opc.ai/guides/comma-eon-mounting-calibration-7zbso7) and [here](https://community.comma.ai/wiki/index.php/Installing_EON).

There is calibration in openpilot. See [calibrationd](https://github.com/commaai/openpilot/blob/devel/selfdrive/locationd/calibrationd.py), but the camera is still expected to be generally close to the center of the windshield.
