### ISSUE TITLE
Dashcam mode car unrecognized - 2019 jeep grand Cherokee trailhawk

### ISSUE THREAD

**Issue by cwarkenton** [commaai/openpilot#1490]
OP worked great. Latest forced update to 7.3 gave dashcam mode car unrecognized.

**Comment by VirtuallyChris** [comment]
What is your dongle ID?

**Comment by cwarkenton** [comment]
Thanks! Shows N/A

**Comment by cwarkenton** [comment]
Eon, Grey Panda, Giraffe, and FCA harness. All 'stock' from comma.ai

**Comment by VirtuallyChris** [comment]
Dongle ID can be found in device Settings -> Device -> Dongle ID

**Comment by cwarkenton** [comment]
04c3ecffabf06cdd

**Comment by VirtuallyChris** [comment]
This appears to be fixed in 0.7.5 with this pull request:
https://github.com/commaai/openpilot/pull/1354

Just to be safe, I've added a few more of your car's messages into this pull request:
https://github.com/commaai/openpilot/pull/1496

**Comment by cwarkenton** [comment]
Thanks for your help! 
I did pull and update add fingerprint through ssh. When the car started eon would give the proper 'keep eyes on road and be ready to take over' like it was good to go. When I get above around 8 mph it would give LKAS fault. 
Is 7.5 out somewhere I can flash?

**Comment by VirtuallyChris** [comment]
It's out in release2-staging or wait until it comes out on release very soon
