### ISSUE TITLE
More friendly environment for Visiond on PC Linux

### ISSUE THREAD

**Issue by hongyuli** [commaai/openpilot#150]
After reading [previous posts](https://github.com/commaai/openpilot/issues/4), I'm totally fine that openpilot does not release the visiond source code. But for this binary visiond, is it possible to post a tutorial on how to use it in Linux PC environment or maybe a wrapper on any languages? 

I know for the current openpilot, it is still possible to run visiond on Linux PC, as discussed [here](https://github.com/commaai/openpilot/issues/31). However, it is too hard for a green hand who does not have system programming experience. A more friendly environment for visiond will be helpful for developers to test visiond on vairous datasets and improve visiond by adding data-preprocessing.

Thanks.

**Comment by geohot** [comment]
visiond only runs on select Android phones
