### ISSUE TITLE
Sometimes training guide doesn't show on first boot

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#1501]
Just had it happen to me on a dashcam install. Terms and conditions showed, then went straight to the home screen on accepting. After that openpilot doesn't go offroad because training is not completed.

Manually starting the training from the settings fixed the issue.

**Comment by adeebshihadeh** [comment]
Seems this is intentional on the apk side? https://github.com/commaai/openpilot-apks/blob/master/offroad/js/store/nav/actions.js#L30

We either need to fix this in thermald and ignore training for dashcam or remove that condition in the apk.
