### ISSUE TITLE
Add alert for driver facing camera not working

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#1506]
Currently this triggers a generic "Communication issue between processes" warning.

**Comment by th-ad** [comment]
Would it be sufficient to check if the `dMonitoringState` process is alive and then trigger a more specific warning if it isn't?

**Comment by ZwX1616** [comment]
> Would it be sufficient to check if the `dMonitoringState` process is alive and then trigger a more specific warning if it isn't?

ideally we want to track the frontFrame packet or frame info from visionipc to know about camera state
