### ISSUE TITLE
Question about Honda Civic limitations on video “openpilot @ Web Summit”

### ISSUE THREAD

**Issue by muyufan** [commaai/openpilot#151]
You said：
> Due to limitations in steering firmware, steering is disabled below 12 mph

But in this video at 0:35 “openpilot @ Web Summit” [https://www.youtube.com/watch?v=cWeGcTvrO40](url)

Car can do left steering in an stop and go scenario, 
So what that limitations mean??? " steering is disabled below 12 mph"

**Comment by csouers** [comment]
That car was probably running their modified steering firmware. They've removed a lot of limitations that the factory iteration has. It's not publicly available.
