### ISSUE TITLE
Honda Civic 2016 without Honda Sensing

### ISSUE THREAD

**Issue by nominator** [commaai/openpilot#152]
Would it be possible to enable 'drive by wire' on Honda Civic 2016 models that don't have Honda Sensing installed. Models released in Pakistan didn't have Honda Sensing. So I am wondering is it worth trying to get a Panda, read messages and try to reverse engineer and find accelerate/brake and steering functions. Even without honda sensing, the car has ACC so it can auto brake and accelerate. So I am sure I can find these using Panda ans Cabana, but I am not sure about the steering. There is no auto-steer function available in the car. 

Please help me out here. If this turns out to be impossible then I will think about getting an after market Honda Sensing package installed in my car so that I can have it controlled by Openpilot ;)

**Comment by vanillagorillaa** [comment]
Honda Sensing is required. Closing
