### ISSUE TITLE
Add testing to camerad/modeld/dmonitoringmodeld

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#1536]
We need code to play an HEVC on the device and put it into camera_frame_stream.

Then run camerad with camera_frame_stream, modeld, and dmonitoringmodeld and check the output packets to be the same as the last run.

Test should reset calibration at start, and also needs to run calibrationd.

**Comment by adeebshihadeh** [comment]
I think this is really a couple different tests:

* run modeld and camerad with camera_frame_stream on device, and compare output packets
  * same for dmonitoringmodeld
  * calibrationd is already tested in process replay, so I think we can send the calibration from the logs
* run camerad on device with a special flag that writes the image to the capnp structs and check `frame`, `frontFrame`, and `thumbnail`
  * I'll write this as a generic replay using sockets to bring process replay to all the non-python daemons

What do you think @geohot?
