### ISSUE TITLE
Scope of an "all deprecated" comment unclear

### ISSUE THREAD

**Issue by LouisCAD** [commaai/openpilot#16]
Hi, I saw a comment saying "all deprecated" [here](https://github.com/commaai/openpilot/blob/e94a30bec07e719c5a7b037ca1f4db8312702cce/cereal/log.capnp#L87), but it's not clear where it's scope ends.

Could you be more specific on which fields exactly are deprecated, or add a statement to say where's the last deprecated field of the deprecated range?

**Comment by geohot** [comment]
It's only that section before the blank line. We should rename the fields.

**Comment by mgraczyk** [comment]
[Fixed](https://github.com/commaai/openpilot/blob/master/cereal/log.capnp#L88) in version 0.2
