### ISSUE TITLE
Dashcam mode car unrecognized - 2020 Toyota RAV4 hybrid XLE

### ISSUE THREAD

**Issue by drleuk** [commaai/openpilot#1604]
**Describe the bug**
unable to use openpilot - stuck in dashcam mode - car unrecognized

**How to reproduce or log data**
attempted to install forks from other rav4 hybrid TSS2 users
?fingerprint issue

**Expected behavior**
functional openpilot

**Device/Version information (please complete the following information):**
 - Device: comma2 devkit (0.7.5)
 - Dongle ID: 1250f32ee7c6fb26
 - Version: 0.7.5
 - Car make/model: 2020 Toyota RAV4 hybrid XLE (manufactured 3/2020)

**Additional context**

**Comment by pd0wm** [comment]
Should be fixed by https://github.com/commaai/openpilot/commit/d9202905449b8e2ea25ddb2ebb392eccb384471b

**Comment by drleuk** [comment]
thanks!
