### ISSUE TITLE
question about the function "model_eval_frame"

### ISSUE THREAD

**Issue by YJCITA** [commaai/openpilot#1614]
When I read the code, finde the func "ModelDataRaw model_eval_frame", which calculate pos(camera trans_vs, rot_vs ). I veru interting how to calculate, but I get nothing from the code. So can you share some details or papaers about this?
Thx

**Comment by pd0wm** [comment]
`model_eval_frame` runs the neural net on an image from the camera. Can you be more specific about your question?

**Comment by YJCITA** [comment]
> `model_eval_frame` runs the neural net on an image from the camera. Can you be more specific about your question?

 use the neural net to calculate camera motion information(such as  trans_vs, rot_vs) directly?
I wonder is there use some algorithms llike: Visual Odometry, or Visual Inertial Odemotry?

**Comment by pd0wm** [comment]
VIsual odometry is used in to generate the ground truth for the model, this not used online. The online model just takes in two frames and predicts the translation and rotation.

https://arxiv.org/abs/1812.05752v1 has some more info about our ground truthing stage + references to other papers.

**Comment by YJCITA** [comment]
> model

thx!!
Another question: do you evaluate the model output translation and rotation precision in different road case? How aboult he result?

**Comment by pd0wm** [comment]
Can you elaborate on that question? Not sure what you mean exactly.

**Comment by YJCITA** [comment]
I think I have get what I need
