### ISSUE TITLE
Handle transition from stock cruise enabled when starting in the middle of drive

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/openpilot#1623]
**Describe the bug**
It's been 30 hours, the comma two is off. When I turn on the car, the device begins to boot - but I still want to use my ACC for the first few minutes of my drive. I activate cruise control and am cruising on the highway. The comma two goes onroad, and stock acc immediately disengages with no warning.

**Expected behavior**
It would be great if there was some sort of alert from the comma two that stock ACC has been disengaged upon boot.

**Comment by adeebshihadeh** [comment]
Seems like this is because carState initializes with values that create noEntry events which will cancel the cruise mode.

**Comment by adeebshihadeh** [comment]
Will be addressed with #2262
