### ISSUE TITLE
There is not the directory zmq in openpilot/phonelibs

### ISSUE THREAD

**Issue by kev1876** [commaai/openpilot#163]
Hello!
    I were trying yo remake the spinner in ui, but when i read the makefile in the UI directory, I fond there is not the directory zmq in openpilot/phonelibs but mentiond in the makefile. anyone can do me a favor!

**Comment by brubakerjeff** [comment]
Hi,
Were you able to get another farther? What commands did you run to get to this point?

-Jeff
