### ISSUE TITLE
How do I make 2017 Prius Prime to be a self driving vehicle?

### ISSUE THREAD

**Issue by fiftycentsjj** [commaai/openpilot#164]
Hi Sir: 
          Greeting to you.
          Eon+Panda+Giraffe+Chrrf. Can the vehicle be a self driving vehicle with that all? Do I need to install openpilot in to EON? How? Your kindly reply would be appreciated. Thank you so much.

**Comment by geohot** [comment]
EON is designed to be a dashcam. It is not designed to drive a car.

**Comment by fiftycentsjj** [comment]
Many thanks for your quick reply. Any possibilities to make 2017 Prius Prime self driving as what you show Honda self driving video on the website? Can I install openpilot in to EON with Giraffe, Panda and Chrrf for making vehicle self driving? I am really interested in your self driving solution. Thank you very much.

**Comment by anhhna** [comment]
@fiftycentsjj as I know your car can if it have the Adaptive Cruise Control and Advanced Lane Keeping System likes Honda Civic
