### ISSUE TITLE
dmonitoring_model.keras can't load

### ISSUE THREAD

**Issue by gucasbrg** [commaai/openpilot#1656]
user keras 2.3.0 and tensorlfow 2.2.0
```
from tensorflow.keras.models import load_model, model_from_config
model = load_model('dmonitoring_model.keras')

```

result 
TypeError: Error converting shape to a TensorShape: Dimension value must be integer or None or have an __index__ method, got 80.0.

**Comment by ikarakaya89** [comment]
Reason, dmonitoring_model.keras is empty.  You should dowload model files again.

**Comment by ZwX1616** [comment]
this happens because TF2.2 requires tensor shape to be int only -- try 2.1 or 2.0?
future models won't have this problem.
