### ISSUE TITLE
Reason for /usr/bin/bash vs /bin/bash?

### ISSUE THREAD

**Issue by johschmitz** [commaai/openpilot#1681]
**Describe the bug**
Hello guys, just wanted to check out openpilot and get to the point to be able to run it on my Linux Machine. However I was immediately stopped by this issue. So here my question: what is your reason for having /usr/bin/bash instead of /bin/bash in your shell scripts? What distribution are you developing on? Would switching to /bin/bash be an option for you in order to increase compatibility?
I am willing to create a pull request for this but wanted to check with you first about the right approach.

**How to reproduce or log data**
Run launch.sh

**Expected behavior**
Shell scripts should run without modifications on commonly used Linux distributions.

**Device/Version information (please complete the following information):**
 - PC

**Additional context**
- Tested with Ubuntu/Linux Mint

**Comment by pd0wm** [comment]
The comma two/eon run NEOS, our own termux based OS. It doesn't have `/bin/bash`. You don't need to run launch.sh on the computer, you can just start `selfdrive/manager.py` directly and everything should work.
