### ISSUE TITLE
Getting "White Panda Is No Longer Supported" when running with Carla

### ISSUE THREAD

**Issue by johschmitz** [commaai/openpilot#1684]
**Describe the bug**
![image](https://user-images.githubusercontent.com/771979/84475959-b7120880-ac8d-11ea-8bdb-bc23df8fa80f.png)

**How to reproduce or log data**
Run openpilot with Carla as described here:
https://github.com/commaai/openpilot/tree/master/tools/sim

**Expected behavior**
It should drive in Carla.

**Device/Version information (please complete the following information):**
 - Device: PC
 - Version: 97b1ee25a7cff52216f5a1e8c5cb2b4b5847eba2

**Additional context**
-

**Comment by pd0wm** [comment]
https://github.com/commaai/openpilot/commit/6810333075694c9c72d3c689f05462f6e6565e88 should fix it.

**Comment by johschmitz** [comment]
I have the latest master branch including that fix but it doesn't seem to help.

**Comment by johschmitz** [comment]
Okay I just went through the whole process from scratch, including deleting the openpilot folder and the pipenv cache, and now I don't get the error anymore. Not sure why.
![image](https://user-images.githubusercontent.com/771979/84695076-8ca0a380-af4a-11ea-80ac-d98aac91c624.png)

What doesn't work though is speeding up. Documentation says
```
1: Cruise up 5 mph
2: Cruise down 5 mph
3: Cruise cancel
q: Exit all
```
But nothing happens.

**Comment by johschmitz** [comment]
Okay, apparently the keyboard polling thread is running as a part of the Carla bridge (bridge.py)
So the answer is to have the focus on the bridge.py terminal when pressing 1, 2, 3, q.
