### ISSUE TITLE
openpilot cycling between offroad and onroad a few times on startup when overheated

### ISSUE THREAD

**Issue by Hubblesphere** [commaai/openpilot#1687]
**Describe the bug**
Temporary dash error, switching between offroad/onroad while vehicle is running (Mid-day hot temps, C2 around 75 degrees C)

**How to reproduce or log data**
Start of this drive: f91c796ac0bf5eb6|2020-06-12--12-12-48--0

**Expected behavior**
Start overheated, maintain connection and engage once cooled down. 

**Device/Version information (please complete the following information):**
 - Device: [Comma Two]
 - Dongle ID: [f91c796ac0bf5eb6]
 - Version: [0.8 master-ci]
 - Car make/model [2019 Toyota Corolla Hatchback]

**Comment by pd0wm** [comment]
Can you make sure the drives are uploaded?

**Comment by pd0wm** [comment]
Looking at the qlogs the tempature of the device was about 80 C. When openpilot went onroad CPU temperature quickly spiked to over 107 C. We then go offroad to protect the CPU from overheating too much. The cpu temperature then probably dropped, we went onroad again and the cycle repeated. The solution would be to add hysteris to the `danger` thermal state so we don't go onroad when we risk overheating too much when we would do that.

**Comment by Hubblesphere** [comment]
I'll have drives uploaded later this afternoon. I sometimes don't have a good connection to upload at work. Sounds easy enough to fix!

**Comment by pd0wm** [comment]
https://github.com/commaai/openpilot/pull/1688

**Comment by pd0wm** [comment]
Merged a fix. Please let us know if you like the new behavior of cooling down before going onroad.

**Comment by Hubblesphere** [comment]
This issue is still occurring due to temp spike on startup: f91c796ac0bf5eb6|2020-06-22--13-25-34--0

More stable as it only happens once, but throws a dash error until it cools and comes back on road.
