### ISSUE TITLE
HKG Resume Bug

### ISSUE THREAD

**Issue by TK211X** [commaai/openpilot#1696]
![image](https://user-images.githubusercontent.com/33460783/84581707-2b45cc80-adb2-11ea-8e36-727acdce838d.png)

When using stock HKG SCC there is a 1 in 20 chance the ECU will fault and cancel SCC when OP sends resume command. It has come to my attention that this usually happens after OP sends a resume command multiple times but the lead vehicle creeps within 3.7 meters and the SCC logic does not resume because of this. I would try modifying the code so that it remains as is, but does not attempt to resume unless the lead vehicle distance is reported as more than 3.7 meters and increasing. This may help remedy the issue although it may not be the root cause. Sending resume at and below 3.7 Meters is pointless as SCC will not resume anyway.

Example logic:

ACC_ObjDist

Stationary at X.X climbs to 3.7 <--- DO NOT RESUME

Stationary at X.X climbs to 3.8 <--- SEND RESUME PAST 3.7 (3.8)

Stationary at 4.8 <--- DO NOT RESUME

Stationary at 4.8 then climbs <--- SEND RESUME ON INCREASE (Greater than 3.7)

**Comment by xx979xx** [comment]
I am not sure that I get everything but this change to [selfdrive/car/hyundai/carcontroller.py#L86](https://github.com/commaai/openpilot/blob/dbc609b240e598b06aec82c25d761d18d9c022ee/selfdrive/car/hyundai/carcontroller.py#L86) should help:
```
      elif self.last_lead_distance < CS.lead_distance > 4.8 and (frame - self.last_resume_frame) > 5:
```

**Comment by TK211X** [comment]
Wouldn’t it be:

S.lead_distance > 3.7

@xx979xx

**Comment by xps-genesis** [comment]
a res hit is valid for 2 seconds, if the lead starts to move, hit res(spam), then we hope the lead starts to move > 3.7m with in 2 sec. 

but right now we keep spamming as the lead distance keep changing.

**Comment by xx979xx** [comment]
@TK211X what about this:

> Stationary at 4.8 <--- DO NOT RESUME

I don't get it

**Comment by TK211X** [comment]
@xx979xx 

The SCC has stopped and the lead vehicle is at 4.8 in the example and not moving forward so we would not hit resume.

**Comment by TK211X** [comment]
The resume bug appears to be due to the parity bit.

**Comment by xps-genesis** [comment]
![image](https://user-images.githubusercontent.com/65239463/85884567-db530680-b7b0-11ea-86a1-7952aaf6360b.png)

**Comment by adeebshihadeh** [comment]
@xps-genesis is this not an issue on the community fork?

**Comment by xps-genesis** [comment]
i haven't seen this issue on the community branch. that said, this is a very random issue. so no idea if that change shown in the screenshot above really helps.
