### ISSUE TITLE
If no data, 'Finish Setup' shows after every drive

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/openpilot#1709]
**Describe the bug**
This happens when having no data during a drive. When that drive ends, the device forgets it's paired and needs to run through the process again.
https://www.youtube.com/watch?v=OP8vrl8xhcY

**Expected behavior**
Remember being paired and don't check if unpaired until fully connected to data again

**Comment by adeebshihadeh** [comment]
This will be fixed in the Qt UI.
