### ISSUE TITLE
Needed bounties;

### ISSUE THREAD

**Issue by AltonWells** [commaai/openpilot#173]
Toyota; 

86, Tacoma

Subaru; 

BRZ, WRX

**Comment by Capri2014** [comment]
do you consider adding mazda?

**Comment by bertramt** [comment]
If your vehicle isn't on the list of the top 10 cars sold in the last couple years, I wouldn't expect comma to place a bounty or put much effort into a port. The biggest problem is older cars lack the required drive by wire abilities that comma supports.  

At best you could rally a community bounty in the forums or slack channel.   See the [candidate vehicles](https://community.comma.ai/wiki/index.php/Candidate_Vehicles) page on the wiki for some guidance on what vehicles might be capable of self driving.  Visit #old_cars on the comma slack for discussions on older cars.

**Comment by bpanicker13** [comment]
Need a bounty for Highlander Hybrid

**Comment by andrewfree** [comment]
Is there any technical reason the new Subarus w/ eyesight would not work? Seems like a good one to add.

**Comment by geohot** [comment]
Bounty program is cancelled due to effort required to maintain and test safety of ports.
