### ISSUE TITLE
Show alert if fan is not spinning

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#1732]

**Comment by gordio** [comment]
Fan without control wire, so maybe control overheat and show warning?

**Comment by pd0wm** [comment]
The panda measures fan rpm. I was thinking an alert which shows if there is a command above 10% fan speed, but the rpm reads zero.

**Comment by kishkaru** [comment]
> The panda measures fan rpm

How does it do this?

> an alert which shows if there is a command above 10% fan speed, but the rpm reads zero.

This will be annoying for those of us with Noctua fan mod, and soldered directly to 5V rails on EON board.
If possible, maybe a way to disable the alert? Or else the end user will need to edit the code to disable the alert.

**Comment by LoganxDev** [comment]
I’m about to finish a first pass at this, what would be a good way to test this?

**Comment by pd0wm** [comment]
You could make a change to boardd to ignore the fan command.

**Comment by LoganxDev** [comment]
Sweet, I'll test it out tonight.

**Comment by LoganxDev** [comment]
Opened #2258 for this.
