### ISSUE TITLE
how to run openpilot manually to test my own code

### ISSUE THREAD

**Issue by YJCITA** [commaai/openpilot#1734]
I add ARS404 radar to openpilot/selfdrive/car/volkswagen/radar_interface.py, and I want to debug, so add logging, but everytime I change the code I should reboot tht EON, it can run the new code, but it takes times to restart the EON to run openpilot.
I try to run "launch_openpilot.sh" manually，but it may two openpilot code run on the EON  at the same time. I also try to kill the "manager.py" process manully, and run it again manuly, bug it deos not work well.
So I wonder how to run the openpilot manuly to terst my own code .
Thx

**Comment by adeebshihadeh** [comment]
This isn't an issue, a better place for questions like this is our [community discord](http://discord.comma.ai/).
