### ISSUE TITLE
ubloxd_main.cc : should be 'delete msg', not 'free(msg)'

### ISSUE THREAD

**Issue by deanlee** [commaai/openpilot#1742]
https://github.com/commaai/openpilot/blob/10cb6ab87ab812ada7c26d5b67d95a739d8d3b54/selfdrive/locationd/ubloxd_main.cc#L105-L107

@pd0wm 

btw, I'v submitted a PR for single SubSocket https://github.com/commaai/openpilot/pull/1716

**Comment by pd0wm** [comment]
Fixed! Saw your PR, still need to review it but like the cleanup.
