### ISSUE TITLE
Sound spamming as of Sound refactor (#1589)

### ISSUE THREAD

**Issue by csouers** [commaai/openpilot#1744]
**Describe the bug**
I'm getting spamming of the chimePrompt sound after this change.

**How to reproduce or log data**
In a sharp curve, the steer torque isn't sufficient. As the car wobbles as the curve straightens out, the sound continues to play over and over (sometimes without ever finishing before stopping the current one and then playing the next one).

**Expected behavior**
Sound should not repeat until the duration of the (sound) event has ended.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 95e637a323d6e9fc
 - Version: based on master-ci (f42af10b943400b617c4744cb0469db35920b451)
 - Car make/model: 2017 Civic Hatchback

**Comment by adeebshihadeh** [comment]
Fixed in 78b428e53441da339f8d13b78bfcf1f5ca192d6f
