### ISSUE TITLE
Older cars

### ISSUE THREAD

**Issue by EricTousignant** [commaai/openpilot#177]
I'm very interested in this technology and would love to know what you think is the oldest cars that could work?

I currently drive a Chevrolet Trax 2014 and was wondering what is the extent of the drive-by-wire possibilities.

Also, how good can this system be in the snow, when forward visibility is a challenge even for a human driver?

**Comment by bertramt** [comment]
[https://community.comma.ai/wiki/index.php/Candidate_Vehicles](https://community.comma.ai/wiki/index.php/Candidate_Vehicles)

There is also a #old_cars channel on the comma.ai slack that might be helpful.

**Comment by EricTousignant** [comment]
Thank you for the information.
