### ISSUE TITLE
Stuck on Starting Boardd

### ISSUE THREAD

**Issue by ahadcove** [commaai/openpilot#1796]
**Describe the bug**
I'm trying to run Debug Car Controls, and followed the Readme under tools/

When running boardd in the terminal it hangs at `Starting Boardd`

**How to reproduce or log data**

PARAMS_PATH=persist/params selfdrive/boardd/boardd

**Expected behavior**

Boardd to start running

Operating system: Ubuntu 16.04

**Comment by adeebshihadeh** [comment]
Both debug_controls.py and boardd must be running in order for boardd to start. boardd blocks on CarParams, which debug_controls.py writes.
