### ISSUE TITLE
how to support Honda FIT?

### ISSUE THREAD

**Issue by 9crk** [commaai/openpilot#181]
as a young man ,you know, FIT is so popular.
here is my Questions about supporting FIT:

1.can the autopilot work without radar?
2.can the OBD control the steeling wheel on FIT? if not, what if I design a motor to control the steeling wheel ?
3.can the autopilot software be installed on most of the mobile phones?what's the hardware requriement?

**Comment by bugsy924** [comment]
https://community.comma.ai/wiki/

**Comment by vanillagorillaa** [comment]
1. Not currently. ACC with Radar is needed until Vision Only support is added.
2. Does the car have EPS? On most Honda's steering only occurs from the LKAS camera and not OBD2
3. The OnePlus 3/t is the only supported hardware for OpenPilot

**Comment by jfrux** [comment]
#266
