### ISSUE TITLE
joystickd not working, transmit buffer full, output errors

### ISSUE THREAD

**Issue by codename224** [commaai/openpilot#1816]
Trying to run joystickd.py in tools to get my steering wheel moving. Following the directions in the tools readme leads to transmit buffer full messages, and output errors. See screenshot below. 

![errors](https://user-images.githubusercontent.com/4961059/86519492-23e17400-bdf0-11ea-9629-86a7530576bc.png)

**Comment by dorkmo** [comment]
did you get it working?

**Comment by codename224** [comment]
> did you get it working?

I did not, I’ve abandoned the project. There have been some significant changes in OP code recently that make this issue outdated.
