### ISSUE TITLE
openpilot EON screensize right side keyboard mapped off screen

### ISSUE THREAD

**Issue by kmacpher67** [commaai/openpilot#182]
https://plus.google.com/+kenmacpherson/posts/QbUeAeNuxKT
upgrade EON to openpilot 0.4.0.2 and keyboard screen gets pushed aside

From the Comma.ai main screen, click "Log in" and google sign in page appears.
click focus into email/phone number field 
keyboard right of the letter "K" is forced off the screen, looks portional to left hand nav.

**Comment by bugsy924** [comment]
Known issue on initial setup
Reboot EON to load small keyboard

**Comment by kmacpher67** [comment]
I was just coming here to post. 
REBOOT DOES NOT DO IT. 
SHUTDOWN. LOL. 
I did a reboot before posting this too. 
Sorry. 
Funny, that the shutdown basically does a reboot. I wonder if it needs to be done twice. 
Anyrate, log in works! Now on to getting my Linux laptop enabled.
