### ISSUE TITLE
Can we able to run any of the openpilot module in Linux

### ISSUE THREAD

**Issue by sainisanjay** [commaai/openpilot#1828]
can we able to run any openpilot module in Linux by fetching or reading the images from in-build laptop Webcam or external camera?
Further, i have Qualcomm 855 board, can i run visiond on thats board? if yes may i know how?

**Comment by pd0wm** [comment]
yes, https://github.com/commaai/openpilot/tree/master/tools/webcam

yes, use SNPE for the 855.

**Comment by sainisanjay** [comment]
Thanks @pd0wm, could you help me run on 855. 
I have 855 board with camera, SNPE SDK, please guide me with steps that i have to followed.

**Comment by adeebshihadeh** [comment]
Closing as this isn't an issue. The documentation for running on other platforms besides EON/comma two is currently the webcam README linked above.
