### ISSUE TITLE
is there any schdule about vehicle base on "MLB"

### ISSUE THREAD

**Issue by YJCITA** [commaai/openpilot#1835]
I  see the comment "PQ35/PQ46/NMS, and any future MLB, to come later.", is there any new message about it?
Audi Q5L is based on MLB, if it is possable tp  use OP?
Thx

**Comment by jyoung8607** [comment]
MLB vehicles (the VW Touareg and the entire Audi line except A1/A3) use FlexRay. Comma have performed some limited experiments (see the [Audi Q8 medium article](https://medium.com/@comma_ai/hacking-an-audi-performing-a-man-in-the-middle-attack-on-flexray-2710b1d29f3f)) but at this time we unfortunately we don't have supportable hardware or plans in that direction.
