### ISSUE TITLE
Build standalone binaries in CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#1850]
Build updater, text window, etc. in CI and push with master-ci instead of checking them in.

**Comment by adeebshihadeh** [comment]
On second thought, this isn't really possible since these binaries may be needed before  openpilot starts building. For example, if the updater and NEOS version are changed in the same release, the NEOS install would happen with the old updater.

Instead, they should be re-built in CI and tested against the checked-in binaries to see if they are update to date with the source files.

**Comment by whowe444** [comment]
Where do the checked-in binaries get built and how can I build them?
