### ISSUE TITLE
Error; Driver model lagged

### ISSUE THREAD

**Issue by adam-nelson** [commaai/openpilot#1868]
**Describe the bug**

Engaging openpilot causes master error driver model laggged

**How to reproduce or log data**

Engage openpilot and wait 30 seconds before error appear

**Expected behavior**

N/A

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: 18e8ac91b805db11
 - Route: 18e8ac91b805db11|2020-07-11--18-36-12--354
 - Version: master-ci 0.7.7-release
 - Car make/model:Toyota corolla Hybrid 2020 hatchback Right hand drive

**Additional context**

Error happen pretty consistently every 10 seconds before i disengaged. Testing the master-ci branch because of an another error that was fixed

I did the same pass of road on Thursday night - 18e8ac91b805db11|2020-07-09--18-57-53--172
No error

**Comment by adam-nelson** [comment]
Just checking if this is new bug or old bug?

**Comment by xps-genesis** [comment]
i have had similar experience during a recent short trip. only with on a reboot of comma, it made it happy for the rest of the trip or the alert would come one consistently for every 5-10seconds of op engagement

**Comment by pd0wm** [comment]
Should be fixed by https://github.com/commaai/openpilot/commit/58c3b5ba84f6c3da3c660770148cea98c708fce5. Feel free to reopen an issue if you still get too much of these warnings.
