### ISSUE TITLE
2017 Prius auto high beam missing

### ISSUE THREAD

**Issue by hailite** [commaai/openpilot#187]
After enabled OP, all other functionalities work  fine, good job! However, auto high beam functionality is missed.

**Comment by mwkrieger** [comment]
I saw this on my Honda as well. Turns out, the sensor is in the rearview mirror, so of your EON is blocking that sensor, or you've removed the rearview mirror - your auto high beams won't work.

**Comment by hailite** [comment]
@mwkrieger I turned on rearview mirror, but auto high beam still didn't work.

**Comment by csouers** [comment]
Incorrect. The camera provides auto high beam functionality on Honda, likely on Toyota as well. The sensor on the back of the mirror is for auto-dimming rear view mirror only. If you power off the camera through giraffe, you lose auto-high beam functionality. Retaining it would require message forwarding and keeping the camera alive.

**Comment by billy2kool** [comment]
I have a 2016 Honda Accord touring and I think your right.  But is there anyone working on touring.

**Comment by chandroos** [comment]
@csouers, is there a way you can retain the power to the camera? Any panda settings?

**Comment by bitshop** [comment]
Is the camera just sending something to say it sees light or doesn't? We can likely simulate AHB with a bit of modeling...

**Comment by arne182** [comment]
I would like to work on this after I have finished with the blindspot sensors. I assume it will be similar. The same problem exists on the RAV4 Hybrid.

**Comment by mtourangeau** [comment]
Is there a way I can help? I'm not famillialr with linux that's why I didn't fix any problem yet. If you can help me setting up the debugging environment on Windows, I'll help to fix this problem. I already install Visual Studio Code but I don't know how to debug python scripts.

**Comment by arne182** [comment]
Capturing auto high beam events would help. Set the stock adas on and drive
at night over 40km/hr with the AHB on. We need to find out which can
message is being sent. You could search through the messages with cabana or
share the drives where the events occurs.

Mathieu Tourangeau <notifications@github.com> schrieb am Mo., 28. Mai 2018,
16:28:

**Comment by mtourangeau** [comment]
Perfect. I'll do that.

**Comment by mtourangeau** [comment]
How do I record my drive if I use dip switch 1101? OpenPilot will not record my drive with this setting. Should I use 0101 for procy stock adas w/ panda?

**Comment by andy867** [comment]
The panda will still be recording all the can messages. Are you using comma power by chance?

**Comment by mtourangeau** [comment]
Can I use Chffr on iPhone connected to my panda to capture code?

**Comment by mtourangeau** [comment]
I think I have what you need. Here it is:
https://community.comma.ai/cabana/?route=96515cca9b5ce486|2018-05-29--22-30-25

**Comment by mtourangeau** [comment]
I can't find the CAN message with the link I provided... :(

**Comment by mtourangeau** [comment]
I'm using eon with panda and Giraffe. But for the recording, I connected my panda to the standard odbii port, install Chiffr app on iPhone, connect the Chffr app to the wifi panda's and record my drive. Did it works?

**Comment by arne182** [comment]
You need to use the "copy share link" button. If you could also give the
time at which the ahb come on and off that would be good

Mathieu Tourangeau <notifications@github.com> schrieb am Mi., 30. Mai 2018,
04:46:

**Comment by mtourangeau** [comment]
https://community.comma.ai/cabana/?route=96515cca9b5ce486%7C2018-05-29--22-30-25&max=3&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F96515cca9b5ce486%2F6d435809c4dee8a0598bbae5e7c2c48a_2018-05-29--22-30-25

at 8 seconds the high beam come ON
a 14 seconds the high beam come OFF

**Comment by arne182** [comment]
It should be working now on my branch. AHB

**Comment by hailite** [comment]
@arne182 Are you able to send a PR? Thanks.

**Comment by arne182** [comment]
The fix is so easy and thanks to wocsor and otherchase I could. The fix has a caveat.
 It requires a 120ohm resistor on pins 12 and 13 of your panda. Then enable message forwarding in panda firmware and remove static values for camera.

**Comment by bitshop** [comment]
Resistor because we need to terminate the CANBUS? If so we should make a 
plug in connector with M/F plugs and resistor in between so no soldering is 
required.

Steve Radich

**Comment by arne182** [comment]
Yes. Termination is needed. Sounds nice. For now I just have it jammed into my giraffe and the Panda forced in. It does not even look that bad.

**Comment by arne182** [comment]
Pull request done. https://github.com/commaai/openpilot/pull/411
Test and comment.

**Comment by vanillagorillaa** [comment]
added this functionality in 0.5.6. Closing

**Comment by arne182** [comment]
Requires 120ohm resistor but all the information is in the pull request. What is up with the massive cleanup vanillagorillaa?
