### ISSUE TITLE
2020 Hyundai Kona

### ISSUE THREAD

**Issue by hitmantw25** [commaai/openpilot#1883]
I am just wondering if this will work. It is the ultimate version so it has SSC and LKAS. I would like to know if it will work before buying a comma 2 device. If anyone could help me with this I would really appreciate it.

Thank you all for your time!!!

**Comment by adeebshihadeh** [comment]
This isn't an issue, please see the [supported cars section of the README](https://github.com/commaai/openpilot#supported-cars).

**Comment by hitmantw25** [comment]
Well I see that the 2019 is on the list but not the 2020? Will the new comma 2 have the right fingerprint for the 2020 version?
