### ISSUE TITLE
2020 Hyundai Kona

### ISSUE THREAD

**Issue by hitmantw25** [commaai/openpilot#1884]
So in the previous post #1883 I had one more question and didn't know if anyone sees anything after it is closed.

So here was my question?

Well I see that the 2019 is on the list but not the 2020? Will the new comma 2 have the right fingerprint for the 2020 version of the Kona?

I just want to make sure its going to work before spending the money for a comma 2.

Thanks again for everyone's time!!!

**Comment by VirtuallyChris** [comment]
Support for vehicles not on our supported car list ( https://github.com/commaai/openpilot#supported-cars ) will come through community contributions. I would suggest checking out our community discord ( discord.comma.ai ) where users there can help point you in the right direction for adding support for your vehicle. Please post in your make’s channel (ie. #Toyota or #Honda)
