### ISSUE TITLE
What is needed for full stop and go ACC in a Honda Ridgeline

### ISSUE THREAD

**Issue by johhansantana** [commaai/openpilot#1900]
Hello, I just found this project and saw the table for the supported vehicles. The Ridgeline in this table says that

No ACC accel below 

And the value is 25mph. What does this actually means? The regular ACC in the Ridgeline I believe stops working below this speed. Is this the same with openpilot? If so, what would be the benefits of installing openpilot and or how could I acquire full stop and go ACC in a Ridgeline?

**Comment by vanillagorillaa** [comment]
Please see note one which is appended to the Ridgeline No ACC below speed and can be found at the bottom of the supported vehicles list.
