### ISSUE TITLE
Camera not focusing. 

### ISSUE THREAD

**Issue by drbeers** [commaai/openpilot#1913]
Camera is blurry.  When comma engaed keeps saying take control,  trying to auto focus camera.  Makes device unusable.

**Comment by pd0wm** [comment]
Can you fill out the bug report template? At least we need your dongle ID and a drive where this happened.

**Comment by techasit14607** [comment]
Let's go!

**Comment by drbeers** [comment]
Thursday July 23rd 9am towards the beginning when on freeway.

Is that the device id at the bottom of the picture attached?

**Comment by adeebshihadeh** [comment]
Closing due to insufficient information. Feel free to reopen after filling out all the information in the bug report template, or in this case contact support as it may be a hardware issue.
