### ISSUE TITLE
dark screen only can see the menu/settings

### ISSUE THREAD

**Issue by cheta48** [commaai/openpilot#1920]
screen black no road. checked all connection and everything looks fine. please help. thanks

**Comment by techasit14607** [comment]
Help fix it.

**Comment by techasit14607** [comment]
Open camera.

**Comment by cheta48** [comment]
Only can see the menu/setting. No pic of road

**Comment by adeebshihadeh** [comment]
Closing due to insufficient information. Feel free to reopen after filling in all the information in the bug report template.
