### ISSUE TITLE
Add missing Hyundai test routes

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#1929]
Each route should be at a least a few minutes with stock openpilot engaged. Comment a route with the model of your car.

* [x] HYUNDAI.HYUNDAI_GENESIS
* [ ] HYUNDAI.ELANTRA
* [ ] HYUNDAI.ELANTRA_GT_I30
* [ ] HYUNDAI.GENESIS_G80
* [ ] HYUNDAI.GENESIS_G90
* [ ] HYUNDAI.KIA_FORTE
* [x] HYUNDAI.KIA_OPTIMA
* [ ] HYUNDAI.KIA_OPTIMA_H
* [x] HYUNDAI.KIA_SORENTO
* [x] HYUNDAI.KIA_STINGER
* [x] HYUNDAI.KONA
* [ ] HYUNDAI.KONA_EV

**Comment by xps-genesis** [comment]
Add these to list

HYUNDAI.KONA_HEV,
HYUNDAI.GRANDEUR,
HYUNDAI.GRANDEUR_HEV,
HYUNDAI.KIA_NIRO_HEV,
HYUNDAI.SONATA_H,
HYUNDAI.KIA_CADENZA,
HYUNDAI.KIA_CEED,
HYUNDAI.KIA_CADENZA_HEV,
HYUNDAI.KIA_SPORTAGE,

**Comment by adeebshihadeh** [comment]
Those don’t need to be added since we don’t currently support them. They simply won’t be merged in until we have a test route.

**Comment by xps-genesis** [comment]
i am a little confused, because people will not run the default stock release from comma since the vehicles are not supported. so we may find it even more difficult to get routes of the new vehicles running stock.

let me know what you think.

**Comment by adeebshihadeh** [comment]
Before any new model gets merged in, someone with the car has to test the branch that we intend to merge in. The route they used to test it can serve as the test route.

**Comment by xps-genesis** [comment]
KONA and OPTIMA route details added

**Comment by adeebshihadeh** [comment]
Moved to #978
