### ISSUE TITLE
v0.8.1 Japan model 2021 RAV4 Hybrid G TSS2 CAN error

### ISSUE THREAD

**Issue by bcredford** [commaai/openpilot#19516]
**Describe the bug**
On rav4-fw branch due to fingerprint conflict on Japanese 2021 Toyota RAV4 Hybrid G. Installation triggers multiple dashcam alarms and displays CAN error: check connections on Comma 2 UI and openpilot inoperational. tmux -a following installation reboot provides continuous "transmit buffer full" 

**How to reproduce or log data**
tmux -a in ssh following installation using the following syntax: cd /data && rm -rf openpilot && git clone -b rav4-fw https://github.com/commaai/openpilot && cd openpilot && git submodule init && git submodule update && reboot

**Expected behavior**
Comma 2 should install normally and interface with car controls without triggering errors.

**Device/Version information (please complete the following information):**
 - Device: COMMA 2
 - Dongle ID: 1415021230d7c15a
 - Route:
 - Timestamp: 
 - Version: rav4-fw branch v0.8.1
 - Car make/model: Japan model 2021Toyota RAV4 Hybrid G

**Additional context**
tmux files attached
[tmux_after_rav4-fw_git_upload_japanese_Try1 rav4_installed only dashcam first then uninstalled dashcam after update.log](https://github.com/commaai/openpilot/files/5700297/tmux_after_rav4-fw_git_upload_japanese_Try1.rav4_installed.only.dashcam.first.then.uninstalled.dashcam.after.update.log)
[tmux_after_rav4-fw_git_gupdate_FAIL multiple dash errors_community features on.log](https://github.com/commaai/openpilot/files/5700298/tmux_after_rav4-fw_git_gupdate_FAIL.multiple.dash.errors_community.features.on.log)
[tmux_after_rav4-fs_git_upload_japanese_rav4_TRY2_FAIL_MultDashAlarm_turned off community features before first reboot for make build.log](https://github.com/commaai/openpilot/files/5700299/tmux_after_rav4-fs_git_upload_japanese_rav4_TRY2_FAIL_MultDashAlarm_turned.off.community.features.before.first.reboot.for.make.build.log)
[tmux_values.py_update fingerprint line 77 only.log](https://github.com/commaai/openpilot/files/5700300/tmux_values.py_update.fingerprint.line.77.only.log)

**Comment by VirtuallyChris** [comment]
please properly fill out the bug report template

**Comment by bcredford** [comment]
Didn't see template. What additional info does it need?

Brian Redford



________________________________

**Comment by VirtuallyChris** [comment]
You'll see it when you go to create a bug report. It has a template to fill out.

**Comment by VirtuallyChris** [comment]
want to try master-ci again?

**Comment by adeebshihadeh** [comment]
Verified with one of your routes that your car now correctly fingerprints. If you switch to master-ci, your device will recognize the car correctly.

**Comment by bcredford** [comment]
Oops just replied to Chris's email. Master-ci not working for me. Getting a txmt buffer error on tmux a.
________________________________

**Comment by bcredford** [comment]
Still getting can error on master-ci and transmit buffer full error on tmux a. Got a video if you have somewhere to drop. 183mb.
________________________________

**Comment by bcredford** [comment]
Why did you close this? The issue isn't resolved.
________________________________

**Comment by bcredford** [comment]
Thank you
________________________________

**Comment by VirtuallyChris** [comment]
had a bad USB-C cable. good to close.
