### ISSUE TITLE
Rega Hawlery here

### ISSUE THREAD

**Issue by regamask** [commaai/openpilot#19519]
**Describe the bug**

**How to reproduce or log data**

**Expected behavior**

**Additional context**

Operating system: [e.g. Ubuntu 16.04]

**Comment by regamask** [comment]
![image](https://user-images.githubusercontent.com/75854414/102351255-2fe47b00-3fb7-11eb-9d33-bf8225d23c27.jpeg) regarding hawlery

**Comment by Liverpoolj** [comment]
Hey still don't understand what I need to do
