### ISSUE TITLE
OP stopped tracking lead semi

### ISSUE THREAD

**Issue by abdulrahman004** [commaai/openpilot#19539]
OP detects lead semi; but as I get closer it has a hard time detecting semi. May be bigmodel will help ?

Expected behavior
OP should continue to track lead semi

Device: FreEon
Dongle ID: 59f457ce47259dd2

Route: 59f457ce47259dd2|2020-12-17--02-21-51--25
Timestamp: 18:47:35
Version: 0.8.0-release-2
Car make/model: Toyota Sienna 2018
Additional context
gif of the report
https://imgur.com/a/7RE9XzN

have another report about lead car detection. OP tracks stopped lead car; however for some reason it thinks the car is switching lanes and starts to draw a new path around lead vehicle and doesnt track lead car . Later sees that there is no adjacent lane and re-draws path correctly and detects lead car again

Route: 59f457ce47259dd2|2020-12-17--02-21-51--15
Timestamp: 18:36:53
Version: 0.8.0-release-2
Car make/model: Toyota Sienna 2018
Additional context
gif of the report
https://imgur.com/a/TbJQ9s3

**Comment by HaraldSchafer** [comment]
Not really relevant anymore because this model is now old. We are working on better lead detection tests though!
