### ISSUE TITLE
Car unrecognized Toyota Highlander 2019 

### ISSUE THREAD

**Issue by grevg** [commaai/openpilot#19543]
**Describe the bug**

After installing comma two and connecting the display says Dashcam mode Car unrecognized 

**How to reproduce or log data**

**Expected behavior**

This model is in the list of supported, so I ordered from online shop comma.ai

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 922bcfdc7c1e117d
 - Route: 922bcfdc7c1e117d |2020-12-19
 - Timestamp: [19 December 
 - Version: 0.8
 - Car make/model: Toyota Highlander 2019 safety sense  US manufacturing for  Russian market 
 - Engine is down forced to 249hp, unlike US version 

**Additional context**

**Comment by adeebshihadeh** [comment]
Fingerprinted added in d6caca943308ff96c96f6750cb7763f577240925. If you switch to master or master-ci, your car should now be recognized.

**Comment by grevg** [comment]
> Fingerprinted added in [d6caca9](https://github.com/commaai/openpilot/commit/d6caca943308ff96c96f6750cb7763f577240925). If you switch to master or master-ci, your car should now be recognized.

Thanks for fast fix.
How do I switch to master? I have v 0.8.0 automatically installed from setup process.
