### ISSUE TITLE
OP gets confused with a sudden exit ramp and almost crashed into a divider

### ISSUE THREAD

**Issue by aeykaygee** [commaai/openpilot#19586]
**Describe the bug**

While driving on a freeway, behind a lead car, OP got confused by an exit ramp. It stopped following the lead car to instead almost took the exit. I had to take control to bring it back on the road. Had I not done that I would have most ceratainly crashed into the divider.

**How to reproduce or log data**

This probably needs a very specific road condition to reproduce. See the video.

**Expected behavior**

I would expect OP to continue following the lead car and not take the exit in this case

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 3c946decd6bc40b9
 - Route: [e.g. 1608744542638/1608748144744 (link to segment: https://my.comma.ai/3c946decd6bc40b9/1608744542638/1608748144744 
 - Timestamp: Dec 23 10:16:57
 - Version: release2 0.8
 - Car make/model: 2020 Chrysler Pacifica

**Additional context**

**Comment by HaraldSchafer** [comment]
This isn't really caused by a specific bug, just the model misunderstanding the scene. This should get better as the model improves. Thanks for the report!
