### ISSUE TITLE
Supported ECU's 

### ISSUE THREAD

**Issue by samimoftheworld** [commaai/openpilot#1959]
I am actually looking to make a self-driving electric car prototype to showcase as a project in a tech-fest next year. I was wondering for comma two devkit is there a list of compatible Electric Car ECU's and Camera systems to look at to integrate the car with the devkit?

**Comment by adeebshihadeh** [comment]
We don’t test or support ECUs individually, but users on our discord have successfully retrofitted actuators on old cars
