### ISSUE TITLE
OP recognizes asphalt patch as a lead car and brakes at highway speed

### ISSUE THREAD

**Issue by petschekr** [commaai/openpilot#19617]
**Describe the bug**

When driving on a freeway in daylight with brand new asphalt laid in interrupted portions of the right half of the lane, OpenPilot detects the contrast between new and old asphalt as a stopped lead car and begins to brake harshly.

**How to reproduce or log data**

Seems to be caused by very specific conditions but this bug was reliably triggered 5 or more times in a construction zone on I-26 during a recent drive. I had to take manual control for ~4 minutes until the strips of contrasting pavement stopped appearing.

**Expected behavior**

No phantom lead car should be detected and braking commands should not be sent to the car

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: `28241175c05b4fbc`
 - Route: `28241175c05b4fbc|2020-12-27--07-55-27--61`
 - Timestamp: 27 Dec 2020 beginning at `08:56:15` (timestamp `3650` in cabana shows brake application) and again at `08:57:04`
 - Version: `release2-staging` (`0.8.1`)
 - Car make/model: 2020 Toyota RAV4 Hybrid

**Additional context**

Imgur GIF of one of the stretches of road that causes this: https://imgur.com/a/pKNfCKq

**Comment by HaraldSchafer** [comment]
Thanks for the report, the ground truth for these cases is good, so this just the model making a mistake. Should improve as we improve the model all-round.
