### ISSUE TITLE
BSM Lane Change Fault

### ISSUE THREAD

**Issue by cowanhm** [commaai/openpilot#19623]
**Describe the bug**

2021 RAV4. The Lane Change BSM has a fault scenario. This vehicle has a “BLINKING” lane change marker that may allow BSM to NOT override the Lane Change Assist, depending on instantaneous status of signal when turn signal is turned on. 

**How to reproduce or log data**

Activate lane change while OP is engaged. If a vehicle is present or approaching, the “blocked” message comes up on C2 Screen and OP prevents lane change. Once in awhile, the BSM Light on side-mirror appears to BLINK and vehicle starts lane change despite another vehicle being in blind spot. 

**Expected behavior**

The vehicles BSM status should prevent lane change, even when side-mirror indicator blinking a warning.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: e346693d5b95a02f
 - Route: https://my.comma.ai/cabana/?route=14b218baa26b0ebd%7C2020-12-30--19-08-07&exp=1640910369&sig=oFZ6%2FlxvNqUbhAA11InY9wxnRmifvAtBByv2byUqg%2Fs%3D&max=3&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F14b218baa26b0ebd%2Ffef299cdaf7f0f1d294776fff0d96974_2020-12-30--19-08-07
 - Timestamp: 67
 - Version: 0.8.1 master 
 - Car make/model: 2021 RAV4 TSS 2.0  (toyota_nodsu_hybrid_pt_generated.dbc)

**Additional context**

**Comment by cowanhm** [comment]
A minimum (0.5sec?) lockout delay upon blindspot-detect should solve issue.

**Comment by cowanhm** [comment]
![BSM_FAIL](https://user-images.githubusercontent.com/15847404/103388435-02c7ba80-4ad7-11eb-9b55-9ca04ac06798.png)

**Comment by pd0wm** [comment]
Is there another bit that signifies the blinking state?

**Comment by pd0wm** [comment]
Is it actually blinking or just losing track of the car for a little bit?

**Comment by cowanhm** [comment]
After looking for the other bit, now I’m agreeing that it’s probably just losing and regaining. The physical light on the car appears to be a three state. Off,  Solid, or R Rapid Blinking. 

 It’s a little difficult to test... because it may scare people when I turn on the signal when they’re in my blind spot.

Thanks,
Cowan Moore
330-701-3922

**Comment by cowanhm** [comment]
This discusses that third blinking state.  BSM light will blink if there’s a car in the Blindspot, and the turn signal is activated in that direction. I’ll try to re-simulate it this morning and send you the cabana



Thanks,
Cowan Moore
330-701-3922

**Comment by pd0wm** [comment]
Thanks! My feeling it's just losing the car. Not sure if we want a cooldown on the signal, that could be annoying if you try to change lanes right after a car passes you.

**Comment by ps11918** [comment]
Even 1 second delay could be helpful...   the BSM appears to fully deactivated prior to passing car being fully passed.

**Comment by cowanhm** [comment]
Even 1 second delay could be helpful... the BSM appears to fully deactivate prior to passing car being fully passed.

**Comment by adeebshihadeh** [comment]
I don't think we should be writing hacks like this to overcome deficiencies in the car's built in BSM. These delay values may not be consistent between models in a make.
