### ISSUE TITLE
Auto Update Fails While Connected Online - OP Disengages

### ISSUE THREAD

**Issue by praxis-alpha** [commaai/openpilot#19665]
Auto update fails to update, message remains "Connect to the internet to check for updates. Open pilot won't engage". Comma two unit is connected online via android wifi 2.4/5G tether

Unistall and reinstall of comma ai does not remedy the issue.

Restarting is a temporary work around for the current trip.

This issue has been occurring for months and multiple revisions.

Could a manual "Check for updates option be added"? Or adjustment of update check interval, if that is the issue?

Comma Two Stock v0.8.0-release
Honda Civic 2016 Trng 

I've had this issue for months with multiple versions, is this an ongoing bug? (edited

**Comment by adeebshihadeh** [comment]
Closing since no relevant information was provided. Feel free to reopen after filling out the bug report template.
