### ISSUE TITLE
PyJWT 2.0.0 does not return bytes for encode()

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#19776]
calling `jwt.encode(...).decode('utf-8')` on pyjwt 2.0.0 and higher throws an error because `jwt.encode(...)` returns a `str` now instead of `bytes` (and Pipfile was updated to pyjwt 2.0.0)
https://github.com/commaai/openpilot/blob/def24ae27ad4cd5948731770745d5039f20ffcf2/Pipfile.lock#L613-L620
if tests didn't catch this, we should probably add one!
https://github.com/commaai/openpilot/blob/def24ae27ad4cd5948731770745d5039f20ffcf2/common/api/__init__.py#L30

**Comment by ShadyD45** [comment]
can we fix this by converting the return value of `encode()` to bytes using `bytes()` instead of decode and then return the resulting value which is in `bytes` ? 
Something like this:  `return bytes(jwt.encode(payload, self.private_key, algorithm='RS256'), 'utf8')` 
Should I open a PR?
