### ISSUE TITLE
Put pending bootlog uploads at the front of the queue

### ISSUE THREAD

**Issue by Jon8RFC** [commaai/openpilot#19796]
They're very small in comparison to everything else.  Regardless of the timestamps, the bootlogs seem to be placed at the end of the queue and behind all routes, in all circumstances.

For situations like sharing a bug report where the bootlogs are necessary, it would be much more convenient to have the tiny bootlogs always upload first instead of uploading gigs of routes for multiple days when the small bootlog from 10 minutes ago is what's wanted.

**Comment by pd0wm** [comment]
I'm already working on this! They will also be put in their own folder instead of a separate route.

**Comment by Jon8RFC** [comment]
@pd0wm Will the bootlogs be permitted to upload over cellular/comma prime as well?  As far as I can tell, they will only upload over wifi.

**Comment by pd0wm** [comment]
Yes. They will be put in a special folder, and uploaded with the qlogs. (Same as crashlogs https://github.com/commaai/openpilot/blob/master/selfdrive/loggerd/uploader.py#L61)

**Comment by Jon8RFC** [comment]
Wow, thanks for this! This will be very helpful.
