### ISSUE TITLE
Model: Lane changes overshooting and correcting

### ISSUE THREAD

**Issue by actuallylemoncurd** [commaai/openpilot#19865]
**Describe the bug**

When I was on the highway going 65mph, I went to change lanes. After crossing the lane markers i turned my turn signal off (though I've tested this with keeping it on and off for lane change, same affect) OpenPilot proceeded to go almost until the shoulder line, then correct into the center of the lane

**How to reproduce or log data**

Go on highway
Change lanes at around 65, may happen at other speeds but  I was going 65

**Expected behavior**

To change lanes into the center of the other lane, not go to the gutter

**Device/Version information (please complete the following information):**
 - Device: Freon, leeco, grey panda
 - Dongle ID: 579dad05095e1b3e
 - Route: 579dad05095e1b3e|2021-01-21--02-55-24
 - Timestamp: Around 8-9 mins into the drive when i get on the highway
 - Version: https://github.com/actuallylemoncurd/openpilot/tree/0c40b224f4dc85bdec110867b458719c09e34fdb
 - Car make/model: 2013 Volkswagen Jetta Sportwagen TDI

**Additional context**

None afaik

**Comment by RCoaster** [comment]
The same thing is happening in 0.8.1, only to the left. Changing lanes to the right works as intended.

**Comment by actuallylemoncurd** [comment]
initially i only noticed it going to the right, then i kept testing and it started happening on both

**Comment by C0mpl3t3N00b** [comment]
Still happening even on v0.8.2 (latest master-ci from 1/28/2020):

bdad50b8a1f9fa8e|2021-01-28--19-57-49--7

**Comment by HaraldSchafer** [comment]
linked to https://github.com/commaai/openpilot/issues/2596
