### ISSUE TITLE
openpilot not working

### ISSUE THREAD

**Issue by billy2kool** [commaai/openpilot#199]
Open pilot not working on 2016 Honda Accord touring.   Is there anyone working on it

**Comment by vanillagorillaa** [comment]
@billy2kool I don't believe that there is anyone specifically working on the 16 accords. These models use a different protocol to communicate on the bus. To my knowledge nobody has started working on it

**Comment by vanillagorillaa** [comment]
Can I personally work on it? No, I don't have access to a car or knowledge, but you can. Even if you downgraded that wouldn't do anything as having just the fingerprint wouldn't do you any good. To update simply reboot your EON

**Comment by billy2kool** [comment]
Ok thank you
