### ISSUE TITLE
Red line on median 

### ISSUE THREAD

**Issue by hondacm450e** [commaai/openpilot#19940]
Hey. Red line half way up median. not sure if that’s a pencil issue. 
![B95FC3A5-54FB-473D-9F7A-18306C2F07E5](https://user-images.githubusercontent.com/45337027/106051967-19056e00-60b7-11eb-80b1-b068cd117902.jpeg)

**Comment by VirtuallyChris** [comment]
I'll close this issue for now. We know the road edges aren't that accurate on the current model, and we are training a new segnet for 0.8.2. Feel free to reopen the issue once we have the new model.

**Comment by davetapley** [comment]
@VirtuallyChris are these road edge red lines still something of interest, or not since laneless is taking over?
