### ISSUE TITLE
OpenPilot unavailable  in simulation when trying to run it with carla

### ISSUE THREAD

**Issue by mahbub-iut** [commaai/openpilot#19969]
I've been trying to test Open Pilot using start_carla.sh and start_openpilot_docker.sh   scripts to run the simulation on a ubuntu 20.04 machine.. But when I try to engage pressing 1 the UI shows 

"OpenPilot Unavilable
System Malfunction:Reboot Your Device"

And when I initially pressed 1 to engage Open Pilot I got the message in Terminal **CarControl: Reader was evicted, reconnecting**

I don't see any other error and have no clue how to resolve this issue

**Comment by grekiki** [comment]
I would recommend asking around the discord simulation channel, we are aware that the simulator may not be most stable at the moment.
