### ISSUE TITLE
LKAS fault: Restart car to engage

### ISSUE THREAD

**Issue by atstevenha** [commaai/openpilot#1996]
**Newly installed Comma 2 for a 18 Grand Cherokee with adaptive cruise. Once installed and connections checked. The screen keeps reading LKAS fault. It seems like signal triggers or slow speeds. Please help. **

**Comment by adhintz** [comment]
If you only engage OpenPilot when you're going more than 39mph do you still see the LKAS faults?

**Comment by atstevenha** [comment]
> If you only engage OpenPilot when you're going more than 39mph do you still see the LKAS faults?

I can't even engage actually. Hasn't work since I've install it.

**Comment by atstevenha** [comment]
![20200807_200039](https://user-images.githubusercontent.com/69372760/89698791-b04bee80-d8e8-11ea-8ff7-23ac8d91a696.jpg)

**Comment by cydia2020** [comment]
Seems to be the dashcam version, install openpilot during setup by choosing custom software, and type https://openpilot.comma.ai in the address bar.
