### ISSUE TITLE
Checks for variable mismatches between values.py and other files (and/or a more informative error message)

### ISSUE THREAD

**Issue by Jon8RFC** [commaai/openpilot#19979]
I found that my values.py file didn't copy over, so I was stuck with the default.  I was shown "openpilot unavailable waiting for controls to start".

I was able to reliably reproduce this error message:

1. /data/openpilot/selfdrive/car/[BRAND]/values.py is perfectly configured for the candidate car.
2. Have a fingerprint and/or firmware version(s) successfully detected by the comma2 when starting the car.
3. In values.py have the class CAR not match other files.

For a Sonata, for example, open values.py and comment out the FPv1 and FPv2 fingerprints, save, reboot comma2, start car.  All is fine and dashcam mode for an unsupported car is shown, as expected.
Uncomment the FPv1 and FPv2 fingerprints in values.py, change all references of class CAR "SONATA" to "SONATA_ERROR", save, reboot comma2, start car, see "openpilot unavailable waiting for controls to start".
In other scenarios, such as changing all but one class CAR instance of "SONATA" in values.py, OpenPilot fails to start with a syntax error which I guess could be intended, but at least it's more informative.

Unless there's actually another known situation which can cause this, maybe there could be a more informative error message in which OP/comma2 successfully fingerprints a car but the problem is still with the syntax consistency.  I've seen a few mentions of this in other forks on Discord, so my guess is it's just a small typo that the authors may not easily notice if their car isn't the one with the problem.

**Comment by adeebshihadeh** [comment]
Although this is a dev kit, we intentionally don't show much debugging information in the onroad UI. The only reason a regular user would see the "Waiting for controls to start" alert is if controlsd crashed, which is extremely uncommon. The full traceback is in the logs and available when you SSH into your device.
