### ISSUE TITLE
OP2 stock setup - disconnected while driving now constantly rebooting (boot loop)

### ISSUE THREAD

**Issue by justin5188** [commaai/openpilot#20016]
I have had no issues since I've used it for the past couple of months.

On the way home yesterday it gave engine codes, started constantly rebooting, I unplugged the USB-C when I got home, powered off, powered back on (while the car was parked and on as well), and it just goes into a boot loop.

What are some ways I can resolve this?

**Comment by vanillagorillaa** [comment]
Please email support@comma.ai
