### ISSUE TITLE
V0.8.2 lane positioning model bug

### ISSUE THREAD

**Issue by royboendermaker** [commaai/openpilot#20031]
**Describe the bug**

I upgraded to the 0.8.2 branch and driving on a 2 way motorway with double center lane markings OP picks the wrong lane line. It picks the outer lane marking that is ment for the opposite lane. So it doesn't position the car on the road in a right way. It's constantly hugging the left lane line. There is aprox. 5-10 cm distance to the center lane markings on the left and on the right it's like 50-60 cm. It's undrivable for me this way. The left lane marking hugging problem also occurs when there ain't double center lane markings, so just a single divider marking. So could also be some kind of model alignment problem. With 0.7.9 i had exactly the same problem and will fall back to 0.7.4 (https://github.com/actuallylemoncurd/openpilot/tree/openpilot-vw-community-private-pq-braking) that doesn't have this problem and does a decent job.  I haven't changed anything on my EON mount position or coding etc. 

**How to reproduce or log data**

Drive on a EU road with double center lane markings speed around 80 km/h. Or just a 2-way road with one center lane marking.

**Expected behavior**

Decent centering of the car on the road with equeal spacing left and right. 

**Device/Version information (please complete the following information):**

    Device: Oneplus 3T, grey panda, center mount under rear view mirror
    Dongle ID: c4289221cf16a21c
    Route: c4289221cf16a21c|2021-02-06--11-19-45
    Timestamp: Around 12:32;23 till the end (760s in Cabana). For double lane markings and 12:34:53 (911s in Cabana) for single center lane markings. 
    Version: https://github.com/actuallylemoncurd/openpilot/tree/pq-legacy-extcan
    Car make/model: 2010 Scirocco 2.0 TDI

**Additional context**
There are 2 people running this branche without this problem, they are based in the US and in Australia.
2 people outside of the US and living in the EU are having this lane hugging problems. 
I also see the lane width is like 3.50m in Australia and US. Could be the model takes this value as a higher probability for lane width with the smaller 80 km/h roads of 2,75m we have here. 100 km/h roads are 3.25m and 120 km/h roads are 3.50m over here. Those are minimum values.

**Comment by HaraldSchafer** [comment]
Laneless policy should deal with this better, if not already it will soon. Once laneless is good enough it will be the default policy.

**Comment by royboendermaker** [comment]
Laneless didn’t fix it, i tried 0.8.2 laneless and it’s just as bad. Please re-open this bug report.

**Comment by HaraldSchafer** [comment]
Laneless was only released in 0.8.3

**Comment by royboendermaker** [comment]
Actuallylemoncurd merged the laneless function into 0.8.2 but i understand it’s maybe too far off the Comma code. I will try again with 0.8.5.
