### ISSUE TITLE
My.comma.ai drive log bug 

### ISSUE THREAD

**Issue by royboendermaker** [commaai/openpilot#20035]
**Describe the bug**

I upgraded to the 0.8.2 branch and had some problems with lane centering. So i decided to take a look at the drive logs at my.comma.ai.  Almost the whole drive is displayed as disengaged (blue) in stead of green when engaged and also drive length of 0 km/ miles which was clearly not the case.  Also multiple steering override messages are display in the annotations screen but not chronological as it would be normally. The log only displays the first couple of seconds without any annotations and then stops and keeps buffering/loading. Then all the annotations are then showed. 

**How to reproduce or log data**

I don't know if you can reproduce it, Should be done by one of the people running this branch on a VW. 

**Expected behavior**

Decent logging of annotations in chronological order and HUD/Video playback without endless buffering. 

**Device/Version information (please complete the following information):**

    Device: Oneplus 3T, grey panda, center mount under rear view mirror
    Dongle ID: c4289221cf16a21c
    Route: c4289221cf16a21c|2021-02-06--11-19-45
    Timestamp: Whole log
    Version: https://github.com/actuallylemoncurd/openpilot/tree/pq-legacy-extcan
    Car make/model: 2010 Scirocco 2.0 TDI

**Additional context**
- It was my first drive with 0.8.2. so first i got the panda depricated message, after that calibration which finished succesfully. And while driving i also got the check GPS signal message because i hadn't plugged in the gps antenna. But OP still works without it but must be taken into consideration for finding the cause of this problem.

**Comment by adeebshihadeh** [comment]
It's likely that the issue is in your fork. If you can reproduce with stock openpilot, feel free to reopen this issue.
