### ISSUE TITLE
Alert message to immediately connect to the internet for updates even though OP is connected

### ISSUE THREAD

**Issue by pjankovi** [commaai/openpilot#20057]
**Describe the bug**

After the drive, the OP started displaying the following message:

 "Immediately connect to the internet to check for updates. If you do not connect to the internet, openpilot won't engage in 1 day."

However, the OP is connected to the internet and uploads drives successfully. 

Then as the alert predicts, the OP did not engage anymore the next day, displaying the alert again asking to connect to the internet in order to check for updates.

To solve the issue I entered the following command, which reinstalled the software and got rid of the alert message:

cd /data && rm -rf openpilot && git clone -b master-ci https://github.com/commaai/openpilot && reboot

****
Before reinstalling the software, the alert msg was happening every time after I turn off the car after my drive.

**Expected behavior**

This should not be happening since the OP is connected to the internet. 

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: ffccc77938ddbc44
 - Route: ffccc77938ddbc44|2021-02-09--14-31-24
 - Timestamp: at the end when I turn off the car
 - Version: master-ci
 - Car make/model: 2021 Toyota Camry Hybrid LE

**Comment by adeebshihadeh** [comment]
Your device isn't on msater-ci, it's on an old branch based off master. I'd recommend reinstalling master-ci then switching to release2 after 0.8.2 is in release.

**Comment by pjankovi** [comment]
Thanks! So if I enter the following, would I accomplish what you are suggesting?

cd /data && rm -rf openpilot && git clone -b master-ci https://github.com/commaai/openpilot && reboot

If this is not doing what is supposed, then I am not sure how to reinstall master-ci. So I would appreciate if you can send the proper command. Thanks!

**Comment by adeebshihadeh** [comment]
Yes, that should work.
