### ISSUE TITLE
PlotJuggler

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#20068]
https://github.com/commaai/PlotJuggler/tree/rlog

core functionality:
- [x] nice README
- [x] wrapper to pass in route and segment
- [x] wrapper falls back to qlogs
- [x] make nice CLI interface for wrapper
- [x] plugin works with snap version
- [x] install script
- [x] building in CI
- [ ] nice demo experience
  * copy and paste one-liner, ideally without having to clone openpilot
- [x] robustness
  * works regardless of cereal/openpilot directory
- [x] test in CI
  * run the install procedure on a clean machine
  * run the wrapper with a sample route and ensure it doesn't crash

nice to haves:
- [ ] streaming
- [x] DBC parsing
- [ ] make some default layouts for common use cases
- [ ] installer for mac
- [ ] show thumbnails?
- [ ] video?

**Comment by pd0wm** [comment]
Can we also improve performance? Loading a long route takes quite a while. Maybe to some simple profiling to make sure we're not throwing away a bunch of performance on something stupid.

**Comment by adeebshihadeh** [comment]
Core stuff is done. Moving the other TODOs over to individual issues on https://github.com/commaai/PlotJuggler/issues.
