### ISSUE TITLE
Internet Connection Notice

### ISSUE THREAD

**Issue by justinmerrell** [commaai/openpilot#20076]
Warning that device is not able to connect to the internet, does not go away regardless of 4G or WiFi. The problem remains even after a reboot. No change to prime subscription and still able to view the car from the app.
https://photos.app.goo.gl/sEAkDVhLuS7UahcW8

 - Device: Comma Two
 - Dongle ID: 33f227678462b4b1
 - Version: master-ci
 - Car make/model: Toyota 2017 RAV4 Hybrid

**Comment by adeebshihadeh** [comment]
Closing due to lack of necessary information. Feel free to reopen after filling out the template.

**Comment by justinmerrell** [comment]
Edited.

**Comment by justinmerrell** [comment]
> Closing due to lack of necessary information. Feel free to reopen after filling out the template.

Should I make a new report?

**Comment by adeebshihadeh** [comment]
Can you ssh in to your device and try running `cd /data/openpilot && git fetch --dry-run`? Paste the output here.

**Comment by justinmerrell** [comment]
From https://github.com/commaai/openpilot
 + 872e0c17...0b476aba master-ci        -> origin/master-ci  (forced update)
 * [new branch]        agnos06          -> origin/agnos06
   40919a6f..c189d15a  master           -> origin/master
 + 698caf46...2440b640 new-model        -> origin/new-model  (forced update)
   ddf0aebb..d229b989  pandad-refactor  -> origin/pandad-refactor
 + b2b986c9...1f51d030 release3-staging -> origin/release3-staging  (forced update)
 * [new branch]        tesla-ap2        -> origin/tesla-ap2
 + 9a976fe3...d3eb7b9a testing-closet   -> origin/testing-closet  (forced update)
   e08b0b47..6c309220  tici_db_remaster -> origin/tici_db_remaster
 * [new branch]        ui-fixes         -> origin/ui-fixes
 + b2383d91...00490bae zookeeper-ci     -> origin/zookeeper-ci  (forced update)

**Comment by adeebshihadeh** [comment]
I checked your device's logs over the last week and seems it's updating fine now, so we'll close this. I also fixed up the error handling in #20754, so the exceptions you would've been getting will show as an alert and in the logs for debugging.
