### ISSUE TITLE
TSS2 Corolla needs angle offset for more accurate angle signal from torque message

### ISSUE THREAD

**Issue by ShaneSmiskol** [commaai/openpilot#20086]
This line seems to be incorrect along with the comment for a TSS2 Corolla: https://github.com/commaai/openpilot/blob/master/selfdrive/car/toyota/carstate.py#L22. I'm just not sure if the TSS2 Corolla is the exception or if we can always offset if that more accurate angle is seen and just remove the needs_offset variable. I think it's the latter and we can always offset if the angle signal in the torque message is available.

On birdman's TSS2 Corolla that `STEER_TORQUE_SENSOR` `STEER_ANGLE` signal that's being used always seems to start at 0, so the angle openpilot uses can have an offset that varies wildly between drives depending on where the wheel starts, since it's not being offset when it should.

This is simulating what carstate does now (but doesn't actually offset it, so you can see the difference in angles. It should have been offset -2.95829... degrees.
![Screenshot_164](https://user-images.githubusercontent.com/25857203/108022080-7ec58580-6fe5-11eb-9a23-5999a98ad34f.png)

Here's also the different angles plotted against each other:
![Screenshot_163](https://user-images.githubusercontent.com/25857203/108022298-eaa7ee00-6fe5-11eb-9842-eba8ea81b336.png)

From carstate is what openpilot uses, and from can is the message available and used on TSS1 cars that's not as precise (`STEER_ANGLE_SENSOR`, `STEER_ANGLE`).

**Comment by ShaneSmiskol** [comment]
Considering my TSS1 Corolla's offset is about -0.31 degrees this is rather high which could cause some weirdness on initial engage as openpilot works to find out the offset that carstate should have taken care of: 
![Screenshot_165](https://user-images.githubusercontent.com/25857203/108022933-2db69100-6fe7-11eb-99d8-71fcfac0b018.png)

**Comment by pd0wm** [comment]
Are you suggesting to replace line 22 by `self.needs_angle_offset = True`. I guess that can't hurt.

**Comment by ShaneSmiskol** [comment]
Yeah, if you found nodsu non-TSS2 cars need the offset too then I bet they all do with the more accurate sensor. If a specific car doesn't need the offset then both angles will start at the same value keeping the offset 0 hopefully
