### ISSUE TITLE
DMonitoring Inputs

### ISSUE THREAD

**Issue by weiwang928** [commaai/openpilot#2009]
Hello,

I am trying to run dmonitoring_model.keras on my computer. I am just wondering what is the input format for this model and where can I find code that processes inputs for it?

Thanks

**Comment by ZwX1616** [comment]
you can check out 
https://github.com/commaai/openpilot/blob/f3fb406eee85b072c727ccaf027bd2dacd3aa69a/selfdrive/modeld/models/dmonitoring.cc#L37
