### ISSUE TITLE
Update camerad with new camera convention

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#20095]
New convention from https://github.com/commaai/cereal/commit/a0348379249f77b85765846f0ebc5dcdb358821d

@deanlee interested in this one? should make the camerad code much more readable

**Comment by deanlee** [comment]
do you mean using `capnp/dynamic` to process FrameData?

**Comment by adeebshihadeh** [comment]
That would be nice, but I meant just fixing all the rear/front stuff to match the new packet names, e.g. front -> driverCamera.

**Comment by deanlee** [comment]
OIC

**Comment by deanlee** [comment]
I'm doing it in  https://github.com/commaai/openpilot/pull/20096 ,please remind me if I did something wrong.

**Comment by adeebshihadeh** [comment]
looks good so far :)

**Comment by adeebshihadeh** [comment]
Thanks @deanlee!
