### ISSUE TITLE
Intermittent "Car Unrecognized"  toyota highlander 2021

### ISSUE THREAD

**Issue by jaenmora** [commaai/openpilot#20135]
Intermittent "Car Unrecognized"  toyota highlander 2021

**Expected behavior**

**Device/Version information 
 - Device: comma two
 - Dongle ID:  8099222e8aa449f6
 - Route: 
 - Version: V0.8.1
 - Car make/model:  toyota highlander 2021
**Additional context**

**Comment by vanillagorillaa** [comment]
Please edit your original post and provide the relevant information (I.E. DongleID)

**Comment by VirtuallyChris** [comment]
Your car had missing engine fw. I've added it in this PR https://github.com/commaai/openpilot/pull/20144

master-ci will have this in a few hours.
