### ISSUE TITLE
The vehicle can not run properly in the simulator

### ISSUE THREAD

**Issue by LLplane** [commaai/openpilot#20158]
The vehicle can not run properly in the simulator and always  always hit the edge of the road.

below are some screenshots 
![commai-pilot](https://user-images.githubusercontent.com/46469819/109115907-adc4bf80-777a-11eb-95b0-a7551a0d41b2.png)

the car hit the edge
![commaai_error](https://user-images.githubusercontent.com/46469819/109116569-be296a00-777b-11eb-8a75-d9c52d32c96b.png)

Operating system: [e.g. Ubuntu 18.04]

**Comment by westbrook00** [comment]
![image](https://user-images.githubusercontent.com/38600921/109136267-e83a5680-7792-11eb-8c65-5afc4bc06b1d.png)
Hello,LLplane! Have you got this error before? I just follow the steps:1. ./start_carla.sh 2../start_openpilot_docker.sh, then it can't find the attribute "angelSteersDes", if anyone helps me fix the error,I will thank a lot!

**Comment by adeebshihadeh** [comment]
Closing this as there are several problems and open issues for the simulator. We'll be spending some time on getting the simulator in a good state and fixing the open issues very soon.
