### ISSUE TITLE
Brightness increase option for polarizing screen protectors

### ISSUE THREAD

**Issue by Jon8RFC** [commaai/openpilot#20193]
The commonly suggested screen protector to accommodate polarized glasses reduces brightness a noticeable amount:
https://smile.amazon.com/dp/B01BZFRC0Y/

If there is an easy-to-access switch in settings to override the brightness curve dynamically, that'd be very helpful. 
Neutral or zero would be standard, and override is +/- a percentage range that supplements the custom brightness curve enabled on the comma two.

**Comment by adeebshihadeh** [comment]
We like to keep the amount of settings and toggles in openpilot to a minimum. See https://github.com/commaai/openpilot/wiki/FAQ#can-i-adjust-the-brightness-calibration.
