### ISSUE TITLE
fcamera.hevc files missing necessary container information for proper playback

### ISSUE THREAD

**Issue by Jon8RFC** [commaai/openpilot#20194]
**Describe the bug**

The fcamera.hevc files playback on VLC and divx players as 40 second videos.  Uploaded to youtube, they playback as 48 second videos.  These files are missing the necessary information for the video to playback at the correct framerate.  The qcamera.ts files contain the information to playback at the appropriate framerate.

**How to reproduce or log data**

Download and playback an fcamera.hevc video segment, or upload it to youtube, and see that the video lengths are not ~60 seconds.

**Expected behavior**

For the container/header/metadata/something to properly instruct video players on how to playback the file.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 6363a0e48f515f27
 - Route: 6363a0e48f515f27_2021-02-26--10-49-55--1--fcamera.hevc
 - Timestamp: 6363a0e48f515f27_2021-02-26--10-49-55--1--fcamera.hevc
 - Version: 0.8.1
 - Car make/model: Hyundai Sonata 2018

**Additional context**
File content example image (large):
https://user-images.githubusercontent.com/12204953/109408085-ccc67b80-794b-11eb-8f37-29d0897eb496.png

**Comment by adeebshihadeh** [comment]
See #1051
