### ISSUE TITLE
'cereal/gen/cpp/car.capnp.h' file not found

### ISSUE THREAD

**Issue by Eleanor456** [commaai/openpilot#2020]
When I compiled openpilot by scons, showing the error "selfdrive/boardd/boardd.cc:22:10: fatal error: 'cereal/gen/cpp/car.capnp.h' file not found". And I found that the cereal folder is empty. Could you tell me how to solve this problem. 
Thanks!

**Comment by adeebshihadeh** [comment]
cereal is a submodule, which needs to be initialized after cloning.

**Comment by stplaydog** [comment]
Is this issue resolved?
