### ISSUE TITLE
OpenPilot Unable to See Lane Markers Causing Lane Departure

### ISSUE THREAD

**Issue by C0mpl3t3N00b** [commaai/openpilot#20213]
**Describe the bug**

While at slight curve in the highway, there was a change in road type and OpenPilot no longer saw the lane lines and caused my car move into another lane.

**How to reproduce or log data**

Have OpenPilot engaged at highway speeds and drive on pavement that has different material (imagine cement / asphalt change) while on a curve.

**Expected behavior**

If I can see the lane lines or markers on the ground, OpenPilot should also see the lane markers so the vehicle does not veer into vehicles. _(Maybe hardware limitation to the low resolution of the mobile phone's camera?)_

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: bdad50b8a1f9fa8e
 - Route: bdad50b8a1f9fa8e|2021-02-28--12-26-03--13
 - Timestamp: bdad50b8a1f9fa8e|2021-02-28--12-26-03--13
 - Version: master-ci
 - Car make/model: Toyota Rav4 Hybrid 2021

**Additional context**

![lane changes](https://user-images.githubusercontent.com/70859798/109585023-89891b80-7ab7-11eb-96c8-7f7805be6c74.png)

**Comment by HaraldSchafer** [comment]
Thanks for report. Should be significantly improved with 0.8.3, due to the new segnet and better laneless performance.
