### ISSUE TITLE
Offroad UI enhancements

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#20263]
- [x] Show username for current SSH keys
- [x] Refresh developer page periodically
- [x] Cache home screen state (drive stats, prime status, etc.)
  - [x] show cached version instead of "No Internet connection" when offline
- [x] Click outside of confirmation dialog to dismiss
- [x] Close confirmation dialogs after settings timeout
- [x] Make driver view fast
- [x] Don't shift drive stats down when alert/update button is shown
- [x] Description text in settings
- [x] Close offroad alerts when all alerts go away
- [x] Scrolling in offroad alerts + release notes
- [x] Disable driver view button while onroad
- [x] Close android activities when exiting settings
- [x] Show calibration values

**Comment by BrevanJ04** [comment]
- [ ] WPA2-EAP support
- [ ] Remove saved wifi networks
- [ ] UI change to denote the difference between connecting over wifi and ethernet

**Comment by doktorsleepelss** [comment]
* [ ]  View mount placement degrees like on C2

**Comment by jyoung8607** [comment]
- [ ] Optionally mask Wifi password during entry

**Comment by speedking456** [comment]
- [ ] Reset SSH keys to default

**Comment by michaelhonan** [comment]
- [ ] comma prime upgrade widget overlaps the home statistics view.

**Comment by grekiki** [comment]
> * [ ]  comma prime upgrade widget overlaps the home statistics view.
I think that's only true on PC because it uses the narrower screen(https://github.com/commaai/openpilot/blob/fb5873bb6d00b4f625e9ee0cd1767fe8805b2476/selfdrive/ui/qt/qt_window.hpp#L16)
