### ISSUE TITLE
OP crosses double yellow line into opposite lane

### ISSUE THREAD

**Issue by abdulrahman004** [commaai/openpilot#20266]
Driving on a two lane road with dashed double yellow line in center. Visibility looked pretty good when OP decides to cross over yellow lines and go in oncoming lane. Not sure why. May be center yellow lines were faded ?

Expected behavior
Car shouldn't have changed driving path

Device: FreEon
Dongle ID: 59f457ce47259dd2 

Route: 59f457ce47259dd2|2021-03-07--02-20-14--7
Timestamp: 18:27:53
Version: 0.8.2 (release 2)
Car make/model: Toyota Sienna 2018
Additional context
gif of the report
https://imgur.com/a/NbmpDmz

**Comment by HaraldSchafer** [comment]
Thanks for this report. This one is pretty extreme. The 0.8.3 model should recover from these kind of things though, the 0.8.2 model could not recover from quick mistakes.
