### ISSUE TITLE
"openpilot Unavailable: Main Switch Off"

### ISSUE THREAD

**Issue by pviolette3** [commaai/openpilot#2029]
**Describe the bug**

Latest openpilot (0.7.7) has never engaged for me: it always gives an error that the main switch is off:

![20200809_131107](https://user-images.githubusercontent.com/1941415/90319005-4daab200-dee9-11ea-84fe-723a99de4286.jpg)

I have a Honda Civic Hatchback, 2019. The car was previously working for me on a fork of [0.7.4](https://github.com/pviolette3/openpilot/tree/release2) with one [Cherry Pick to recognize my car's firmware versions](https://github.com/pviolette3/openpilot/commit/966cf2c7660306877c7bb7e620aa6557aeb15584). At the beginning of August, this fork was no longer working, because OP gave a message to update. Therefore, I factory-reset the comma 2 and updated to the latest OP (0.7.7), and have since been getting this error when tapping the "set cruise" button.

I did double-check the mounting of C2/wiring, and it is connected to OBD2 +USB-C properly, as far as I can tell. It powers on fine; it doesn't say "Car Unrecognized" on startup. The Main Switch Off error only happens when I engage with "set cruise" button.

How/where does one turn the Main Switch On?

**How to reproduce or log data**

Turn on car. Car is recognized OK. Start driving; engage open pilot with "Set Cruise Control'. Open Pilot fails to engage (<error beep>) + "openpilot Unavailable: Main Switch Off" (pictured above).

**Expected behavior**

OP engages, and drives my car, as in 0.7.4 :)

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 5d02a73998def520
 - Route: Here is the latest failure: 5d02a73998def520|2020-08-13--18-05-26 ; here is the last known good drive (running on my fork): 5d02a73998def520|2020-06-30--13-58-27 (June)
 - Timestamp: I think I tried to engage OP at 18:15:11 , in the "not working" route.
 - Version: Openpilot v0.7.7-release  (release2, hash = 241f412efc31). Panda fw: 1bddc6597451eaed
 - Car make/model:  Honda Civic Hatchback, 2019

**Additional context**

I did not drive for most of July, so I'm not sure exactly when the "upgrade now" errors started happening.

Thanks for the help!

**Comment by vanillagorillaa** [comment]
This is not a bug, you need to hit the "Main" switch on your steering wheel.
