### ISSUE TITLE
.local/bin/scons: No such file or directory

### ISSUE THREAD

**Issue by ryleymcc** [commaai/openpilot#20325]
when i run `scons -j$(nproc)
`
i get the error: bash: `/home/ryley/.local/bin/scons: No such file or directory`

Can't find any step-by-step, clean installation instructions online for OP on ubuntu 20. Everyone readme assumes you have everything set up already.

**Comment by adeebshihadeh** [comment]
We updated our READMEs today. Check out the new README at https://github.com/commaai/openpilot/tree/master/tools#setup. Let us know if you have any issues with these setup instructions!

**Comment by ryleymcc** [comment]
Once I set my PYTHONPATH in ~/.bashrc it builds without errors
