### ISSUE TITLE
openpilot in simulator not work

### ISSUE THREAD

**Issue by lixit** [commaai/openpilot#20381]
**Describe the bug**

after run `./start_carla.sh `

the following error appeared
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.`

**How to reproduce or log data**

following the README

**additional context**

My laptop doesn't have NVIDIA card. Is the NVIDIA card required?

Operating system: [Ubuntu 20.04]

**Comment by adeebshihadeh** [comment]
Yes, this method requires an NVIDIA card. See the CARLA documentation: https://carla.readthedocs.io/en/latest/build_docker. @iejMac let's add this to the README.
