### ISSUE TITLE
Screen only shows side bar info and rest is blank. OP does not engage 

### ISSUE THREAD

**Issue by wasserbrunner** [commaai/openpilot#2039]
The main section of the screen is blank, no video feed, no lane lines (see image). OP can not engage. Makes the engage sound then disengage sound immediately. 

**How to reproduce or log data**
It began happening seemingly out of no where and I haven't been able to use my comma for weeks. 

I don't know

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: d0f00bd94de791b7
 - Route: all in last few weeks
 - Timestamp: constant
 - Version: 0.7.7 release 2
 - Car make/model: 2020 corolla 

**Additional context**
I have reinstalled op with no luck.
![image0](https://user-images.githubusercontent.com/69725717/90431131-8fc52680-e096-11ea-91e5-f5493767ff5e.jpg)

**Comment by pd0wm** [comment]
I suspect the camera of your comma two is broken. If you contact support@comma.ai they can get that replaced.
