### ISSUE TITLE
2017 Subaru Impreza ping pong in lane

### ISSUE THREAD

**Issue by Jahmangy** [commaai/openpilot#20397]
My 2017 Subaru Impreza does not drive straight between the lane lines to a point that it’s not useable. Help!!

**Comment by pd0wm** [comment]
Please fill out the bug report template with dongle id and drive(s).

**Comment by Jahmangy** [comment]
Hi Willemstad,
Where would I find the report template? And what’s the dongle Id?


Maurice 
Best Regards

On Mar 18, 2021, at 11:45 AM, Willem Melching ***@***.***> wrote:

﻿
Please fill out the bug report template with dongle id and drive(s).

**Comment by pd0wm** [comment]
When you create a new issue on github it will populate with a template. Basically we want this info:

Device: [e.g. EON/EON Gold/comma two]
Dongle ID: [e.g. 77611a1fac303767, can be found in Settings -> Device -> Dongle ID or my.comma.ai/useradmin]
Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
Timestamp: [When in the route the bug occurs (e.g. 4min 30s into the drive)]
Version: [commit hash when on a non-release branch, or version number when on devel or release2 (e.g. 0.7.6)]
Car make/model: [e.g. Toyota Prius 2016]

**Comment by Jahmangy** [comment]
Device/Version information (please complete the following information):

Device: Comma2
Dongle ID: 0bad2474c0a9a035
Route: all but most recent 69
Timestamp: all 
Version: v0.8.2-release
Car make/model: 2017 Subaru Impreza with EyeSight
Additional context
The path mapping still showed the car is between to lane lines even when it crosses outside of the lane

**Comment by RCoaster** [comment]
Steer Actuator Delay is too high- should be lowered by .2 to reflect the new MPC

**Comment by Jahmangy** [comment]
Thanks. However, how do I go about making this fix? 


Maurice 
Best Regards

On Mar 27, 2021, at 10:55 AM, RCoaster ***@***.***> wrote:

﻿
Steer Actuator Delay is too high- should be lowered by .2 to reflect the new MPC

**Comment by dbzx6r** [comment]
> 
> Thanks. However, how do I go about making this fix? Maurice Best Regards On Mar 27, 2021, at 10:55 AM, RCoaster ***@***.***> wrote: ﻿ Steer Actuator Delay is too high- should be lowered by .2 to reflect the new MPC — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You will need to ssh and cd into /data/openpilot/selfdrive/car/subaru and use 'nano interface.py' to modify the value from 0.4 to 0.2. I'm in the same boat as you with pingponging, i've made this change and I'm going to test it out

**Comment by dbzx6r** [comment]
i've made the change, and it is significantly better, but there's still some room for improvement.

in the video below specifically watch around the 1:15 mark, you can see it still gets pretty close to the lane line, and there is still pingponging BUT it will maintain the lane in this short drive.

[https://www.youtube.com/watch?v=n4QwyiiONUo](url)

do you have any suggestions on the next value to adjust?

**Comment by michaelhonan** [comment]
Can confirm (as I have an 18 Impreza, which is the exact same car), this is not an OP bug. It's related to tuning.

Likely worth closing this as 0.8.3 corrected a lot of the lateral issues seen in 0.8.2. Rest can be tuned out.

**Comment by Jahmangy** [comment]
OK. I'm still on 0.8.2 and the device is not giving me the option to do the OTA update to 0.8.3. I tried powering down and resting the device but it's still on 0.8.2.

**Comment by michaelhonan** [comment]
@Jahmangy if you're not on stock, you'll need to ask your fork maintainer. Likely either "fk da police" or "mlp" in the Subaru channel on Discord.

**Comment by Jahmangy** [comment]
It's on stock. Everything is stock. I'm just trying to get it to work after my first experience with my initial drive.

**Comment by michaelhonan** [comment]
Fair enough! Well, I'd connect to Wifi if you haven't already, and just let it sit for 5 minutes. It should prompt you.

If all else fails, just head to Settings -> Device -> Uninstall openpilot, then follow the [instructions to install openpilot](https://github.com/commaai/openpilot/wiki/Installing-openpilot) again.

**Comment by adeebshihadeh** [comment]
Closing this since it sounds like a tuning issue and lateral performance on subarus should be improved with recent versions.
