### ISSUE TITLE
Device going offroad while car started

### ISSUE THREAD

**Issue by adam-nelson** [commaai/openpilot#2042]
**Describe the bug**

Since the updated method has changed in 0.7.8. 

I've have noticed a restart/reset that causes disengagement of the openpilot

**How to reproduce or log data**

Driving openpilot with engage and pushing an update from github

Alternative not driving..... System will just reboot or reset itself

**Expected behavior**

An update should trigger while the car is on or driving.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 18e8ac91b805db11
 - Version: 0.7.9 master-ci
 - Car make/model: Toyota corolla hatchback au delivered 2019

**Additional context**

I assume this being triggered by any github push trigger to master/master-ci branch

**Comment by adeebshihadeh** [comment]
The updater doesn't run when onroad. I checked your last five routes, but didn't seen anything. Do you have a route where this happened? Has this happened more than once and why do you think it's the updater?

**Comment by pd0wm** [comment]
An update also should never cause the device to reboot by itself. Only when you press the reboot button after a drive it will restart.

**Comment by VirtuallyChris** [comment]
Wondering if the device is bootlooping to some extent. If it continues to reboots randomly email support@comma.ai

**Comment by adeebshihadeh** [comment]
I reviewed more of your routes, and this isn't related to the updater. The ignition line goes low, and your device goes offroad. I recommend unplugging everything and ensuring each connector is seated properly. If the issue persists after that, contact support@comma.ai.
