### ISSUE TITLE
remove le pro3 battery 

### ISSUE THREAD

**Issue by dingyf12593** [commaai/openpilot#20464]
black panda + le pro3 ,It's summer i want remove the le pro3 battery. but i found , The phone can't start when the battery is removed  or  keep the battery protection board and remove the cells.  How to solve this problem? Thanks very much

**Comment by VirtuallyChris** [comment]
This isn't an issue with openpilot so I'm going to close it. It is one of the main selling points of a comma two though! If you want to pick the community for how they go about this, join discord.comma.ai in the #hw-unofficial channel.
