### ISSUE TITLE
error: inflate: data stream error (incorrect data check)

### ISSUE THREAD

**Issue by bli1** [commaai/openpilot#20481]
**Describe the bug**
After factory reset and backup openpilot folder under data, I git clone a copy and plan to checkout master-ci. 

cd /data
mv openpilot openpilot.backup
git clone https://github.com/commaai/openpilot.git

Then I receive error as:

**
root@localhost:/data$ git clone https://github.com/commaai/openpilot.git
Cloning into 'openpilot'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (39/39), done.
error: inflate: data stream error (incorrect data check)iB/s   
fatal: pack has bad object at offset 3891079: inflate returned -3
fatal: index-pack failed
**

**Expected behavior**

I expected to git clone. 

**Device/Version information (please complete the following information):**
 - Device: [comma two]
 - Version: [0.8.2]

**Comment by adeebshihadeh** [comment]
This is not an openpilot issue, but make sure your device has enough memory and a stable internet connection.
