### ISSUE TITLE
The simulation screen just pop-up for a moment on vncserver, then disappear... other functions work correct.

### ISSUE THREAD

**Issue by edwardchang0112** [commaai/openpilot#20533]
After follow the steps

`sudo INSTALL=1 ./start_carla.sh`
![image](https://user-images.githubusercontent.com/64570284/112944328-4200b880-9165-11eb-8827-253f3551eb6c.png)

`sudo ./start_openpilot_docker.sh`

![image](https://user-images.githubusercontent.com/64570284/112944549-9310ac80-9165-11eb-98ed-7e595f0646e2.png)

![image](https://user-images.githubusercontent.com/64570284/112944573-9c9a1480-9165-11eb-8c0d-40e54df42332.png)

There is no new screen pop-up while using Mobaxterm (xclock and xeyes works fine), but other function seems working correctly.

So I tried to use vncserver, get almost the same results, the one different thing is for vncserver, I can see the comma's screen pop-up a moment then disappear.

How can I resolve this problem. Is there any comments?

Here's are the error messages
1. The X11 connection broke (error 4). Did the X11 server die? How should I do for this?

![image](https://user-images.githubusercontent.com/64570284/112951640-2352ef80-916e-11eb-97b3-0e1457bb9d94.png)

2. Error reading params None: 'NoneType' object has no attribute 'get'

![image](https://user-images.githubusercontent.com/64570284/112951882-6dd46c00-916e-11eb-852e-363dde17db96.png)

**Comment by adeebshihadeh** [comment]
This seems like a bit of an edge case, and we can't immediately reproduce this. Unless you have a way to reproduce this outside of vncserver, I'm going to leave this closed. We'd be happy to merge a PR that fixes this though.
