### ISSUE TITLE
Webcam tool doesn't work well.

### ISSUE THREAD

**Issue by zhuhj-tery** [commaai/openpilot#20575]
**Describe the bug**
Hi,
We try to use the webcam tool of openpilot on a PC. We followed the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC to two web cameras and the black panda. These two web cameras were tested to be able to work well. The computer successfully recognized these three devices. However, it seems that the cameras didn't work since the ui showed "Camera Malfunction! Contact Support!". In the terminal, there are some error messages showing that the cameras are not alive:
![image](https://user-images.githubusercontent.com/69643560/113495335-0a747200-94bf-11eb-9e5e-6ce12ece01e1.png)
![image](https://user-images.githubusercontent.com/69643560/113495337-106a5300-94bf-11eb-89c8-52fb493800f9.png)
![image](https://user-images.githubusercontent.com/69643560/113495343-16603400-94bf-11eb-9c80-d0d2dfccc295.png)
Any comments or suggestions are appreciated.
Thanks!
**How to reproduce or log data**

We just run the command: PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py and started the car.

**Expected behavior**

The UI should show the road webcam's view.

**Additional context**
Operating system: Ubuntu 20.04
Web camera: Logitech C920 and C615

**Comment by grekiki** [comment]
Does your PC have a good Nvidia GPU?

**Comment by zhuhj-tery** [comment]
Thanks for the suggestions. I tried to run camerad separately and found out that the issue is caused by the connection problem between the camera and the PC. So, I rebuilt openpilot with the correct camera index and it works.
Thanks a lot.
