### ISSUE TITLE
Connect Offline while connected to wifi

### ISSUE THREAD

**Issue by strickc** [commaai/openpilot#20578]
**Describe the bug**

 About a week ago my comma2 started saying "Connect Offline" even when connected to wifi.  Today when turning it on to upgrade to 0.8.3.  It gave me a red time / date cannot be updated error and then a "Openpilot will stop engaging in 0 days" error.  I sshed into the comma and deleted and cloned release2, which all worked fine because it was connected to wifi.  Upgrade went smoothly, including the neos upgrade, and when it turns on it first says "Connect Online" but changes to "Connect Offline" after 1 second.  Multiple reboots produce the same issue.  This is the case whether connected to the vehicle or just a usb power supply.

**How to reproduce or log data**

Connect to wifi, observe it says Connect Offline.  
Let me know if there are any logs I can share please.

**Expected behavior**

I expect it to say Connect Offline so it won't eventually refuse to enable and get updates.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: a9badec81d3f1943
 - Route: N/A
 - Timestamp: N/A
 - Version: 0.8.3 (same with 0.8.2)
 - Car make/model: 2021 Rav4 Hybrid

**Additional context**

![image](https://user-images.githubusercontent.com/8469483/113511015-de86da00-951a-11eb-9c00-558fe0461b7f.png)

**Comment by gregjhogan** [comment]
This is a athena backend issue that is intermittently happening which we are working on resolving
