### ISSUE TITLE
Car fw versions in useradmin don't have proper formatting

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/openpilot#20593]
Before 0.8.3, carfw was shown in the same format as it is in the values.py file.

Since many people still use useradmin to fingerprint their cars, we should make the logs match what they would see in values.py to prevent PRs [like this](https://github.com/commaai/openpilot/pull/20583)

![image](https://user-images.githubusercontent.com/37757984/113651090-366e2f80-9646-11eb-9a56-20cdd0320462.png)

**Comment by gregjhogan** [comment]
This was a temporary fix until capnproto 0.9.0 is released with https://github.com/capnproto/capnproto/pull/1143

**Comment by VirtuallyChris** [comment]
Ah I see, sucks that there hasn't been a release in over a year :/

**Comment by adeebshihadeh** [comment]
There's unlikely to be a new capnp release soon. @gregjhogan can we just build capnp from source in useradmin for now?

**Comment by gregjhogan** [comment]
Tried using the bleeding edge capnproto and it is actually worse (all non-ascii characters change to octal notation)

![image](https://user-images.githubusercontent.com/4112046/117245778-394c7380-adf0-11eb-8209-dc491b9ee138.png)

not exactly sure why it is doing this, it is somewhere inside capnproto

an alternative would be to switch from `str()` to `to_dict()` and then use `pprint` to format it, but this approach leads to re-ordering of the keys and turning off all the sorting doesn't fix it (`logMonoTime` goes to the bottom)

**Comment by adeebshihadeh** [comment]
This isn't really an actionable openpilot issue and personally don't think the format is a huge deal. We have a test to check for duplicate FW. Closing and will open an issue in xx to track this when we get some more time to look into it.
