### ISSUE TITLE
Hard oversteer on curved road as approaching stop 

### ISSUE THREAD

**Issue by letsdudiss** [commaai/openpilot#20596]
**Describe the bug**

When car is about to come to a full stop (normally at around 10-20km/h) and the road is curved/bent, the car steers really hard (causes torque limit warning) into the direction of the curve. i.e if the road is curved to the right, as car slows down to approx. 25km/h, it steers suddenly and hard into the right, causes the car to depart its current lane into the lane on the right

**How to reproduce or log data**

Best reproduced during Stop and Go traffic on windy road

**Expected behavior**

To not steer too hard

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Dongle ID: 0ccc2a956a1a1064
 - Route: 0ccc2a956a1a1064|2021-04-06--07-58-46
 - Timestamp: 2m9s (at 18:10:56) and 21m48s (at 18:19:35)
 - Version: 0.8.3 devel (from commaai) with some commits on top (for Stop and Go)
 - Car make/model: Subaru Impreza 2021 but also saw a similar report on discord by someone driving another make

**Additional context**

Happens twice, first time is the most obvious. From explorer, the 2 incidents can be easily identified by torque limit warning

**Comment by pd0wm** [comment]
Looks like the model was overestimating the turn a little bit. Also at low speed we use quite high steering angles to get you back on the desired path, which quickly hits the torque limit. Hopefully when control aggressiveness is driven by model uncertainty problems like these will get better.

Unfortunately not single easy thing we can fix to make these problems go away.

![2021-04-08-145342_631x474_scrot](https://user-images.githubusercontent.com/1314752/114029848-3c4c5680-987a-11eb-98d7-2f615404f7d1.png)

**Comment by letsdudiss** [comment]
Can i reduce its aggressiveness by default some how?

**Comment by HaraldSchafer** [comment]
Yeah low speed control is pretty bad still, and generally too aggressive. It's not a quick to improve that, but it's on the TODO list, thanks for the report!

**Comment by letsdudiss** [comment]
Looks like its fixed from this?

https://github.com/commaai/openpilot/commit/dc40631e97739c8e55f271501b6356eda52d84ff

I tried it on my usual route where it used to happen, seems fixed
