### ISSUE TITLE
Communication Issue between Processes

### ISSUE THREAD

**Issue by KDKimura** [commaai/openpilot#20603]
**Describe the bug**

Anywhere from immediately to a few minutes after engaging openpilot, comma two displays error

TAKE CONTROL IMMEDIATELY Communication Issue between Processes

**How to reproduce or log data**

Uninstall and reintall openpilot if you want because it doesn't solve the issue.
Unplug DSU. I believe the issue also occurred with DSU connected.
Toggle on LDA and front camera upload.
Start car and engage openpilot.
Sometimes it occurs immediately, other times it occurs within 4 minutes.

**Expected behavior**

Less energy expenditure in the arms and Wall-E like obliviousness....openpilot should function without this error.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 55c431eb30c49edb
 - Route: 55c431eb30c49edb|2021-04-05--13-04-24
 - Timestamp: 0-5 minutes into the drive
 - Version: 0.8.3
 - Car make/model: Toyota Prius 2016

**Additional context**

🤬

**Comment by adeebshihadeh** [comment]
I meant to edit your comment on #20601 with the template filled out. Closing as this is a duplicate issue.
