### ISSUE TITLE
Hyundai Ioniq Electric 2020 - CAN Error,Check connections

### ISSUE THREAD

**Issue by Dr-Diesel** [commaai/openpilot#20692]
**Describe the bug**

Hyundai Ioniq Electric 2020 , when connected to car, CAN Error Check connections appears , no openpilot functionality except speed + highlighting the road

**How to reproduce or log data**

Install Openpilot, Start the car, a while "Be ready to take driving" or so, "CAN Error" afterwards.

**Expected behavior**

Any Openpilot functionality.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: acef3b725c798766
 - Route:  
 acef3b725c798766|2021-04-16--04-35-09 (can record another one)
 acef3b725c798766|2021-04-16--08-30-38 (v0.8.3, no drive, just startup, can record drive)
 - Timestamp: Immediate after start
 - Version: openpilot v0.8.2 , tried upgrade to openpilot v0.8.3-release , same behavior
 - Car make/model: Hyundai Ioniq Electric 2020

**Additional context**

It's not USB-C cable related, tried both way, two cables (when USB-C faulty, Dashcam mode occurs afaik) 
Two Pandas tried (received replacement harness)
Tried Fingerprint2 to add my firmware, still no luck.

WARNING - when tried to fiddle with `tmux a` , accidentaly pressed Ctrl+C instead of `+d with car powered On. Afterwards ALL LKAS CALIBRATION WAS RESET and car started to issue "Check LKAS" on dash. Today recalibrated at dealer (3hr...), anyway "Can ERROR" still occurs.

I have SSH available, but truth said, I'm quite afraid to debug it online with car connected, after it corrupted LKAS calibration, quite don't want to proceed it again.

Can provide any info from C2 ssh, but no dangerous operations to crash it and corrupt the lkas again.

Available at discord DrDiesel#6766

**Comment by adeebshihadeh** [comment]
Fixed in #20706
