### ISSUE TITLE
Stuck in "registering device"

### ISSUE THREAD

**Issue by wasserbrunner** [commaai/openpilot#20736]
Describe the bug

I had constant model lagging error, so I reinstalled openpilot. It got stuck in "registering device". I have tried factory reseting and reflashing, neither worked. I am still stuck in "registering device". I have tried multiple wifi connections. I've tried plugged into a computer and the wall with a strong charger.

How to reproduce or log data

I reproduce it by rebooting my device.

Expected behavior

Normal boot

Device/Version information (please complete the following information):

Device: Comma 2
Dongle ID: can't get
Version: Release2-staging
Car make/model: 2020 corolla.

Thank you for any help.

**Comment by adeebshihadeh** [comment]
This may be related to a recent change on our backend. How did you wipe your device? Did you touch /persist at all? Can you get your device's serial number (SSH in and run `getprop ro.serialno`)?

**Comment by wasserbrunner** [comment]
I'm not familiar with most of this kind of technical stuff. I don't know if I touched /persist. I just followed the directions for reflashing on a mac https://github.com/commaai/eon-neos

I don't know if I can ssh in because I reflashed it and can't setup ssh in the settings (cause it won't  boot). When I get home I'll see if workbench detects it

**Comment by adeebshihadeh** [comment]
We pushed a change to our backend. If you connect your device to wifi and try again, it should work. Let us know how if you have any other issues!

**Comment by wasserbrunner** [comment]
That worked thank you!!

**Comment by ReFil** [comment]
I encountered this bug a few hours ago, using a FrEON, put in openpilot.comma.ai as the install link. reflashed twice to no avail

**Comment by adeebshihadeh** [comment]
That's expected for freons on current release. You'll need to run master until the next release.
