### ISSUE TITLE
Sensor timestamp not used in locationd

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#2074]
Sensord publishes the exact measurement timestamp. Currently this is not used by locationd. Instead the packet timestamp is used.

@HaraldSchafer Can you verify this improves the kalman filter results? I quickly checked Mesh3D and that also seems to use packet timestamps instead of measurement timestamps.

See: https://github.com/commaai/openpilot/blob/master/selfdrive/locationd/locationd.py#L243

`current_time` should be `sensor_reading.timestamp / 1e9`

**Comment by HaraldSchafer** [comment]
When I tested it made little difference, but thanks have improved since. Will try again when I am back.
