### ISSUE TITLE
2017 Jeep cherokee KL try fix  car unrecognized -Fingerprinting-

### ISSUE THREAD

**Issue by kellersing** [commaai/openpilot#20760]
i tired and trying to learn something else to fixing this edit, about how and why car unrecognized, our  2017 Jeep Cherokee has ACC, KLS or front camera forward ,   i think something maybe it would fix by fingerprinting if support to .     

![carfx](https://user-images.githubusercontent.com/83252469/116187448-8dba6980-a6f3-11eb-8692-9a645ffb8fea.PNG)

i am used window Powershell via SSH wifi and location to /data/openpilot/selfdrive/car/Chryler/values.py
nano values.py   >Edit>Save>Exit

i change edit values.py, please check this below picture,  if i am doing correct or what?

![CARFW](https://user-images.githubusercontent.com/83252469/116187650-e2f67b00-a6f3-11eb-9d35-2582c1fa10d8.PNG)

but the problem is,  after we Save and Exit Edit because it need require to reboot device however it already restore itself values lost of my edit,  ,     i dont quit understand about powershell or was it device self-heal, 

however after device reboot, i got error screen boot.    

![178771667_2950332885234580_8698461556349131712_n](https://user-images.githubusercontent.com/83252469/116188923-2e118d80-a6f6-11eb-9a99-9367652cadff.jpg)

sorry for my bad English due to my deaf language , thank you for patience

**Device/Version information (please complete the following information):**
 - Device: Comma Two Pink
 - Dongle ID: e82e1bae71399c09
 - Route: e82e1bae71399c09|2021-04-26--17-20-00
 - Version: 0.8.3

**Comment by kellersing** [comment]
@pd0wm would you check this for it?

**Comment by VirtuallyChris** [comment]
Jeep doesn't use FP 2.0 yet. Please get your fingerprint the old way and add it as a subset of the existing fingerprint.

**Comment by kellersing** [comment]
@VirtuallyChris  ok thank, i would try, on fingerprinting 1.0,   it a bit hard for me understand

**Comment by VirtuallyChris** [comment]
oh just noticed it's not a Grand Cherokee so it's not supported yet and will likely need a new car port. I'll close this issue for now.
