### ISSUE TITLE
KeyError:'dongle_id' - simulation UI is stuck in loading spinner 'registering device'

### ISSUE THREAD

**Issue by jbirtel** [commaai/openpilot#20767]
**Describe the bug**

After starting the OpenPilot docker with the provided script start_openpilot_docker.sh in openpilot/tools/sim, the UI window opens but I am stuck in the loading screen 'registering device'.
Tried it with different commits over the last few days and also on a different device/different OS.
This happens with or without being connected to the internet, I don't know if this is important.
However, it is possible to connect to CARLA and see the log output of the steering/break data, just the simulation is not visible as the UI is stuck in the spinner. 

**How to reproduce or log data**

I just simply started the docker with the script and then OpenPilot gets stuck in the loading screen.
After closing the window of OpenPilot and pushing `CTRL+C` in the terminal, I entered exit there to exit out of the root user. Then I got this error message:

getting pilotauth
failed to authenticate
Traceback (most recent call last):
  File "/openpilot/selfdrive/registration.py", line 72, in register
    dongle_id = dongleauth["dongle_id"]
KeyError: 'dongle_id'

**Expected behavior**

Normally, the loading spinner should hide after a short amount of time and the POV of the car in the CARLA simulation and a part of the comma device should be visible. 

Operating system: Ubuntu 18.04.5 LTS and also Ubuntu 20

**Comment by VirtuallyChris** [comment]
This should be fixed with https://github.com/commaai/openpilot/pull/20770
