### ISSUE TITLE
C++ cleanup

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#20799]
- [x] standardize file extensions to .cc and .h
- [ ] cleanup include paths, include from the root
- [x] replace ifdefs with the HW abstraction layer where possible

**Comment by adeebshihadeh** [comment]
@deanlee interested in this one? probably best to do each in a separate PR.

**Comment by adeebshihadeh** [comment]
@deanlee I think we can close this if we get rid of the opendbc/cereal paths in the include path

**Comment by ahowe444** [comment]
I notice there are still some .hpp in phonelibs/ directory. Are these meant to be standardized as well?
