### ISSUE TITLE
2017 Honda CRV LX AWD is no longer recognized in 0.8.4

### ISSUE THREAD

**Issue by spektor56** [commaai/openpilot#20809]
**Describe the bug**

When I start the car on 0.8.4 it says community features detected, I turn that on and restart the car.  Then I get the no exact match found error and that its going to use the 2017 Honda CRV EX

**How to reproduce or log data**

Update to 0.8.4

**Expected behavior**

Should be recognized as it was before

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: f280907e439de88d
 - Route: f280907e439de88d|2021-05-03--20-59-36
 - Version: 0.8.4
 - Car make/model: 2017 Honda CRV LX AWD (Canadian model)

**Comment by pd0wm** [comment]
Looks like the exact firmware versions of your car are not upstreamed, causing a fuzzy match. If you want the alert to go away, please make a PR with your firmware version.

In this case the trim level is not relevant, there is only type Honda CRV in our database. It's probably the trim level of the person who originally upstreamed the car. I'll see if I can remove trim levels from the car names to prevent confusion in the future.
