### ISSUE TITLE
[Feature request] data output (no obd)

### ISSUE THREAD

**Issue by Gouster4** [commaai/openpilot#2082]
Hi. Im wondering if i can use openpilot on ubuntu computer without panda or any other hardware. Just laptop with ubuntu, 2 webcams and arduino.
So openpilot would output values to selected com port (arduino) and arduino would take control of retrofitted components in any old car.
Everyone should program arduino by themself as its program would depend on retrofitted components.

**Comment by adeebshihadeh** [comment]
There's an example of something like this used for simulation. See `tools/sim/bridge.py`.
