### ISSUE TITLE
PSA Cars - Peugeot e2008

### ISSUE THREAD

**Issue by itrack** [commaai/openpilot#20832]
Hi!
Plans to integrate PSA cars in Openpilot? Like Peugeot e2008, Peugeot e208, Opel Corsa-e?

**Comment by VirtuallyChris** [comment]
That car likely doesn't have LKAS or ACC which is needed for openpilot. Plus, this isn't where you would ask to add support. All support comes from community contributions, so feel free to make a PR if you can get it working on your car!

**Comment by itrack** [comment]
But cars have LKAS and ACC, the cars is autonomous level 2

**Comment by dorkmo** [comment]
@itrack its hard to know for sure if a new vehicle will work will openpilot, you might start exploring the car's stock hardware. you might try to find the camera and its plugs. post pictures of what you find. it may share parts with other cars.

**Comment by VirtuallyChris** [comment]
Great if it has LKAS and ACC you will need to do a brand port. Theres some helpful info on some old blog posts on blog.comma.ai. Otherwise, the community needs to add support on their own. We have an #other-cars channel on discord.comma.ai if you want to ask for help from others.
