### ISSUE TITLE
hyundai accent 2016

### ISSUE THREAD

**Issue by gamerzvm** [commaai/openpilot#20884]
pls add the compatibility for hyundai accent 2016

**Comment by gamerzvm** [comment]
![image](https://user-images.githubusercontent.com/84055502/117908480-0d0e8680-b30b-11eb-996b-43545076cc27.png)

**Comment by gamerzvm** [comment]
i will add cruise control to my accent by the way

**Comment by pd0wm** [comment]
We don't accept issues for unsupported cars. If you want your car to be supported you have to make a PR. If you need help feel free to join our discord (http://discord.comma.ai/) and join the #hyundai-kia-genesis channel.
