### ISSUE TITLE
Toyota Corolla Hybrid 2021: Wrong Model Year

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#20890]
**Describe the bug**

I have a Toyota Corolla Hybrid 2021 but under my.comma.ai/useradmin it appears as a Toyota Corolla Hybrid 2019 model. I don't know if that affects performance in any way, just thought I would note that.

**How to reproduce or log data**

Not applicable.

**Expected behavior**

The right model and year should be recognized by Comma Two.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: cd21d47a9d46bdf3
 - Route: All
 - Timestamp: All
 - Version: 0.8.3
 - Car make/model: Toyota Corolla Hybrid 2021

**Additional context**

**Comment by vanillagorillaa** [comment]
This is normal. The "Toyota Corolla Hybrid" supports 2019, 2020, and 2021 models as they are all the same vehicle and we only list one vehicle year in the code.
