### ISSUE TITLE
 Following the preceding vehicle

### ISSUE THREAD

**Issue by jjg3873** [commaai/openpilot#2090]
The nature of following the vehicle ahead can lead to unwanted lane departure. I am currently using version 7.8. While running on the highway, I followed the car in front to the rest area.

**Comment by jjg3873** [comment]
Unwanted lane departure may occur due to following vehicle. I am currently using version 7.8. While driving on the highway, my vehicle followed the vehicle ahead and entered the rest area.

**Comment by michaelhonan** [comment]
@jjg3873 Please edit your issue to use the Bug Template. comma need much more information than what you have provided in order to investigate the issue.

See here: https://github.com/commaai/openpilot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
