### ISSUE TITLE
Simulation stops for invalid vehicle parameters

### ISSUE THREAD

**Issue by siggie0815** [commaai/openpilot#20909]
When starting latest OP simulation, few seconds after engaging OP it disengages with the following alert message: _"Vehicle Parameter Identification Failed"_

Also see this [discord conversation](https://discord.com/channels/469524606043160576/684457101455786017/841788306970247198).

The [proposed fix works](https://discord.com/channels/469524606043160576/684457101455786017/841953842991595570), but is obviously not intended to be used in real world use. However performance is much worse than on older commits.

I also can confirm, the issue did not exist before May 6th.

**Comment by creikey** [comment]
Ran a git bisect and fc3da5eaf9e9448825115e19dd59e1a2657ab249 seems to be the offender

**Comment by creikey** [comment]
Looking at that commit, replacing `if (log.getStandstill())` L287 of locationd.cc with `if (this->car_speed < 1e-3)` fixes the issue on master

**Comment by adeebshihadeh** [comment]
The sim doesn’t properly set the WHEELS_MOVING bit here https://github.com/commaai/openpilot/blob/master/tools/sim/lib/can.py#L42.

**Comment by creikey** [comment]
> The sim doesn’t properly set the WHEELS_MOVING bit here https://github.com/commaai/openpilot/blob/master/tools/sim/lib/can.py#L42.

Just curious, where are these car can messages parsed into updates for the CarState capnp struct?
