### ISSUE TITLE
Two-mile difference between car speedometer and OpenPilot

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#20918]
**Describe the bug**

The max speed setting on OpenPilot is always two miles below that displayed on my car. The real-time speed on OP is 1-2 miles/hour below my car's shown speed.

**How to reproduce or log data**

Driving on a highway, engage car cruise control, engage OP and set desired max cruise speed.

**Expected behavior**

I expect the max set speed to be the same on OP and my car's display.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: cd21d47a9d46bdf3
 - Route: cd21d47a9d46bdf3|2021-05-15--09-02-28
 - Timestamp: Entire route
 - Version: 0.8.3
 - Car make/model: Toyota Corolla Hybrid 2021

**Additional context**
None at this time.

**Comment by adeebshihadeh** [comment]
openpilot's speed is directly read from the wheels. The speedometer fudges the speed a bit to ensure that the displayed speed isn't lower than the actual speed. Currently, we've chosen to use the actual speeds, but we understand this is confusing and may revisit this in the future.
