### ISSUE TITLE
Radar not publishing firmware version 2018 Honda fit ex

### ISSUE THREAD

**Issue by el11nene11** [commaai/openpilot#20912]
![Screenshot_20210514-182736](https://user-images.githubusercontent.com/83991628/118337584-1bfb6180-b4e2-11eb-9070-9e86e790e8bb.jpg)

Comma 2 states on screen car not supported. Support says radar isn't publishing firmware version so it's causing this. 

Dongle id: 81ed6773e542b743
Route: 81ed6773e542b743|2021-05-14--17-07-24

**Comment by VirtuallyChris** [comment]
Please add your Dongle ID and a route as stated in the template when you create a bug.

**Comment by el11nene11** [comment]
> Please add your Dongle ID and a route as stated in the template when you create a bug.

Just edited

**Comment by adeebshihadeh** [comment]
@el11nene11 is this still an issue? I don't see any recent routes from your device.

**Comment by el11nene11** [comment]
No. This isn't an issue anymore. With the replacement comma two the issues were resolved. Thanks
