### ISSUE TITLE
Toyota: 2021 Highlander Platinum AWD Fingerprint (car not recognized) and Pre-Collision Malfunction

### ISSUE THREAD

**Issue by etc6849** [commaai/openpilot#20913]
**Describe the bug**
Car Not Recognized (was able to manually edit values.py using the following to get car recognized), but please add the car as it is in the supported list.

Fingerprint for 2021 Highlander Platinum AWD:
36: 8, 37: 8, 114: 5, 119: 6, 120: 4, 170: 8, 180: 8, 186: 4, 355: 5, 401: 8, 426: 6, 452: 8, 464: 8, 466: 8, 467: 8, 544: 4, 550: 8, 552: 4, 562: 6, 565: 8, 608: 8, 610: 8, 643: 7, 658: 8, 705: 8, 728: 8, 740: 5, 761: 8, 764: 8, 765: 8, 791: 8, 800: 8, 810: 2, 812: 8, 814: 8, 818: 8, 822: 8, 824: 8, 830: 7, 835: 8, 836: 8, 865: 8, 869: 7, 870: 7, 871: 2, 877: 8, 881: 8, 885: 8, 889: 8, 891: 8, 896: 8, 898: 8, 900: 6, 902: 6, 905: 8, 913: 8, 918: 8, 921: 8, 933: 8, 934: 8, 935: 8, 942: 8, 944: 8, 945: 8, 951: 8, 955: 8, 956: 8, 976: 1, 987: 8, 998: 5, 999: 7, 1000: 8, 1001: 8, 1002: 8, 1014: 8, 1017: 8, 1020: 8, 1041: 8, 1042: 8, 1044: 8, 1056: 8, 1059: 1, 1063: 8, 1076: 8, 1077: 8, 1082: 8, 1114: 8, 1161: 8, 1162: 8, 1163: 8, 1164: 8, 1165: 8, 1166: 8, 1167: 8, 1172: 8, 1228: 8, 1235: 8, 1237: 8, 1263: 8, 1264: 8, 1279: 8, 1541: 8, 1552: 8, 1553: 8, 1556: 8, 1557: 8, 1568: 8, 1570: 8, 1571: 8, 1572: 8, 1592: 8, 1593: 8, 1594: 8, 1595: 8, 1649: 8, 1653: 8, 1654: 8, 1655: 8, 1696: 8, 1745: 8, 1775: 8, 1779: 8, 1786: 8, 1787: 8, 1788: 8, 1789: 8, 1904: 8, 1912: 8

carFw = [
      ( ecu = eps,
        fwVersion = "8965B48310\000\000\000\000\000\000",
        address = 1953,
        subAddress = 0 ),
      ( ecu = esp,
        fwVersion = "\001F15260E051\000\000\000\000\000\000",
        address = 1968,
        subAddress = 0 ),
      ( ecu = engine,
        fwVersion = "\001896630EB2200\000\000\000\000",
        address = 1792,
        subAddress = 0 ),
      ( ecu = fwdRadar,
        fwVersion = "\0018821F6201200\000\000\000\000",
        address = 1872,
        subAddress = 15 ),
      ( ecu = fwdCamera,
        fwVersion = "\0028646F4803000\000\000\000\0008646G5301200\000\000\000\000",
        address = 1872,
        subAddress = 109 ) ],

Once you manually add the information above in the specified format (converting addresses to hex and remembering commas), a Pre-Collision Malfunction error on the dash once you enable openpilot.  If I disable openpilot and shut car off and back on, error goes away.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 73484e3ac5b1b0a7
 - Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
 - Timestamp: [When in the route the bug occurs (e.g. 4min 30s into the drive)]
 - Version: .8.3 release2 
![20210514_225651](https://user-images.githubusercontent.com/2585352/118346478-c63aaf80-b509-11eb-9d3b-b9809d7699d5.jpg)
![20210514_225623](https://user-images.githubusercontent.com/2585352/118346479-c89d0980-b509-11eb-943e-1b0e91aeaa70.jpg)
![20210514_222749](https://user-images.githubusercontent.com/2585352/118346480-ca66cd00-b509-11eb-94a1-99f986ac9c6f.jpg)

 - Car make/model: 2021 Toyota Highlander Platinum AWD

**Comment by adeebshihadeh** [comment]
A fix was shipped in the subsequent release (0.8.4) for the PCS fault. I also checked your logs, and your car's fingerprint is in release. Let us know if you have any more issues.
