### ISSUE TITLE
Failure to accelerate quickly after a cut-out

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#20920]
**Describe the bug**

OP fails to quickly accelerate when a slow car cuts out (moves to another lane). Had to press the gas pedal to accelerate as there were speeding cars behind me in the lane.

**How to reproduce or log data**

Have the lead car slow down considerably and switch lanes. OP will not accelerate quickly.

**Expected behavior**

OP should be able to detect a cut-out and begin acceleration much sooner.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: cd21d47a9d46bdf3
 - Route: cd21d47a9d46bdf3|2021-05-15--12-11-19--18
 - Timestamp: May 15 @ 12:29:32
 - Version: 0.8.3
 - Car make/model: Toyota Corolla Hybrid 2021

**Additional context**

![Screenshot 2021-05-15 172007](https://user-images.githubusercontent.com/9168908/118378429-d69e6900-b5a1-11eb-8cf8-9d1fad68c427.png)

**Comment by adam-nelson** [comment]
What happens if lead car changes his mind and you'll accelerate into him?

**Comment by pd0wm** [comment]
This stuff will get better once we switch to end-to-end longitudinal control. We won't be adding any hard-coded policy for this.

**Comment by adam-nelson** [comment]
Thanks. i had same opinion
