### ISSUE TITLE
Model bug: detecting bike lanes as lane lines

### ISSUE THREAD

**Issue by grekiki** [commaai/openpilot#20952]
On the route 650b1e4383a9baf2|2021-05-16--11-13-50 the model is often detecting the bike line on the sidewalk as the right lane line, thereby causing the car to move towards the curb. It also seems to like to classify the right road edge as a lane line. 

Have more such examples if useful. 

Attaching example image from explorer 
![Screenshot from 2021-05-18 22-13-26](https://user-images.githubusercontent.com/16437969/118717431-59cff100-b826-11eb-9f56-ab5a66854067.png)

**Comment by HaraldSchafer** [comment]
This is unfortunate, but we aren't really putting effort into lanelines anymore. All effort for lateral is now going into laneless.
