### ISSUE TITLE
Failed to slow down for stopped car

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#20976]
**Describe the bug**

OP was engaged and approaching a stopped car at a red light. The stopped car was detected but OP was not slowing down in time and my car's FCW came on and had to brake manually.

**How to reproduce or log data**

Approach a stopped car on a very large curve while OP is engaged.

**Expected behavior**

I expect OP to slow down a lot earlier for the stopped car.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: cd21d47a9d46bdf3
 - Route: cd21d47a9d46bdf3|2021-05-20--07-50-40--12
 - Timestamp: May 20 @ 08:02:55
 - Version: 0.8.4
 - Car make/model: 2021 Toyota Corolla Hybrid

**Additional context**
![Screenshot 2021-05-20 084503](https://user-images.githubusercontent.com/9168908/118980855-b971ed80-b947-11eb-850c-c82fa26b0d93.png)

**Comment by HaraldSchafer** [comment]
This is similar to https://github.com/commaai/openpilot/issues/20970

Closing and connecting. Will try to find a solution ASAP
