### ISSUE TITLE
Planner Solution Error with a new model (FCW)

### ISSUE THREAD

**Issue by yegor-mialyk** [commaai/openpilot#20986]
I'm on master-ci branch of 0.8.5: commit c3142c629a69070d0eef4250cb0d2d69fb5632a2 (origin/master-ci)

Was interested to test FCW feature (as crazy as it may sound). Had a few 5 to 20 min drives. And I got Planner Solution Error about 4 times. 2 times staying behind a lead car on intersection right after a lead car started moving.

 - Device: comma two
 - Dongle ID: b53343dbb47c5474
 - Car make/model: Hyundai Santa Fe 2020

P.S. OP FCW works fine in my not so crazy tests, sometimes it warns earlier than a Hyundai stock FCW, sometimes a bit later.
But OP catches cross traffic (which is cool).

**Comment by HaraldSchafer** [comment]
Should be fixed with 
https://github.com/commaai/openpilot/pull/20995
