### ISSUE TITLE
Move to C++ unlogger

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#20991]
We have parallel implementations of unlogger right now, the original python version and the new C++ version. The new unlogger doesn't lag and will support replaying from the UI (#2547). The old unlogger lives in `tools/replay/` and the new one lives in `selfdrive/ui/replay`. Once these TODOs are complete, we can completely remove the old unlogger.

- [x] fallback to qcams, ideally we don't require video either
- [x] add pause/play using spacebar
- [x] stop replay while waiting for video to load (the time is still progressing)
- [x] occasional OpenCL error on VisionIPC init
- [x] work with only 1 segment routes
- [x] show error when route is not found
- [x] sometimes replay starts in the second segment
- [x] add optional argument for start time
- [x] seeking by timestamp is not reliable, sometimes it seeks to a point and them immediately goes back to where you were
- [x] segfaults randomly
- [x] send YUV/RGB for all cameras

**Comment by adeebshihadeh** [comment]
@deanlee interested in this one? feel free to refactor LogReader and FrameReader as necessary, right now they seem unnecessarily tied to the replay use case.

**Comment by deanlee** [comment]
I'll split it into several PRs

**Comment by adeebshihadeh** [comment]
@deanlee startup seems to be super slow when the D/E cams are also uploaded

**Comment by deanlee** [comment]
#22308 should be able to solve this

**Comment by pd0wm** [comment]
Video looks strange when replaying using qcams now. Both on master and on #22195
![2021-09-23-224108_1905x1076_scrot](https://user-images.githubusercontent.com/1314752/134627987-b5188267-3482-4f52-a660-d2dab6125cae.png)

**Comment by deanlee** [comment]
@pd0wm that's strange. I can play qcamera normally on #22195 (demo route)

https://user-images.githubusercontent.com/27770/134628979-5ea438c5-2b5f-414f-a4c3-078f45356390.mp4

**Comment by deanlee** [comment]
I modified Segment::Segment() (#22195 ) on my laptop to test fall back to qcamera. the result does not seem to have any problems
```
  // fallback to qcamera
  static int i = 0;
  if (++i % 2 == 0) {
    road_cam_path_ = files_.road_cam.isEmpty() ? files_.qcamera : files_.road_cam;
  } else {
    road_cam_path_ = files_.qcamera.isEmpty() ? files_.road_cam : files_.qcamera;
  }
```

**Comment by deanlee** [comment]
- [ ] seeking stuck while segments is loading.
- [ ] framereader has a delay of 300-500ms after seeking.

**Comment by pd0wm** [comment]
> @pd0wm that's strange. I can play qcamera normally on #22195 (demo route)
> I modified Segment::Segment() (#22195 ) on my laptop to test fall back to qcamera. the result does not seem to have any problems
> 
> ```
>   // fallback to qcamera
>   static int i = 0;
>   if (++i % 2 == 0) {
>     road_cam_path_ = files_.road_cam.isEmpty() ? files_.qcamera : files_.road_cam;
>   } else {
>     road_cam_path_ = files_.qcamera.isEmpty() ? files_.road_cam : files_.qcamera;
>   }
> ```
> 
>  1.mp4

I was using a C3 route. Maybe that's different?

**Comment by deanlee** [comment]
> Can we control d/e cam using a command line flag? Think you don't need them most of the time.

Did you mean to load the driverCam/WideRoadCam only when there are -d or -e flags?

**Comment by pd0wm** [comment]
Yeah, that sounds good.

**Comment by pd0wm** [comment]
Noticed two more bugs while testing today:
 - Replay got stuck on a segment boundary, but that segment was already downloaded earlier according to the logs
 - When seeking into the route it started playing at that point, but no longer played in realtime but went as fast as it could.

**Comment by deanlee** [comment]
> Qcameras seem to be broken on C3 footage only.

#22238 May be able to solve this problem

> Do you need a route for testing?

yes, that would be much better to have a c3 demo route

**Comment by pd0wm** [comment]
Both problems might be related to a specific route I was replaying. Will do some more digging and let you know (`a8e8bf6a3864361b|2021-01-04--03-01-18`, t=840`)

**Comment by pd0wm** [comment]
@deanlee I don't really understand what's going on. The route should be public so you can look as well. To reproduce seek to t=840. If you have the same problem as me it will play fast for a couple seconds, and then play normally. Then seek back to t=840 again and it will play faster for the whole segment. Any ideas?

**Comment by deanlee** [comment]
> @deanlee I don't really understand what's going on. The route should be public so you can look as well. To reproduce seek to t=840. If you have the same problem as me it will play fast for a couple seconds, and then play normally. Then seek back to t=840 again and it will play faster for the whole segment. Any ideas?

@pd0wm  it looks like an old bug related to keep time. if the us_begin<1ms, the replay will not sleep to wait. #22348  resolved this bug

**Comment by pd0wm** [comment]
Can we make things more robust somehow? I don't think the code should be relying on the sleeps being ns accurate.

**Comment by deanlee** [comment]
This case is a bug( the replay will not sleep  if us_begin>1), not the accurate. I think #22195  is enough

**Comment by pd0wm** [comment]
Can we fix the visual glitches when seeking? I assume this is due to skipping past a keyframe?

**Comment by deanlee** [comment]
yes it is. I'm going to fix it in #22217

**Comment by deanlee** [comment]
The new demo route is not public 
```
"Error transferring https://api.commadotai.com/v1/route/4cf7a6ad03080c90%7C2021-09-29--13-46-36/files - server replied: FORBIDDEN"
failed load route "4cf7a6ad03080c90|2021-09-29--13-46-36" from server
```

**Comment by pd0wm** [comment]
Should be public now!

**Comment by deanlee** [comment]
#22238 can fix the transform problem on C3.
before:
![a](https://user-images.githubusercontent.com/27770/135435886-c09d0b76-134b-4217-8d98-77c7dfd65075.jpeg)
after:
![b](https://user-images.githubusercontent.com/27770/135435902-ef9446f4-64dd-45a2-9eff-d7e7f5e7a21c.jpeg)

**Comment by pd0wm** [comment]
Yeah, I'm aware. In the meantime you can also run with `TICI=1 ./ui`.
