### ISSUE TITLE
Deleter behavior not consistent for boot and crashlogs

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#21022]
The deleter looks at creation date of the folder. This doesn't work for the bootlogs and crashlogs, since the folder is created once but grows over time. When the deleter decides to wipe it, it removes the whole folder. These two folders need to be excluded from the folder logic, and needs be handled on a file-by-file basis by deleter.

**Comment by jyoung8607** [comment]
> The deleter looks at creation date of the folder. This doesn't work for the bootlogs and crashlogs, since the folder is created once but grows over time.

It's worse than that, it's doing a sort by the textual name of the directory, not the filesystem ctime. So the boot directory still stays at the top of the to-be-deleted list, even though it's getting deleted (and recreated) all the time.
