### ISSUE TITLE
2021 Rav4 Prime gets CAN Error even after the fingerprint is added (STEERING_LKA and PRE_COLLISION seems to have a different checksum scheme?)

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/openpilot#2103]
**Describe the bug**

2021 Rav4 Prime gets CAN Error even [after the fingerprint is added](https://github.com/commaai/openpilot/pull/2018). 

[We've checked the setup against another Rav4 and the harness and C2 do not show the same error message and believe the hardware to be sound.](https://discordapp.com/channels/469524606043160576/524327905937850394/749377789723148368)

We get this error:

![](https://media.discordapp.net/attachments/524327905937850394/748711512910069788/FQpE1sjDSO17Yy-SrAZ68cQiSZd-oakrEjM6gqwBML7pQIa3EmaBIKIft8pEGfu9mtpLqI_c6ULaw2OxssZq0MrZoWvS6rwgzwyY.png)

**How to reproduce or log data**

With a known-good Harness + C2 setup installed in the Rav4 Prime, checkout this branch on the C2: https://github.com/nelsonjchen/openpilot/tree/rav4_prime_fw @ commit 640ae8b

Start the Rav4 Prime.

**Expected behavior**

No CAN Error or `CHECKSUM FAIL` error in `tmux`.

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Dongle ID: 54bb533aec9ff844
 - Route: 54bb533aec9ff844\|2020-08-29--13-31-50
 - Timestamp: 158433520979974 from logs is when the error message is printed to the screen.
 - Version: https://github.com/nelsonjchen/openpilot/tree/rav4_prime_fw @ 640ae8b0b56a52a4eef662192967546e660c66a0
 - Car make/model: 2021 RAV4 Prime (VIN ends in 002147) 

**Additional context**

I've been helping matty#8553 on Discord add support for his 2021 Rav4 Prime to openpilot. Many others and I thought this was as simple as adding the [fingerprint for the TSS2 Rav4 Prime to OP](https://github.com/commaai/openpilot/pull/2018). This turns out to not be the case. 

After reproduction, we have SSH'd into the C2 and taken a look at `tmux a`, we see `CHECKSUM FAIL` spam:

![](https://media.discordapp.net/attachments/524327905937850394/749388683123097740/Screen_Shot_2020-08-29_at_3.02.57_PM.png?width=1237&height=911)

Looking at Cabana, it seems that `STEERING_LKA` is now 8 bytes in size up from 5 bytes in the past and that PRE_COLLISION IS size 8 up from 7.

I took a look at `STEERING_LKA` and tried the existing checksum algorithm [in a scratch-program, I implemented Toyota's checksum per the IOActive document to the last value and seeing if that pre-existing approach works for the RAV4 Prime's 8 byte `STEERING_LKA`. My unit tests work for my Corolla 2020's data. It doesn't for the 2021 Rav4 Prime's data and they don't match.](https://github.com/nelsonjchen/toyota_checksum_2020_scratch/blob/8422bd3b4b7770391e940d31202b8129fdebcb02/src/lib.rs#L97-L108)

The last four bytes for `STEERING_LKA` are rapidly changing. 

![high_entropy](https://user-images.githubusercontent.com/5363/91650158-ed5f5880-ea30-11ea-9b07-6e3dca7f8f83.gif)

I haven't taken a look at `PRE_COLLISION` other than noticing the size change. Using the existing algorithm on a value here doesn't seem to work either.

Unfortunately, I've hit the limits of what I can do right now. I think Toyota has changed the checksum scheme or something for `STEERING_LKA` and `PRE_COLLISION`. 

I am not the owner of this 2021 Rav4 Prime, matty#8553 on Discord is. 

Please reach out to matty#8553 if you need him to perform some diagnosis. If there may be something out of his depth and Comma staff or someone from the community is not available or willing to help him through the "boring" diagnosis parts such as setup/SSH/forks/etc, let me know and I will be happy to help walk matty#8553 through those tasks.

**Comment by adeebshihadeh** [comment]
This isn’t an issue - the RAV4 Prime isn’t listed as a supported car.

**Comment by jassdsu** [comment]
I have the same issue on my 2020 rav4 hybrid- I emailed support. Not sure if there is a solution or even if this is a supported vehicle anymore.

**Comment by wmoralesap** [comment]
Did you have any answer? I have the same issue with my 2020 rav4 hybrid.

**Comment by jassdsu** [comment]
I have 2020 Hybrid- you need change the program to the master-ci version. You need help with that?

On Sep 21, 2020, at 4:41 AM, Walter Morales <notifications@github.com> wrote:

﻿

Did you have any answer? I have the same issue with my 2020 rav4 hybrid.

**Comment by wmoralesap** [comment]
Yes please! How do I change to the master-ci version?

**Comment by jassdsu** [comment]
Firstly, have you verified that someone is using the Prime with Comma AI?  I did have the same error message so it sounds similar.  My parents are awaiting on their Prime to come in so I’ll be figuring this out soon- hopefully.

Start by downloading workbench (you’ll find the link for it on commas website) on your PC, and plugging your Comma unit in somewhere nearby on the same wifi as your PC.  Workbench communicates with the unit and it’ll allow you to update the operating system.

I have to track down the step by step instructions- its really not bad but it took me a while to understand how everything works.

**Comment by wmoralesap** [comment]
I already changed to master-ci version but now says dashcam mode: Car unrecognized. 
![Uploading 20200921_164728.jpg…]()

![Uploading 20200921_164809.jpg…]()

**Comment by jassdsu** [comment]
Nice work, now it needs to pair with your vehicle.  Leave the comma on for ten minutes and it should locate it.  If not, restart the comma and give it another 10 minutes.  You can turn your car off while doing this.

**Comment by wmoralesap** [comment]
I already tried it. The weirdest thing is that when thr engine is off, the comma 2 device shows vehicle connected. but when I turn it on, goes to dashcam mode. Do I need to fingerprint it?

**Comment by jassdsu** [comment]
Did it take about 30 minutes to install master-CI?  It takes a while and I’m wondering if it didn’t finish installing. I had a similar problem before I installed master-ci

**Comment by wmoralesap** [comment]
Yeah, installing master-ci took like 30 minutes.

**Comment by jassdsu** [comment]
Search for other people with your exact car- I know there’s a few users. Sorry- mine worked after I did all that.

If you find a solution let me know cause I’ll be dealing with this in a month.

On Sep 21, 2020, at 9:26 AM, Walter Morales <notifications@github.com> wrote:

﻿

Yeah, installing master-ci took like 30 minutes.

**Comment by wmoralesap** [comment]
I understand. Thanks for your support! I will reply back if I found a solution

**Comment by jassdsu** [comment]
Did you figure anything out?

On Sep 21, 2020, at 9:43 AM, Walter Morales <notifications@github.com> wrote:

﻿

I understand. Thanks for your support! I will reply back if I found a solution

**Comment by wmoralesap** [comment]
Yes, it was the fingerprint for the ESP. They already uploaded the new FW value and it works really good now.

**Comment by jassdsu** [comment]
What did you need to do differently? I’m not sure I understand.

On Sep 23, 2020, at 10:55 AM, Walter Morales <notifications@github.com> wrote:

﻿

Yes, it was the fingerprint for the ESP. They already uploaded the new FW value and it works really good now.

**Comment by jassdsu** [comment]
Awesome. Enjoy.

On Sep 23, 2020, at 11:05 AM, Walter Morales <notifications@github.com> wrote:

﻿

I just download the master-ci again. They uploaded a new version that fixed my problem.

**Comment by nelsonjchen** [comment]
@jassdsu @wmoralesap I hate to bother you two but could we keep the conversation here on the 2021 Rav4 Prime and/or the new `STEERING_LKA` message that is currently an unknown? It might be better if that were discussed on Discord (or perhaps if comma (read @VirtuallyChris) were to [ask for and setup GitHub Discussions on this repo](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/226))?

**Comment by jassdsu** [comment]
I don’t have the prime, I have the 2020 RAV4 hybrid and I have not experienced that issue. I know there are users with that vehicle that are running master CI and it’s working fine. I would recommend reaching out to them.

Are you currently experiencing the issue or are you just wondering about it?

On Sep 23, 2020, at 11:09 AM, Nelson Chen <notifications@github.com> wrote:

﻿

@jassdsu<https://github.com/jassdsu> @wmoralesap<https://github.com/wmoralesap> I hate to bother you two but could we keep the conversation here on the 2021 Rav4 Prime and/or the new STEERING_LKA message that is currently an unknown? It might be better if that were discussed on Discord (or perhaps if comma (read @VirtuallyChris<https://github.com/VirtuallyChris>) were to ask for and setup GitHub Discussions on this repo<https://github.community/t/can-one-apply-for-github-discussions-beta/121120/226>)?

**Comment by nelsonjchen** [comment]
@jassdsu This GitHub issue is about the 2021 Rav4 Prime.

**Comment by nelsonjchen** [comment]
I've since started a sheet to organize and record a community bounty for the ECU Security Key issue that is likely the nature of this new "code":

https://docs.google.com/spreadsheets/d/1MKS78_utvbAe74Xv7zszgEnn6JrtBgpgYlVOfoIvLEw/edit#gid=0

**Comment by jonvkw** [comment]
Does anyone know if the source of the key is from the front facing camera or ECU?  I was wondering if swapping the front facing camera from another lower year Rav4 may revert to 5 byte LKA message?

**Comment by adeebshihadeh** [comment]
Locked the conversation since this issue was closed. Let's move the discussion over to our GitHub Discussions page.

**Comment by adeebshihadeh** [comment]
Relevant discussion: https://github.com/commaai/openpilot/discussions/19932
