### ISSUE TITLE
What other functions does Panda have besides communicating with the vehicle ?

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21037]
**Describe the bug**
I use the webcam tool to run openpilot on PC. We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC to two web cameras. If I use Panda connect to computer, I would like to ask what is the function of Panda. Besides communicating with the vehicle, what other functions does Panda have. Is there any detailed guideline about Panda?
Looking forward your reply, thanks. 

Operating system: [e.g. Ubuntu 20.04]

**Comment by pd0wm** [comment]
Let's merge these two issues: https://github.com/commaai/openpilot/issues/21038
