### ISSUE TITLE
ui dispaly NO PANDA when input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21038]
**Describe the bug**
I use the webcam tool to run openpilot on PC. We refer to the guideline and connected the PC to two web cameras and CAN card(We use CAN card instead of Panda). When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", report " Connecting to panda
starting python selfdrive.loggerd.uploader
deviceState: Reader was evicted, reconnecting
"Error transferring https://api.commadotai.com/v1/devices/UnregisteredDevice/owner - server replied: NOT FOUND"
"Error transferring https://api.commadotai.com/v1.1/devices/UnregisteredDevice/ - server replied: NOT FOUND"
The ui interface is as follows and how to solve it, looking forward to your reply. 
![Screenshot from 2021-05-26 13-56-27](https://user-images.githubusercontent.com/84113314/119609468-34e10c80-be2a-11eb-8aca-07fa0cd39fc4.png)

**Expected behavior**
The UI could display Openpilot correctly

**Additional context**

Operating system: [e.g. Ubuntu 20.04]

**Comment by pd0wm** [comment]
What is a CAN card? Openpilot only works using a panda.

**Comment by LIHaoran-good** [comment]
CAN card is also used to communicate with vehicle, which is the same as Panda

**Comment by LIHaoran-good** [comment]
@pd0wm Hi,  I see the **OpenCL Driver** is mentioned in [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam), so I want to ask what is the function of the **OpenCL Driver**?
Thanks for your reply.

**Comment by adeebshihadeh** [comment]
If you want to use your "CAN card", you'll need to modify boardd. OpenCL is used in camerad and modeld.

**Comment by LIHaoran-good** [comment]
@adeebshihadeh Hi， how to install OpenCL Driver, do you have the guideline, thanks.
