### ISSUE TITLE
Comma 2 records drives even when parked, happens until comma crashes.

### ISSUE THREAD

**Issue by pk-r7** [commaai/openpilot#21034]
**Describe the bug**

Device continuously records routes even when vehicle is parked. The comma 2 I am using is a replacement and previous unit suffered from this issue when running the main release as well as a fork.  The unit wakes up and records a short drive for less than a minute. At some point it locks up and has to be either soft (via power) or hard rebooted. I have verified electrically the ignition pin is not signaling a wake up. I have a Tesla so the ignition pin is not connected. 

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: a7102f281a94d75b
 - Route: all
 - Timestamp: regular intervales
 - Version: release
 - Car make/model: Tesla Model S AP1

**Additional context**

Image attached of the behavior:
<img width="1320" alt="Capto_Capture 2021-05-24_11-00-54_AM" src="https://user-images.githubusercontent.com/35041244/119584746-1c1b1d00-bd7e-11eb-880c-1da1dd5816c2.png">

**Comment by adeebshihadeh** [comment]
We don't support or sell a harness for any Tesla models. I'm not sure how you connected your car to the comma two, but that's likely the issue here. In your device's logs, I'm seeing the ignition line go high.
