### ISSUE TITLE
Honda: do same checks in panda and carState

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#21055]
There's about 50 mismatches on the Honda CRV Hybrid for `brakePressed` between carState and panda

**Comment by pd0wm** [comment]
Are you using a route from before https://github.com/commaai/openpilot/commit/4215f63769fd6f350194cf5b6c9607cce40e18e0 was merged? It was using the wrong signal in the panda for a while.

**Comment by adeebshihadeh** [comment]
This test just replays the CAN messages through openpilot and panda, so that wouldn't affect this.

**Comment by loveloveses** [comment]
I think the mismatches is as the ibootser use for brake when use acc
the ibooster can give -0.2g for brake，when the car need more for brake，the VSA will simulation an brake，and the brakelight will light on

**Comment by loveloveses** [comment]
i have open an issue as #19838，but it is closed

**Comment by adeebshihadeh** [comment]
This is covered by #23643
