### ISSUE TITLE
Changing lanes then changing back causes lane change assist to continue trying to change lanes in the previous direction.

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#21118]
**Describe the bug**

Signaling and using lane change assist to change lanes back and fourth in rapid succession, like when passing a parked car, causes lane change assist to continue trying to change lanes in the first direction signaled, and will fight you on the change back to the original lane.

For example: You're in the right lane and there is a parked car in front, you signal and change left to pass the parked car with lane change assist, then immediately signal right again before lane change assist completes. After lane change assist completes the left lane change, it will think you're signaling and trying to make another left lane change despite signaling right. OP will fight you during the entirety of the right lane change.

**How to reproduce or log data**

Signal and change lanes in one direction, then immediately signal in the opposite direction while the initial lane change is still completing. After the initial lane change completes, OP will think that you're trying to make a second lane change in the same direction, instead of back to your previous lane as you've signaled.

**Expected behavior**

For lane change assist to realize that the direction signaled has changed.

**Device/Version information (please complete the following information):**
 - Device: Comma2
 - Dongle ID: 903210ecc0cb706b
 - Route: 903210ecc0cb706b|2021-06-02--23-18-38--11
 - Timestamp: 23:30:00
 - Version: 0.8.4
 - Car make/model: VW Golf R Manual

**Additional context**

IIRC, if you turn your signal off, and then re-trigger it will "fix" the problem, however if you re-trigger your signal in a different direction from the first one while lane change assist is working, it will not realize the direction has changed.

Talking to @jyoung8607, he thinks  it may have regressed in #20765

Let me know if you have more questions. :)

**Comment by pd0wm** [comment]
You're right, that is a regression from that PR. I changed the logic to determine lane change direction in the `preLaneChange` state now. The first state was skipped when you make more than one lane change in succession.
