### ISSUE TITLE
Support for Hyundai PHEVs

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#21114]

**Comment by YawWashout** [comment]
OOOOOOO OOOOOOOO OOOOOOOOOOO!!!!!!

if you help out the Hyundai IONIQ PHEV 2020.... I'll... I'll probably do nothing because I'm useless but man I'd be happy!

**Comment by ShaneSmiskol** [comment]
To Support:

- [ ] Ioniq PHEV 2020 (needs new dbc)
- [ ] Sonata HEV 2020 (unsure)

**Comment by ShaneSmiskol** [comment]
Why did this not get merged? If there's a common signal we don't need another DBC: https://github.com/commaai/panda/pull/583/files
