### ISSUE TITLE
DM doesn't detect if my eyes are closed, or asleep

### ISSUE THREAD

**Issue by zorrobyte** [commaai/openpilot#21145]
While DM does a great job badgering me if I'm distracted, DM doesn't seem to care if I'm sleeping or passed out. Next time you are in a safe environment, try closing your eyes and pretending you are sleeping, or worse, passed out.

Good DM would help prevent crashes such as:
https://youtu.be/lssmh4GH188

Edit: Uploading some routes as I duplicate...

**Comment by zorrobyte** [comment]
Sat in my car in various poses with my eyes closed. Received the "Keep eyes on road" alert but never a disengagement:
d5b9bf105ad64d5d|2021-06-04--18-46-24

Maybe timeout is just super high? Feels like something isn't working properly with how quick DM chastises me for looking at my phone, head unit. I'm happy to replicate further and go on longer "drives".

**Comment by ZwX1616** [comment]
Hmm the alerts don't go beyond green if the car is at standstill.

**Comment by zorrobyte** [comment]
Feature not bug, closing
