### ISSUE TITLE
VIDEOIO ERROR: V4L2: Could not obtain specifics of capture window. VIDEOIO ERROR: V4L: can't open camera by index 1

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21164]
**Describe the bug**
I use the webcam tool to run openpilot on PC. We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC to two web cameras and Panda. When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", report the error "VIDEOIO ERROR: V4L2: Could not obtain specifics of capture window. VIDEOIO ERROR: V4L: can't open camera by index 1", details please refer to below picture. How to solve it ? Thanks.
![Screenshot from 2021-06-06 19-17-23](https://user-images.githubusercontent.com/84113314/120922502-1b7a7300-c6fc-11eb-9a1b-c47661575a1e.png)

**How to reproduce or log data**

When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

**Expected behavior**

**Additional context**

Operating system: [e.g. Ubuntu 20.04]

**Comment by iHelp101** [comment]
Run "ls /dev/video*" to find your webcam IDs. It is likely that the webcams are not mapped to the standard IDs. You can then adjust camera_webcam to match the IDs.

**Comment by LIHaoran-good** [comment]
@iHelp101 Thanks for your reply.   After I verified the webcam IDs in camera_webcam.cc,  it is ok
