### ISSUE TITLE
report the error "Immediately connect to the internet to check for updates" when input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21163]
**Describe the bug**
I use the webcam tool to run openpilot on PC. We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC to two web cameras and Panda. When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", report "Immediately connect to the internet to check for updates",  details please refer to below picture. How to solve it ? Thanks.
![Screenshot from 2021-06-06 16-17-14](https://user-images.githubusercontent.com/84113314/120917861-17daf200-c6e4-11eb-9618-cfd5e36f2df5.png)

**Expected behavior**

Openpilot can run successfully

**Additional context**

Operating system: [e.g. Ubuntu 【20.04]

**Comment by pd0wm** [comment]
Have you tried running updated on PC? This can be solved by clearing your params folder (`~/.comma/params`)

**Comment by adeebshihadeh** [comment]
Fixed in 29ac94b71997303fdd2cae137a1a3ccd016868e7. After clearing your params, you shouldn't see this again.
