### ISSUE TITLE
Model failes to properly handle and intrudes into "fifth lane" protected turn lanes. (Not TWLTLs)

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#21162]
**Describe the bug**
So, I don't know what the proper name is for this type of turn lane, but it's very common in my city.
There is a protected 3rd or 5th lane that "grows" out the middle for people to turn left at. It's a protected left turn, and not a Two-Way Left-Turn Lane. The other lanes going in that same direction, do an S bend around it and rejoin back in their original positions after the intersection.

OpenPilot routinely just continues straight, cutting into these left turn lanes making little effort to navigate around most of them, unless they are long and slow (which most aren't in my city).
A couple good examples of this:
https://www.google.com/maps/place/45%C2%B024'30.3%22N+75%C2%B040'39.2%22W/@45.4084184,-75.6776809,49m/data=!3m1!1e3!4m14!1m7!3m6!1s0x0:0x0!2zNDXCsDI0JzMwLjMiTiA3NcKwNDAnMzkuMiJX!3b1!8m2!3d45.4084167!4d-75.6775556!3m5!1s0x0:0x0!7e2!8m2!3d45.4084254!4d-75.6775541
https://www.google.com/maps/place/45%C2%B023'57.6%22N+75%C2%B038'54.6%22W/@45.3993279,-75.6490542,197m/data=!3m2!1e3!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d45.3993269!4d-75.6485072

Both these left turn lanes predictably cause OP to continue straight through them instead of going around them.

**How to reproduce or log data**

Engage OpenPilot on a road with these protected temporary 3rd/5th left turn lanes. And make sure you're in the lane that the protected left will "grow" into.
As the protected left grows into your lane, OpenPilot will fail to move over to the right along with your lane. However, if it's a 4 lane road becoming a 5 lane road, and you're not in the left most lane, and instead in the right most lane, OP will track your lane properly.

**Expected behavior**

For OP to not change lanes unexpectedly, and continue tracking the lane as it makes it's S bend around the new protected left.

**Device/Version information (please complete the following information):**
 - Device: C2
 - Dongle ID: 903210ecc0cb706b
 - Route: 903210ecc0cb706b|2021-06-05--23-46-30--3
 - Timestamp: 23:50:20
 - Version: at least since 0.8.3, possibly before.
 - Car make/model: 2019 VW Golf R, Manual

**Additional context**

This bug has been around for a while, I'm currently on the master-ci branch, however this was happening on the released versions of 0.8.4, 0.8.3 and I'm pretty sure on 0.7.4 and up thought I can't be certain. I decided to see if I could find other reports, and I couldn't so I decided to create an issue for it. :)

**Comment by HaraldSchafer** [comment]
Closing this, this is part of the general improving laneless driving project. Not really actionable with a specific fix, thanks for the report!

**Comment by nabeelr** [comment]
Thanks for the input Harald. 

Should I avoid these kind of reports in the future?

Any feedback on making my feedback more valuable to the team?

**Comment by HaraldSchafer** [comment]
For us they can still be useful, especially detailed ones like this. It keeps us aware of the failures people are experiencing and gives us data to look at to test fixes for certain failures. 

But we do prefer to have them closed if there is not an immediate fix in sight.

**Comment by nabeelr** [comment]
Cool, good to know. If I'm every submitting things that aren't helpful or too often, please let me know. 😉
