### ISSUE TITLE
ui interface displays NO Panda

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21171]
**Describe the bug**

I use the webcam tool to run openpilot on PC. We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC to two web cameras and Panda. When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", the webcam view can be displayed , but displays NO Panda, details please refer to below picture. How to solve it ? Thanks.

![Screenshot from 2021-06-07 20-50-53](https://user-images.githubusercontent.com/84113314/121020784-4a174d00-c7d3-11eb-8671-61f5797493be.png)

**How to reproduce or log data**
input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

**Expected behavior**

**Additional context**

Operating system: [e.g. Ubuntu {20.04]

**Comment by pd0wm** [comment]
Can you post your manager.py output?

**Comment by adeebshihadeh** [comment]
We like to keep our issue tracker to bugs and enhancements. Our [community discord](https://discord.comma.ai/) is a better place to get openpilot running.
