### ISSUE TITLE
Slow frame rate in webcam mode 

### ISSUE THREAD

**Issue by davidtena98** [commaai/openpilot#21176]
**Describe the bug**

After running OpenPilot on PC noticed that the the queue "frame" was not sending 1200 messages per segment, but way less. The frame rate was about 5 fps. I'm Using a Logitech C920, which should be fine since its inside your camera_init module inside camera_webcam.cc.

**How to reproduce or log data**

Simply by running OP for the webcam environment and checking then the generated logs. The amount of messages in logReader of type "frame" indicate the amount of messages of such queue.

**Expected behavior**

something close to 1200 messages to reach the 20Hz.

**Additional context**

It's disconcerting since the camera initialization indicates OpenCV that the capture will be at 20 FPS, but as I said before, the frame messages are sent to the queue at a much slower rate that that.

Operating system:
- Ubuntu 20.04
- Graphics: Nvidia GFORCE GTX 1050
- OpenCV: compiled version 4.5

**Comment by adeebshihadeh** [comment]
The webcam camera driver isn't an actively maintained target, and performance isn't really tested or guaranteed. However, we'll certainly merge improvements and CI tests to improve the quality.
