### ISSUE TITLE
"Error transferring https://api.commadotai.com/v1.1/devices/UnregisteredDevice/stats - server replied: NOT FOUND"

### ISSUE THREAD

**Issue by hiccup-luohao** [commaai/openpilot#21190]
I use openpilot and Carla to simulate .but have the  problem "Error transferring https://api.commadotai.com/v1.1/devices/UnregisteredDevice/stats - server replied: NOT FOUND"

**Comment by pd0wm** [comment]
This error is expected. If your device is not registered we can't fetch the drive statistics. I would merge a PR that would prevent the API request from being sent if there is no valid dongle id.

**Comment by hiccup-luohao** [comment]
Thank you.I use the latest master branch, and there is a problem in the simulation: openpilot unavailable communication issue between processes.

**Comment by hiccup-luohao** [comment]
How can I solve it .
