### ISSUE TITLE
Replace frame stream with replay

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#21202]
Now that we have a nice way to use vipc from python, we no longer need camera_frame_stream. We still need a default camera driver for PC, so I think it would be nice to replace it with a replay using one of the public [test routes](https://github.com/commaai/openpilot/blob/master/selfdrive/test/test_routes.py).

**Comment by adeebshihadeh** [comment]
@deanlee interested in this one?

**Comment by deanlee** [comment]
do we need to support driver camera in camera_pc? there is no dcamera in public test ruotes

**Comment by adeebshihadeh** [comment]
I’d like to support it. Here’s a public route with dcam: 534ccd8a0950a00c|2021-06-08--12-15-37.

**Comment by deanlee** [comment]
https://commadataci.blob.core.windows.net/openpilotci/534ccd8a0950a00c/2021-06-08--12-15-37/0/dcamera.hevc:
BlobNotFoundThe specified blob does not exist

**Comment by deanlee** [comment]
#21241
