### ISSUE TITLE
Better way to decrease speed

### ISSUE THREAD

**Issue by chicman** [commaai/openpilot#21240]
If driver decrease MAX Set, OP will apply break for even 1 mph/kph difference. 
Not a smooth way nor a economic way.

Here is my suggestion:
As my understanding to most Japan/Korean cars, stock ACC would let the vehicle coast/slide without the break, if the decrease MAX Set is less than about 3~7 mph/kph. 
Since the drag will do the job for such minor slow down , this results a lot smoother long control/experience.

FYR

**Comment by pd0wm** [comment]
Think this preference is very user specific. The German cars are lot stricter with following the speed.

Until we have a way to predict what the user actually wants depending on the traffic situation we'll keep the current behavior.
