### ISSUE TITLE
Meta: Community Wiki Changes Immediate

### ISSUE THREAD

**Issue by ChadBailey** [commaai/openpilot#21268]
I recently modified the community wiki page https://github.com/commaai/openpilot/wiki/SSH and the changes were live immediately with no approval process (see the [history](https://github.com/commaai/openpilot/wiki/SSH/_history) for [my change](https://github.com/commaai/openpilot/wiki/SSH/_compare/d87660be1885cdfa8bd9922d38e476899a3d4fb4...754b77091e9b36acbac4f46349269c9107992ed7)). I'm not even certain anyone is notified that changes have been made. Can I have someone peer review the changes I've made? (I added the Experienced Developer Quick Start)

This behavior may be intentional, but I looked for anything discussing this and couldn't find it. I'm opening this report since the policy could be abused by spam bots.

Best of memory, when I've made similar changes in other projects it generated a pull request to the wiki directly in browser. Perhaps my mind has fabricated this memory though.

**Comment by adeebshihadeh** [comment]
This is intentional. The README's in the repo are intended to be authoritative, while the wiki is community maintained (see the [SSH README](https://github.com/commaai/openpilot/blob/master/tools/ssh/README.md) as an example). AFAIK, there is no feature like the one you remember in GitHub Wikis.

**Comment by ChadBailey** [comment]
Thanks for the explanation. This open-and-shut bug report should now help future people curious about this, so I think it was worth the effort in the end.
