### ISSUE TITLE
ui interface display error " Dashcam mode for unsupported car "and "Camera Malfunction"

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21291]
**Describe the bug**

I use the webcam tool to run openpilot on PC and Vehicle . We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC and vehicle(SuperB 2018) to two web cameras and Panda .When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", the webcam view can be displayed , but displays error " Dashcam mode for unsupported car "and "Camera Malfunction", How to solve it ? Thanks.

**How to reproduce or log data**
input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

**Expected behavior**

**Additional context**

Operating system: [e.g. Ubuntu 20.04]

**Comment by adeebshihadeh** [comment]
The camera malfunction alert shows if the cameras are not running at the expected frequency. Please use the community discord for further help getting setup. The issue tracker is not the right place to get help.
