### ISSUE TITLE
UX Improvement for Settings Page

### ISSUE THREAD

**Issue by C0mpl3t3N00b** [commaai/openpilot#21304]
**Problem:** 

Many users are not aware that some options in the _Settings->Device_ page are actionable beyond the CTA's (Call to Action) that are on the far right. This paradigm is not consistent in the UI since not all areas of the UI will behave the same despite not having any differentiating visual cues.

Refer to:

- When Driver Camera area is tapped, more information can be expanded
- When Camera Calibration is tapped, information regarding the accuracy of the mount is displayed for users to understand how well they have installed the device and is also great information to share when troubleshooting.

**Solution:**

Place a visual signifier beside the options that can be expanded, so users know that specific line is different from the rest. Please examples below:

![Comma-Suggestion](https://user-images.githubusercontent.com/70859798/122292517-e95ed300-ceaa-11eb-8189-30dbf02ff18e.png)

![Comma-Suggestion2](https://user-images.githubusercontent.com/70859798/122292874-51adb480-ceab-11eb-9aac-6dabae7e313a.png)

**Note:**

_Space between text and icon/symbol should be at the minimum 3 spaces so eligibility between text and icon/symbol is retained._

This is just an interim solution until Comma rolls out their new UI, but just like Comma is a shippable intermediary, this simple UI change can benefit the customers and users of OpenPilot in the short term.

**Resources:**

https://www.compart.com/en/unicode/U+24D8 

https://www.compart.com/en/unicode/U+2304

**Comment by adeebshihadeh** [comment]
We've decided to not ship intermediate design changes like this until we have the time for a proper design refresh.
