### ISSUE TITLE
Calibration Invalid Error

### ISSUE THREAD

**Issue by JTFINDUSTRIES** [commaai/openpilot#21303]
To whom it may concern;

I have a comma 2 that has worked fine until recently. I didn't drive my car for a week while I was on vacation. When I got back the comma 2 showed an update was available and that if I didn't connect to the internet in 0 days openpilot would be unavailable. However, my comma 2 was connected to my home wifi and even reconnected several times to confirm. I still could not click on the update. So I uninstalled openpilot and reinstalled under the premise that the new install would be the latest version. This morning the openpilot recalibrated and drove as normal. When I got in my car after work it said calibration invalid please clear and recalibrate. I did that several times and each time it said recalibrate. Getting frustrated I did the uninstall and reinstall again. Again the calibration failed. What is wrong with my comma 2? I've attached pictures of the serial number and error codes. Please advise. Thanks. 

Sincerely, 

Justin T. Fowler

**Comment by VirtuallyChris** [comment]
Hi Justin, we replied via a support email. Check your spam, some emails weren't getting through yesterday.

**Comment by JTFINDUSTRIES** [comment]
It is working after repositioning my comma 2. Thanks!
