### ISSUE TITLE
Model (desiredAngledDeg) oversteering. 

### ISSUE THREAD

**Issue by ClockeNessMnstr** [commaai/openpilot#21346]
On sharper turns the model is making large corrections after over steering turns.

With the Hud you can especially see the sharp changes in target directory as the model first over steers and then tries to correct. 

Route segment:
a3586311666ae480|2021-06-18--16-44-45--10

In the PID log we can see the target angle is achieved well and not overshot although it is held longer as the desired falls. 

First, the oversteer, it noticably moves to the inside. This could be a slightly missed steering ratio being learned. Or maybe the model is cutting the corner.

This happens every time.

**Comment by ClockeNessMnstr** [comment]
![PXL_20210618_205755982 MP](https://user-images.githubusercontent.com/6653860/123180803-091d6a80-d45a-11eb-8682-73300e07e808.jpg)

**Comment by ClockeNessMnstr** [comment]
going to try and figure out the tuning holding the angle for about 1 sec.

**Comment by pd0wm** [comment]
As far as I can tell the turn is too tight to be fully visible in the limited model box. This causes the model to guess and overestimate the turn. When it gets farther into the turn it sees more and corrects.

**Comment by ClockeNessMnstr** [comment]
makes more sense. when i get a chance, hopefully I can get a little more aggressive on the tune without making any oscillations anywhere else.

**Comment by pd0wm** [comment]
You don't want to fix this with (PID) tuning. The only task of the PID controller is to follow the desired angle as closely as possible. If the model is wrong there isn't much you can do about it.

**Comment by ClockeNessMnstr** [comment]
Thanks, you're correct. It won't be quite right/corrected. the PID looks just a touch sloppy tracking at the higher angle. looks like the desired angle is at least a little further from the lanes/curb even though it will still move around in the lane here.

**Comment by ClockeNessMnstr** [comment]
![Screenshot from 2021-06-26 09-48-40](https://user-images.githubusercontent.com/6653860/123515006-d21aa500-d663-11eb-8750-bec63f35963c.png)

**Comment by ClockeNessMnstr** [comment]
This is on my other vehicle. the height should be the only difference. (both mounted centered and within 1deg up/lat)

Possibly not the model? unless it makes sense that height could interfere?

**Comment by pd0wm** [comment]
In your example route I plotted the model on top of a map, and it was definitely overestimating the curvature of the turn.

**Comment by ClockeNessMnstr** [comment]
![Screenshot from 2021-07-03 10-45-55](https://user-images.githubusercontent.com/6653860/124396830-fa487a80-dcd9-11eb-9bd8-8270db683bc7.png)

**Comment by ClockeNessMnstr** [comment]
got better tracking on the forester. the ramp up is limited by the eps to about 30/2047 per 0.02s

**Comment by pd0wm** [comment]
You're saying it was ignoring the request because the request was ramping up too quickly?

**Comment by ClockeNessMnstr** [comment]
Not totally ignoring, but spending a lot of time in a steering "deadzone" and eps not keeping up with requested ramp up/down rate

 the eps wass actually decreasing torque longer than the LKAS was decreasing since even when lkas increases for a few steps it's lower than the eps torque reached. 

Some of the improvement is just setting the ramp_up limits even lower to match eps behavior. Then when the controller changes direction from the steering moving, the eps also changes immediately.

The rest of my improvement is the back calculation PR. Otherwise the integrator is winding up more against the ramp up limits.

**Comment by ClockeNessMnstr** [comment]
![Screenshot from 2021-07-03 02-40-30](https://user-images.githubusercontent.com/6653860/124468798-91a7df00-dd67-11eb-8aea-9bf669120782.png)
![Screenshot from 2021-07-03 02-46-07](https://user-images.githubusercontent.com/6653860/124468810-953b6600-dd67-11eb-9dd3-d275d7c3da74.png)

**Comment by ClockeNessMnstr** [comment]
different/exaggerated scenario but here is a recovery from holding the steering off course and releasing. Same tune but the first is unstable because of the lag in the torque request from the LKAS ramp up/down being to high.

**Comment by pd0wm** [comment]
I agree that we should probably limit the integrator when it's hitting the ramp limits.

Have you tried using the `freeze_integrator` input to the pid controller? Maybe it's as simple as

`latcontrol_pid.py:42`
```python
      output_steer = self.pid.update(angle_steers_des, CS.steeringAngleDeg, check_saturation=check_saturation, override=CS.steeringPressed,
                                     feedforward=steer_feedforward, speed=CS.vEgo, deadzone=deadzone, freeze_intergrator=CS.steeringRateLimited)
```

**Comment by ClockeNessMnstr** [comment]
freeze integrator if reaching the ramp up limits would work a little but we'd lose too much integrator action hitting the limits all the time. 
could also feed back a "saturation direction" (-1, 0, 1) to enable clamping on ramp up saturation like currently done with the absolute limits.
but, yes, at that point it's cleaner to just feedback the saturated output and we can back-calculating to get the most anti-windup benefit. 

In the screenshots above the integrator is actually reversed by the back-calculation during driver-override. This gives a smoother / more stable release of the steering wheel than if it was clamped at it's previous value.
