### ISSUE TITLE
Tie RHD mode to fingerprints.

### ISSUE THREAD

**Issue by ClockeNessMnstr** [commaai/openpilot#21345]
I'm not sure if all right hand vehicles will have different firmware in their fpv2 fingerprints but if they do we could get rid of the toggle for right hand drive and tie everything to fingerprints. 

Currently the right hand toggle could possibly be abused?

This came up talking about
https://github.com/commaai/openpilot/issues/21344

Under the assumption we want to limit changes to the driver monitoring window. This might go hand in hand with adding an adjustment parameter to vehicles based on their windshield/driver seat position.

**Comment by adeebshihadeh** [comment]
We've discussed and thought about a few different things for handling RHD, and we've settled on the toggle. Assuming this information happens to be in the fw version strings for all the makes, maintaining a separate list of RHD fw would be difficult to maintain.
