### ISSUE TITLE
[DM] Expand Area Used For Facial Tracking in Driver-Facing Camera

### ISSUE THREAD

**Issue by BadOlives** [commaai/openpilot#21344]
My device is mounted in a position where the driver-facing camera can still see my face, but only half of my face fits in the frame currently used for Driver Monitoring. This is causing DM to think that a driver is not looking at the road, when indeed I am. The current size of the frame being used restricts the mounting position of the device. I could mount my device lower, but I would be compromising my view of what's in front of me. I am suggesting to expand the frame to cover that gap not used for DM currently or to increase the width closer to the left edge of the screen (if looking at the preview in Driver Camera) in left-hand drive mode. Also incorporate this into right-hand drive mode by doing the equivalent to the right edge. This will allow users to have a bit more freedom in mounting their devices without having to worry about OP not working properly due to DM issues. A few ways to implement this solution:

1) Expand frame all the way to the left (LHD) and right (RHD) completely/partially.

OR

2) Implement an offset that the user can change in settings and set a maximum adjustment limit that a user can use so that the passenger can't be used to engage or keep OP engaged.

OR

3) Keep the current size of the frame and instead move it as far left (LHD) or right (RHD) that the camera is able to see.

Image below shows a rough estimate of the current frame used by DM in left-hand drive mode. Grey area can be be seen by the camera, but only the green area is used for facial tracking currently.

![Facial Tracking Area](https://user-images.githubusercontent.com/35647712/122655911-1c070680-d10b-11eb-92b8-2115936e6734.png)

If you are worried about the risk of someone taking advantage of this and using it to enable OP without a driver, well you shouldn't. There is a toggle for people to abuse that feature called RHD mode. See issue #21345

**Comment by ZwX1616** [comment]
I believe we are always using method#3
https://github.com/commaai/openpilot/blob/28694041d5ee860cdd5f26acb63887e0ce7d8bbf/selfdrive/modeld/models/dmonitoring.cc#L71

I suggest to try aiming it a little bit yawed while staying in calibration limits

**Comment by BadOlives** [comment]
> I believe we are always using method#3
> https://github.com/commaai/openpilot/blob/28694041d5ee860cdd5f26acb63887e0ce7d8bbf/selfdrive/modeld/models/dmonitoring.cc#L71
> 
> I suggest to try aiming it a little bit yawed while staying in calibration limits

I think the reason for that gap is because that is where the side UI usually is (if enabled to display with OP active). Possibly have the frame ignore the side UI?
