### ISSUE TITLE
New EON stucks at homepage?How to setup openpilot rightly?Dose this device work rightly?

### ISSUE THREAD

**Issue by liyangsensetime** [commaai/openpilot#21353]
I follow the instruction (https://github.com/commaai/openpilot/wiki/Installing-openpilot),but my EONS just stuck at thiepage.
I tried to connect it to my car and the icon "nopanda" has been change into "conneted online".
![QQMail_0 (1)](https://user-images.githubusercontent.com/84004614/122681789-abeea280-d228-11eb-9bb5-0f8660482806.jpg)

**Comment by liyangsensetime** [comment]
The version is 0.8.5.
i have cost more than 2 days to solve this problem ,i print some log in  this sdk showing that the road camera do not get connected. 
The driver camera could work rightly and i can get images of the road camera from comma app .
If someone can solve thie problem , i would appreciate it

**Comment by cydia2020** [comment]
it seems like the device doesn't go "onroad", you should try another usb-c cable

**Comment by liyangsensetime** [comment]
> it seems like the device doesn't go "onroad", you should try another usb-c cable
i have tried this way ,but this device just stuck  at this page ?
![QQMail_2](https://user-images.githubusercontent.com/84004614/122702640-665ec380-d282-11eb-8100-0da754a5ad9e.jpg)

**Comment by pd0wm** [comment]
It looks like you're not using the original USB-C cable. A lot of third party USB-C cables don't have all the pins connected internally. Make sure it supports USB 3.2 gen 2.

**Comment by cydia2020** [comment]
這是甚麼車型？沒看到ADAS相機好像

What car model is this? It doesn't look like it has an ADAS camera.

**Comment by pd0wm** [comment]
GitHub issues are for tracking issues related to openpilot. This issue is specific to your hardware or installation, and doesn't belong on GitHub. If there is an issue with your C2 or hardware bought from comma please contact support at support@comma.ai. For other questions join our discord on https://discord.comma.ai.
