### ISSUE TITLE
Steeringwheel shaking Issue 2021 Acura 

### ISSUE THREAD

**Issue by ptajml** [commaai/openpilot#21376]
Driving rough surface (Ex. concrete surface on bridge) causes steering wheel to shake left/right for a few seconds. It is worse at low speed. Steering wheel shaking issue stops by it self or sometimes i have to hold steering wheel. 
It happens if you drive straight and hit a bump in the road. I don't have this issue if i use stock LKAS.

**Device/Version information (please complete the following information):**
 - Device: comma 2
 - Dongle ID: 91ac852a198890c2
 - Route1: 91ac852a198890c2|2021-06-22--10-12-47--0 - Timestamp1: 10:20:45 ~ 10:20:50,  10:22:38 ~10:22:42 , 10:23:04 ~10:23:11
 - Rout 2: 91ac852a198890c2|2021-06-21--18-01-23 - Timestamp 2: 18:03:31 ~ 18:03:52
 - Version: 0.8.5
 - Car make/model: 2021 Acura RDX

**Comment by adeebshihadeh** [comment]
Please provide more information and fill out the template

**Comment by ptajml** [comment]
> 
> 
> Please provide more information and fill out the template

Sorry i pressed enter while filling out the template

**Comment by pd0wm** [comment]
Your PID controller is tuned too aggressively. I suggest lowering kP.

![2021-06-23-112844_1928x1263_scrot](https://user-images.githubusercontent.com/1314752/123072848-2fb9b200-d416-11eb-944b-6556aeb253f4.png)

**Comment by ptajml** [comment]
Is there any instructions on lowering kP value?

**Comment by adeebshihadeh** [comment]
Here's where the parameters are defined for your car - https://github.com/commaai/openpilot/blob/master/selfdrive/car/honda/interface.py#L338. Join the #tuning channel on our [discord](https://discord.comma.ai) for some help. If you come up with some better values, submit them as a PR.
