### ISSUE TITLE
My Comma device

### ISSUE THREAD

**Issue by swervo954** [commaai/openpilot#2140]
**Describe the bug**

So I recently got my comma device and I hook up all the wires, so then the device turned on and I connected it to my cars WiFi and then it said it’s downloading the open pilot software. Then all of a sudden the comma device just shut off. After that when I plugged it in the device just keeps restarting. So now I’ve tried to hard reset but it still does the same thing.(HONDA ACCORD SPORT 2.0 2018)

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [e.g. EON/EON Gold/comma two]
 - Dongle ID: [e.g. 77611a1fac303767, can be found in Settings -> Device -> Dongle ID or my.comma.ai/useradmin]
 - Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
 - Timestamp: [When in the route the bug occurs (e.g. 4min 30s into the drive)]
 - Version: [commit hash when on a non-release branch, or version number when on devel or release2 (e.g. 0.7.6)]
 - Car make/model: [e.g. Toyota Prius 2016]

**Additional context**

**Comment by pd0wm** [comment]
Sounds like a hardware issue. If you email support@comma.ai they will take care of it!
