### ISSUE TITLE
fatal error: 'QApplication' file not found

### ISSUE THREAD

**Issue by hiccup-luohao** [commaai/openpilot#21400]
When porting openpilot 0.8.4 to Neos, the following problems appear：

clang++ -o selfdrive/ui/main.o -c -std=c++1z -DQCOM -mcpu=cortex-a57 -D_REENTRANT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QUICK_LIB -DQT_QUICKWIDGETS_LIB -DQT_QML_LIB -DQT_CORE_LIB -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -DQCOM -mcpu=cortex-a57 -Iphonelibs/opencl/include -I. -Iphonelibs/catch2/include -Iphonelibs/bzip2 -Iphonelibs/libyuv/include -Iphonelibs/openmax/include -Iphonelibs/json11 -Iphonelibs/curl/include -Iphonelibs/libgralloc/include -Iphonelibs/android_frameworks_native/include -Iphonelibs/android_hardware_libhardware/include -Iphonelibs/android_system_core/include -Iphonelibs/linux/include -Iphonelibs/snpe/include -Iphonelibs/nanovg -Iphonelibs/qrcode -Iphonelibs -Icereal -Icereal/messaging -Icereal/visionipc -Iopendbc/can -I/system/comma/usr/include -I/system/comma/usr/include/qt -I/system/comma/usr/include/qt/QtWidgets -I/system/comma/usr/include/qt/QtGui -I/system/comma/usr/include/qt/QtCore -I/system/comma/usr/include/qt/QtNetwork -I/system/comma/usr/include/qt/QtConcurrent -I/system/comma/usr/include/qt/QtMultimedia -I/system/comma/usr/include/qt/QtQuick -I/system/comma/usr/include/qt/QtQml -I/system/comma/usr/include/qt/QtQuickWidgets -Iselfdrive/ui/qt selfdrive/ui/main.cc
selfdrive/ui/main.cc:1:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^~~~~~~~~~~~~~
1 error generated.
scons: *** [selfdrive/ui/main.o] Error 1
scons: building terminated because of errors.

**Comment by adeebshihadeh** [comment]
NEOS didn't have Qt until version 16.
