### ISSUE TITLE
ui interface display error "openpilot Unavailable,Waiting for controls to start  "

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21428]
**Describe the bug**

I use the webcam tool to run openpilot on PC and Vehicle . We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) and connected the PC and vehicle(Using Nissan DBC to make the virtual signal) to two web cameras and Panda .When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", the webcam view can be displayed , but displays error "openpilot Unavailable,Waiting for controls to start  ", How to solve it ? Thanks.

**How to reproduce or log data**
When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

**Expected behavior**
Openpilot can run normal on vehicle

**Additional context**

Operating system: [e.g. Ubuntu 20.04]

**Comment by adeebshihadeh** [comment]
As we've said in your previous issues, our issues are not for help getting started. Check out the community discord at https://discord.comma.ai for help getting setup.

**Comment by zeroyang0809** [comment]
hello do you fix your problem? 
i meet the same question
could you share your steps to fix it?
THX
