### ISSUE TITLE
OP v0.8.6 run webcam error： no panda

### ISSUE THREAD

**Issue by YJCITA** [commaai/openpilot#21425]
**Describe the bug**

run webcam , UI show no panda

**How to reproduce or log data**

OP version V0.8.6
[op_maneger_output.txt](https://github.com/commaai/openpilot/files/6724570/op_maneger_output.txt)
![UI_error](https://user-images.githubusercontent.com/12579690/123602805-bbbf4580-d82b-11eb-8aab-536f2c95b0d8.png)

**Expected behavior**

OP should run on PC

**Additional context**

Operating system: ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Our issues are not for help getting started. Check out the community discord at https://discord.comma.ai for help getting setup. However, for this issue, ensure your udev rules are setup properly. See https://github.com/commaai/panda#python.

**Comment by visionandy** [comment]
same problem here, have you solved it?
