### ISSUE TITLE
Docker image ghcr.io/commaai/openpilot:latest private

### ISSUE THREAD

**Issue by brianhaugen2** [commaai/openpilot#21459]
**Describe the bug**

When trying to pull ghcr.io/commaai/openpilot:latest I get an error with denied

**How to reproduce or log data**

$ docker pull ghcr.io/commaai/openpilot:latest
Error response from daemon: Head https://ghcr.io/v2/commaai/openpilot/manifests/latest: denied

**Expected behavior**

Not sure if this is expected or not, but seems like it could be a public image since the Dockerfile is available in the repo

I am able to pull ghcr.io/commaai/openpilot-base:latest without problems

Operating system: Windows10

**Comment by adeebshihadeh** [comment]
That's an old package. Use ghcr.io/commaai/openpilot-prebuilt:latest.
