### ISSUE TITLE
Cruise Fault on 2021 Camry

### ISSUE THREAD

**Issue by silvercurrent** [commaai/openpilot#21478]
Comma 2 displays 'Cruise Fault. Restart car to engage.' every time the car is started. Troubleshooting steps I've unsuccessfully tried based on other comments:

- Cycling the ignition.
- Enabling community features for CAN-based fingerprinting.
- Cloning the lta branch (`git clone -b lta https://github.com/commaai/openpilot`) on OP 0.8.3 and 0.8.4. As of 0.8.5, I believe this has been merged into master: https://github.com/commaai/openpilot/pull/19731

Dongle ID: b65f04d24b59c98d
Drives: all
OP version: 0.8.5
Car: 2021 Toyota Camry SE

**Comment by adeebshihadeh** [comment]
Yes, that has been merged and is in the current release. Your issue is being tracked in #20703 and should have a fix in the next release.
