### ISSUE TITLE
C2 will not boot

### ISSUE THREAD

**Issue by pauste** [commaai/openpilot#21475]
**Describe the bug**: After loading a fork that didn’t work I tried to reload a fork that did work and my C2 doesn’t boot. It starts with the Comma logo and then the screen goes blank. After waiting more than 15 minutes I can press the power button and I get “Power off” or “Reboot” as selections. 

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: Comma two - Order #15616
 - Dongle ID: n/a (seems to be bricked)
 - Route: n/a
 - Timestamp: n/a
 - Version: fork from 0.8.5
 - Car make/model: 2019 Kia Niro Plug-in Hybrid

**Additional context**

**Comment by adeebshihadeh** [comment]
Your device isn't bricked. Contact the fork maintainer for support.
