### ISSUE TITLE
Model training code

### ISSUE THREAD

**Issue by nadashin** [commaai/openpilot#21480]
I have a question.

Which part of this repository has the code for training the model?
Is it in a different repository?

I am opening this issue after not getting email answer from Comma and openpilot's top committers.

**Comment by adeebshihadeh** [comment]
This repo doesn’t have any training code. The training code is not public.

**Comment by beeman** [comment]
'Open'pilot...

![image](https://user-images.githubusercontent.com/36491/124421988-da10ce00-dd62-11eb-894b-5d198fdfc67d.jpeg)

**Comment by nadashin** [comment]
*Email Reply*

Chris McCammon (comma.ai)

Jul 6, 2021, 19:46 MST
Hi Nadashin,

We won't be open sourcing the training infrastructure. Doing so would only help large corporations and not be helpful to any individuals trying to push ML further.

You need a 100+ thousand datacenter to train at any reasonable speed.

Best,
Chris
