### ISSUE TITLE
Tool to generate screenshots of UI in all states

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#21483]
It would be nice to have a tool that generates screenshots of UI in all the possible states for testing design changes. We could also use this as a regression test to ensure refactors don't change design.

Examples of possible states:
* home screen
  * not paired
  * paired with prime
  * paired with no prime
* onroad UI
  * 0/1/2 leads
  * DM and engage-ability icons on and off

**Comment by maykonpacheco** [comment]
Hi, could you give us more details on how this would work and how it would help the user experience?

**Comment by Edgars01** [comment]
Hello. Do you still need this? I can try to make it as my first contribution.
