### ISSUE TITLE
Palisade Problems

### ISSUE THREAD

**Issue by Palispades** [commaai/openpilot#21527]
Hello everyone.  I'm new to openpilot and currently having some bugs/issues with my 2021 Hyundai Palisade SEL convenience and premium HDA package.  Whenever I have the cruise set, and come into a stop/go situation the openpilot software still holds the scenario and never enters the "stop and go press pedal to continue screen".  On top of this inconvenience the cluster screen will flash, and all the SES lights will momentarily flash including the transmission selection GUI.  This flashing in the cluster will continue, sometimes several times until the car in front of me pulls away.  Whenever the car pulls away the openpilot will continue to follow the car without any driver inputs.  I did a little bit of hardwire debugging myself and it seems that the harness and all the connections are intact and properly connected to the car.  Any ideas what this may be?  Ill add the datalog tomorrow with the instructions pasted below on my drive to work.  I think this is an excellent community with a great accomplishments, but this glitch is driving me crazy! Anyone have similar issues? Thanks.

**Comment by gregjhogan** [comment]
openpilot doesn't control longitudinal on your vehicle, but it can spam the resume button for you each time it prompts to press press resume to continue, so it does and you are just seeing the prompt flash for a split second (which is expected)
