### ISSUE TITLE
NEOS update version not displayed 

### ISSUE THREAD

**Issue by royboendermaker** [commaai/openpilot#21540]
Describe the bug

When OP wants to install a NEOS update the version is not displayed you are upgrading to. So you are blindsighted what you are doing. Some devices can’t handle NEOS versions >14. So it would be nice to show. 

How to reproduce or log data

Turn your EON in recovery mode and do an OP base install. 

Expected behavior:

NEOS version you are upgrading to is not displayed. 

Device/Version information (please complete the following information):

Device: Oneplus 3T, grey panda
Dongle ID: c4289221cf16a21c
Route: -
Timestamp: -
Version: https://github.com/actuallylemoncurd/openpilot/tree/khonsu 0.7.9 
Car make/model: 2010 Scirocco 2.0 TDI
Additional context: -

**Comment by adeebshihadeh** [comment]
The NEOS updater UI isn't shown to users on release branches, as updates are automatically downloaded and installed in the background. In your case with the OP3T, we disabled the updater on the last supported version, so those users would stay on a supported version.
