### ISSUE TITLE
Add Documentation to Readme for CARLA Docker

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#2154]
Would be nice to have a very simple getting started with openpilot + CARLA on PC in the main README, with a link from the top of it.

I think this will help bring a lot of people into the codebase who don't have a car or comma hardware.

(looks like we already passed Apollo in stars, but more can't hurt)

**Comment by pd0wm** [comment]
@grekiki Can you expand the `Testing on PC` section of the main readme with a simple example on how to start the two docker containers?
