### ISSUE TITLE
Error when running scons

### ISSUE THREAD

**Issue by fsalsubaei** [commaai/openpilot#21553]
When I run scons -j4 I get this error
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cythonize cereal/messaging/messaging_pyx.pyx
sh: 1: cythonize: not found
cythonize cereal/visionipc/visionipc_pyx.pyx
sh: 1: cythonize: not found
cythonize common/clock.pyx
sh: 1: cythonize: not found
cythonize common/kalman/simple_kalman_impl.pyx
scons: *** [cereal/messaging/messaging_pyx.cpp] Error 127
scons: *** [cereal/visionipc/visionipc_pyx.cpp] Error 127
scons: *** [common/clock.cpp] Error 127
sh: 1: cythonize: not found
scons: *** [common/kalman/simple_kalman_impl.cpp] Error 127
scons: building terminated because of errors.

**Comment by adeebshihadeh** [comment]
Our issue tracker is not for help getting started. Check out our community discord - https://discord.comma.ai.
