### ISSUE TITLE
Comma 2 Says No Panda 

### ISSUE THREAD

**Issue by JPFoxxx** [commaai/openpilot#21572]
**Describe the bug**
Also showing no panda Software??
2020 Toyota Prius

**Comment by adeebshihadeh** [comment]
Our issue tracker is not for support. Check out https://discord.comma.ai for help getting started. If you think you've hit a bug, open a new issue and fill out the whole bug report template.

**Comment by JPFoxxx** [comment]
Thank you I will return the device.
