### ISSUE TITLE
UI interface report "CAN Error: Check Connections" 

### ISSUE THREAD

**Issue by LIHaoran-good** [commaai/openpilot#21574]
**Describe the bug**

I use the webcam tool to run openpilot on PC and Vehicle . We refer to the [guideline](https://github.com/commaai/openpilot/tree/master/tools/webcam) .When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py", UI interface displays error " CAN Error: Check Connections " ,
and manager.py output: "selfdrive/boardd/panda.cc: Transmit buffer full"
How to solve it ? Thanks.

**How to reproduce or log data**
When input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"

**Device/Version information (please complete the following information):**
 - Device: Webcam C920
 - Dongle ID: 
 - Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
 - Timestamp: input "PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py"
 - Version: openpilot v0.8.5
 - Car make/model: NISSAN X-TRAIL 2017

**Additional context**

**Comment by adeebshihadeh** [comment]
Our issue tracker is not for support or help getting started. Check out our community discord at https://discord.comma.ai
