### ISSUE TITLE
UI: fix http request caching

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#21637]

**Comment by adeebshihadeh** [comment]
@deanlee want to look into this one? would be nice to also write tests

**Comment by deanlee** [comment]
ok

**Comment by adeebshihadeh** [comment]
this is for things like the API requests for drive stats that we cache to a param

**Comment by deanlee** [comment]
I see... but I think it's still better to use QNetworkConfigurationManager to test internet connection in qt/setup. it's more "realtime" and if we clear nam'scache in HttpRequest, the time of clear/re-init may be more than 300ms on EON

**Comment by deanlee** [comment]
> this is for things like the API requests for drive stats that we cache to a param

could it be expressed in a more specific way?

**Comment by adeebshihadeh** [comment]
We cache the last successful request in RequestRepeater so that things like the drive stats are populated even without internet. https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/request_repeater.cc#L15

**Comment by deanlee** [comment]
I still don't quite understand how to fix the request caching. can it  be solved if we don't emit receivedResponse from cache when there is no network?

**Comment by adeebshihadeh** [comment]
Fixed the caching with #21693, but the prime widget doesn't seem to take advantage of the caching properly.
