### ISSUE TITLE
Comma IOS app does not calculate duration properly when timezone changes during a drive

### ISSUE THREAD

**Issue by jqnatividad** [commaai/openpilot#21662]
**Describe the bug**

Comma IOS app does not calculate duration properly when timezone changes during a drive

**How to reproduce or log data**

Drive thru a timezone...

**Device/Version information (please complete the following information):**
 - Device: EON
 - Dongle ID: 5f82f62b22138c50
 - Route: 5f82f62b22138c50|2021-07-16--19-32-52--208
  - Version: 1.3.4.180
 - Car make/model: Toyota Prius Prime 2017 Advanced
 
**Additional context**

The time stamps are off by one hour from the duration (Start: 11:50p End: 2:28a Duration: 3:38). Interestingly, the start location is in the same timezone as the end location, but I crossed a timezone earlier in the day, on an earlier route.

![image](https://user-images.githubusercontent.com/1980690/126256278-74697fab-90d0-4956-b066-14f790aa132a.jpeg)

**Comment by adeebshihadeh** [comment]
The native app is being suneset. If the same issue exists with explorer, open an issue on that repo.
