### ISSUE TITLE
[2021 Toyota Corolla TS Hybrid] Getting "Take control immediately" while driving or CAN errors while in Dashcam mode

### ISSUE THREAD

**Issue by mysliwiec-tech** [commaai/openpilot#21719]
**Describe the bug**

I cannot indicate when the issue is occurring, but I got a red alert saying "Take Control Immediately" on my Comma 2 on whole screen. It happens when I got OpenPilot engaged. It flashes few errors on my car dashboard: headlights error, LKAS error, RTA error etc. In few seconds they disappear, but I cannot reenable OpenPilot till I restart the engine.

Experiencing it since v0.8.4-release2.

**How to reproduce or log data**

Hard for me to catch what are the situations when it occurs. Logs are uploaded.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: bd1aa84276ac73ae
 - Route1: bd1aa84276ac73ae|2021-07-25--14-40-35--14
 - Timestamp1: 14min 10s
 - Route2: bd1aa84276ac73ae|2021-07-22--17-47-27--4
 - Timestamp2: 4min 07s
 - Route3: bd1aa84276ac73ae|2021-07-25--18-00-55--5
 - Timestamp3: 5min 33s
 - Version: v0.8.6-release2
 - Car make/model: Toyota Corolla TS 2021 Hybrid

**Additional context**

If I do not engage the OpenPilot at all (and set the toggle, so it works only in the Dashcam mode), instead of getting red alert, I got CAN: Communication error from time to time. That's why I have to turn Comma2 immediately, as those errors are not allowing me to even enable stock AutoPilot at all.

I think it is simillar to what was described in #21054, #21557

**Comment by VirtuallyChris** [comment]
Hi, this is likely a hardware issue. Can you please email support@comma.ai with the above info and we will assist.
