### ISSUE TITLE
Lexus NX300h 2018

### ISSUE THREAD

**Issue by rickyb82** [commaai/openpilot#2174]
I've installed comma two on my lexus but i've two error: first: dashcam mode for unsupported car, and second: CAN ERROR: CHECK CONNECTION
All cables are correctly connected and i've checked all installation.
Anyone have same issue?

Thanks in avance

Riccardo

**Comment by VirtuallyChris** [comment]
Can you provide your dongle ID? in Settings -> Device -> Dongle ID. Most likely needs its firmware versions added.
