### ISSUE TITLE
Connection Error (No Panda)

### ISSUE THREAD

**Issue by tglevrie** [commaai/openpilot#21777]
"No Panda" shows on display

Whenever I start my up car in the morning the system will read "No Panda." I can usually fix this by rebooting the system, but yesterday when driving a long distance the system gave a "check connection" (I believe?) would not fix even if rebooted. I stopped and reconnected everything, which seemed to fix the problem for the rest of the day, but this morning it gave the "No Panda" message again. Again, rebooting seemed to fix it. This issue has been happening since the 0.8.6 update (if that's any help).

Seems to happen if the car is off for more than a few hours.

Turn off car overnight

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 58ce3aea82a8082c
 - Route: 7/28/2021 - 7:19am-8:14am (Apologies, unable to find any Route number at my.comma.ai/useradmin)
 - Timestamp: Around the 55 minute mark (At least that's what I'd imagine given the error stopped the connection)
 - Version: 0.8.6
 - Car make/model: Toyota Camry Hybrid 2020

**Comment by VirtuallyChris** [comment]
This is likely a hardware issue. Please email that info to support@comma.ai so we can help out!
