### ISSUE TITLE
Lane departure warning false positive

### ISSUE THREAD

**Issue by grekiki** [commaai/openpilot#21778]
**Describe the bug**
On the route 650b1e4383a9baf2|2021-07-29--09-50-32 at 210s I got a lane departure alert despite staying clearly inside my lane. 

**How to reproduce or log data**

Not sure it's reproducible, will add info if I get more occurences

**Device/Version information (please complete the following information):**

 - Device:comma2
 - Version: Fork of master from a month ago, very similar to 0.8.6 release, in particular https://github.com/grekiki/openpilot/commit/8ea0e169c6090108a46db9086ec6dcc17368e035
 - Car make/model: VW Caddy

Quick bug preview: https://youtu.be/1LKCRRWEi0k

Since I suspect it's a model bug: @HaraldSchafer

**Comment by pd0wm** [comment]
Looks there is quite a bit of yaw to the left after passing the white car. I can imagine the model thinks you're going to cross the line.

**Comment by grekiki** [comment]
![Screenshot from 2021-07-29 22-25-04](https://user-images.githubusercontent.com/16437969/127560932-f8b76d60-876e-4941-a10b-3db37475be4f.png)
Ok the model seems to have quite freqent lane change ideas, looks like at also thought that I am going to lanechange to the right on the sidewalk and then the bus stop afterwards at 50 kph, was "lucky" there were no lanelines close to the driving line. Looking at the rest of the drive it seems to think I am going to perform a right lanechange whenever there is a sideroad to the right no matter my speed...
