### ISSUE TITLE
New Comma Two crashes and spins until unplugged

### ISSUE THREAD

**Issue by physhster** [commaai/openpilot#21802]
I had a previous Comma Two that encountered a fan issue and was replaced under warranty, however it has already crashed twice mid-drive with the comma logo and a spinning circle around it that only goes away when restarted.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: dddd7608e2dcafee
 - Route: dddd7608e2dcafee|2021-07-29--16-29-14
 - Timestamp: Unknown
 - Version: 0.8.6
 - Car make/model: VW Golf GTI Mk7.5

**Comment by VirtuallyChris** [comment]
Please email this to support@comma.ai It's likely a hardware issue we can get resolved asap.
