### ISSUE TITLE
Speed limit problem 

### ISSUE THREAD

**Issue by Na112786** [commaai/openpilot#21803]
- Device: [comma two]
 - Dongle ID: [1631748f51929063]
 - Route: [1631748f51929063|2021-07-28--06-22-45]
 - Timestamp: [Unknown]
 - Version: [release2 (0.8.6)]
 - Car make/model: [honda pilot 2019]

Speed limit problem, 
Everything was great on speed limit 84mph with version 0.8.5
When I updated to version 0.8.6, I found problem with speed limit 69mph. And the speed is low, so please can you help me to back my original speed limit 84 mph, pls.

Milestone: 2000.
Thank you.

**Comment by pd0wm** [comment]
Can you be more specific what happened? Did you get the alert about speed to high? Did the car never reach the desired speed?

Looking at the route I never see the set speed set higher than 101 kph (~63 mph).

**Comment by Na112786** [comment]
>
> This is ur question :

> Did the car never reach the desired speed?
>
My answer, YES THE CAR NEVER REACH THE DESIRED SPEED.

This is ur comment :

> Looking at the route I never see the set speed set higher than 101 km ( 63
> mph).
>
My answer, myvcomma two version 0.8.5 reach to (84mph), Attached guide to
the picture.  And all the comma. ai members said, the speed limit is
(84mph), Attached guide to the picture.

Now, the specific problem is attached in video, so u can understand
directly, ( I set the speed on 135km, then the speed come down
automatically to 114km)????

Why this happened in version 0.8.6?
Could you help me, Pls.

>

**Comment by pd0wm** [comment]
I don't see a video. If you want to share files you have to do that through the github web interface, not through email.

Are you sure you sent the right route, this is a plot of the set speed while openpilot was engaged in the 2nd half of the drive.

![2021-08-02-194521_1629x1978_scrot](https://user-images.githubusercontent.com/1314752/127902693-56c7b0f0-e222-4d3a-a391-b15fb26bbfd0.png)

**Comment by Na112786** [comment]
Attache video..
Sorry the video can't send because the big size. I will put in the Honda,
accra comma ia members

**Comment by Na112786** [comment]
How I can send the video, in GitHub, in which place?

> Attache video..
> Sorry the video can't send because the big size. I will put in the Honda,
> accra comma ia members, but still big size...
>

**Comment by Na112786** [comment]
This is the pic of the route...

> Are you sure you sent the right route, this is a plot of the set speed
> while openpilot was engaged in the 2nd half of the device
>

**Comment by Na112786** [comment]
I sent the video to ***@***.***

Please, I need help, do understand me.
Now u have all the information

**Comment by Na112786** [comment]
Finally ur system except the video 

https://user-images.githubusercontent.com/88205149/128094328-40f19cd4-c264-4531-af47-74436b40ec55.mp4

**Comment by Na112786** [comment]
![oldest speed limit 135km](https://user-images.githubusercontent.com/88205149/128094665-4dc716f8-60d4-4486-890e-1f39201ed68b.jpg)

**Comment by Na112786** [comment]
![commaai members](https://user-images.githubusercontent.com/88205149/128094703-ff0cb18e-a2c0-43d6-ae68-48de9f145a6e.jpg)

**Comment by Na112786** [comment]
![Screenshot_20210802_221047_com android chrome](https://user-images.githubusercontent.com/88205149/128095570-06c68a13-f0ef-4079-9a48-48dac114d6c3.jpg)
![Screenshot_20210802_221023_com android chrome](https://user-images.githubusercontent.com/88205149/128095575-9f9f568f-a945-41a2-a508-e51a0973ac66.jpg)

Route

**Comment by HaraldSchafer** [comment]
Thanks for the detailed feedback, this issue is the same as this. So I will link and close.
https://github.com/commaai/openpilot/issues/21697

**Comment by Na112786** [comment]
Hello, 
What is the news about this problem 👇
* Poor longitudinal tuning *

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/commit/a8f3e2b3c26f2b617a1c9c94250b44adce861d04

Just merged a potential fix into master. This should hopefully help with some Hondas. I was not able to test some, so any feedback is welcome.
