### ISSUE TITLE
No prime

### ISSUE THREAD

**Issue by Itislv** [commaai/openpilot#21858]
My comma two did an update today ( 0.8.6 to 0.8.7) and now where it usually started "connect online" it now rewards "no prime". I checked and made sure my subscription is active, and it is but in explorer it starts my device is offline (does show online when connected to my home wifi). I've done nothing at all to my device short of the initial setup.

**Comment by adeebshihadeh** [comment]
Please fill out the bug report template so that we can look into this.

**Comment by VirtuallyChris** [comment]
Please email support@comma.ai with this and your Dongle ID so we can look into it. I suspect your SIM card got deactivated.
