### ISSUE TITLE
No Stop & Go support on 2021+ Toyotas without  emergency e-brake

### ISSUE THREAD

**Issue by OPgood** [commaai/openpilot#21882]
No SNG support on most Toyota car models that don’t have Full-Speed Range DCC this is due to any car from Toyota that does not have a electronic emergency brake from 2021+. how can this be fixed?  Car automatically disengages when the Soren hits below 15 to 20 mph. Specifically on the 2021 Camry?

**Comment by adeebshihadeh** [comment]
This is not a bug, as this is the behavior of your stock ACC system. However, you may be able to workaround it, and we'd merge a PR to do so.

**Comment by OPgood** [comment]
So it’s that’s the case they brew to fix the website! Website clams it works at 0 acc

**Comment by VirtuallyChris** [comment]
Where on the website does it claim it works stop and go?

**Comment by OPgood** [comment]
Did you not just read my previous comment? Website (this GitHub itself compatibility chart) clams it works to 0ACC not 20ACC so if it was 0ACC like it states it would work for stop and go not automatically disengage at 20mph

**Comment by OPgood** [comment]
![13C477E4-146E-4622-96EF-469196980A3E](https://user-images.githubusercontent.com/88660934/128780277-534da04b-f00b-4f47-bb50-e352b92a55bb.jpeg)

**Comment by dorkmo** [comment]
looks like the footnote reference [4] talks about some camrys not having full speed range dynamic radar cruise control, not sure if it is possible to get around this. You might ask on the toyota discord if anyone has tried

**Comment by dorkmo** [comment]
@VirtuallyChris would it be better to list it as 28mph, then have the reference talk about 0mph on certain trims?
Does pedal work in this scenario?

**Comment by anotabien** [comment]
@AlexandreSato was working on a workaround to enable SNG
https://github.com/AlexandreSato/openpilot-Brazil/blob/master/acc_type1.py
https://medium.com/@tapecom/openpilot-stop-and-go-hack-for-thailand-toyota-corolla-cross-hybrid-premium-sefty-model-with-comma-b379a2a95bbc
