### ISSUE TITLE
Improve camerad startup time

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#21925]
camerad takes noticeably longer to startup on C3 vs C2

**Comment by adeebshihadeh** [comment]
@deanlee interested in looking into this one?

**Comment by deanlee** [comment]
It seems that most of the time is spent on vipc_server->create_buffers. but we can't execute it in multiple threads, maybe there will be some improvement after removing rgb buffer

**Comment by adeebshihadeh** [comment]
This does indeed seem to be pretty good without the RGB buffers.
