### ISSUE TITLE
athena: persist upload queue to disk

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#21921]
Make sure the upload queue survives device restarts

**Comment by DevinLeamy** [comment]
Hi,

I'm a new contributor to openpilot, and this looks like it would be a good first issue for me.
Can I be assigned to this issue?

**Comment by pd0wm** [comment]
- Caching can be done in a persistent param. (`selfdrive/common/params.cc`), e.g. `AthenaUploadQueue`. I would just json to store a list of upload items.
 - They would indeed need to be stored real time, we can loose power at any moment. Probably upon receipt, and after every successful or failed upload in the upload handler. The queue can be loaded back in on startup.
