### ISSUE TITLE
Add param for set_unsafe_mode in boardd.cc

### ISSUE THREAD

**Issue by williefeb19** [commaai/openpilot#21951]
I think this could be a useful mod for a part of the OpenPilot community. I like OP stock release2 but want to be able to use the gas pedal to resume from a stop in my non-DSU car. Currently this is the only file that needs to be recompiled when using release2 if you are wanting to modify OpenPilot for allowing the gas pedal to be pressed. Having a file like "DisableUpdates" that is for "set_unsafe_mode" in params/d would allow maintaining this function across updates with out having to recompile boardd.cc code. I am probably in the minority of users that this would be useful for but I am hoping it would be a straight forward mod.

**Comment by adeebshihadeh** [comment]
`DisableUpdates` was created for users with deprecated hardware to stay on a version of openpilot that supports their hardware. The param suggested here is meant to toggle between two difference experiences, which isn't something we're interested in including in openpilot.
