### ISSUE TITLE
With 120° Wide Angle Lens, Driver Monitoring Does Not Detect Face Unless Shift Face/Body to Center of Cabin

### ISSUE THREAD

**Issue by thedp79** [commaai/openpilot#21964]
**Describe the bug**

Driver monitoring will only successfully/continuously detect driver's face if driver is sitting slightly off center (towards middle of cabin). See pictures attached. Otherwise, driver monitoring is intermittent/inconsistent in face detection. In preview mode, driver monitoring is able to successfully track and find head/face, only when driving is area for detection shifted slightly to the center of cabin and driver monitoring unable to detect face. 

**How to reproduce or log data**

Drive in normal/comfortable sitting position. When driver monitoring is not active, begin to shift body/ move head to center of cabin until driver monitoring icon is active.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 52d86230ee29aa84
 - Route: 52d86230ee29aa84|2021-08-18--07-59-16
 - Timestamp: between 0820 and 0825 is a driver alert for face not detected, but there are several throughout the route
 - Version: 0.8.7 release2
 - Car make/model: 2017 Chrysler Pacifica Hybrid

**Additional context**

There is a 120° wide angle lens attached. Does not impede DM. Device camera provides limited detection for shorter drivers. If the area for face detection could be shifted slightly to the driver's left or possibly widened to capture more cabin.

Normal Driving Position
![normal_driving_position](https://user-images.githubusercontent.com/46816673/129990755-f1fedf4e-25e7-46ad-a331-5d7816c2639f.png)

Shifted to center of cabin driving position
![shifted_sitting_position](https://user-images.githubusercontent.com/46816673/129990770-a01ac312-1895-4df7-a0c7-e4746eced699.png)

**Comment by adeebshihadeh** [comment]
We can't look into this with modifications such as an extra lens. If you remove all HW modification and still have issues, feel free to open another issue.
