### ISSUE TITLE
Laneless - Struggled with Hard Shoulder

### ISSUE THREAD

**Issue by Achilles308** [commaai/openpilot#21987]
**Describe the bug**

Was driving along with laneless on and seemingly out of nowhere it started to cut the corner towards this newly paved inside shoulder. It is hard to tell in the video, but that drops off maybe 10 inches and should essentially be treated like a hard curb. I'm not even sure my tire would hit the bottom but my frame would have been on the road no doubt. That shoulder is no joke. Might be a good comma pencil one but adjust the road to be where the drop off starts, not the color if that makes any sense.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: f39975d916ed458a
 - Route: f39975d916ed458a|2021-08-19--17-36-23--56
 - Timestamp: 18:32::50 local time
 - Version: master-ci 0.8.8 updated right before the drive
 - Car make/model: 2020 Toyota Corolla Hatchback

**Additional context**

I took over and steered the car sharply away from the abyss black hole of the hard shoulder...

I believe lanefull pulled this off with easy earlier in the week... it still seems like laneless is trained to be a racecar driver by cutting corners too sharp.

**Comment by HaraldSchafer** [comment]
Closing this, this is part of the general improving laneless driving project. Not really actionable with a specific fix, thanks for the report!
