### ISSUE TITLE
No audio alert for min_speed_alert

### ISSUE THREAD

**Issue by ClickToDisplay** [commaai/openpilot#22006]
There should definitely be an audio alert since you are supposed to take control and open pilot is no longer steering.

**Comment by adeebshihadeh** [comment]
There's nothing called `min_speed_alert`, so I assume you're referring to the `belowSteerSpeed` event. The alert for this event already plays a chime. https://github.com/commaai/openpilot/blob/58be354118821b11abc4d967e50350b6381e5789/selfdrive/controls/lib/events.py#L193.
