### ISSUE TITLE
openpilot unavailable system malfunction:reboot your device.

### ISSUE THREAD

**Issue by Torch-HXM** [commaai/openpilot#22012]
**Describe the bug**
My carla vision is 0.9.11 and my openpilot vision is 0.8.8.
When I run openpilot in carla,it has a problem of "openpilot unavailable system malfunction:reboot your device",picture as follow:
![2021-08-22 21-12-43 的屏幕截图](https://user-images.githubusercontent.com/88866541/130356643-85e8bb13-e9c2-492d-b527-1ab8688d29a4.png)

**How to reproduce or log data**
My steps are like this:
1.start carla in the first terminal:
![2021-08-22 21-10-50 的屏幕截图](https://user-images.githubusercontent.com/88866541/130356694-3b46cbec-2b74-4059-8a31-efcc8b604383.png)

2.start openpilot in the second terminal

3.press '1' and then comes out this issue.

**Additional context**
To solve this problem, I have done some exploring and try. 
I used to stop carla when carla and openpilot were both running,then the problem didn't come out again.And you can press '1' to add the speed as the official documentation says,but the car didn't move at all.In addition,when I stop carla,the ui image came out a logo like this:
![2021-08-22 21-31-56 的屏幕截图](https://user-images.githubusercontent.com/88866541/130357081-54378188-d48f-4e09-b9fe-42252f688ffd.png)

I have no idea about how to solve this problem.I would appreciate it if you can help me.

Operating system: [e.g. Ubuntu 20.04]

**Comment by riponcse10** [comment]
All of a sudden, I am also facing the same issue. It worked fine till 15-20 days ago, I don't know whether it is a version compatibility issue.

**Comment by adeebshihadeh** [comment]
Should be fixed by 9afa0eec6451a37a0dc0c39bf4837edd2ad53531.

**Comment by Torch-HXM** [comment]
> All of a sudden, I am also facing the same issue. It worked fine till 15-20 days ago, I don't know whether it is a version compatibility issue.



> Should be fixed by [9afa0ee](https://github.com/commaai/openpilot/commit/9afa0eec6451a37a0dc0c39bf4837edd2ad53531).

thank you for your replay.I solve my problem successfully according to your advice.

**Comment by Torch-HXM** [comment]
> All of a sudden, I am also facing the same issue. It worked fine till 15-20 days ago, I don't know whether it is a version compatibility issue.

Thank you.
