### ISSUE TITLE
Get no result after running openpilot docker

### ISSUE THREAD

**Issue by MotamedNia** [commaai/openpilot#22042]
**Hi, I've followed the instructions described on this [page](https://github.com/commaai/openpilot/blob/master/tools/sim/README.md). Carla's simulator and openpilot docker also runs successfully. After running openpilot simulator caral map also changed to a new map. but openpilot application just shows a blue screen. no road and no vehicle information.**

Operating system: Ubuntu 16.04
Docker version: 19.03.12

**Comment by adeebshihadeh** [comment]
Check out our community discord at https://discord.comma.ai for help getting started with the simulator. There's a channel called `openpilot-simulation` for this.
