### ISSUE TITLE
Merge Accord 2021 back in

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22064]
Once #22073 is done, we can merge back in the 2021 Accords.

**Comment by adeebshihadeh** [comment]
@csouers other Bosch models like the Civic Hatch also have `0x33DA` and `0x33DB`, but we just pass them through. Before merging the 2021 Accord back in, I think we should look into whether we should also send those on the Civic Hatch and any other Bosch models that use those.

**Comment by csouers** [comment]
Looking into it!

**Comment by spektor56** [comment]
2021 CRV Hybrid also has this

**Comment by austinwylie** [comment]
Is there a path to getting this back in? Just an Accord 21 owner, looking forward to having full support for the car again. 🙂 Let me know if I can help with drives or anything.

**Comment by adeebshihadeh** [comment]
@austinwylie Getting this merged back in with #23021 in the next release that will get out in a few weeks. Once that's merged, you can run master-ci in the meantime, and just confirm everything works as before.
