### ISSUE TITLE
Failed Lane Change - Edge Case

### ISSUE THREAD

**Issue by Achilles308** [commaai/openpilot#22082]
I intentionally initiated a lane change in a hard area, and it certainly didn't complete it. This is a moderate left turn going down a moderate hill. Lighting was excellent, lane markers are white with dark outline contrast on light concrete. The lane change started and it just never got enough turn to complete the lane change and the turn... so it just road right in the middle between the two lanes.

comma 3
master-ci 0.8.9
Toyota Corolla Hatchback
dfb993cc43ba69dc|2021-08-29--14-41-09--14 and into 15
14:56::01 is around the start time

I don't believe I touched the wheel the cancel the lane change, but hard to know for sure. I do believe I turned it back into the initial lane and tried the lane change again. It ran out of room as the lane ended and abruptly joined the lane I was trying to get into.

Edit: Hard to remember, but I don't recall a warning either that the lane change failed. I would expect OP to be able to identify when something it was suppose to do fails and alert the user.

**Comment by HaraldSchafer** [comment]
Closing this, this is part of the general improving laneless driving project. Not really actionable with a specific fix, thanks for the report!
