### ISSUE TITLE
updated: git corruption

### ISSUE THREAD

**Issue by Na112786** [commaai/openpilot#22093]
I can't update my C2. The notes given by alert that : " unable to download updates, Ensure the software is correctly installed", Evidence 1pic. 

Last update check & check for update ,Evidence 2pic + 3pic.

Device: [comma two]
Dongle ID: [1631748f51929063]
Route: [1631748f51929063|2021-07-28--06-22-45]
Timestamp: [31.8.2021]
Version: [release2 (0.8.7)]
Car make/model: [honda pilot 2019]

Thanks.

**Comment by Na112786** [comment]
![IMG_20210831_232648](https://user-images.githubusercontent.com/88205149/131566829-ff863bad-d337-4b3b-9e94-76e7faf0a494.jpg)
![IMG_20210831_234904](https://user-images.githubusercontent.com/88205149/131566832-5954f951-6dd9-491b-91d6-324a9ba1656d.jpg)
![IMG_20210831_234930](https://user-images.githubusercontent.com/88205149/131566835-c66e737b-8466-4ea1-a4af-a056efe7b772.jpg)

**Comment by Na112786** [comment]
Are there any risks of uninstall the openpilot ?
And is it from the same place that I can re-install?

Thanks

**Comment by adeebshihadeh** [comment]
No, there's no risks. Simpy install the same way you did when you initially setup the device. Check out #installation-help on the community discord for help.

**Comment by Na112786** [comment]
How about, all my driving miles?
Is will delete?

**Comment by adeebshihadeh** [comment]
This should largely be fixed by d4b42042331fe797efa144d7e5646c92925386db.
