### ISSUE TITLE
System "No panda" "No connection" "CAN Error"

### ISSUE THREAD

**Issue by tglevrie** [commaai/openpilot#22114]
When I attempted to turn on openpilot (comma 2) I got a message saying something along the lines of "CAN Error: ...(something) processes." I powered it off and on again hoping it would fix the problem, but the same issue came up, but this time it said "No panda" and "No connection." I attempted to power off the system, but when I did the power menu froze in place and the background was still functioning. My comma device shut off and won't turn back on. I've tried rewiring all the components, and plugging the comma device into a computer to power it up, but to no avail. 

Unsure how to reproduce

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 0d4f012f6f5b1616
 - Route: 0d4f012f6f5b1616 2021-09-02--16-35-49 (I apologize, as I'm not sure this is the event, but this was the last log on the useradmin page)
 - Timestamp: Unable to view log, but should be for the duration of the trip I'd imagine
 - Version: 0.8.8
 - Car make/model: Toyota Camry Hybrid 2020

**Additional context**

**Comment by adeebshihadeh** [comment]
This sounds like a hardware issue. Contact support@comma.ai for hardware support.
