### ISSUE TITLE
Phantom Braking for Shadows?

### ISSUE THREAD

**Issue by Achilles308** [commaai/openpilot#22206]
I reported a shadow bridge braking example on discord some 4 weeks or so ago. I tried to find the bridge that it happened at, but with so many to pick from and no readily easily available brake logs on cabana (that I could figure out in the limited time I had), I was not able to find it. It broke from 70 to 65... so minor... but still a braking event for no reason.

This is another example of bug #20704

This event was a braking event after a street light and into the shadow behind it (best I can tell, that is what I think it was braking for at least). The set speed was 40 and sometime around the streetlight or the shadow, OP broke to 35.

comma 3
master-ci 0.8.10
dfb993cc43ba69dc|2021-09-09--21-50-02--18 and 19
22:08::57 Local time
2020 Toyota Corolla Hatchback

It would be helpful to know if this is a VOACC or a radar issue?

**Comment by adeebshihadeh** [comment]
@HaraldSchafer what do you think of moving model feedback to github discussions? I made a new category for driving feedback https://github.com/commaai/openpilot/discussions/categories/driving-feedback
