### ISSUE TITLE
Poor or no GPS since 0.8.6 to 0.8.9

### ISSUE THREAD

**Issue by git6578** [commaai/openpilot#22269]
**Describe the bug**
c2 does not detect GPS.
**How to reproduce or log data**

drive the car

**Device/Version information (please complete the following information):**
 - c2
 - https://my.comma.ai/useradmin/?onebox=a589dcc642fdb10a
 - https://my.comma.ai/useradmin/?onebox=a589dcc642fdb10a%7C2021-09-18--15-40-29
 - route beginning and end, other routes have no gps the entire way
 - 0.8.9
 - VW Touran 2017

**Additional context**

updated from 0.8.6
windshield replaced, maybe hardware error?

**Comment by adeebshihadeh** [comment]
This is likely a hardware issue. Contact support@comma.ai.
