### ISSUE TITLE
CARLA: make car drive well

### ISSUE THREAD

**Issue by pkr-20** [commaai/openpilot#22265]
**Describe the bug**

faulty autopilot - the car crashes within a couple of seconds after engaging autopilot, even though there is no reason for it to do so 

**How to reproduce or log data**

start the CARLA docker container with `run --rm --net=host -e DISPLAY= -e DSL_VIDEODRIVER=offscreen -it --gpus all carlasim/carla:0.9.11 ./CarlaUE4.sh -opengl -nosound -quality-level=Low -world-port=2000`

run ~/openpilot/tools/sim/start_openpilot_docker.sh

hit '1' to engage autopilot, and watch as the car eventually drives into the side guardrail, unable to move after that. (throttle will max out at 1, and steer will move slightly)

Operating system: Ubuntu 18.04.5

**Comment by Ming2888** [comment]
Is there any update on this issue? I encountered the same problem.

**Comment by maykonpacheco** [comment]
Why do you need to use
"run --rm --net=host -e DISPLAY= -e DSL_VIDEODRIVER=offscreen -it --gpus all carlasim/carla:0.9.11 ./CarlaUE4.sh -opengl -nosound -quality-level=Low -world- port=2000" instead of "./start_carla.sh" and "./start_openpilot_docker.sh" ?

https://github.com/commaai/openpilot/blob/master/tools/sim/README.md

**Comment by Ming2888** [comment]
I am using "./start_carla.sh" and "./start_openpilot_docker.sh", and still have the same issue.

**Comment by maykonpacheco** [comment]
Add here an image of the error that is appearing, that way we can see what you are doing.

**Comment by Ming2888** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/100655683/156275512-239920c8-51fa-45b0-b902-cee6b3598a14.png)
![Screenshot_2](https://user-images.githubusercontent.com/100655683/156275529-49ebf036-6681-4efe-b3d8-fda617d187d4.png)

**Comment by Ming2888** [comment]
Autopilot does not work, and the vehicle drove off road.
