### ISSUE TITLE
2021 Hyundai Sonata N Line: Actual vehicle speed does not match desired SCC/ACC set speed

### ISSUE THREAD

**Issue by sunnyhaibin** [commaai/openpilot#22291]
**Describe the bug**
Noticed a speed difference between set desired SCC/ACC speed and actual vehicle cruise speed in both car cluster and OP screen. This was on `master` on the 2021 Hyundai Sonata N Line, with radar points enabled through the `hyundai_enable_radar_points.py` script and OP long enabled through `DisableRadar`.

**How to reproduce or log data**
Set SCC/ACC to 40 MPH, the actual vehicle cruise speed speed would stabilize at 38 MPH, even after going uphill/downhill in some segments.

**Device/Version information (please complete the following information):**
 - Device: `comma two`
 - Dongle ID: `ac404ef8838ff10f`
 - Route: `ac404ef8838ff10f|2021-09-20--19-25-24`
 - Timestamp: 10min 45s into the drive
 - Version: master `485afda79db7b65d00eb03553511c14f4b2f5301`
 - Car make/model: 2021 Hyundai Sonata N Line

![bug_report_2](https://user-images.githubusercontent.com/47793918/134109230-6e24d06a-60eb-44bf-9700-a217864ab1ca.jpg)
![bug_report_1](https://user-images.githubusercontent.com/47793918/134109243-31516845-610e-40f3-aa64-fa6686a09c5e.jpg)

**Comment by xps-genesis** [comment]
same behavior on my Chrysler Pacifica

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/pull/22295

This should fix it
