### ISSUE TITLE
openpilot Longitudinal Control not working anymore with 2021 Hyundai Sonata N Line on comma 3

### ISSUE THREAD

**Issue by sunnyhaibin** [commaai/openpilot#22311]
**Describe the bug**

Installed `master` (`c01e622e828c1c2e41ac9708a74e4209811ad07b`) on the comma three and went into `/data/params/d/DisableRadar` to saved with `1`. The car does not seem to have `openpilotLongitudinalControl` enabled, no lead car indicator (triangle), cruise control SET/RES does not increment/decrement speed by 5 MPH, etc. After multiple reboots it is still the same. Verified that `DisableRadar` stays consistent with `1` after multiple reboots. Radar points were previously enabled on the car with `/data/openpilot/selfdrive/debug/hyundai_enable_radar_points.py`.

**How to reproduce or log data**

1. Install `master` (`c01e622e828c1c2e41ac9708a74e4209811ad07b`) on comma three
2. Create `/data/params/d/DisableRadar` and save with `1`.
3. Reboot comma three
4. No lead car indicator (triangle) or SCC/ACC with SET/RES to perform 5 MPH increment/decrement cruise set speed change.

**Device/Version information (please complete the following information):**
 - Device: comma three
 - Dongle ID: `36e10531feea61a4`
 - Route: `36e10531feea61a4|2021-09-22--09-39-27`
 - Timestamp: Entire drive
 - Version: `master` (`c01e622e828c1c2e41ac9708a74e4209811ad07b`)
 - Car make/model: Hyundai Sonata N Line 2021

**Comment by pd0wm** [comment]
You wrote `1\n` into the param, that doesn't work. Use `echo -n "1" > /data/params/d/DisableRadar`
