### ISSUE TITLE
[Nissan Leaf] Disengages when lead car slows below 20mph

### ISSUE THREAD

**Issue by willemcvu** [commaai/openpilot#2233]
To replicate:

1. Have openpilot activated for steering, with Nissan stock system doing longitudinal control.
2. Have lead car indicated on HUD with set speed faster than lead car speed.
3. Lead car brakes for a complete stop.

At this point, the Nissan system starts braking, but at about 20mph, 9/10 times adaptive cruise control disengages, openpilot disengages, and the HUD shows a "seatbelt warning" saying that the system can't be engaged if the seat belt is not connected (I can't remember the exact message text).

It is quite jarring for all adaptive cruise control to suddenly disengage mid-braking :/ 

With the stock Nissan adaptive cruise control, this (obviously) does not happen.

**Comment by pd0wm** [comment]
Can you fill out the bug report template with dongle id + route?

**Comment by willemcvu** [comment]
Yep, I'll do that when I get home tonight - I see the template now, apologies for not following the format the first time around.

**Comment by willemcvu** [comment]
See new bug report at #19631. Closing.
