### ISSUE TITLE
No module named 'selfdrive.services'

### ISSUE THREAD

**Issue by San29n** [commaai/openpilot#2234]
**Describe the bug**

Traceback (most recent call last):
  File "joystickd.py", line 11, in <module>
    from selfdrive.services import service_list
ModuleNotFoundError: No module named 'selfdrive.services'

**How to reproduce or log data**

**Expected behavior**

**Additional context**

![image](https://user-images.githubusercontent.com/66538932/94371962-c5275000-00e9-11eb-8255-e5d60b5b8e42.png)
Operating system: [e.g. Ubuntu 16.04]

**Comment by adeebshihadeh** [comment]
This isn't a recent version of openpilot - `tools/carcontrol/joystickd.py` doesn't import from selfdrive.services.
