### ISSUE TITLE
Failed to stop for car although FCW came on

### ISSUE THREAD

**Issue by TKassis** [commaai/openpilot#22416]
**Describe the bug**

This keeps happening. When approaching a stopped car at a traffic light (regardless of ego speed), OP does not slow down or stop. This is surprising because the FCW on OP goes off so it is detecting the stopped lead properly but failing to react.

**How to reproduce or log data**

Approach a stopped car at a traffic light with OP engaged.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: d359be01b5dd56bf
 - Route: d359be01b5dd56bf|2021-10-03--11-25-54--1
 - Timestamp: Sun, 3 Oct @ 11:27:37
 - Version: 0.8.9
 - Car make/model: Toyota Corolla Hybrid 2021

**Comment by HaraldSchafer** [comment]
You were in a turn which makes the model not sure what's your lead. Right as the turn ended the model saw the lead and openpilot asked for heavy braking, the lag in the brake request means it tool 0.4s before the car started decelerating. And at that point you were already quite close for your speed, so you took over and also got an FCW.
