### ISSUE TITLE
Boardd: libusb initialization error after too many connect retries

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22423]
If you leave boardd running with no pandas connected it will start printing errors after a few minutes and no longer connects to a panda.

```
...
libusb: error [usbi_pipe] failed to create pipe (24)
selfdrive/boardd/panda.cc: libusb initialization error
libusb: error [usbi_pipe] failed to create pipe (24)
selfdrive/boardd/panda.cc: libusb initialization error
libusb: error [usbi_pipe] failed to create pipe (24)
selfdrive/boardd/panda.cc: libusb initialization error
...
```

**Comment by pd0wm** [comment]
@robbederks Mentioned creating and destroying a context leaks an fd. We have to fix that or re-use the same context

**Comment by robbederks** [comment]
Indeed. Initializing and (re)using the default libusb context (pass in nullptr) fixes this
