### ISSUE TITLE
UI stuck in visionIPC receive timeout

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22427]
Happens when you go onroad/offroad quickly. Reproduced on master@47f601e50a8357ff1a30b4224f7fef0e65253df0 and comma three.

UI is very unresponsive when this happens

**Comment by deanlee** [comment]
#22450 (do not reconnect vipc after offroad.)  should be able to solve this problem.

#22354 is a better solution. move vipc to a separate thread without affecting the main UI thread.
