### ISSUE TITLE
"Steering Temporarily Unavailable, TAKE CONTROL IMMEDIATELY" error on slight lateral corrections

### ISSUE THREAD

**Issue by evdoks** [commaai/openpilot#22471]
**Describe the bug**

"Steering Temporarily Unavailable, TAKE CONTROL IMMEDIATELY" with a loud sound alert appears when a significant steering correction is made while OpenPilot is enabled.

**How to reproduce or log data**

1. Enable OpenPilot while approaching a steep curve or a turn that OpenPilot won't be able to take on its own.
2. When in the curve or turning, apply torque to the steering wheel (the torque must be more significant than a simple slight correction).

**Device/Version information (please complete the following information):**
 - Device: comma two/comma three
 - Dongle ID: `80ec17a2b40ba5f0`
 - Route: `80ec17a2b40ba5f0|2021-10-07--10-00-18`
 - Timestamp: approx. 24min 30s
 - Version: 0.8.9
 - Car make/model: Toyota RAV4 2019 Hybrid (TSS 2.0, Germany)

**Additional context**

The error appears on a regular basis.

**Comment by adeebshihadeh** [comment]
This should be significantly improved in 0.8.10. You'll still get an orange alert while you're overriding, but shouldn't see a red alert under normal conditions while overriding.
