### ISSUE TITLE
Unify framereader/logreader implementations

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#22500]
- [ ] python interface to cpp logreader/framereader
- [ ] logreader support for processing a single segment from url without writing out any files
- [ ] framereader support for processing a single segment from url without writing out any files
- [ ] framereader support for [index video stream](https://github.com/commaai/openpilot/blob/537dff3ae0bac7ca3d40f1441297cc146dc1a9bb/tools/lib/framereader.py#L132-L144) from url without writing out any files

support from command line is not needed, this is for spinning through thousands of random segments as fast as possible without disk I/O becoming a bottleneck (or wearing out SSD drives)

**Comment by adeebshihadeh** [comment]
@deanlee after these are done, we should be able to replace the python logreader and framereader with a wrapper around the new ones

**Comment by deanlee** [comment]
I need to find a way to pass DynamicStruct to the pycapnp PyObject
