### ISSUE TITLE
replay fails returning "error loading [...]" and "selfdrive/ui/replay/logreader.cc: bz2 decompress failed" on VM of Ubuntu 20.04

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#22548]
### Describe the bug

When trying to run `./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam` 
the replay never seems to start and no files are ever found in `/tmp/comma_download_cache/` 

The following output is seen:
`services  std::vector(sensorEvents, gpsNMEA, deviceState, can, controlsState, pandaStates, peripheralState, radarState, roadEncodeIdx, liveTracks, sendcan, logMessage, liveCalibration, androidLog, carState, carControl, longitudinalPlan, procLog, gpsLocationExternal, ubloxGnss, clocks, ubloxRaw, liveLocationKalman, liveParameters, cameraOdometry, lateralPlan, thumbnail, carEvents, carParams, roadCameraState, driverCameraState, driverEncodeIdx, driverState, driverMonitoringState, wideRoadEncodeIdx, wideRoadCameraState, modelV2, managerState, uploaderState, testJoystick)
load route "0c7f0c7f0c7f0c7f|2021-10-13--13-00-00" with 4 valid segments
seeking to 0
downloading segment 0 ...
downloading segment 1 ...
downloading segment 2 ...
error loading /tmp/comma_download_cache/5dc1ceadc0de14526359d17c82d942a0c181663dd6cd4f33aac67715a4f12a41
error loading /tmp/comma_download_cache/28179ae4cf59ed666bdb62b6c8d2c8e484ef14c5bfa24055ceecdb0f7b097419
error loading /tmp/comma_download_cache/b7fb64e83708656605f955a80e2e0920bffb2c74066ff74d7f03755989e5fc44
selfdrive/ui/replay/logreader.cc: bz2 decompress failed
error loading /tmp/comma_download_cache/6e8b582898b672671d29ed80546d73fb416933ac2c2c02e744b3676c69e7e918
error loading /tmp/comma_download_cache/c4b7188bd7502cc650d5a215fcfdc39c862bbd2cf1d6655a247b0d1ab158b69a
error loading /tmp/comma_download_cache/e96099cb6c9478eca3c20cfe2f0f3153b09be5d4433b8257824a614b3e26619e
selfdrive/ui/replay/logreader.cc: bz2 decompress failed
error loading /tmp/comma_download_cache/8fb591fc08fb75f7e6c3d981972aa1f7ea6323267f4a04d980121cc74028197f
error loading /tmp/comma_download_cache/d4c0a031343d9f1efc97daf669f3dd36dc267b9d7323ce3403008ce25e8c2bd6
error loading /tmp/comma_download_cache/0441efdd85cfa0a9254d9a88a5e27831dc94851a5d274d62b4bf342e0cc40a7a
selfdrive/ui/replay/logreader.cc: bz2 decompress failed
`
I'm also unable to run `./replay --demo`, and get a similar error.

### OS Version

Ubuntu 20.04

### openpilot version or commit

37937a4aa69d8f4dc75d1cbfd3f2a6ba7e04f478

### Additional info

The VM is a VirtualBox VM.

**Comment by dzid26** [comment]
I got the commit and rebuild.  Now download is working for me - even on the slow internet.

**Comment by deanlee** [comment]
@dzid26 happy to hear that, thank you for testing!

**Comment by adeebshihadeh** [comment]
Merged #22531. @nabeelr can you pull and confirm this fixes your case too?
