### ISSUE TITLE
replay: malloc(): corrupted top size, corrupted size vs. prev_size, double free or corruption (!prev)

### ISSUE THREAD

**Issue by osekom** [commaai/openpilot#22555]
### Describe the bug

hi, I am trying to reproduce the command "./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam" for the CTF comma_hack but I get the following errors:

./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam
services  std::vector(sensorEvents, gpsNMEA, deviceState, can, controlsState, pandaStates, peripheralState, radarState, roadEncodeIdx, liveTracks, sendcan, logMessage, liveCalibration, androidLog, carState, carControl, longitudinalPlan, procLog, gpsLocationExternal, ubloxGnss, clocks, ubloxRaw, liveLocationKalman, liveParameters, cameraOdometry, lateralPlan, thumbnail, carEvents, carParams, roadCameraState, driverCameraState, driverEncodeIdx, driverState, driverMonitoringState, wideRoadEncodeIdx, wideRoadCameraState, modelV2, managerState, uploaderState, testJoystick)
load route "0c7f0c7f0c7f0c7f|2021-10-13--13-00-00" with 4 valid segments
seeking to 0
downloading segment 0 ...
downloading segment 1 ...
downloading segment 2 ...
merge segments std::vector(0, 1, 2)
camera[2] frame size 1928x1208
start vipc server
Starting listener for: camerad
camera[1] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
camera[0] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
malloc(): corrupted top size
Aborted (core dumped)

or:

./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam
services  std::vector(sensorEvents, gpsNMEA, deviceState, can, controlsState, pandaStates, peripheralState, radarState, roadEncodeIdx, liveTracks, sendcan, logMessage, liveCalibration, androidLog, carState, carControl, longitudinalPlan, procLog, gpsLocationExternal, ubloxGnss, clocks, ubloxRaw, liveLocationKalman, liveParameters, cameraOdometry, lateralPlan, thumbnail, carEvents, carParams, roadCameraState, driverCameraState, driverEncodeIdx, driverState, driverMonitoringState, wideRoadEncodeIdx, wideRoadCameraState, modelV2, managerState, uploaderState, testJoystick)
load route "0c7f0c7f0c7f0c7f|2021-10-13--13-00-00" with 4 valid segments
seeking to 0
merge segments std::vector(0)
merge segments std::vector(0, 1)
merge segments std::vector(0, 1, 2)
camera[2] frame size 1928x1208
start vipc server
Starting listener for: camerad
camera[1] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
camera[0] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
corrupted size vs. prev_size
Aborted (core dumped)

or:

./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam
services  std::vector(sensorEvents, gpsNMEA, deviceState, can, controlsState, pandaStates, peripheralState, radarState, roadEncodeIdx, liveTracks, sendcan, logMessage, liveCalibration, androidLog, carState, carControl, longitudinalPlan, procLog, gpsLocationExternal, ubloxGnss, clocks, ubloxRaw, liveLocationKalman, liveParameters, cameraOdometry, lateralPlan, thumbnail, carEvents, carParams, roadCameraState, driverCameraState, driverEncodeIdx, driverState, driverMonitoringState, wideRoadEncodeIdx, wideRoadCameraState, modelV2, managerState, uploaderState, testJoystick)
load route "0c7f0c7f0c7f0c7f|2021-10-13--13-00-00" with 4 valid segments
seeking to 0
merge segments std::vector(0)
merge segments std::vector(0, 1)
merge segments std::vector(0, 1, 2)
camera[2] frame size 1928x1208
start vipc server
Starting listener for: camerad
camera[1] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
camera[0] frame size 1928x1208
restart vipc server
Stopping listener for: camerad
Starting listener for: camerad
double free or corruption (!prev)
Aborted (core dumped)

### OS Version

Ubuntu 20.04 Not VM

### openpilot version or commit

current

### Additional info

Let me know as soon as possible if you need any additional information about my environment.

**Comment by osekom** [comment]
I try in various ways with the same result, right now I don't have my test environment at hand to check the memory status but the features where I am running openpilot: intel i9, 24gb ram, 1tb ssd, rtx3060 10gb. for memory ram or virtual memory I think that is not the problem. I only get about 3 seconds of playback before the error.

**Comment by osekom** [comment]
Hello, I still have the same error, I decided to try a fresh installation of Ubuntu 20.04 but without favorable results, in the morning I will try on my laptop with similar characteristics in hardware with a ryzen processor, I will inform you in a few hours.

**Comment by deanlee** [comment]
@lipniak  pull #22572 to see if it can be resolved.

**Comment by lipniak** [comment]
#22572 fixed the issue.

**Comment by osekom** [comment]
hi, sorry for the delay a bit, I did a fresh build of the master branch on an Ubuntu 20.04 VM and it was successful but when trying this on ubuntu as base system I keep getting the same corruption error

**Comment by deanlee** [comment]
@osekom did you build against the latest master branch https://github.com/commaai/openpilot ?

**Comment by osekom** [comment]
@deanlee correct, the master branch, as I mentioned earlier in a virtual machine works perfectly, but when I try to reproduce the command ./replay on my pc with ubuntu as the base system I get the error.

**Comment by osekom** [comment]
yes, it worked for me
