### ISSUE TITLE
0.8.9 Stuck on Boot Loop Every Few Days

### ISSUE THREAD

**Issue by billcheese5** [commaai/openpilot#22568]
### Describe the bug

My comma two was working perfectly for the past 10 months until I installed 0.8.9 (from 0.8.7), now it worked for a few days then got stuck in a boot loop with the comma logo only. I went into fastboot, used the guide to reflash the comma software, reinstalled openpilot like the day I got it, and it worked perfectly... For a few days, when it went into the boot loop again. I am going to reflash it again but I don't want to have to do it every few days.

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

I don't know what this means

### openpilot version

0.8.9

**Comment by adeebshihadeh** [comment]
This sounds like a hardware issue. Contact support@comma.ai.
