### ISSUE TITLE
Put camera/lens type enum in VisionIpcBufExtra

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22574]
This can be used to choose intrinsics instead of relying on the combination of frame size and stream type (or worse, the HW type for which things were compiled). Not sure yet about the best way to handle this in replays. Do we also put this enum in EncodeIdx, and write some heuristics for older routes?

**Comment by deanlee** [comment]
It is better to find out a way without adding new fields in EncodeIdx
