### ISSUE TITLE
Match button engagement logic in panda/openpilot

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22597]
Openpilot tries to engage on the falling edge of the set/resume button. Panda safety modes (at least for Honda/Hyundai) sets `controls_allowed` while the button is pressed. This can cause a mismatch when the brake and the set button are released at the same time. In this case the panda never sets `controls_allowed`, but openpilot does try to engage because the brake is no longer pressed when the falling edge is triggered one cycle later.

- [x] Honda Nidec w/ pedal
- [x] Honda Bosch w/ longitudinal control
- [x] Hyundai w/ longitudinal control

**Comment by pd0wm** [comment]
Drive where this happens with the gas: `fbbb958f3157f063|2022-03-03--21-13-55--7`

**Comment by adeebshihadeh** [comment]
Hondas done in https://github.com/commaai/panda/pull/874/

**Comment by adeebshihadeh** [comment]
Hyundai Longitudinal done in https://github.com/commaai/panda/pull/875
GM done in https://github.com/commaai/panda/pull/876
