### ISSUE TITLE
Add button to override no internet lockout 

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22608]
The reboot workaround for the no connectivity lockout should be replaced by a button or some other kind of interaction that's just annoying enough to incentivize users to still keep up to date.

**Comment by jsegill** [comment]
Simple math problem? Add 2x random numbers together and enter the result into Comma device. Easy enough to do, but annoying enough to make you want to connect to the internet possibly.

**Comment by sunnyhaibin** [comment]
High-level logic to achieve annoyance while allowing update bypass:
* After 14 days, shows "Update Later" button to allow the user to switch to onroad state after mouse click and set `snooze_counter` to 1. Device will not allow to switch to onroad state unless up to date or mouse click on "Update Later" button.
* Once the device switches to offroad state, set the `snooze_counter` to 0, "Update Later" button reappears, and does not allow the user to switch to onroad state unless the device is up to date or mouse click on the "Update Later" button.
