### ISSUE TITLE
Cannot engage Openpilot on RAV4 2.5 Hybrid Active Edition (XLE) 2021 

### ISSUE THREAD

**Issue by SuperShinyEyes** [commaai/openpilot#22619]
### Describe the bug

Hi! 

My RAV4 2021 is recognized but Openpilot engagement (steering wheel) UI is missing. 
So while it does lane detection and path planning, I cannot engage openpilot.
I drove up to 90km/h. I checked logs inside the tmux session in Three. 
All processes are running without an error.

Dongle ID: 27acef92baddfaed

![img](https://user-images.githubusercontent.com/5738363/137961569-9f9a3d88-3117-467f-8d24-a86178b4f929.jpg)

### What hardware does this issue affect?

comma three

### Which car does this affect?

Toyota RAV4 2.5 Hybrid Active Edition (XLE) 2021 (Finland Europe)

### Provide a route where the issue occurs

na

### openpilot version

v0.8.9-release

**Comment by SuperShinyEyes** [comment]
I remembered that I had a back up harness cable. Tried it but got same errors like above.

Does it mean that the wiring is not correct for my car variant? Comma Three shows velocity correctly. I can also see steering angles in the log.

**Comment by seyoung-solteq** [comment]
I will contact the support.

@pd0wm, But is the harness not 100% passthrough with Comma Three attached? Does it suppress LKA/FRC camera CAN messages then?

**Comment by adeebshihadeh** [comment]
Nice work debugging @SuperShinyEyes. Can we close this? Definitely seems like a hardware issue.

**Comment by SuperShinyEyes** [comment]
@adeebshihadeh, Yes. I will update once the issue is resolved.

BTW, thanks for the nice microservice architecture with tmux. 
It was really easy to debug thanks to the architecture.

**Comment by SuperShinyEyes** [comment]
I got the new harness but openpilot is still not engageable. ping @pd0wm

- The dashboard error message is gone.
- `commIssue` is gone.
- `wrongCarMode` is still present; `cs_out.cruiseState.available` is false.
```
'PCM_CRUISE_2': {'CHECKSUM': 4.0, 'MAIN_ON': 0.0, 'SET_SPEED': 0.0, 'LOW_SPEED_LOCKOUT': 1.0}
```

All services that controlsd depend on are alive and valid:
```
Is all valid? True
{'deviceState': True,
 'driverCameraState': True,
 'driverMonitoringState': True,
 'lateralPlan': True,
 'liveCalibration': True,
 'liveLocationKalman': True,
 'liveParameters': True,
 'longitudinalPlan': True,
 'managerState': True,
 'modelV2': True,
 'pandaState': True,
 'radarState': True,
 'roadCameraState': True,
 'wideRoadCameraState': True}
Is all alive? True
{'deviceState': True,
 'driverCameraState': True,
 'driverMonitoringState': True,
 'lateralPlan': True,
 'liveCalibration': True,
 'liveLocationKalman': True,
 'liveParameters': True,
 'longitudinalPlan': True,
 'managerState': True,
 'modelV2': True,
 'pandaState': True,
 'radarState': True,
 'roadCameraState': True,
 'wideRoadCameraState': True}
 ````

 Message from controlsd
 ```
 {"event": "fingerprinted", "car_fingerprint": "TOYOTA RAV4 HYBRID 2019", "source": 1, "fuzzy": false, "fw_count": 5}
{"event": "alert_add", "alert_type": "startup/permanent", "enabled": false}
```

How could we solve the `wrongCarMode` issue? When is `cp.vl["PCM_CRUISE_2"]["MAIN_ON"]` ever nonzero?
https://github.com/commaai/openpilot/blob/37192c1aba15eba61b7f335d1861eee8860e1f86/selfdrive/car/toyota/carstate.py#L85

**Comment by pd0wm** [comment]
Did you enable cruise control?
![16490707_24](https://user-images.githubusercontent.com/1314752/140362133-44f58541-080e-4188-8e4b-01e871a23753.jpg)

**Comment by pd0wm** [comment]
That is not normal. Your car may be faulted, which requires a full power cycle to clear. Try locking the doors and waiting a few minutes.

If the problem persists, please enable the "upload raw logs" toggle and share a route id from connect/useradmin so we can take a look.

**Comment by SuperShinyEyes** [comment]
Hey @pd0wm! Rebooting both the car and comma three worked!
Thank you so much! This was the best customer service I've ever got in my life!!!
