### ISSUE TITLE
Route Replay does not finish

### ISSUE THREAD

**Issue by fsalsubaei** [commaai/openpilot#22614]
### Describe the bug

I'm trying to replay a route but it gets stuck every time. I tried also another route and still has the same issue
![Screenshot from 2021-10-19 10-31-57](https://user-images.githubusercontent.com/84398522/137866786-6daafd3b-7e97-4045-84b8-b1647068fc48.png)

### OS Version

Ubuntu 20.4

**Comment by deanlee** [comment]
Looks like the replay stopped at the end of the route(876s).  we already support looping after https://github.com/commaai/openpilot/commit/f6de10b55a089a0600dd9826ffa3bfc140752370 .

**Comment by xiaomanbusiy** [comment]
Hello, i'm trying using replay also, but, **"Error sending a packet for decoding"**
**"camera[0] failed to get frame:### happens"**, how can i solve this, thanks very much.

ps: I use command just as below : ./replay '3533c53bb29502d1|2019-12-10--01-13-27--0' --data_dir "../openpilot/data" --no-cuda
