### ISSUE TITLE
Hyundai IONIQ Electric (2018)

### ISSUE THREAD

**Issue by Alexwijn** [commaai/openpilot#2263]
Hello, I'm thinking of getting the Comma Two for my car and install the OpenPilot software. But I noticed my car was not supported yet. But it does have Lane Assist and Adaptive Cruise Control.

Is it possible to get compatibility for my car. I'm a developer myself so I also know my way around a terminal so I can assist someone that could help me with this. Thanks!

**Comment by adeebshihadeh** [comment]
It should be a straightforward port, but all new car support comes from the community. The Hyundai channel on our [community discord](https://discord.comma.ai/) will be able to help you out.
