### ISSUE TITLE
Alert for empty carfw

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/openpilot#22642]
This happens quite often. People don't have their comma power plugged in and are wondering why the car isn't fingerprinting. Maybe 'No Firmware' 'Check comma power connection' or something to that effect.

**Comment by adeebshihadeh** [comment]
Done in 897492d27c416b1b8f70fee00de5e4db8c168ba8

**Comment by ErichMoraga** [comment]
Although well-aware the carFw is pulled from the OBD-II port via CPv2, I've found a significant # of these are actually from defective or poorly connected USB-C cables too.
