### ISSUE TITLE
Feature request for 2017 Lexus RX 450H Blind spot audio warning

### ISSUE THREAD

**Issue by richardhughes260** [commaai/openpilot#2264]
This is a deficiency in the Lexus, not Openpilot.

Would it be possible to add an audio warning when there is something detected in the blind spot and the signal is on for that side?

My wife had a 2017 Sonata Hybrid that gave an audio warning when she had the signal on for the side where the blind spot detection was sensing a vehicle.

She has a 2017 Lexus RX 450H now and it does not give an audio alert when you have the turn signal on and the blind spot detection is sensing a car on that side.

I

**Comment by pd0wm** [comment]
I don't think it's worth the code complexity to add this feature. Feel free to create your own fork where you add this.
