### ISSUE TITLE
[$300 bounty] GM: implement FW query

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22663]
Examples PRs for other brands: #1540 #20271

Bounty is for a clean, working PR that you work with us to upstream. Has to work on our Bolt without a comma power.

**Comment by sshane** [comment]
- [ ] Figure out what calibration ids are important
- [ ] Allow address range of GM ECUs behind gateway (for camera ACC Bolt)

**Comment by sshane** [comment]
Will be closed with https://github.com/commaai/openpilot/pull/31221
