### ISSUE TITLE
Tesla: implement FW query

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22661]
Examples PRs for other brands: https://github.com/commaai/openpilot/pull/1540 https://github.com/commaai/openpilot/pull/20271

**Comment by sshane** [comment]
This should be much easier to merge with https://github.com/commaai/openpilot/pull/25042 in master, @robbederks want to take a stab soon?

**Comment by robbederks** [comment]
Sure, will try it out. Shall I try over the comma power, or do you prefer it on bus 0? Think both might work
