### ISSUE TITLE
Comma 3: Hotspot does not allow devices to connect to the Internet

### ISSUE THREAD

**Issue by TaiFeng** [commaai/openpilot#22674]
### Describe the bug

When Enabling the Hotspot, devices that connect to the Wi-fi network are unable to access the Internet.

1. Settings > Network > Advanced > Enable Hotspot
2. Connect devices to network with standard 'swagswagcomma' password
3. Note: there is no internet connection

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

0a14ba4d948fc170|2021-10-21--10-27-58

### openpilot version

Aragon7777/openpilot/tree/0.8.8-shane-spektor-honda-toyota

**Comment by raucodes** [comment]
The problem goes little bit more far. If you enable Tethering, the comma three connects self to it, so all other devices can't connect to the comma device, because of a routing loop. If you enable tethering it won't connect to WiFi at home automatically, you must disable the tethering toggle.

**Comment by pd0wm** [comment]
@TaiFeng This is a check on the carrier based on the packet TTL.
@raucodes I played around a bit with tethering while staying connected by creating a virtual interface, but this resulted in a very slow connection. So for now this is the intended behavior. Tethering should also be disabled on reboot.

**Comment by TaiFeng** [comment]
@pd0wm Is this issue fixed? I don't want to pay for Prime if it's not going to work.

**Comment by raucodes** [comment]
> @pd0wm Is this issue fixed? I don't want to pay for Prime if it's not going to work.

For me it isn’t. I have full 4G strength and devices did not get an IP address.

**Comment by adeebshihadeh** [comment]
> @pd0wm Is this issue fixed? I don't want to pay for Prime if it's not going to work.

Tethering isn't a feature of comma prime. We just launched a cheaper tier to comma prime where you bring your own sim if you'd like to switch to that.

**Comment by TaiFeng** [comment]
@adeebshihadeh Is this a recent change? I used Tethering with Comma Prime on my Comma 2 without issue. I only see one tier of Comma Prime on the website.

**Comment by adeebshihadeh** [comment]
Tethering may have happened to work on the comma two, but it wasn’t an intentional or advertised feature. The tiers are on the connect app. @VirtuallyChris will get something added to the website too.

**Comment by gregjhogan** [comment]
If internet access through tethering doesn't work, it is because the carrier actively took measures to block it.  Bypassing such measures most likely violates the terms of use.
