### ISSUE TITLE
No sound on comma three until reboot

### ISSUE THREAD

**Issue by robbederks** [commaai/openpilot#22681]
### Describe the bug

Sometimes on the second / later route, the C3 will not play sounds anymore. A reboot fixes this.
Not sure about the cause yet, might also be an AGNOS issue.

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

N/A

### openpilot version

Latest

**Comment by adeebshihadeh** [comment]
#22878 should mitigate this until the next AGNOS.

**Comment by adeebshihadeh** [comment]
AGNOS 3 now has the proper plugins, so I reverted #22878. Let's see if this comes back.

**Comment by adeebshihadeh** [comment]
@pd0wm confirmed that it has indeed come back. Perhaps it was related to /var filling up. `fbbb958f3157f063|2021-12-21--12-12-27`

**Comment by adeebshihadeh** [comment]
Reverted back to making soundd persistent for now. That definitely seems to fix it, but would still like to understand this better.

**Comment by krkeegan** [comment]
Just ran into this on my comma 3 today.  On 8.13, with a few changes in my own fork.  Rebooting solved it.

Would a boot log be helpful?

**Comment by kevinharbin** [comment]
Oct 22, 2022, while driving my C3 did not make any sounds for engage/disengage/steering alert/etc. I rebooted and everything went back to normal.
I'm on release. 35c004509e3057f2|2022-10-22--10-46-40--0

**Comment by adeebshihadeh** [comment]
Fixed with https://github.com/commaai/agnos-builder/pull/138
