### ISSUE TITLE
sim: current issues preventing PC simulation with Carla, and some fixes

### ISSUE THREAD

**Issue by jwolffe** [commaai/openpilot#22705]
### Describe the bug

Over the last month or so, the "out of the box" docker-based Carla simulations have not functioned correctly. I have created some temporary native (non-docker) fixes for several issues that allow the current master code to "drive" on my Ubuntu PC as a non-root user. Hopefully this information will prove useful to other developers.

### OS Version

Ubuntu 20.04LTS

### openpilot version or commit

e178bed3016957ae09228a91f793c8d5c00d5573

### Additional info

Issues and Fixes:
**1) Undo PR #22546 to allow correct camera operation (EON vs TICI switching of values)- temporary only.** The PR is assumed to fit together with a planned future implementation.

**2) CS.canValid problem- fix in controlsd.py:**
    ....
    self.button_timers = {ButtonEvent.Type.decelCruise: 0, ButtonEvent.Type.accelCruise: 0}
    self.canValid = False  #add to intialization
    ...
    self.canValid = CS.canValid or SIMULATION #add after reading message
    all_valid = self.canValid and self.sm.all_alive_and_valid()
    ...
    [replace all other instances of CS.canValid with self.canValid]

**3) Fix .comma path to prevent generating path errors**
sudo mkdir /.comma
sudo ln -s $HOME/.comma/* /.comma/

**4) Add exports to ~/.bashrc:**
export USE_FRAME_STREAM=1
export SIMULATION="1"
export FINGERPRINT="HONDA CIVIC 2016" (related to PR #22679)

**5) Modify util.cc  --- allow non-root simulation, return 0 for priority and affinity setters**
int set_realtime_priority(int level) {
#ifdef __linux__
  if ((getenv("SIMULATION") != nullptr) && (std::string(getenv("SIMULATION")) == "1")) {
    return 0;
  }
  else {
  .... [ linux priority code ]
  }
#else  

  int set_core_affinity(std::vector<int> cores) {
#ifdef __linux__
  if ((getenv("SIMULATION") != nullptr) && (std::string(getenv("SIMULATION")) == "1")) {
    return 0;
  }
  else {
  .... [ linux affinity code ]
  )
#else  
**6) Add the PythonAPI egg for Carla into the PYTHONPATH, allowing bridge.py to run**

**Comment by jwolffe** [comment]
I did some more troubleshooting on the canValid bug mentioned above in item 2). It is apparently caused by timeout problem in the UpdateValid function in opendbc/can/parser.cc. 
Commenting out the can_valid = false statement on line 278 fixes the problem. I don't know enough about the overall system timing to suggest either disabling the timeout, or changing the timeout value,  during Simulation.

**Comment by jwolffe** [comment]
A little more troubleshooting... the problem is not the timing tolerance in Simulation.  The state.seen time value used in computing the time difference is sometimes 0. Now trying to find where that is coming from. Any hints about the possible location would be welcome.

**Comment by jwolffe** [comment]
Even more observations. I turned on DEBUG in parser.cc, revealing that message 0x1ED was missing, in turn causing the UpdateValid function to want to set can_valid false. Message 0x1ED is associated with "HUD_SETTING" in the honda_civic_touring_2016_can_generated.cc file, so I added a statement into can.py:
	msg.append(packer.make_can_msg("HUD_SETTING", 0, {}, idx))
	
That (mostly) fixed the problem, the simulation works, even after un-commenting the "can_valid = false" statement in parser.cc (the commenting-out that originally got things working). Only one remaining side-effect now, I get lots of "COUNTER not defined" output in the bridge.py terminal window. I think I'm pretty much "out of gas". I really don't understand the messaging system. Hopefully someone else can take over from here to make simulation work properly. I suspect more work will be needed to get bridge.py to produce completely correct messages.

**Comment by wellochang** [comment]
I am trying to run simulator  in Ubuntu recently, This thread helps a lot. Thanks @jwolffe 
With the "COUNTER not defined" output issue, I modified the DBC file in `/opendbc/honda_civic_touring_2016_can_generated.dbc`  : 
```
BO_ 493 HUD_SETTING: 8 XXX
 SG_ IMPERIAL_UNIT : 5|1@0+ (1,0) [0|1] "" EON
 SG_ COUNTER : 61|2@0+ (1,0) [0|3] "" EON
 SG_ CHECKSUM : 59|4@0+ (1,0) [0|3] "" EON
```
With this modification, the simulator works with clear `bridge.py` terminal. 

So, the whole process go through to make simulator works is : 
1.  Undo  #22546 
2.  add `msg.append(packer.make_can_msg("HUD_SETTING", 0, {}, idx))` in `/tools/sim/lib/can.py`
3.  rebuild openpilot with  `USE_FRAME_STREAM=1 scons -j$(nproc)`

After that, excute `start_carla.sh` ,`launch_openpilot.sh` and `bridge.py` in different terminal. The simulation should work fine.

**Comment by jwolffe** [comment]
Thanks, @wellochang, that gets us to a good point for simulation. I'm working on a pull request that should hopefully get merged into the "master" openpilot code.
