### ISSUE TITLE
Honda Accord EX 2018 “Vehicle Parameter Identification Failed” error on Comma 3

### ISSUE THREAD

**Issue by MikserOK** [commaai/openpilot#22701]
### Describe the bug

Having issue with “Vehicle Parameter Identification Failed” error on Comma 3. Error happens randomly pretty often (<30 min between triggers) mostly appear as red screen error, but sometimes as gray preventing from activating OP. Never happened on Comma 2 before on same car. 

### What hardware does this issue affect?

comma three

### Which car does this affect?

Honda Accord EX 2018

### Provide a route where the issue occurs

c8aab54281c1f4db|2021-10-18--20-51-31--11

### openpilot version

any release3 thru 0.8.10

### Additional info

I believe issue is similar to that ticket https://github.com/commaai/openpilot/issues/21909

Dongle id c8aab54281c1f4db

drives:
c8aab54281c1f4db|2021-10-18--20-51-31--11 at 21:03:25
c8aab54281c1f4db|2021-10-22--22-04-22--2 at 22:07:01
c8aab54281c1f4db|2021-10-25--18-41-45—5 at 18:47:27

**Comment by MikserOK** [comment]
Updated to released today 0.8.10, still having issue.

[c8aab54281c1f4db_2021-11-01--18-40-09--17--rlog.bz2.zip](https://github.com/commaai/openpilot/files/7457933/c8aab54281c1f4db_2021-11-01--18-40-09--17--rlog.bz2.zip) ~18:57:21
[c8aab54281c1f4db_2021-11-01--20-25-06--26--rlog.bz2.zip](https://github.com/commaai/openpilot/files/7457938/c8aab54281c1f4db_2021-11-01--20-25-06--26--rlog.bz2.zip) ~ 20:53:00

Also I've noticed broken pixels on videos, is that something I should worry about?

![01](https://user-images.githubusercontent.com/2751462/139789420-569e1e5c-c9a2-499b-a15d-2d6473a97fa6.jpg)
![02](https://user-images.githubusercontent.com/2751462/139789421-1efaaea9-4a12-4854-b20c-a1933282855d.jpg)

**Comment by pd0wm** [comment]
No need to worry about those dead subpixels. Won't affect driving. 

Your old dongle ID was `0a27f45fa0ef0d41`, which had similiar offsets of -8 degrees (e.g. `0a27f45fa0ef0d41|2021-10-05--22-01-19`). Either your steering angle sensor is mounted at an offset, or your car needs to be re-aligned. When driving straight, does your steering wheel look straight?

**Comment by MikserOK** [comment]
Not really, steering wheel looks few degrees to the left, but it's been like that for awhile maybe a year. I imagine it's not something I can check myself this sensor? I have a bluedriver, but not a dealership level scan tool. Ok, so I go do wheels alignment somewhere and see if that helps?

**Comment by pd0wm** [comment]
If you can see the steering wheel being offset it's probably not the sensor. An alignment will probably fix your issues. Make sure they also take care of making sure the steering wheel is straight.

**Comment by MikserOK** [comment]
Did alignment, drove ~300 miles so far no error, thank you! It seems like not the most uncommon issue, maybe add suggestion to do alignment except just “Vehicle Parameter Identification Failed” which doesn't tell much to unexperienced users. Really appreciate all the help!

**Comment by pd0wm** [comment]
Great to hear. Your new angle offset looks about -1.5 deg, which is fine!

I'll think about a separate alert that just looks at large average angle offset and recommend alignment
