### ISSUE TITLE
100% CPU on onnxruntime threads caused by spin-waits

### ISSUE THREAD

**Issue by jwolffe** [commaai/openpilot#22736]
### Describe the bug

I observed onnx_runner.py threads consuming nearly 100% of 4 CPU cores on my 8 core PC when running Openpilot simulations with Carla. Basically, one thread seems to consume less than a full core, while the others are at a solid 100%. I then tried different values for "options.intra_op_num_threads" in onnxrunner.py. The following results are from the System Monitor utility, where 100% means all 8 cores are busy. 

11% with CPUExecutionProvider  (1 thread)
21% with CPUExecutionProvider  (2 threads)
35% with CPUExecutionProvider  (3 threads)
44% with CPUExecutionProvider  (4 threads)
63% with CPUExecutionProvider  (6 threads)
 3% with CUDAExecutionProvider (4 threads)

### OS Version

Ubuntu 20.04LTS

### openpilot version or commit

e178bed3016957ae09228a91f793c8d5c00d5573

### Additional info

I was not able to get a "pip install onnxruntime-gpu" configuration working with my RTX2070 CUDA/CUDNN setup. I then built onnxruntime from source to see if it would help- it gave the same results for CPU operation, but now I got the CUDA/GPU working, with dramatic reduction of CPU time (after minor mods to onnx_runner.py to select CUDA execution). After a good deal of investigation it seems that onnxruntime CPU operation defaults to spin-waits on the input queues, which fully accounts for the measured results. Great for benchmarking, but not all that practical in this case. Given the low execution rate of the supercombo model, spin waits are major overkill; the operating system's scheduling should be entirely adequate.

Unfortunately, the latest onnxruntime APIs only support changing the allow_spinning option from C++; it isn't supported in the Python API. While the CUDAExecutionProvider solves my immediate simulation problems, it should be possible to rewrite the Python code for C++ disabling of the spinning. 

There are probably broader issues than just my Carla simulation on a PC- the Comma2 and Comma3 (and other) devices may suffer from the spinning, resulting in higher power dissipation than necessary, along with loss of available processing capability. At the very least, it would be a good idea to allow tuning the "options.intra_op_num_threads" value from an environment variable, to better match hardware capability with processing load.

**Comment by pd0wm** [comment]
> There are probably broader issues than just my Carla simulation on a PC- the Comma2 and Comma3 (and other) devices may suffer from the spinning, resulting in higher power dissipation than necessary, along with loss of available processing capability. At the very least, it would be a good idea to allow tuning the "options.intra_op_num_threads" value from an environment variable, to better match hardware capability with processing load.

Comma two & three use Qualcomm's SNPE, so onnx is only relevant for PC users.

@mitchellgoffpc You have been spending some time on the ONNX stuff. Can you look into this?

**Comment by jwolffe** [comment]
Good to hear that it's only on the PC. I'm continuing to explore possible fixes.

**Comment by jwolffe** [comment]
An additional observation.  When I tried rebuilding onnxruntime with allow_spinning set to false, it didn't reduce CPU load. Either I did it wrong (entirely possible) or there is an issue other than the designed-in spin waits.

**Comment by jwolffe** [comment]
i tried "pip install onnxruntime-openmp", and put "export OMP_WAIT_POLICY=PASSIVE" into the environment. This results in approximately 12-20% CPU usage. This may be a reasonable solution for many users, but I favor the CUDA-based setup.  Even while acknowledging that onnxruntime GPU  support is a fragile, implementation-dependent thing- I had to build from source. "All of the above" might be the right approach in the openpilot code- CPU,-only, CPU with OMP, CUDA, OpenVino, or others, depending on the system setup. Opinions are welcome!
