### ISSUE TITLE
Add C++ code to sphinx API docs

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22732]
https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/

**Comment by tecandrew** [comment]
done doxygen docs in the past before, could I take a crack at this? not sure how to integrate it into a sphinx site though

![image](https://user-images.githubusercontent.com/21319730/139530533-23461cfa-fc2b-4d5e-963d-e1fefe5b9b6a.png)

**Comment by pd0wm** [comment]
Feel free to open a wip PR once you have some kind of build process going!
