### ISSUE TITLE
OP generates, or finds, new FW fingerprints

### ISSUE THREAD

**Issue by tecandrew** [commaai/openpilot#22745]
### Describe the bug

0.8.9-release has no issue recognizing the car with its current list of FPs. 0.8.10 is finding new ones? 

0.8.9 drive: `715ac05b594e9c59|2021-10-29--16-50-17`

### What hardware does this issue affect?

comma two

### Which car does this affect?

Hyundai Elantra Hybrid 2021

### Provide a route where the issue occurs

715ac05b594e9c59|2021-10-29--17-33-38

### openpilot version

0.8.10 release2-staging

### Additional info

not sure if it affects other cars, but certainly affects mine 😐. workaround PR https://github.com/commaai/openpilot/pull/22727

**Comment by pd0wm** [comment]
I changed some of the queries and timeouts for Hyundai, so it’s not unexpected that a query that would time out before now completes successfully. Since we send multiple queries to the same ecu those would like a new version is showing up.
