### ISSUE TITLE
Alert when panda is blocking too many messages

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22779]

**Comment by BBBmau** [comment]
When it comes to the alert, is this referring to the alert showing up on the comma device? A sound could be played which signifies to the developer that panda is blocking too much rather than a visual.

**Comment by adeebshihadeh** [comment]
I'm actually not sure that we want to alert in this case, since it's un-actionable to the user.

**Comment by adeebshihadeh** [comment]
Added the count in pandaState with #23647. Now that we can track this in FindInteresting with the qlogs, I think this is sufficient.
