### ISSUE TITLE
Integral can build up with brake hold

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#22791]
### Describe the bug

If you engage brake hold and then engage openpilot (since user isn't pressing the brake), the long PI controller is allowed to build up integral while we're held at a standstill without a lead, and upon pressing the resume button the car is being sent 1.44 m/s/s acceleration instead of 1.2 m/s/s causing overshoot to 2 m/s/s.

![Screenshot from 2021-11-04 07-19-06](https://user-images.githubusercontent.com/25857203/140312332-79ad0b4a-5509-4e06-8f51-89222abb478a.png)

### What hardware does this issue affect?

comma three, 2022 Toyota Camry Hybrid

### Provide a route where the issue occurs

f15e3c37c118e841|2021-11-04--06-25-15--1

### openpilot version

0.8.10

**Comment by pd0wm** [comment]
Can we read the brake hold status? On Honda we don't allow engagement with brake hold.
