### ISSUE TITLE
Look into using the VIN for fingerprint caching

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22802]
Quicker fingerprinting times will become more important as more queries are added to support FW fingerprinting for all cars and as startup times go down. Right now, we fingerprint on the first drive after booting, then [cache](https://github.com/commaai/openpilot/blob/6bef60ddf56d49a2d6afdf1dfcb85cc3da8211a6/selfdrive/car/car_helpers.py#L101) that for subsequent drives but discard the cache on boot. Instead, we'd like to keep the cache around until the VIN changes.

**Comment by gregjhogan** [comment]
An alternative is send tester present to all ecus and the list of addrs that respond should tell you the vehicle manufacturer (then only run fingerprinting for a single manufacturer).  Detecting VIN change is simpler, but firmware changes will no longer be detected (ensuring the interface to the car had not changed).

**Comment by pd0wm** [comment]
Think this came up in the meeting as well, but we have to be careful to not cache these results forever. Any changes/breakage in the fingerprinting code wouldn't be discovered for quite a while.

**Comment by adeebshihadeh** [comment]
Closing as this doesn't need to be an issue. This is already the obvious thing to look into once fingerprinting is enough of a concern for startup time.
