### ISSUE TITLE
Graceful reboot/shutdown while onroad

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22821]

**Comment by Achilles308** [comment]
Maybe gated for certain cars? On my Toyota Corolla Hatchback these buttons work fine if you're smart about when you use them (disengage OP then reboot).

I think turn off should always be avaliable, personally. Maybe that means some kind of warning to the user to take over control of the car before it does shutdown.

Also, if these are removed, then please add some way to change toggles and implement them without requiring a reboot. Like a soft reboot?

**Comment by pd0wm** [comment]
Decided to change this a little since blocking the buttons would just make people unplug their device. We allow reboot/shutdown when not engaged. The actual shutdown/reboot will be moved to manager so it can first do a graceful shutdown of all the openpilot services and close the relay to hand control back to the car.
