### ISSUE TITLE
No navigation if ui restarts while onroad

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#22820]
If you hit a ui freeze/watchdog, the ui restarts but doesn't fetch the prime status properly leaving you with no navigation after the restart.

Also make sure to re-broadcast the route path when this happens.

**Comment by Achilles308** [comment]
Not sure if I was suppose to add my nav crashes here, but #22855 is likely the same issue. My nav UI did not restart without having to reboot the comma 3. I tried various things like clearing the route, which it let me do.... start a new route and nothing would bring back Navigation.

**Comment by pd0wm** [comment]
Should be fixed by https://github.com/commaai/openpilot/pull/22850
