### ISSUE TITLE
Vehicle can't keep in lane on right bank turn on highway, drifted half a car into passing lane

### ISSUE THREAD

**Issue by VenomrushCT** [commaai/openpilot#22836]
### Describe the bug

Upgraded to v0.8.10 and notice vehicle is unable to keep in lane during a right bank turn on a highway, it would drift to the passing lane, at times half a car length. 

I did not notice this issue in earlier version on the same route.

Route: f72a3ad7dc38d5cf|2021-11-06--09-18-49--19
Happened in an earlier right bank turn but less severe: f72a3ad7dc38d5cf|2021-11-06--09-18-49--17

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

f72a3ad7dc38d5cf|2021-11-06--09-18-49--19

### openpilot version

0.8.10

**Comment by Verylukyguy** [comment]
I have noticed this too.  The vehicle seems to make left turns on the freeway okay and stays comfortably away from the right lane line, but, it crowds, hugs, and even drives on or over the left lane line when making right turns.

**Comment by HaraldSchafer** [comment]
It just looks like it's hitting torque limits to me
![torq](https://user-images.githubusercontent.com/6804392/141016145-c293ee90-1132-4754-ab91-94032c26b00c.png)

**Comment by VenomrushCT** [comment]
I never had this issue in earlier version. It was perfect through this exact turn. I did not have to intervene. 

My vehicle is a Honda CR-V 2018 and currently using laneless. Unless something else vehicle specific was changed. 

I will try to turn off laneless and observe the behavior tonight and report.

**Comment by HaraldSchafer** [comment]
It would be helpful if you could show me a segment doing this turn correctly. Do you have a segment id of it working well previously?

**Comment by VenomrushCT** [comment]
Unfortunately I cancelled Prime so don't have the old drives. 

I went out again just now to take that turn twice. At the same speed (70mph) replicate the same condition as best I can. This is what I observed:

f72a3ad7dc38d5cf|2021-11-09--19-14-13--10 in this segment I turned off laneless. Seems to take the turn more confident. 

f72a3ad7dc38d5cf|2021-11-09--19-33-10--5 in this segment I reset the calibration and turned on laneless again. Seems to take the turn more confident. 

Another unrelated issue I can't find the Nov 6 route morning anymore. It hasn't been 2 weeks?

**Comment by HaraldSchafer** [comment]
I can still see it?

https://connect.comma.ai/f72a3ad7dc38d5cf/1636204730142/1636206418650

That doesn't work for you?

**Comment by VenomrushCT** [comment]
> I can still see it?
> 
> https://connect.comma.ai/f72a3ad7dc38d5cf/1636204730142/1636206418650
> 
> That doesn't work for you?

It's not accessible for me anymore 

**User Admin**
![image](https://user-images.githubusercontent.com/42399925/141169321-df643eae-3495-4991-81ca-5ceacf70ef33.png)

**Connect**
![image](https://user-images.githubusercontent.com/42399925/141169393-61c9bfe3-c9a1-4f2b-9111-d1f23faf467d.png)

**Comment by HaraldSchafer** [comment]
Ah looks like drives are only accessible for 3 days without prime :/

**Comment by VenomrushCT** [comment]
So is this issue valid? I am not able to view the old drive to visually see. 

Left turns on highway perform amazing, issue seems to be with the right turn. 
I took the same road in the opposite direction, so same amount of turning required, never had any warnings for left turns.

**Comment by HaraldSchafer** [comment]
From the data I saw, it looked like it was hitting the torque limit. It's possible some changes in how the model plans the path makes it take the turn worse with the same amount of torque, but not something I can say conclusively from the data.


If you have more examples of it behaving very poorly again, post them here.

**Comment by Achilles308** [comment]
> From the data I saw, it looked like it was hitting the torque limit. It's possible some changes in how the model plans the path makes it take the turn worse with the same amount of torque, but not something I can say conclusively from the data.
> 
> If you have more examples of it behaving very poorly again, post them here.

Just anecdotally, I have noticed on banked turns with laneless 0.8.11 does better at not cutting the corner early. In other words, it no longer cheats the inside of the curve to be able to make the turn. Which, for a turn that was right on that limit before, it would fail to maintain the lane now.

For my car, I'm getting more alerts than before in these types of banked turns, however, the turns are completed much smoother and with less center line cutting. So damned if you do, damned if you don't. I would rather it not cut the double yellow entering the turn and fail to maintain lane due to low torque than to constituently cut the yellow for turns it could have made without crossing the yellow ever.

**Comment by VenomrushCT** [comment]
This is an issue, why is it closed?

**Comment by adeebshihadeh** [comment]
The conclusion with the given information was it's probably hitting the torque limit. More information was requested over two weeks ago with none given. If you'd like us to look into this more, post further examples.
