### ISSUE TITLE
run statsd on device

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#22845]

**Comment by robbederks** [comment]
statsd seems to require node.js to run and a relatively big project, so maybe we should just build a similar simple daemon in python?

**Comment by gregjhogan** [comment]
> statsd seems to require node.js to run and a relatively big project, so maybe we should just build a similar simple daemon in python?

Yes!

**Comment by adeebshihadeh** [comment]
Done, thanks @robbederks!
