### ISSUE TITLE
Missing Sconscript file under rednose/

### ISSUE THREAD

**Issue by HaotianRen12** [commaai/openpilot#22866]
### Describe the bug

Hi, I was trying to run "$ scons -c" under openpilot/ and there was an error saying " Missing SConscript 'rednose/SConscript' ". I could find an SConscript file under rednose/rednose/, but not under rednose/. I'm new to openpilot and not sure if there is supposed to be that file under rednose/, any help would be appreciated!

### OS Version

Ubuntu 20.04

### openpilot version or commit

aa38a5fe34008718ea53ffa339f375ac0b3990a1

**Comment by abdulrahman004** [comment]
did you do `git clone --recurse-submodules https://github.com/commaai/openpilot.git` before trying to build.
rednose is a git submodule that needs lives outside opnepilot repo

**Comment by HaotianRen12** [comment]
Thank you so much, it solved my issue. I didn't add "--recurse-submodules" and cloned rednose manually from git.
