### ISSUE TITLE
sensord: Gyro values are unreasonable sometimes during init

### ISSUE THREAD

**Issue by nuwandavek** [commaai/openpilot#22888]
### Describe the bug

When initialized, sometimes the gyro values are unreasonable. We could potentially filter these out in sensord.

![image](https://user-images.githubusercontent.com/1649262/141519955-9766a81e-a3b0-4ded-bf94-391fbdeca577.png)

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

fbbb958f3157f063|2021-11-12--11-15-20/0

### openpilot version

c7be73b826b21947197f24c6a60fc5a7098e42af

**Comment by adeebshihadeh** [comment]
How many values are nonsense? Is it just the first one?

**Comment by adeebshihadeh** [comment]
@nuwandavek is this still an issue?

**Comment by nuwandavek** [comment]
This happens in ~25% of first segments (checked in 10k routes). This is not a problem as there are lots of checks downstream, but good to resolve it in `sensord`! May have to skip the first 5-10 readings. 
![image](https://user-images.githubusercontent.com/1649262/189459262-1db8038d-f51e-43ab-9fc8-90dfc4bc6f17.png)
![image](https://user-images.githubusercontent.com/1649262/189459285-c7701637-f331-45c0-a5c4-1b0399507921.png)

**Comment by adeebshihadeh** [comment]
@gast04 let's write a unit test to catch this and fix it

**Comment by incognitojam** [comment]
@gast04 can we close this?
