### ISSUE TITLE
Comma.ai won't turn on!

### ISSUE THREAD

**Issue by peterk714** [commaai/openpilot#2289]
*My Comma.ai won't turn on!
I have remove my Comma.ai and connected to power cord.  I have tried repeatedly to turn on the device and there is no response.
Please advise?

**Comment by cydia2020** [comment]
from #2290 it appears to be a boot loop, contact support?

**Comment by LoganxDev** [comment]
From the Wiki:

> When using a wallcharger at your desk, make sure it can output 2-3A (installation draws just a little above 1.0A).

Does your power source meet that requirement?

**Comment by peterk714** [comment]
Yes it meets that voltage requirement.  I used 60 watt usb to C laptop charger.  I used that same charger to install the software on the AON when I first got it 12 months ago.

Peter

**Comment by peterk714** [comment]
I’m going on a long trip this Friday. I would like to have my problem resolved by then.

Thanks,

Peter

**Comment by peterk714** [comment]
45 watt 2.4 amp output.  I used this same charger to configure the Eon when it first arrived

**Comment by peterk714** [comment]
When is somebody from Comma.ai going to provide me a resolution to my problem????

**Comment by vanillagorillaa** [comment]
Hello Peter, a response email was sent to you earlier this morning.

**Comment by peterk714** [comment]
It said contact support

**Comment by vanillagorillaa** [comment]
Yes, your support email was responded to earlier this morning by the support team.

**Comment by peterk714** [comment]
I have two c connector power sources, 60 Watt Lenovo Laptop and universal 45 watt source and they are both over 2.4 amps

**Comment by peterk714** [comment]
How do I turn this thing on????
