### ISSUE TITLE
Wide Road Camera Error

### ISSUE THREAD

**Issue by bbennett80** [commaai/openpilot#22938]
### Describe the bug

- C3, stock OP, 2020 Subaru Ascent

Driving to the airport on the morning of 9-24-21, I received a “wide road camera error” message on screen. After a about 20 seconds the message cleared and the device returned to normal operation. This was addressed to comma support via email and was determined to be "a 1 off software issue."
Route: be44434f27731ff8|2021-09-24--08-36-10
Discord link: https://discord.com/channels/469524606043160576/871838269405556736/891010918987751434  

- C3 (same C3 as before), stock OP, 2022 Hyundai Sonata Hybrid

Today, 11-16-21, while at the SAME intersection (Lat 35.4414, Lon -119.0519) I again received “wide road camera error.” After about 20 seconds the message cleared and the device returned to normal operation. 
Route: be44434f27731ff8|2021-11-16--17-56-33--5
Discord link: https://discord.com/channels/469524606043160576/871838269405556736/910369676985524244

Between those two events I did NOT experience a similar “wide road camera error” during ANY drive. Both error events occurred at the exact same location, ~2 months apart. Reporting here on advice from Erich. 

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

be44434f27731ff8|2021-11-16--17-56-33--5

### openpilot version

0.8.10 release3

**Comment by adeebshihadeh** [comment]
Fixed by #22943, which will ship in the next release.
