### ISSUE TITLE
OP 0.8.11 devel-staging cruiseMismatch 

### ISSUE THREAD

**Issue by ffhspa** [commaai/openpilot#22930]
### Describe the bug

With new version OP 0.8.11 i often get cruiseMismatch . Never happened in previous release. 
I have a Honda Civic Bosch Diesel
I dont have a route bcs i deactivated Logs and Uploads

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

N/A

### openpilot version

0.8.11

**Comment by adeebshihadeh** [comment]
Duplicate of #22903
