### ISSUE TITLE
Highlander 2021 e2e_long fork issue

### ISSUE THREAD

**Issue by Yoel4007** [commaai/openpilot#23001]
### Describe the bug

C3, on fork e2e long , the mph will drop slowly without any reason, although the max mph is higher and no cars are in front of it in the freeway, 

Also, yellow blinking street lights will force a full stop.

### What hardware does this issue affect?

comma three

### Which car does this affect?

Toyota Highlander 2021

### Provide a route where the issue occurs
https://cabana.comma.ai/?route=878a25353867b7e1%7C2021-11-21--12-10-27&seekTime=2&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F878a25353867b7e1%2F76541d26f24a395b5a0fa15a916755a5_2021-11-21--12-10-27

### openpilot version

0.8.11

**Comment by adeebshihadeh** [comment]
Closing as that is an experimental branch.
