### ISSUE TITLE
C3 UI crash when in Toggles menu during offroad transition

### ISSUE THREAD

**Issue by jyoung8607** [commaai/openpilot#23007]
### Describe the bug

UI process crashes within a second or two of an onroad->offroad transition while in the Toggles menu.

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

3cfdec54aa035f3f|2021-11-22--22-56-06

### openpilot version

jyoung8607:mqb-long

### Additional info

Happening during MQB long development, but I haven't come anywhere near the UI process. Seems 100% repeatable, 4 out of 4 attempts today. My device has uploaded several crash dumps, for example:

`cd:/3cfdec54aa035f3f/crash/2021-11-22--22-56-28_2f8e0b67_selfdrive_ui__ui`

Steps to repro:

1. Start car
2. Settings -> Toggles
3. Shut off car
4. Wait a few seconds, display reverts to comma logo for a couple seconds, and then UI restarts

**Comment by deanlee** [comment]
Think it's cameraview's issue. the hideevent will be called twice after going offroad in settings window.
