### ISSUE TITLE
UI crashes if ignition switched on then off 2x in rapid succession.

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#23018]
### Describe the bug

If you switch the ignition on then off, and on then off again, if timed correctly, the UI will crash, visually very similarly to how it crashes in issue #23007

I'm currently doing this via a Panda Jungle.

Attached is the output of tmux when this happens
[uicrash.txt](https://github.com/commaai/openpilot/files/7591866/uicrash.txt)
:

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

903210ecc0cb706b|2021-11-23--15-52-13--0

### openpilot version

release2-staging 0.8.11 ba86100

### Additional info

I'm able to reproduce it at my desk, but haven't had a chance to try it on my car yet. I'll likely give this a shot tomorrow.

**Comment by adeebshihadeh** [comment]
Same as #23007. The fix isn't in release yet.
