### ISSUE TITLE
Ensure git repo isn't touched outside overlay

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23064]

**Comment by pd0wm** [comment]
I bet we can replicate some of the git branch/commit functions in python by reading the git config directly. This way we can ensure it does't write anything.

**Comment by jyoung8607** [comment]
Back when I wrote the updater, I wasn't aware of this much faster and cheaper way to check for remote changes:

![image](https://user-images.githubusercontent.com/46612682/144264215-62ba4d4d-1b70-405b-81f1-07b5f6743d2b.png)

I'm assuming `git rev-parse HEAD` is a readonly op, I wouldn't think it would try to check/refresh things like `git status` and friends, but I haven't checked. If it does make changes, the local commit could be checked just once at manager startup. `git ls-remote [remote [branch]]` shouldn't be making any local changes.

Using this method, everything on C2/C3 would stay readonly when just checking if an update exists. We wouldn't even need to set up the overlay, we'd only need to do it when an actual update becomes available. Ditching the overlay setup and the full `git fetch` operation every ten minutes seems like a good resource savings, especially on C2.

Extra credit: the git repo protocol is well-documented, and `updated` could be taught to call `ls-refs` methods against GitHub directly without launching an external process at all.

**Comment by adeebshihadeh** [comment]
Haven't seen any issues on agnos so far. @jyoung8607 #25724 uses `git ls-remote`
