### ISSUE TITLE
Any plans to support HKG HDA2 cars?

### ISSUE THREAD

**Issue by jazzbearz** [commaai/openpilot#23072]
Recent HKG models have Highway Driving Assistant 2 feature which uses FF Cam, 5 radars and sonic sensors through can fd. Now, the 0.8.11 is released with can fd enabled, Do you have any plans to support HDA2 cars?

Cars affected: 
Genesis - G80, GV80, GV70, 
Hyundai - Ioniq5
Kia - EV6

**Comment by adeebshihadeh** [comment]
Everything is in place to support these cars, but we have no plans to port one of these cars ourselves. This will likely come from community support, like most of the supported HKG models. Moving this to the "Vehicles" section of our Discussions.
