### ISSUE TITLE
soundd: scale volume with ambient noise instead of speed

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23084]

**Comment by IvanVnucec** [comment]
Where is the code location of the volume scaling functionality?

**Comment by IvanVnucec** [comment]
Oh I see, it´s in sound.cc file line 49.

**Comment by IvanVnucec** [comment]
Is the calculation of the ambient noise already implemented or not? If not, where in code can I get signal values from the microphone?

**Comment by adeebshihadeh** [comment]
Nope. I'd start here to get audio input: https://doc.qt.io/qt-5/qtmultimedia-multimedia-audioinput-example.html.

**Comment by adeebshihadeh** [comment]
This may no longer be necessary with the new sounds I just merged in. Even at 100% volume with no ambient noise, they're quite pleasant.

**Comment by Verylukyguy** [comment]
They are so jingly.
