### ISSUE TITLE
reboot: low on memory 

### ISSUE THREAD

**Issue by tecandrew** [commaai/openpilot#23162]
### Describe the bug

while using OP it gave the loud alert to take control then prompted to reboot the device because it was low on memory. initially happened towards the end of a 2 hr drive.

### misc:
- just obtained the device not too long ago
- was actively routing to destination using nav

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

`eb5a50f9e98f50b9|2021-12-06--16-44-30`

### openpilot version

0.8.11-release

### Additional info

another user on discord `#nav-feedback` said it also happened to them recently (their drive: `66253de0fd139602|2021-12-03--12-47-46--35`)

happened again earlier today on a shorter drive: towards the end of `eb5a50f9e98f50b9|2021-12-07--12-32-36--6`

**Comment by redacid95** [comment]
This is a known issue and will be fixed in 0.8.12 release. Master currently has the fix in place based on what I have seen in their milestone tracker. https://github.com/commaai/openpilot/issues/22298

**Comment by pd0wm** [comment]
@redacid95 the fix should have already made it into the 0.8.11 release. This might be a new issue. I'm looking into it.

**Comment by ananyaget** [comment]
Currently having this exact problem C3 sunnypilot Hyundai ioniq phev 2022.
About 1:45 min into drive low memory reboot issue.

**Comment by ananyaget** [comment]
On 0.8.12 and low memory issue is still happening
