### ISSUE TITLE
Add more processes to valgrind tests

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#2323]
- [ ] loggerd (also see https://github.com/commaai/openpilot/issues/2277)
- [ ] logcatd
- [ ] proclogd
- [ ] boardd (needs usb mocking)
- [ ] sensord (needs i2c mocking)
- [ ] modeld
- [ ] dmonitoringmodeld

**Comment by grekiki** [comment]
Couldn't get any of them to work just by setting up their ProcessConfig.  Looks like it is going to be slightly more complicated.
