### ISSUE TITLE
GitHub bot

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23261]
For issues:
- [ ] respond to car bugs with common info
  - [ ] openpilot long, pedal, etc.
- [ ] pull & preserve routes

For PRs:
- [ ] pull & preserve routes

**Comment by maykonpacheco** [comment]
Hi, could you elaborate more on the problem?

One suggestion would be to use.
- Description
- How to reproduce the error.
- Expected outcome
