### ISSUE TITLE
Write script to compute toyota safety param from logs

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#2328]
Have a script to quickly check the safety params from logs. We should automatically check all toyota models for correct safety param.

**Comment by pd0wm** [comment]
https://gist.github.com/adeebshihadeh/1a771a2e23fb06bbf2d8720abf71efa3

**Comment by adeebshihadeh** [comment]
Done in 82c112dad067de5ea33ff8249f14ac6233439c85
