### ISSUE TITLE
Navigation map opens when device boots even though no directions were sent

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#23281]
### Describe the bug

On master, if my device boots when I turn my car on, when openpilot goes on-road the nav map pops open with no directions active (I didn't send any directions).  This seems to consistently happen.

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

5decac85ab437ed1|2021-12-15--07-51-16

### openpilot version

16dd7ce1fe2a2b0537fefd5ad131d1494d0d09ad

**Comment by jyoung8607** [comment]
I've been noticing this lately on master as well. I assumed it was an intentional feature and not a bug, perhaps not...?

**Comment by pd0wm** [comment]
Introduced by https://github.com/commaai/openpilot/pull/22789
