### ISSUE TITLE
Clean up supported cars

### ISSUE THREAD

**Issue by VirtuallyChris** [commaai/openpilot#2329]
There are a few cars on the readme that we don't sell harnesses for, plus I'm not sure if they even work anymore. We should get confirmation that there are still users of the following cars. If there aren't we should remove them from the readme and codebase.

* Buick Regal 2018
* Cadillac ATS 2018
* GMC Acadia Denali 2018
* Holden Astra 2017

**Comment by adeebshihadeh** [comment]
I'm not sure why we would want to remove these cars. Our regression testing should be good enough that they should continue to work.
