### ISSUE TITLE
openpilot stops too far back from lead on incline

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#23302]
openpilot seems to consistently stop further back on an incline compared to flat ground
example: `5decac85ab437ed1\|2021-12-22--12-29-05--16`
first engagement it stops too far back, then next 3 I try to get it to creep forward
![image](https://user-images.githubusercontent.com/4112046/147296852-3bb4cc2d-3518-4671-a820-ccd504641bb3.png)
once stopped too far back, I see it oscillates between the stopping (longControlState==2) and starting (longControlState==3) state @ 50 Hz
![image](https://user-images.githubusercontent.com/4112046/147297915-930f72c3-3dd2-4b28-ae58-78ba6b349417.png)

**Comment by sshane** [comment]
I believe the stopping/starting oscillation is due to `vEgoStopping` being greater than `vEgoStarting`, which will always lead to a state transition oscillation due to the logic in longcontrol.py (assuming this car is a Hyundai, the route isn't public to check out).

**Comment by pd0wm** [comment]
Think I added the high vEgoStopping because the acceleration started oscillating a lot around the set point at low speeds. But maybe we should check if that's still the case, since there probably have been a bunch of changes since then.
