### ISSUE TITLE
ignoring file third_party/acados/Darwin/lib/libblasfeo.dylib, file was built for arm64 which is not the architecture being linked (x86_64): third_party/acados/Darwin/lib/libblasfeo.dylib

### ISSUE THREAD

**Issue by 1066196847** [commaai/openpilot#23335]
### Describe the bug

https://github.com/commaai/openpilot/blob/master/tools/README.md
cd openpilot && scons -j$(nproc) -> makes the bug

### OS Version

mac pro 10.14.3

**Comment by adeebshihadeh** [comment]
Mac support isn't great right now. We're fixing it up and tracking progress in #22562.
