### ISSUE TITLE
Driver monitor red alert sound should be more persistent

### ISSUE THREAD

**Issue by ZwX1616** [commaai/openpilot#2333]
right now the "disengage immediately" alert sound lasts only 3 beeps and goes quiet

**Comment by ZwX1616** [comment]
to make it a bit longer a new _AudibleAlert_ can be added in _selfdrive/ui/sound.hpp_

but we might also want controlsd to be aware of the state and not do lane change and stuff?

**Comment by VirtuallyChris** [comment]
The existing sound should just loop during red alert, is there any easy way to implement that?
