### ISSUE TITLE
Make RobustLogReader fast

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#23358]
https://github.com/commaai/openpilot/blob/master/tools/lib/robust_logreader.py can deal with corrupted logs, but is very slow and needs an external call to `bzip2recover`. Our C++ replay handles corrupted logs in a much more elegant way.

**Comment by QueTeddy** [comment]
Would love to attend to this but don't know how to go about it.

**Comment by ahowe444** [comment]
Can we use this gist: https://gist.github.com/TimSC/8579121?

**Comment by deanlee** [comment]
I think we can resolve this issue by adding python interface to c++ logreader, I'll split the logreader_pyx from https://github.com/commaai/openpilot/pull/22707 and submit a new pr

**Comment by Love69by** [comment]
어떻게 참석해 야되나요?
