### ISSUE TITLE
ERROR: No matching distribution found for onnxruntime-gpu==1.10.0

### ISSUE THREAD

**Issue by davetapley** [commaai/openpilot#23351]
### Describe the bug

`tools/mac_setup.sh` fails with:

```
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.10.0 (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for onnxruntime-gpu==1.10.0
ERROR: Couldn't install package: onnxruntime-gpu
```

### OS Version

macOS Catalina 10.15.7 (19H1519

### openpilot version or commit

fed7cfeef064b12f76b413298ffdf71fec1f537e

### Additional info

According to [here](https://github.com/microsoft/onnxruntime#build-pipeline-status) there is no GPU build for macOS.

**Comment by adeebshihadeh** [comment]
Fixing up the Mac support is still a WIP. We're tracking it in #22562.
