### ISSUE TITLE
replay: fix random test failures

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23378]
Example: https://github.com/commaai/openpilot/runs/4696631366?check_suite_focus=true

**Comment by deanlee** [comment]
`Download failed: error code: 56` 
I think this is not a bug,  the failure is due to a network problem in function `getRemoteFileSize` :  `56 - failure in receiving network data`.

**Comment by adeebshihadeh** [comment]
Can we retry that a couple times?

**Comment by deanlee** [comment]
Yes i have done:D
