### ISSUE TITLE
Failed to make docker image using dockerfile

### ISSUE THREAD

**Issue by zhaoqianli0202** [commaai/openpilot#23386]
### Describe the bug

I try to use Dockerfile.openpilot_base to make  docker image in arm64 host,but got below error,pip can't find onnxruntime-gpu:1.10.0(arm64) in pypi,Is there any way to fix this problem？

Installing dependencies from Pipfile.lock (b5a4af)...
An error occurred while installing onnxruntime-gpu==1.10.0 --hash=sha256:2ffe8009eef07307a836e654a8449c177c0ef84ef29c4619d464d5ad8ab2d01b --hash=sha256:aa00cba93c73117485031f990795ee5702644f7f2885f3d5bb4cdb683924ab6f --hash=sha256:eadb86b76fbc0520cca811cde92f0031ebcd0f999df1abd80c4a6dc1941942f4 --hash=sha256:277b6bdca32ed049a8f387dbd9c871e1088cacede46be9f300c573a5b51526e5 --hash=sha256:8e4c52e6af7e2a10ed41e51986a247b91ef0e568f51c9d88e0eae181cfd04f62 --hash=sha256:1554ae7168cdecea27ac969f5731ca2ff636464117a8e1a3382a4c29510343b6 --hash=sha256:f6e056cd38265e1a158b72da234546291bb3cad663d81dcd66cbcbbce028e3a8 --hash=sha256:f1c5e09f3c2cf8d337f964455ab7c6131f911746a55b9f7297de4bc0e906d3fe! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 119/119 — 00:08:48

Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.10.0 (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for onnxruntime-gpu==1.10.0
ERROR: Couldn't install package: onnxruntime-gpu
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01

### OS Version

Ubuntu 18.04:arm64

**Comment by adeebshihadeh** [comment]
The issue tracker isn't the appropriate place to get help. Check out the #dev-openpilot channel at discord.comma.ai.
