### ISSUE TITLE
Communication Issue between processes

### ISSUE THREAD

**Issue by dwnaes** [commaai/openpilot#2339]
Cannot activate OP

When trying to activate OP I get the msg, "Communication Issue between processes"

Comma 2 Device, OP vers 7.9 (updated 2 days ago)
2017 Toyota Corolla LE

*I recently had to replace the car battery.
**I've been using OP for 6mo w no issues.  Same car, doggle, etc...

**Comment by VirtuallyChris** [comment]
Please use the template, we need things like your Dongle ID and a route to look into this
