### ISSUE TITLE
UI: fix network related lags

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23445]
Lags are obvious in these cases, but it's probably all fundamentally the same cause.

* wifi network scrolling isn't smooth
* wifi network scrolling freezes while updating the list
* keyboard isn't responsive in networking page
* open settings and rapidly switch between the different panels

**Comment by adeebshihadeh** [comment]
@deanlee want to take a look at this? All the NetworkManager is pretty messy, so should be pretty easy to fix it up

**Comment by deanlee** [comment]
I might have to do it in a few steps. I'll clean up the code first
