### ISSUE TITLE
CI: speedup mac caching

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23450]
A fully cached run takes 8 minutes. More than half of that is reminding brew that the dependencies are already there. 2.5 minutes in "brew link" and another 3+ minutes running tools/mac_setup. 

https://github.com/commaai/openpilot/runs/4745246244?check_suite_focus=true

**Comment by alecgarza96** [comment]
What are the steps necessary to recreate?

**Comment by maykonpacheco** [comment]
For some reason the macos build is commenting, I don't know if this task is still relevant.
![image](https://user-images.githubusercontent.com/38124066/156235457-8acabf4d-b0df-4772-866d-c6e45d0babda.png)
