### ISSUE TITLE
Joystick 🕹️

### ISSUE THREAD

**Issue by ryleymcc** [commaai/openpilot#23484]
### Describe the bug

Joystickd.py running on PC does not connect to comma device. Instructions should be improved since everyone I asked was unable to get it to work.

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Let me know if you still have issues after 7eca4d62078b14de62c5f2ce08e382eb31cc7076

**Comment by tgnabor-Phx999** [comment]
Please unsubscribe me from this thread, I tried- no can do

•Tom Nabor•

On Jan 10, 2022, at 13:06, Adeeb Shihadeh ***@***.***> wrote:

﻿

Let me know if you still have issues after 7eca4d6<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommaai%2Fopenpilot%2Fcommit%2F7eca4d62078b14de62c5f2ce08e382eb31cc7076&data=04%7C01%7C%7C29322b16468e4297e87f08d9d474a19f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774419655373425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mNz2H50VUzhNiNBAI%2FqwYfQiSOq6hAAuJ3Av0gKk4tk%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcommaai%2Fopenpilot%2Fissues%2F23484%23issuecomment-1009297060&data=04%7C01%7C%7C29322b16468e4297e87f08d9d474a19f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774419655373425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rBdyT2YqFZczSpcKjUTwAqeQtCvg1f8IsATShAOXNds%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOWFJ24MVIFXIBZ7CEZQCXLUVM32XANCNFSM5LULIA2Q&data=04%7C01%7C%7C29322b16468e4297e87f08d9d474a19f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774419655529655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qy1UgbvptcNoIinwEIPEGAPdmOqBmDSQXsN25jaqVCk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C29322b16468e4297e87f08d9d474a19f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774419655529655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xJlFeC%2F4TDWpNbcsuXkl%2FXtttyr%2F1a4qa75VD7z16E0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C29322b16468e4297e87f08d9d474a19f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774419655529655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nDVvnpEe9fTGk%2BRt%2BjAk59jR0qD7chmMeYbeeSHQzk4%3D&reserved=0>.

**Comment by ryleymcc** [comment]
> Let me know if you still have issues after [7eca4d6](https://github.com/commaai/openpilot/commit/7eca4d62078b14de62c5f2ce08e382eb31cc7076)

joystickd.py works with keyboard when running it directly on the c2 using the command `tools/joystick/joystickd.py --keyboard`.

When I do
`echo -n "1" > /data/params/d/JoystickDebugMode`

then,

`cereal/messaging/bridge {192.168.57.189} testJoystick`

then on my laptop 
`export ZMQ=1`

then
`tools/joystick/joystickd.py`

It starts on my laptop but there is no output from the comma 2 ssh shell. It does enter joystick mode but it seems like it's not connected. How can I tell if my laptop is sending the data over the network?
