### ISSUE TITLE
Clearer semantics and terminology suggestions.

### ISSUE THREAD

**Issue by joshuairl** [commaai/openpilot#235]
Mentions of comma in OpenPilot in alerts and notifications don’t make sense to me...

Why does it say things like ‘Comma Canceled - Low speed’ and ‘Comma Unavailable - Steering temporarily disabled’

What is ‘Comma’ other than the company name?

Wouldn’t it make sense for the software to not mention its own name?

Maybe OpenPilot instead of Comma?

If Comma is the cloud platform / vision system, maybe that should be clearer in the long run?
Maybe making the vision system pluggible?

**Comment by rbiasini** [comment]
As of today, "openpilot" has replaced "comma" in the devel branch already :)

**Comment by joshuairl** [comment]
🙏🏼😆👍
