### ISSUE TITLE
Toyota: merge car params and tunes

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23644]
Start by merging any params configuration that's common between two cars, e.g. fe5056ffd8dfb6a8ecb1b008a8c77c2b3b2e7511. Then, merge as many tunes as possible in `selfdrive/car/toyota/tunes.py`.

**Comment by sshane** [comment]
https://github.com/commaai/openpilot/pull/24068 will probably close this

**Comment by adeebshihadeh** [comment]
This is for all the params, like mass, wheelbase, etc.

**Comment by adeebshihadeh** [comment]
Params look pretty much merged and tunes will be deleted with torque control.
