### ISSUE TITLE
Honda: cleanup brake press detection

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23643]
openpilot considers two extra conditions for brake pressed that panda doesn't. 

- [ ] determine if brake_switch is necessary, and if it is, do we need two samples?
Going back to the one history, this was done to prevent a mismatch between openpilot and the Honda PCM. Do we need this at all? Is the noise real? What signal does the PCM use?

- [ ] remove the [exception for the Ridgeline, Pilot, and Passport](https://github.com/commaai/openpilot/blob/3ca8e3653b4dd7552c2cca6d3eb6ed76c98240be/selfdrive/car/honda/carstate.py#L291)
 #475 has the history for this one.

The PCM seems to use something different than us for brake presses. Perhaps it's using a different brake pressed signal or it simply has a threshold on the brake pedal position.

**Comment by sshane** [comment]
Responses: Honda PCM seems to disable on brake switch, after up to 50 frames on occasion. However the signal we were using (`BRAKE_PRESSED` on `POWERTRAIN_DATA`) also can lag for up to tens of frames after `BRAKE_SWITCH`. Leading to instances where a `cruiseDisabled` alert was thrown on brake disengagement as the PCM disengaged before openpilot even saw the brake pressed state.

We need to `or`/`||` the two signals, as `BRAKE_SWITCH` is never 1 when in park, and in other rare circumstances (like near very end of drive, at standstill). We also need to make sure we see `BRAKE_SWITCH` twice from the car, as sometimes it rises to 1 for a single frame without any real user brake press.
