### ISSUE TITLE
GM: CAN ignition cleanup

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23645]
@sshane this can tag along with #23617. We want to entirely remove the 0x1F1 signal.

https://github.com/commaai/panda/blob/2c419de8b0c34d1985cf7f952594e5b6f7d6477f/board/drivers/can_common.h#L199

**Comment by sshane** [comment]
Looking at the data, there's a lot of routes from dongle id `420070a24c33e506` where it's only onroad for a few seconds, then goes back offroad, so it's possible the old ignition signal we're using has many false positives. Here's a specific case: `420070a24c33e506|2021-11-06--09-36-13`

A few plots: https://imgur.com/a/PEYtWm5

Checked 15232 segments, 1633 unique routes, and 49 unique dongles. The only cars where we have any mismatches at all are the Volt (281 segments with reasonable mismatches), and only two instances on the Denali where the difference is that it's offset by a frame or two.

These are the cars missing that I didn't check: `['HOLDEN ASTRA RS-V BK 2017', 'CHEVROLET MALIBU PREMIER 2017', 'CADILLAC ATS Premium Performance 2018', 'BUICK REGAL ESSENCE 2018']`

Raw data:
```
Platform: GMC ACADIA DENALI 2018
Checked 1 unique dongles, 53 unique routes, and 593 segments
Mismatches: 23 frames, 0 segments (any frame)
---
Platform: CADILLAC ESCALADE ESV 2016
Checked 10 unique dongles, 116 unique routes, and 617 segments
Mismatches: 0 frames, 0 segments (any frame)
---
Platform: CHEVROLET VOLT PREMIER 2017
Checked 45 unique dongles, 1464 unique routes, and 14022 segments
Mismatches: 751821 frames, 342 segments (any frame)
```
