### ISSUE TITLE
pedal: make openpilot and panda thresholds match

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#23667]
Verify by removing [these exceptions](https://github.com/commaai/openpilot/blob/1c31c9b7a3b0ee72b9dca443067deab793e19187/selfdrive/test/test_models.py#L210) in the tests.

- [x] Honda
- [x] Toyota

**Comment by sshane** [comment]
Adding to this, the signals also don't line up quite right. Looks like there's a constant offset of about 5 units, and it doesn't closely match the gas pedal percentage from the car, but that's probably okay as it varies from car to car.

A Corolla TSS-P (`9eca4c02a35f86c3|2022-01-26--12-59-39--2`): https://user-images.githubusercontent.com/25857203/152479219-e34fd290-884f-4994-84a5-54b3abac7850.png
