### ISSUE TITLE
Error trying to use Carla

### ISSUE THREAD

**Issue by maykonpacheco** [commaai/openpilot#23664]
### Describe the bug

When I try to run CARLA using the ./start_openpilot_docker.sh command, I always get the same error.
This error does not prevent the UI from opening, but when I finish the entire installation, CARLA does not work.

![image](https://user-images.githubusercontent.com/38124066/151680551-f78dccff-f39f-4240-a4f6-33ced34a6370.png)

![image](https://user-images.githubusercontent.com/38124066/151680583-38f93648-2b28-47c4-a465-cb84bbbb7353.png)

How to reproduce the error.
Open a terminal and run the command
cd tools/sim ./start_carla.sh

Open another terminal and run the command
cd tools/sim ./start_openpilot_docker.sh 

![image](https://user-images.githubusercontent.com/38124066/151680715-4aed82ed-6ed0-4057-96fc-5bff2f1d0e3b.png)

### OS Version

Ubuntu 20.04

### openpilot version or commit

5fb9c6aa683e8a4ecd7591ecc76c9f29e30b060e

### Additional info

And the first time I'm running openpilot on my computer.

**Comment by rzeydelis** [comment]
I am getting the same error. It seems like the "Intro" module was added where you have to go through the tutorial and terms and conditions, which might be leading to this error.

**Comment by adeebshihadeh** [comment]
The bridge crash was fixed with 36a3ec04bec98f6b61ada90cdda692dc6fdc0416.

**Comment by maykonpacheco** [comment]
Now it's working
