### ISSUE TITLE
Dashcam mode on Honda CRV hybrid 2019

### ISSUE THREAD

**Issue by rogerkerse** [commaai/openpilot#23669]
### Describe the bug

Everything is connected properly and when I turn on the car, I only get a message “Dashcam mode”.

### What hardware does this issue affect?

comma three

### Which car does this affect?

Honda CR-V hybrid 2019

### Provide a route where the issue occurs

11fa019479471a0a|2022-01-30--16-19-33--0

### openpilot version

0.8.12

**Comment by adeebshihadeh** [comment]
Looks you have the `dashcam` branch installed, which is only for passively recording logs.
