### ISSUE TITLE
C3 auto restarts after after shutdown

### ISSUE THREAD

**Issue by alancyau** [commaai/openpilot#23688]
### Describe the bug

While the vehicle is turned on and the user clicks on the power off button, the C3 will automatically reboot after it has shutdown. This is expected behavior per @robbederks. I suggest disabling the power off button while the vehicle is on, similar to how the calibration toggle is handled.

Discussed with @robbederks and he said to submit a PR/issue.

@sunnyhaibin, can you take this?

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

N/A

### openpilot version

0.8.12

**Comment by sunnyhaibin** [comment]
@alancyau This is merged with hiding the power button while onroad. Should be good to close.
