### ISSUE TITLE
athenad: ignore duplicate upload requests

### ISSUE THREAD

**Issue by gregjhogan** [commaai/openpilot#23705]
If two requests come in to upload the same file to the same URL (excluding query params) the second should be ignored if the first is still in the queue or is currently uploading.

**Comment by pd0wm** [comment]
Doesn't it make more sense to remove the existing one and replace it by the new one?

**Comment by gregjhogan** [comment]
That would be better.  I was worried there might be race conditions related that would result in it still getting uploaded twice.  Now that I think about it again, maybe if a request to upload the same file to the same host name comes in we can update the URL in the existing queue item to accomplish this?

**Comment by zutila** [comment]
@adeebshihadeh

**Comment by gregjhogan** [comment]
This was closed by #25062
