### ISSUE TITLE
add fingerprint for 2020 toyota rav4 hybrid

### ISSUE THREAD

**Issue by drleuk** [commaai/openpilot#2373]
add fingerprint for 2020 toyota rav4 XLE hybrid

**Device/Version information (please complete the following information):**
 - Device: commatwo
 - Dongle ID: 45a8364561b5d149

**Additional context**

**Comment by VirtuallyChris** [comment]
please connect your device to wifi, currently we have no drives from this dongle ID.

**Comment by drleuk** [comment]
Completed. Can close case.
