### ISSUE TITLE
Bolt EV

### ISSUE THREAD

**Issue by Sid928** [commaai/openpilot#23736]
I would really like to get the Comma ai system set up on my 2020 Bolt EV.  Can anyone help?

**Comment by adeebshihadeh** [comment]
Car support largely comes from the community. Check out our [Discord](https://discord.comma.ai) or GitHub Discussions for getting started.

**Comment by Sid928** [comment]
I posted a message.  I hope someone will be able to help.

________________________________

**Comment by Sid928** [comment]
As you may know, the recalled Bolts are now getting battery packs to replace the recalled ones.  I hope that you will be able to get the years of the Bolts updated and supported at some point.

Thanks,
Sid

________________________________

**Comment by darknight111** [comment]
Hi Sid,

Check out the opgm repository on GitHub. They is the most up to date Bolt and GM development.
