### ISSUE TITLE
2022 Honda Ridgeline noisy pedal fix.  is 2021 software incorporate this modification?

### ISSUE THREAD

**Issue by sammy1859** [commaai/openpilot#23758]
### Describe the bug

Does 2021 Honda ridgeline software include the 0.1 noise correction or does it have to be done manually? I am using it on a new 2022

### What hardware does this issue affect?

comma three

### Which car does this affect?

2022 Honda ridgeline

### Provide a route where the issue occurs

1

### openpilot version

/

**Comment by vanillagorillaa** [comment]
This fix will be in the 0.8.13 release which should be out soon. You won't need to change anything.
