### ISSUE TITLE
Honda Passport: user brake press false positive

### ISSUE THREAD

**Issue by gricha01** [commaai/openpilot#2376]
**Describe the bug**
I have a 2019 Honda Passport. With open pilot engaged, 40mph on the city streets, if there is a car stopped at the red light in front of me as i approach it, it does not even try to slow down. i have to take over and initiate the stop. if i remember correctly it just shuts off, no beeboop.

**How to reproduce or log data**
you can reproduce it by driving toward a car at a stop light, does it every time.

**Expected behavior**
I am expecting it to start to slow down till it reaches its lowest ACC speed of 26 mph

**Device/Version information **
 - Device: comma two
 - Dongle ID: d5450ec7974784ca
 - Route: d5450ec7974784ca\|2020-10-20--17-06-17 
 - Timestamp: 17:09:15/17:10:09/17:11:22/17:13:12/17:16:12
 - Version: openpilot v0.7.9-release
 - Car make/model: Honda Passport 2019

**Additional context**
I went on a trip 2 days ago and this may be tied in. while on a 2 1/2 hour drive down the freeway it would pace cars no problem, but if a car changed lanes into my lane it would just disengage, no beeboop. just disengage.

**Comment by gricha01** [comment]
So, any updates? What should I do?

**Comment by pd0wm** [comment]
![2020-11-09-064152_666x1129_scrot](https://user-images.githubusercontent.com/1314752/98555338-aecaf300-2256-11eb-9b8f-b7ef7de4e3ac.png)

I looks like your car has a little offset in the USER_BRAKE signal. When openpilot sends a brake command this brings it just over the threshold for the brake detection, causing a disengage. Specifically this check triggers: https://github.com/commaai/openpilot/blob/master/selfdrive/car/honda/carstate.py#L309.

Can you try removing that check (which according to the comment is only for pedal users), and see if that fixes your issue?

**Comment by gricha01** [comment]
I'm sorry, only had this for 20 days. how do i remove it? I've only had it plugged into the car so for. 
Tell me what to do, where to go in it. and what to remove and I'll do.  
Thanks George

**Comment by gricha01** [comment]
Can you or someone there remove it? i don't have a clue how to remove it. I tried asking in discord, but got no help.

**Comment by adeebshihadeh** [comment]
Is this still an issue?

**Comment by gricha01** [comment]
Yes. I still have the issue. I do not know how to SSH. Is there someone you can recommend or who I can look for on discord to correct this? When I ask I only get told to go to YouTube and learn SSH. I'm not a computer person. I just would like to hire someone to tap into it and fix it.

**Comment by sshane** [comment]
The offsets seem to be different across the three cars where it checks if `ret.brake` > 0.05. The Ridgeline's offset is 0.02 where it has no noise, and the Passport is 0.05 with lots of noise: 
![Screenshot from 2021-06-21 14-14-01](https://user-images.githubusercontent.com/25857203/122829081-5d2e2080-d29b-11eb-946e-9c95d25a5378.png)
![Screenshot from 2021-06-21 14-14-09](https://user-images.githubusercontent.com/25857203/122829086-5ef7e400-d29b-11eb-9bca-eb313375d180.png)

Should we fix this in the DBCs, or remove this check altogether? From what I've seen `cp.vl["POWERTRAIN_DATA"]["BRAKE_PRESSED"]` is catching all of the brake press cases even at low speeds.

**Comment by adeebshihadeh** [comment]
I checked the commit in one responsible for those lines. It seems to be a mitigation for a grinding noise when disengaging with the brake pedal at low speeds. Since then, we've merged a few PRs to address other grinding noises. Do we still need that code?

**Comment by justinmccaffrey** [comment]
Are you still having this issue? I've never had this with my 2021 passport (Openpilot Sept 2021-Present)

**Comment by gricha01** [comment]
Yes I am.

**Comment by gricha01** [comment]
Yes I am.

    On Friday, November 5, 2021, 08:27:45 PM CDT, justinmccaffrey ***@***.***> wrote:  
 
 


Are you still having this issue? I've never had this with my 2021 passport (Openpilot Sept 2021-Present)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fraserxiong** [comment]
Hi, Can I create a temporary branch that has a threshold of 0.6 without getting banned by comma?

**Comment by adeebshihadeh** [comment]
This should be fixed by #23641

**Comment by gricha01** [comment]
I am running V0.8.13 and can confirm this is no longer happening. The only thing i am getting now is the same that is listed in #23821. thanks everyone.
