### ISSUE TITLE
calibration tool?

### ISSUE THREAD

**Issue by myf** [commaai/openpilot#238]
was just trying to test out openpilot 0.4.2 with grey panda, after calibration it seems that our car got really close to the right lane marker and sometimes we would ride on top of the lane. People suggested that the position of the NEO is very important. We simply eye-balled it instead of calibration. Is there any calibration tool that comes with and if not, would there be interests in making one since it's kinda crucial to the whole system?

**Comment by Glidepathuav** [comment]
You will need to fabricate a fixture to help aid in perfect install in
order to make it all jive.

**Comment by vanillagorillaa** [comment]
Just going to drop this here .... 

https://community.comma.ai/wiki/index.php/Gridded_UI

**Comment by myf** [comment]
ahh that is very relevant, thank you

On May 1, 2018 12:11:34 AM EDT, vanillagorillaa <notifications@github.com> wrote:
>Just going to drop this here .... 
>
>https://community.comma.ai/wiki/index.php/Gridded_UI
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/commaai/openpilot/issues/238#issuecomment-385594927

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
