### ISSUE TITLE
Bigmodel: Phantom braking, possible incorrect lead & controls lag (braking)

### ISSUE THREAD

**Issue by zorrobyte** [commaai/openpilot#23804]
### Describe the bug

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/7257172/154824440-872b0684-0d5a-4ca8-b834-3625f235e207.png">

As far as I can remember, the lead indicator was tracking the car on the exit ramp right and OP was braking, even though I had nothing in front of me. Cruise was set to 60~ and the car was slowing to 45~ before I had to disengage.

For the fellow readers here, here's a Toyota fork with bigmodel and stock cruise if you wanna try it out before a fix: https://github.com/zorrobyte/openpilot/tree/zorropilot-stockcruise

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

4aa5d874f367adbc|2022-02-19--19-45-14--10

### openpilot version

85efde269da2680a77c75c248aafc8c29435ca98

### Additional info

I replicated this previously, and also had issues in another instance stopping for a lead. See https://github.com/commaai/openpilot/pull/23684#issuecomment-1042371661 and following

Do you guys use any sort of vision for lead detection? If so, likely the issue as the frame piped into model is much larger now.

**Comment by zorrobyte** [comment]
![image](https://user-images.githubusercontent.com/7257172/154824890-518d9c5f-1899-4fb2-b503-e9943eaf4d23.png)

**Comment by vanstinator** [comment]
Comma 2, same behavior, same sha (https://github.com/commaai/openpilot/commit/85efde269da2680a77c75c248aafc8c29435ca98). I was in the right exit lane and there was a car in front of me and a car in the middle lane a little further ahead. Lead indicator jumped between 2 vehicles while I was in an exit.

`27b1608e5d22ba94|2022-02-19--20-24-05--16`

<img width="808" alt="image" src="https://user-images.githubusercontent.com/577219/154825751-7e3204c9-9bd0-4ddf-8c0c-5aeb918be33e.png">

**Comment by zorrobyte** [comment]
This stop felt pretty rough and reminds me of controls lag from previously, could have just been expected behavior, but still wanted to include:
`4aa5d874f367adbc|2022-02-19--23-05-39--19`

I have a route from a previous commit that had the same phantom braking behavior around the same place on the interstate:
`4aa5d874f367adbc|2022-02-16--14-26-49`

Here is a disengagement due to very laggy controls, as Harold mentioned in the commit:
`4aa5d874f367adbc|2022-02-16--18-50-12--5`

![](https://user-images.githubusercontent.com/6804392/154409254-ba78367b-831d-4a4c-b43f-0d6641253b9f.png)

**Comment by scottadair** [comment]
Had something similar happen to me. Driving on the highway and came around a corner which had an on-ramp. OP locked onto the cars on the merge and slowed down.

4b8ae689eaa74602|2022-02-20--11-30-16

**Comment by JoshHobbs** [comment]
Here's one where I believe it was braking for oncoming traffic.

255403b2bd0acb75|2022-02-21--17-32-13--4

**Comment by HaraldSchafer** [comment]
There was a bug in how the bigmodel wideframe was transformed. Which had a pretty big impact on performance. This should fix
https://github.com/commaai/openpilot/pull/23817

@zorrobyte Btw that laggy control disengagement has nothing to do with bigmodel, the phantom braking though is probably this bug

**Comment by zorrobyte** [comment]
> There was a bug in how the bigmodel wideframe was transformed. Which had a pretty big impact on performance. This should fix #23817
> 
> @zorrobyte Btw that laggy control disengagement has nothing to do with bigmodel, the phantom braking though is probably this bug

Thank you for looking into it and the fix so quickly! I'll keep an eye out for the new model and look forward to testing it, will be happy to close this issue once resolved
