### ISSUE TITLE
Steering bug during turns

### ISSUE THREAD

**Issue by jcwillia1** [commaai/openpilot#23839]
### Describe the bug

during a right turn on my commute on 2/22 5:10-ish pm with open pilot engaged, the car's steering wheel flipped from about 75 degrees to 105 degrees and locked there.  The screen flashed orange to take control.

I disengaged OP (I think, it happened fast) reset the driving line until the lane turned straight and re-engaged cruise.  I initially thought it was a one off issue until someone described the exact same problem on the comma subreddit this morning.

https://connect.comma.ai/587c6380f108936f/1645567568051/1645569124154

17:13 or so

Bonus fun : watch me dodge potholes at 17:08

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

https://connect.comma.ai/587c6380f108936f/1645567568051/1645569124154

### openpilot version

08.13

**Comment by sshane** [comment]
It looks like from around 40 degrees you started touching the wheel to override and take the turn
![Screenshot from 2022-02-23 10-43-28](https://user-images.githubusercontent.com/25857203/155386481-ce5cabe7-cc1f-425c-ba7d-bee50752ccce.png)

**Comment by adeebshihadeh** [comment]
This is also unrelated to the issue reported on Reddit with the Subaru Ascent.

**Comment by sshane** [comment]
Can you verify which segment this occurred? The timestamps seem to be off in connect.

**Comment by sshane** [comment]
The take control alert was caused by an internal angle limit in your car, as Hyundai limits you to ~90 degrees and won't steer past that.

![Screenshot from 2022-02-24 22-46-36](https://user-images.githubusercontent.com/25857203/155668115-237d9ed2-a6f7-4306-9a30-af3adc2614d5.png)
