### ISSUE TITLE
WSL2 Ubuntu 20.04 has missing llvm api public key.

### ISSUE THREAD

**Issue by thavens** [commaai/openpilot#23855]
I fixed the issue by just downloading llvm with the automated installer.
`sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"`
After that was able to find the gpg key.
Maybe a check could be added to solve this issue.

Below are images in order of commands:
![image](https://user-images.githubusercontent.com/67104840/155645478-e41fd0f2-bfff-45a9-b4bb-2b533722ec0f.png)
![image](https://user-images.githubusercontent.com/67104840/155645566-304791f0-6e49-4c16-8f81-d083592b31ab.png)

**Comment by pd0wm** [comment]
This sounds like an issue with your (WSL) setup. It's complaining about a bionic (18.04) package.
