### ISSUE TITLE
Laneless Model Failing to Complete Lane Change

### ISSUE THREAD

**Issue by SushiFerret** [commaai/openpilot#23866]
### Describe the bug

When requesting a lane change, the car began to move into the next lane before suddenly stopping and beginning to push itself back into the original lane. During this instance, though openpilot was still engaged, I still provided a manual steering override to force it to complete the lane change. 

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

35e10875cf1c90ea|2022-02-25--20-33-36--8

### openpilot version

0.8.13

### Additional info

Bug occurs at 20:42:33

**Comment by adeebshihadeh** [comment]
We've pushed quite a few models since 0.8.13. Feel free to open a new issue if you're still having issues.
