### ISSUE TITLE
Git high CPU/RAM usage

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#23879]
git garbage collection sometimes uses a lot of memory until it gets OOM killed. This can happen while onroad and cause lags.

- [ ] Ensure `git gc` is only ever started by `updated` and running in the overlay, never triggered by something like`version.py`.
- [ ] Ensure updated is immediately canceling any ongoing git/copy operations when going onroad.

**Comment by jyoung8607** [comment]
> git garbage collection sometimes uses a lot of memory until it gets OOM killed. This can happen while onroad and cause lags.

Long term, ulimits or cgroups to manage physical memory maximums might be a wise complement to the already existing CPU and IO priority management.
