### ISSUE TITLE
OP Long creeping with lead car stopped

### ISSUE THREAD

**Issue by redacid95** [commaai/openpilot#23884]
### Describe the bug

When lead car comes to a stop, OP seems to react and come to a stop, but then start to creep forward even when lead car doesn't move. This happens almost every complete stop, regardless of the scene. 

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

f1055ddb93ff2d3b|2022-02-28--17-15-08--9

### openpilot version

49eb4fb776c0199153b8bf9e274199090c0cb291

### Additional info

Additionally, I am on OP long on Honda Bosch. I understand this is experimental, so let me know if this is something that should be resolved with E2E.

I can also get more segments if required. 

It appeared that this was being looked into here, however I tried these changes and still experienced the issue. https://github.com/commaai/openpilot/pull/23838

**Comment by pd0wm** [comment]
The issue could also come from vision only longitudinal, the lead distances/speeds aren't always self consistent for stopped cars. Closing this issue since it's not expected to work right now.
