### ISSUE TITLE
Thermal controller doesn't work if the offroad temp is high -> onroad

### ISSUE THREAD

**Issue by khoi** [commaai/openpilot#23907]
### Describe the bug

Context:
- I parked the car outside the sun, the avg CPU temp is 85 C
- Start the car, maximum aircon, the temp still stay at > 80C until the end of the trip
- Normally, my CPU temp is around 65 - 70 C

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

ec07911a91f863f3|2022-03-04--12-55-50

### openpilot version

f539d9c0bce0b3b992ab1a3ff128de01fefa3c41

**Comment by robbederks** [comment]
![image](https://user-images.githubusercontent.com/894159/156754708-aec33aad-80aa-46ba-807e-f3d083f64492.png)

It looks like your device stayed inside of the yellow thermal zone for the whole drive (which allows you to use the device as normal, no blocker on engage / going onroad). To get out of that zone, your CPU should have gotten to 96C (above this we start seeing some throttling of the chip), which means you had about 10C of margin still. 

The thermal policy worked as intended, and is slowly integrating the fan speed up to get your CPU temp back to the set point of 75C. It is possible to be a little more aggressive on the fan speed, which would result in a bit more fan noise but usually not much extra cooling power.

The recent switch to the bigmodel has caused quite a bit of extra GPU load (and thus thermal output), which might explain your sensation of the device running hotter than you were used to. Nothing to worry about imo.
