### ISSUE TITLE
Driver Monitoring alerting "Pay attention"  even though i'm watching road

### ISSUE THREAD

**Issue by joelegg** [commaai/openpilot#23914]
### Describe the bug

0.8.13 SA driver monitoring is alerting me i am not concentrading. and gets to the point where the red alert goes off. 

This occurs 

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

https://connect.comma.ai/dc25f84f7b307cc9/1646636797147/1646636871553

### openpilot version

0.8.13

### Additional info

this is running on shanes fork but i undertand he doens't adjust driver monitoring and was told to submit feedback here by your team in DM Feedback. 

The issue occurs (red alert) at 6:07pm 7th March 2022

**Comment by ZwX1616** [comment]
![Screenshot from 2022-03-07 16-37-37](https://user-images.githubusercontent.com/7658937/157142457-7a57b37f-6000-4bcb-a841-68f8af9484ac.png)

This seems to be model runtime errors in pose estimation when running the quantized model on the DSP and I was able to reproduce the same behavior from your segment on my c3.

Luckily we have been putting work in minimizing snpe model error lately, and the next model for release will not suffer from this.
