### ISSUE TITLE
DM alerting me to pay attention only during sunset period.

### ISSUE THREAD

**Issue by kinng** [commaai/openpilot#23921]
### Describe the bug

Drove during daytime without a single DM issue.  Then on the return trip just after sunset, thus the sky is still somewhat bright and my car was facing west, DM was alerting me to pay attention almost nonstop.  After stopping to shop and a gas fill up, the sky was still a little bright and the DM resumed alerting me.  About 10 minutes later when the sky is pretty dark then everything is back to normal again.
I have noticed when it's alerting me, the DM icon was dimmed.  i.e. the camera couldn't see me.  I wiped the lens with a tissue but had no effect.
On the driver preview screen, my face is to the upper left corner of the highlighted rectangle, and my hair is above it; and I do wear glasses.
I did slide my body down a little to allow my face to be within the bound of the highlighted rectangle and it helped minimize the alerts.  
Would be great if the highlighted rectangle's position can be adjusted by the user.

### What hardware does this issue affect?

comma three

### Provide a route where the issue occurs

9ff6adaf72343a2c|2022-03-05--18-10-27

### openpilot version

0.8.13

### Additional info

Only mod was changing CAMERA_OFFSET to -0.13 in lane_planner.py.
C3 was mounted dead center with both calibrations less than 1.  I did mount it about 2 inches lower in order not to block my dash cam.
Car is 2017 Toyota Highlander Hybrid.

**Comment by ZwX1616** [comment]
The model does struggle a lot when there is extreme lighting splits on the driver face. We will try to improve this in future models combined with HDR2.0 on c3
