### ISSUE TITLE
Lateral MPC is undershooting future predicted plan

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#23935]
It seems the lateral MPC's plan is not very accurate when compared to the actual future plan in `steerActuatorDelay` seconds. We can't interpolate the lateral plan to 100 Hz until this is fixed, but I'll look into it some more and confirm it's a real issue. Closing https://github.com/commaai/openpilot/pull/23788 until it doesn't cause oscillations.

Longitudinal:
![Screenshot from 2022-02-25 14-43-30](https://user-images.githubusercontent.com/25857203/157407131-72962988-aaae-4a1e-85eb-516f091a63aa.png)

Lateral:
![Screenshot from 2022-02-25 14-31-43](https://user-images.githubusercontent.com/25857203/157407151-9ea18d8f-61d9-4bd1-816d-eb27298c8f31.png)

**Comment by GregorKikelj** [comment]
Do you take this into account? https://github.com/commaai/openpilot/blob/4f4f18a648f8b5ec1fa63c60f69da1a32e60d9a5/selfdrive/controls/lib/drive_helpers.py#L99

**Comment by sshane** [comment]
Yup, I compared now + 0.2 seconds vs. the actual plan in 0.2 seconds

**Comment by ClockeNessMnstr** [comment]
Is the orange line time  shifted curvatures[0] and the blue line OP's current get_desired_curvature? For 0.+.2s

Was about to mention they looked right but this would be backwards from expected I think

**Comment by GregorKikelj** [comment]
@ClockeNessMnstr I think it's exactly that yeah. Got better match here by using 
`psi_interp = interp(0.2, T_IDXS[:CONTROL_N], lat_plan.psis)
psi_interp_curvature = psi_interp/(max(CS.vEgo, 0.001)*0.2)`

**Comment by adeebshihadeh** [comment]
Have you confirmed this is a real issue?

**Comment by sshane** [comment]
Well I assume so since we can't interpolate the plan to 100Hz. However I haven't confirmed that it's an issue *recently*, so if anyone doesn't do that, I'll check in the next few weeks

**Comment by adeebshihadeh** [comment]
@sshane is this still relevant?

**Comment by sshane** [comment]
Yassine was going to check it out

**Comment by adeebshihadeh** [comment]
Closing, @YassineYousfi feel free to re-open if it's still an issue
