### ISSUE TITLE
Toyota: blind spot monitor detection is flaky

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#23944]
In route `4289612fe1127f18|2022-03-10--04-13-46` (and probably many others), we miss the 1 Hz BSM message and openpilot thinks there's no BSM sensors, when in actuality we just miss the low frequency message.

**Comment by adeebshihadeh** [comment]
Let's see if there's a higher frequency message that also indicates whether there's BSM. I'd like to avoid increasing the min fingerprinting time.

**Comment by sshane** [comment]
Kumar on Discord said there's another message which sends at 5 Hz:

![Screenshot from 2022-03-09 23-13-21](https://user-images.githubusercontent.com/25857203/157608444-54845755-e87e-4630-9ffb-950e509963f6.png)

**Comment by adeebshihadeh** [comment]
See https://github.com/commaai/opendbc/pull/190

**Comment by sshane** [comment]
Fixed in https://github.com/commaai/openpilot/pull/24964
