### ISSUE TITLE
Vehicle parameter identification fault

### ISSUE THREAD

**Issue by ninjaphysics** [commaai/openpilot#2394]
Hello I’m having an issue with my jeep grand Cherokee 2017, everything was working fine until a recent update I am now getting vehicle parameter identification called whenever I try to engage open pilot. I am attaching a video showing what happens. Please let me know what I can try to fix this issue. 

Also here is the Cabana link to the time when I took this video: 

https://my.comma.ai/cabana/?route=6d2a1f125a515d2a%7C2020-10-20--16-04-52&exp=1635010309&sig=cpiDFqxCPhNaUBcHojTh9Vzb1huFEsQpx4%2FFEnEbqLQ%3D&max=31&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F6d2a1f125a515d2a%2F1e4add4d344d6e69376b83b08c3bab74_2020-10-20--16-04-52

[Video.zip](https://github.com/commaai/openpilot/files/5430897/Video.zip)

**Comment by pd0wm** [comment]
Your steer ratio became negative due to very brief localizer error in a route on September 12. In 0.7.10 I added some logic to reset the parameters, so if you update it should be fixed. You can also reset your calibration, that should also delete the wrong parameters.
