### ISSUE TITLE
HKG resume logic not working on Hyundai Genesis(2015-2016)

### ISSUE THREAD

**Issue by xps-genesis** [commaai/openpilot#2395]
**Describe the bug**

The new resume logic in Master-Ci for HKG doesn't work on the Hyundai Genesis(2015-2016), This can be an issue with other older HKG cars. The resume logic is triggered when the standstill flag from SCC is set. This often allows the SCC to accept once or twice during a stop but often misses when the lead starts to move. 

**How to reproduce or log data**

ACC activated behind a stopped target vehicle to start the resume logic 

**Expected behavior**

Resume and continue moving when the lead starts to move.

**Device/Version information (please complete the following information):**
 - Device: [comma two]
 - Dongle ID: [6fe86b4e410e4c37]
 - Route: [6fe86b4e410e4c37|2020-10-23--19-14-59]
 - Timestamp: [497 seconds]
 - Version: [master-ci]
 - Car make/model: [Hyundai Genesis 2015-16]

**Comment by adeebshihadeh** [comment]
Is this still an issue?

**Comment by xps-genesis** [comment]
yup still doesn't work on older vehicles

**Comment by SeanCox** [comment]
I tested the PR and left some notes for this https://github.com/commaai/openpilot/pull/25579

**Comment by SeanCox** [comment]
@adeebshihadeh This issue has been fixed.
