### ISSUE TITLE
Steer Unavailable Below xx mph alert on HKG stays on even above min steer speed

### ISSUE THREAD

**Issue by xps-genesis** [commaai/openpilot#2397]
**Describe the bug**
On a vehicle with min steer speed, the alert stays on for 4m/s above the min speed.

**How to reproduce or log data**
Enable OP at speed below min steer speed. Accelerate the vehicle above min steer speed. The steering is controlled above min steer speed however the alert stays on until the speed is above (min_steer_speed + 4m/s).

**Expected behavior**
offset_speed = 1m/s, when vehicle speed is above (min_steer_speed +1m/s)
offset_speed = 0m/s, when vehicle speed is below min_steer_speed
 - Alert should be displayed when vehicle speed is below (min_steer_speed + offset_speed)

**Device/Version information (please complete the following information):**
 - Device: [comma two]
 - Dongle ID: [6fe86b4e410e4c37]
 - Route: [6fe86b4e410e4c37|2020-10-23--19-14-59]
 - Timestamp: [122 seconds <]
 - Version: [Master-Ci]
 - Car make/model: [Hyundai Genesis 2015-16]

**Comment by adeebshihadeh** [comment]
This is because of the [hysteresis logic](https://github.com/commaai/openpilot/blob/master/selfdrive/car/hyundai/interface.py#L261) to prevent the event from flickering back and forth while around the min steer speed. If the hysteresis gap is too big, feel free to open a PR to improve it.
