### ISSUE TITLE
Crossing double yellow lines left turns, mostly night

### ISSUE THREAD

**Issue by brandon8791** [commaai/openpilot#2399]
**Every time at night on left turns, car wants to ride on yellow line or cross the double yellows... most of the time I try to hold the steering wheel and correct it, can plainly see it on the comma ai screen**

**How to reproduce or log data**

<! Drive at night, will cross double yellow lines on left turns. -->

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [e.g. EON Gold]
 - Dongle ID: 6229d6b7f184457b
 - Route: any night time drive
 - Timestamp: couldn’t figure out
 - Version: Latest v0.7.9 release
 - Car make/model: [ Toyota Prius 2016 ]

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/issues/2361
