### ISSUE TITLE
Hyundai longitudinal: long press to increment by 5 mph inconsistent

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#23997]
Does not work 100% of the time, more likely to work shortly after incrementing by just one?

Route example: 5decac85ab437ed1|2022-03-18--07-53-37

**Comment by adeebshihadeh** [comment]
Still an issue? I haven't noticed it in the sonata.

**Comment by sshane** [comment]
We have tests now! Doesn't seem to be an issue anymore
