### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [commaai/openpilot#240]
Hi,
I have design this logo with the letter O and P, if you like you can keap it for this project.
If you want it I will give you all the formats of the design free. If you want to make changes please specify.

Greetings

![oplogo-model](https://user-images.githubusercontent.com/34600369/39528353-c55dd8e2-4e1b-11e8-9599-cf2f77a3e89e.png)

**Comment by joshuairl** [comment]
I love it.  Its simple but very brilliant.  I support it.

**Comment by nunojesus** [comment]
Thanks, what color do you prefer as the main logo, I can send you also the other colours too.
Can I make the png files to send to you?
Greetings!

**Comment by nunojesus** [comment]
See if you like the font type

![oplogo-model2](https://user-images.githubusercontent.com/34600369/39575442-76960826-4ed2-11e8-89ce-8c0c7a59b0f0.png)

**Comment by mtourangeau** [comment]
What about this? I did not complet the O because I'm not good at using MS Paint :)
![openpilot](https://user-images.githubusercontent.com/33037289/39575647-51b2ba64-4ea9-11e8-8f26-58f975e2c4fa.png)

**Comment by joshuairl** [comment]
Not digging the type.  @mtourangeau That's not too shabby either.

**Comment by nunojesus** [comment]
in my opinion the logo that I presented has a stronger presence, but you decide what is best for the project.

**Comment by nunojesus** [comment]
Since I dont have feedback from you I will close this issue. Good luck for your project.
