### ISSUE TITLE
Openpilot in Simulation Mode is not using IMU data.

### ISSUE THREAD

**Issue by rahul-arasikere** [commaai/openpilot#24016]
### Describe the bug

When running the bridge.py script to bridge the Carla server, in the IMU callback, the sensorEvent packet does not set a timestamp, and hence in locationd, the packet is rejected as it checks the timestamp to 0, and rejects the packet as it assumes there is no valid data.

I am not sure if in simulation mode this is the expected behaviour or a bug and wanted to point it out.

A possible solution would be to extend common.clock.pyx to include a `nanosec_since_boot()` function as the carla server maintains simulation time apart from linux.

### OS Version

Ubuntu 20.04

**Comment by tiredDev** [comment]
Can I start working on an issue or does it need to be assigned first ?

**Comment by pd0wm** [comment]
Feel free to open a draft PR once you made some progress. We don't assign issues.

**Comment by equilibrium-liberalism** [comment]
> ### Describe the bug
> 
> When running the bridge.py script to bridge the Carla server, in the IMU callback, the sensorEvent packet does not set a timestamp, and hence in locationd, the packet is rejected as it checks the timestamp to 0, and rejects the packet as it assumes there is no valid data.
> 
> I am not sure if in simulation mode this is the expected behaviour or a bug and wanted to point it out.
> 
> A possible solution would be to extend common.clock.pyx to include a `nanosec_since_boot()` function as the carla server maintains simulation time apart from linux.
> ### OS Version
> 
> Ubuntu 20.04
> ### openpilot version or commit
> 
> _No response_
> ### Additional info
> 
> _No response_


Have you encountered following issue when running bridge.py ? sorry for a entry level question. 

**case 1'**
~/openpilot/tools/sim$ python3 bridge.py
Traceback (most recent call last):
  File "bridge.py", line 19, in <module>
    import cereal.messaging as messaging
ModuleNotFoundError: No module named 'cereal'

**case 2**
:~/openpilot/tools/sim$     ./bridge.py
Traceback (most recent call last):
  File "./bridge.py", line 11, in <module>
    import carla  # pylint: disable=import-error
ModuleNotFoundError: No module named 'carla'

**Comment by rahul-arasikere** [comment]
You need to run the python script from the main `openpilot` folder, or update `$PYTHONPATH` to include the openpilot directory. `carla` is another python package you need along with the carla server.

**Comment by equilibrium-liberalism** [comment]
@rahul-arasikere Thank you for your reply. it enlightened me as a new bee of openpilot.

**Comment by adeebshihadeh** [comment]
fixed in #25937
