### ISSUE TITLE
Prepare for CAN fingerprinting deprecation

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#2402]

**Comment by pd0wm** [comment]
Let's add an alert in 0.8.4 if your fingerprint source is can

**Comment by adeebshihadeh** [comment]
I'm thinking this is the way we deprecate CAN fingerprinting:
* remove all the unused fingerprints (#20994)
* put CAN fingerprinting behind community features (#20993)
* remove CAN fingerprints for cars that always use FW on release
