### ISSUE TITLE
Tesla: support no disengage on gas properly

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24036]
Not sure if there's any special signals we need to send when controlling long, like `DAS_accState` or anything else. Need to make sure:

- openpilot longitudinal actuation is disabled when gas is pressed
- car does not try to accelerate more than what you're applying to the accelerator (ie. you can lightly tap the gas and coast)

Close if there's nothing we need to do

**Comment by robbederks** [comment]
This worked out of the box! Light gas gives you 0 accel, that's fine I think.
