### ISSUE TITLE
modeld cannot recover when bridge is terminated

### ISSUE THREAD

**Issue by ebadi** [commaai/openpilot#24040]
### Describe the bug

When bridge.py is terminated, it seems that modeld should keep trying until a frame is received. (https://github.com/commaai/openpilot/blob/master/selfdrive/modeld/modeld.cc#L89)
However modeld stucks in printing `vipc_client_main no frame` error messages even after bridge.py is restarted. 

### OS Version

Ubuntu 18.04

**Comment by HaraldSchafer** [comment]
I could not reproduce this. When bridge is killed, openpilot goes offroad so it kills modeld anyway? When bridge restarted modeld starts from scratch?

**Comment by HaraldSchafer** [comment]
Closing for now

**Comment by adeebshihadeh** [comment]
Probably fixed as a side effect of 302b0ea9bbac0fec939919b0d09b604569305be7
