### ISSUE TITLE
Reverse gear in simulator

### ISSUE THREAD

**Issue by ebadi** [commaai/openpilot#24041]
### Describe the bug

To recover a collision in the CARLA simulator, it helps a lot if it was possible to use reverse gear even if you don't have joystick [1](https://github.com/commaai/openpilot/blob/master/tools/sim/lib/manual_ctrl.py#L182) & [2](https://github.com/commaai/openpilot/blob/master/tools/sim/bridge.py#L336).  

Adding the line below had no effect:
```
def keyboard_poll_thread(q: 'Queue[str]'):
  while True:
    c = getch()
    # print("got %s" % c)
    if c == '1':
      q.put("cruise_up")
    elif c == '2':
      q.put("cruise_down")
    elif c == '3':
      q.put("cruise_cancel")
    elif c == 'w':
      q.put("throttle_%f" % 1.0)
    elif c == 'a':
      q.put("steer_%f" % 0.15)
    elif c == 's':
      q.put("brake_%f" % 1.0)
    elif c == 'd':
      q.put("steer_%f" % -0.15)
    elif c == 'r':  # <-----
      q.put("reverse_switch")
    elif c == 'q':

```

### OS Version

Ubuntu 18.04

**Comment by adeebshihadeh** [comment]
I don't think it's useful to keep the manual control stuff for the simulator. I think we'll focus on making the openpilpot experience good in the simulator and perhaps add a reset button for this case.
