### ISSUE TITLE
Improve alert verbosity

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24066]
Alerts should give more insight into what the actual problem is.

- [x] Camera Malfunction might also be lag.
  - [x] Remove "contact support"
  - [x] show which camera(s) are lagging
  - [x] ensure it's not showing when the whole system is lagging.
- [x] commIssue should show the processes that are lagging 
- [x] split out commIssue average frequency check into own alert
- [x] startupNoFw: can we make more clear that the ob-ii port is used for fingerprinting
- [x] outOfSpace: almost never happens, but show remaining space?
- [x] overheat: show temperature
- [x] calibrationInvalid: show angles
- [x] processNotRunning: show process name
- [x] modeldLagging: show frame drop percentage 
- [x] lowMemory: show remaining memory 
- [x] <s>highCpuUsage: show cpu usage</s> unused
- [ ] canError: show bus(es) for whole dropout, message id(s) for wrong checksum/counter
- [x] relayMalfunction: explain actual fault?
- [x] Model Output Uncertain: posenet speed vs car speed

**Comment by adeebshihadeh** [comment]
For canError, I added cloudlog support in opendbc, and the checks that throw canError are logged in the qlog with the specific check and message address.
