### ISSUE TITLE
2018 Sonata w/LKAS + Collision avoidance

### ISSUE THREAD

**Issue by Brandon-Myers** [commaai/openpilot#241]
I have a 2018 Sonata with LKAS and the front radar for adaptive cruise control and collision avoidance.

What would it take for me to start a pilot program to have this car (And other Hyundai's with the same equipment) supported?

**Comment by Brandon-Myers** [comment]
FYI: Read the medium article about the Toyota.

**Comment by vanillagorillaa** [comment]
Hyundai is not officially supported yet. You will need to do a port yourself or with others. I would join the slack and ask in the Hyundai channel. There are a few users working on a port and making decent progress.

**Comment by veritas2884** [comment]
@Brandon-Myers I cannot find that slack group. Has any progress been made? I have a 2016 Sonata with Lane Departure Warning and Full Stop Adaptive Cruise Control and want to get Openpilot running on it.

**Comment by energee** [comment]
[slack.comma.ai](slack.comma.ai)

**Comment by veritas2884** [comment]
@energee thanks. I don't see a Hyundai subchannel though.

**Comment by emmertex** [comment]
@vanillagorillaa This should be closed.
Hyundai/Kia are well supported by community, and supported officially.
