### ISSUE TITLE
HKG: Verify and remove cars from torque blacklist

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24122]
Need to verify if these cars can send up to 384 instead of 255 for the max torque:

- [ ] Genesis G80 2018
- [ ] Genesis G90 2018
- [ ] Hyundai Elantra 2017-19
- [ ] Hyundai Genesis 2015-16
- [ ] Hyundai Ioniq Hybrid 2017-19
- [ ] Hyundai Ioniq Electric 2019
- [ ] Hyundai Santa Fe Plug-in Hybrid 2022
- [x] Hyundai Sonata 2018-19
- [ ] Kia Forte 2018-21
- [ ] Kia Niro Plug-in Hybrid 2019
- [ ] Kia Optima Hybrid
- [ ] Kia Sorento 2018-19
- [ ] Kia Stinger 2018

**Comment by adeebshihadeh** [comment]
@sunnyhaibin any ones you already verified that we can bring over from your fork?

**Comment by sunnyhaibin** [comment]
> @sunnyhaibin any ones you already verified that we can bring over from your fork?

@adeebshihadeh Yes. Below is the list of cars that were confirmed to be able to send up to 384 for the max torque on my fork:
- Hyundai Elantra 2017-19
- Hyundai Ioniq Hybrid 2017-19
- Hyundai Ioniq Electric 2019
- Hyundai Santa Fe Plug-in Hybrid 2022
- Kia Niro Plug-in Hybrid 2019

Some of the cars on the issue's car list are using my fork as well. I will get them to test and report back.

**Comment by adeebshihadeh** [comment]
Great, that's a good chunk of the remaining ones!

**Comment by sunnyhaibin** [comment]
@adeebshihadeh The following car is also confirmed to work well with sending up to 384 for the max torque:
- Genesis 2015 and 2016

**Comment by sshane** [comment]
Do you have any routes where these cars are commanding that torque? I can throw a branch together with them on the higher torque

**Comment by sunnyhaibin** [comment]
> Do you have any routes where these cars are commanding that torque? I can throw a branch together with them on the higher torque

That would be great if you can setup a branch for them.

I believe some users have their devices banned due to previous violations, but I'll see what I can do.

**Comment by sshane** [comment]
Let us know if you have anyone in the above list try this branch: https://github.com/commaai/openpilot/commits/h384

**Comment by sshane** [comment]
It's possible we need to reduce the steering tune when we merge these cars, @Jon8RFC on Discord noticed jerking for turns with the new higher steering torque (no faults).

**Comment by sunnyhaibin** [comment]
@sshane Here's a route with the `Hyundai Ioniq Electric 2019`!
- `8e221cf40bc9c78a|2022-04-20--17-51-52`

**Comment by multikyd** [comment]
Those cars should be okay with 384 torque including my car, Optima Hybrid 2017(MY16 K5 Hybrid from Korea). I've never heard there has been issues related to 384 from HKG old&new cars. Every HKG users will be happy with the value. Thank you Comma!

**Comment by sshane** [comment]
We will probably wait until the torque controller is added back, as raising the max torque likely means the car needs a new tune for optimal control

**Comment by gregjhogan** [comment]
I recall people saying some cars accept values higher than 255, but not getting additional torque above 255, so if we increase it we should verify we are not just adding a dead-zone at the top end of the request value range.  This should be possible by looking at the motor output torque vs request value.

I found this related conversation:
https://discord.com/channels/469524606043160576/524611978208215070/737805997992706059
```
At that time any value above 255, up to 470 something, resulted in the same torque output.
```

**Comment by adeebshihadeh** [comment]
Community has been doing a pretty good job of testing and moving cars over - don't think we need an issue for this.

**Comment by j2mc** [comment]
I see this was closed, but it appears most of the cars in this list are still being limited.  Has there been more testing done to verify these cars need to be limited?  I have a 22 Santa Fe PHEV and would be happy to provide any data that's needed.
