### ISSUE TITLE
Detect Hyundai features by CAN fingerprint

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24127]
If we can do this reliably via CAN fingerprint, we can get rid of some of these lists: https://github.com/commaai/openpilot/blob/433f649faaeb9b605827a2e898079fb6cf0b1279/selfdrive/car/hyundai/values.py#L1118

For example, the car in this PR could be removed and added to the existing Ioniq PHEV: https://github.com/commaai/openpilot/pull/24089

**Comment by adeebshihadeh** [comment]
Don't really need an issue for this
