### ISSUE TITLE
Hyundai: move cars out of legacy safety mode

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24136]
These cars seem to have the correct checksums and counters and can be removed from the [LEGACY_SAFETY_MODE_CAR](https://github.com/commaai/openpilot/blob/master/selfdrive/car/hyundai/values.py#L1132).
- [ ] HYUNDAI SONATA 2019
- [ ] KIA OPTIMA SX 2019 & 2016

**Comment by adeebshihadeh** [comment]
Let's just check all the cars and be more strict about this when merging car ports. Perhaps add it to the car port and fingerprint verification script.

**Comment by adeebshihadeh** [comment]
@sshane is this done?
