### ISSUE TITLE
Camerad and modeld not working

### ISSUE THREAD

**Issue by jsp58** [commaai/openpilot#24163]
### Describe the bug

I set up my PC for openpilot to use with webcams (following openpilot/tools/README.md and /openpilot/tools/webcams/README.md). When the car is off, the UI appers without any problem at all. However, when I turn on the car (Toyota Prius 2019 TSS), camerad and modeld fail.

### OS Version

Ubuntu 20.04

### openpilot version or commit

6c0fa7775ccd2fd69b0094ef7dc385f32f4d7af4

### Additional info

The webcams I use are: Logitech C920 for the road and a Logitech C615 for the driver.

![Screenshot from 2022-04-07 16-34-57](https://user-images.githubusercontent.com/103203066/162237309-0f578808-81a1-4414-bc78-40e7d98d95c1.png)

I run openpilot executing on the PC running:
`PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 DRIVERCAM_ID=0 ROADCAM_ID=2 selfdriver/manager/manager.py`

The output is:

`selfdrive/loggerd/bootlog.cc: bootlog to /home/jsaez/.comma/media/0/realdata/boot/2022-04-07--16-22-45.bz2
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
roadCameraState: Reader was evicted, reconnecting
sensorEvents: Reader was evicted, reconnecting
gpsLocationExternal: Reader was evicted, reconnecting
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
navd ui soundd deleter logmessaged thermald statsd
pandaStates: Reader was evicted, reconnecting
pandaStates: Reader was evicted, reconnecting
driverMonitoringState: Reader was evicted, reconnecting
peripheralState: Reader was evicted, reconnecting
./modeld: 3: Bad substitution
Waiting for CAN messages...
Getting VIN & FW versions
controlsState: Reader was evicted, reconnecting
carState: Reader was evicted, reconnecting
controlsState: Reader was evicted, reconnecting
liveCalibration: Reader was evicted, reconnecting
carParams: Reader was evicted, reconnecting
carState: Reader was evicted, reconnecting
liveLocationKalman: Reader was evicted, reconnecting
carState: Reader was evicted, reconnecting
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
liveLocationKalman: Reader was evicted, reconnecting
selfdrive/loggerd/loggerd.cc: logging to /home/jsaez/.comma/media/0/realdata/2022-04-07--16-22-58--0
platform[0] CL_PLATFORM_NAME: NVIDIA CUDA
vendor: NVIDIA Corporation
platform version: OpenCL 3.0 CUDA 11.4.94
profile: FULL_PROFILE
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
name :NVIDIA GeForce RTX 2060 with Max-Q Design
device version :OpenCL 3.0 CUDA
max work group size :1024
type = 4 = CL_DEVICE_TYPE_GPU
platform[0] CL_PLATFORM_NAME: NVIDIA CUDA
vendor: NVIDIA Corporation
platform version: OpenCL 3.0 CUDA 11.4.94
profile: FULL_PROFILE
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
[ffvhuff @ 0x7f9030002700] dimensions not set
name :NVIDIA GeForce RTX 2060 with Max-Q Design
device version :OpenCL 3.0 CUDA
max work group size :1024
type = 4 = CL_DEVICE_TYPE_GPU
loggerd: selfdrive/loggerd/raw_logger.cc:49: RawLogger::RawLogger(const char *, int, int, int, int, bool, bool, bool): Assertion `err >= 0' failed.
vin query retry (1) ...
vin query retry (2) ...
selfdrive/modeld/modeld.cc: models loaded, modeld starting
Assertion failed: ok (src/mailbox.cpp:99)
vin query retry (3) ...
Onnx available providers:  ['CUDAExecutionProvider', 'CPUExecutionProvider']
Onnx selected provider:  ['CUDAExecutionProvider']
Traceback (most recent call last):
  File "/home/jsaez/openpilot_virtualenv/openpilot8.13/selfdrive/modeld/runners/onnx_runner.py", line 58, in <module>
    ort_session = ort.InferenceSession(sys.argv[1], options, providers=[provider])
  File "/home/jsaez/openpilot_virtualenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jsaez/openpilot_virtualenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ../../models/supercombo.onnx failed:Protobuf parsing failed.
vin query retry (4) ...
controlsState: Reader was evicted, reconnecting
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
Starting listener for: camerad
vin query retry (5) ...
roadCameraState: Reader was evicted, reconnecting
camerad: selfdrive/camerad/cameras/camera_webcam.cc:72: void (anonymous namespace)::run_camera(CameraState *, cv::VideoCapture &, float *): Assertion `video_cap.isOpened()' failed.
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd
camerad clocksd logcatd loggerd modeld navd proclogd ui soundd locationd calibrationd controlsd deleter logmessaged paramsd plannerd radard thermald statsd`

I tried to execute those models separately, but the result was the same.

When running the camerad daemon:
`DRIVERCAM_ID=0 ROADCAM_ID=2 ./camerad`

The output is:
`platform[0] CL_PLATFORM_NAME: NVIDIA CUDA
vendor: NVIDIA Corporation
platform version: OpenCL 3.0 CUDA 11.4.94
profile: FULL_PROFILE
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
name :NVIDIA GeForce RTX 2060 with Max-Q Design
device version :OpenCL 3.0 CUDA
max work group size :1024
type = 4 = CL_DEVICE_TYPE_GPU
Starting listener for: camerad
camerad: selfdrive/camerad/cameras/camera_webcam.cc:72: void (anonymous namespace)::run_camera(CameraState *, cv::VideoCapture &, float *): Assertion `video_cap.isOpened()' failed.
Aborted (core dumped)`

When executing modeld, the output is:

`./modeld: 3: Bad substitution
platform[0] CL_PLATFORM_NAME: NVIDIA CUDA
vendor: NVIDIA Corporation
platform version: OpenCL 3.0 CUDA 11.4.94
profile: FULL_PROFILE
extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
name :NVIDIA GeForce RTX 2060 with Max-Q Design
device version :OpenCL 3.0 CUDA
max work group size :1024
type = 4 = CL_DEVICE_TYPE_GPU
selfdrive/modeld/modeld.cc: models loaded, modeld starting
Onnx available providers:  ['CUDAExecutionProvider', 'CPUExecutionProvider']
Onnx selected provider:  ['CUDAExecutionProvider']
Traceback (most recent call last):
  File "/home/jsaez/openpilot_virtualenv/openpilot8.13/selfdrive/modeld/runners/onnx_runner.py", line 58, in <module>
    ort_session = ort.InferenceSession(sys.argv[1], options, providers=[provider])
  File "/home/jsaez/openpilot_virtualenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__

    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jsaez/openpilot_virtualenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ../../models/supercombo.onnx failed:Protobuf parsing failed.`

**Comment by adeebshihadeh** [comment]
I'm going to close this since it isn't a specific issue. Check out our community discord for help getting started. Feel free to open new issues if you hit specific bugs.
