### ISSUE TITLE
Civic controls mismatch

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#24172]
3x controls mismatches across these routes

cfb32f0fb91b173b|2022-04-06--14-54-45
cfb32f0fb91b173b|2022-04-08--08-38-33

**Comment by redacid95** [comment]
20' Civic Hatchback Sport. Still getting control mismatches, less than what I was getting before this update. Disable on accel is set to false, and VOACC (OP Long) is enabled.

f1055ddb93ff2d3b|2022-04-12--17-30-13--4
f1055ddb93ff2d3b|2022-04-12--17-30-13--5
f1055ddb93ff2d3b|2022-04-12--17-30-13--6

**Comment by adeebshihadeh** [comment]
This is specifically for cars with a gas interceptor.

**Comment by sshane** [comment]
@redacid95 controls allowed didn't go high when you engaged, does this happen with stock ACC or only openpilot longitudinal? In any case you can open an issue and I'll look into it when I have time
