### ISSUE TITLE
Bug: face detection stopped working during daylight conditions, works fine at night

### ISSUE THREAD

**Issue by DorkSaber** [commaai/openpilot#2417]
About a week ago I started getting frequent errors saying that no face was detected on my C2 when driving during the day. It seems to happen more frequently the brighter it is outside. Night drives work fine as always. It seems that the image preview during the day off the driver-facing camera is overexposed/washed out to the point where all detail in the face is obscured, showing only a bright silhouette. Night drives are unaffected and still work fine. Driving on a sunny day though now causes disengages and alarms every few seconds when using OP unless I pretty violently jerk the wheel immediately every time the error pops up. Light tap like on the stock Honda Sensing doesn't work. IR LED's are always on now in any lighting condition, though I admit I'm not sure if they're supposed to be always on or if previously they only came on at night.

Test drive with issue reproduced and driver-facing camera uploaded: Mon, Oct 26 @ 08:00 to 08:25

**How to reproduce or log data**

Drive during the day, the brighter the more often it occurs.

**Expected behavior**

Prior to this, C2 had the same view of driver. Seat position hasn't changed and C2/rearview mirror position is the same, but face tracking was working perfectly with a very high degree of accuracy.

**Device/Version information (please complete the following information):**
 - Device: Comma2
 - Dongle ID: bc014e9a661d4a5e
 - Route: bc014e9a661d4a5e|2020-10-26--08-00-09
 - Timestamp: Throughout the whole drive about twice a minute
 - Version: 0.7.11
 - Car make/model: 2017 Honda Civic EX sedan
**Additional context**

Since this issue started, I've updated from 7.10 to 7.11, and I did an OS update that I was prompted about. Also, my UI is extremely sluggish on the C2, with time from click to response being about 3-5 seconds. Not sure if it's related. No issues driving though. Attached image is during daylight showing IR emitters on and the overexposed image of driver face.
![image](https://user-images.githubusercontent.com/72579153/97227863-73d3b480-17ac-11eb-9a71-949e6e376f18.png)

**Comment by ZwX1616** [comment]
fixed in #2418
