### ISSUE TITLE
loggerd: wasting 20% of a CPU making full frame copies on C3

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#24186]
In `OmxEncoder::encode_frame` there's a call to `libyuv::I420ToNV12`, this is a copy.

Removing this requires several things:
* VisionIPC broadcasts NV12 frames with width stride 2048
* Replace OMX_AllocateBuffer with OMX_UseBuffer on the VisionIPC buffers

Potential issues:
* OMX has only 7 buffers, VisionIPC has 40. Why do we have 40?
* Encoders wouldn't be able to fall behind

This would also free a ton of memory and cache thrashing. 40 frames is 417MB. The copies are 208 MB/s of ram bandwidth.

**Comment by geohot** [comment]
Also see #23589 to remove the scale

**Comment by adeebshihadeh** [comment]
Done in #24519
