### ISSUE TITLE
UI does not scale on screens smaller than 1080p

### ISSUE THREAD

**Issue by alisedaghatbaf** [commaai/openpilot#24267]
### Describe the bug

When I launch openpilot by running tools/sim/launch_openpilot.sh the ui shows up with a very large font size and I cannot interact with it.
![Screenshot from 2022-04-20 08-03-16](https://user-images.githubusercontent.com/31185263/164161198-3977b337-ad31-4fd8-a1e3-179be69ccb5c.png)

### OS Version

Ubuntu 20.4

### openpilot version or commit

v0.8.14

**Comment by adeebshihadeh** [comment]
Set the environment variable `SCALE` to workaround this, e.g. `SCALE=0.8 ~/openpilot/selfdrive/ui/ui` for an 80% sized window.

We'll review PRs to improve quality on different resolutions, but it's not explicitly a goal for us. We target the comma three screen size for our UI.
