### ISSUE TITLE
Errors when using cantools with openpilot/opendbc/hyundai_kia_generic.dbc

### ISSUE THREAD

**Issue by gsa88** [commaai/openpilot#2427]
When I launch cantools with hyundai_kia_generic.dbc:
```
$ cantools monitor -c can0 hyundai_kia_generic.dbc
```

**Errors occure:** 

- error: DBC: "Invalid syntax at line 1568, column 10: "BO_ 1191 >>!<<4a7MFC: 8 XXX""
- error: DBC: "Invalid syntax at line 1604, column 9: "BO_ 870 >>!<<366_EMS: 8 EMS""
- error: DBC: "Invalid syntax at line 1611, column 9: "BO_ 854 >>!<<356: 8 XXX""
- error: The signals CF_LkasDawStatus and CF_Lkas_Daw_USM are overlapping in message LKAS12.

**Solution:**

- For the first three errors, the solution is to rename the message so that they don't start with numbers.
- For the last error, the position of the bits for the above signals should be changed.

**Comment by adeebshihadeh** [comment]
This sounds like it should be a PR against opendbc.
