### ISSUE TITLE
2021 Hyunda Palisade - Car Alert - Check Forward Collision Avoidance Assist System

### ISSUE THREAD

**Issue by llck80ll** [commaai/openpilot#24316]
### Describe the bug

When Comma 3 is plugged in, whether OpenPilot is engaged or not, the alert keeps coming up. I tried rebooting, unplugging but doesn't seem to correct the issue.

### What hardware does this issue affect?

comma three

### Which car does this affect?

Hyundai Palisade 2021

### Provide a route where the issue occurs

29c3af39bd48a377|2022-04-25--07-52-41--0

### openpilot version

0.8.13

### Additional info

It's been happening for the past 3-4 days or so.

**Comment by sshane** [comment]
Can you connect your device to WiFi to let the logs upload?

**Comment by llck80ll** [comment]
I apologize, you’re right. The device is in the center console since the alert keeps going off. I’ll plug it in inside the house so it connects to Wi-Fi now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by llck80ll** [comment]
Hello, any updates on this car alert? I’m going to try uninstalling and reinstalling OpenPilot.
________________________________

**Comment by llck80ll** [comment]
I still get the alert after doing a factory reset.

**Comment by llck80ll** [comment]
My car is parked in the garage and is connected to Wi-Fi at all times.

Is there a way to manually push the logs?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by llck80ll** [comment]
It is connected to Wi-Fi.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sshane** [comment]
@llck80ll I noticed you haven't driven in a while and I wasn't able to preserve any routes, do you still have this issue?

**Comment by llck80ll** [comment]
Palisades is totaled.

From: Shane Smiskol ***@***.***>
Date: Wednesday, May 10, 2023 at 1:02 AM
To: commaai/openpilot ***@***.***>
Cc: llck80ll ***@***.***>, Mention ***@***.***>
Subject: Re: [commaai/openpilot] 2021 Hyunda Palisade - Car Alert - Check Forward Collision Avoidance Assist System (Issue #24316)

@llck80ll<https://github.com/llck80ll> I noticed you haven't driven in a while and I wasn't able to preserve any routes, do you still have this issue?
