### ISSUE TITLE
replay: fix CarParams write

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24327]
Currently it writes as Event.CarParams, but Python processes expect a CarParams struct

https://github.com/commaai/openpilot/blob/master/selfdrive/ui/replay/replay.cc#L279

**Comment by sshane** [comment]
@arudomanenko want to also try out this issue? If you try to start radard.py with replay you'll see what the issue is.

**Comment by maykonpacheco** [comment]
@sshane I'm trying to solve this problem, could you explain how to run radard.py with replay.

**Comment by sshane** [comment]
Start replay and then run radard.py, replay will stop publishing radarState packets whenever radard starts up, but you'll notice radard crashes on reading the CarParams param

**Comment by maykonpacheco** [comment]
@sshane It seems like a very simple and silly question but this will help a lot of people who are trying to debug openpilot, could you explain and show how to read the CarParams parameter defined by replay?

**Comment by sshane** [comment]
https://github.com/commaai/openpilot/blob/master/selfdrive/controls/radard.py#L187

Basically we need replay.cc to write the parameter in a way that radard will read it correctly.
