### ISSUE TITLE
updated: only fetch current branch

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24351]
A branch with a reference to non-existent submodule commits breaks updated, even if you're not on that branch. This also breaks git on a pc, but a second git pull usually fixes it.

This happens when there are errors like:
```
fatal: remote error: upload-pack: not our ref 49143116e829114d1d909fc53e51330555bd816a
Errors during submodule fetch:
	cereal

```

**Comment by adeebshihadeh** [comment]
This should be fixed once we only pull the current branch.

**Comment by adeebshihadeh** [comment]
Done in #25724
