### ISSUE TITLE
DM not recognizing chinky eyes at night

### ISSUE THREAD

**Issue by tommyluu** [commaai/openpilot#2436]
**Describe the bug**

DM is not working as expected because it is not recognizing that my eyes are in fact open at night. 

This is most likely due to having chinky eyes, and the model is not trained to recognize them. 

**How to reproduce or log data**

I can verify this because the DM will warn that driver is not paying attention just a few seconds into activating OpenPilot, and if I strain to open my eyes wider, then the warning will go away but come right back without wide eyes.

**Expected behavior**

DM should be able to recognize whether eyes are open or closed, whether or not it is day or night.

**Device/Version information:**
 - Device: comma two
 - Dongle ID: 102110287766742152833
 - Route: 06d00785f52b907a
 - Timestamp: When in the route the bug occurs a few seconds after activating the system
 - Version: 0.7.9
 - Car make/model: Honda Civic Hatchback 2017

**Additional context**

This only occurs during the night. DM works just fine during the day. Not sure if it might be camera resolution or weak IR issue and if it can even be rectified. Just received the comma two and have experienced this right out of the box. Right now, I'm using a webcam cover to disable DM at night; not a great solution.

**Comment by ZwX1616** [comment]
the DM model gets better over time with more data. You can help improving it by turning on driver camera uploading.
