### ISSUE TITLE
Enable/Disable Openpilot from controls

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#24382]
Suggest a toggle, such as "Press Cruise Cancel x3 within a second" and that will toggle Openpilot between Dashcam mode and being enabled.

**Comment by adeebshihadeh** [comment]
This sounds like a nice feature for a fork, but this isn't something we're interested in implementing.

**Comment by ns3284** [comment]
Shame. That means while driving, I can't use ACC by itself without turning off the car and disabling Openpilot.
