### ISSUE TITLE
Custom Hardware

### ISSUE THREAD

**Issue by nandrews283** [commaai/openpilot#244]
I currently have a 2012 Honda civic. It does not have LKAS or ACC.  Do you think it would be possible to implement something like XMatik's LaneCruise? I believe I have the knowledge to build all the hardware for it, I'm not sure how to add the software though. 

I was thinking something along the lines of using the entire system outside of the cars CAN Bus system and try to create my own network for all the self-driving parts.  Let me know what you think!

**Comment by ch4se** [comment]
see #old_cars on slack
