### ISSUE TITLE
selfdrive/modeld/modeld.cc: vipc_client_main no frame when running uiview.py on stock master (and webcam)

### ISSUE THREAD

**Issue by zorrobyte** [commaai/openpilot#24405]
### Describe the bug

![image](https://user-images.githubusercontent.com/7257172/166497023-a7efb56f-b4c8-4005-8018-5760d21c4f2e.png)
![image](https://user-images.githubusercontent.com/7257172/166497057-76aa465f-34a0-4579-b372-aecf9c01ca51.png)

Run uiview.py on lastest master, receive console spam `selfdrive/modeld/modeld.cc: vipc_client_main no frame` and corrupted video. This happens with and without webcam compile and launch options.

### OS Version

Ubuntu 20.04

### openpilot version or commit

05f606c8121c89990225ff873c2779fcb3790ead

**Comment by adeebshihadeh** [comment]
This just means modeld is timing out on receiving frames, which will happen if camerad isn't running at a consistent 20Hz. If it's otherwise working, you can ignore it.
