### ISSUE TITLE
Allow rlog/fcamera upload for LTE SIM only

### ISSUE THREAD

**Issue by nickn17** [commaai/openpilot#2445]
I am living in the flat and don't have a "wifi" for my car. But comma2 has inserted LTE SIM card with 300GB net. It's possible to add settings to openpilot menu that allows full LTE uploading?

**Comment by adeebshihadeh** [comment]
We want to minimize the amount of toggles in openpilot, and I don't think this makes the cut. However, it sounds like a nice feature for a fork.
