### ISSUE TITLE
CameraViewWidget assertion failed during replay

### ISSUE THREAD

**Issue by jeroenlammersma** [commaai/openpilot#24487]
### Describe the bug

I am on the master branch, without any modifications.

When I start the demo replay using:
```selfdrive/ui/replay/replay --demo```
and then starting the ui using:
```selfdrive/ui/ui```

The following error occures:
```_ui: selfdrive/ui/qt/widgets/cameraview.cc:243: void CameraViewWidget::vipcConnected(VisionIpcClient *): Assertion `glGetError() == GL_NO_ERROR' failed.
Aborted (core dumped)```

### OS Version

Ubuntu 20,04

### openpilot version or commit

master

**Comment by maykonpacheco** [comment]
@jeroenlammersma Did you follow these steps?
https://github.com/commaai/openpilot/blob/master/tools/README.md

![image](https://user-images.githubusercontent.com/38124066/167754563-28600c4e-75e2-4f25-9874-6124fc5e51b0.png)

**Comment by jeroenlammersma** [comment]
Yes I did. And when I remove the assertion
```assert(glGetError() == GL_NO_ERROR);```
at lines 231, 235 and 260 from https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/widgets/cameraview.cc
and then rebuild, it kinda works, but it seems it won't load the video stream correctly and this is what I get:
![ui without assert](https://user-images.githubusercontent.com/33349469/167811643-f0e71fce-7440-4231-b3a1-06f64764c90c.png)


I also tried the debug ui
```python replay/ui.py```
and that one works without any issues.

**Comment by pd0wm** [comment]
Can you printing the exact openGL using `glGetError`? Are other opengl applications working correctly on your system?

**Comment by khoi** [comment]
https://github.com/commaai/openpilot/pull/24317/files seems to break the build for macOS Silicon as well. I'm also getting `glGetError`

**Comment by jeroenlammersma** [comment]
@pd0wm

When I run
```glxinfo | grep 'version'```

I get:
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.1
    Max compat profile version: 4.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL core profile version string: 4.1 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.10
OpenGL version string: 4.1 (Compatibility Profile) Mesa 21.2.6
OpenGL shading language version string: 4.10
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16```

I have not tested other opengl applications, because I am not sure which applications use it. Do you know a one I can try?

**Comment by pd0wm** [comment]
You can try something like glxgears. What hardware are you using?

The real way to debug this is to add glGetError and see what exact error you're hitting.

**Comment by jeroenlammersma** [comment]
I added that snippet to the code. When executing I receive like a dozen of the following error:
```gl error: 0```

The console:
![image](https://user-images.githubusercontent.com/33349469/167940546-5c709e59-2b61-40b9-bc69-8b832578c1de.png)

I had some issues with the rig running dedicated Ubuntu, but I will have it running tomorrow and will post the results here then.

Thanks anyway already! I hope it is just a VM issue.

**Comment by jeroenlammersma** [comment]
But when thinking about it a bit more ```GL_NO_ERROR``` is ```0``` right?

because in gl3.h GL_NO_ERROR is defined as 0
```#define GL_NO_ERROR                       0```

So the assert should actually not fail right?
I am confused now :)

Ok, I will try on the dedicated Ubuntu machine tomorrow and see how it goes.

**Comment by pd0wm** [comment]
discord.comma.ai is probably faster if you need troubleshooting help (see the #dev-openpilot channel). Feel free to open a new issue if there is an actual bug.

**Comment by jeroenlammersma** [comment]
@pd0wm 
I did some experimenting and I found out you just need adequate hardware for it to run properly. The VM on my laptop just didn't had enough. Thanks for help anyway and will go to discord next time :)

**Comment by pd0wm** [comment]
About the `glGetError()`. I just noticed calling that function clears the error. You need to store it in a variable if you want to check and print it.
