### ISSUE TITLE
About the parameters in function get_compute_gb_acura()

### ISSUE THREAD

**Issue by ecpknpaul** [commaai/openpilot#245]
Hi openpilot team:
      The function get_compute_gb_acura() is in  the file openpilot/selfdrive/car/honda/interface.py, how to calculate those parameters in the function:
```
  def get_compute_gb_acura():
  # generate a function that takes in [desired_accel, current_speed] -> [-1.0, 1.0]
  # where -1.0 is max brake and 1.0 is max gas
  # see debug/dump_accel_from_fiber.py to see how those parameters were generated
  w0 = np.array([[ 1.22056961, -0.39625418,  0.67952657],
                 [ 1.03691769,  0.78210306, -0.41343188]])
  b0 = np.array([ 0.01536703, -0.14335321, -0.26932889])
  w2 = np.array([[-0.59124422,  0.42899439,  0.38660881],
                 [ 0.79973811,  0.13178682,  0.08550351],
                 [-0.15651935, -0.44360259,  0.76910877]])
  b2 = np.array([ 0.15624429,  0.02294923, -0.0341086 ])
  w4 = np.array([[-0.31521443],
                 [-0.38626176],
                 [ 0.52667892]])
  b4 = np.array([-0.02922216])
```
    I can't find debug/dump_accel_from_fiber.py mentioned above. Thanks a lot.

**Comment by pd0wm** [comment]
This was a small neural network that was trained based on some logs. 

Network structure: 
`{"class_name": "Sequential", "config": [{"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "dense_10", "output_dim": 3, "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "input_dtype": "float32", "input_dim": 2, "b_regularizer": null, "W_regularizer": null, "activation": "linear", "batch_input_shape": [null, 2]}}, {"class_name": "LeakyReLU", "config": {"alpha": 0.1, "trainable": true, "name": "leakyrelu_7"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "dense_11", "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "activation": "linear", "output_dim": 3}}, {"class_name": "LeakyReLU", "config": {"alpha": 0.1, "trainable": true, "name": "leakyrelu_8"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "dense_12", "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "activation": "linear", "output_dim": 1}}]}`

dump_accel_from_fiber.py:
```#!/usr/bin/env python
import os
import h5py

weights = h5py.File(os.getenv("HOME")+"/one/models/accel_from_fiber_3_neurons.keras", 'r')

w0 = weights['dense_10']['dense_10_W'][:]
b0 = weights['dense_10']['dense_10_b'][:]
w2 = weights['dense_11']['dense_11_W'][:]
b2 = weights['dense_11']['dense_11_b'][:]
w4 = weights['dense_12']['dense_12_W'][:]
b4 = weights['dense_12']['dense_12_b'][:]

def f(x):
  return repr(x).replace("array", "np.array").replace(", dtype=float32", "")

print "w0 =",f(w0)
print "b0 =",f(b0)
print "w2 =",f(w2)
print "b2 =",f(b2)
print "w4 =",f(w4)
print "b4 =",f(b4)```
