### ISSUE TITLE
athena: requesting the status of a large upload queue causes a disconnect

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24504]
Reported on discord by @incognitojam with an upload queue with 500+ items.

![image](https://user-images.githubusercontent.com/1314752/168085942-50731e91-331c-471a-a1a8-c2057144af30.png)

**Comment by incognitojam** [comment]
I left it on overnight to upload files and to try to reduce the queue size, and now I can see the upload queue contains more than 1,500 items.
