### ISSUE TITLE
web joystick: split axes into separate joysticks

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24512]
Should make it easier to control the body, requested by @briskspirit

**Comment by adeebshihadeh** [comment]
No need for an issue here. It's easy enough to just try it out and see if it's better.

**Comment by sshane** [comment]
Forgot about this, maybe it would be nice to keep these types of issues open so prospective contributors can see it might be wanted. We can also add a low-priority tag for us so we know what is an actual issue, and what is a feature request
