### ISSUE TITLE
Make the time from initial wheel touch alert to making noise longer

### ISSUE THREAD

**Issue by ShaneSmiskol** [commaai/openpilot#2453]
I just took my first drive with 0.7.10 (since 0.7.7) tonight and since I don't have DM at night I use wheel touch. However with the changes to wheel touch timings in this commit https://github.com/commaai/openpilot/commit/21d4ac1eebba06769f03edf7220ce84bd6ae154d I find myself not being able to catch the alert fast enough so that it *doesn't* make noise. If I'm looking straight at the road, as soon as I notice that the alert to touch the wheel has shown, it's just then turning to orange and starts making noise, possibly waking up anyone else in the car (but is also annoying if it's just you).

Is there any way we can either delay this prompt noise, or revert part of that commit to make the time from initial "touch the wheel" alert to making noise alert its original length? It was perfect before, but now makes driving at night much more annoying. Another annoyance is the orange warning alert that makes noise turns on and off repeatedly if the monitoring model is uncertain, since the orange alert resets the `hi_std_alert_enabled` variable, so it's just in a loop until I touch the wheel, even if I'm looking at the road and the model can see me.

That last thing could be solved by a timeout on how quickly it can show the uncertain alert after orange alert is shown.

**Comment by ShaneSmiskol** [comment]
Follow up; if this will not be changed, then I'd at least like to know if we can revert the driver monitoring times to their previous values without risking being banned. After all, they were good enough until the last commit.

**Comment by geohot** [comment]
We can make the green alert appear sooner.

**Comment by geohot** [comment]
Hmm, actually @ZwX1616, can we revert _AWARENESS_PRE_TIME_TILL_TERMINAL and _AWARENESS_PROMPT_TIME_TILL_TERMINAL? I'm not sure why we had to change that.

**Comment by ShaneSmiskol** [comment]
Yeah that sounds about right, I felt like it gave me about 2 seconds before it made noise which wasn't ideal (you end up hearing that warning beep every ~30 seconds or so at night).

**Comment by ShaneSmiskol** [comment]
I'll go out and test the original values/find ones that seem better as well as try to fix that uncertain alert flickering while the orange "touch wheel" alert is on screen and open a PR for that

**Comment by ZwX1616** [comment]
> Hmm, actually @ZwX1616, can we revert _AWARENESS_PRE_TIME_TILL_TERMINAL and _AWARENESS_PROMPT_TIME_TILL_TERMINAL? I'm not sure why we had to change that.
> 
> Or @ShaneSmiskol, without changing _AWARENESS_TIME=35 if you find values for the others two that are better, we'd upstream.

Yeah we can do that. Something in the middle might be better? But yes I am okay with being more strict with the green while allowing more time to react before orange. The driver is expected to hold the wheel in that situation anyways.

**Comment by ShaneSmiskol** [comment]
I went out to get a video of the second issue I described, you can see the uncertain warning keeps triggering since the orange alert keeps resetting it. I actually didn't expect it to disengage here, I thought since it wasn't showing either alert for a few seconds that it saw me and reset the timer but I guess it didn't.

https://streamable.com/xxx7on

**Comment by ShaneSmiskol** [comment]
Have any ideas what can be changed to fix the flickering?

**Comment by DaveyD233** [comment]
Adobe flash player should be discontinued in December, so as a result, we're going to have to make things more adaptable to HTML5 and webm devices or programming :-) just saying

**Comment by naomiplays332** [comment]
what

**Comment by ZwX1616** [comment]
> Have any ideas what can be changed to fix the flickering?

A counter can be added to avoid throwing multiple alerts within a short amount of time, but it's kind of hacky tbh. When it says "Check Driver Visibility", check driver visibility. If driver visibility can't be achieved, vision DM will not work as desired. I would just touch the wheel to reset.

**Comment by ZwX1616** [comment]
That being said, you are welcome to find out a comfortable green/orange balance and submit a PR for that!

**Comment by ShaneSmiskol** [comment]
I don't think not changing behavior is a good solution since it's especially confusing to know what the state of awareness is if it flickers on and off and then goes terminal out of nowhere. It was completely unexpected for me since it seemed like it picked up my face and was happy, but then gave me less than a second to react before disengaging.

I'll make a PR for updating the times though soon, I just need time to experiment
