### ISSUE TITLE
Radarless Honda: enable longitudinal

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24559]
On these cars (2022 Civic), the camera seems to send the ACC messages on address `0x1C8`. Will be called `ACC_CONTROL_2` in `honda_civic_ex_2022_can_generated.dbc`.

Need to find the bits for AEB since the current `ACC_CONTROL` (`0x1DD`) message had those and the DBC definitions for other signals don't look fully correct.

**Comment by kevinharbin** [comment]
Might be here 
https://cabana.comma.ai/?route=f44aa96ace22f34a%7C2022-05-23--16-17-30&seekTime=1&url=https%3A%2F%2Fchffrprivate.azureedge.net%2Fchffrprivate3%2Fv2%2Ff44aa96ace22f34a%2Fcf8616c5c88a4736cea2b14aa073b41b_2022-05-23--16-17-30
![honda civic 2022 AEB](https://user-images.githubusercontent.com/76784413/169914383-a3dec85f-19d3-4e9c-95d7-9022066bdca5.JPG)

**Comment by sshane** [comment]
Done in https://github.com/commaai/openpilot/pull/25364
