### ISSUE TITLE
Does comma three support 2018 Lincoln MKZ Hybrid？

### ISSUE THREAD

**Issue by tornadomeet** [commaai/openpilot#24562]
Hello, does comma three now support ```2018 Lincoln MKZ Hybrid```? i want to purchase comma three, but i found no l```incoln mkz ```support, so how do i choose ```Vehicles``` if w want to purchase. Any suggest? thanks!

@vanillagorillaa

**Comment by alancyau** [comment]
Supported vehicles are found here

https://github.com/commaai/openpilot/blob/master/docs/CARS.md

Lincolns aren't supported.
