### ISSUE TITLE
Enable multiple github accounts to be configured for SSH access through device UI

### ISSUE THREAD

**Issue by JasonJShuler** [commaai/openpilot#24579]
Especially while working on porting a new vehicle, the device owner and the developer both need to SSH into a device. Sometimes multiple developers need access.

This can be accomplished by adding the SSH keys to the config store manually, but this hides the presence of multiple SSH users from the owner.

My suggestion would be to update the GithubUsername and GithubSshKeys parameters to be lists, and update the SSH user UI to support a list of usernames.

I created a second, related enhancement to include an expiration on SSH access: https://github.com/commaai/openpilot/issues/24580 that I would highly recommend be included with this enhancement. Expiration should be added as a new Parameter list.

The lists would be related by list index.

Finally, it might be a good idea to periodically remind the owner to review SSH users when more than one are setup - but this is probably out of scope

**Comment by adeebshihadeh** [comment]
We like to keep our UI pretty simple, but perhaps we'd take a PR that allows entering a full URL in the username box.
