### ISSUE TITLE
Add ability to set an expiration on SSH users

### ISSUE THREAD

**Issue by JasonJShuler** [commaai/openpilot#24580]
This would be especially helpful if https://github.com/commaai/openpilot/issues/24579 (Support for multiple SSH users) is implemented.

Giving SSH access to someone else allows the other person complete control over your device, and at present when you setup an SSH user, the access never expires.

I would suggest including an option when adding an SSH user to setup an expiration. This could be an integer for number of days where 0 is indefinite, or the user could be offered a dropdown with presets, like so Expires: Never, 1 hour, 1 day, 1 week, 1 month, 6 months.
I would recommend storing the setting as a numeric despite how the interface is setup.

When the access expires, an offroad temporary alert should be shown to the owner at the next offroad opportunity.

**Comment by adeebshihadeh** [comment]
Basically same as #24579.
