### ISSUE TITLE
Hi! I got a 2018 Kia Niro Hybrid that has SCC & LKAS.

### ISSUE THREAD

**Issue by Bteekman** [commaai/openpilot#24619]
Hi! I got a 2018 Kia Niro Hybrid that has SCC & LKAS.
Dongle ID: 4e767390477883bd

**UPDATE, as of 11/14/2020 -

Panda Dongle ID: c34bb915cead4fce

Sorry if I provided the wrong information!

_Originally posted by @AshyElbows in https://github.com/commaai/openpilot/discussions/2401#discussioncomment-128793_

**Comment by Bteekman** [comment]
With harnas you Buy for the Kia Niro 2018 hev ?

**Comment by pd0wm** [comment]
The openpilot issue tracker is not for questions.

Please join our discord at dicsord.comma.ai and join the `hyundai-kia-genesis` channel.
