### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#2462]
* limit flickering of DM and engage-ability icons
* <s>remove battery/charging icon for C2</s>, looks bad if we just remove

**Comment by adeebshihadeh** [comment]
@deanlee interested in this one? we probably want a generic filter class in util that we can then use for the DM and steering wheel icons

**Comment by deanlee** [comment]
I'll try.what parameters does this class require?start and stop color? or just alpha?

**Comment by adeebshihadeh** [comment]
The class should be like this python one https://github.com/commaai/openpilot/blob/master/common/filter_simple.py.

**Comment by adeebshihadeh** [comment]
Will be done in the onroad Qt refactor
