### ISSUE TITLE
Add more tests around athena/uploader uploading

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24624]
Currently it's not verified that athena and uploader are actually uploading correct data. Especially now that these services handle bz2 compression for some files this can easily be broken.

**Comment by maykonpacheco** [comment]
I'll do it

**Comment by AlexandreSato** [comment]
i think this will useful to check binary headers and examples of CRC checks in a bz2 file: https://github.com/dsnet/compress/blob/master/doc/bzip2-format.pdf
