### ISSUE TITLE
UI: better lane change alert

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#24638]

**Comment by jozef-simo** [comment]
Initial UI Proposal ([Figma](https://www.figma.com/file/kPvxp4UcTTU9RLLOY7R2b9/openpilot---REDESIGN?node-id=303%3A3))

1 – STATE: "Changing Lanes" :
- VARIANT 1 - icon positioned next to the speed dial
- VARIANT 2 - since Variant 1 layout breaks UI in split-screen Navigation view, the icon in Variant 2 is centered and positioned by screen edges.

Preview:
VARIANT 1
![Variant 1](https://user-images.githubusercontent.com/17929309/170130955-5f0c6017-5acc-44f9-acaa-c6ace938124f.gif)
VARIANT 2
![Variant 2](https://user-images.githubusercontent.com/17929309/170130978-9c7cf444-4bcb-47c2-927b-5530b935bff4.gif)

2 – STATE: "Car Detected in Blindspot" *work in progress 🚧

**Comment by ebranga** [comment]
I think "Blind VARIANT 2" is the best for blind spot.

**Comment by BadOlives** [comment]
Very nice proposal. I too agree with Variant 2 for "Car Detected in Blind Spot".

**Comment by JoneKone** [comment]
Both to variant 2 Although i feel when it's blocked the blinking ball could become larger and the next lane should be all red.

**Comment by ebranga** [comment]
@Achilles308. Changing Lanes variant 2 is when the screen is split into Navigation and Camera Views.

**Comment by jozef-simo** [comment]
Updated UI

State 1: Start Lane Change Once Safe

| Without Text Alert | With Text Alert |
| ------------- | ------------- |
| ![State 1-1](https://user-images.githubusercontent.com/17929309/171759002-a1151056-312b-4de4-9b99-d6919f62d799.jpg) | ![State 1-1 Alert 2](https://user-images.githubusercontent.com/17929309/171759021-d8c5c2af-c413-443c-9caf-9186ce7c72d6.jpg) |

State 2: Car Detected in Blindspot
| Without Text Alert | With Text Alert |
| ------------- | ------------- |
| ![State 2-1](https://user-images.githubusercontent.com/17929309/171759122-89a0c86d-e75e-490c-aade-e2e7f12fad69.jpg) | ![State 2-1 Alert 2](https://user-images.githubusercontent.com/17929309/171759137-a4f9b51f-7308-403f-aa50-8168febeef1e.jpg) |
----

**QUESTION: With/Without text Alert?**
The current UI presents a default openpilot alert. It covers a substantial part of the screen and hides the driving path. however, the benefit of text alert is that it better highlights two points: 
- you (the driver) have to nudge to initiate the lane change
- it's the driver's responsibility to check if it's safe

Including the text alert - does it add contextual value or not? Should we prioritize our user groups differently? Experienced OP driver (might not need a text alert), novice OP driver (text alert might add additional context) in this regard?

**Comment by Achilles308** [comment]
One thing I just realized... aren't there 5 states of lane change?

A) Pre lane change, the turn signal is activated
B) Lane change started and in progress, the wheel was nudged the correct direction indicating the lane is clear and OP starts to initiate the controls to do the lane change
C) Lange change complete, kind of a non step if you just hide the lane change UI elements upon completion

The other states are:
D) Lane change is blocked, the blind spot monitoring or enhanced DM indicated the lane is not clear
E) Invalid lane to change into, no valid lane is seen so no lane change is possible

Some ideas on how to implement something to indicate if you're between A or B as listed above:

When in pre lane change (A), maybe the arrow could be a light gray color and when the lane change is started and in progress (B) it then turns white. When the lane change is blocked (D), the arrow could remain light gray in the red circle of course


I prefer with text but I think I'd propose an additional option of how to implement the text. I think a VERY thin box at the bottom would suffice. Maybe the text height plus padding above and below in the vertical like 5 pixels or something absurdly small. Keep it very sleek for daily use. If a user isn't sure what's going on, the text will offer some clues and clarity. I think no text would work for most frequent users, but sometimes someone not as familiar will drive the car and they should have the opportunity to learn the system by having text feedback. I don't think it's toggle worthy either.

**Comment by samcooler** [comment]
a small note: relying on red/green contrast or low-opacity red overlay for an important safety message is not [colorblind compatible design](https://www.google.com/search?q=red+green+colorblind+design). There should be a shape-based change (or additional symbol) in addition to a color change. Suggestion: the arrow shape could change to an X, or the icon circle shape could change to a larger X. The text overlay is also a decent improvement on the color-change-alone design.

**Comment by jozef-simo** [comment]
UPDATE:
1. State 1/2 - Reduced padding on Alert text. Making it less obstructive for the daily driver.
2. State 2 (Car Detected in Blindspot) - Added car icon as an additional visual clue.

PREVIEW:

| State 1 | State 2 |
| ------------- | ------------- |
| ![State 1](https://user-images.githubusercontent.com/17929309/171968385-c514c1a0-a338-4d13-a6f8-cbeccddf106e.jpg) | ![State 2](https://user-images.githubusercontent.com/17929309/171968391-d714d5e9-466f-465c-9904-30056cb4e533.jpg) |

PREVIEW: State 2 (Car Detected in Blindspot) – Once the adjacent line clears out, the indicator turns green.
![State 2](https://user-images.githubusercontent.com/17929309/171968426-078c4a92-d053-4d11-9a04-f4e40c825271.gif)

**Comment by jozef-simo** [comment]
Following up @Achilles308 
> For Car Detected in Blindspot variant 2, instead of a full path turning red, can it be made so about a car length turns red instead? Would give better spacial indication of roughly where the car blocking the lane change is. In instances where the user is trying to change into a not valid lane, the full path red might be a useful distinction.

Would be nice to see it from behind the wheel (in action).

| State 2 - full path | State 2 - partial path |
| ------------- | ------------- |
| ![State 2](https://user-images.githubusercontent.com/17929309/171969149-eaf609da-bcea-47ab-a181-15bfb7259dba.jpg) | ![State 2-1-1](https://user-images.githubusercontent.com/17929309/171969146-449de5e1-d580-46f4-a979-378a743b4cdf.jpg) |

**Comment by BadOlives** [comment]
> Following up @Achilles308
> 
> > For Car Detected in Blindspot variant 2, instead of a full path turning red, can it be made so about a car length turns red instead? Would give better spacial indication of roughly where the car blocking the lane change is. In instances where the user is trying to change into a not valid lane, the full path red might be a useful distinction.
> 
> Would be nice to see it from behind the wheel (in action).
> 
> State 2 - full path	State 2 - partial path
> ![State 2](https://user-images.githubusercontent.com/17929309/171969149-eaf609da-bcea-47ab-a181-15bfb7259dba.jpg)	![State 2-1-1](https://user-images.githubusercontent.com/17929309/171969146-449de5e1-d580-46f4-a979-378a743b4cdf.jpg)

That looks really good! I'm torn between the full path and partial path as both of them look amazing. Also, great work on the alerts at the bottom. I'd love to see this implemented for all alerts besides lane changes. It looks sleek and doesn't block half the screen.

**Comment by Achilles308** [comment]
@jozef-simo I'm loving the improvements!
 
I think this alert text is a good size, but I'm curious what **bold** would look like with an even narrower padding? Like maybe half that padding even? In my mind, this text is going to be read like 1 in 100 times, so minimal is better. If this is for ALL alerts then maybe it's perfect or could even go bigger if the goal is constancy.

I really like the partial path being red, however, I thought of something else :D   What if it rendered the front bumper, wheel,  and partial hood of a generic looking car in that semi translucent red?

Like the front of something like this...
![screenshot](https://user-images.githubusercontent.com/85138080/172501242-f02065e6-3485-4fe4-b751-d49968b9b19f.png)

**Comment by Achilles308** [comment]
What a terrible way to explain the concept... haha... I finally had time to mock up something better.... here's my concept as listed above about a transparent car front end shape in the lane that's being blocked for lane change.

![image](https://user-images.githubusercontent.com/85138080/179635555-d1c2cae1-358a-4aac-b8db-4d68ad334bd5.png)

**Comment by haraschax** [comment]
Different design that works better when map view is open.

This would be pre-lanechange state:
![Screenshot from 2023-06-28 22-26-43](https://github.com/commaai/openpilot/assets/6804392/3345ab5c-7941-41f5-8b9b-17e0fa2d20ee)

And changing lane state:
![Screenshot from 2023-06-28 22-27-40](https://github.com/commaai/openpilot/assets/6804392/56f574f2-525e-4609-a9fa-a58b4a278564)

@deanlee You want to try implement this?
