### ISSUE TITLE
Hyundai longitudinal: handle button signal changing mid press

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24673]
If you hold the accel or decel button and then quickly switch to the other (which is pretty easy actually), the signal for the buttons in CLU11 never goes to 0, so we never add a button event with `decelCruise` or `accelCruise` not being pressed, thus causing its button timer to increment until it's pressed again. It can cause the set speed to jump by 5 mph all the way down to the minimum or maximum allowed cruise speed the next time you engage with any other button.

Example:

```python
buttonEvents: [<car.capnp:CarState.ButtonEvent builder (pressed = true, type = decelCruise)>]
2.0 0.0 deque([2.0, 2.0, 2.0, 0.0], maxlen=4)
buttonEvents: [<car.capnp:CarState.ButtonEvent builder (pressed = false, type = decelCruise)>]
0.0 2.0 deque([0.0, 0.0, 0.0, 2.0], maxlen=4)
buttonEvents: [<car.capnp:CarState.ButtonEvent builder (pressed = true, type = decelCruise)>]
2.0 4.0 deque([2.0, 2.0, 2.0, 4.0], maxlen=4)
buttonEvents: [<car.capnp:CarState.ButtonEvent builder (pressed = true, type = cancel)>]
4.0 0.0 deque([4.0, 4.0, 4.0, 0.0], maxlen=4)
buttonEvents: [<car.capnp:CarState.ButtonEvent builder (pressed = false, type = cancel)>]
0.0 4.0 deque([0.0, 0.0, 0.0, 4.0], maxlen=4)
```

**Comment by KyleGreenlaw** [comment]
Also happens when you press & hold/quickly press another button (such as distance adjusting button) and go to set the speed.

**Comment by sshane** [comment]
@pd0wm we're trying to remove all the car specific labels and move to using the car label to replace it
