### ISSUE TITLE
Remove WideCameraOnly param

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24689]
VisionIPC should communicate which streams are available when connecting.

**Comment by adeebshihadeh** [comment]
@deanlee want to take care of this one? we just have to add something to VIPC to know which streams are available, then use that in the UI to replace the WideCameraOnly param.

**Comment by deanlee** [comment]
how about keeping the existing interface and only add a static function `getAvailableStreams` to vipc_client?  https://github.com/commaai/cereal/pull/400
