### ISSUE TITLE
0.7.10 lost track of yellow reflector dots used to mark center yellow line

### ISSUE THREAD

**Issue by ErikRNissen** [commaai/openpilot#2469]
**Describe the bug**

first drive on 0.7.10 (stock op).  On a stretch of road i drive frequently OP lost track of the yellow dots used to marke the center double yellow line.  OP then used the white lines on both sides of the road as lane lines and began to cross the double yellow line 

**How to reproduce or log data**

Driving a stretch of road i normally drive

**Expected behavior**

OP deyects the yellow dots and understands them to be a lane line keeping car in the correct lane

**Device/Version information (please complete the following information):**
 - Device: Comma 2
 - Dongle ID: ae3ed0eb20960a20

 - Route: ae3ed0eb20960a20%7C2020-11-01--06-56-46

link:  https://my.comma.ai/useradmin/?onebox=ae3ed0eb20960a20%7C2020-11-01--06-56-46
 - Timestamp: 7:22:49  - steering override about 3min 30 seconds into drive
 - Version: 0.7.10
 - Car make/model: Chevy Volt 2018 

**Additional context**

**Comment by HaraldSchafer** [comment]
Several improvements made in 0.8 should fix this problem
