### ISSUE TITLE
Precise location from ublox raw gnss - using RTK or PPP?

### ISSUE THREAD

**Issue by kozuch** [commaai/openpilot#247]
I found out you started selling the "panda grey" with ublox gnss. I wonder how precise location do you get from this because for a cm level precision you also need data from nearby base station... (say max 20 km away). Do you use the NGS CORS network for RTK post-processing? Or do you use PPP service only?

**Comment by jfrux** [comment]
From my understanding, don't take my word for it... there is no base station piece to this.
Apparently the precision with just the panda grey is good enough for OpenPilot's purposes.

**Comment by kozuch** [comment]
No, you definitely are wrong. Currently there is no HW on the market (at least not in the price range of panda's GNSS receiver) that would allow for a 10 cm positioning precision (which comma.ai claims) without the use of corrections from a nearby base station. This may change in the future but today the situation looks like this.

**Comment by jfrux** [comment]
If you knew the answer then why are you posting this issue?
And if you already knew how OpenPilot is using it, then why post the issue? Are you just trolling?

**Comment by bugsy924** [comment]
It's definitely using base stations for correction. If I recall correctly it was with NASA's or some other government related network. Float RTK is easily done, unsure of fixed as I've only heard from others' experiences

**Comment by kozuch** [comment]
@jfrux 

I am asking for details of their precise positioning solution. This is far from trolling to me...

**Comment by jfrux** [comment]
@kozuch Okay, sorry about that.  Didn't mean to jump to conclusions...
My guess is you might not get an answer on a GitHub issue since this isn't really the place for it.

If you want a real answer, might want to get connected to Comma Slack at https://comma.slack.com/.
Thanks Jan, take it easy.

**Comment by geohot** [comment]
We use a variety of sources on the backend, including CORS. The goal is to recover trajectories with <10cm accuracy in post, build a map, then use the map to localize to <10cm in real time. Of course, everything takes time to build.
