### ISSUE TITLE
Improved update check/download feedback UI & added upload/download indicator and status

### ISSUE THREAD

**Issue by Jon8RFC** [commaai/openpilot#24720]
**Problem:**
The only feedback seemingly given is:

1. "failed to fetch update" (which could mean a myriad of different "no connectivity" scenarios--dns failure, no wifi/cellular connection, no internet connection, github is down, etc--and doesn't necessarily mean "an update exists, but it failed")
2. An eventual "here's the update" screen (long after the process initiated and finished, entirely unbeknown to the user while in progress)
3. No indication of successful check and/or no update, just "last update check" timestamp changing
4. A grayed out "check" button while a download is in progress

When I tap "check" and it is grayed out, I have no idea that 0.8.14 is actually being downloaded/processed, until I leave the screen and come back and can tap "check" again, with the same zero-feedback.  I have no idea if there's significant latency, some problem, or that a download is in progress.

Similarly, "last update check: now" when manually tapping "check" isn't descriptive.  If I were to check my comma3 shipping status or tracking number and the only feedback options were "404", "checked" (not "awaiting shipment", "shipped", "tracking number xyz", etc...only "checked"), and "delivered", that wouldn't be helpful.  Or, a perpetual "checking..." screen which is analogous to the grayed out "check" button and the 0.8.14 update being downloaded and background processes in action.

There's no way to know that any uploads/downloads are in progress.

**Request:**
The manual "check" button should have better feedback of what's going on and what went on.
Just slightly more specific errors, like "no internet connection" or "github/whatever unresponsive" or "download failed" (maybe internet is lost mid-download?).
Show that an update was found and is being downloaded/processed.
Show that a successful, manual update check occurred, like the button changing to "No updates".

There should also be an at-a-glance indication, without digging through menus, that uploads/downloads are in progress, even in the background.
From the at-a-glance indication, a quick and easy means to tap and view specifics of the uploads/downloads.  For instance, if I'm sitting in my car after the engine is off, I should be able to see that uploads are in progress.  And from there, tap to see details like "2/524" or "2/3", and I can watch a progress bar for the current upload so that I can decide if I want to take it inside for faster uploading, depending on the situation of uploads, upload speed, and time until the comma3 will probably shut off.

**Comment by adeebshihadeh** [comment]
A really nice updater UI is on the list for new designs. New design is rolling out incrementally (see #24638).  Closing this since we're tacking the new design project internally.
