### ISSUE TITLE
new max speed & speed limits design

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#24735]
Updated Variant 2 based on today's call – [Figma](https://www.figma.com/file/kPvxp4UcTTU9RLLOY7R2b9/openpilot?node-id=367%3A2058)
- MAX
  - updated layout
  - engaged: updated color on "MAX" word (V1 green seems to fit better)
- Speed Limit
  - US
  - EU - enclosing box - bottom right & left have full corner radius for better visual appeal

**Needs decision:** Going over Speed Limit
- Going +10 over speed limit → Max turns orange 🟠
- Going +20 over speed limit → Max turns red 🔴

+10/+20 limits are good enough, or should be made lower? For instance +5/+15?

------

PREVIEW:

![Speed Limit - Preview](https://user-images.githubusercontent.com/17929309/171731258-fe2119b0-b479-4c0d-a860-2f6c37f8a9b5.jpg)

![Speed Limit - States](https://user-images.githubusercontent.com/17929309/171731037-09844976-536e-4f2d-b5da-060b65831723.jpg)

_Originally posted by @jozef-simo in https://github.com/commaai/openpilot/issues/24681#issuecomment-1145306572_

**Comment by ClockeNessMnstr** [comment]
> @jozef-simo What do you want to display if there is no set speed yet? We used to display N/A, but that doesn't quite fit and never thought it looked very good.

"--" is a familiar option from oem systems with set speed or speed limit indicators that don't hide when not available. 
Not sure how prevalent that is actually but.

**Comment by KyleGreenlaw** [comment]
Instead of a hard switch at +10/+20 from white->orange->red, maybe change colour in a soft manner when accelerating/decelerating to those speeds .. I feel like it'll be more subtle and less abrupt.

**Comment by jozef-simo** [comment]
Great idea! @KyleGreenlaw 
> Instead of a hard switch at +10/+20 from white->orange->red, maybe change colour in a soft manner when accelerating/decelerating to those speeds .. I feel like it'll be more subtle and less abrupt.

PREVIEW:
![PREVIEW](https://user-images.githubusercontent.com/17929309/171970745-18ae39b5-968d-4822-b4c5-db400f21a743.jpg)

**Comment by maykonpacheco** [comment]
![COLOR TRANSITION PREVIEW](https://user-images.githubusercontent.com/38124066/172292583-fdb6ef16-592b-46c8-83ff-43c4d478522f.jpg)
