### ISSUE TITLE
2021 Mirai - Braking Delay - Lots of Hard Braking in Traffic

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#24746]
### Discussed in https://github.com/commaai/openpilot/discussions/24743

<div type='discussions-op-text'>

<sup>Originally posted by **BruinBears** June  3, 2022</sup>
Have a pretty long commute through LA traffic and I've noticed there is a pretty large delay, maybe around 1 second, between when the car in front brakes and openpilot starts braking.

Most cases I end up taking over the brakes to avoid openpilot hitting the brakes hard.

Happened a few times on this drive:
390a85b0f0d7a93b|2022-06-01--08-09-03
9, 25, 32, 46</div>

**Comment by adeebshihadeh** [comment]
Duplicate of #2731?

**Comment by HaraldSchafer** [comment]
Yes likely, linked.
