### ISSUE TITLE
After First update Comma Two V0.7.9 Stoped Working Two massages 1.Key chain has stopped 2. Keyboard AOSP has stopped My Comma 2 is useless now . Could not factory reset, nothing works , same massage coming back !

### ISSUE THREAD

**Issue by GBenke** [commaai/openpilot#2474]
**Describe the bug**

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [e.g. EON/EON Gold/comma two]
 - Dongle ID: [e.g. 77611a1fac303767, can be found in Settings -> Device -> Dongle ID or my.comma.ai/useradmin]
 - Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
 - Timestamp: [When in the route the bug occurs (e.g. 4min 30s into the drive)]
 - Version: [commit hash when on a non-release branch, or version number when on devel or release2 (e.g. 0.7.6)]
 - Car make/model: [e.g. Toyota Prius 2016]

**Additional context**

**Comment by VirtuallyChris** [comment]
Please reflash NEOS using this guide. https://github.com/commaai/eon-neos#restoring-on-linuxos-x If the issue still persists, email support@comma.ai

**Comment by skyej944** [comment]
File "flash.sh", line 8
    if [ ! -f $FASTBOOT ]; then
         ^
SyntaxError: invalid syntax

**Comment by skyej944** [comment]
This is what I get when running flash.sh
