### ISSUE TITLE
2020 Highlander Hybrid Camma2 no longer working after recall software update by Toyota 

### ISSUE THREAD

**Issue by howardlan3** [commaai/openpilot#24754]
### Describe the bug

My comma 2 has been working fine for past year. There is a recall from Toyota "A software error can cause the Vehicle Stability Control system (VSC) not to default to "on" the next time the car is started under certain circumstances. This can result in noncompliance with a federal safety requirement." NHTSA Recall No 22V-239.  I had Toyota perform the recall (software update) last week and my Comma 2 no longer works. It says unrecognized car, dashcam mode only. I reinstalled the software just now, and I was hopeful when it asked me to drive above 15mph for calibration. After calibration, it still said unrecognized car, dashcam mode only. This recall effects 2020-2022 Highlander Hybrid. 2021-2022 Mirai. 2021-2022 Rav4 prime. 2022 Rav4 Hybrid. 2021-2022 Sienna Hybrid. 2021-2022 Venza Hybrid. 

Please help!

### Which car does this affect?

2020 Highlander Hybrid 

### Provide a route where the issue occurs

e6e870e046704048|2022-06-03--21-17-43--0

### openpilot version

0.8.13

**Comment by sshane** [comment]
Your missing fingerprint was added in this PR: https://github.com/commaai/openpilot/pull/24289. Since you're using a C2, you'll have to cherry-pick that into any branch you use
