### ISSUE TITLE
Honda Civic: fix blocking LKAS messages

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24750]
cfb32f0fb91b173b|2022-06-03--15-08-55--11

**Comment by adeebshihadeh** [comment]
Can you make the issue title more speciifc or add a small description? The Honda safety has very limited TX checks since the EPS limits are already quite strict. This segment also doesn't have any blocked messages.

**Comment by sshane** [comment]
Are you sure?We block `STEERING_CONTROL` and `BRAKE_COMMAND`.
![Screenshot from 2022-06-06 14-31-03](https://user-images.githubusercontent.com/25857203/172252732-065904bd-186d-458f-975e-474a633b913b.png)

**Comment by sshane** [comment]
Looks like neither blocked msg caused the dash fault
