### ISSUE TITLE
Honda: fix requested torque oscillation

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24751]
PI gains are too high and without any rate limits the request we send to the car oscillates pretty badly

cfb32f0fb91b173b|2022-06-03--15-08-55--11

![Screenshot from 2022-06-03 17-56-45](https://user-images.githubusercontent.com/25857203/171970350-bb812293-714f-459b-828d-d8b245eaecc3.png)

Or tune this car properly

**Comment by sshane** [comment]
Assigned Harald as a proper tune would also fix this more correctly

**Comment by HaraldSchafer** [comment]
Should be improved with https://github.com/commaai/openpilot/commit/e58f6fbc11424e8059d6a86a4f0990f604c3a22f
