### ISSUE TITLE
Cruise Fault w/ Openpilot Long Toggle ON

### ISSUE THREAD

**Issue by tecandrew** [commaai/openpilot#24758]
### Describe the bug

cruise fault occurs when OP long toggle is on. 

### Which car does this affect?

Hyundai Elantra Hybrid 2021

### Provide a route where the issue occurs

eb5a50f9e98f50b9|2022-06-03--22-09-19

### openpilot version

0.8.14 release3

### Additional info

[Another user claim they see the same issue](https://discord.com/channels/469524606043160576/524611978208215070/982579451281956905) on Kia Niro EV

**Comment by adeebshihadeh** [comment]
The Hyundai long safety isn’t included in release3. You’ll need to run a non release branch, e.g. master or devel for Hyundai long.

**Comment by tecandrew** [comment]
thanks for the info, I had no idea about this. I believe I ran 0.8.13 w/ OP long for a bit w no fault, so I think OP long would work in this release.
