### ISSUE TITLE
Panda - Rust implementation

### ISSUE THREAD

**Issue by jwinarske** [commaai/openpilot#24773]
Any interest in a Rust implementation of the Panda firmware?

**Comment by GregorKikelj** [comment]
This sound more for https://github.com/commaai/panda/issues. In any case if you really want to use Rust with a Panda try https://github.com/pd0wm/pandacan-rs

**Comment by adeebshihadeh** [comment]
Thank, but not interested.

**Comment by jwinarske** [comment]
@GregorKikelj That's for the host side.  I'll post in panda repo thanks.

**Comment by geohot** [comment]
Again, why do this? A new codebase would have a new set of bugs. I also see very few places where the C code is holding us back. While these things would be fun projects, we are a company with a mission, and supporting the migration of the panda firmware to Rust is not where we should be spending our time.

**Comment by jwinarske** [comment]
@geohot I work at Toyota (ex-QC 10yrs) and was reaching out to see if there was any interest, not looking for engineering support.

**Comment by geohot** [comment]
I mean, you are obviously welcome to rewrite panda in rust, it's MIT. I'm just saying it's unlikely we'll upstream it.

**Comment by ycllz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已收到
