### ISSUE TITLE
ui: unable to scroll on 'Regulatory' page

### ISSUE THREAD

**Issue by CruelSenpai** [commaai/openpilot#24808]
### Describe the bug

When selecting the VIEW button on the Regulatory option in Settings, user is unable to scroll down to see additional information. This has been a persistent bug for a few versions of OP on the C3 now.

### Provide a route where the issue occurs

No route

### openpilot version

0.8.15 master

**Comment by BadOlives** [comment]
Referencing issue #24800 as this might go along with this issue.

**Comment by Achilles308** [comment]
@pd0wm The scrolling on the terms and conditions page when onboarding works great... you have to scroll all the way down for the accept button to be activated though. Here is the part calling the tc.html page
https://github.com/commaai/openpilot/blob/cb8885cffb313bea258c012c3026461a22bf8135/selfdrive/ui/qt/offroad/onboarding.cc#L91

and the terms and conditions are located here https://github.com/commaai/openpilot/blob/cb8885cffb313bea258c012c3026461a22bf8135/selfdrive/assets/offroad/tc.html#L1

Might help to see a working scroll for the html display... seems to be rarely used.

**Comment by adeebshihadeh** [comment]
@deanlee want to take a look at this one?

**Comment by deanlee** [comment]
I'll check in it.
