### ISSUE TITLE
Show bus dropout for radar bus

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#24828]
This user's 2022 Highlander Hybrid has no radar points, thus radard never sends radar packets, and radard doesn't automatically switch to VOACC, causing openpilot to ignore leads: 2aaed1ef9648b871

Unclear if this should be handled in radard or controlsd, but think this is a good idea still.

**Comment by sshane** [comment]
Also this guy's RAV4 had a bad cable, somehow causing PCS faults, but also, bus 1 was largely missing. https://github.com/commaai/openpilot/pull/25136

**Comment by adeebshihadeh** [comment]
#25179 will show the radar fault alert
