### ISSUE TITLE
OpenPilot Fails to Stop for Stationary Lead Car on Torch-Model

### ISSUE THREAD

**Issue by C0mpl3t3N00b** [commaai/openpilot#2484]
**Describe the bug**

I was following a lead car that was moving and then stopped, but OpenPilot with Torch-Model was not able to stop for the lead car.

**How to reproduce or log data**

Lead car was being followed from a stop, lead car began moving with traffic, OpenPilot began moving with lead car, lead car brakes to a stop, OpenPilot did not stop with lead car.

**Expected behavior**

When the lead car comes to a stop, OpenPilot should also stop at a safe distance from the lead car.

**Device/Version information (please complete the following information):**
 - Device: Comma Two
 - Dongle ID: bdad50b8a1f9fa8e
 - Route:bdad50b8a1f9fa8e|2020-11-02--14-41-38--2
 - Timestamp: 14:44:17
 - Version: master-ci (torch-model "injected") 
 - Car make/model: 2020 Toyota Rav4 Hybrid LE

**Additional context**

Was running Torch-Model on master-ci built.

https://my.comma.ai/cabana/?route=bdad50b8a1f9fa8e%7C2020-11-02--14-41-38&exp=1636055623&sig=oF%2FdN7LFePbKG%2BOf6ACrUf%2FaaKtcfHomnxg2tplKMKE%3D&max=17&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fbdad50b8a1f9fa8e%2Ff1f5e1146b245aa61290f5dfef5f8908_2020-11-02--14-41-38

**Comment by HaraldSchafer** [comment]
Closed because it is about a branch.
