### ISSUE TITLE
Des it support Honda Freed 2016 ?

### ISSUE THREAD

**Issue by SINO4006** [commaai/openpilot#24896]
My car have acc and LKAS 

thanks!

**Comment by adeebshihadeh** [comment]
Only the 2020 model has been tested, but looks like the 2016 is the same generation, so it should work.

**Comment by SINO4006** [comment]
Does it support Low speed acc and LKAS? My car acc don’t work under 25km/h and the LKAS don’t work below 65km/h

**Comment by SunDuke1** [comment]
Not entirely clear, Comma three is basically useless for the 2020 Honda Freed when used in the city and at low speeds?  Where can I read the protocol or see the test video of the Honda Freed Openpilot?
