### ISSUE TITLE
Fix controlsMismatches from 0.8.14-release

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#24944]
```
HONDA ODYSSEY 2018                       0c23034a3a1e7bf4|2022-06-18--19-12-39--17
NISSAN ALTIMA 2020                       78daf6341d75cffb|2022-06-17--09-42-14--2
NISSAN ALTIMA 2020                       78daf6341d75cffb|2022-06-17--09-42-14--3
NISSAN ALTIMA 2020                       78daf6341d75cffb|2022-06-17--10-14-12--3
NISSAN ALTIMA 2020                       78daf6341d75cffb|2022-06-23--11-51-47--2
NISSAN ALTIMA 2020                       78daf6341d75cffb|2022-07-09--20-30-55--1
HONDA CIVIC (BOSCH) 2019                 a18f93cc836f33e4|2022-06-10--16-15-02--39
HONDA CIVIC (BOSCH) 2019                 a18f93cc836f33e4|2022-06-11--06-48-31--4
HONDA CIVIC (BOSCH) 2019                 a18f93cc836f33e4|2022-06-13--09-58-04--0
HONDA CR-V 2017                          c390b60ad96d2ff2|2022-07-01--07-40-21--4
HONDA CIVIC 2016                         ffa76986ec8e871e|2022-06-21--17-18-20--5
HONDA CIVIC 2016                         ffa76986ec8e871e|2022-07-06--16-55-12--4
```

- [x] HONDA ODYSSEY 2018 https://github.com/commaai/panda/pull/988
- [x] HONDA CIVIC 2016 https://github.com/commaai/panda/pull/988
- [ ] NISSAN ALTIMA 2020 https://github.com/commaai/openpilot/issues/25166
- [ ] HONDA CIVIC (BOSCH) 2019 (no rlogs)
- [ ] HONDA CR-V 2017 https://github.com/commaai/openpilot/issues/25160

**Comment by sshane** [comment]
All Nissans routes seem to be fixed on latest panda master: https://imgur.com/a/NpG14cg

**Comment by adeebshihadeh** [comment]
The Nissan appears to be hitting the lag detection in panda somehow. `controls_allowed` is never high for more than two pandaStates frames, and the lag detector runs at 1Hz. We'll need to add some more logging to see what's going on there.
