### ISSUE TITLE
Code version and simulation

### ISSUE THREAD

**Issue by L-Net-1992** [commaai/openpilot#24974]
### Describe the bug

I want to download the code of version 0.8.12, but I find that there are no simulation tools in the tools folder. Do you have any instructions about the simulation of version 0.8.12. thank you!

### OS Version

Ubuntu20.04

### openpilot version or commit

0.8.12

**Comment by pd0wm** [comment]
This is the last commit from 0.8.12: https://github.com/commaai/openpilot/tree/57871c99031cf597ffa0d819057ac1401e129f32
