### ISSUE TITLE
Toyota: Potential EPS belt wear out

### ISSUE THREAD

**Issue by Smartype** [commaai/openpilot#25004]
### Describe the bug

This is a Toyota Avalon 2018 hybrid car. With stock LDA and low speed limit ACC.   The mileage is about 40000km. installed  openpilot for about one year.  When take apart the EPS motor from the steering rack, found that the belt wore out. The motor gear  wore out too. 
![CAF042D3-AB3F-4785-B642-D1070E6CFF30](https://user-images.githubusercontent.com/64790/176659995-991dbf7b-7b0f-4476-a202-d7cb06c967dc.jpeg)

The motor above is from the car mentioned above. Then motor below is from another Avalon has a mileage of 80000km, without openpilot. 

![DD5C3864-3B03-4257-9B8C-F0D2C80E83FA](https://user-images.githubusercontent.com/64790/176659915-9fbf42e7-48d1-4623-967e-cb55a615a349.jpeg)

Picture of the steering rack EPS belt. 

### Which car does this affect?

Toyota Avalon 2019 Chinese

### Provide a route where the issue occurs

Not available

### openpilot version

0.8.7

**Comment by Smartype** [comment]
The car own bought a new Avalon 291 steering rack (with tss 2.x support, lta). And he said the mechanical struct/belt is the same.

**Comment by zorrobyte** [comment]
@Smartype It makes sense, the car was not designed for constant steering. I'd consider this a wear item if using OP on this model moving forward. Although it would be nice for comma to add a note to the vehicle list, I doubt they would.

Good find!

**Comment by Smartype** [comment]
> @Smartype It makes sense, the car was not designed for constant steering. I'd consider this a wear item if using OP on this model moving forward. Although it would be nice for comma to add a note to the vehicle list, I doubt they would.
> 
> 
> 
> Good find! Makes me wonder if this would have happened to the Rav if I would have kept it.

The new Avalon 2021 has LTA support. (I guess it is supposed to do steering whenever possible, am I right?) 

And it has the same steering rack.(maybe with a different FW)

**Comment by jyoung8607** [comment]
> @Smartype It makes sense, the car was not designed for constant steering. I'd consider this a wear item if using OP on this model moving forward. Although it would be nice for comma to add a note to the vehicle list, I doubt they would.

Important parts of those pictures are blurry, but I don't see how a neoprene-fiberglass or urethane-polyester belt wipes out a metal gear like that, especially without showing severe wear, which it doesn't. We see the belt has lost some chunks, but the parts we can see of the belt are basically there. What's been lost are a few relatively meaty chunks from some sort of sudden trauma, not a gradual fine deposit of powder-like belt material like you'd see from wear over time. Maybe some metallic FOD got loose in there and went dancing around?

**Comment by geohot** [comment]
@zorrobyte If I see more stuff like "Although it would be nice for comma to add a note to the vehicle list, I doubt they would.", you'll be banned from our github. If there's a real issue pertaining to a model of car, we'd be happy to note that after we have real evidence. Assuming bad faith = ban.

Now, I can't see why this would affect specifically the Avalon, or have anything to do with openpilot at all. The EPS motor is constantly applying torque to the wheel when the human is steering also. I would guess that something else happened to the Avalon, the main issue with a sample size of 1.

**Comment by pd0wm** [comment]
@Smartype how did you notice this issue? Did this user loose power steering, or get some form of warning/DTC?

**Comment by Smartype** [comment]
> @Smartype how did you notice this issue? Did this user loose power steering, or get some form of warning/DTC?

The car owner was trying to upgrade to tss 2.5. So he has lots of parts to be replaced. EPS motor is one of then. He accidentally found this issue.

**Comment by adeebshihadeh** [comment]
I'm going to close this. There's nothing substantive for us to look into here beyond "here's a blurry picture of a failed EPS driven by openpilot, and look at this perfect one without openpilot." Feel free to open a new one if anything ends up pointing to openpilot.
