### ISSUE TITLE
Hardware accelerated frame decode on comma three

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#25006]
This is probably best done as an ffmpeg extension that we can eventually include in AGNOS. The first use will be to make the [model replay test](https://github.com/commaai/openpilot/blob/c49f997be505760a18e85a241e6d45b98952c894/Jenkinsfile#L155) fast. The [V4LEncoder](https://github.com/commaai/openpilot/blob/master/selfdrive/loggerd/encoder/v4l_encoder.cc) has the encode side of this.

@deanlee interested in this one?

**Comment by deanlee** [comment]
WIP
