### ISSUE TITLE
Carla sim "Openpilot unavailable Communication issue between processes"

### ISSUE THREAD

**Issue by Saumya-Shah** [commaai/openpilot#2501]
I have ubuntu 18.04 and have run the two given scripts for running openpilot with Carla. I get a warning saying "Grey Panda is deprecated" followed by  "Openpilot unavailable Communication issue between processes" when I engage by pressing 1 on the terminal.
Operating system: [e.g. Ubuntu 18.04]

**Comment by dorkmo** [comment]
theres currently a hack to remove it in controllerd

https://github.com/commaai/openpilot/wiki/CARLA#communication-issue-between-processes

join the discord server and check out channel #openpilot-simulation  a few people have had the same issue

**Comment by Saumya-Shah** [comment]
Did you mean controlsd.py file? I removed the lines corresponding to radar commissue and commissue events in lines 210-214. That doesn't seem to fix it though, can you help? I have joined discord server but don't see more description regarding this over there. Thanks a lot. 

![Screenshot from 2020-11-07 21-27-08](https://user-images.githubusercontent.com/22060625/98455550-2e19d300-2140-11eb-9deb-454dfce0791d.png)

**Comment by dorkmo** [comment]
sorry im not sure, davidtena98 most recently experienced it.  They start talking about it here... https://discord.com/channels/469524606043160576/684457101455786017/774270397243326474

**Comment by LoganxDev** [comment]
#2528

**Comment by Saumya-Shah** [comment]
Hi, thank you for the reply. Unfortunately, I still have the issue. The am running it as follows:

`sudo ./tools/sim/start_carla.sh`

Then in other terminal:
`sudo ./tools/sim/start_openpilot_docker.sh `

And then I change the following inside the docker container:

In bridge.py: I changed hwType from "greyPanda" to "blackPanda" as in  #2528 and 
I also comment the issue lines in controlsd.py as shown in the screenshot above. 

And then I rerun the bridge.py. 

Did I miss something?

**Comment by LoganxDev** [comment]
It sounds like you didn't kill and restart openpilot. Looking at your screen shot if you go into the right hand terminal window then go to the first tmux window with ```` ` + 0 ````, then `ctrl + c` to kill openpilot. Make your edits then run `./launch_openpilot.sh`, finally you can swap back to the tmux window you started in with ```` ` + 1```` and rerun `bridge.py`. These steps are performing `tmux_script.sh` which is what `start_openpilot_docker.sh` is doing inside the docker container.

**Comment by gucasbrg** [comment]
changed hwType from "greyPanda" to "blackPanda" as in #2528,
also wrong config
![Screenshot from 2020-11-15 18-12-23](https://user-images.githubusercontent.com/3182658/99182534-689ef380-2770-11eb-8223-80f5256d51a1.png)

**Comment by gucasbrg** [comment]
There are three interesting tips to improve

- The greypanda written in bridge.py caused thermald started false. Then, as soon as the manager was opened, all services were killed.
- When sim is used, all service alives are also monitored, and then there is even a frontframe, which is nothing. . .
- That is, when onnx is running on the cpu, the fps prediction is very low, and then the prompt is not very friendly

**Comment by DanielYEHsieh** [comment]
Hi @adeebshihadeh,

thanks for replying.

I did the same change in
https://user-images.githubusercontent.com/22060625/98455550-2e19d300-2140-11eb-9deb-454dfce0791d.png
but it seems not fixed the issue,

and in bridge.py: is already changed from "greyPanda" to "blackPanda"
but it still runs into the same issue.

kill and restart openpilot did not help too.

Is the fix in discord?

Thanks!
