### ISSUE TITLE
Command injection in juggle.py

### ISSUE THREAD

**Issue by firmianay** [commaai/openpilot#25022]
### Describe the bug

hi, great project!

In `tools/plotjuggler/juggle.py` I found that the parameter layout is directly spliced into the command and executed, which may cause the command injection vulnerability, and when the file is executed with root privileges, it may lead to privilege escalation.

```py
def start_juggler(fn=None, dbc=None, layout=None):
  env = os.environ.copy()
  env["BASEDIR"] = BASEDIR
  env["PATH"] = f"{INSTALL_DIR}:{os.getenv('PATH', '')}"
  if dbc:
    env["DBC_NAME"] = dbc

  extra_args = ""
  if fn is not None:
    extra_args += f" -d {fn}"
  if layout is not None:
    extra_args += f" -l {layout}"

  cmd = f'{PLOTJUGGLER_BIN} --plugin_folders {INSTALL_DIR}{extra_args}'
  subprocess.call(cmd, shell=True, env=env, cwd=juggle_dir)
```
```py
  parser.add_argument("--layout", nargs='?', help="Run PlotJuggler with a pre-defined layout")
```

### Provide a route where the issue occurs

None

### openpilot version

latest

**Comment by pd0wm** [comment]
This is a debug tool, so this not a concern.
