### ISSUE TITLE
ensure updated doesn't crash on stripped release/master-ci builds

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#25047]
A missing file in `files_common` broke updated on master-ci, without any test catching this.

**Comment by pd0wm** [comment]
@adeebshihadeh looks like we already have a test for this, but updated is excluded explicityly: https://github.com/commaai/openpilot/blob/master/selfdrive/manager/test/test_manager.py#L15

Is this due to the overlay lock? In that case we should just ensure the test is started in a clean state so we can test updated too.

**Comment by adeebshihadeh** [comment]
Fixed in e8c8bd902d6c21173e4067b348e2762e5aefc4ab
