### ISSUE TITLE
pre-commit run --all fails on macOS

### ISSUE THREAD

**Issue by oskarkocol** [commaai/openpilot#25055]
## Problem
Running `pre-commit run --all` on `master` on Mac returns mypy errors. All the errors seem to relate to functions  from the `os` module that provide interface to the scheduler (e.g. `getxattr`).
Terminal output:
```
selfdrive/loggerd/xattr_cache.py:11: error: Module has no attribute "getxattr"
selfdrive/loggerd/xattr_cache.py:23: error: Returning Any from function declared to return "None"
selfdrive/loggerd/xattr_cache.py:23: error: Module has no attribute "setxattr"
common/realtime.py:39: error: Module has no attribute "sched_setaffinity"
selfdrive/loggerd/tools/mark_unuploaded.py:8: error: Module has no attribute "removexattr"
selfdrive/loggerd/tools/mark_all_uploaded.py:8: error: Module has no attribute "setxattr"
```

## How to reproduce
Run `pre-commit run --all` in the `openpilot` folder.

## Possible cause
This PR https://github.com/commaai/openpilot/pull/24448 replaced custom `xattr` implementation with one from the `os` package. According to the documentation, the scheduler functions from the `os` package are only available on "some Unix platforms" (https://docs.python.org/3/library/os.html#interface-to-the-scheduler). It would make sense that `xattr` fro the `os` package is not available for MacOS

## Possible solution
What do you think about allowing to run local tests in a dockerized environment? I had some experience with https://github.com/nektos/act which allows running Github Actions workflows locally, using Docker. Adding this would forever end the problem of OS compatibility, at least in the universe of tests.

### OS Version

macOS Big Sur 11.6.1 (20G224)

**Comment by pd0wm** [comment]
Part of the problem here is that we have `--warn-unused-ignores` enabled. For MacOS it's fine to ignore these errors, but on linux that would be an unused ignore and generate an error again.

**Comment by adeebshihadeh** [comment]
Since pre-commit doesn't allow conditional skipping of just the mypy stage, I just disabled pre-commit install on mac (https://github.com/commaai/openpilot/commit/28d0459c69a6f9bcf511fe982ba573cb7842e385) until our mac support is in better shape.
