### ISSUE TITLE
Calibration drop down gone

### ISSUE THREAD

**Issue by ifixaudio22** [commaai/openpilot#25069]
### Describe the bug

Calibration drop down that displays R/L up/down values is gone on latest stock master-ci

### Provide a route where the issue occurs

832d14f92ad84eb6 Dongle id

### openpilot version

0.8.15 master-ci

### Additional info

17 Toyota Highlander SDSU Pedal

**Comment by adeebshihadeh** [comment]
Thanks for reporting! Fixed in ff3f6de149475ce995c21f8308da0bbc08922c54
