### ISSUE TITLE
Failed dependencies installation on M1 Air

### ISSUE THREAD

**Issue by tomtom-95** [commaai/openpilot#25070]
### Describe the bug

Try to follow the openpilot tools readme to build openpilot. I run tools/mac_setup.sh but the installation fails with this message:

Ignoring carla: markers 'platform_system != "Darwin"' don't match your environment
An error occurred while installing ft4222==1.4.1 --hash=sha256:9369b55393b2e1f58f8b8516bcf9cd6fd34c05e77377c4cc48be39a49cad7be5 --hash=sha256:800a26a4a8fc854f41e4de41e45b6deafdeb78ae5eff48818f710bb2d94a8c11 --hash=sha256:ec984bd7e9300e5f2e50823dcd5874d54aa3e7503e69afe7eb3b4cea77071084 --hash=sha256:8790e96b4c3f8d1fb768f689f1c437a59b20889e4726ed7457ff3d188f0a3274 --hash=sha256:d479c037b417ff289727112f1d4725563b78448d3765f457c8bf6884e4d83abd --hash=sha256:4b7e4c8b5e4a8fe769127d3db99b7b410468ffe2718a07f7b317e7dc1ad9ca4f --hash=sha256:cc368b06b92529a11add37d14196d2e2aaae19c6ffc51b9457513a0d05ceae1a --hash=sha256:eadcbc1dd20ed6d7d07dc53354ea137bcea30fb0889d74bedcd189cdb4f61c84 --hash=sha256:372be3d7d04c0f6dfa62ff66b3d4be5c39d57c258ab562d9eb0d7cdd3a90ed0f --hash=sha256:422740efac86f3fdd971bb9a94d9974e56cfe062284a2be1a85db96dd0e77e5e --hash=sha256:68e6b357ea2287fe0e8dac287efbac2f0ce9632d65e828d422d3a0604555c174 --hash=sha256:4414ef82a6321c5205ab0e3dab2bf072f14b4dd3262e5f392560adf107210d41 --hash=sha256:b7f58cd16213a5c92503c530b301f071d67283c80c1e8cb43d6f3ec5c186df35 --hash=sha256:a6236f05b8948cd9c113c7159e3fdde202a0f73dce6440da078fd2fc9e411123 --hash=sha256:1f9be0961bd7f3e0c1729c9692f602244e93898610611602ce1fa16059ac5bfa --hash=sha256:459894dcca7db71a0d58e6f3abb4c9dd67654c92ad9d934f1e32dc08bed87645 --hash=sha256:1c71913f9fb862634fb77eb6efeea38b2b839e09f739aee5864b9549bcf1c4a9 --hash=sha256:1489b08e4042cb2b24894495c1c8514fa115122e9f8a739f665f0e4d8c53d3f4 --hash=sha256:dce00d513be811f738954c5593c52b533a02331e8a26983280dea3f4d864962f --hash=sha256:3ebf9380315c6af8f9f3bc5c5c7a5ae06498349c14a7b2e65d5067b20462d21b --hash=sha256:208cde748fc2bf4a753e217ee2844e75d7d1b6d370a8937a2055f9de8906f933! Will try again.
Ignoring casadi: markers 'platform_system != "Darwin"' don't match your environment
Ignoring onnxruntime-gpu: markers 'platform_system != "Darwin"' don't match your environment
An error occurred while installing pyqt5==5.15.4 --hash=sha256:213bebd51821ed89b4d5b35bb10dbe67564228b3568f463a351a08e8b1677025 --hash=sha256:2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be --hash=sha256:8c0848ba790a895801d5bfd171da31cad3e551dbcc4e59677a3b622de2ceca98 --hash=sha256:a88526a271e846e44779bb9ad7a738c6d3c4a9d01e15a128ecfc6dd4696393b7 --hash=sha256:883a549382fc22d29a0568f3ef20b38c8e7ab633a59498ac4eb63a3bf36d3fd3! Will try again.
An error occurred while installing pyqt5-qt5==5.15.2 --hash=sha256:9cc7a768b1921f4b982ebc00a318ccb38578e44e45316c7a4a850e953e1dd327 --hash=sha256:76980cd3d7ae87e3c7a33bfebfaee84448fd650bad6840471d6cae199b56e154 --hash=sha256:750b78e4dba6bdf1607febedc08738e318ea09e9b10aea9ff0d73073f11f6962 --hash=sha256:1988f364ec8caf87a6ee5d5a3a5210d57539988bf8e84714c7d60972692e2f4a! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pyqt5-qt5==5.15.2 (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pyqt5-qt5==5.15.2
ERROR: Couldn't install package: pyqt5-qt5
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/3 — 00:00:01

Before the installation of these dependencies it does not seem to be a problem.
(minor change in this script is the pip version (I set the 22.1.2) but the result is the same with the version of the original script)

### OS Version

Monterey 12.4 

### openpilot version or commit

356190f6712b68218237147deddf90fbe6268b6e

**Comment by pd0wm** [comment]
pyqt was removed from the dependencies by https://github.com/commaai/openpilot/commit/1382e28aa0b32923a44efa28c5b25d9b02c41d68
