### ISSUE TITLE
Improve Chinese translations

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25072]
We'd like to improve our simplified translations and add traditional.

Translation file: https://github.com/commaai/openpilot/blob/master/selfdrive/ui/translations/main_zh.ts

Install QT Linguist with `sudo apt install qtbase5-dev qtchooser qt5-default qttools5-dev-tools` and run `linguist selfdrive/ui/translations/main_zh.ts` to edit the file

**Comment by sshane** [comment]
@deanlee want to take a look? @sunnyhaibin is also going to fix some translations tonight.

**Comment by crwusiz** [comment]
i add korean translate https://github.com/commaai/openpilot/pull/25073
