### ISSUE TITLE
Hyundai: VIN returns on non-functional address for certain cars

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25096]
Responses from all addresses from 0x700 + 256 (these are from `IsoTpParallelResponse`, so they are tx addrs):

```python
(1971, None) uds b'1.08.00'
(2002, None) uds b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
(1990, None) uds b'KNDC44LA2N5030320'
(2022, None) uds b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff
(2020, None) uds b'CVEV-- BMS       '
(2018, None) uds b'KNDC44LA2N5030320'
```

**Comment by sshane** [comment]
Interestingly, I see these addresses in this document: https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/vehicle/OVMS.V3/components/vehicle_kianiroev/src/vehicle_kianiroev.cpp

1990 is `Cluster. ODO`
2018 is `VMCU - VIN`

@gregjhogan think we need another brand-specific request for this car, or does it really respond on a non-standard address?

**Comment by sshane** [comment]
I checked a Niro EV actually, and it has the same problem (it responded with `'DEEV__ BMS \x00\x00\x00\x00\x00\x00'`), maybe this is a problem with all the HKG EVs.

**Comment by gregjhogan** [comment]
Mixing sending requests for functional and physical addresses kind of sounds like a mess (you can't do it in parallel).  It seems possible that all supported vehicles that are not electric currently respond with the VIN on 0x7e8 meaning we could potentially switch it to only querying two addresses: 0x7e0 (engine) and 0x7e2 (vehicle motor control unit) and query them in parallel.

**Comment by sshane** [comment]
This seems to work! EV6 responses to both UDS and OBD queries on 0x7e2, Optima and RAV4 on 0x7e0

**Comment by sshane** [comment]
Looks like the Civic only responds on the 29 bit functional address. Can we not query that in parallel?

**Comment by gregjhogan** [comment]
I believe the only thing we cannot do in parallel is:
* sub addresses (I believe we have found this doesn't work for Toyota)
* physical and functional addresses (functional address response handling has to assume all response messages pertain to the functional address request)

**Comment by sshane** [comment]
Aren't functional addresses labeled by query type? Could we read the response data to know which tx addr is for an rx addr? We could use that, but that's extra complexity

We could still make it work as is for VIN, as we only have one functional 29 bit address. Might take some changes to IsoTpParallelQuery though

**Comment by gregjhogan** [comment]
With some work you could probably do 29 bit functional and 11 bit physical addresses in parallel since they don't overlap.
It is harder to say if you can handle a physical address that also responds to a functional address (the response address is the same for both and the ECU could do something dumb like respond to both putting duplicate messages on the CAN bus that will break expected sequence)
