### ISSUE TITLE
Match speeds show on car's dash

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#25099]
Need to look into the other cars, but know about these off the top of my head:
- [ ] Toyota: vEgo https://github.com/commaai/openpilot/pull/25234
- [x] Toyota: set speed 
- [x] Hyundai: only vEgo doesn't match https://github.com/commaai/openpilot/pull/25235
- [x] Honda: vEgo doesn't match https://github.com/commaai/openpilot/pull/25232
- [x] Nissan: https://github.com/commaai/openpilot/pull/25233

**Comment by adeebshihadeh** [comment]
@sshane can you double check on Discord to see if we're missing any? If not, we should be good to close once the last Toyota PR is merged.

**Comment by sshane** [comment]
Think Subaru is still wrong
