### ISSUE TITLE
Multilanguage improvements

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25092]
- [ ] We would like to dynamically translate without restarting UI
- [ ] Translate alerts (dynamic text requires injecting our own translations with custom contexts into the TS files)
- [x] For the [translations badges](https://github.com/commaai/openpilot/tree/badges), auto-concatenate them together

**Comment by sshane** [comment]
@deanlee want to look into this when you get a chance?

**Comment by deanlee** [comment]
WIP

**Comment by sshane** [comment]
Offroad alerts are done here: https://github.com/commaai/openpilot/pull/28512, onroad alerts are in this PR: https://github.com/commaai/openpilot/pull/28528, dynamically updating isn't a priority. Closing!
