### ISSUE TITLE
Ensure CANParser counter/checksums checks are the same as panda

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25160]
For example, `SCM_BUTTONS`'s counter started returning garbage values (or issue with a cable) and only panda noticed it, causing a controls mismatch.

We need to change how the checks work in the CANParser, if counter or checksum failed, we don't update the last time seen, so it just causes a TIMEOUT error with the same thresholds as it.

http://data-raw.internal/c390b60ad96d2ff2/2022-07-01--07-40-21/4/rlog.bz2

**Comment by adeebshihadeh** [comment]
This case really looks like a bad cable. We also need a better check than a threshold on bad counters, as some mildly faulty cables can slip through like in this case.

**Comment by sshane** [comment]
- [ ] Do same check for checksum now

**Comment by adeebshihadeh** [comment]
@sshane is this done?

**Comment by sshane** [comment]
Made the counter checks match, I'll check the checksum checks. Might already match

**Comment by adeebshihadeh** [comment]
@sshane this should be done with the new fuzzing tests right?

**Comment by sshane** [comment]
I believe so.
