### ISSUE TITLE
Ioniq 5 - missing CAN message 0x2A4

### ISSUE THREAD

**Issue by G80Tampa** [commaai/openpilot#25182]
### Describe the bug

Error, CAN Bus Disconnected: Likely Faulty Cable

![IMG_20220713_233016031_HDR](https://user-images.githubusercontent.com/86332792/179123929-fde1ebf2-5d84-4c32-97dc-7e5b295e0caf.jpg)
![unknown](https://user-images.githubusercontent.com/86332792/179123947-fff7ea57-b3f0-4f93-9f37-8f4a26d137db.png)

### Which car does this affect?

Hyundai Ioniq 5 2022

### Provide a route where the issue occurs

51b07e62f9b64fee|2022-07-14--19-25-33--1

### openpilot version

0.8.15

**Comment by spectre3ooo** [comment]
Here's another drive from my car:
45dfe516db6622f8|2022-07-19--00-10-13
But, i'm getting a camera malfunction error on my C3 now.

**Comment by hoomoose** [comment]
I get this exact same error with my Kia EV6.
Route: 68d6a96e703c00c9%7C2022-07-19--16-53-15

**Comment by sunnyhaibin** [comment]
The Ioniq 5 from the issue's OP confirmed that this specific Ioniq 5 does not have the `LKAS` message `0x2a4`.

**Comment by spectre3ooo** [comment]
> The Ioniq 5 from the issue's OP confirmed that this specific Ioniq 5 does not have the `LKAS` message `0x2a4`.

In this case, would you tell it not to look for 0x2a4, and instead use the LFA messages?
