### ISSUE TITLE
Honda: Civic brake pulses while pre-enabled and adjusting set speed at a standstill

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#25191]
Engage at a standstill -> keep brake depressed -> adjust set speed

`be13974ffe78aa72|2022-07-16--15-58-44`

**Comment by adeebshihadeh** [comment]
Looks like each button press re-enables the cruise state, which openpilot will immediate;y cancel
![image](https://user-images.githubusercontent.com/8762862/179381261-a40b3c64-751a-4ab1-ad16-b0221007e805.png)

**Comment by vanillagorillaa** [comment]
Looks to only occur when a pedal is installed. Maybe there is another bit that can be used for cruisestate.enabled?

**Comment by adeebshihadeh** [comment]
Ah, if it's pedal only, then I think we can close.
