### ISSUE TITLE
Hyundai Santa Fe 2022 no longer fingerprints correctly

### ISSUE THREAD

**Issue by khoi** [commaai/openpilot#25195]
### Describe the bug

My Hyundai Santa Fe 2022 is no longer FP-ed correctly. After checking `carParams`, the value seems to be changed from the original values (https://github.com/commaai/openpilot/pull/23718/files).

Do I need to update them again? 

### Provide a route where the issue occurs

ec07911a91f863f3|2022-07-18--11-18-16

### openpilot version

master-ci

**Comment by sshane** [comment]
Besides the recent PR to use the brand FW response, looks like your car is also returning a new transmission FW not in the database. It would have at least fuzzy fingerprinted with that added

**Comment by sshane** [comment]
Want to try this branch? https://github.com/commaai/openpilot/pull/25205

**Comment by sshane** [comment]
Fixed in https://github.com/commaai/openpilot/pull/25205 and https://github.com/commaai/openpilot/pull/25204
