### ISSUE TITLE
Openpilot doesn't support chinese version camry 2021

### ISSUE THREAD

**Issue by iRankoo** [commaai/openpilot#25317]
### Describe the bug

Dear all.
My car is toyota camry 2021, gas , 2.5g, chinese version. which is different from international version. 
I have bought panda, harness, and EON.  I connect the devices,and start the car engine. But the EON show "Car Unrecognized". It doesn't work.
It looks like chinese camry has different DBC control command.
Can anyone help?

### Which car does this affect?

Toyota camry 2021 chinese version

### Provide a route where the issue occurs

11111

### openpilot version

0.8.13

**Comment by adeebshihadeh** [comment]
We no longer support the EON and can't look at issues from previous releases. Check out the discord for help.
