### ISSUE TITLE
The cameraview will disappear when drawing lane lines 

### ISSUE THREAD

**Issue by Ren-HL** [commaai/openpilot#25323]
### Describe the bug

I build this on an arm board and I want to use webcam to run openpilot.
On the pc(x86), I modified part of the code with reference to CARLA and the openpilot can sucessful draw the lane lines.
But on the arm board, the cameraview will disappear when drawing lane lines. Whether I use webcam or replay. 
When the program runs here :
`painter.drawPolygon(scene.track_vertices.v, scene.track_vertices.cnt);`
the cameraview in the ui will disappear.
I change the pen color to red otherwise can not see anything.

https://user-images.githubusercontent.com/101161005/182121398-a71c5b10-755d-42c9-864f-9a1319eaa3c3.mp4

### OS Version

Ubuntu 20.04

### openpilot version or commit

6e789fa

**Comment by adeebshihadeh** [comment]
We can't really look into issues like this that are platform or board specific; we can only really ensure that the UI runs well on our Ubuntu workstations and the comma three. It's possible this is a bug in your GL driver or the Qt platform for your board.
