### ISSUE TITLE
Blank Screen on Boot (screen is working)

### ISSUE THREAD

**Issue by bradmurray** [commaai/openpilot#2532]
My comma two boots up showing the comma logo, but then goes to a blank screen and never fully starts. I can hold down the power button and I will see the reboot/power down options, but that's all I can do.

**Device/Version information:**
 - Device: comma two
 - Dongle ID: a2b1d650214053d7
 - Route: N/A
 - Timestamp: N/A
 - Version: Unable to get because of bug
 - Car make/model: Toyota Prius Prime 2020

**Comment by adeebshihadeh** [comment]
I see your latest routes are from master. There's many ways this can happen when you're checking out other branches/forks, including not initializing the submodules. I suggest factory resetting your device and sticking with the release branch.
