### ISSUE TITLE
harness relay open while panda in bootstub

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#25343]
### Describe the bug

Git Commit 4f0fe747ba on master-ci today. Tried rebooting, tried restarting car, etc. Comma keeps showing "No Panda" and car states on start "Auto Emergency Braking (AEB) / ACC Limited Functionality Service Required" though I don't see a check engine light.

### Which car does this affect?

Chrysler Pacifica 2022

### Provide a route where the issue occurs

N/A as route won't generate, Serial: 4395faadf0a373f2

### openpilot version

0.8.16 Nightly (4f0fe747ba)

**Comment by adeebshihadeh** [comment]
https://github.com/commaai/panda/pull/1006 fixes the "No Panda", but your cruise fault is an unrelated issue. Does the fault occur with the harness installed **without the comma three plugged in** (make sure to unplug the device while the car is off, so the faults can clear)? If so, sounds like you may have a bad harness.

**Comment by ns3284** [comment]
As mentioned, the cruise fault may be some odd symptom. My CEL does not come on, like it normally would when there is a fault. I'll wait for that Panda fix and report back, or we can close this as a duplicate issue.

**Comment by adeebshihadeh** [comment]
As I said, these should be unrelated issues, and I'd like to explore the fault. If they are not unrelated, then that is its own issue that should be addressed. Either way, there's a problem here that we should understand.

**Comment by ns3284** [comment]
![image](https://user-images.githubusercontent.com/43015596/182479581-22ad66c0-30d9-4d9b-b527-b4439f18fcf3.png)
![image](https://user-images.githubusercontent.com/43015596/182479606-e4981424-6de7-461c-b6c2-f6156e14079e.png)
![image](https://user-images.githubusercontent.com/43015596/182479647-e07a1367-e1e9-4a50-a871-3124c5e90233.png)
Just some visuals of what I saw.

**Comment by ns3284** [comment]
Latest update has fixed the problem. I don't see the error on the car anymore. I wonder if somehow the signal from the sensor where the harness is connected may have had some corruption which caused that warning. Basically, perhaps this will always happen when Panda is unable to load?

**Comment by Achilles308** [comment]
> Latest update has fixed the problem. I don't see the error on the car anymore. I wonder if somehow the signal from the sensor where the harness is connected may have had some corruption which caused that warning. Basically, perhaps this will always happen when Panda is unable to load?

I also got a brief cruise fault when I had the no panda error on master-ci recently. My car cleared it after the relay clicked over though... the error was only on for maybe 1/10 to 1/4 of a second? Maybe your car kept it for longer?
