### ISSUE TITLE
Low Memory

### ISSUE THREAD

**Issue by themagiccog** [commaai/openpilot#25392]
### Describe the bug

Notification on my device showing low memory
![WhatsApp Image 2022-08-09 at 3 50 42 PM](https://user-images.githubusercontent.com/13458634/183761499-e7490cb4-1113-4d3b-bf13-a56888f14514.jpeg)

### Provide a route where the issue occurs

06353521b1f136dd

### openpilot version

0.8.15

**Comment by teknonut** [comment]
Happened to me as well yesterday while vehicle was running and I was sitting in the parking lot.  Had to reboot to resolve the issue.

**Comment by adeebshihadeh** [comment]
This should be fixed in 0.8.16.
