### ISSUE TITLE
2022 corolla car unrecognized->py fw fix now  "can error"  HELP!?!

### ISSUE THREAD

**Issue by witchdr2022** [commaai/openpilot#25452]
### Describe the bug

I have a 2022 Corolla that didn’t recognize the car so I added fw update for blueprinting per the instructions now it is giving me “CAN error: check connections” any suggestions?

### Which car does this affect?

2022 corolla  (generic US model)

### Provide a route where the issue occurs

e01d990b9fafc7c7|2022-08-16--08-22-40

### openpilot version

0.8.16

**Comment by adeebshihadeh** [comment]
You added it to the hybrid instead of the ICE corolla, so it was missing a message that openpilot was expecting. I added your FW to the correct platform in 0ed8a7f42def893bece557c0acd3d5fb1e11ecde, so you can run master-ci until the next release.
