### ISSUE TITLE
UI - Yellow lead indicator isn't in 3D 

### ISSUE THREAD

**Issue by ShaneSmiskol** [commaai/openpilot#2545]
Whenever I'm going up or down a hill with a lead, the yellow indicator doesn't follow the car and stays in its current y position.

**Comment by VirtuallyChris** [comment]
I noticed this and was about to report it. Nice job 😆

**Comment by HaraldSchafer** [comment]
Ah yes, I can fix that

**Comment by HaraldSchafer** [comment]
@deanlee Interested in looking into this? The lead prediction of the model only predicts and x and y, no z (height). But we could use the height of predicted path at that point to draw the lead triangle.

**Comment by deanlee** [comment]
@HaraldSchafer  good idea. I'd like to have a try in pull request https://github.com/commaai/openpilot/pull/2525

**Comment by adeebshihadeh** [comment]
@deanlee can we bring this out of the big UI PR and make a small PR for just this?

**Comment by deanlee** [comment]
@adeebshihadeh added 20 lines of code in this new PR: https://github.com/commaai/openpilot/pull/19793
