### ISSUE TITLE
Master-ci 0.8.0 Model Lagging Error

### ISSUE THREAD

**Issue by nickgeurnop** [commaai/openpilot#2546]
Issue:

Model Lagging error on 0.8.0 pre release. Normal bootup, no dash faults

Details:

 - Device: comma two
 - Dongle ID: 1615388ccbe3edc9
 - Route: 1615388ccbe3edc9|2020-11-13--19-11-34
 - Timestamp: About 2 minutes into drive, repeated lagging until reboot
 - Version: master-ci 0.8.0 pre-release
 - Car make/model: 2019 Toyota Corolla Hatchback XSE (TSS2.0)

Updated, restarted C2 and car. Issue went away. Will monitor and report.

**Comment by pd0wm** [comment]
Looks like loggerd was using more CPU than normal. @adeebshihadeh any thoughts?

**Comment by nickgeurnop** [comment]
Issue:

Model Lagging error on 0.8.0 pre release. Normal bootup, no dash faults

Details: 

Happened twice in quick succession. Was able to re-engage a minute later unlike first bug report. 

Expected Behavior:

Model does not lag and does not throw error forcing disengagement.

Device: comma two
Dongle ID: 1615388ccbe3edc9
Route: 1615388ccbe3edc9|2020-11-16--09-25-09
Timestamp: @ 9:31:16 
Version: master-ci 0.8.0 pre-release
Car make/model: 2019 Toyota Corolla Hatchback XSE (TSS2.0)

**Comment by nickgeurnop** [comment]
Issue:

Model Lagging error on 0.8.0 pre release. Normal bootup, no dash faults

Details:

Happened twice in quick succession. Was NOT able to re-engage a minute later like first bug report.

Expected Behavior:

Model does not lag and does not throw error forcing disengagement.

Device: comma two
Dongle ID: 1615388ccbe3edc9
Route: 1615388ccbe3edc9|2020-11-18--17-35-44
Timestamp: @ 17:47:30, many times afterward for about 10 minutes
Version: master-ci 0.8.0 pre-release
Car make/model: 2019 Toyota Corolla Hatchback XSE (TSS2.0)

**Comment by nickgeurnop** [comment]
I'd like to mention that I am consistently updating the Master-ci branch while reporting these bugs.

**Comment by adeebshihadeh** [comment]
Your last route isn't uploaded. Can you connect your device to wifi until all the logs are uploaded?

**Comment by nickgeurnop** [comment]
I made the report maybe 15 minutes after getting home. Please let me know if it is still unavailable. C2 connects to wifi from driveway when I get home + I have my 3 months of comma prime.

**Comment by geohot** [comment]
Can confirm DM model is taking ~37 ms to run when it usually takes ~14 ms on 1615388ccbe3edc9/2020-11-13--19-11-34/0

1615388ccbe3edc9/2020-11-15--12-38-37/1 is running in the usual 14.

**Comment by geohot** [comment]
Fix for dmonitoringmodeld CPU usage:

https://github.com/commaai/openpilot/commit/826c21b045b09d6e28b313b3c57cd62800febb16

Though aside from the wasted RAM bandwidth, I'm not sure how this causes modeld lag. Maybe it is just the RAM bandwidth?

**Comment by adeebshihadeh** [comment]
@nickgeurnop This should be fixed in master-ci now. Re-open the issue if it happens again after updating.
