### ISSUE TITLE
Add replay (unlogger) to QT UI

### ISSUE THREAD

**Issue by geohot** [commaai/openpilot#2547]
So at first it sounds crazy. But then you remember how bad unlogger is and you think about it more.

A dashcam has the ability to replay the "recording" on the device. openpilot should too, and it can replace unlogger. Replay with the same messages on the bus. Grab the files from the API, or fast fast if they are already on the device. We do a really bad job surfacing the ability to replay routes in the detail we record them with explorer and the app.

I imagine a nice movie timeline scroll overlayed on the bottom of UI while replaying. This completes the device as a dashcam, but...

The real win would be for PCs. I run ui on my PC, pair the PC to my account, and can access all the routes from my device. I replay one, I can inspect the messages, replace services, etc...all the things we do now with unlogger.

The docker is great for carla (minus the current bug). I was pleasantly surprised when the openpilot UI came up. Imagine I could, with just the one docker command and a quick pair to my account from my phone, start replaying one of my drives (or of course some demo drives without pairing).

Either way, we need to surface playing back drives better to (prospective) developers.

**Comment by pd0wm** [comment]
Would be nice if we can also replace ui.py. The only reason I still use that is for plots of speed and steering angles. If we can add a second window to the qt ui to plot/visualize arbitrary cereal messages that would be a great improvement over ui.py

**Comment by marschr** [comment]
Did a mockup of an c2 version of it..
![op_u2ui_v1](https://user-images.githubusercontent.com/5367013/105155010-e1138f00-5ae8-11eb-833c-bf5575b75961.png)

Was the `tools/nui` thingy ever related to this idea? It seemed like some QT version of unlogger.

**Comment by adeebshihadeh** [comment]
TODOs
- [ ] initial headless PR (#20602)
  - [ ] streaming + socketless mode
  - [ ] fetch routes with the public API
  - [ ] all python unlogger functionality
- [ ] nice route selector in the UI
- [ ] smart segment fetching
- [ ] works well on-device
- [ ] nice demo route with docker?

**Comment by adeebshihadeh** [comment]
replay is good now, but do we still want this? I don't see this becoming better than connect/useradmin, and it's tons of code to add to the UI.

**Comment by deanlee** [comment]
Maybe a basic version can be implemented without too much code, I will try to see if it works

**Comment by deanlee** [comment]
it may not require a lot of code to only implement basic functions. let me have a try.
