### ISSUE TITLE
nav: parse roundabout step properly

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25480]
### Describe the bug

Instruction show first right, but it's 3rd right...

![20220818_180921](https://user-images.githubusercontent.com/96002277/185460205-1453c82f-36d9-4345-9691-e481d6fd6363.jpg)

### Provide a route where the issue occurs

6111bd7df5043394|2022-08-18--17-58-07

### openpilot version

fix-lfa-warn

**Comment by DerGue69** [comment]
OpenPilot v0.8.16

**Comment by sshane** [comment]
Think this should solve this: https://github.com/commaai/openpilot/pull/29159

**Comment by sshane** [comment]
I checked another route with a straight roundabout but mapbox gave us a "right" modifier which is incorrect, but it seems like we're parsing the data correctly. Nothing said straight in the route step.

Can you get a new route with rlogs uploaded?

**Comment by DerGue69** [comment]
I would need a new prime abbo.

**Comment by sshane** [comment]
That's fine, can you find the exact roundabout and send me a route with rlogs? I can simulate the rest

**Comment by DerGue69** [comment]
@sshane This was last year on a road trip. 
This place is several hours away from home. 
So...no, sorry I can't.

I could find out the exact location on Google Maps with a little research.

**Comment by sshane** [comment]
Oh that's fine, I'll use a recent route then you have and put the destination somwhere.

**Comment by sshane** [comment]
@jakethesnake420 want to try this issue?

**Comment by jakethesnake420** [comment]
@sshane sure I can take a look. Do i need to handle left hand drive? From skimming through the code I don't think navd is checking for 'driving_side'. Would also need to create flipped icons.
