### ISSUE TITLE
Multilang: handle longer text in UI

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25492]
- [ ] Make toggle title text wrap like the descriptions<br>
  ![Screenshot from 2022-08-19 00-02-39](https://user-images.githubusercontent.com/25857203/185562805-58b86bbc-09a5-458c-a025-fde99dce2716.png)
- [ ] (dynamically?) adjust button widths<br>
  ![Screenshot from 2022-08-18 23-51-23](https://user-images.githubusercontent.com/25857203/185563176-1d0e0ab2-fa05-4442-8fb3-e7a9c11ecd63.png)
- [ ] (dynamically?) adjust text sizes where and when needed

**Comment by sshane** [comment]
@deanlee want to tackle any of these? The first should be a pretty easy one

**Comment by bpluta** [comment]
@sshane I can try to do this if no one has taken this task yet. Dynamically adjustable text sizes would be nice feature as some phrases in different languages are much longer than in English and could not be made any shorter without statically shrinking text for all language versions

**Comment by sshane** [comment]
Going to wait for a re-design instead
