### ISSUE TITLE
curb/sidewalks drivable

### ISSUE THREAD

**Issue by brianandyt** [commaai/openpilot#2549]
**Describe the bug**
With the pytorch model the curb and sidewalk is considered drive-able

**Expected behavior**
Road edge stop at the curb not sidewalk.

**Device/Version information**
 - Device: [comma two]
 - Dongle ID: [5b28df82ec2927c8]
 - Route: [5b28df82ec2927c8|2020-11-14--09-03-31--0]
 - Timestamp: [4min 10s into the drive)]
 - Version: [master-ci]
 - Car make/model: [Toyota Corolla 2020]

**Comment by HaraldSchafer** [comment]
For the time being we don't use road edges for driving policy, so they are not critical.
