### ISSUE TITLE
Toyota Rav4 Road Sign System missing

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#255]
I have been trying to find the can bus messages for road sign recognition. 
Some how I assume it needs to be proxied from the forward camera. 
But need to find the messages that need to be forwarded first.
Anyone else missing this feature?

**Comment by mtourangeau** [comment]
It wasn’t missing on my Canadian Prius Prime in the USA. But the sign does not works in Canada even without Open Pilot Installed.

**Comment by arne182** [comment]
Done. Working. Don't know the signal yet.

**Comment by zorrobyte** [comment]
The Prius Prime uses the same camera module, however this feature is disabled. Is it possible to spoof model encoding from the ECU to enable features on other models?

**Comment by arne182** [comment]
This issue has been fixed with the forwarding of auto high beams via 120 ohm resistor
