### ISSUE TITLE
Mazda: 2022 CX5 OEM Front Camera Sensor Failure Error

### ISSUE THREAD

**Issue by kravatch** [commaai/openpilot#25525]
### Describe the bug

When driving with OP active, front camera sensor error shows up on the OEM instrument cluster

similar error to https://vf.vin/static/uploads/images/sr2/mazda/2022/02/18/2018-mazda-cx-5-jm3kfbdm5j0335098-img-13.jpg 

Error goes away with disengage/rengage OP

No errors seen on C3 unit and self drive does not disengage and does not seem affected

### Which car does this affect?

2022 CX5 Signature

### Provide a route where the issue occurs

1bf23ce7dee4e6fc|2022-08-22--19-28-34
1bf23ce7dee4e6fc|2022-08-22--19-20-26
### openpilot version

0.8.15 release3

**Comment by adeebshihadeh** [comment]
* Does this only show while engaged?
* Does it stay on once it appears?
* Does it appear instantly after engaging?
* How consistently does this happen? Every engagement?

@Jafaral do you know anything about this?

**Comment by kravatch** [comment]
> * Does this only show while engaged?
yes
> * Does it stay on once it appears?
I believe so. I left it on for about 30 seconds after the warning triggered before I disengage OP which clears it
> * Does it appear instantly after engaging?
no, it does take some time, if the error happens (it does not always happen)
> * How consistently does this happen? Every engagement?
not every engagement, but it does correlate with more complicated actions (slow to stop and s-turning)

**Comment by Jafaral** [comment]
Would help I cab view CAN data @adeebshihadeh

**Comment by Jafaral** [comment]
@kravatch  are you running stock OP? or one of my branches?   if you are running stock OP, can you switch and try `mazda-0.8.15` ?

**Comment by kravatch** [comment]
I am running stock 0.8.15

To clarify earlier behavior, the error does go away on its own, but does come back pretty consistently so long as self-drive was active

Unfortunately today my c3 unit started experiencing fan failures on the unit itself and it overheated and reset 2 times. I suspect that may be related to the camera failure. I am still within the 30 day purchase window and will be pursuing a hardware RMA

**Comment by adeebshihadeh** [comment]
> Unfortunately today my c3 unit started experiencing fan failures on the unit itself and it overheated and reset 2 times. I suspect that may be related to the camera failure. I am still within the 30 day purchase window and will be pursuing a hardware RMA

The fan malfunction is software. We're pushing out 0.8.16 this week to address it. You can run the `release3-staging` branch to fix it for now. https://github.com/commaai/openpilot/pull/25509

**Comment by kravatch** [comment]
@Jafaral I did just try the mazda-0.8.15 branch but the camera issue persisted and I also faced a "cannot steer under 0 mph" error (though it did self drive just fine)

I also needed to patch in my FW values IE https://github.com/commaai/openpilot/pull/25423

**Comment by Jafaral** [comment]
@kravatch , can you please send me a drive with camera issue? You can dm me on discord.

**Comment by kravatch** [comment]
I think i have narrowed the camera issue down to low(er) speed only

I suspect it may be an interaction with the OEM TJA in the signature trim which kicks in below 40 MPH

I have not been scientific in my experiments, but above that speed does seem to be around when I stop seeing this

**Comment by Jafaral** [comment]
I did discover new signals in your car, working to see if can fix i the issue for you:

![image](https://user-images.githubusercontent.com/10768078/187349356-2759d6fd-91fc-48ab-93e0-ac78a9c4d8ac.png)

This also might be related to :  #24881 , to steer from zero without delay in cars with no stock TJA enabled.

**Comment by sshane** [comment]
@kravatch going to close since you report this is no longer an issue on master. Please let me know if that's not the case!

**Comment by DouglasSherk** [comment]
I'm getting this same issue but on a 2024 Signature now. I'm on master-ci from yesterday.
