### ISSUE TITLE
test_translations not working locally?

### ISSUE THREAD

**Issue by jeroenlammersma** [commaai/openpilot#25547]
### Describe the bug

When trying to run the instruction as stated [here](https://github.com/commaai/openpilot/tree/master/selfdrive/ui/translations#testing):
```bash
selfdrive/ui/tests/create_test_translations.sh && selfdrive/ui/tests/test_translations
```
it will not work:

![test_translations_error](https://user-images.githubusercontent.com/33349469/186422823-897107dd-fa2c-4e5f-ba23-a3c741bc1d03.png)

Or is it a typo and is [test_translations.py](https://github.com/commaai/openpilot/blob/master/selfdrive/ui/tests/test_translations.py) meant with the second command?

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
You need to build with the `--test` flag, e.g. `scons -j8 --test`.
