### ISSUE TITLE
Navigation stopped when driving through a long tunnel 

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25541]
### Describe the bug

I had navigation to a destination active.
Car entered tunnel. Navigation was awful then, GPS was all over the place.
When tunnel was over, I recognized that the navigation destination was cancelled.
It was not possible to reengage navigation through my smartphone.
![20220821_145146](https://user-images.githubusercontent.com/96002277/186350399-85aae576-278a-49ba-adf1-66afa608329c.jpg)

### Provide a route where the issue occurs

Not recorded

### openpilot version

0.8.16 lfa-fix-warn

**Comment by adeebshihadeh** [comment]
We can't look into this without a route. Why was this not recorded?

**Comment by DerGue69** [comment]
I am from Austria.
I am currently in slowenia for a week.
Had to disable the upload to save data. (Personal sim card)

Will be back at home on Monday, try to provide route by then.

**Comment by DerGue69** [comment]
6111bd7df5043394|2022-08-21--12-18-16--33   @   ~12:51 I entered the tunnel.
And afterwards the navigation was not working anymore.

**Comment by sshane** [comment]
Does this still happen?

**Comment by DerGue69** [comment]
I don't know, since I dont have prime any more.
