### ISSUE TITLE
Regression: Rav4 2019 FWD Fingerprint Failure

### ISSUE THREAD

**Issue by nkanitkar** [commaai/openpilot#25542]
### Describe the bug

Toyota Rav4 2019 FWD does not fingerprint on release3 branch. Getting unknown vehicle error. 

Steps to re-create:
Try using release3 branch on specified vehicle. 

Using Erich's `values.py fix` pin in #toyota-lexus resolves this issue. 
This has been broken for a while. I initially ran into this issue when upgrading from v7.X dragonpilot to v8.X release3 on C2.
Now using a different C3 using release3, I am getting the same error.
Previously on v7.X release2 and dragonpilot I did not experience this fingerprinting issue. 

### Which car does this affect?

Toyota Rav4 2019 

### Provide a route where the issue occurs

28947140cc79e4cf|2022-08-23--12-10-11--3

### openpilot version

0.8.15

### Additional info

Fixed by disabling auto-updates and manually replacing values.py. As per Erich's pin in #toyota-lexus.

```
echo -en "1" > /data/params/d/DisableUpdates
cd /data/openpilot/selfdrive/car/toyota && rm -f values.py
wget https://raw.githubusercontent.com/ErichMoraga/openpilot/815/selfdrive/car/toyota/values.py && python -m compileall values.py
```

**Comment by sshane** [comment]
Merged missing engine FW here: https://github.com/commaai/openpilot/pull/25563, you were likely hardcoding your fingerprint on that fork before.
