### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by pipeabellos** [commaai/openpilot#25550]
### Describe the bug

Following the README.md steps [here](https://github.com/commaai/openpilot/tree/master/tools/webcam) there are some references `camera_webcam.cc` which is a file that no longer exists.

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Added a note in 051e1e0a062e0eb398e9bb16291b95ba3ae497eb

**Comment by L-Net-1992** [comment]
camera_webcam.cc file is missing and the PC cannot run
