### ISSUE TITLE
Mazda: 2022 CX5 disengage on gas triggers stock radar cruise control cancelled message 

### ISSUE THREAD

**Issue by alancyau** [commaai/openpilot#25586]
### Describe the bug

I noticed a pattern where pressing the gas pedal while assisting the steering wheel during a EPS limit exceeded situation causes the car to display a "Mazda Radar Cruise Control Cancelled" message on the dash and a chime. OpenPilot will still properly disengage and this is simply a deviation from a regular disengage. A regular disengage on gas, not during EPS limit exceeded situation, will not produce this message.

a4af1602d8e668ac|2022-08-28--15-20-10--4

### Which car does this affect?

2022 Mazda CX5

### Provide a route where the issue occurs

a4af1602d8e668ac|2022-08-28--15-20-10--4

### openpilot version

082e46ce5e0f16108d59e8c2c04ec76ea8e7dd86

**Comment by alancyau** [comment]
![Uploading EDC27E64-3C93-40C6-8D75-84946508689C.jpeg…]()

**Comment by alancyau** [comment]
![7FC9C9C3-A99A-42E5-B827-DD7C4138655F](https://user-images.githubusercontent.com/59986772/187095443-c19e7f0b-1bc2-4e18-9f69-a4addd7c3277.jpeg)

**Comment by alancyau** [comment]
This bug appears to be resolved on @Jafaral's branch. https://github.com/Jafaral/openpilot/tree/mazda-tja

a4af1602d8e668ac|2022-09-02--22-30-21--10

**Comment by sshane** [comment]
Do you know what he does?

**Comment by Jafaral** [comment]
I think I resolved upstream too.

**Comment by sshane** [comment]
What was the issue?
