### ISSUE TITLE
openpilot docker image native support for M1

### ISSUE THREAD

**Issue by MaherJendoubi** [commaai/openpilot#25581]
### Describe the bug

I build the openpilet docker image successfully but when I run the container I see an AMD64 on the docker desktop on M1.
The warning is "IMAGE MAY HAVE POOR PERFORMANCE, OR FAIL, IF RUN VIA EMULATION".
Is it possible to have native support for M1 for the docker image?

### OS Version

macOS Monterey Version 12.5.1

### openpilot version or commit

13489d092e2c09119e880022507d7331cf54c615

### Additional info

Docker desktop for MAC version 4.11.1

**Comment by adeebshihadeh** [comment]
This really isn't something we're interested in working on ourselves right now, but we would gladly merge a PR for it.
