### ISSUE TITLE
Comma two suddenly stopped working, showing no PANDA

### ISSUE THREAD

**Issue by visionandy** [commaai/openpilot#25580]
### Describe the bug

Comma two suddenly stopped working yesterday, and showing no PANDA. 

### Provide a route where the issue occurs

0844505b5a3fc8d8

### openpilot version

0.8.13.1-release

### Additional info

I have provided the Dongle ID, and please let me know if there are anything needed from my side. Many thanks!

**Comment by adeebshihadeh** [comment]
Our issue tracker isn’t for support. Check out the community discord instead.

**Comment by visionandy** [comment]
so that means all these problems have to be solved from the customer side?
