### ISSUE TITLE
Bad behaviour during construction site with double road marking

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25596]
### Describe the bug

During a construction site openpilot was not usable.
Yes, even for a human it is not intuitive (see picture).
Had to contol the car almost the whole time during this construction site.

![image](https://user-images.githubusercontent.com/96002277/187284866-bc58cfd0-5ed0-44d5-8cf2-5876c45de598.png)

### Provide a route where the issue occurs

6111bd7df5043394|2022-08-28--15-30-41--22

### openpilot version

0.8.16 (lfa-fix-warn)

### Additional info

Construction site starts at 15:53:09 - 22
Ends at: 16:00:46 - 30

**Comment by sshane** [comment]
You were on an older model on this branch
