### ISSUE TITLE
Changing Lanes doesn't feel natural and is too harsh

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25595]
I am on  0.8.16 (fix-lfa-warn) and have a Kia Niro EV.

When driving on a straight with ~70 kmh (~43 miles) and I perform a auto-lane change, the "feeling" is ok. Maybe a bit too harsh.

When driving on a motorway with ~130 kmh (80 miles) and I perform the auto-lane change, the initial auto-steering is too hard/harsh and I have to "smooth" it with my hand. It doesn't feel natural.

When driving on a motorway with ~130 km/h e.g. on a long left curve and I perform a lane change from left to right, the feeling is not natural, it is way too harsh. The initial steering is way too hard in this situation.

I would suggest to "smooth" the lane change depending on speed and the steering angle.

**Comment by morrislee** [comment]
i experience this too on 0.8.16 on 2020 GMC Sierra 1500. This effect can be minimized by holding the steering wheel while doing the nudge firmly, then it will smoothly transition

**Comment by sshane** [comment]
You were on an old model, I would try master or the branch you were on now — just updated
