### ISSUE TITLE
Planner Error --> Take control 

### ISSUE THREAD

**Issue by Adminiuga** [commaai/openpilot#2560]
**Describe the bug**
Got a "Planner Error -> Take control immediatly" today, while following a car in a turn on a ramp. At this moment I can't say it is a bug, more of a glitch as it happened only once so far. Just wanted to let you know it happened. 

**How to reproduce or log data**
Can't reproduce this, so far happened only once. But have the logs 

**Expected behavior**
The preference is not getting planner errors.

**Device/Version information (please complete the following information):**
 - Device: EON Devkit 128GB
 - Dongle ID: 3c8f0c502e119c1c
 - Route: 3c8f0c502e119c1c|2020-11-15--11-36-06--8
 - Timestamp: Sun, 15 Nov, 2020 @ 11:44:45 -- 11:44:47
 - Version: v0.8.0-Release@master-ci  git revision: 327d83031dd4
 - Car make/model: Subaru Ascent 2019

**Additional context**
Happened only once, can't reproduce, just hoping it would help to make planner behave better. Otherwise I can live with it and  you may close this issue.

**Comment by HaraldSchafer** [comment]
Should be fixed with this 
https://github.com/commaai/openpilot/pull/2565/commits/0d5ecd64a10debf2f62e27fc23738ccce9d1cdb3
