### ISSUE TITLE
Car was breaking when situation was normal

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25662]
### Describe the bug

OP was engaged. I had a left and right lane.
A car was parking on the right side, and OP was breaking when it should not have.

,
![image](https://user-images.githubusercontent.com/96002277/188328016-8de580ff-d5e5-4a36-b451-50f2fea9e39a.png)

Sunday Sep 4 @ 13:41:43 – 36

### Provide a route where the issue occurs

6111bd7df5043394|2022-09-04--13-05-17--36

### openpilot version

0.8.17 (fix-lfa-warn)

**Comment by sshane** [comment]
You were using stock ACC here, openpilot was not controlling longitudinal
