### ISSUE TITLE
Simulator CI test

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#2572]
The test should run openpilot in the simulator for a minute and fail on process crashes or unexpected alerts. Ideally, this test should be able to run in GitHub Actions.

**Comment by ekdnam** [comment]
I would love to work on the issue. Can you assign me?

**Comment by geohot** [comment]
No assignment required, just submit a PR!

**Comment by ekdnam** [comment]
Okay sure! Can someone give a few guidelines on how to solve the issue? I am new to testing, and would love to get some insights on how to proceed

**Comment by grekiki** [comment]
First get the simulator to work on your PC

**Comment by zachwildd** [comment]
Looks like you'll have to use self-hosted runners to get a GPU

**Comment by adeebshihadeh** [comment]
If we need to use a GPU, we can just run this on our existing jenkins machine, but it doesn't really need to run well. For now, we just want to check for crashes or regressions, like the grey panda deprecation breaking the sim.

**Comment by gijskoning** [comment]
@adeebshihadeh I build a draft pr for carla and bridge.py connection in CI. https://github.com/commaai/openpilot/pull/24009 However, GPU is really needed according to the Carla docs. Do I need to create a similar setup in the Jenkins file?

**Comment by adeebshihadeh** [comment]
@gijskoning if you write a test that runs on my PC, I"ll do the CI integration
