### ISSUE TITLE
An out-of-range value is assigned to longitudinalPlan.longitudinalPlanSource

### ISSUE THREAD

**Issue by Chizuchizu** [commaai/openpilot#25730]
### Describe the bug

I was monitoring the topic while running the replay and found some strange values.

```python
import cereal.messaging as messaging

sm = messaging.SubMaster(["longitudinalPlan"])
while True:
        sm.update()
        print(sm["longitudinalPlan"])
```

The replay was run with the following command, and at around 590 seconds (where it pauses at the intersection), I observed a strange value in `longitudinalPlan.longitudinalPlanSource`.

```bash
cd tools/replay
./replay --demo --ecam --dcam
```

![image](https://user-images.githubusercontent.com/44621609/189565594-809deaf9-960d-4a7f-b0a0-23d6168f590c.png)

This is the value of `longitudinalPlan` observed around 590s of replay.

```bash
( lateralValidDEPRECATED = false,
...
  vTargetFutureDEPRECATED = 0,
  longitudinalPlanSource = (5),
  vCruiseDEPRECATED = 0,
  aCruiseDEPRECATED = 0,
...
  solverExecutionTime = 0 )

```
And the next is the value of `longitudinalPlan` in the normal case.

```
( lateralValidDEPRECATED = false,
...
  laneWidthDEPRECATED = 0,
  vTargetFutureDEPRECATED = 0,
  longitudinalPlanSource = cruise,
  vCruiseDEPRECATED = 0,
  aCruiseDEPRECATED = 0,
...
  solverExecutionTime = 0 )
```

Since `longitudinalPlanSource` is an enumerated type to which values from 0 to 4 are assigned, the number 5 is considered a bug.

[cereal/log.capnp at cea51afd67b5c56f7a18207ef91c5e45d6345526 · commaai/cereal](https://github.com/commaai/cereal/blob/cea51afd67b5c56f7a18207ef91c5e45d6345526/log.capnp)

```capnp
  enum LongitudinalPlanSource {
    cruise @0;
    lead0 @1;
    lead1 @2;
    lead2 @3;
    e2e @4;
  }
```

### Provide a route where the issue occurs

4cf7a6ad03080c90|2021-09-29--13-46-36

### openpilot version

cd7de851b17

### Additional info

If I run `tools/replay/ui.py` while playing the replay, I got an error at some point (when `longitudinalPlanSource` is assigned 5).

I am wondering how an out of range value can be assigned to `longitudinalPlanSource`.

```bash
$ python ui.py 
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "ui.py", line 228, in <module>
    ui_thread(args.ip_address)
  File "ui.py", line 194, in ui_thread
    info_font.render("LONG MPC SOURCE: " + str(sm['longitudinalPlan'].longitudinalPlanSource), True, YELLOW),
  File "capnp/lib/capnp.pyx", line 1019, in capnp.lib.capnp._DynamicEnum.__str__
  File "capnp/lib/capnp.pyx", line 1011, in capnp.lib.capnp._DynamicEnum._as_str
RuntimeError: Member was null.

```

**Comment by incognitojam** [comment]
The route is using the branch `stop-lines` so the cereal definitions aren't necessarily the same
