### ISSUE TITLE
Chrysler: query FW versions on non-OBD bus

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25749]

**Comment by sshane** [comment]
@realfast should be able to get VIN, but do you know if all the ecus respond on bus 0 as well?

**Comment by realfast** [comment]
Yes all ECUs should respond on bus 0. The only one I would question is the gateway.

**Comment by sshane** [comment]
Do/would we use the gateway for anything that tells us any information, ie. is it okay to lose it?

**Comment by realfast** [comment]
> Does the gateway tell us anything about the car we care about? ie. is it okay to lose it?

I can’t think of a reason to keep it.
