### ISSUE TITLE
Nissan: query FW versions on non-OBD bus

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#25755]

**Comment by sshane** [comment]
@avolmensky do you know if you can get all the versions on bus 0?

**Comment by sshane** [comment]
moved to https://github.com/commaai/openpilot/issues/26643

**Comment by sshane** [comment]
I think we can get most, if not all, on bus 0. Want to finalize the Nissan queries first before we add the bus for logging.

**Comment by adeebshihadeh** [comment]
@sshane ready to close?

**Comment by sshane** [comment]
oh yeah
