### ISSUE TITLE
Quectel GNSS: CRC16 check

### ISSUE THREAD

**Issue by HaraldSchafer** [commaai/openpilot#25766]
Intermittently when reading the raw quectel GNSS messages a CRC16 check fails.
https://sentry.io/organizations/commaai/issues/3497081366/?project=77924&query=is%3Aunresolved+user.id%3A0a48944e30871bb9&statsPeriod=14d

Unclear if it needs to be ignored or dealt with.

**Comment by adeebshihadeh** [comment]
ModemManager was interfering, fixed in #25973
