### ISSUE TITLE
corolla cross 21/22 non us - "Dashcam Mode Car Unrecognized"

### ISSUE THREAD

**Issue by lucasolivmed** [commaai/openpilot#25798]
### Describe the bug

openpilot 0.8.16 installed but openpilot doesn't work. dashcam mode Car Unrecognized message is displayed.

### Provide a route where the issue occurs

dong id : 3eb4c34a2a663c37

### openpilot version

0.8.16

**Comment by sshane** [comment]
Can you put your device on wifi?

**Comment by lucasolivmed** [comment]
Now, its on wifi

> Can you put your device on wifi?

**Comment by sshane** [comment]
Solved by: https://github.com/commaai/openpilot/pull/25814
