### ISSUE TITLE
How to support Nissan leaf?

### ISSUE THREAD

**Issue by vusaalab** [commaai/openpilot#258]

**Comment by martinl** [comment]
Here are some pointers on how to get started with a new port:
https://medium.com/@comma_ai/a-panda-and-a-cabana-how-to-get-started-car-hacking-with-comma-ai-b5e46fae8646
https://medium.com/@energee/add-support-for-your-car-to-comma-ai-openpilot-3d2da8c12647
https://medium.com/@comma_ai/openpilot-port-guide-for-toyota-models-e5467f4b5fe6
