### ISSUE TITLE
switch to Poetry package manager

### ISSUE THREAD

**Issue by incognitojam** [commaai/openpilot#25828]
since Poetry 1.2 is [released](https://python-poetry.org/blog/announcing-poetry-1.2.0/) now and has things like dependency groups, it may be worth switching from pipenv for the much faster performance

**Comment by HaraldSchafer** [comment]
there is an old open PR if you want to finish it https://github.com/commaai/openpilot/pull/24858

**Comment by adeebshihadeh** [comment]
No need for an issue here, there's an open PR.

**Comment by incognitojam** [comment]
should have searched! my bad
