### ISSUE TITLE
Add Force Upload Toggle

### ISSUE THREAD

**Issue by devimauz** [commaai/openpilot#25836]
Should be good to add force upload toggle if network manager can't figure it out is it on metered or unmetered connection.
@adeebshihadeh @incognitojam 
![Screenshot_20220918-155744](https://user-images.githubusercontent.com/11072062/190929682-e6426b56-fa8d-4419-a642-04e47b8498d3.png)

**Comment by adeebshihadeh** [comment]
It's planned, see #23731
