### ISSUE TITLE
Mobile Data Saver

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#25886]
When using a self-owned SIM Card, Comma 3 is uploading all drives all the time in the background and uses lot of data.
It would be nice to have an option "Upload Videos only via WiFi". Then a SIM with a low data plan would be sufficient.

**Comment by adeebshihadeh** [comment]
We already minimize cell data usage for comma prime and only upload the low res logs on cell. If you’d like to upload less on cell, it’s fairly straightforward to make your own changes in the uploader.
