### ISSUE TITLE
Honda CR-V Car Unrecongnized error

### ISSUE THREAD

**Issue by Torreskai0722** [commaai/openpilot#25882]
### Describe the bug

I have used comma 3 on my Honda CR-V for severla months and it works well. Recently it shows error that the car is unrecognized. Sometimes I can resolve this error after unplug and plut the OBD adapter. Now it cannot work whatever I do.

### Which car does this affect?

Honda CR-V 2021

### Provide a route where the issue occurs

N/A

### openpilot version

0.9.16

### Additional info

![Photo of a comma three with a "Car Unrecognised" alert on the screen](https://user-images.githubusercontent.com/4038174/192081065-e8b5d0bf-d966-4d6e-91d6-69bd687ca80c.png)

**Comment by incognitojam** [comment]
Please provide your dongle ID so that it can be investigated

**Comment by sshane** [comment]
Can you provide your dongle id or route name? We can't look into this issue without any data

**Comment by sshane** [comment]
Any updates @Torreskai0722?

**Comment by Torreskai0722** [comment]
> Any updates @Torreskai0722?

Thanks for the reply. The issue is not resolved. The dongle id is 64fb2e43102e56d5.

**Comment by sshane** [comment]
It looks like your comma three isn't able to communicate with the comma power. I would try a new ethernet cable and comma power. Also try to reseat all connections

**Comment by sshane** [comment]
Any updates?

**Comment by sshane** [comment]
@Torreskai0722 it looks like you haven't driven since October, so I'll close this issue for now in case you've returned the C3. Please let us know if you are still struggling with this issue and we will re-open!

**Comment by Torreskai0722** [comment]
The former issue disappear but another issue comes out. When the comma 3 device is powered, there are strange sounds like marble hitting. I have attached a video for it.

https://user-images.githubusercontent.com/36166171/212577319-ce0ca18e-6266-4d66-a6de-1d24ba15a3a9.mp4

**Comment by sshane** [comment]
I would email support for that issue.

**Comment by Torreskai0722** [comment]
> I would email support for that issue.

Any update on that?

**Comment by sshane** [comment]
Did you email support?
