### ISSUE TITLE
My car sped up with stationary lead car in front

### ISSUE THREAD

**Issue by wongjunjin** [commaai/openpilot#2599]
I am not sure what happened. There was a stationary lead car in front of me (traffic lights) but my car just continuously drove towards it. I had to brake because it shows no indication of braking before it was too late.

**How to reproduce or log data**
Unsure.

**Expected behavior**
My car was supposed to slow down way earlier. 

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 7bc774bc8e17fd8a
 - Route: 7bc774bc8e17fd8a|2020-11-21--04-03-47
 - Timestamp: Nov 21@12:32:58
 - Version: 0.7.10
 - Car make/model: Toyota Corolla 2019

**Comment by pd0wm** [comment]
The lead car was detected just after you disengaged, at a distance of about 100 meters. At first the model thought the car was moving, when it was 90 meters out it fused with the radar point and correctly detected that it was stationary.

The situation with a stopped car between other car is a tricky situation, which should improve when we move more towards end-to-end longitudinal control. A human would slow down when approaching a traffic situation like this, irregardless if it already sees a stopped car in their lane or not.
