### ISSUE TITLE
Mobile web joystick performance improvement

### ISSUE THREAD

**Issue by ntegan1** [commaai/openpilot#25996]
use websockets for communicating with webserver instead of xhr

maybe turn into an installable pwa as well, wss:// sslcert

pwa allows for joystick/controller attached to iphone/android via bluetooth or lightning/usb adapter,  
until someone gets bluetooth on c3

**Comment by sxsmg** [comment]
Hey, can I take this up?

**Comment by adeebshihadeh** [comment]
Closing sine this isn't an issue, but feel free to make a PR.
