### ISSUE TITLE
Cabana Feature Request.

### ISSUE THREAD

**Issue by MoreTore** [commaai/openpilot#26123]
Feature Part 1: Add a textbox that I can type in a timestamp to go to. There should also be a button beside the textbox that says "Goto" or I can press return/enter key.

Feature Part 2: When I make a signal I want to be able see the timestamp where that signal changes. In it's simplest form I can imagine 2 buttons on each signal graph. One button could read "Prev Change" and "Next Change". When I press the buttons It would fill the textbox with the timestamp then I can press "Goto" btn when I am ready. I think it would be a good idea to think about how advance this feature could become.

Another level of complexity would be to goto next/prev timestamp where signal is ==, >, <  a value. The options could be selected with a dropdown list or a new window.

**Comment by adeebshihadeh** [comment]
New cabana is still under heavy development. Feedback should go in this discussion #26091
