### ISSUE TITLE
UI: watch3 segfault on WSL2 ubuntu 20

### ISSUE THREAD

**Issue by tecandrew** [commaai/openpilot#26144]
### Describe the bug

Freshly pulled and built openpilot. Attempted to run `./selfdrive/ui/watch3` to view a replay alongside plotjuggler's data causes a segfault. 

`ui` and `_ui` both encounter the same issue. `spinner` works just fine. 

### OS Version

Ubuntu 20.04.5 LTS WSL2

### openpilot version or commit

98cac3578b2d0d2e4db283a728f647bc71825bfb

**Comment by adeebshihadeh** [comment]
We don't target Windows, and `ui` especially is well tested on Ubuntu. If you can reproduce on Ubuntu, feel free to re-open.

**Comment by jyoung8607** [comment]
FYI there seem to be frequent/intermittent issues with WSL2 and many GUI apps not limited to openpilot. I myself have this trouble with UI and plotjuggler from time to time. Try launching as `LIBGL_ALWAYS_SOFTWARE=1 ./watch3`
