### ISSUE TITLE
kia seltos 2021

### ISSUE THREAD

**Issue by Alejoaguirre3a** [commaai/openpilot#26179]
### Describe the bug

I just received my open pilot comma ai 3 but doesn't recognized my car, my car was in the list so why i do have issues?
KIA SELTOS MODEL S 2021. commaai works only as a dash cam mode

### Which car does this affect?

KIA SELTOS S 2021

### Provide a route where the issue occurs

na

### openpilot version

updated

### Additional info

N/A

**Comment by sshane** [comment]
Can you provide your dongle ID? It's in device settings

**Comment by Alejoaguirre3a** [comment]
> Can you provide your dongle ID? It's in device settings

724f06bcdb81bc8e

**Comment by sshane** [comment]
I only see Kia Stinger routes in that dongle id, are you sure it's yours?

**Comment by Alejoaguirre3a** [comment]
Yes it is I bought it to used in two cars. the kia stinger doesn't have a problem.but when i connected to the kia seltos  2021 does not work. 
    On Friday, October 21, 2022 at 11:48:09 AM PDT, Shane Smiskol ***@***.***> wrote:  
 
 


I only see Kia Stinger routes in that dongle id, are you sure it's yours?

**Comment by Alejoaguirre3a** [comment]
![20220921_204019](https://user-images.githubusercontent.com/116313673/197271643-d6196699-6410-400e-a6c9-a662c0ee9231.jpg)
![20220921_211742](https://user-images.githubusercontent.com/116313673/197271679-f98b7d14-38c7-4d27-ad1c-786ca0511f4d.jpg)
![thumbnail (1)](https://user-images.githubusercontent.com/116313673/197271705-f083a99a-5448-4465-96b3-0fe85ba944e5.jpg)

this are the pictures to show you the messages from the comma ai screen .

**Comment by sshane** [comment]
It's not showing up in useradmin for some reason. Make sure to plug it into the Seltos, and turn the car on for a few minutes to ensure the C3 saves the route

**Comment by Alejoaguirre3a** [comment]
Ok will do!

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 21, 2022 at 12:31 PM, Shane ***@***.***> wrote:   


It's not showing up in useradmin for some reason. Make sure to plug it into the Seltos, and turn the car on for a few minutes to ensure the C3 saves the route

**Comment by sshane** [comment]
I see some routes from last month now, it looks like your radar isn't responding (even to tester present). Do you happen to know if your car lacks a radar?

**Comment by sshane** [comment]
From your VIN, it looks like you have a series S. In that case, only the SX has Smart Cruise Control w/ Stop and Go: https://cdn.dealereprocess.org/cdn/brochures/kia/2021-seltos.pdf

You can try a fork to add LKAS to this car, however we cannot support it upstream if it does not have a radar, nor adaptive cruise control.

**Comment by sshane** [comment]
Added your Stinger's FP: https://github.com/commaai/openpilot/pull/26198

**Comment by Alejoaguirre3a** [comment]
> From your VIN, it looks like you have a series S. In that case, only the SX has Smart Cruise Control w/ Stop and Go: https://cdn.dealereprocess.org/cdn/brochures/kia/2021-seltos.pdf
> 
> You can try a fork to add LKAS to this car, however we cannot support it upstream if it does not have adaptive cruise control. Let me know if you do actually have SCC and I can take a look at this again

I just connected.  My car have cruise control and line assistance as well.  If I get to a stop I have to stop the car my self and then hit the gas to keep moving.  So I don't have stop and go I guess.  ![20221021_131609.jpg](https://user-images.githubusercontent.com/116313673/197281456-ba613c24-45e2-494a-a0c3-9d801a792ef4.jpg)

Thanks

**Comment by sshane** [comment]
Requested upload, can you put the device online? Does your car actively brake for cars, or is it just normal cruise control? I don't see a distance setting.

**Comment by Alejoaguirre3a** [comment]
No it doesn't break for cars, only gives me a sound alert.

**Comment by sshane** [comment]
Yep, that means you don't have Smart Cruise Control which is a pre-requisite. Again, forks may offer what you're looking for.
