### ISSUE TITLE
install openpilot on EON screen upside down

### ISSUE THREAD

**Issue by kmacpher67** [commaai/openpilot#262]
attempted upgrade of EON from chffrPlus to openpilot. 
1> uninstalled 
2> selected local WIFI end point
3> typed in:  openpilot.commai.ai
4> screen flashed old school characters and was inverted visually but screen touch was still the original way

**Comment by kmacpher67** [comment]
https://photos.app.goo.gl/xArGsTrFGiumXGDp8

**Comment by mtourangeau** [comment]
That’s normal.

**Comment by kmacpher67** [comment]
It's unusable.  I can't even touch the spot on the screen where the text is. 
The tactile input is inverted from the display output.  That's normal? 
The system is unusable have you ever tried to figure out where to click when the output is upside down from the input?

**Comment by energee** [comment]
This is a known bug, you can fix it from an ssh session with the following command:

`LD_LIBRARY_PATH="" content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:1`

**Comment by jfrux** [comment]
Known bug, is there a way to fix it in code?  Just curious.

**Comment by geohot** [comment]
0.4.7 should run that command automatically. We need to flip the installer too, will close this when we do.

**Comment by geohot** [comment]
Fixed

**Comment by kmacpher67** [comment]
is `0.4.7` pushed to the `https://openpilot.comma.ai` latest? 
I just tried reloading: it's still upside down. 
---
was able to ssh into the system using this: 
https://medium.com/@jfrux/comma-eon-getting-connected-with-ssh-3ed6136e4a75
great doc, easy to follow. 
-----
```
total 0
root@localhost:/system/comma/home$ LD_LIBRARY_PATH="" content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:1
root@localhost:/system/comma/home$ 
```

**Comment by kmacpher67** [comment]
Version 
0.5-release
Branch
release2

**Comment by bugsy924** [comment]
0.5 is supposed to have the inward facing camera to the left of the screen

**Comment by kmacpher67** [comment]
So my older model plastic case is nolonger valid.
There is a switch in the default geometry.
Thank you, @bugsy924 .
