### ISSUE TITLE
2020 Ioniq EV safety issue

### ISSUE THREAD

**Issue by KorayZ** [commaai/openpilot#2620]
TLDR: 32mph warning displays, blocking out other warnings and displays, but car can steer below 32.

When driving @40mph or lower, the device displays a warning "Cannot steer below 32mph" which takes up most of the screen. When this is active, no other safety warnings can display over it, potentially AEB warnings in extreme cases. I put in a PR including this, but it never went through. The 2020 Ioniq (ev anyway) is capable of driving below 32mph with steering, all the way down to zero, so I'm not sure why this warning even shows up

**Comment by geohot** [comment]
This is not a safety issue, this is a message on the HUD. Please don't label things like this safety issues, it cheapens the term for real safety issues that involve violations of our safety model.

The Ioniq EV is a community supported car. If you'd like it fixed, we be happy to merge a clean, well tested, PR.
