### ISSUE TITLE
Comma 3 random restart during drive

### ISSUE THREAD

**Issue by JamesL6** [commaai/openpilot#26214]
### Describe the bug

Toward the end of my drive, the Comma 3 randomly restarted, errors were thrown on my dash, then the Comma 3 turned back on, and the dash errors went away. This was all happening while driving.

Car: 2022 Camry Hybrid XSE

Version: Master 0.8.17

Device: Comma 3

### Provide a route where the issue occurs

76fcc86c5aa85c45|2022-10-21--22-19-07--10

### openpilot version

Master - 0.8.17

**Comment by adeebshihadeh** [comment]
Thanks for the report. Unfortunately, this is a case of #24302. It's a rare crash, but if it happens again, you can try re-seating the NVMe.

**Comment by JamesL6** [comment]
Thank you @adeebshihadeh

**Comment by JamesL6** [comment]
C3 froze and rebooted again mid drive

76fcc86c5aa85c45|2022-11-04--21-09-42--6
