### ISSUE TITLE
CI: e2e tests with CARLA

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#26215]
An extension of `selfdrive/test/test_onroad.py` that also tests driving behavior. Let's start with a few simple test cases: driving straight, stopping behind a lead, and resuming from a stop after lead moves.

**Comment by jon-chuang** [comment]
Hi, I'm interested. Could I be assigned this?

**Comment by jon-chuang** [comment]
I'm thinking that a cheaper simulator e.g. one of those suggested in https://github.com/commaai/openpilot/issues/27284 could be more suitable. What do you think?

**Comment by adeebshihadeh** [comment]
Yeah, I think whatever we get out of #27284 will be the new default simulator. CARLA will probably remain as the "higher end" one.

**Comment by adeebshihadeh** [comment]
No more CARLA
