### ISSUE TITLE
No barcode two pair a new device

### ISSUE THREAD

**Issue by Jameselectronis** [commaai/openpilot#26262]
### Describe the bug

Hi everyone I'm having problem with my comma , too is not showing barcode in order to pair the device. Any help or advice would be much appreciated
![20221026_202315](https://user-images.githubusercontent.com/116784972/198235025-0d4219fa-9ca7-471c-8e63-7acfd752d737.jpg)

### Provide a route where the issue occurs

When trying to install

### openpilot version

0.8.13.1

### Additional info

Hi everyone I'm having problem with my comma , too is not showing barcode in order to pair the device. Any help or advice would be much appreciated
![20221026_202315](https://user-images.githubusercontent.com/116784972/198235025-0d4219fa-9ca7-471c-8e63-7acfd752d737.jpg)

**Comment by Jameselectronis** [comment]
![20221027_070740](https://user-images.githubusercontent.com/116784972/198280614-94efdd07-4f60-46f7-b19b-b9c524dc1dc2.jpg)
Here is the whole thing

**Comment by vanillagorillaa** [comment]
Devices that are already paired do not show the QR code. This device is either paired to your own account already, or if you bought it used, paired to the previous owners account.

**Comment by vanillagorillaa** [comment]
Reading the linked PR, you purchased this from Ebay, which means this device is likely still paired to previous owner. You will need to get in touch with them and have them unpair it from their account.
