### ISSUE TITLE
UI - Yellow lead indicator isn't in Golf

### ISSUE THREAD

**Issue by dingyf12593** [commaai/openpilot#2628]
0.7.10 and 0.8.0  Never shown  Yellow lead indicator

 - Device: [EON Gold]
 - Dongle ID: [3f84146622df5f39]
 - Version: [0.8.0]
 - Car make/model: [ golf 7.5 2018]

**Comment by pd0wm** [comment]
Openpilot doesn't control longitudinal control on VW, so we don't show the lead indicator to prevent confusion. Openpilot could see a lead that the car's ACC doesn't and it won't stop for it.

**Comment by dingyf12593** [comment]
Is there any hope of support ？ 😄
