### ISSUE TITLE
Change Branch UI Not Working

### ISSUE THREAD

**Issue by tecandrew** [commaai/openpilot#26314]
### Describe the bug

Changing branches using the UI menu, after a fresh pull of a branch, causes an incomplete build. Upon pressing "Install" after "Download" of the branch causes the Comma3 device to get stuck on the Logo upon reboot.

Relevant info when SSH'ing onto the device while stuck on boot logo.

```
comma@tici:/data/openpilot$ git status
On branch h90d-3-frames
Your branch is up to date with 'origin/h90d-3-frames'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   body (modified content, untracked content)
	modified:   cereal (modified content, untracked content)
	modified:   opendbc (modified content, untracked content)
	modified:   panda (modified content, untracked content)
	modified:   tinygrad_repo (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
comma@tici:/data/openpilot$ git branch -v
* h90d-3-frames dc01ebe75 3 frames
  master-ci     8faa84833 openpilot v0.8.17 release
```

TMUX session information

```
Waiting for wayland
wayland ready
adjusting time from '2022-08-31 08:27:50.024705' to '2022-11-01 21:58:49'
Tue 01 Nov 2022 09:58:49 PM UTC
INFO:root:System time valid
Traceback (most recent call last):
  File "./build.py", line 8, in <module>
    from common.basedir import BASEDIR
  File "/data/openpilot/common/basedir.py", line 4, in <module>
    from system.hardware import PC
  File "/data/openpilot/system/hardware/__init__.py", line 4, in <module>
    from system.hardware.base import HardwareBase
  File "/data/openpilot/system/hardware/base.py", line 5, in <module>
    from cereal import log
ImportError: cannot import name 'log' from 'cereal' (unknown location)
```

### Provide a route where the issue occurs

eb5a50f9e98f50b9

### openpilot version

0.8.17-master-ci

### Additional info

Steps taken to produce bug:

1. Fresh clone of OP using a specific branch

`git clone https://github.com/commaai/openpilot.git --branch h90d-3-frames --recurse-submodules`

2. Built OP manually and rebooted device
3. Drove with OP to test
4. Change to `master-ci` using UI menu
5. Download & Install (using buttons on UI)
6. Drive with OP to test
7. Change back to original branch `h90d-3-frames` using UI menu
8. Download & Install (using buttons on UI)
9. Stuck on boot logo

Bootlog (`.bz2`) can be provided if needed. `bootlogs/eb5a50f9e98f50b9/2022-11-01--12-17-02.bz2`

**Comment by incognitojam** [comment]
I can also reproduce this by cloning `master`, switching to `master-ci`, and then switching back to `master` fails (the submodule directories are empty).
