### ISSUE TITLE
updated: use Qt::MarkdownText format instead of rendering markdown

### ISSUE THREAD

**Issue by incognitojam** [commaai/openpilot#26332]
We can probably get rid of the MarkdownIt library if Qt can render the markdown for us

https://github.com/commaai/openpilot/blob/master/selfdrive/updated.py#L71
https://doc.qt.io/qt-5/qt.html#TextFormat-enum

**Comment by adeebshihadeh** [comment]
I don't think we have that in our Qt version.

**Comment by incognitojam** [comment]
oh, I saw qt5 but didn't realise it was only added in qt5.14

**Comment by adeebshihadeh** [comment]
Let's close if our Qt is too old.

**Comment by incognitojam** [comment]
I think we have 5.12
