### ISSUE TITLE
Communication issue between processes due to frame drop

### ISSUE THREAD

**Issue by adam-nelson** [commaai/openpilot#2636]
**Describe the bug**

Driving on 3 hour journey using Toyota
Corolla hybrid 2019 and comma two got error message. Communication issue between processes

Was able to reengage after two mins

**How to reproduce or log data**
The issue is random:

https://my.comma.ai/18e8ac91b805db11/1606449645457/1606454798869

**Expected behavior**

No disengagement or error between processes

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: 18e8ac91b805db11
 - Route: https://my.comma.ai/18e8ac91b805db11/1606449645457/1606454798869
 - Timestamp: Fri, 27 Nov, 2020 @ 15:03
 - Version: master-ci 0.8.0
 - Car make/model: Toyota Corolla hybrid 2019 accent sport￼

**Additional context**

https://my.comma.ai/18e8ac91b805db11/1606449645457/1606454798869

**Comment by pd0wm** [comment]
The model frame drop percentage was over 5% which caused the model packet to become invalid. I'll probably remove this check since we check in other places too.
