### ISSUE TITLE
Eon Gold Devkit "Getting Started" Loop

### ISSUE THREAD

**Issue by matluvhonda** [commaai/openpilot#26402]
### Describe the bug

Backstory:
I have a comma eon Gold devkit, and have had it for several years now (bought new in 2019, I think). I've had it in my 2018 Honda Accord. It hasn't been updated in probably a year or two. A couple weeks ago, I purchased a 2022 Honda Civic Si, so the eon finally came in the house and I decided to update it and see what I needed to do to get it into the new civic. Started by tearing apart the rear view mirror area of the car to get a look at the lkas system. Looks like it's the same connector as my 18 accord (not sure if this helps anyone), but I couldn't get the panda plugged in to the lkas while it was mounted without altering the headliner of the car (the lkas is too close to the headliner and the panda is too large to fit). So, I came inside and decided to start updating the device while I look online to see if anyone has a solution to this problem yet. 

The Issue:
Updated the device, and now it's stuck on the "getting started" screen (see attached image). When I click the "Continue to Setup" button, it takes me to the page where I can select to use as dashcam, or download software. If I click to download software, I can input the URL ( I used openpilot.comma.ai per the instructions from virtuallyChris), then it loads for about 3 seconds, restarts the device and takes me back to the "Getting started" page. I also tried the "use as dashcam" option, and after selecting that, it does the exact same thing... Right back to the "Getting Started" page. 

Any help with getting the eon up and running again is greatly appreciated. Also, any help getting this installed in the new civic is extremely appreciated!

### Provide a route where the issue occurs

N/A

### openpilot version

0

### Additional info

Cannot provide a route or openpilot version as it is stuck in the "Getting Started" loop.

**Comment by adeebshihadeh** [comment]
The EON is no longer supported. Check out the community discord for hlep.
