### ISSUE TITLE
Honda wheel shaking

### ISSUE THREAD

**Issue by rm-baugh** [commaai/openpilot#26447]
### Describe the bug

The lines when you are in 0.8.17 are constantly shaking and the wheel will shake and jitter as well. 

I hope this router show it if not I can provide video recording as well as this is a constant thing

### Provide a route where the issue occurs

`f52e6599c4b36bbf|2022-11-10--09-33-15`

### openpilot version

[`master-ci / bd47818 / 0.8.17`](https://github.com/commaai/openpilot/commit/bd47818f424302a1ba88028a99a8153dcd7853c8)

**Comment by adeebshihadeh** [comment]
Some fixes for honda were merged today. They improve our Hondas. Can you try out latest master or master-ci?

**Comment by adeebshihadeh** [comment]
Closing, but feel free to reopen if you still have issues.
