### ISSUE TITLE
Open Pilot Master-ci detected on coming traffic as traffic ahead and braked 

### ISSUE THREAD

**Issue by joelegg** [commaai/openpilot#26459]
### Describe the bug

Coming down a hill - open pilot (master-ci) saw on coming traffic on the right (i'm in Australia) as traffic in front and started to brake. 

https://useradmin.comma.ai/logs?url=https%3A%2F%2Fcommadata2.blob.core.windows.net%2Fqlog%2Fdc25f84f7b307cc9%2F2022-11-11--09-42-41%2F2%2Fqlog.bz2%3Fse%3D2022-11-11T00%253A22%253A12Z%26sp%3Dr%26sv%3D2018-03-28%26sr%3Db%26rscd%3Dattachment%253B%2520filename%253Ddc25f84f7b307cc9_2022-11-11--09-42-41--2--qlog.bz2%26sig%3D0MtipOjGxWuMTQJGTLqbeMlhevpPoiPnv%2FzcmLf7VRs%253D

occurs approx 35 seconds into this segment

### Provide a route where the issue occurs

dc25f84f7b307cc9|2022-11-11--09-42-41

### openpilot version

master-ci

**Comment by incognitojam** [comment]
GitHub isn't the best place for this kind of issue to be reported and tracked, if you have more driving feedback please check out #start-here on discord and submit the route IDs using the form
