### ISSUE TITLE
If your HKG car isn't supported or doesn't work with stock openpilot, comment your model and dongle ID here. We'll work to get support for these cars in upstream openpilot.

### ISSUE THREAD

**Issue by max2020201** [commaai/openpilot#2645]
If your HKG car isn't supported or doesn't work with stock openpilot, comment your model and dongle ID here. We'll work to get support for these cars in upstream openpilot.

_Originally posted by @adeebshihadeh in https://github.com/commaai/openpilot/discussions/2401_

**Comment by max2020201** [comment]
Dongle ID
a3b2d141e497235d
And my car is 2017 Hyundai Santa Fe sport Ultimate 2.0T I need fingerprint to this car 
And new update 0.8 com out and my car still car unrecognized please help me

**Comment by adeebshihadeh** [comment]
Comment on the GitHub discussion instead of opening an issue
