### ISSUE TITLE
Wide camera display shifts to the right

### ISSUE THREAD

**Issue by oremax** [commaai/openpilot#26457]
### Describe the bug

When I tried it on 0.8.17 master-ci
The wide camera display shifts to the right.
Just driving is no problem.
It's a display issue only.

The display with the normal camera is working normally without any problems.

What caused this issue
Camera calibration → NG
UNINSTALL recovery → NG

At low speeds, it is always off, so
I want to turn off the automatic change to the wide camera.

Device used
C3

car
PRIUSPRIME2021

UI that shows roads and lanes are always misaligned
https://drive.google.com/file/d/1TkaQxpPOIsvm4RbiWbLx93m392j8nR2t/view?usp=share_link

### Provide a route where the issue occurs

516d6c3bd3ce6315|2022-11-08--07-35-14--2

### openpilot version

0.8.17 master-ci

**Comment by adeebshihadeh** [comment]
All your routes are on forks. If you can reproduce on stock master-ci, feel free to re-open.

**Comment by oremax** [comment]
commaai
release3-staging
Version 0.9.0 (2022-11-21)

Wherever you use the wide camera, it is always shifted to the right.

516d6c3bd3ce6315|2022-11-19--08-02-57--0
516d6c3bd3ce6315|2022-11-19--08-02-57--0

https://youtu.be/YGnTI0NCjIA

Is it a hardware problem?
