### ISSUE TITLE
[Bug] OpenPilot performs software update automatically while driving

### ISSUE THREAD

**Issue by VenomrushCT** [commaai/openpilot#2646]
Bug reported on Discord: https://discord.com/channels/469524606043160576/524328425415245827/782450439224295504

Ideally, OpenPilot should check the following before performing automatic update:

1. Vehicle speed is 0
2. Vehicle is in park
3. Countdown prompt of X seconds before executing automatic update (optional)

**Comment by adeebshihadeh** [comment]
The updater only runs while ignition is low, and the update is only performed on reboot. When an update is ready, an alert will show with the release notes and version number.
