### ISSUE TITLE
Car unrecognized 

### ISSUE THREAD

**Issue by ianstuppel** [commaai/openpilot#26487]
### Describe the bug

Car unrecognized dashcam mode only with stable latest release.  Will only recognize car with master-ci.

### Which car does this affect?

Hyundai santa fe phev 2022

### Provide a route where the issue occurs

4e77fe0c3543bda2

### openpilot version

Master-ci 0.8.17

**Comment by nelsonjchen** [comment]
Nothing to really do here, a new stable release should come out soon with support for that car around the 21st.

https://github.com/commaai/openpilot/blob/master/RELEASES.md#version-0817-2022-11-21
