### ISSUE TITLE
Carla simulation not available in Openpilot UI

### ISSUE THREAD

**Issue by franco126** [commaai/openpilot#26503]
### Describe the bug

When I run the simulation on PC, Carla "interface" in Openpilot UI is not shown. 
So I can't see car or road.
![Schermata del 2022-11-15 13-21-13](https://user-images.githubusercontent.com/51539908/201918862-e3574c17-a060-4c33-bc22-927366841b56.png)
When I press 1 in bridge.py shell, it says "Openpilot available press set to engage. 
In launch_openpilot.sh shell seems to be everything ok.
Even if I run in docker container, I get the same issue
Here some screenshot...
![Schermata del 2022-11-15 13-26-40](https://user-images.githubusercontent.com/51539908/201919587-1305f1f3-e65e-424c-aa54-10ed1035e908.png)
![Schermata del 2022-11-15 13-27-01](https://user-images.githubusercontent.com/51539908/201919591-b51260bf-6736-4302-a99f-462dc932f65f.png)

### OS Version

Ubuntu 20.04

### Steps to reproduce

- Terminal 1: run CARLA (not docker version)
- Terminal 2: poetry shell - cd /tools/sim - ./launch_openpilot.sh
- Terminal 3: poetry shell - cd tools/sim - ./bridge.py

**Comment by Ruishenl** [comment]
I ran into the exact same issue. I am on Ubuntu22

**Comment by eli-davis** [comment]
same issue, ubuntu 20, followed all directions...doesnt show up on ui

**Comment by jbeck9** [comment]
Same. Openpilot seems to run normally, just nothing on the UI. This is running Carla and OpenPilot through the Docker images for me.

I'm guessing it is related to #26169, but that is just a guess.

**Comment by didpurwanto** [comment]
Same here. Carla is working fine but the bridge in 0.9.0 version has nothing.

**Comment by joeking11829** [comment]
Same issue here.

**Comment by fatsheep2020** [comment]
same issue here

**Comment by didpurwanto** [comment]
Any updates about this?
In my case rn, I can see the future trajectory, but cannot load the images from Carla.

**Comment by ebadi** [comment]
> Same. Openpilot seems to run normally, just nothing on the UI. This is running Carla and OpenPilot through the Docker images for me.

> same issue, ubuntu 20, followed all directions...doesnt show up on ui

@jbeck9 and @eli-davis, how do you know that openpilot is working?

For me OP seems not to be **fully** engaged after I press `1`. 
![image](https://user-images.githubusercontent.com/1111940/207285853-46c02657-2ec3-42d8-aee6-eddb4d9e4775.png)

**Comment by ebadi** [comment]
Passing ` --high_quality --dual_camera` to `bridge.py` solved the camera issue for me. The vehicle is still not moving with my interference using `WASD` .

![image](https://user-images.githubusercontent.com/1111940/207360569-59c6bb0e-1077-4cb8-a1ac-c3319cea144c.png)

**Comment by didpurwanto** [comment]
@ebadi try press 1, then press 2 (twice), then click multiple times at the screen. In my case, I will get the trajectory by doing this.

Also me, after rebuild again. I got like yours too.
![Screenshot from 2022-12-14 09-36-02](https://user-images.githubusercontent.com/8987946/207483572-ebfc249f-2c75-495d-96eb-396d0ae4ca29.png)

**Comment by didpurwanto** [comment]
@ebadi I also got this too. But, there is no future trajectory.

**Comment by didpurwanto** [comment]
@ebadi same here.
![Screenshot from 2022-12-14 09-58-42](https://user-images.githubusercontent.com/8987946/207486473-82311230-4b0b-4420-aeca-ce943c8f572b.png)

**Comment by Ruishenl** [comment]
I tried with the latest Docker Image again on master branch, but the UI  now doesn't  even change to the running mode, it stays at the home page. Is there a way we can rebuild the docker image on our own ?

**Comment by didpurwanto** [comment]
Check opencv2, mine is missing
ImportError: libnppc.so.11: cannot open shared object file: No such file or directory
@ebadi

**Comment by ebadi** [comment]
[didpurwanto](https://github.com/didpurwanto) Please check this bug report and workaround (reinstalling `opencv-python-headless`) here #26786

**Comment by zeroyang0809** [comment]
hello i meet the problem "openpilot unavailable waiting for controls to start"
this problem is familiar with your problem
do you know how to fix it ?
thx

**Comment by adeebshihadeh** [comment]
Fixed with d5375af2f5c9f74cb88ffa1ab52feb9fef77a43c
