### ISSUE TITLE
Openpilot crossed double yellow lines at night while gradually turning to the left at 55 mph

### ISSUE THREAD

**Issue by Rav42020** [commaai/openpilot#2652]
**Describe the bug**
While testing ver 8.0, Openpilot crossed double yellow lines at night while gradually turning to the left at 55 mph - 7.10 did not do this.

**How to reproduce or log data**

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [Comma 2]
 - Dongle ID: [ c76c4478eb02d483]
 - Route: [ c76c4478eb02d483 2020-11-29–06-23-08]
 - Timestamp: [Chk route at 6:37:06]
 - Version: [commit hash when on a non-release branch, or version number when on devel or release2 (e.g. 0.7.6)]
 - Car make/model: [e.g. Toyota Rav 4 2020]

**Additional context**

**Comment by HaraldSchafer** [comment]
same as https://github.com/commaai/openpilot/issues/2361
