### ISSUE TITLE
Where is camera_webcam.cc? How to change the cameras id?

### ISSUE THREAD

**Issue by Torch-HXM** [commaai/openpilot#26545]
### Describe the bug

I want to test it on my laptop,but the camera of my laptop can not be recognized.So I want use two webcams,but only one of them which is used to monitor the driver's face can be recognized,I want to change the ids of the camera in the program,but can not find camera_webcam.cc which is used to change the camera's id in the past versions.What should I do? 

### OS Version

ubuntu 20.04

**Comment by adeebshihadeh** [comment]
See #24590
