### ISSUE TITLE
2020 Honda Accord Hybrid Camera Malfunction

### ISSUE THREAD

**Issue by forenzo24** [commaai/openpilot#26572]
### Describe the bug

![27D5AA3F-8EF8-4533-94B0-E52CF914ED22](https://user-images.githubusercontent.com/118789664/203217820-3f30c552-1fa6-4847-8741-33b5572ff243.jpeg)

![02768DD1-D4E4-447E-92C5-1F184BEE778B](https://user-images.githubusercontent.com/118789664/203217836-dacfa02f-78ca-4094-865d-903bfc0f02c9.jpeg)

Camera Malfunction: roadCamera, driverCamera, wideRoadCamera

I used master-ci on my 2020 accord hybrid as of 10-21-2022 around 7PM PST and it was running fine, but today 10-22-2022, after updating around 6PM PST, this issue happened

### Which car does this affect?

Honda Accord Hybrid 2020

### Provide a route where the issue occurs

https://installer.comma.ai/commaai/master-ci

### openpilot version

fd0ed57

**Comment by adeebshihadeh** [comment]
c0c94b4961e8e32c3f8dbcfed2b7d91c28000085
