### ISSUE TITLE
Hyundai: 2023 Palisade port support

### ISSUE THREAD

**Issue by alancyau** [commaai/openpilot#26571]
The 2023 Hyundai Palisade is a mid-cycle refresh and has added CAN-FD. Therefore, a fingerprint update of `CAR.PALISADE` won't work. 

Note that SEL trim with Premium Package and higher adds HDA2. SE and XRT trims retain HDA.

![image](https://user-images.githubusercontent.com/59986772/203218968-46160474-a86f-4821-9004-9be49f24ac26.png)

![image](https://user-images.githubusercontent.com/59986772/203219145-2b107d2a-c2a7-4da4-9553-6f8905a3d971.png)

**Route Logs:**
The Hyundai Harness A was used. It's unclear if the pins need to be swapped based on the updates to the car. Both the stock A and swapped pins logs were uploaded.

Stock Harness A route:
28aa956828c3407d|2022-11-21--22-40-37--0

Swapped pins route:
28aa956828c3407d|2022-11-21--23-04-42--0

Pins swapped per this picture
![image](https://user-images.githubusercontent.com/59986772/203213220-4f2b1c11-4472-4d14-b502-61ef86feec1b.png)

Once we figure out the proper harness, it appears there's still some CAN decoding to do per @sunnyhaibin 

> sunnyhaibin — 11/08/2022 9:12 AM
> Yep, still the same with the SCC and LKAS11 messages, different definitions to the ones already have now. There's a possibility that the ADAD driving unit can be ignored, but won't know yet. 
> I'll ask comma and see what's the approach on this, it's gonna be messy and a long process. 
> Yumy — 11/08/2022 9:15 AM
> Can you explain a little bit what you see and what's different from other Hyundai cars?
> sunnyhaibin — 11/08/2022 9:15 AM
> Signals don't make sense with the current DBC (hyundai_kia_generic.dbc) 
> Yumy — 11/08/2022 9:17 AM
> Got it, is there anything else to do in the meantime?
> sunnyhaibin — 11/08/2022 9:17 AM
> If you are inclined, you could reverse engineer and start understanding what the bits mean in the applicable messages in cabana.
> https://connect.comma.ai/, cabana to get started
> My project stack is quite full and won't be able to reverse engineer those messages, especially when I don't have access to the actual car 😦 
> Seems like those messages are the ones to deal with, but won't know until they can be confirmed.

**Comment by kjanoudi** [comment]
Any updates on the 2023 telluride?

**Comment by kjanoudi** [comment]
There is now a GoFundMe set up to get this working: https://gofund.me/74d1b155 
See discord channel here for most recent updates: https://discord.com/channels/469524606043160576/1016709312602706031/1066817559602671666

**Comment by adeebshihadeh** [comment]
Closing since the PR is open.
