### ISSUE TITLE
Wide camera display shifts to the right

### ISSUE THREAD

**Issue by oremax** [commaai/openpilot#26593]
### Describe the bug

The wide camera display shifts to the right.
Just driving is no problem.

commaai
release3-staging
Version 0.9.0 (2022-11-21)

Wherever you use the wide camera, it is always shifted to the right.

516d6c3bd3ce6315|2022-11-19--08-02-57--0
516d6c3bd3ce6315|2022-11-19--08-02-57--0

https://youtu.be/YGnTI0NCjIA

Is it a hardware problem?

### Provide a route where the issue occurs

516d6c3bd3ce6315|2022-11-19--08-02-57--0

### openpilot version

0.9.0

### Additional info

https://youtu.be/YGnTI0NCjIA

**Comment by vanillagorillaa** [comment]
@oremax Please email support@comma.ai and we will get this device replaced for you.
