### ISSUE TITLE
Carla Openpilot Not Working with the latest docker image

### ISSUE THREAD

**Issue by Ruishenl** [commaai/openpilot#26595]
### Describe the bug

I am following the instruction to get the carla-openpilot integration working, but the dashboard doesn't seem to render the carla world. I am able to pass my keyboard input to engage openpilot but got Openpilot Unavailable message:
![Screenshot from 2022-11-22 16-31-08](https://user-images.githubusercontent.com/22068468/203853198-c31db90d-be7a-4a3f-963d-862b6456466d.png)

Carla seems to be having memory error as well but no sure if it's related : 
`Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
./CarlaUE4.sh: line 5:    13 Segmentation fault      (core dumped) "$UE4_PROJECT_ROOT/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping" CarlaUE4 "$@`

Steps to reproduce:
Terminal 1
./start_carla.sh

Terminal 2 
./start_openpilot_docker.sh

Terminal 3:
docker exec -it OPENPILOT_CONTAINER_ID /bin/bash
./launch_openpilot.sh

Terminal 4
docker exec -it OPENPILOT_CONTAINER_ID /bin/bash
./bridge.py

### OS Version

Pop!_OS 22.04

### openpilot version or commit

b15018387c774b9f470e88f22b96861d62917656

### Additional info

I also have a warning message showing the current branch is not tested. Am i supposed to use a released tag instead ?
Also tried running the integration_tests in the container but failed

**Comment by fatsheep2020** [comment]
@incognitojam  do it simulator issue? anddo you know how to fix it, as i knew, it work well before....
thanks a lot!

**Comment by incognitojam** [comment]
This is the same issue as #26503

**Comment by zeroyang0809** [comment]
hello do you fix this problem? could you show solutions to fix it? 
thanks
