### ISSUE TITLE
Simulation error

### ISSUE THREAD

**Issue by Torch-HXM** [commaai/openpilot#26600]
### Describe the bug

I have followed the instruction in the tools\sim\README.md.But I got some errors.

**### 1. start_carla.sh**
![q](https://user-images.githubusercontent.com/88866541/203957025-c0605e34-234a-449b-9367-4f86dbeaafc0.png)
**### 2. start_openpilot_docker.sh**
**(1) ./bridge.py**
![w](https://user-images.githubusercontent.com/88866541/203957255-c52399e1-f6e8-4b50-9911-78388cf48396.png)
**(2) ./launch_openpilot.sh**
![e](https://user-images.githubusercontent.com/88866541/203957364-83a56d31-dff2-4aab-8630-bc902f68c74a.png)
**### 3. ui**
![r](https://user-images.githubusercontent.com/88866541/203959885-123d44e6-7cf3-4b47-8075-b718466b9365.png)

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Check out our [Discord](https://discord.comma.ai) or GitHub Discussions for getting started.
