### ISSUE TITLE
openpilot oversteer during curve

### ISSUE THREAD

**Issue by MJR1989** [commaai/openpilot#26657]
### Describe the bug

Car crossed halfway into next lane at approximately 35 mph in a curve

### Provide a route where the issue occurs

b0a7a22dea55a1cd|2022-12-01--10-19-51--7

### openpilot version

0.9.0

### Additional info

```
'carFingerprint': 'TOYOTA COROLLA HYBRID TSS2 2019',

'gitBranch': 'release3',
'gitCommit': 'da5d08d5f8eabc2e6862bdb611ea01f3a1ab959d',
```

**Comment by incognitojam** [comment]
Looks like the actual lateral accel overshot what openpilot wanted here for about 2.5 seconds
![Screenshot from 2022-12-01 20-44-38](https://user-images.githubusercontent.com/4038174/205216634-a30a2f73-b431-4be0-9023-e6de3cc1e6e8.png)

**Comment by MJR1989** [comment]
> Looks like the actual lateral accel overshot what openpilot wanted here for about 3-4 seconds
> 
> ![Screenshot from 2022-12-01 20-44-38](https://user-images.githubusercontent.com/4038174/205216634-a30a2f73-b431-4be0-9023-e6de3cc1e6e8.png)
> 
> 
> 
> 

I've had a lot of issues since 0.9.0 came out with oversteer normally it's not so dramatic normally it's either the inside tire riding the line like a rail at slower speeds or coming within inches of the lane line at highway speeds idk what causes this hopefully someone way smarter than me can fix it 😅

**Comment by sshane** [comment]
@nuwandavek have you looked into this? Friction too high?

**Comment by adeebshihadeh** [comment]
Thanks for the report. Please post future driving feedback in the #driving-feedback channel on Discord.
