### ISSUE TITLE
I want to make Yaris compatible with open pilot

### ISSUE THREAD

**Issue by gonzalles125** [commaai/openpilot#26688]
### Describe the bug

Openpilotは私のヤリスでは機能しません。認識するために改善したいのですが、よろしくお願いします。

### Provide a route where the issue occurs

02bdabbbfec5a8af

### openpilot version

0.8.1.3

**Comment by vanillagorillaa** [comment]
This isn't a bug. For adding new vehicle support, please see our community discord, discord.comma.ai ,where users there can assist you
