### ISSUE TITLE
Steering bug: Steering stops working at very low speeds in experimental mode.

### ISSUE THREAD

**Issue by dukeajuke** [commaai/openpilot#26694]
### Describe the bug

2022 Arteon in experimental mode:

When at very low speeds or often stopping for a stop sign or another car, Openpilot displays a warning "Steering temporarily unavailable" and won't start working again even at higher speeds until the device is rebooted. At the same time, my car displays the message "Take control of the wheel" like it used to with my stock lane keeping. 

### Provide a route where the issue occurs

`200d2fe234e1fef3|2022-12-03--18-50-25`

### openpilot version

0.9.0

```
'carFingerprint': 'VOLKSWAGEN ARTEON 1ST GEN',

'gitBranch': 'mqb-fw-dukajuke',
'gitCommit': 'c1524b4b082de8bf9091193c5682b45280ae3105',
'gitRemote': 'https://github.com/jyoung8607/openpilot.git',
```

**Comment by dukeajuke** [comment]
This is a better example route: 200d2fe234e1fef3|2022-12-03--16-12-04

**Comment by sshane** [comment]
@jyoung8607 recommended sharing the route with him so he can look into this.

**Comment by dukeajuke** [comment]
Thanks! I’ll do another drive with the experimental turned on and share it to you. It doesn’t happen at ever time its stops, but it does happen at least once with every drive.

**Comment by dukeajuke** [comment]
Hi Jason - I shared my device with you. The drive is - 200d2fe234e1fef3|2022-12-07--12-15-05--0. The steering disconnect issue happens at the first light about half way through the drive.

**Comment by jyoung8607** [comment]
@dukeajuke, I see where in the drive you encountered the steering fault, but not yet why based on the qlogs (abbreviated logs) that have been uploaded so far. At your convenience, go back to that same route in comma connect, go to Files, and Upload All Logs. That will send up some detailed debug info I need, so long as your device is on WiFi.

**Comment by dukeajuke** [comment]
Logs should be uploaded now. You can look at my last drive too. It did the same thing but this time in Chill mode. Displays a warning "Steering temporarily unavailable" and it won't start working again until I shut the car off and reboot the device. Thanks in advance for looking at this!

**Comment by jyoung8607** [comment]
Checked all three routes mentioned so far and unfortunately the rlogs haven't uploaded for any of them.

@sshane can you make sure these routes are queued for upload? I can't due to commaai/connect#203.

`200d2fe234e1fef3|2022-12-03--18-50-25`
`200d2fe234e1fef3|2022-12-03--16-12-04`
`200d2fe234e1fef3|2022-12-07--12-15-05`

**Comment by dukeajuke** [comment]
Looks like Those drives have been overwritten already (should have bought more storage!). I’ll do another drive tonight and make sure the logs get updated.

**Comment by dukeajuke** [comment]
The other routes were overwritten already. I just did another drive and the logs have been uploaded. The steering disconnects and errors out at the first light near the last 25% of the drive. - Route: 200d2fe234e1fef3|2022-12-11--17-00-49--0

**Comment by dukeajuke** [comment]
17:05:13 is about where the steering error occurs.

**Comment by jyoung8607** [comment]
It looks like your EPS doesn't want to see steering commands below 1 km/h. It also looks like your EPS is something new-to-us. There's an obvious difference in reported software part numbers, and a less obvious variance in its diagnostic response that makes me think it runs a different software stack than our usual. Fortunately, they should be easy to identify.

It looks like you're still running your temporary fingerprint update branch, so I've taken the liberty of pushing an update to that branch which prevents steering below 0.3 m/s (1.08 km/h). Please give that a try at your convenience.

Whether it works or not, please report back with your results. The change I've put in is more of a diagnostic measure than a final fix. If it works well, I'll add detection for this firmware to upstream openpilot. If not, I'll need to see logs again.

**Comment by dukeajuke** [comment]
Thanks! I'll give it a try tomorrow. I do need to reinstall that branch to get the update correct?

**Comment by jyoung8607** [comment]
Your device should already see the update and prompt you to install it from the UI. If it doesn't, go to Settings and then Software to manually check for updates. On the off chance that process doesn't work for you, yes you could reinstall.

**Comment by dukeajuke** [comment]
Looks like it updated automatically overnight. The change you make fixed my steering problem! Thanks again for all your help.

**Comment by dukeajuke** [comment]
Do you know if this change and the one you made to add my car's fingerprint will make it into the next release?

**Comment by jyoung8607** [comment]
I'm glad the change worked for you. Re: the fingerprint, that was merged long ago and will be in the next release. Re: the steering fix, I'm still considering how best to fix it in mainline openpilot. It may be a couple days before I file a PR. This GitHub issue will remain open for now, so you can watch it for updates.

**Comment by otaviobps** [comment]
I'm running sunnypilot but I'm having the exact same issue. @jyoung8607 which file is responsible for tweaking this? I want to check it in sunnypilot to see if I can fix it.

Also, how can I check if my fingerprint is correct? I'm running in a 2023 VW Taos

**Comment by dukeajuke** [comment]
Yep. Still happens on mine. Usually occurs at very low speeds.
________________________________
