### ISSUE TITLE
2022 Rav4 Hybrid "Headlight System Malfunction"

### ISSUE THREAD

**Issue by fawasme** [commaai/openpilot#26713]
### Describe the bug

Using stock 0.9.0 on 2022 Rav4 Hybrid, the "Headlight System Malfunction" error will constantly display on the MID. Also the auto high/low beam switching will not work. 

Issue will appear as soon aw the car starts. Constantly. 

### Which car does this affect?

Toyota RAV4 Hybrid 2022

### Provide a route where the issue occurs

https://connect.comma.ai/b55f9c346adf3f5f/1670293977853/1670295026520

### openpilot version

0.9.0

### Additional info

Using stock 0.9.0 on 2022 Rav4 Hybrid, the "Headlight System Malfunction" error will constantly display on the MID. Also the auto high/low beam switching will not work. 
![C922AA62-9AFE-45A5-AA72-5FE0CD06D88C](https://user-images.githubusercontent.com/119915293/205823478-7165ca82-bd26-4528-a0a7-55a1d897eef5.jpeg)
![9E0BAB08-8DAE-48DC-BBDC-A1A4E2791488](https://user-images.githubusercontent.com/119915293/205823484-3e378187-7860-4320-bfb4-89a2969709d8.jpeg)

**Comment by sshane** [comment]
You say constantly, but does this actually start as soon as you turn your car on? Or is it later into the drive?

**Comment by sshane** [comment]
Some questions that might help debug this:
- Is this a brand new cable? I would recommend trying a new one.
  - Is the relay box and C3 new?
- Did this start just recently, or is a persistent problem from when you first got your device?

**Comment by fawasme** [comment]
Thanks for the help Shane. I just received a confirmation email that you
guys will be shipping me a new cable for free. That sounds fair. I will
test it as soon as I get it and report back to you.

One last question regarding the 22 Rav4 Hybrid w/Denso: Do you think the
LONG will be available anytime in the future (I know it won't be right
away, but in the future) for this model?. This is something that really
makes a difference on me holding onto the device for the long run or not.
Is there hope for that?

**Comment by adeebshihadeh** [comment]
Yes, longitudinal is likely to be supported in the future.

**Comment by sshane** [comment]
Make sure your comma power is plugged in correctly, I'd try to re-seat that.

**Comment by fawasme** [comment]
No luck yet. Reseated everything, new cable keeps working bad and even worse than the original one

**Comment by fawasme** [comment]
![image](https://user-images.githubusercontent.com/119915293/207761030-b4c20ba2-6113-492b-b1b2-33401d9a32ad.jpeg)

Issue being reproduced on a another Rav4 2022 Hybrid

**Comment by fawasme** [comment]
Will a cable like this work to perform another test, assuming I have two bad Usb-C cables?

https://www.bestbuy.com/site/sku/6419158.p?skuId=6419158 https://www.bestbuy.com/site/sku/6419158.p?skuId=6419158

**Comment by fawasme** [comment]
I tested today with a new USB-C 3.2 cable. The problem still persists. After reporting on Discord, another member suggested that the issue might be either the Harness (which by PFD comparison seems fine) or the box. However, Comma support is either ignoring my request or I don't know what's going through their department. But I just can't hold on such an expensive device and have no answers at all. This is beyond unnaceptable, I will proceed to return everything until a fix has been stablished for this car model. You need to understand that I have a return window on a device that is NOT WORKING properly on an advertised vehicle which is supposed to work. 

I wished I had a different outcome and actually helped the project. I will not recommend this product to anyone after this experience.

**Comment by fawasme** [comment]
Issue was hardware related and specific to the C3 device. Using the original harnesses, cables and  box the problem was solved by a replacement unit. This ticket can be closed.

**Comment by sshane** [comment]
Great to hear! Let me know if there's any other issues!
