### ISSUE TITLE
Honda Accord 2020 Not Working ACC/LKAS/RDM Dashboard Error

### ISSUE THREAD

**Issue by joseption** [commaai/openpilot#26742]
### Describe the bug

Recently switched over from a Comma 2 which was running the stock version of OpenPIlot perfectly fine and without issue. When using Comma 3 with stock (release3) OpenPilot software on a non-hybrid Honda Accord 2020 the vehicle dashboard displays an ACC, LKAS, and RDM error. During this time, OpenPilot does not display any errors but does not appear to receive or respond to any of the cruise control commands from the vehicle. With the vehicle's cruise main turned on the ACC, LKAS, Honda sensing icon, and the info icon are all red. Clicking on the cruise +/- steering wheel buttons make an audible error sound and nothing happens on the OpenPilot display. This problem can be reproduced once OpenPilot loads and switches the harness box relay to use the Comma 3.

The harness, harness box, and all cables have already been reconnected and even replaced to ensure that the issue is not due to a faulty connection. I suspect this is software related specifically with my vehicle year since, during testing, switching to the master branch and enabling experimental mode does not yield any errors on either the Comma 3 or the vehicle and everything works as it should.

I would really like to get the release version working for me since I prefer using the vehicle's ACC for now. Any help is appreciated!

### Which car does this affect?

Honda Accord 2020

### Provide a route where the issue occurs

7c21724ca42488d4|2022-11-28--13-01-01--13

### openpilot version

0.9.0

### Additional info

Not sure if any of these errorLogMessage errors mean anything, but here are some from another drive 7c21724ca42488d4|2022-12-09--19-52-12--1

{'errorLogMessage': '{"created": 1670633534.1287196, "ctx": {"daemon": "modeld", "device": "tici", "dirty": false, "dongle_id": "7c21724ca42488d4", '
                    '"version": "0.9.0-release"}, "filename": "selfdrive/modeld/modeld.cc", "funcname": "run_model", "levelnum": 40, "lineno": 90, '
                    '"msg": "vipc_client_main no frame"}',
 'logMonoTime': 172306257061,
 'valid': True}
{'errorLogMessage': '{"created": 1670633534.1662509, "ctx": {"daemon": "modeld", "device": "tici", "dirty": false, "dongle_id": "7c21724ca42488d4", '
                    '"version": "0.9.0-release"}, "filename": "selfdrive/modeld/modeld.cc", "funcname": "run_model", "levelnum": 40, "lineno": 150, '
                    '"msg": "skipping model eval. Dropped -1 frames"}',
 'logMonoTime': 172343521227,
 'valid': True}
{'errorLogMessage': '{"msg": {"event": "fingerprinted", "car_fingerprint": "HONDA ACCORD 2018", "source": 1, "fuzzy": false, "cached": false, '
                    '"fw_count": 13, "ecu_responses": [[417001776, null, 1], [417001967, null, 1], [417001744, null, 1], [417001786, null, 1], '
                    '[417001904, null, 1], [417001758, null, 1], [417001768, null, 1], [417001771, null, 1], [417001825, null, 1], [417001739, null, '
                    '1], [417001811, null, 1], [417001824, null, 1], [417001909, null, 1]], "vin_rx_addr": 417001744, "error": true}, "ctx": '
                    '{"daemon": "controlsd", "dongle_id": "7c21724ca42488d4", "version": "0.9.0-release", "dirty": false, "device": "tici"}, '
                    '"level": "ERROR", "levelnum": 40, "name": "swaglog", "filename": "car_helpers.py", "lineno": 171, "pathname": '
                    '"/data/openpilot/selfdrive/car/car_helpers.py", "module": "car_helpers", "funcName": "fingerprint", "host": "tici", "process": '
                    '46572, "thread": 548378335056, "threadName": "MainThread", "created": 1670633534.7578797}',
 'logMonoTime': 172936091268,
 'valid': True}
{'errorLogMessage': '{"created": 1670633586.3671598, "ctx": {"daemon": "locationd", "device": "tici", "dirty": false, "dongle_id": '
                    '"7c21724ca42488d4", "version": "0.9.0-release"}, "filename": "selfdrive/locationd/locationd.cc", "funcname": "handle_gps", '
                    '"levelnum": 40, "lineno": 343, "msg": "Locationd vs ubloxLocation position difference too large, kalman reset"}',
 'logMonoTime': 224547069658,
 'valid': True}

**Comment by sshane** [comment]
Hi @joseption, is this still an issue for you?

**Comment by sshane** [comment]
Any updates @joseption?

**Comment by sshane** [comment]
It looks like you returned your device, so I'm going to close this. In the original route you sent, panda was reporting issues sending messages to the camera (likely all the messages it should have been forwarding), which would explain why everything was fine when using openpilot longitudinal, as we were blocking the camera's messages displaying faults.

Likely hardware issue, either panda or the OBD-C cable connected to the comma three.

![image](https://github.com/commaai/openpilot/assets/25857203/133d6fcd-a788-4561-a823-f3f759362422)
