### ISSUE TITLE
Planner stops commanding braking when soft disabling

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#26764]
<img width="1117" alt="Screenshot_37" src="https://user-images.githubusercontent.com/25857203/206963267-211fe997-8e9e-4542-9236-e6e4ff59a0ab.png">

**Comment by sshane** [comment]
fixed when setting `self.params[:,1]` to 2 (not caused by `v_upper`)

**Comment by adeebshihadeh** [comment]
Fixed in #26765
