### ISSUE TITLE
2020 Silverado Wanders straight, hugs curves

### ISSUE THREAD

**Issue by solardude2** [commaai/openpilot#26771]
### Describe the bug

Wanders lane straight, hugs lines straight, hugs inside curves and crosses lines in curves. Has been doing this since being supported.  View of road and 360 camera showing lane placement can be seen here.  Unlisted video (https://www.youtube.com/watch?v=xU4Cuonmq_s)

### Which car does this affect?

2020 Silverado

### Provide a route where the issue occurs

38aa7da107d5d252|2022-12-11--11-05-23

### openpilot version

 openpilot v0.9.1

**Comment by morrislee** [comment]
Same here from Sierra, the lane cutting on curves seems to be happening other cars too, there are a few reports even on small cars.

**Comment by sshane** [comment]
@nuwandavek hopefully your Bolt tune should extend to all GM

**Comment by Verylukyguy** [comment]
Has there been any progress on the Bolt/GM tuning?

**Comment by morrislee** [comment]
I believe they are referring to https://github.com/commaai/openpilot/pull/26371

**Comment by sshane** [comment]
@solardude2 does this still happen on latest master?

**Comment by solardude2** [comment]
Last time I used it. Nobody with this type truck is using master. All on forks. I went back to my old tried n true and the other guys are on a fork of master trying to get it to work better. I will happily switch back for testing. Cuts curves and doesn't stay straight.

**Comment by sshane** [comment]
@nuwandavek does the non-linear function we have work for this car?

**Comment by morrislee** [comment]
NNFF from twilsonco is very much of an improvement for the oscillation in straights and over cutting in turns. But nothing so far fixes hugging in laneless profile. Lane planner still exist in sunnypilot has slightly better reliability in centering. I dont know if its a planner cost issue needs to be tuned or model is natually hugging when its still a taller vehicle

**Comment by morrislee** [comment]
**Lane Planner**
![image](https://github.com/commaai/openpilot/assets/607941/031e0479-aa9f-423c-a725-161e41e294bd)

**Laneless Planner**
![image](https://github.com/commaai/openpilot/assets/607941/390ecd56-647e-4ac8-8a31-0306e9a6ce04)

Same route with different planner...

Doesnt look like a control issue, they look identical, this is with tim's NNFF, lane planner from sunny's fork to compare.

Lane positioning is very close to the Laneless from master that tim has added NNFF in, master just more oscillation and poor turn performances

**Comment by nuwandavek** [comment]
@morrislee Can you post these route ids? 
@sshane I'm working on an NNFF like controls stack for this (which should greatly improve oscillation/turns), but hugging is more upstream, usually. I can look at the logs and comment better.

**Comment by morrislee** [comment]
> @morrislee Can you post these route ids? @sshane I'm working on an NNFF like controls stack for this (which should greatly improve oscillation/turns), but hugging is more upstream, usually. I can look at the logs and comment better.

Laneless:
fe80a4e1cedec853|2023-08-05--17-47-13--0

Lane Planner:
fe80a4e1cedec853|2023-08-07--18-20-15--0

**Comment by sshane** [comment]
Requested upload, please keep the device on wifi

**Comment by nuwandavek** [comment]
[This](https://github.com/commaai/openpilot/pull/29540) should fix a lot of the lane wandering etc issues. The tune was pretty broken previously. 
@morrislee tried it and it is better than master. The neural fit is the final answer for all controls issues, but it will take a bit of time to be done more generically. As far as non-controls turn cutting, it is upstream of controls (model-planning) and is a top priority for comma. Multiple people are working on various approaches, and will hopefully have a fix soon.

**Comment by sshane** [comment]
Fixed by https://github.com/commaai/openpilot/pull/29540
