### ISSUE TITLE
[PC] ui.py is missing libnppc.so.11

### ISSUE THREAD

**Issue by ebadi** [commaai/openpilot#26786]
### Describe the bug

I have an identical issue as #26503 #26595 and I tried to see if I can see camera images from `./ui.py` and noticed another issue:

```
root@research:/openpilot/tools/replay# ./ui.py 
Traceback (most recent call last):
  File "./ui.py", line 6, in <module>
    import cv2  # pylint: disable=import-error
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libnppc.so.11: cannot open shared object file: No such file or directory
```
Partial workaround, upgrading opencv from  4.5.5.64 to 4.6.0.66 fixes the issue with the missing libnppc.so.11 shared library but only opens up a blank windows:
```
root@research:/openpilot/tools/replay# pip  list | grep cv
opencv-python-headless        4.5.5.64


root@research:/openpilot/tools/replay# pip uninstall  opencv-python-headless

root@research:/openpilot/tools/replay# pip install opencv-python-headless 
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 MB 32.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.5 in /root/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from opencv-python-headless) (1.23.4)
Installing collected packages: opencv-python-headless
Successfully installed opencv-python-headless-4.6.0.66
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

### OS Version

Ubuntu 20.04 / docker

### openpilot version or commit

Tested on 72bf819ef06ee81f37d33f45979dfcf8d88b0ad3 (but this commit is not relevant)

**Comment by ebadi** [comment]
Passing `--high_quality --dual_camera` to `bridge.py` solved the camera issue and now the window is not blank. I keep this issue open so the dependency problem (`libnppc.so.11`) can be solved too

**Comment by pgchui** [comment]
I had the same issue with NVIDIA driver 525 and CUDA 12.0. Swtiched to NVIDIA driver 520 and CUDA 11.8 fixed my issue.

**Comment by adeebshihadeh** [comment]
We've updated the python packages a few times since then. Feel free to make another issue if you're still having this issue.
