### ISSUE TITLE
No video (blue screen) when in simulator

### ISSUE THREAD

**Issue by jeroenlammersma** [commaai/openpilot#26814]
### Describe the bug

When running openpilot in the CARLA simulator, the only thing I get is a blue screen (see image below).
I checked if the car spawned in the map, but that is the case (second image below).
Furthermore, I tried a complete fresh Ubuntu 20.04 and openpilot installation, but still, same result.

The latest commits did not introduce this issue, this was already the case some weeks ago.

![openpilot-sim-blue-screen-ui](https://user-images.githubusercontent.com/33349469/208154057-aea755cf-99ea-48b0-aa34-3d2553e2fbc4.png)

![openpilot-sim-blue-screen-car](https://user-images.githubusercontent.com/33349469/208154535-8a1b0a9c-544d-4d72-b7b7-9bc3b0bc1477.png)

### OS Version

Ubuntu 20.04

### openpilot version or commit

6dc1fa255970a5976a6acc1f1b9424258ee3fcf3

### Additional info

- CPU: AMD Ryzen 9 5900x
- GPU: NVIDIA RTX 3070

**Comment by incognitojam** [comment]
This is the same issue as https://github.com/commaai/openpilot/issues/26503

**Comment by jeroenlammersma** [comment]
Ah sorry, did not see this issue. Thanks for pointing me in the right direction!

**Comment by zeroyang0809** [comment]
hello i meet the problem "openpilot unavailable waiting for controls to start"
this problem is familiar with your problem
do you know how to fix it ?
thx
