### ISSUE TITLE
replay: make it work on device

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#26810]
An error in cameraview.cc is thrown on this line: https://github.com/commaai/openpilot/blob/08b4cff484940b394fa64d89dad65330bcb51a4a/selfdrive/ui/qt/widgets/cameraview.cc#L328

**Comment by sshane** [comment]
@deanlee do you want to take a quick look at this one? I remember seeing that the strides or height of the VIPC stream were different when using camerad vs replay, so it might be a simple fix

**Comment by deanlee** [comment]
Looks like a sync issue : https://github.com/commaai/openpilot/pull/26904

**Comment by sshane** [comment]
Hmm, still looks like I'm getting the same error running replay and ui
