### ISSUE TITLE
Comma2 freeze

### ISSUE THREAD

**Issue by emersondi** [commaai/openpilot#26831]
### Describe the bug

Hi.. my comma2 freeze today... Just start the car... move a few metters and then freeze at 6km/h winth the video frozen too...then travel 30 minutes and still frozen.. so I unplugged and plugged the USB... then  comma2 never turn on... no vibration at plug... and only the blue Led in the back.... what should I do?? Thanks for your suppot and help.

### Provide a route where the issue occurs

https://useradmin.comma.ai/logs?url=https%3A%2F%2Fcommadata2.blob.core.windows.net%2Fbootlogs%2F6f4ef5deb3e2820f%2F2022-12-17--19-13-10.bz2%3Fse%3D2022-12-22T23%253A24%253A21Z%26sp%3Dr%26sv%3D2018-03-28%26sr%3Db%26rscd%3Dattachment%253B%2520filename%253D6f4ef5deb3e2820f_2022-12-17--19-13-10.bz2%26sig%3DgXMPHLlwfzALnPcC6HIkEOM%2FsVXoNokxauOBSLdEq2s%253D

### openpilot version

Animal pilot

**Comment by adeebshihadeh** [comment]
This repo is not for hardware support. Contact support@comma.ai if your device is still under warranty.
