### ISSUE TITLE
How to upgrade the base model of Honda 2019 INSPIRE so that it can support automatic driving？

### ISSUE THREAD

**Issue by mack007liu** [commaai/openpilot#26843]
### Describe the bug

How to upgrade the base model of Honda 2019 INSPIRE so that it can support automatic driving. Check the official document and there is no support

### Which car does this affect?

the base model of Honda INSPIRE 2019 

### Provide a route where the issue occurs

*

### openpilot version

*

**Comment by adeebshihadeh** [comment]
Closing since this is not an issue. Check out our [community discord](https://discord.comma.ai) server for discussions like this instead.
