### ISSUE TITLE
2023 Highlander Hybrid Platinum Support

### ISSUE THREAD

**Issue by sivapallu** [commaai/openpilot#26845]
### Describe the bug

Hi there, I am getting the error message “dash cam mode car unrecognized “. Is there anything I can do to fix the issue. Your help would be greatly appreciated.

My car is 2023 highlander hybrid platinum 

### Provide a route where the issue occurs

4e5f97eadd967fda

### openpilot version

0.9.0

**Comment by alancyau** [comment]
Check out the car fingerprinting wiki. If you need additional help, someone on the Discord channel will be able to help you.

https://github.com/commaai/openpilot/wiki/Fingerprinting
