### ISSUE TITLE
Manager failed to start: thermald.py related?

### ISSUE THREAD

**Issue by adam-nelson** [commaai/openpilot#2688]
**Describe the bug**

Recent update has caused an error startup? I am on master-ci 0.8.1

**How to reproduce or log data**

Update comma two to latest revision

**Expected behavior**

No errors on startup

**Device/Version information (please complete the following information):**
 - Device: [comma two]
 - Dongle ID: [18e8ac91b805db11]
 - Route: [unknown]
 - Timestamp: [3am local time aest]
 - Version: [master-ci 0.8.1]
 - Car make/model: [Toyota corolla accent sport hybrid 2019]

**Additional context**

![image](https://user-images.githubusercontent.com/5194943/101063584-af993f80-35de-11eb-9c5f-223ccecff3c8.jpeg)![image](https://user-images.githubusercontent.com/5194943/101063585-af993f80-35de-11eb-848b-780555e45ecf.jpeg)

**Comment by pd0wm** [comment]
Fixed by https://github.com/commaai/openpilot/commit/d5a806e564afcc1b4de0b934a6073e4695cc7f96

**Comment by adam-nelson** [comment]
Dam typos
