### ISSUE TITLE
Adjust Volume Levels for Alerts based on the sound in the car

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#26925]
It would be great for the comma 3 to have ambient sound where the volume is adjusted based on how much sound there is in the car. I remember there being talks about the comma 3 having a microphone, there should be a way to check the sound levels found in the car and increase the sound of the alerts after a certain period of time (10 seconds of loud music playing or loud talking)

**Comment by incognitojam** [comment]
This was already implemented https://github.com/commaai/openpilot/pulls?q=is%3Apr+micd+is%3Aclosed

**Comment by BBBmau** [comment]
ah gotcha, It wasn't part of the `devel` branch. Thanks letting me know
