### ISSUE TITLE
No Messages in Cabana - Need to view LKAS11 values

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#26942]
### Describe the bug

I uploded all logs. But I cannot view cabana/LKAS11 data.
All I get in cabana is "Loading messages..."

![image](https://user-images.githubusercontent.com/96002277/212271855-7b1ad082-e8ac-499c-9668-39fbdfc212ba.png)

### Provide a route where the issue occurs

6111bd7df5043394|2023-01-12--19-48-43--0

### openpilot version

master

**Comment by adeebshihadeh** [comment]
web cabana is going to be deprecated soon. try out the new cabana here instead: https://github.com/commaai/openpilot/tree/master/tools/cabana
