### ISSUE TITLE
Display more useful info than just `NO PANDA` when a panda is blocked from flashing due to the IGN being on.

### ISSUE THREAD

**Issue by nelsonjchen** [commaai/openpilot#26982]
Users typically get into this situation when switching codebases that change out the panda firmware but for some reason do not turn their car off when changing the codebases. 

`NO PANDA` is a bit of a blunt message when a panda isn't available. In the background, the panda may be flashing or there might be some other issue in the environment blocking flashing like IGN being on. The widget or UI should reflect some of this activity to provide clarity and steps to remediate.

**Comment by adeebshihadeh** [comment]
Haven't seen this be an issue recently and it's fixed in HW on the comma 3X. so gonna close.
