### ISSUE TITLE
updating to 4.7 total failure

### ISSUE THREAD

**Issue by mfd00gie** [commaai/openpilot#270]
My Geo was not updating so as instructed I uninstalled openpilot. I reinstalled the software and now all that it can do is boot up ending in a black screen that is non responsive. The only input that it responds to is the power button and it will shut down and/or restart. The GUI is not there. 

Thanks!!!

**Comment by mfd00gie** [comment]
P.S. This problem is independent on whether or not it is plugged into the Panda on a 2016 civic EX-L w Sensing

**Comment by jfrux** [comment]
@mfd00gie Hop on the Comma Slack channel as this doesn't appear to be a bug.
We can help you on there.
