### ISSUE TITLE
commIssue: dropping CAN packets

### ISSUE THREAD

**Issue by tglevrie** [commaai/openpilot#27027]
### Describe the bug

Lately, during drives, I've received an orange screen saying that there's a communication issue. Disengaging and reengaging fixes the issue for the most part, and rebooting will reduce the frequency even more so. I just wanted to make a report to see if an issue could be identified. 

### Provide a route where the issue occurs

1c05783affe6641f|2023-01-20--19-06-44

### openpilot version

0.9.0

### Additional info

Makes no difference whether in experimental mode or not, if that helps. Issue happens around 19:10:15. Thanks a bunch for the help (:

**Comment by sshane** [comment]
Seems like you're dropping CAN packets every once in a while. Have you tried a new cable?

**Comment by tglevrie** [comment]
I have not. I will try this and hopefully it resolves the issue. Thank you very much!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sshane** [comment]
Let me know when you try it, and which cable you try

**Comment by adeebshihadeh** [comment]
This is a system lag, not a cable issue. #27084 is another instance of this.

**Comment by goodchoom** [comment]
After several days of not getting the alerts and updating to 0.9.1 master-ci e14fd545816b9546f2362717213ae9000bd69d27 they started going off again. This time they ocurred more frequently and earlier on than expected.

3d681b6c168ca058|2023-01-28--16-36-55--0

**Comment by AreYouRlyScared** [comment]
I ran into this issue today when I went to lunch at work, as requested by @sshane, I'm posting the segment here. It should be noted a simple reboot fixed it. 

22 EUV, Running the latest `master` commit.
`3140e1c6195c880e|2023-02-02--20-30-40--2`
