### ISSUE TITLE
"Openpilot failed to build" screen

### ISSUE THREAD

**Issue by camojackson** [commaai/openpilot#27041]
### Describe the bug

Downloaded the recent update to the master-ci on 1/20/23. When I got back in the car after the update the screen said "Openpilot failed to build". I hit the reset button but it keepos coming back to the same screen. On a 2022 Kia Sorento with Red Panda.
![IMG-1945](https://user-images.githubusercontent.com/48506575/213936014-c170040d-088d-43ed-a1ad-e28416431960.jpg)

### Provide a route where the issue occurs

No route

### openpilot version

master-ci 1/20/23

**Comment by adeebshihadeh** [comment]
There was a bad commit briefly on master.
