### ISSUE TITLE
Communication Issue Between Processes

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#27084]
### Describe the bug

Every day since 1/21/2023, openpilot has thrown this alert while engaged and driving on a specific section of road about a minute into the drive. These alerts show up intermittently but go away on their own after a few seconds, also they don't seem to affect the driving performance.

### Provide a route where the issue occurs

3d681b6c168ca058|2023-01-23--16-32-00--1

### openpilot version

0.9.1 master-ci cf1c43f04cca2cff367921a244adeb11f307d3f1

**Comment by sshane** [comment]
Are you having the same commIssue from https://github.com/commaai/openpilot/issues/27027. Can you try a new cable and see if that resolves the issue? You can probably email support@comma.ai for a free one.

**Comment by adeebshihadeh** [comment]
This isn’t a cable issue. It’s a system lag.

**Comment by adeebshihadeh** [comment]
Thanks for the report, we'll track it in #27027.
