### ISSUE TITLE
Restarting comma service kills ssh connection

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#27102]
### Describe the bug

Using `tmux kill-session -t comma; rm -f /tmp/safe_staging_overlay.lock; tmux new -s comma -d "/data/openpilot/launch_openpilot.sh"; tmux a` would restart openpilot without issues.

The new suggested command seems to be `sudo systemctl restart comma` but this kicks off non-local ssh connections, specifically when using comma's `ssh.comma.ai` service.

### Provide a route where the issue occurs

1a5d045d2c531a6d

### openpilot version

0.9.1

**Comment by adeebshihadeh** [comment]
This isn't a bug. You can use `launch_openpilot.sh` or `selfdrive/manager/manager.py` for this purpose.
