### ISSUE TITLE
Adding multiple LIDARs , RADAR and cameras

### ISSUE THREAD

**Issue by snakehaihai** [commaai/openpilot#2713]
Hi 
I`m just wondering if there is any plan to add additional LIDARs and RADARs or stereo cameras for safer navigation?

I saw some RADAR code inside the git. But not very sure how to use my custom RADARs from school robotics project. Is there any guideline in this? I also have a couple of ouster OS1- 16line and velodyne puck. How I can interface them in to have absolute measurement?

**Comment by adeebshihadeh** [comment]
See selfdrive/car/*/radar_interface.py for how to interface with a radar. Closing as I think this is more appropriate as a GitHub Discussion.
