### ISSUE TITLE
openpilot will suddenly brake !

### ISSUE THREAD

**Issue by betashepherd** [commaai/openpilot#27147]
### Describe the bug

When the vehicle passes through the spliced road, openpilot will suddenly brake. I don't know if this is a bug or it is set up on purpose? Maybe openpilot thinks it's the end of the road and brakes suddenly? I'm not sure.

Comma Two + [Toyota Corolla Hybird 2021] + openpillot 0.8.13

![image](https://user-images.githubusercontent.com/5636922/215374723-7a2b8cad-ecfc-445d-930f-2e6d349b6688.png)

### Provide a route where the issue occurs

private device

### openpilot version

0.8.13

**Comment by incognitojam** [comment]
It might be related to the radar picking up a metal object. Without logs it is impossible to debug this further.
