### ISSUE TITLE
Total black screen, C3 not responding

### ISSUE THREAD

**Issue by Samcat308** [commaai/openpilot#27172]
### Describe the bug

C3 driving with stock open pilot froze up yesterday. Tried restarting got a black screen not responding tried putting auxiliary power at home and still black screen. No splash screen I’ve put over 6000 miles on this unit with no problems 

### Provide a route where the issue occurs

Unable to upload C3 froze black screen

### openpilot version

0.9.0

**Comment by adeebshihadeh** [comment]
What's your dongle ID? You can find it in connect.

**Comment by Samcat308** [comment]
This was taken back in NovemberSent from All-Ways Painting On Jan 31, 2023, at 1:07 PM, Adeeb Shihadeh ***@***.***> wrote:﻿
What's your dongle ID? You can find it in connect.

**Comment by adeebshihadeh** [comment]
This is most likely a HW issue. Email support@comma.ai and we'll take care of it.
