### ISSUE TITLE
Subaru Crosstrek 2022 Fingerprint not recognized

### ISSUE THREAD

**Issue by Kirivije** [commaai/openpilot#27216]
### Describe the bug

recently got a comma three and my device will only work in dashcam mode.

### Which car does this affect?

Subaru Crosstrek 2022

### Provide a route where the issue occurs

e91f0f6d24a7fe4b|2023-02-02--18-35-49

### openpilot version

0.9.1

**Comment by sshane** [comment]
Closed with https://github.com/commaai/openpilot/pull/27222
