### ISSUE TITLE
Bounty: Volvo - 2022 XC90 T8 (hybrid) - $5,000 USD

### ISSUE THREAD

**Issue by turtleHeadMcHeadFace** [commaai/openpilot#27226]
$5,000 USD bounty for Volvo XC90 integration. I have a 2022 XC90 T8 Extended Range, want openpilot on it.

Message me on discord if you have questions: iliketurtles#1457

**Comment by adeebshihadeh** [comment]
Thanks for the interested, but our issue tracker is strictly for issues (and sometimes bounty we're backing). Discord is a better place for this.

**Comment by masad-frost** [comment]
Did you find someone to take this on? I'm happy to chip in

**Comment by turtleHeadMcHeadFace** [comment]
Unfortunately no takers so far :/.
Tyler Barney

On Aug 31, 2024, at 6:39 PM, Faris Masad ***@***.***> wrote:

﻿

Did you find someone to take this on? I'm happy to chip in
