### ISSUE TITLE
Openpilot performs poorly in Carla Simulation

### ISSUE THREAD

**Issue by PhilWallace** [commaai/openpilot#27232]
### Describe the bug

Hello guys. I'm running the latest Openpilot on Carla simulation, and found out it perform quite poorly... Specifically, It cannot even stay in the lane with very low speed (25 mph or even lower), and it is very likely to crash in some turnings:

![Screenshot from 2023-02-07 08-47-19](https://user-images.githubusercontent.com/37956889/217018606-74ee1fa2-e86c-45fe-981f-ec91199fc5a5.png)

Considering the good performance of Openpilot on real car, I wonder what is the reason leading to such poor performance in simulation. Maybe the parameter of the MPC control not well-tuned? Or the vehicle dynamic model of Openpilot does not fit the Carla's car model? I also felt that the detected lanes are quite laggy, which may not provide real-time information for the planning and controlling module.

 Any advice on improving the performance in Simulation? Many thanks.
 

### OS Version

Ubuntu 20.04

**Comment by ferryman0723** [comment]
I met the same situation and can‘t solve it！

**Comment by adeebshihadeh** [comment]
We've moved our simulator to MetaDrive and it performs much better now. Let us know if you have any issues with that.
