### ISSUE TITLE
The controls lagging problem in Carla Simulation

### ISSUE THREAD

**Issue by ferryman0723** [commaai/openpilot#27257]
### Describe the bug

I'm running the latest Openpilot docker on Carla simulation.
After input 
```
# Terminal 1
./start_carla.sh
# Terminal 2 - Run openpilot and bridge in one Docker:
./start_openpilot_docker.sh
```
and input` ./bridge.py --high_quality --dual_camera` in the openpilot docker,the car cannot accelerate and keep driving in the lane after I input '1'.
![图片](https://user-images.githubusercontent.com/109616002/217483731-3129b243-75d5-417c-b429-be38c3c442b1.png)
After that I modify the code in selfdrive/controls/controlsd.py  like this
![0e6c2074d573e30361d36bd23bb561d2b02924f2](https://user-images.githubusercontent.com/109616002/217485179-e67ab230-8f93-4e11-9b2f-7db859e48ecb.png)
![2e44f46511846d8ab4f2ac4381fe7634873fc0b5](https://user-images.githubusercontent.com/109616002/217485191-08dcb164-f1c1-46f6-aebb-e80cecff8a2d.png)

Although the car can accelerate now, it performs badly and slowly,unable to maintain lane driving and show the Controls Lagging problem,It seems that this problem existed before I modified the code.Has anyone met this problem and successfully solved it?Thanks a lot！

![1675846884147](https://user-images.githubusercontent.com/109616002/217486634-63e1c2ed-27c4-46b1-a169-07fcf9c53642.jpg)
![图片](https://user-images.githubusercontent.com/109616002/217486877-ecdf0cae-2f8b-484a-8899-bbd5df729fb3.png)
![1675846884131](https://user-images.githubusercontent.com/109616002/217487052-2884b2d8-7366-4936-80dd-f3e263619b8f.jpg)
![1675848236396](https://user-images.githubusercontent.com/109616002/217488874-3a1dec51-66b3-464f-912e-04bbedb63f4e.jpg)

### OS Version

Ubuntu 20.04(docker)

**Comment by fatsheep2020** [comment]
it can work on v0.9.0, not OP docker, after I tested

**Comment by ferryman0723** [comment]
> it can work on v0.9.0, not OP docker, after I tested

how can I run the v0.9.0 in the docker as my PC is ubuntu18.04,have you met the same problem?thanks for reply!

**Comment by ferryman0723** [comment]
some screenshots
![图片](https://user-images.githubusercontent.com/109616002/218674125-d3b7c722-8e11-4c41-9bce-0dedac7efc89.png)
![图片](https://user-images.githubusercontent.com/109616002/218674148-4a3ea9f8-8155-4712-ab68-9f04783af9cf.png)

**Comment by jon-chuang** [comment]
What are your system specs? It's probably a performance issue if your GPU is weak.

Try running without `--high_quality` and report back. Thanks.

**Comment by ferryman0723** [comment]
> 

It seems to have the same problem after running without --high_quality,still lagging problem.I use Intel(R) Xeon(R) Silver 4214 CPU + 2080TI,is this configuration enough to run op?thanks

**Comment by ferryman0723** [comment]
> What are your system specs? It's probably a performance issue if your GPU is weak.
> 
> Try running without `--high_quality` and report back. Thanks.

It seems to have the same problem after running without --high_quality,still lagging problem.I use Intel(R) Xeon(R) Silver 4214 CPU + 2080TI,is this configuration enough to run op?thanks

**Comment by zeroyang0809** [comment]
hello i meet the problem "openpilot unavailable waiting for controls to start" 
this problem is familiar with your problem 
do you know how to fix it ? 
thx

**Comment by jon-chuang** [comment]
If you are building on master, it is due to https://github.com/commaai/openpilot/pull/27354

You need to add:
`Params().put_bool("ObdMultiplexingDisabled", True)`

**Comment by zeroyang0809** [comment]
thanks for your reply 
where to add Params().put_bool("ObdMultiplexingDisabled", True)
thank you so much

**Comment by jon-chuang** [comment]
Put it in the `peripheral_state_function` loop in `bridge.py`

**Comment by jon-chuang** [comment]
Yes. Lmk if it works.

**Comment by zeroyang0809** [comment]
thanks for your reply.
i can successfully launch the carla simulation on openpilot.
however when the car run for a few seconds,
it has this problem "take control immediately Vechicle Parameter Identification Failed". 
Do you know how to fix it? Thanks 
![image](https://user-images.githubusercontent.com/116786638/220255243-5b8f0699-3e37-4bd1-95d1-a2c692825909.png)

**Comment by jon-chuang** [comment]
Not too sure. You could try to put the suggested line after pm.send(..) instead.

**Comment by ferryman0723** [comment]
> What are your system specs? It's probably a performance issue if your GPU is weak.
> 
> Try running without `--high_quality` and report back. Thanks.

After the above steps, the latest op image in my PC has the following problems,I think it‘s still controls lagging problem.Does it means the GPU is not strong to run the op and carla?I use the 2080T
![图片](https://user-images.githubusercontent.com/109616002/220839429-4a2db9dd-8f51-4c5a-a118-5956774c11e8.png)
![图片](https://user-images.githubusercontent.com/109616002/220839448-6b1a805f-c8f1-4d55-8eca-4b4760077554.png)

**Comment by ferryman0723** [comment]
> it can work on v0.9.0, not OP docker, after I tested

hello,have you met the same problem？can you give me some measure ，thanks a lot!

**Comment by ferryman0723** [comment]
> it can work on v0.9.0, not OP docker, after I tested

how can you run the v0.9.0  op docker,I can't find it ,can u give me some idea?thanks!

**Comment by ferryman0723** [comment]
> it can work on v0.9.0, not OP docker, after I tested

how can you run the v0.9.0 op docker,I can't find it ,can u give me some idea?thanks! @fatsheep2020

**Comment by ferryman0723** [comment]
> What are your system specs? It's probably a performance issue if your GPU is weak.
> 
> Try running without `--high_quality` and report back. Thanks.

@jon-chuang  I have the question that when I run the official docker,does it use the GPU?I havn't seen the op is using gpu

**Comment by ferryman0723** [comment]
I resolved this problem after I changed my pc,I think it‘s Gpu server configuration issues and I recommend using op on personal computer.Anyway, thanks all those who replyed.You can use the docker from:(https://hub.docker.com/r/ferryman0723/openpilot).Now it can work.

**Comment by CrazyMustard-404** [comment]
> thanks for you reply. is that like this?
> 
> ![1](https://user-images.githubusercontent.com/116786638/220133097-99a47290-9e93-4b1c-aaa0-2edb5b6025fb.png)

Hello, could you please send me a copy of your bridge.py? I am currently using openpilot 0.8.9 and encountering the same issue as you. Additionally, my bridge.py differs from the latest official version. Thank you! Email: 415736313@qq.com

**Comment by tk-menot** [comment]
@ferryman0723 Hi, considering that the latest version no longer supports Carla, I am using your Docker image. But I encountered some problems: (1) The UI interface of openpilot in the image is problematic, and I cannot see the surrounding environment. (2) I hope to set a destination and have the openpilot drive towards that point. Do you have any methods? Looking forward to and thank you very much for your answer!
