### ISSUE TITLE
Vehicle Stops After Vehicle Parameter Identification Failed Alert

### ISSUE THREAD

**Issue by didpurwanto** [commaai/openpilot#27282]
### Describe the bug

I just updated to 0.9.0 version in docker version and encounter some problems. The first matter, which has been resolved by installing libzmq package to enable modeld module. The second issue that has not resolved yet is the vehicle start to decelerate and finally stop after Vehicle Parameter Identification Failed alert.

Snapshot of ``bridge.py``, it shown that the engine still engaged but the vehicle is stop running in Carla.
![Screenshot from 2023-02-10 11-54-14](https://user-images.githubusercontent.com/8987946/217996697-ad75eed7-31a3-4ae4-9258-cd7a14cee8c8.png)

Thanks for the help.

### OS Version

Ubuntu 20.04

### openpilot version or commit

0.9.0

### Additional info

![frame 1](https://user-images.githubusercontent.com/8987946/217996486-2a721635-e0b9-4c1c-9eac-819be2449b41.png)
![frame 2](https://user-images.githubusercontent.com/8987946/217996506-413e2104-d205-479c-8682-5c5b332cff6f.png)
![after a couple of second](https://user-images.githubusercontent.com/8987946/217996560-6437a7d4-8031-47c1-87a3-02ebe7aef1d8.png)
![vehicle alert](https://user-images.githubusercontent.com/8987946/217996583-2c07ee25-e580-4fda-ac51-60d2701fd363.png)
![vehicle stop](https://user-images.githubusercontent.com/8987946/217996603-116a5eb8-40b5-49a6-b524-7452f8bb02ba.png)

**Comment by PhilWallace** [comment]
Comment the identification failed alert code in _controlsd.py_ worked for me.

**Comment by didpurwanto** [comment]
@GregorKikelj Do you face this problem too?

**Comment by didpurwanto** [comment]
@PhilWallace Can you give more detail information?

**Comment by GregorKikelj** [comment]
@didpurwanto I can't get UI to show the camera feed yet... It segfaults with dual camera mode but should finally have some time today to investigate more

**Comment by PhilWallace** [comment]
> @PhilWallace Can you give more detail information?

I commented the following codes in selfdrive/controls/controlsd.py, should be line 374~375:
    #if not self.sm['liveParameters'].valid:
    #  self.events.add(EventName.vehicleModelInvalid)

**Comment by didpurwanto** [comment]
Thansk @PhilWallace . Indeed it will work but will affect the driving quality.
