### ISSUE TITLE
Toyota: TSS2 Slow reaction to braking command

### ISSUE THREAD

**Issue by briskspirit** [commaai/openpilot#2731]
Was going off ramp with high speed, on a stop light there was a stopped semi truck. TSS2 issued AEB warning and applied brakes, OP haven't seen stopped lead car? 

Not bragging about AEB at all, creating this bug report to check if there is a bug with lead detection or if model can't see semis.

P.S.: had problems with semis in front before, sometimes they are transparent and sometimes there's a feeling that distance to lead is calculated to its rear axle(radar error?)

Route: f66032c2b5aa18ac|2020-12-09--09-38-44
Timestamp: 1923 sec
Version: 0.8.1 master-ci

**Comment by abdulrahman004** [comment]
Going to add a similar issue that occurred to me. A car entered sideways and merge into my lane. OP didnt detect it till very late. My car's stock AEB did fine and beeped at me (not sure if it applied brakes)

Route:59f457ce47259dd2|2020-12-10--02-48-45--3
Timestamp: 18:51:45
Version: 0.8.0 - release2

gif https://imgur.com/a/Zkm9hVp

**Comment by pd0wm** [comment]
It was commanding brakes, but seems like the car took quite a while to respond. Due to the slow response it also required more braking than the 3 m/s^2 allowed by the safety limits.

![2020-12-10-115237_721x434_scrot](https://user-images.githubusercontent.com/1314752/101763028-7bda8000-3ade-11eb-802b-4b47d0302b87.png)

**Comment by pd0wm** [comment]
@abdulrahman004 The model only detected the car once it was fully in your lane. Hopefully end-to-end longitudinal will be better at dealing with these situations.

**Comment by briskspirit** [comment]
@pd0wm Could be that it was reacting slow because it was me just setting cruise speed lower and lower while going off ramp?
Status value 10:

![Capture](https://user-images.githubusercontent.com/11968822/101778342-beda2a80-3ac1-11eb-98c9-d2fc703bc0fe.JPG)

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/issues/24746

**Comment by haraschax** [comment]
There is no known way to make TSS2 more responsive
