### ISSUE TITLE
LKAS Faults - '17 Bolt

### ISSUE THREAD

**Issue by dominicdoty** [commaai/openpilot#27324]
### Describe the bug

2017 Bolt running `opgm/build-bolt` experienced two LKAS hard faults while openpilot was engaged.
May be a fork specific issue or a non-supported car issue.

Didn't notice any specific conditions that were common to these two errors that may have triggered them.

`82a0516f27e12844|2023-02-12--19-24-29--9`
`82a0516f27e12844|2023-02-12--19-38-07--28`

### Which car does this affect?

Chevrolet Bolt 2017

### Provide a route where the issue occurs

82a0516f27e12844|2023-02-12--19-38-07--28

### openpilot version

341eb2e0fd46b79eeb4096b28443f304c3e71528

### Additional info

On OPGM branch that's rebased to comma master nightly - version I am currently using would have been rebased to master on Saturday night. I'll need to fetch git log from the device to confirm which master commit specifically I'm rebased on top of.

**Comment by adeebshihadeh** [comment]
We can't look into issues from forks. Report the issue to the fork maintainers instead. Feel free to open a new issue if you can reproduce this with stock openpilot.
