### ISSUE TITLE
Disable route planning indicator when car is parked

### ISSUE THREAD

**Issue by minorOffense** [commaai/openpilot#27359]
I’ve had a few people now when I show them the comma 3 when we first get into the car and it’s parked they ask why the green line is waggling all over the place. And I just tell them it’s trying to figure out where to drive. And then they inevitably make a joke along the lines of “well hopefully it doesn’t drive into the garage door”. 

Figure it might be a good idea to just not have it trying to route a path while in park. May make the system seem more polished or confident in its abilities. Maybe even a message similar to when the car is in reverse gear. Just have it say “parked” greyed out or something.

**Comment by adeebshihadeh** [comment]
I don't think we want to hide the model outputs in these scenarios, though we are working on communicating model confidence in the UI. Closing unless @HaraldSchafer has thoughts on this.
