### ISSUE TITLE
Openpilot unavailable Waiting for controls to start

### ISSUE THREAD

**Issue by zeroyang0809** [commaai/openpilot#27399]
### Describe the bug

when i run the car simulation on openpilot, i meet this problem.
i run the openpilot on local(instead of docker).
there is no any error on there terminals.

![图1 (3)](https://user-images.githubusercontent.com/116786638/220122757-120e839c-c9aa-4da4-87a7-2556ff9e4ed7.png)

### Provide a route where the issue occurs

no Dongle ID 

### openpilot version

0.9.0

**Comment by zeroyang0809** [comment]
i find that my Dongle ID is none. is that normal? thanks

![2023-02-20_21-41](https://user-images.githubusercontent.com/116786638/220124430-26955f9a-e3b4-4e8a-955d-59f5ef2dd739.png)

**Comment by jon-chuang** [comment]
See also: https://github.com/commaai/openpilot/issues/27257#issuecomment-1436319753

**Comment by zeroyang0809** [comment]
thanks for your reply.
i can successfully launch the carla simulation on openpilot.
however when the car run for a few seconds,
it has this problem "take control immediately Vechicle Parameter Identification Failed".
Do you know how to fix it? Thanks
![image](https://user-images.githubusercontent.com/116786638/220256126-04d88d6f-7ace-4a32-ac82-8abc5718f1a1.png)

**Comment by joedursun** [comment]
Getting this same error on my 2020 Subaru Outback with a brand new Comma 3. I'm new to this so not sure if it's a an installation issue (I've double checked that the harness and cables are fully plugged in) or a bug in OpenPilot.

**Comment by MoreTore** [comment]
> thanks for your reply. i can successfully launch the carla simulation on openpilot. however when the car run for a few seconds, it has this problem "take control immediately Vechicle Parameter Identification Failed". Do you know how to fix it? Thanks ![image](https://user-images.githubusercontent.com/116786638/220256126-04d88d6f-7ace-4a32-ac82-8abc5718f1a1.png)

this is likely the fake gps or imu data not updating correctly. You can just disable it and add this to controlsd:

if SIMULATION:
  ignore += ['driverCameraState', 'managerState','liveParameters', 'liveTorqueParameters', 'liveLocationKalman']

**Comment by davidx** [comment]
I just experienced this too on c3x toyota prius 2017
