### ISSUE TITLE
camerad memory leak

### ISSUE THREAD

**Issue by ZwX1616** [commaai/openpilot#2739]
**Describe the bug**

camerad uses 2-3% more memory per day if run for days

**How to reproduce or log data**

run camerad for extended amount of time

**Expected behavior**

constant memory usage

**Device/Version information (please complete the following information):**
 - Device: EON/comma two
 - <s>Dongle ID:</s>
 - <s>Route:</s>
 - <s>Timestamp:</s>
 - Version: current master
 - <s>Car make/model:</s>

**Additional context**

**Comment by ZwX1616** [comment]
this might have been in camerad for ever. are you interested in looking into it? @deanlee

**Comment by deanlee** [comment]
I would love to try

**Comment by pd0wm** [comment]
Merged the PR. @ZwX1616 Can you check if the leak is gone?

**Comment by ZwX1616** [comment]
> Merged the PR. @ZwX1616 Can you check if the leak is gone?

yeah the testing closet devices have been updated. we should be able to see the difference easily

**Comment by adeebshihadeh** [comment]
Seeing no leak after two days, thanks @deanlee :)

**Comment by deanlee** [comment]
I'm glad the problem was finally solved
