### ISSUE TITLE
Driver Monitoring Camera Exposure - Request 9075

### ISSUE THREAD

**Issue by mhodalin** [commaai/openpilot#2741]
**Describe the bug**

During drive (Right Hand Drive) unit will consistently display either 'No Face Detected' or 'Driver Model Input Uncertain' causing 'Touch Steering Wheel' prompt and mode disengagement, appears to be error in exposure of driver monitoring camera while using Right Hand driver mod. Driver camera indicator will flicker consistently 

**How to reproduce or log data**

Unit will show these errors frequently during driving in all conditions

**Expected behavior**

Driver camera with correct exposure able to accurately identify face of driver while in Right Hand driver mode

**Device/Version information (please complete the following information):**
 - Device: Comma2
 - Dongle ID: 7e6bdbe1cef85fea
 - Route: 7e6bdbe1cef85fea_2020-12-08--19-35-11--0
 - Timestamp: All
 - Version: 0.7.8, 0.7.9, 0.7.10, 0.8
 - Car make/model: Toyota Rav4 Hybrid 2020

**Additional context**

Australia based with Right Hand drive engaged. Unit will consistently fail to recognize face of driver causing mode disengagement. When troubleshooting, unit has no problem identifying face of person in left hand seat. Driver camera indicator will flicker between steady and nothing observed during engagement

**Driver segmet** 

[7e6bdbe1cef85fea_2020-12-08--19-35-11--0--dcamera.zip](https://github.com/commaai/openpilot/files/5676229/7e6bdbe1cef85fea_2020-12-08--19-35-11--0--dcamera.zip)

**Attached pictures demonstrate the difference in exposure in Left and Right hand modes**

![Exposure RHS Driver Camera Low Light](https://user-images.githubusercontent.com/68986132/101841670-7e9aab00-3b9a-11eb-932c-62dd093dabab.jpg)
![Exposure RHS Driver Normal Seated Position 2 (High Light)](https://user-images.githubusercontent.com/68986132/101841676-81959b80-3b9a-11eb-86bb-e7f382507c78.jpg)
![Exposure RHS Driver Normal Seated Position Low Light](https://user-images.githubusercontent.com/68986132/101841679-85292280-3b9a-11eb-87f0-7dcde10f1d8e.jpg)
![Exposure LHS Driver Camera](https://user-images.githubusercontent.com/68986132/101841688-89edd680-3b9a-11eb-8d76-b4347a1314b7.jpg)
![Exposure RHS Driver Camera during drive](https://user-images.githubusercontent.com/68986132/101841697-8e19f400-3b9a-11eb-9527-00976abc9104.jpg)
![Exposure RHS Driver Camera Error](https://user-images.githubusercontent.com/68986132/101841703-92461180-3b9a-11eb-8249-9b594a1be22f.jpg)

**Comment by ZwX1616** [comment]
https://github.com/commaai/openpilot/commit/fef8d4093f1ebf6ad91c6bac95c465c83ee7e396

should be fixed in next release! thanks for reporting!

**Comment by mhodalin** [comment]
Thanks!
