### ISSUE TITLE
Chevy Bolt EUV Premier 2023 - Openpilot fails to restart with no Comma error message after stop and go city traffic

### ISSUE THREAD

**Issue by DerrickBarra** [commaai/openpilot#27451]
### Describe the bug

**Vehicle**
Chevy Bolt EUV 2023 Premier

**Device**
Comma 3 with Bolt EUV 2023 Harness

**Openpilot Version**
Openpilot Master Branch - February 21st 2023 release

**Description**
Openpilot fails to restart after allowing it to previously come to a complete stop in traffic.

**To Replicate**
1. Allow Openpilot to slow the Chevy Bolt down at a traffic light behind another car and come to a complete stop.
2. Allow enough time to pass so that Openpilot is not longer able to control the Bolt and will require it to be disabled and manual control by the driver to take over.
3. When traffic resumes, disengage Openpilot using the gas pedal to resume standard vehicle control and follow traffic
4. After a few seconds, attempt to re-engage Openpilot.
5. If the bug occurred, you won't see a message appear on the Comma 3. However Openpilot will fail to start with no feedback from the Comma 3 or the driver info screen on the Bolt.

**Notes**
- In one instance when this error occurred, I believe I saw a message on the Chevy Bolt's driver info screen that said "Adaptive Cruise Control Unavailable". But usually I'm not looking at the driver info screen when this error occurs so it can be hard to catch it.

**Example Route**
[Recorded Route Link](https://connect.comma.ai/3b68b660a77fd80e/1677281083389/1677282764840)
Around 18:30'ish (around 6:30PM EST) on this route is when I noticed the issue.

### Which car does this affect?

Chevy Bolt EUV Premier 2023

### Provide a route where the issue occurs

3b68b660a77fd80e|2023-02-24--18-24-43--6

### Openpilot version

f381b694013ef662c5d7638fe7b706315ce9547d

**Comment by nelsonjchen** [comment]
Hey uh, the thing is called openpilot. Just wanted to say it's a bit awkward to keep seeing a competitor's name.

**Comment by DerrickBarra** [comment]
> Contributor

Good catch! I've modified the post accordingly.

**Comment by sshane** [comment]
Unfortunately the camera does not publish anything on CAN telling us that it's faulted. Do you see any message on the dash when this happens? How long after you disengaged at a stop did this happen?

**Comment by sshane** [comment]
@DerrickBarra Does this still happen for you?

**Comment by sshane** [comment]
Any updates @DerrickBarra? Closing if not.

**Comment by sshane** [comment]
I'll try to reproduce here, it's very possible that the camera does not like seeing duplicate counters from the buttons.

![image](https://github.com/commaai/openpilot/assets/25857203/4753caf9-9e14-4601-ae9e-cb8bafd2a23b)

**Comment by adeebshihadeh** [comment]
Is this still an issue?
