### ISSUE TITLE
2023 Hyundai Tucson Hybrid identification 

### ISSUE THREAD

**Issue by ishfaaq** [commaai/openpilot#27461]
### Describe the bug

The 2023 Tucson Hybrid is identified as the ICE model because the camera and radar modules have the same Id. It works perfect once modified.

### Which car does this affect?

Hyundai Tucson Hybrid 2023

### Provide a route where the issue occurs

92c61194164c3e2e|2023-02-26--10-01-51

### openpilot version

0.9.1

### Additional info

Please let me know if you need additional info about the car

**Comment by sshane** [comment]
Hi @ishfaaq, it would be helpful if you could run a command over ssh. Are you on Discord? That might be quicker to communicate.

**Comment by ishfaaq** [comment]
I am, I posted this in the hkg channel with the username ishj. I got it to run for now by modifying values.py, but I'll happily test things.

**Comment by mathiasparks** [comment]
Hi @ishfaaq & @sshane - Looking for your post on the hkg discord, but having some trouble finding it. I attempted to setup the Comma 3 in my 2023 Hyundai Tucson Hybrid yesterday evening and got the "Dashcam Mode Car Unrecognized" message. Any chance either of you could provide a link to the resolution for this? Much appreciated :)

**Comment by sshane** [comment]
@mathiasparks can you provide your dongle id?

**Comment by not-vanished** [comment]
> @mathiasparks can you provide your dongle id?

Hey Shane, I'm a long time follower of my your branch on my C2, and super happy for you for being in the SD area. I grew up in Denton County as well! Hope your week is going well, man!

Could you help me as to locating the dongle ID, is that's physically looking at the hardware? I'm looking to get my 2023 Hyundai Tucson Hybrid running as well.

**Comment by mathiasparks** [comment]
Hey @sshane - sorry I've been out of town and am now back home. My dongle id is a1f50efb97003e30.

**Comment by sshane** [comment]
@not-vanished sorry for the late reply, yes that will be in the Device settings! Do you already have it set up?

**Comment by sshane** [comment]
@mathiasparks @not-vanished are you the same person?

**Comment by not-vanished** [comment]
> @mathiasparks @not-vanished are you the same person?

I am not the same person. Heh.

**Comment by sshane** [comment]
@not-vanished any updates?

**Comment by not-vanished** [comment]
@sshane Hey Shane, sorry for the delay. I had to fly out of town for an emergency. Let me get this info to you by the weekend.

**Comment by sshane** [comment]
No worries! Whenever you get the chance!

**Comment by sshane** [comment]
@mathiasparks adding your car in: https://github.com/commaai/openpilot/pull/28036

Doesn't seem to conflict with existing FW versions for the non-hybrid so should be safe to merge.

**Comment by sshane** [comment]
@mathiasparks adding your car in: https://github.com/commaai/openpilot/pull/28036

Doesn't seem to conflict with existing FW versions for the non-hybrid so should be safe to merge. There's been a problem where some Tucson Hybrid and ICE share identical FW versions, but everything looks fine with your car.

Did you use the Hyundai N harness?

**Comment by mathiasparks** [comment]
Thank you @sshane! Much appreciated. How do I get that build on my Comma 3? 

Regarding harness, are you referring to the Red Panda?

**Comment by not-vanished** [comment]
> No worries! Whenever you get the chance!

Hey @sshane, I messaged you directly on Discord as Kenichi#4323 with my Dongle ID and VIN. Thanks again for your help!

**Comment by not-vanished** [comment]
@sshane - @mathiasparks is actually a friend of mine! We didn’t realize we were replying to this thread together. The car is now working! Thank you so much for your help and continued contributions to the OpenPilot community.

**Comment by sshane** [comment]
Looks like you're both supported now! Let me know if there's any other issues or feedback you have!

**Comment by sohaib0004** [comment]
@sshane Hey I am having same issue with my 2024 tucsan hybrid, I have sent you friends request on discord. Hope you can help me out too

**Comment by ishfaaq** [comment]
@sohaib0004 You will need to replace the firmware(s) in the Hybrid section with the ones from the ICE section. You can just switch them around. Openpilot is currently thinking that your car is an ICE model.

**Comment by sohaib0004** [comment]
@ishfaaq can you give me quick call 3464344362. I am not familiar with github / discord so its hard for me to go inside any of the comma3 files. If you can help me with that i can change it.
