### ISSUE TITLE
micd: filter out fan frequencies

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#27473]
When the fan is running and the car is stopped, the filtered sound pressure level dBA is about 10-15 dB higher.

**Comment by adeebshihadeh** [comment]
Seems to work fine without this; still think it's necessary?

**Comment by sshane** [comment]
The volume goes up with the fan, but it may not be noticeable until the fan is near max. I haven't evaluated how bad it is across the fleet yet. Should plot how much db increases with fan percentage/rpm

**Comment by adeebshihadeh** [comment]
Seems fine, we can reopen if we noticed it
