### ISSUE TITLE
Smoother Lane Change Cancellation

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#27488]
It would be nice if when you're in the process of lane changing that you can cancel out of it anytime by just going against the torgue of openpilot.

From my experience when I don't want to merge anymore I have to really fight against the torque from the comma. It would be nice if it detects a sudden change against the torque that it will simply stop merging instead of it trying to merge still.

**Comment by HaraldSchafer** [comment]
This isn't really feasible to do reliable in the way we train lane changes now.
