### ISSUE TITLE
Lexus ES 2019 - “dashcam mode, car unsupported” error

### ISSUE THREAD

**Issue by AwesomeJiefu** [commaai/openpilot#27501]
### Describe the bug

Hi,
Can any one help me with this error? 
My dongle ID is e5fc06c3b27fb519.

### Which car does this affect?

LEXUS ES300h 2019

### Provide a route where the issue occurs

e5fc06c3b27fb519|2023-03-05--17-32-36

### openpilot version

0.9.1

**Comment by ErichMoraga** [comment]
This is just a fingerprint issue, as discussed in your Discord post...
https://discord.com/channels/469524606043160576/524327905937850394/1082357724521693286

https://github.com/commaai/openpilot/wiki/Fingerprinting

I also received your email an hour ago, but you didn't add me to your DongleID.  Be sure to see my pinned msg. in #toyota-lexus for more details.
