### ISSUE TITLE
2018 Kia Stinger 2.0L Premium "Can Error: Check connections" $200 Bounty

### ISSUE THREAD

**Issue by oricalworks** [commaai/openpilot#2750]
Describe the bug
Openpilot gives me "Can Error: Check connections" when everything is connected properly in my 2018 Kia Stinger 2.0L Premium.

How to reproduce or log data
Not really sure I've checked all connections and virtually Chris verified my connections were correct too. I just got my comma 2 today and installed it.

Expected behavior
Openpilot Engagement

Device/Version information (please complete the following information):

Device: comma two
Dongle ID: 98b4e32baa5d21ec
Routes: d98b4e32baa5d21ec|2021-01-01--11-58-38 , 98b4e32baa5d21ec|2021-01-02--11-31-44
Version: 0.8.
Car make/model: 2018 Kia Stinger 2.0L Premium

https://my.comma.ai/cabana/?route=dbad5babdf6cf346%7C2020-12-15--10-16-07&exp=1639604724&sig=ZUS9W1SkM1end94dF%2FivOygNHKQ0%2FTxO1onx3smPyAk%3D&max=8&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fdbad5babdf6cf346%2F065dff135063635fca7bd68aa9694319_2020-12-15--10-16-07
https://drive.google.com/file/d/1LIb6QWQW2TnmNcPguKAT5jMMbYcYG0yu/view?usp=sharing
https://drive.google.com/file/d/1trgluKPWqrfoqe5oUld879NRuzjw2XbC/view?usp=sharing

$200 - Bounty (To claim bounty Openpilot must engage and steer, contact me @ Oricalworks@Gmail.com (Zelle, Paypal))

**Comment by adeebshihadeh** [comment]
Can you edit your post and fill out the bug report template?

**Comment by oricalworks** [comment]
Describe the bug
Openpilot gives me "Can Error: Check connections" when everything is connected properly in my 2018 Kia Stinger 2.0L Premium.

How to reproduce or log data
Not really sure I've checked all connections and virtually Chris verified my connections were correct too. I just got my comma 2 today and installed it.

Expected behavior
Openpilot Engagement 

Device/Version information (please complete the following information):

Device: comma two
Dongle ID: dbad5babdf6cf346
Route: dbad5babdf6cf346|2020-12-11--17-46-20 , dbad5babdf6cf346|2020-12-11--13-13-52
Version: 0.8.
Car make/model: 2018 Kia Stinger 2.0L Premium

**Comment by oricalworks** [comment]
> Can you edit your post and fill out the bug report template?

done :)

**Comment by oricalworks** [comment]
Looking to buy whom ever fixes it a couple of coffees. :)

**Comment by oricalworks** [comment]
Here is my fingerprint from workbench 67: 8, 127: 8, 304: 8, 320: 8, 339: 8, 356: 4, 358: 6, 544: 8, 576: 8, 593: 8, 608: 8, 688: 5, 809: 8, 854: 7, 870: 7, 871: 8, 872: 8, 897: 8, 902: 8, 909: 8, 916: 8, 1040: 8, 1042: 8, 1056: 8, 1057: 8, 1078: 4, 1107: 5, 1136: 8, 1151: 6, 1168: 7, 1170: 8, 1173: 8, 1184: 8, 1265: 4, 1280: 1, 1287: 4, 1290: 8, 1292: 8, 1294: 8, 1312: 8, 1322: 8, 1345: 8, 1348: 8, 1363: 8, 1369: 8, 1379: 8, 1384: 8, 1407: 8, 1419: 8, 1427: 6, 1456: 4, 1470: 8, 2000: 8, 2004: 8, 2008: 8, 2012: 8

**Comment by robbaker92** [comment]
If you are still having this problem try to remove the car for line 333 of values.py.

**Comment by oricalworks** [comment]
> If you are still having this problem try to remove the car for line 333 of values.py.
which car?
DBC = {
  CAR.ELANTRA: dbc_dict('hyundai_kia_generic', None),
  CAR.ELANTRA_GT_I30: dbc_dict('hyundai_kia_generic', None),
  CAR.GENESIS_G70: dbc_dict('hyundai_kia_generic', None),
  CAR.GENESIS_G80: dbc_dict('hyundai_kia_generic', None),
  CAR.GENESIS_G90: dbc_dict('hyundai_kia_generic', None),
  CAR.HYUNDAI_GENESIS: dbc_dict('hyundai_kia_generic', None),
  CAR.IONIQ_EV_2020: dbc_dict('hyundai_kia_generic', None),
  CAR.IONIQ_EV_LTD: dbc_dict('hyundai_kia_generic', None),
  CAR.IONIQ: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_FORTE: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_NIRO_EV: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_OPTIMA: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_OPTIMA_H: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_SORENTO: dbc_dict('hyundai_kia_generic', None),
  CAR.KIA_STINGER: dbc_dict('hyundai_kia_generic', None),
  CAR.KONA: dbc_dict('hyundai_kia_generic', None),
  CAR.KONA_EV: dbc_dict('hyundai_kia_generic', None),
  CAR.SANTA_FE: dbc_dict('hyundai_kia_generic', None),
  CAR.SONATA: dbc_dict('hyundai_kia_generic', None),
  CAR.SONATA_2019: dbc_dict('hyundai_kia_generic', None),
  CAR.PALISADE: dbc_dict('hyundai_kia_generic', None),
  CAR.VELOSTER: dbc_dict('hyundai_kia_generic', None),
}

**Comment by robbaker92** [comment]
# these cars use the FCA11 message for the AEB and FCW signals, all others use SCC12
  "use_fca": set([CAR.SONATA, CAR.ELANTRA, CAR.ELANTRA_GT_I30, CAR.KIA_STINGER, CAR.IONIQ, CAR.IONIQ_EV_2020, CAR.KONA_EV, CAR.KIA_FORTE, CAR.KIA_NIRO_EV, CAR.PALISADE, CAR.GENESIS_G70, CAR.KONA]), look for this in values.py in Hyundai and remove the CAR.KIA_STINGER,

**Comment by oricalworks** [comment]
Opps i was looking in release2 were you referring to master?

**Comment by robbaker92** [comment]
Release2 is okay it’s a bit higher up the page than what you have got in your other comment

**Comment by oricalworks** [comment]
@robbaker92 I added you to my fork, sorry for my stupidity if I'm mistaken.

**Comment by oricalworks** [comment]
Done

**Comment by oricalworks** [comment]
@robbaker92 Thanks for all your help I truly appreciate it!

**Comment by robbaker92** [comment]
Let me know if you have any more problems.

**Comment by oricalworks** [comment]
I'm still getting Can Error check connections

**Comment by robbaker92** [comment]
You can try xxx979xxx’s 8.0 branch. Use “ cd /data/openpilot
git remote add xx979xx https://github.com/xx979xx/openpilot.git
git fetch --all” and then “git checkout 8.0”. After your need to and the fingerprint back in. Check if it’s made a difference, if not then try to remove the same thing from value.py.

**Comment by oricalworks** [comment]
hmm I'm sure i didn't do any typos when adding a new array. On the new branch it endlessly hangs at this point
```
root@localhost:/data/openpilot$ ./launch.sh
Using interface 'wlan0'
OK
/data/openpilot/launch_chffrplus.sh: line 29: echo: write error: No such device
/data/openpilot/launch_chffrplus.sh: line 31: echo: write error: No such device
/data/openpilot/launch_chffrplus.sh: line 34: echo: write error: No such device
/data/openpilot/launch_chffrplus.sh: line 35: echo: write error: No such device
/data/openpilot/launch_chffrplus.sh: line 38: echo: write error: No such device
dinfo 1920x1080
egl version 1.4
egl w 1920 h 1080
gl version OpenGL ES 3.2 V@145.0 (GIT@I0ac3940325)
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang -o selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_solver.os -c -std=gnu11 -DQCOM -mcpu=cortex-a57 -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -DQCOM -mcpu=cortex-a57 -fPIC -Iphonelibs/acado/include -Iphonelibs/acado/include/acado -Iphonelibs/qpoases/INCLUDE -Iphonelibs/qpoases/INCLUDE/EXTRAS -Iphonelibs/qpoases/SRC -Iphonelibs/qpoases -Iselfdrive/controls/lib/lateral_mpc/lib_mpc_export selfdrive/controls/lib/lateral_mpc/lib_mpc_export/acado_solver.c
clang -o selfdrive/controls/lib/longitudinal_mpc/lib_mpc_export/acado_solver.os -c -std=gnu11 -DQCOM -mcpu=cortex-a57 -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -DQCOM -mcpu=cortex-a57 -fPIC -Iphonelibs/acado/include -Iphonelibs/acado/include/acado -Iphonelibs/qpoases/INCLUDE -Iphonelibs/qpoases/INCLUDE/EXTRAS -Iphonelibs/qpoases/SRC -Iphonelibs/qpoases -Iselfdrive/controls/lib/longitudinal_mpc/lib_mpc_export selfdrive/controls/lib/longitudinal_mpc/lib_mpc_export/acado_solver.c
clang -o selfdrive/controls/lib/longitudinal_mpc_model/lib_mpc_export/acado_solver.os -c -std=gnu11 -DQCOM -mcpu=cortex-a57 -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -DQCOM -mcpu=cortex-a57 -fPIC -Iphonelibs/acado/include -Iphonelibs/acado/include/acado -Iphonelibs/qpoases/INCLUDE -Iphonelibs/qpoases/INCLUDE/EXTRAS -Iphonelibs/qpoases/SRC -Iphonelibs/qpoases -Iselfdrive/controls/lib/longitudinal_mpc_model/lib_mpc_export selfdrive/controls/lib/longitudinal_mpc_model/lib_mpc_export/acado_solver.c

```

**Comment by robbaker92** [comment]
If your using workbench then try the install button in that use xxx979xxx fork and 8.0 branch

**Comment by oricalworks** [comment]
Good Morning! I just reinstalled using workbench. It is still hanging on that process from last night.

**Comment by robbaker92** [comment]
Reboot a couple of times

**Comment by oricalworks** [comment]
Ok so I added my fingerprint and got CAN Error: check connections and same thing when I took CAR.stinger out of that "use_fca": set([CAR.SONATA, CAR.ELANTRA, CAR.ELANTRA_GT_I30, CAR.KIA_STINGER, CAR.IONIQ, CAR.IONIQ_EV_2020, CAR.KONA_EV, CAR.KIA_FORTE, CAR.KIA_NIRO_EV, CAR.PALISADE, CAR.GENESIS_G70, CAR.KONA]) and still got same Can error

**Comment by robbaker92** [comment]
run the command "git submodule update --init" with two minus symbols before init. and then reboot.

**Comment by oricalworks** [comment]
Ok done same issue still i'm going to upload a video of my setup.

**Comment by oricalworks** [comment]
https://drive.google.com/file/d/17iSVhIJ8ldI6jruoDp6GL4f18aht5HOe/view?usp=sharing

**Comment by robbaker92** [comment]
in useradmin is it showing a platform?

**Comment by oricalworks** [comment]
it says kia stinger GT2
https://my.comma.ai/useradmin/?onebox=98b4e32baa5d21ec

**Comment by oricalworks** [comment]
here is my dongle id 
98b4e32baa5d21ec

**Comment by robbaker92** [comment]
can you make a drive public

**Comment by oricalworks** [comment]
https://my.comma.ai/98b4e32baa5d21ec/1609597910177/1609599138412
https://my.comma.ai/cabana/?route=98b4e32baa5d21ec%7C2021-01-02--09-31-50&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F98b4e32baa5d21ec%2F3f9a50846fd0f8dfb69401d62541eeec_2021-01-02--09-31-50&seekTime=540

**Comment by oricalworks** [comment]
did that work?

**Comment by oricalworks** [comment]
im so stupid 
98b4e32baa5d21ec|2021-01-02--11-31-44 is now public

**Comment by oricalworks** [comment]
here is another one 98b4e32baa5d21ec|2021-01-01--11-58-38

**Comment by robbaker92** [comment]
Can't see anything that I think is making this error, sorry I can't be more helpful. Discord might have a fix.

**Comment by oricalworks** [comment]
@robbaker92 Thanks so much for all your help and dedication! I really appreciate it!

**Comment by oricalworks** [comment]
what channel should I post on?

**Comment by robbaker92** [comment]
Give installation-help a go.

**Comment by oricalworks** [comment]
once again thanks for your help

**Comment by oricalworks** [comment]
@robbaker92 Hey I've made some progress and have a different error now but no can errors.
It says "openpilot unavailable: waiting for controls to start".
I'm using this repository which is a fork of the HKG community branch
https://github.com/Circuit-Pro/openpilot

**Comment by oricalworks** [comment]
and I had an issue where my fingerprint was not correct. Here is the correct one 
67: 8, 127: 8, 304: 8, 320: 8, 339: 8, 356: 4, 358: 6, 544: 8, 576: 8, 593: 8, 608: 8, 688: 5, 809: 8, 854: 7, 870: 7, 871: 8, 872: 8, 897: 8, 902: 8, 909: 8, 916: 8, 1040: 8, 1042: 8, 1056: 8, 1057: 8, 1078: 4, 1107: 5, 1136: 8, 1151: 6, 1168: 7, 1170: 8, 1173: 8, 1184: 8, 1265: 4, 1280: 1, 1287: 4, 1290: 8, 1292: 8, 1294: 8, 1312: 8, 1322: 8, 1345: 8, 1348: 8, 1363: 8, 1369: 8, 1379: 8, 1384: 8, 1407: 8, 1419: 8, 1427: 6, 1456: 4, 1470: 8

**Comment by oricalworks** [comment]
@xps-genesis @xx979xx  Hey would you guys possibly have any ideas? Any are greatly appreciated! :)

**Comment by xps-genesis** [comment]
Have you tried my fork?

**Comment by xps-genesis** [comment]
URL: https://github.com/xps-genesis/openpilot.git
Branch: xps

**Comment by oricalworks** [comment]
Ill try it now

**Comment by oricalworks** [comment]
@xps-genesis Ok so it says dashcam mode ill fork yours and add my fingerprint

**Comment by xps-genesis** [comment]
Dashcam mode is not because of fingerprint. My fork would say fingerprint unrecognized if that was the issue. Did you turn on the community features toggle in settings?

**Comment by oricalworks** [comment]
hmm let me double check

**Comment by oricalworks** [comment]
yes community features are on. Still having same issue. "Dashcam Mode for unsupported car"

**Comment by xps-genesis** [comment]
dm me on discord xps#8163

**Comment by oricalworks** [comment]
@xps-genesis Hey just got the replacement. It appears to be working because car now has a slew of errors when its plugged it that it never had.

**Comment by oricalworks** [comment]
https://drive.google.com/file/d/1BNwZ144cGKP9lRlDXnF90QWl_T4IvkHO/view?usp=sharing

**Comment by oricalworks** [comment]
Fixed issue bad Hyundai type C harness with bad connection.

**Comment by JoshuaHarrisJBh** [comment]
> and I had an issue where my fingerprint was not correct. Here is the correct one 
> 
> 67: 8, 127: 8, 304: 8, 320: 8, 339: 8, 356: 4, 358: 6, 544: 8, 576: 8, 593: 8, 608: 8, 688: 5, 809: 8, 854: 7, 870: 7, 871: 8, 872: 8, 897: 8, 902: 8, 909: 8, 916: 8, 1040: 8, 1042: 8, 1056: 8, 1057: 8, 1078: 4, 1107: 5, 1136: 8, 1151: 6, 1168: 7, 1170: 8, 1173: 8, 1184: 8, 1265: 4, 1280: 1, 1287: 4, 1290: 8, 1292: 8, 1294: 8, 1312: 8, 1322: 8, 1345: 8, 1348: 8, 1363: 8, 1369: 8, 1379: 8, 1384: 8, 1407: 8, 1419: 8, 1427: 6, 1456: 4, 1470: 8
