### ISSUE TITLE
Cold start dashcam mode full boot

### ISSUE THREAD

**Issue by Miniz199922** [commaai/openpilot#27504]
### Describe the bug

Woke up this morning started the jeep and got dashcam mode after comma logo loaded.  Not sure if its missing a finger print?
5c77528ab6bf019a|2023-03-06--07-21-29--0 - dashcam mode.
5c77528ab6bf019a|2023-03-06--07-30-46--0 - restarted car no dashcam mode.

### Provide a route where the issue occurs

5c77528ab6bf019a|2023-03-06--07-21-29--0

### openpilot version

0.9.0

**Comment by Miniz199922** [comment]
missing this  1239: 8, 1256: 8, 1879: 8. will test and let know. Submitted pull request

**Comment by sshane** [comment]
https://github.com/commaai/openpilot/pull/27649
