### ISSUE TITLE
Wrong speed when using longitudinal control

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#27507]
### Describe the bug

When using longitudinal control, Comma3 is setting GPS Speed instead of cars speedometer speed.
So e.g. setting to max 35 kmh is resulting to 39kmh. See pic.

When not using longitudinal control, the speed is correct.

![image](https://user-images.githubusercontent.com/96002277/223221960-7a420184-955d-4839-9009-80ee4c33a719.png)

### Provide a route where the issue occurs

6111bd7df5043394|2023-03-06--14-28-47--0

### openpilot version

master

### Additional info

Kia Niro EV

Synced Fork of Master:
https://github.com/DerGue69/openpilot

**Comment by morrislee** [comment]
i have this issue too, but not as bad as yours. I am also in kph, around 2 kph higher than set speed pretty much any speeds
