### ISSUE TITLE
Car is breaking too late using Longitudinal Control

### ISSUE THREAD

**Issue by DerGue69** [commaai/openpilot#27521]
### Describe the bug

I started using Longitudinal Control on my Kia Niro EV.
When approching standing cars, I have the feeling that the car starts breaking too late.
And I also have the feeling that the car is dringing in the car in front - so when I am too close, I have to use the breaks.

My suggestion: Start breaking earlier. Keep more distance to car in front before cars come to standstill. 

![image](https://user-images.githubusercontent.com/96002277/223464158-6514ee18-e466-45cd-9729-f5325f681a65.png)

### Provide a route where the issue occurs

6111bd7df5043394|2023-03-07--15-12-34--3

### openpilot version

master

**Comment by sshane** [comment]
This looks like a control issue. We were commanding brake, but the car released brakes and coasted forward, right around the time we set the StopReq bit to 1, and ramped down accel.

![Screenshot from 2023-03-24 20-12-34](https://user-images.githubusercontent.com/25857203/227689017-2714f0c7-c6de-4fab-93bd-252dece31cab.png)

**Comment by sshane** [comment]
@DerGue69 does this still happen?

**Comment by DerGue69** [comment]
Hi Shane.
Yes. Recently I installed 0.9.4 Master ans tested again.
When a large object is in front, it is a gamble, if he stops or nit.

**Comment by DerGue69** [comment]
I opened another issue some time ago:
https://github.com/commaai/openpilot/issues/28917#event-9825544881

**Comment by DerGue69** [comment]
Currently I do not use LC.

**Comment by sshane** [comment]
Please send routes for recent cases.

**Comment by DerGue69** [comment]
That was the last case I recorded:
https://github.com/commaai/openpilot/issues/28917#event-9825544881

I will enable LC after vacation and try to enforce again.

**Comment by adeebshihadeh** [comment]
Controls have been retuned quite a bit since this was opened.
