### ISSUE TITLE
OP failed mid-drive with error

### ISSUE THREAD

**Issue by paulpark2020** [commaai/openpilot#27523]
### Describe the bug

OP failed mid-drive with "process not running" error. 

### Provide a route where the issue occurs

https://connect.comma.ai/9db428338427dec2/1678164069221/1678165783236

### openpilot version

0.9.1

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/commit/ce900f34d08b423e9f3ebed0d028692bb9198dea fixed with this
