### ISSUE TITLE
Process not running - ubloxd

### ISSUE THREAD

**Issue by kevinharbin** [commaai/openpilot#27592]
### Describe the bug

Driving normally while engaged. Device disengaged with Process not running - ubloxd.
On reboot no issues.

### Provide a route where the issue occurs

35c004509e3057f2|2023-03-14--16-23-52--0

### openpilot version

release

**Comment by HaraldSchafer** [comment]
This is due to corrupt data being read in from the satellites and not being handled correctly.

Was fixed in master.
https://github.com/commaai/openpilot/commit/ce900f34d08b423e9f3ebed0d028692bb9198dea
