### ISSUE TITLE
no panda, lsusb shows, Bus 001 Device 006: ID bbaa:ddcc

### ISSUE THREAD

**Issue by babygodzilla** [commaai/openpilot#27622]
### Describe the bug

comma 3, on 0.91 stock, shows no panda
attempted recover.sh, and panda flash
factory reset multiple times, installed stock openpilot 0.91

ran lsusb,
comma@tici:/data/openpilot$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID bbaa:ddcc
Bus 001 Device 005: ID 2c7c:0125 Quectel Wireless Solutions Co., Ltd. EC25 LTE modem
Bus 001 Device 002: ID 0000:0000
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Bus 001 Device 006: ID bbaa:ddcc , is detected,

however, my comma3 device shows no panda

### Provide a route where the issue occurs

c30d8b3a347db8ff

### openpilot version

0.91

**Comment by adeebshihadeh** [comment]
The USB connection to your panda seems flaky. Try unplugging the device for 30 minutes to let the super caps fully drain. If that doesn't work, email to support@comma.ai and we'll get it swapped out for you.
