### ISSUE TITLE
Intermittent "controls are lagging" and "communications between processes is slow" Error message - Honda Accord

### ISSUE THREAD

**Issue by MeterPucha** [commaai/openpilot#27643]
### Describe the bug

Sometimes when I first start my car I get intermittent "controls are lagging" and "communications between processes is slow" error messages sometimes leading to a disengagement. 
I have reloaded openpilot and still happens. I dont know how to reproduce the problem, but it has happened on 4 separate occasions.
There is no damage to the device always hangs on the window. Never took it apart either.

### Provide a route where the issue occurs

b9028def8e733ee6|2023-03-17--18-25-25

### openpilot version

0.9.1

Update 3/29
I had another error message this morning, this time when trying to engage openpilot. Trip id b9028def8e733ee6|2023-03-29--06-34-39--0. Don't know exact content of the message because it flashed by quickly, but something about cannot engage due to encoder. Please let me know what I can do to fix it.

**Comment by krvista** [comment]
Hi!

I updated my Comma 3 to the latest 0.9.2 a few hours ago.
Then I retrained my device. 
After recalibration, I pushed the sunroof button several times to close and open.
And finally I got the lagging messages.
The full logs were uploaded via WiFi.
At the end of these drives, you can find the error points.

8014970252341f77|2023-05-25--20-45-59--3
8014970252341f77|2023-05-25--20-53-41--0

Thank you for your attention!

**Comment by powers68232** [comment]
I just had the same errors displayed on my new Comma 3 this morning during two different drives. It has the latest stable release. It also disabled once with a red error screen. I have it unplugged at the moment and will see if the error continues after reconnecting. This is on a 19 Chrysler Pacifica

**Comment by adeebshihadeh** [comment]
@powers68232 what's your dongle ID?

**Comment by jmontgomery1848** [comment]
I have the same problem now in my 2023 Hyundai Elantra hybrid

**Comment by adeebshihadeh** [comment]
Still experiencing this on 0.9.3-release?
