### ISSUE TITLE
Getting car unrecognized message on supported car

### ISSUE THREAD

**Issue by sdvolks12** [commaai/openpilot#27661]
### Describe the bug

![image](https://user-images.githubusercontent.com/128758584/227390195-9c973626-45aa-464c-a3db-ad4b5dcacf53.jpg)

### Which car does this affect?

2019 Volkswagen Arteon SEL-P

### Provide a route where the issue occurs

https://connect.comma.ai/32011e33e8b1b837/1679613721742/1679616063256

### openpilot version

0.9.1

**Comment by sshane** [comment]
Can you try this branch? https://github.com/commaai/openpilot/pull/27671

Installer URL would be: https://installer.comma.ai/commaai/vw-arteon-fp

**Comment by sdvolks12** [comment]
Installing now

**Comment by sdvolks12** [comment]
![Uploading ED93BDD4-3033-4EDD-BE6E-A51FAFCE1F5D.jpeg…]()

**Comment by sdvolks12** [comment]
![75D6B73E-8DC2-4758-AE81-300DEAB5EDBF](https://user-images.githubusercontent.com/128758584/227655531-20321b06-2368-49d0-8a45-56698013af5d.jpeg)

It stays on this screen

**Comment by sshane** [comment]
Try to start the comma three while the car is off, and let it flash the panda. Then it should work.

**Comment by sdvolks12** [comment]
Works now thank you!

**Comment by sshane** [comment]
Merged! You're welcome to switch to any of these branches to stay up to date: `master`, `master-ci`, or `nightly`
