### ISSUE TITLE
CANParser: parse all signals from specified messages

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#27695]
Many of the lines in a car port are spent on whitelisting signals to be parsed out. The CANParser should be fast enough now that we can simply whitelist messages and parse out all their signals.

- [x] remove the signals arg from the CANParser input, see https://github.com/commaai/opendbc/pull/610 as a starting point
- [ ] add a test case to the [car unit tests](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/test_models.py) to ensure parsing time is reasonable
- [ ] if the test fails, optimize the CANParser until it doesn't

**Comment by adeebshihadeh** [comment]
@deanlee want to try this one out?

**Comment by deanlee** [comment]
Submitted a small pr to improve the performance of query_latest. https://github.com/commaai/opendbc/pull/795

I'm still reading https://github.com/commaai/opendbc/pull/610 to see if there are other parts that need to be optimized.

**Comment by adeebshihadeh** [comment]
> I'm still reading [commaai/opendbc#610](https://github.com/commaai/opendbc/pull/610) to see if there are other parts that need to be optimized.

I think we should start with the test case to ensure all the optimization PRs are strictly improving performance. Would be nice to have a simple check on parsing performance in opendbc, in addition to the one for cars that will live in openpilot.

**Comment by adeebshihadeh** [comment]
@sshane how's this coming along?
