### ISSUE TITLE
Ford: brief unknown gear shifter position while driving

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#27709]
```
54827bf84c38b14f|2023-03-26--10-40-08--11
```

Briefly changed from "Drive" to "UnknownPosition", according to the DBC. May need to add some hysteresis.

![image](https://user-images.githubusercontent.com/8762862/228088160-c5d18c89-612c-4623-a4a1-50b7303db0ef.png)

**Comment by sshane** [comment]
The message actually timed out for more than 0.5 seconds during this event as well, it looks like there was some actual communication or sensor issue. The counter is also spotty. Checking out the fleet data for this.

![image](https://user-images.githubusercontent.com/25857203/235578811-c7e31539-da0e-4a2a-a850-6751b544bcbe.png)

**Comment by sshane** [comment]
Only saw this on our car, one other time in Feb, but not a lot of rlogs to go off of. The ECU timed out sending messages, so I'm not sure using hysteresis is the best way to handle this. canValid didn't fall because the message timed out for 5x its rate, not 10x like we check for.

**Comment by incognitojam** [comment]
Had the same alert again, believe it is the same issue
https://connect.comma.ai/54827bf84c38b14f/1684223584919/1684223607328

**Comment by sshane** [comment]
@incognitojam I know we discussed switching to the message from the engine/transmission instead of the flaky knob position message. Was there any issues with the engine/transmission message?

**Comment by incognitojam** [comment]
From what I can remember the signal from the gear shifter was the one which didn't go to "neutral / no gear" when the transmission changed gear. If we change this I think the Lincoln also had some differences which we should check too.

**Comment by sshane** [comment]
Fixed by https://github.com/commaai/openpilot/pull/32886
