### ISSUE TITLE
ui: ignore steering icon double taps

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#27703]
### Describe the bug

When tapping the steering icon in the upper right corner to switch between chill and experimental modes, a second tap is sometimes registered causing the mode to change twice rapidly which results in the mode basically staying the same.

This is most likely to happen while driving while the device and user are in motion. A small button tap delay such as 0.5s may help with this.

### Provide a route where the issue occurs

1a5d045d2c531a6d

### openpilot version

master

**Comment by sshane** [comment]
Not sure exactly how the touch event works, but you might be able to override the event handler and do nothing if a double tap is registered

**Comment by MoreTore** [comment]
I was just working on something similar in another project. I will make a pr to fix this.
