### ISSUE TITLE
ui: nav does not show when changing destination

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#27710]
nav does not show when you change destination without clearing it

**Comment by royjr** [comment]
Nav: only open map once on destination set https://github.com/commaai/openpilot/pull/21650
https://github.com/commaai/openpilot/blob/3555a08c17af6c1ef22d75345a78ff6f670b1d66/selfdrive/ui/qt/maps/map.cc#L129-L132

**Comment by sshane** [comment]
It looks like clearing the nav destination should reset `allow_open`. But since I tapped another destination with a route already set, it didn't pop up again.

**Comment by sshane** [comment]
@incognitojam this should be a simple one to knock out

**Comment by sshane** [comment]
Also think it should exit the nav settings view when it gets a new route from your phone

**Comment by incognitojam** [comment]
I'm not really sure the original issue is a bug - if you hide the map while navigating do you always want it to open again if you change the destination?

**Comment by adeebshihadeh** [comment]
Yes, I think so.

**Comment by sshane** [comment]
@deanlee want to do this? We should just mirror what navd.py does:

https://github.com/commaai/openpilot/blob/7f02cb9fafb05e77dcbd2b11f41ecb8244f641fe/selfdrive/navd/navd.py#L109
