### ISSUE TITLE
Change fingerprint in lauch_openpilot.sh and get CAN Error: Check Connections

### ISSUE THREAD

**Issue by Jackie890621** [commaai/openpilot#27718]
### Describe the bug

The default fingerprint in ```launch_openpilot.sh``` is *HONDA CIVIC 2016*.
And I wanted to try different cars, so I printed out to see the cars that openpilot supports

![Screenshot from 2023-03-23 20-51-55](https://user-images.githubusercontent.com/66109376/228289597-3067c0da-7db5-4a8b-a580-0a5746932847.png)

As shown in above image, I choose the first one *HONDA ACCORD 2018*.
And I got the error when running ```bridge.py```

![Screenshot from 2023-03-23 20-16-05](https://user-images.githubusercontent.com/66109376/228291235-f42891c2-182a-47dc-977d-580e04d7efac.png)

The accord 2018 and civic 2016 are both belong to HONDA, anything went wrong???

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
This isn't expected to work. Changing cars isn't currently supported in the simulator.

**Comment by Jackie890621** [comment]
OK~~~Thanks
Can I know which parts of code restrict this?

**Comment by GHANINEAMAYAS** [comment]
i have the same problem , can you help me to resolve this problem
