### ISSUE TITLE
Openpilot build (sons -u -j$(nproc)): "Deprecated tool 'qt' renamed to 'qt3'. "

### ISSUE THREAD

**Issue by Eso2000** [commaai/openpilot#27765]
### Describe the bug

Hi,
when trying to build openpilot with:

$ _scons -u -j$(nproc)_

I get the following:

_scons: Readig SConscript files ...
scons: ** Deprecated tool 'qt' renamed to 'qt3'. Please update your build accordingly. 'qt3' will be removed entirely in a future release. File ".../openpilot/SConstruct", line 314, in module._ 

Could somebody please assist?
Thank you.

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
This is an issue with newer scons versions. Ensure you're installing the pinned version from the `poetry.lock` file.
