### ISSUE TITLE
PlotJuggler does not load whole routes like Cabana offline

### ISSUE THREAD

**Issue by rockerrock137** [commaai/openpilot#27823]
Case of use:
When use Cabana and PlotJuggler with offline/local files from realdata folder I wish to load whole routes in PlotJuggle also.

In cabana, ./cabana and select folder of route, whole route loaded.

In plotjuggle, ./juggle.py "folder/to/route" not work, too many arguments, expected 2
in plutjuggle, ./juggle.py "folder/to/route/rlogFile", 60 second of route load, only portion of route

Very nice to document how to or modify PJ to work like cabana to load whole route at a time from realdata/rlog local file

**Comment by ntegan1** [comment]
https://github.com/commaai/openpilot/pull/24473#issue-1230103216

I have examples of using on local data here, where local plotjuggler functionality was added.
As well as some commands on how to re-organize the segment folders into expected folder names.

Also see the test cases here  
https://github.com/commaai/openpilot/blob/master/tools/lib/tests/test_route_library.py
for more examples on supported usage
