### ISSUE TITLE
KIA EV6 - Check Parking Assist / Dashboard Sensors Preview Blinking

### ISSUE THREAD

**Issue by BlackwellDev** [commaai/openpilot#27885]
### Describe the bug

Using latest 0.9.2 master-ci with commit 4eb48f55b4d14188ecd41c6fa124c56fe9164ad4 (taco2) changes fully disables all safety/parking assist features (sensors, 360 camera, blinker cameras, self parking, proximity braking, etc) making this unacceptable. 

Commenting out line {0x7B1, 1, 8}, in board/safety/safety_hyundai_canfd.h restores cameras and sensors, but dashboard preview of sensors is freaking out and self-parking fully broken. 

Here are videos of the bug:
https://user-images.githubusercontent.com/23108129/231481760-3fc13183-adfd-4119-a743-069d8dd596d7.mp4
https://user-images.githubusercontent.com/23108129/231481766-07281782-04ee-450e-917b-f367132d5024.mp4

This is definitely something that needs to be addressed before full support rollout in the future :)

### Which car does this affect?

2022 KIA EV6 GT-LINE AWD (HDA2)

### Provide a route where the issue occurs

N/A

### openpilot version

0.9.2 master-ci with taco2 panda

**Comment by sshane** [comment]
The taco2 branch is not release software, and is especially experimental, and so these issues are currently expected.
