### ISSUE TITLE
Replay CAN messages on PC.  boardd_old.py doesnt exist anymore

### ISSUE THREAD

**Issue by Eso2000** [commaai/openpilot#27909]
### Describe the bug

Hello, 
In order to Stream CAN messages to my PC, I would like to use the replay tool. In the ReadME it says:

### Used Instructions:
"""
In order to replay specific route:
MOCK=1 selfdrive/boardd/tests/boardd_old.py
In another terminal:
tools/replay/replay <route-name>
"""
but the boardd_old.py doesnt exist anymore. Is there a replacement for this?
Thank you in advance!

### OS Version

Ubuntu 20.04

**Comment by MoreTore** [comment]
> ### Describe the bug
> 
> Hello, In order to Stream CAN messages to my PC, I would like to use the replay tool. In the ReadME it says:
> ### Used Instructions:
> 
> """ In order to replay specific route: MOCK=1 selfdrive/boardd/tests/boardd_old.py In another terminal: tools/replay/replay """ but the boardd_old.py doesnt exist anymore. Is there a replacement for this? Thank you in advance!
> ### OS Version
> 
> Ubuntu 20.04
> ### openpilot version or commit
> 
> _No response_
> ### Additional info
> 
> _No response_

Just run Cabana in streaming mode

**Comment by adeebshihadeh** [comment]
Fixed this up in #27975; feel free to open a PR to further improve it.
