### ISSUE TITLE
UI watchdog reset when scrolling device after incompatible NVME installation/removal.

### ISSUE THREAD

**Issue by MoreTore** [commaai/openpilot#27916]
### Describe the bug

Today I tried to install an nvme drive into my C3 but it caused many issues and later figured out that the nvme must be a specific type. Now after removing the ssd and resetting the device (it corrupted stuff) I am getting UI watchdog resets whenever I try to scroll on any menu. I tried to factory reset again, but now I am stuck on the terms and conditions agreement unable to scroll without the UI crashing. 

I am on a branch of master-ci that was working and is working for other people.

I will keep trying things

**Comment by Verylukyguy** [comment]
https://github.com/commaai/agnos

**Comment by MoreTore** [comment]
Yea I'm going to reflash it
