### ISSUE TITLE
Dash Cam unrecognized

### ISSUE THREAD

**Issue by DanSantaCruz** [commaai/openpilot#28023]
### Describe the bug

2023 Hyundai Santa Cruz, Dash Cam not recognized

### Which car does this affect?

2023 Hyundai Santa Cruz

### Provide a route where the issue occurs

all

### openpilot version

Dont know

**Comment by sshane** [comment]
Can you provide your dongle id? It will be in device settings

**Comment by DanSantaCruz** [comment]
Good morning,

Thank you for your response. Dongle and serial in attachment.

It is 617bb607e012533e

Serial Number bad7504c

Thank you,
Dan

**Comment by sshane** [comment]
Hi, your car's fingerprints were added here 2 months ago, but they are not in release yet: https://github.com/commaai/openpilot/pull/27395

Simply install the nightly branch to get up and running!

Installer URL: https://installer.comma.ai/commaai/nightly
