### ISSUE TITLE
can bus error

### ISSUE THREAD

**Issue by DanSantaCruz** [commaai/openpilot#28043]
### Describe the bug

This is a new unit. When installed i received a not registered error. the unit did highlight road edges and the proposed path in yellow. The dash cam error did remain on screen. I was sent a new branch i think it was and installed in the custom software selection. Immediately after the update I am getting a can bus connection error. It shows the road but no loger shows road edges edges or yellow path. The only thing i did was install the new software. I did install it in custom software selection instead of dash cam.

### Provide a route where the issue occurs

all today

### openpilot version

27395

### Additional info

I'm a noob to the process. my apologies.

**Comment by sunnyhaibin** [comment]
Make sure you provide a dongle ID of the comma three.
- What car brand, car model, model year, and trim is this?
- Does it have Adaptive Cruise Control or Smart Cruise Control from the factory?

**Comment by DanSantaCruz** [comment]
2023 hyundai santa cruise with lane keep, adaptive cruise and hwy/smart
cruise.

Dongle and serial attached.

Thank you for your help.

**Comment by incognitojam** [comment]
@DanSantaCruz This forum is only for issues encountered on openpilot release/master branches. New car ports and hardware troubleshooting should take place on discord.
