### ISSUE TITLE
Out of storage alert when restarting vehicle rapidly

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#28136]
the previous controlsd instance is kept up when turning the vehicle back on if done quick enough, so somehow `deviceState` is publishing wrong data in this time

**Comment by adeebshihadeh** [comment]
This doesn't make any sense. Do you have a route?

**Comment by sshane** [comment]
I'll try to get a new one, can't find any with the event added

**Comment by sshane** [comment]
Can't reproduce, I'll re-open if I do
