### ISSUE TITLE
Stuck on "Registering Device" 

### ISSUE THREAD

**Issue by swieder711** [commaai/openpilot#28215]
### Describe the bug

After updating to latest DP release today on my C3, my device got stuck on "Registering Device" screen. Could not reset to factory default on boot screen. Many others reported similar problem on Discord.

### Provide a route where the issue occurs

serial: 2246c0fa

### openpilot version

Latest 

### Additional info

Thanks

**Comment by swieder711** [comment]
Wrong thread for a Dragon Pilot problem.

**Comment by EthanChou860314** [comment]
When I power on, my device got stuck on "Registering Device" screen. 
I dis connect the power, and then connect power. It's still stuck on "Registering Device" screen. 
How can I reset my device?

What is Dragon Pilot problem?
