### ISSUE TITLE
Supported car not recognized (2020 G70)

### ISSUE THREAD

**Issue by kmjack303** [commaai/openpilot#28254]
### Describe the bug

2020 Genesis G70 (Korean Spec) isn’t recognized.

dongle ID: e20ec117fa6a8c81

### Which car does this affect?

2020 Genesis G70

### Provide a route where the issue occurs

e20ec117fa6a8c81|2023-05-22--06-50-56--0

### openpilot version

0.9.1-release / release 3 / cc18662 / Feb 23

**Comment by sshane** [comment]
Fixed in https://github.com/commaai/openpilot/pull/28323. You can download master, master-ci, or nightly branches to use openpilot
