### ISSUE TITLE
Panda siren triggered after turning off ignition

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#28270]
### Describe the bug

Panda siren triggered immediately upon turning off my car after I backed into and parked at a parking space. No visual alert was surfaced during this event. I did not unlatch the seat belt prior to turning off the car.

I believe this event occurred as a result of engaging openpilot, shortly before disengaging by pressing the brake pedal and then backing into the parking space.

### Provide a route where the issue occurs

4f3e4f2f6d94e940|2023-05-23--07-00-22--0

### openpilot version

331907134f752bbb4247cb69f362e789787ae767

**Comment by adeebshihadeh** [comment]
Fixed with 78df554
