### ISSUE TITLE
car docs: better hardware footnotes

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#28308]
![image](https://github.com/commaai/openpilot/assets/25857203/66ffccfc-6193-4ee2-8878-0f7ec7dbe7c0)

@maxime-desroches can you think of a better place for these, or fix the formatting?

**Comment by adeebshihadeh** [comment]
Unclear what this issue is for. Seems fine to me.

**Comment by sshane** [comment]
it's for the inconsistent superscript link, but I agree it's very minor. not worth the additional 40 lines to fix at the moment
