### ISSUE TITLE
GPS signal error - always displayed

### ISSUE THREAD

**Issue by sunilm1992** [commaai/openpilot#28324]
### Describe the bug

My car has a GPS signal issue with the comma3, having returned the device already and being given another one I think the most likely cause is the heating elements in my windscreen
When this GPS error comes up it says 'hardware malfunction if sky visible' but this blocks the entire screen mostly and blocks useful information

please can we change this warning to a smaller one so that it doesn't block the screen / only show it for 30 seconds or something?

### Provide a route where the issue occurs

see above

### openpilot version

0.9.2

**Comment by haraschax** [comment]
Can you post a route? And a picture of your setup?

**Comment by haraschax** [comment]
Not actionable without a route
