### ISSUE TITLE
genesis g70 2018 comma three car unrecognized

### ISSUE THREAD

**Issue by starflowlove** [commaai/openpilot#28320]
### Describe the bug

comma three car unrecognized.
my car 2018 genesis g70

### Which car does this affect?

2018 genesis g70 

### Provide a route where the issue occurs

?

### openpilot version

all version (0.9.1~0.9.2)

### Additional info

Not recognized in all versions,

It is recognized when the vehicle is selected in Sunny.

**Comment by BrandonHacks** [comment]
You need to fingerprint the car. Someone in discord might help if you can’t figure it out.

**Comment by sshane** [comment]
What is your dongle id?
