### ISSUE TITLE
GM: Jerky low-speed steering

### ISSUE THREAD

**Issue by Verylukyguy** [commaai/openpilot#28337]
### Describe the bug

When driving at low speeds, the steering jerks and releases in curves.

This has been in on-going issue since GM was ported.

### Provide a route where the issue occurs

df51b2195de66a9b| 2023-05-25--09-31-00--1

### openpilot version

Comma Nightly @ 546c562

### Additional info

There are also in-curve corrections at highway speeds that seem to be unnecessary and this may be related to this bug.

**Comment by adeebshihadeh** [comment]
Low speed controls isn't really that great in any of our torque cars. @haraschax worth keeping this open?

**Comment by Verylukyguy** [comment]
I wanted to cross-reference the new GMC Acadia Torque Controller tuning that was added to `master` in https://github.com/commaai/openpilot/pull/28923
