### ISSUE TITLE
Phantom braking event 

### ISSUE THREAD

**Issue by MJR1989** [commaai/openpilot#28365]
### Describe the bug

Momentary phantom braking from faulty radar speed detection of cut in vehicle happens between timestamps 16:41:20 and 16:41:30 only brakes for a moment not even long enough for me to respond and manually control the throttle 
### Provide a route where the issue occurs

b0a7a22dea55a1cd|2023-06-01--16-32-34--8

### openpilot version

0.9.2

**Comment by haraschax** [comment]
![Screenshot from 2023-06-01 17-48-43](https://github.com/commaai/openpilot/assets/6804392/188ffc43-2627-402b-a0c0-d50b8876f952)
![Screenshot from 2023-06-01 17-48-35](https://github.com/commaai/openpilot/assets/6804392/05cebea5-a930-4c1c-97fa-92d7ec2b5bd7)
Appears to be a radar issue, reports a slow car. But no slower cars visible in the video. Overpass make be causing issues.

**Comment by adeebshihadeh** [comment]
@haraschax want to keep open or can we close?
