### ISSUE TITLE
"Check" button & "up to date" in Software tab does not translate

### ISSUE THREAD

**Issue by TheOfficialJosh** [commaai/openpilot#28398]
### Describe the bug

The "Check" button does not change to match the translation file for any language, nor does the "up to date" text.
Found while working on Spanish translation (re-open of #27844), which is why branch shows translation-es.
Spanish:
![image](https://github.com/commaai/openpilot/assets/1631602/1a788e97-b5e8-4546-87cd-6733b1c09c6f)
Deutsch:
![image](https://github.com/commaai/openpilot/assets/1631602/e6e8aa6f-ab15-470b-84de-70ff4c68b5c6)
Chinese Simplified:
![image](https://github.com/commaai/openpilot/assets/1631602/a566a83d-0f9c-4ec0-b4cd-3adb06b00a4d)

### Provide a route where the issue occurs

5130484aa8069bad

### openpilot version

0.9.3

**Comment by adeebshihadeh** [comment]
@sshane isn't there supposed to be a test that catches this?

**Comment by sshane** [comment]
Dynamically set text is not very well caught in the test, it only currently tests one static UI state, and so it never gets to these calls, which rely on the updater process. @maxime-desroches maybe as a future project we can test more states of the UI

https://github.com/commaai/openpilot/blame/6d91b7c341afd1bf38e1bb044338a2026d0a6c94/selfdrive/ui/qt/offroad/software_settings.cc#L129-L141

**Comment by sshane** [comment]
Fixed by https://github.com/commaai/openpilot/pull/28417. opened an issue to add better tests
