### ISSUE TITLE
Toyota B Harness

### ISSUE THREAD

**Issue by vanillagorillaa** [commaai/openpilot#28402]
- [x]  which car is this for? 2023 Toyota Corolla Hybrid (vehicles made at Japan plant)
- [x]  schematic - [here](https://github.com/commaai/neo/blob/master/car_harness/Toyota_B_Harness.sch.pdf)
- [x]  beta sent to tester
- [ ]  in shop

**Comment by nelsonjchen** [comment]
Linking this here as possibly related: https://github.com/commaai/openpilot/discussions/19932#discussioncomment-6297415

**Comment by vanillagorillaa** [comment]
Added to shop. Schematic pushed to neo repo. Closing

**Comment by nelsonjchen** [comment]
https://github.com/commaai/neo/blob/master/car_harness/Toyota_B_Harness.sch.pdf

Just linking this here to save someone some clicking: https://comma.ai/shop/car-harness 

In the dropdown, "Toyota B Harness".
