### ISSUE TITLE
Kia Sportage ICE 2023: Controls Unresponsive when disengaging with brake/accel

### ISSUE THREAD

**Issue by Daltoh** [commaai/openpilot#28404]
### Describe the bug

OpenPilot loses control of the car after using the brake or accelerator to disengage. Only occurs when disengaging, accelerating without the disengage-on-accelerator toggle enabled does not cause an error. "Check blind spot indicators" warning comes on the cluster until C3 is unplugged or car is restarted. I have included a few variations of routes with the disengage on accelerator toggled differently.

### Which car does this affect?

Kia Sportage ICE 2023

### Provide a route where the issue occurs

965a780ebeeed150|2023-06-04--20-33-51  - Braking with disengage on accelerator toggle enabled
965a780ebeeed150|2023-06-04--20-39-36 - Accelerating with toggle enabled
965a780ebeeed150|2023-06-04--20-42-19 - Braking with toggle disabled
965a780ebeeed150|2023-06-04--20-45-40 - Accelerating with toggle disabled

### openpilot version

master #90d31b9

**Comment by adeebshihadeh** [comment]
Seems to have been caused by #28020, reverting it in #28406. @sshane we need better tests to catch this before merging it again
