### ISSUE TITLE
New Cabana cannot handle GMlan on white panda 

### ISSUE THREAD

**Issue by ServerDummy** [commaai/openpilot#28429]
### Describe the bug

New Cabana cannot handle GMlan, speed cannot be set to 33.33 kb/s and panda gets stuck on failed to receive, letting only a few messages through.

My panda is hooked into only gmlan and power, so the messages could only be coming from the GMlan. Modified script of can_logger.py reads GMlan fine by adding the line Panda().set_gmlan(2) and GMlan continues to be active until the panda is powered cycled. Changing the switch case in white.h does not appear to enable GMlan.

To get cabana to the state it was in, I ran the can_logger.py with the added enable GMlan line, then opened cabana which results in the errors displayed at the bottom of the screen. As well as a panda CAN checksum error.

![1c9dfa48-a5fb-4cb8-b796-26568bb5168e](https://github.com/commaai/openpilot/assets/63013446/826217df-61b5-4536-9db8-7afc80a3e187)

### Provide a route where the issue occurs

Null, cabana on white panda issue

### openpilot version

9.2

**Comment by adeebshihadeh** [comment]
Since HW GMLAN isn't really used in openpilot anymore, we don't have the resources to continue to support it ourselves. We'll definitely merge PRs to fix it, but since it's not a mainline thing anymore, I'm going to close this issue.
