### ISSUE TITLE
openpilot icon blinks when disengaging with the cancel button

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#28432]
### Describe the bug

The openpilot icon at the top right corner of the screen sometimes blinks when disengaging by pressing the cancel button. This appears to be a visual bug that has surfaced recently as I have not noticed this happening with previous versions of openpilot. Holding down the cancel button does not affect the duration of the openpilot icon disappearing when this occurs.

https://github.com/commaai/openpilot/assets/85845724/198fbba1-89fa-4ee6-9953-38832bc4c7a7

### Provide a route where the issue occurs

4f3e4f2f6d94e940|2023-06-06--12-43-56--18

### openpilot version

b7ddb1b705689d3ebab7a31913d8929ff368ee71

**Comment by adeebshihadeh** [comment]
This is because openpilot isn't engageable on the frame you disengage. #28765 should make this smoother.
