### ISSUE TITLE
Communication Problem Between Processes

### ISSUE THREAD

**Issue by Euclid71** [commaai/openpilot#28484]
### Describe the bug

This is the same or similar to closed issue #21873. 

I get this error with the same symptoms as issue #21873 when I have the OpenStreetMap database set to "== None ==". 

When I set the database to "US - Pacific", I never get this error.

Route: f1bc09b7aead608d|2023-06-09--23-37-12--1
All logs are uploaded.

### Provide a route where the issue occurs

f1bc09b7aead608d|2023-06-09--23-37-12--1

### openpilot version

0.8.16

**Comment by vanillagorillaa** [comment]
You are running a fork, dragonpilot, and not stock openpilot. If your issues persists on stock openpilot feel free to reopen this issue, otherwise you will want to report this issue to your fork maintainer on their respective repo.

**Comment by lhn136** [comment]
I recently ran into the same issue with dragonpilot
