### ISSUE TITLE
Low Memory warning

### ISSUE THREAD

**Issue by RyanDale** [commaai/openpilot#28497]
### Describe the bug

I received a Low Memory warning a few minutes into my drive. The memory usage warnings started at 92% and quickly crept upward to the mid 90's. I had just updated my C3 to the latest OP version of master and previously have not encountered any Low Memory warnings. 

### Provide a route where the issue occurs

88b9fa8e179f87d8|2023-06-11--10-46-08

### openpilot version

9642055

**Comment by adeebshihadeh** [comment]
Fixed by 5161c2364538236b51674fbc63c7f9666e95928b
