### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ns3284** [commaai/openpilot#28505]
### Describe the bug

On the latest nightly (a991dcb) the device consistently hits low memory and freezes up.

### Provide a route where the issue occurs

4395faadf0a373f2|2023-06-11--18-29-48--0

### openpilot version

0.9.3 a991dcb

**Comment by adeebshihadeh** [comment]
See #28497

**Comment by ns3284** [comment]
Looks like it was fixed with revert of the encoder change.
