### ISSUE TITLE
Carla simulator no longer works

### ISSUE THREAD

**Issue by Ktter** [commaai/openpilot#28506]
### Describe the bug

I tried to run openpilot 0.9.13 on Ubuntu 18.04 LTS
using some steps as follow:
1. ` ./start start_carla.sh` in ../sim in Terminal A
2. `sudo docker exec -it openpilot_client bash` in Terminal B
3. `./launch_openpilot.sh` in Terminal B
4. exec docker of openpilot again in terminal C
5. `./bridge.py --dual_camera`
![2023-06-11 22-38-311](https://github.com/commaai/openpilot/assets/75573607/9c323d0d-c6a3-4f30-85e8-ed559210134d)

I could manually control this car in _ui  two week ago, but i cant run it again now.
I will very apperaciate you if you can give me some he

### OS Version

Ubuntu 18.04 LTS

### openpilot version or commit

openpilot 0.9.13

**Comment by haraschax** [comment]
There's a couple bugs with the simulator unfortunately, fixing them here:
https://github.com/commaai/openpilot/pull/28541

This branch engages in simulation, need to clean it up before I can merge though

**Comment by haraschax** [comment]
Fixed
