### ISSUE TITLE
Openpilot Unavailable - Waiting for Controls to start forever - Reboot fixes it

### ISSUE THREAD

**Issue by josurance** [commaai/openpilot#28574]
### Describe the bug

Hello, I get this error message saying Openpilot Unavailable - Waiting for Controls to start 
Reboot fixes it but it comes back on next vehicle start.
The error occurred in code not modified by sunny or twilsonco.

### Provide a route where the issue occurs

https://useradmin.comma.ai/?onebox=64e16c4237493597

### openpilot version

0.9.2.2

### Additional info

![FullSizeRender](https://github.com/commaai/openpilot/assets/136838321/0c5e28a7-b39a-4f1e-8613-e8f71b475443)
![FullSizeRender](https://github.com/commaai/openpilot/assets/136838321/de3c9971-2951-45bf-b61e-32ee83c70ba2)
![FullSizeRender](https://github.com/commaai/openpilot/assets/136838321/88328043-e576-433f-a5a2-f9de6668835c)
![FullSizeRender](https://github.com/commaai/openpilot/assets/136838321/d4506b04-5ad6-4022-b5cd-f5220e268e62)

**Comment by adeebshihadeh** [comment]
This should be reported to the fork maintainer instead. Feel free to open a new issue if you can reproduce this with stock openpilot.
