### ISSUE TITLE
Ford: "Park not available" alert

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#28582]
One of the Nissan KWP2000 queries puts the Bronco Sport into a neutral tow mode state, but it doesn't have neutral tow mode...

Summary of issue: Dash says park not available because it thinks we're in neutral tow mode, but exits that mode and alert goes away as soon as you put it in park. Parking pawl activates as normal, it just applies the parking brake on its own.

**Comment by sshane** [comment]
Here you can see everything was normal on startup where I was in drive, then we queried with this Nissan request and the various neutral tow signals activated, and the normally "OutOfPark
`

![image](https://github.com/commaai/openpilot/assets/25857203/32f6104f-d92a-4397-9e14-5b1d7d7767aa)

**Comment by sshane** [comment]
Random Nissan X-Trail FW query:

fa9224be239005c7|2023-05-30--08-49-15
![image](https://github.com/commaai/openpilot/assets/25857203/1f69b75c-fddb-4a28-9b82-a66f32edf251)

**Comment by adeebshihadeh** [comment]
@sshane is this resolved?

**Comment by sshane** [comment]
No, we still need to merge the Nissan diagnostic mode change.

**Comment by incognitojam** [comment]
Is there anything we can do to fix this in the meantime, perhaps sending Nissan queries after Ford queries? It does cause an annoyance for users (reported that the car will always try to activate the parking brake when you slow down).

**Comment by sshane** [comment]
The problem occurs when the Ford fuzzy fingerprints (since we run all queries before fuzzing fingerprinting, can be improved), or doesn't fingerprint at all. Ordering doesn't matter at the moment.
