### ISSUE TITLE
openpilot Unavailable: Low Communication Rate between Processes

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#28592]
### Describe the bug

Shortly after I started driving, I noticed the openpilot logo was not present and the video was of noticeably worse framerate. When I tried to engage openpilot it threw the **openpilot Unavailable: Low Communication Rate between Processes** alert. A few seconds later, the openpilot logo flashed rapidly before finally becoming solid. After that, I was able to engage openpilot for the rest of my drive with no issues.

### Provide a route where the issue occurs

4f3e4f2f6d94e940|2023-06-18--07-03-48--0

### openpilot version

b25be7003ce60bc62af011100a8a4567d600776c

**Comment by adeebshihadeh** [comment]
Similar to #28714
