### ISSUE TITLE
LEXUS NX-300h hybrid 2020  [vehicle is not recognized and is in dashcam mode]

### ISSUE THREAD

**Issue by Abanggo** [commaai/openpilot#28651]
### Describe the bug

The vehicle is not recognized and is in dashcam mode.

     NX Hybrid 2020, (comma.ai homepage) 
     openpilot upgrades your Lexus NX Hybrid with automated lane centering at all speeds, and adaptive cruise control that automatically resumes from a stop. Traffic light and stop sign handling is also available in Experimental mode.
     SUPPORT: openpilot will work with all packages and trims of this car.

You must be busy, but please help. thank you.

![인식](https://github.com/commaai/openpilot/assets/119370669/6e63f5b4-46e4-43b8-bf90-3252bcb03505)

### Provide a route where the issue occurs

 9a1f34e34fb917f2 | 2023-06-23--11-25-02--0

### openpilot version

master-ci v0.9.4 release  7d6c229

### Additional info

![KakaoTalk_20230623_120748927](https://github.com/commaai/openpilot/assets/119370669/79d825a1-0f7f-49e5-a68b-ce84bb867cdf)

**Comment by Abanggo** [comment]
Thank you very much for your interest.

**Comment by sshane** [comment]
Thanks for trying master with my addition of your hybrid ECU, we got it! This will help us improve fingerprinting in the near future for Toyota.

```python
{'address': 2018,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'hybrid',
                          'fwVersion': b'\x05899837851000\x00\x00\x00\x00899857801000\x00\x00\x00\x00898844813300\x00\x00\x00\x0089884481430'
                                       b'0\x00\x00\x00\x00898844815300\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\t\x04'],
                          'responseAddress': 2026,
                          'subAddress': 0},
```

Added your FW, can you try this branch? https://github.com/commaai/openpilot/tree/add-missing-lexus-300h-fw

Installer URL: https://installer.comma.ai/commaai/add-missing-lexus-300h-fw

**Comment by Abanggo** [comment]
Dear Sshane
Thank you very much for your attention and solving it.
Now, let's install and use it on the C3 of the vehicle.
If you have any other opinions, please leave a comment here.
thank you

**Comment by sshane** [comment]
You can type that installer URL in after factory resetting your device and it will install.

**Comment by Abanggo** [comment]
thank you

The result of installing the latest version and operating it with the vehicle confirmed that it works well.

Is it correct to reboot again by clicking on just one power off?

thank you so much. I will use it well.

![KakaoTalk_20230625_074940355_01](https://github.com/commaai/openpilot/assets/119370669/0fbe4518-5620-4cea-873a-1fd88b98f7bb)

![KakaoTalk_20230625_074940355](https://github.com/commaai/openpilot/assets/119370669/4a5c0ece-ccbe-4345-a1fd-f0a7a6617684)

**Comment by Abanggo** [comment]
Thanks for helping us use openpilot.
I've been driving around town and it's working very well.
Thank you very much for your help.

2023년 6월 24일 (토) 오후 11:11, Shane Smiskol ***@***.***>님이 작성:

**Comment by Abanggo** [comment]
**[Report Abnormal Behavior]**

LEXUS NX-300h hybrid 2020 [vehicle is not recognized and is in dashcam mode] #28651
Lexus: add missing NX 300H 2021 FW #28678

Perform a factory reset and [installer.comma.ai/commaai/add-missing-lexus-300h-fw]
Installed on June 26, 2023 and drove about 400 km in normal operation and parked.

June 27, 2023 [dmonitoringmodeld, navmodeld] is displayed when the vehicle is started, and normal operation stops.

On June 28, 2023, the master / master-ci version was installed and a test drive was performed, but the same [dmonitoringmodeld, navmodeld] was displayed and did not operate normally.

Translated through Google Translate.


![KakaoTalk_20230628_172247785](https://github.com/commaai/openpilot/assets/119370669/9a580f78-25f7-4384-8305-733ea60c84a9)

**Comment by Abanggo** [comment]
https://github.com/commaai/openpilot/issues/28726
