### ISSUE TITLE
new HYUNDAI "KONA_EV_2ND_GEN with HDA II" CAN-FD vehicle Harness

### ISSUE THREAD

**Issue by haram-KONA** [commaai/openpilot#28724]
I would be grateful if you refer to the attached photos for the harness of "Hyundai KONA EV 2ND GEN with HDA II". 
It is currently running in Korea, but it seems that North America or Europe will be shipped in the second half of 2023. 
The shape of the harness and cable wiring are the same as the current "Hyundai TYPE A", but only one wire seems to be different. 

"KONA_EV_2ND_GEN with HDA II" harness please.

![KONA_EV_2ND_GEN_3](https://github.com/commaai/openpilot/assets/88036668/62212cbb-9f77-4447-8d91-bed62142e0fb)
![KONA_EV_2ND_GEN_4](https://github.com/commaai/openpilot/assets/88036668/89dfebaa-e7bf-49dd-877b-d5abddfe0095)
![KONA_EV_2ND_HEN_1](https://github.com/commaai/openpilot/assets/88036668/bd76d46e-f62e-463a-8037-8187f9dcb02a)
![Similar TYPE A _KONA_EV_2ND_GEN-HARNESS](https://github.com/commaai/openpilot/assets/88036668/9106d4ab-6fff-40b3-aabe-4d2869598142)
![KONA_EV_2ND_GEN_2](https://github.com/commaai/openpilot/assets/88036668/c76939f5-a8ab-40e0-95dd-94a23dfed387)

**Comment by vanillagorillaa** [comment]
This vehicle will use the "Hyundai R" harness. You can track progress here, https://github.com/commaai/openpilot/issues/27580
