### ISSUE TITLE
Some drives not uploaded to Comma Connect

### ISSUE THREAD

**Issue by Zack1010OP** [commaai/openpilot#28742]
### Describe the bug

29 June 2023 - some drives uploaded
28 June 2023 - no drive uploaded at all
27 June 2023 - some drives uploaded
26 June 2023 - some drives uploaded

i've got good solid wifi and i've tried to connect to other SSIDs also but same result. i have cross country version so space shouldn't be a problem

### Provide a route where the issue occurs

27 June 2023 9:24pm no uploaded - can't find in comma connect

### openpilot version

sunnypilot - fork dev-c3 (i always update to latest version)

**Comment by incognitojam** [comment]
We cannot provide software guarantees when you are running a community fork.

Suggestions:
- install stock openpilot and see if the issue persists. If it continues, open a new issue and share your dongle ID.
- check whether the files exist on your device (connect with SSH)
- login to https://useradmin.comma.ai/ and see if the routes are visible there
