### ISSUE TITLE
rawgpsd: SUPL configuration persists

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#28747]
We removed the SUPL configuration in #28278 when we switched to XTRA for AGPS, but the configuration persists, so it's unclear if the TTFF we're getting now is from SUPL, XTRA, or both. We should either add the configuration back or clear it on startup, so all the modules are in a consistent state

**Comment by adeebshihadeh** [comment]
Not immediately clear how to clear this configuration. We're getting good performance now with most of our devices having both the SUPL and XTRA configured. @haraschax what do you think of just adding back the SUPL config?

**Comment by haraschax** [comment]
We can add it back, though in my experiments I never got the SUPL to help at all.

**Comment by adeebshihadeh** [comment]
Added back in #28858, so all devices should be in a consistent state now.
