### ISSUE TITLE
Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized 

### ISSUE THREAD

**Issue by bashiromar1795** [commaai/openpilot#28767]
### Describe the bug

Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized 

### Which car does this affect?

Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized 

### Provide a route where the issue occurs

279e4980fb308469|2023-06-30--21-10-27

### openpilot version

0.9.4

### Additional info

Car not in repository and need this car added

**Comment by bashiromar1795** [comment]
OpenPilot is unable to update

**Comment by sshane** [comment]
You need to switch to master, master-ci, or nightly branches
