### ISSUE TITLE
Mac: replay fails to run when ui is open

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#28776]
### Describe the bug

- Was having these issues on Sonoma so started with a fresh Ventura install, installed brew, scons built successfully
- Opening ui with `./selfdrive/ui/ui` runs successfully
- Opening replay with `./tools/replay/replay --demo` either fails with the following..
```
loading route  "4cf7a6ad03080c90|2021-09-29--13-46-36"
load route 4cf7a6ad03080c90|2021-09-29--13-46-36 with 11 valid segments
Error opening terminal: xterm-256color.
QNetworkInterface: could not create IPv6 socket (Too many open files)
QNetworkInterface: could not create IPv6 socket (Too many open files)
QNetworkInterface: could not create IPv6 socket (Too many open files)
```
- ..or this after loading part of the replay ui
```
__ Engaged __ Disengaged __ Info __ Warning __ Critical __ User Tag 
QThreadPipe: Unable to create pipe: Too many open files
QEventDispatcherUNIXPrivate(): Cannot continue without a thread pipe
zsh: abort      ./tools/replay/replay --demo
```
- Closing ui and opening replay by itself runs successfully
- Opening ui while replay is running causes replay to fail with the following..
```
QNetworkInterface: could not create IPv6 socket (Too many open files)
QNetworkInterface: could not create IPv6 socket (Too many open files)
```

### OS Version

MacOS Ventura 13.4.1 (22F82) on M1 Macbook Pro

### openpilot version or commit

6495a18cc9e8c1394ac7395d24bb0a661ce35fbf

**Comment by deanlee** [comment]
it is not a op bug.your system has reached the ulimit.you can fix it by googling "Too many open files"

**Comment by royjr** [comment]
Interesting..

ulimit -n 256 -> `Error opening terminal: xterm-256color.`
ulimit -n 300 -> `degAssertion failed: (*fd >= 0), function malloc_with_fd, file visionbuf_cl.cc, line 24.`
ulimit -n 400 -> `degzsh: segmentation fault`
ulimit -n 999999 -> `degzsh: segmentation fault`
ulimit all unlimited -> `degzsh: segmentation fault`
<img width="325" alt="Screenshot 2023-07-03 at 8 37 48 AM" src="https://github.com/commaai/openpilot/assets/1976269/49e39e1c-bf5f-404f-a7a6-4b3cb99bec8b">

default macOS values..
<img width="330" alt="Screenshot 2023-07-03 at 8 28 14 AM" src="https://github.com/commaai/openpilot/assets/1976269/d8dbe417-9596-49f1-9f94-e67e60086013">

default ubuntu 20.04 values..
<img width="417" alt="Screenshot 2023-07-03 at 8 24 13 AM" src="https://github.com/commaai/openpilot/assets/1976269/13d6ac01-4aef-4878-b492-e967dd5f9347">

**Comment by royjr** [comment]
Fixed by https://github.com/commaai/openpilot/pull/28779

**Comment by royjr** [comment]
I had to additionally change file descriptors from 256 to 512 by `ulimit -n 512`
