### ISSUE TITLE
"Procces Not Running dmonitoringmodeld"

### ISSUE THREAD

**Issue by 37designfk** [commaai/openpilot#28786]
### Describe the bug

Hello.

I am driving a 2016 TSS Prius in Japan.

It was working fine when it was 0.9.1.

Today I upgraded the version of comma three from 0.9.1 to 0.9.3.

The first time I removed comma three, flushing and upgrading by PC browser.

However, I got the message "Procces Not Running dmonitoringmodeld", so I upgraded the version by OTA.

After that, I disconnected the wiring, disconnected the power supply, reinstalled the unit, and performed a Reflash twice, but the "Procces Not Running dmonitoringmodeld" message appeared and I could not use the automatic operation at all.

What countermeasures can I take?

![IMG_5879](https://github.com/commaai/openpilot/assets/65986301/f75d289f-44ed-404a-81c0-e0004c8dac11)

### Provide a route where the issue occurs

27a5ea86956c8d71|2023-07-01--09-07-59

### openpilot version

0.9.3

**Comment by adeebshihadeh** [comment]
Same cause as #28726, we'll track the issue there.
