### ISSUE TITLE
Hyundai Ioniq 6

### ISSUE THREAD

**Issue by IoniqYeti** [commaai/openpilot#28789]
### Describe the bug

Hello, I am running a branch of the openpilot called ioniq - 6. I have talked with some people in the discord and they have told me that it is not a fingerprint issue. The comma3 will recognize my device but Im unable to use any of the features of openpilot.

In this branch, the comma 3 recognizes the car and will not say dashcam mode BUT my dashboard lights up like a Christmas tree. I get 6 errors in total and ALL of my driver assist features are disabled and I cannot engage any of the driving assist features.

If I disable open pilot in the toggles menu, then the car goes to dashcam mode and there are no errors or warnings on the dashboard.

Please help! 

### Which car does this affect?

Hyundai Ioniq6 2023

### Provide a route where the issue occurs

5b86a6f0102bb5e9|2023-07-03--06-06-41--0

### openpilot version

0.9.3

### Additional info

my dongle ID is 5b86a6f0102bb5e9

**Comment by adeebshihadeh** [comment]
This is not a bug with upstream openpilot. If you have issues with a branch, it's best to leave comments on the PR.
