### ISSUE TITLE
openpilot 0.9.2 on PC use rgb_to_yuv.cl, UV plane error

### ISSUE THREAD

**Issue by bccw2021** [commaai/openpilot#28798]
### Describe the bug

openpilot 0.9.2 on PC use rgb_to_yuv.cl, UV plane error:
![image](https://github.com/commaai/openpilot/assets/122735387/f85ca27e-b889-4335-9258-737e2238150f)

### OS Version

ubuntu 20.04

**Comment by adeebshihadeh** [comment]
It's not clear what issue you're reporting, but gonna close since `rgb_to_yuv.cl` is no longer a file in master anyway. Feel free to open a new issue if you have problems running on PC with the latest master.
