### ISSUE TITLE
 KIA: Car Port for SORENTO HYBRID(HEV) 4TH GEN (2023 Korean Ver.)

### ISSUE THREAD

**Issue by VoltIcaRus** [commaai/openpilot#28791]
- [x] route with stock system:  `a18329dff9682723|2023-07-03--14-56-59`

- [x] harness type: [Hyundai A](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)

- [x]  route with openpilot:  `a18329dff9682723|2023-07-03--16-44-18`

- [x] architecture: CAN-FD

**Physical setup**

- Top port behind comma three
comma Power <-> First Harness Box <-> comma three USB C/Right-Angle C <-> comma three

- Bottom port behind comma three
  Camera Harness <-> Second Harness Box <-> USB C/C 3.1 <-> Red Panda <-> USB A/A <-> USB A to C OTG Adapter <-> comma three

- Link to all physical parts during install:

[comma three](https://comma.ai/shop/comma-three)
[car harness kit](https://comma.ai/shop/car-harness)
[CAN FD panda kit](https://comma.ai/shop/can-fd-panda-kit)

Software URL
https://github.com/commaai/openpilot/tree/master-ci

What I did:
The values of fwdRadar   b'\xf1\x00MQhe SCC FHCUP      1.00 1.07 99110-P4000         ',
 and fwdCamera b'\xf1\x00MQ4HMFC  AT KOR LHD 1.00 1.12 99210-P2000 230331',
 for HEVs have been inserted below the code for PHEVs, 
an existing comma-enabled vehicle.

Note: The Kia Sorento 4th generation hybrid (HEV) is a 
is a different model than the Sorento 4th generation plug-in hybrid (PHEV) exported to the United States.
but most parts seem to be shared 
This vehicle is equipped with the HDA1.
![IMG_7130](https://github.com/commaai/openpilot/assets/3735740/318c0122-4faf-4775-8c62-4609c96d306b)

Engage work
Lane Change work
Set speed work
Auto-restart after stopping work

, when I hit the brakes.
it would disengage
even when the option is off.

It is also my understanding that this vehicle is for domestic use in South Korea and that the
It is my understanding that an export version of this vehicle is being produced as a PHEV.
There may be errors or features I missed.

by the way
The touchscreen of the comma 3 that I got repaired today is in poor condition and I will send it back for repair.

**Comment by adeebshihadeh** [comment]
It's not clear what this issue is for. RE: "when I hit the brakes. it would disengage", this is expected behavior; the toggle is for the gas pedal. If you have a clear issue, feel free to make a new one.
