### ISSUE TITLE
nav: zooming improvements

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#28816]
- [x] it looks like it continues to zoom when you pan manually, it probably should stop (like it does if you manually zoom) - https://github.com/commaai/openpilot/pull/29470
- [ ] can also reset the filter when it resets the view/re-centers
- [x] filter too slow, or set a breakpoint above 0, as it continues to zoom when you come to a stop - https://github.com/commaai/openpilot/pull/29601
- [x] fix zoom starting from 0 m/s when you get a fix while driving - https://github.com/commaai/openpilot/pull/29605

_From https://github.com/commaai/openpilot/issues/28796#issuecomment-1622629543_

**Comment by varshneydevansh** [comment]
Hi @sshane can I work on this as I also have experience with Qt and I looked at the comment https://github.com/commaai/openpilot/pull/28796#issuecomment-1622629543

**Comment by sshane** [comment]
sure, any issue open here you feel you could tackle, we're happy to let you

**Comment by jakethesnake420** [comment]
https://github.com/commaai/openpilot/pull/29488

**Comment by jakethesnake420** [comment]
Unless I'm not understanding the idea, I don't think the filter should be reset when you recenter the view.

**Comment by varshneydevansh** [comment]
I will do this in a few days. =)

**Comment by jakethesnake420** [comment]
> I will do this in a few days. =)

I think I have completed them. Just waiting for it to be merged
