### ISSUE TITLE
nav entry: destination not updated on param change

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#28826]

**Comment by sshane** [comment]
- [ ] also noticed on startup without destination, it shows settings button then quickly changes to the nav icon (or vice-versa), with the positional changes and everything

**Comment by adeebshihadeh** [comment]
That should be a separate issue.

**Comment by adeebshihadeh** [comment]
@deanlee want to look into this one? I suspect it's just updating on the showEvent.
