### ISSUE TITLE
tools/replay: set NavDestination from the route

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29026]

**Comment by sshane** [comment]
I was thinking it would be better if we got rid of the param reading in map.cc and just have navRoute publish its navDestination. Similar thing to controlsd with `experimentalMode`, and plannerd with `longitudinalPersonality`.

**Comment by deanlee** [comment]
I agree with @sshane . otherwise we also have to prevent the ui from fetching the NavDestination from the CommaApi during replay.

**Comment by deanlee** [comment]
I agree with @sshane .this can simplifies the synchronizations, replay also works without modification.

**Comment by adeebshihadeh** [comment]
Good point, this is definitely the right solution. Not sure why that's only broadcasted on change.

**Comment by sshane** [comment]
@deanlee can you check how big navRoute is and make a PR to send it at a fixed frequency? I think there were some concerns about the size of the service inflating rlogs/qlogs
