### ISSUE TITLE
ui map: center destination pin and fix overlap with path

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29029]

**Comment by adeebshihadeh** [comment]
@deanlee want to check this one out?

**Comment by sshane** [comment]
mapbox's demo app just pushes their icon up so the image center is the bottom of the marker

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/default/resources/default_marker.svg

**Comment by adeebshihadeh** [comment]
@mitchellgoffpc looks like we'll just have to do that
