### ISSUE TITLE
UiPlan and lane lines should stick to road when going over bumps

### ISSUE THREAD

**Issue by rmcc22** [commaai/openpilot#29036]
When going over bumps the displayed path and lane lines do not track the to image correctly. It would be nice if this could be improved.

![image](https://github.com/commaai/openpilot/assets/83676301/9f467aa6-8102-45d7-8326-9de9b8bc7d43)
![image](https://github.com/commaai/openpilot/assets/83676301/f0df3a17-c420-4330-9188-89f59f318c5c)
![image](https://github.com/commaai/openpilot/assets/83676301/4580d8ba-01c6-4ade-9558-e57553ea52d7)

**Comment by sshane** [comment]
We have an issue opened for this already. You can keep track here: https://github.com/commaai/openpilot/issues/27353
