### ISSUE TITLE
Prius: missing bus 1 traffic

### ISSUE THREAD

**Issue by ReggieR3gg** [commaai/openpilot#29058]
### Describe the bug

Randomly started occurring within the past few days can't figure out what's triggering this
22 prius prime
![20230720_061344](https://github.com/commaai/openpilot/assets/140073713/a3d24869-0bdc-4a62-973b-1c174788be2f)

### Provide a route where the issue occurs

d083dc54dae836f0|2023-07-20--05-55-48

### openpilot version

0.9.3

**Comment by sshane** [comment]
Looks like something is wrong canState1:

![image](https://github.com/commaai/openpilot/assets/25857203/d8a3e162-0080-4ef3-92ce-5ace88be5439)

The camera wants to stay engagd and continues to command acceleration, so doesn't seem like a car issue.

I would try a new USB-C cable in the mean time, but sounds like a possible issue and you should contact support: https://comma.ai/support

**Comment by sshane** [comment]
Any updates @ReggieR3gg? Does this still happen?

**Comment by ReggieR3gg** [comment]
Hi Shane, thankfully a new usb-c cord did the trick! Haven't had the error since

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sshane** [comment]
Thanks for confirming!
