### ISSUE TITLE
ui: fix ETA widget text spacing in map

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29062]
@deanlee alex noticed that this PR changes the spacing between the elements, can we revert that?

Before:
![image](https://github.com/commaai/openpilot/assets/25857203/39b6a547-5f2e-40e7-bac2-579b27be7b1e)

After:

![image](https://github.com/commaai/openpilot/assets/25857203/e1a16c04-dada-43a8-ba8b-1dfce908f6ba)

_Originally posted by @sshane in https://github.com/commaai/openpilot/issues/28780#issuecomment-1644485385_

**Comment by deanlee** [comment]
@jnewb1 thanks for the fix.
