### ISSUE TITLE
Braking Noise / Malfunctions with Pedal Installed on some models

### ISSUE THREAD

**Issue by jfrux** [commaai/openpilot#291]
## Braking Noise with Pedal Installed

Although Pedal Interceptor is just applying gas and has nothing really to do with the brake, it appears to enter an ABS-style emergency braking situation whenever OP is braking at lower speeds, even some higher speeds like 30-45mph.

It's far more noticeable the harder that OP tries to apply brakes at lower speeds.
For instance, when the vehicle is forced completely to zero the brake is difficult to manually override with your foot.  And if you do, it gives loose suddenly and can nudge forward a bit since the brake pedal pressure is releasing.

## No Braking Noise without Pedal Installed

When the Pedal is unplugged and the vehicle is running standard OP it can brake down to zero without the loud noises and overriding problems.

I've confirmed this is happening to the 2018 Honda Odyssey and the 2017 Honda Pilot.
Braking noise is much louder while Pedal is in use.  We haven't figured out why this is.

## Braking malfunctions

While OP is braking, with Pedal attached - if you try to manually press the brake with your foot the brake pedal is firm and almost as if it's being controlled by the ECU via some sort of emergency ABS/ Traction Control braking system.

If you apply the brake and force it to disengage while it's braking, while Pedal attached - it lets loose with a loud-ish grind and then the brake pressure goes away and the vehicle can lunge forward slightly.

I've only confirmed that this "Dramatic braking" issue is happening on my 2017 Pilot Touring.  I have not confirmed with other Pedal users if they experience similar braking glitches.

**Comment by vanillagorillaa** [comment]
@jfrux duplicate? Closing, again, feel free to reopen if needed
