### ISSUE TITLE
Update Loop

### ISSUE THREAD

**Issue by fredcredeur** [commaai/openpilot#29111]
### Describe the bug

The Comma 3 device says there is a 1GB system update.  There are 2 options - 1. Connect to WiFi. 2.Install.  I am connected to wifi and I click install and the next screen I get is "Update failed" with the progess bar greyed out and an option button to Reboot.  This loop continues.

### Provide a route where the issue occurs

NO ROUTE

### openpilot version

Latest Version of Master-Ci

### Additional info

![20230723_193522](https://github.com/commaai/openpilot/assets/38992196/7a9b8c38-f00f-44d4-b776-8b6b322d549e)
![20230723_193534](https://github.com/commaai/openpilot/assets/38992196/bb932e13-e8ef-4765-b26e-9c3a00bf9c74)
![20230723_193548](https://github.com/commaai/openpilot/assets/38992196/78e75d23-a9c3-42f9-8aa0-6de9eb67a0d7)

**Comment by adeebshihadeh** [comment]
See #29104
