### ISSUE TITLE
ui/map: better instruction distances

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29132]
- [ ] round instead of floor - https://github.com/commaai/openpilot/pull/29333
- [ ] more improvements - https://github.com/commaai/openpilot/pull/29151
- [x] show "now" instead of 0 ft? - that's fine, GMaps does this as well. rounding should be good enough
    <img width="600px" src="https://github.com/commaai/openpilot/assets/25857203/a718cdbc-84eb-4dda-99f1-6d41c99b85da">

**Comment by sshane** [comment]
@deanlee want to make a PR to round it?

**Comment by incognitojam** [comment]
I noticed we show miles to 1dp even above 10mi, unlike google maps which rounds it (e.g. show 8.7 mi but round 10.7 mi to 11 mi)
