### ISSUE TITLE
updater UI: sometimes doesn't update status text

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29169]
- [ ] I clicked update, but it didn't change from "update available" until I left the view and came back (or took a while to change, because now it updates properly)
- [ ] The CHECK button can be greyed out without any message (also only hit this one time)

![PXL_20230727_114421072](https://github.com/commaai/openpilot/assets/25857203/42db1147-5cac-4451-bf5e-e4a3c062cbed)

**Comment by adeebshihadeh** [comment]
b92e71a2b6a2067fa67578106a6b5c15f3f5dfb1
