### ISSUE TITLE
Restarting bridge. Error: rpc::rpc_error during call in function `get_sensor_token`

### ISSUE THREAD

**Issue by nathanoy** [commaai/openpilot#29173]
### Describe the bug

Hello,

when executing the `bridge.py` it spams this error multiple times a second:
```
WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 43b5e70-dirty 
WARNING: Simulator API version  = 0.9.13 
Restarting bridge. Error: rpc::rpc_error during call in function get_sensor_token
```

this occurs when executing either `./start_openpilot_docker.sh` or `./bridge.py` and `./launch_openpilot.sh`

My efforts to make the Client API version match the Simulator API version were unsuccessful.

# Temporary fix:
### Using an [older docker image](https://github.com/commaai/openpilot/pkgs/container/openpilot-sim/110716233), seems to work as a workaround (from before the 21 July 2023 ! )
I have not tested which version exactly introduces the breaking changes, but it seems like the update to Python 3.11 broke the client api compatibility.

### OS Version

Ubuntu 20.04.6 LTS

### openpilot version or commit

f911e5f02869475acfb634a058771390fb2273c7

**Comment by haormj** [comment]
same question, ubuntu 22.04, run sim

**Comment by dankanti20** [comment]
Hello guys, 
Please, I need your help on how to run this simulation. I'm novice.
I have already downloaded the dataset.

**Comment by nathanoy** [comment]
After some more fooling around with the situation, it seems to me like the version change to Python 3.11 broke the client API compatibility.

In this pr #28843 the carla client version is defined to be exactly this:

https://github.com/commaai/openpilot/blob/21802265bec5ede0eaf4093ba0cd2c4c5be3b1af/pyproject.toml#L68C1-L68C1
```toml
carla = { url = "https://github.com/commaai/carla/releases/download/3.11.4/carla-0.9.14-cp311-cp311-linux_x86_64.whl", platform = "linux", markers = "platform_machine == 'x86_64'" }
```
Which seems to be made for carla version 0.9.14, yet the file `tools/sim/start_carla.sh` specifically uses `0.9.13`.
After updating `tools/sim/start_carla.sh` to use carla `0.9.14` the error disappears, only the version warning remains (makes sense).

This seems like a great opportunity to try make my first contribution.

**Comment by Dragoadri** [comment]
THANKS SO MUCH THIS FIXED MY PROBLEM!
