### ISSUE TITLE
APN disappears on reboot.

### ISSUE THREAD

**Issue by Chaheeto** [commaai/openpilot#29205]
### Describe the bug

Comma 3 APN vanishes when powered off at next boot, to re establish network APN must be entered again.
This is not with a comma SIM, in Canada, have prime light.

Release 3 branch.

Route before shutdown with LTE working fine:

72c8dc9054796c61|2023-08-01--06-27-36

Route where APN disappears at boot and has to entered again:

72c8dc9054796c61|2023-08-01--15-44-13

### Provide a route where the issue occurs

72c8dc9054796c61|2023-08-01--15-44-13

### openpilot version

0.9.4

**Comment by andiradulescu** [comment]
@adeebshihadeh made a fix for this https://github.com/commaai/openpilot/pull/30517
