### ISSUE TITLE
master-ci: No module named 'tools.bodyteleop'

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#29248]
### Describe the bug

<img width="583" alt="Screenshot 2023-08-05 at 9 38 28 AM" src="https://github.com/commaai/openpilot/assets/1976269/9aadbd7a-e08f-439c-8cb3-6c3ca77a9b6d">

### Provide a route where the issue occurs

-

### openpilot version

master-ci

### Additional info

Reported by [Bassam132](https://discord.com/channels/469524606043160576/616456819027607567/1137326096422014976) and [ifixaudio(Steve)](https://discord.com/channels/469524606043160576/616456819027607567/1137335280458809364)

**Comment by haraschax** [comment]
https://github.com/commaai/openpilot/pull/29249
