### ISSUE TITLE
Lexus IS 2023 [vehicle is not recognized and is in dashcam mode]

### ISSUE THREAD

**Issue by L3R5** [commaai/openpilot#29254]
### Describe the bug

Installed Comma 3 with Toyota harness into 2023 Lexus IS, vehicle is not recognized.

### Which car does this affect?

Lexus IS 2023

### Provide a route where the issue occurs

649bf2997ada6e3a|2023-08-04--22-20-47

### openpilot version

0.9.5

### Additional info

Attempted to fingerprint myself but I could only get as far as "openpilot unavailable; waiting for controls to start."

**Comment by zekst** [comment]
**looking into it**
