### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by roberts2202** [commaai/openpilot#29253]
### Describe the bug

Running the nightly on my C3. Since today, OP crashes with a "ModuleNotFound" error. Commit hash is from the last working master version.

### Provide a route where the issue occurs

534e3360c3936247|2023-08-04--18-37-51--1

### openpilot version

0.9.5 / 932375f7e9b318d100672af5c881c6c41e987d2e\n2023-07-20T14:43:46

### Additional info

![IMG_0300](https://github.com/commaai/openpilot/assets/112574156/b872b7c7-0539-440c-99c8-b00debeaff5b)

**Comment by royjr** [comment]
Should be fixed now. https://github.com/commaai/openpilot/issues/29248
