### ISSUE TITLE
CI <10 mins again

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29380]
- [x] docs build ~15 mins
This one builds openpilot every time without a SCons cache. Fixing that should bring it down to a few minutes.
https://github.com/commaai/openpilot/pull/29436 7-8 mins with this PR

- [x] build simulator ~18 mins
Same as docs? just needs scons cache?
https://github.com/commaai/openpilot/pull/29436 8-9 mins with this PR

- [x] test car models ~15 mins
This has grown with the number of supported cars. `pytest --durations=0` should show where the time is being spent. Running on BuildJet will help here, but want to make sure it's well optimized before we do that. Last time I looked, I believe the panda safety interface was particularly slow.
https://github.com/commaai/openpilot/pull/29514 8-10 mins with this PR
seems to just be the case that we weren't using xdist
- [x] build mac ~20 mins
15 mins is in installing dependencies. caching doesn't seem to be working here. @fredyshox can you check that out?
https://github.com/commaai/openpilot/pull/29399

- [x] unit tests ~17 mins
There's probably a few unnecessarily slow tests here, fixed one of them in https://github.com/commaai/openpilot/pull/29262. in order to properly fix this, we need to make sure individual test case time is easily visible in the output and enforce a default timeout.

- [x] process replay ~18 mins
I think this is pretty well optimized. It's 2.5mins on BuildJet, so just need to merge that.
https://github.com/commaai/openpilot/pull/29277

- [x] docs and sim scons cache misses
https://github.com/commaai/openpilot/pull/29639

**Comment by adeebshihadeh** [comment]
@fredyshox I unchecked macOS. it's under 10 mins, but half the time is spent on cleaning the scons cache, which should take almost no time.

**Comment by fredyshox** [comment]
Working on that here: https://github.com/commaai/openpilot/pull/29401

**Comment by jnewb1** [comment]
For car models:

![image](https://github.com/commaai/openpilot/assets/9648890/b97d90af-5b0f-4e28-a7e8-909e5432e0fa)

About the time is panda_safety_carstate, which is 80% taken by the car interface update loop, which can't really be sped up.
I think our best bet here might just be parallelization with buildjet, we should be able to run these tests in parallel

**Comment by adeebshihadeh** [comment]
@jnewb1 why are docs and simulator checked off? they took 9.5m and 10m on the last commit on master, while the build job took 4m https://github.com/commaai/openpilot/actions/runs/5940120032/job/16108007184

**Comment by jnewb1** [comment]
below 10 minutes on average now, but we can still improve some stuff
