### ISSUE TITLE
nav: some multiline instructions cut off with lanes

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29395]
Couple hundred commits ago: ![image](https://github.com/commaai/openpilot/assets/25857203/90efce03-557b-491c-bb74-87711d99cb0b)

Now: ![image](https://github.com/commaai/openpilot/assets/25857203/35806098-8c20-4519-aa9c-63ed2ac7d24e)

**Comment by deanlee** [comment]
Not sure why, can't reproduce on my laptop

**Comment by sshane** [comment]
I noticed it's not all instructions, only this one. Let me try to find the route

**Comment by sshane** [comment]
So if there was a few more characters after `Freeway` it would add the correct spacing. But if it was just a few characters on the second line, the QWidget this layout was in wouldn't resize. https://github.com/commaai/openpilot/pull/29465 fixes this, as there's no QWidget wrapper any more.
