### ISSUE TITLE
simple test to check TOTAL_SCONS_NODES is up to date

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29402]
related: https://github.com/commaai/openpilot/commit/3e2903a0c184a203718e2430aa33da6e3b62bf7f

**Comment by adeebshihadeh** [comment]
This is only a small QOL thing on non-release builds. Don't think we want the tests to fail in this case. However, we'd definitely merge a PR to get the progress without needing to know TOTAL_SCONS_NODES beforehand.
