### ISSUE TITLE
Subaru: ACC fault

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29405]
Could be from skipped counters?

4822a427b188122a|2023-08-14--16-22-21--14

![image](https://github.com/commaai/openpilot/assets/25857203/26aeaa54-001f-4787-9f77-a23b005a0905)

To figure out if this is the cause:
- [ ] In park, send normal counters for a few seconds, then skip a counter once every second until it faults

**Comment by sshane** [comment]
@jnewb1 this is not related to openpilot, we can close if you're sure

**Comment by jnewb1** [comment]
ill do a bit more research. logging the acc faults is still worthwhile too, so I'll look into those a bit more

**Comment by jnewb1** [comment]
Yea I think so. I'll open a PR to create the counters in OP
