### ISSUE TITLE
[$300 bounty] Multilang: check translation accuracy

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29454]
ie. with some API that can evaluate how accurate translations are. No translation should be egregiously wrong or inappropriate. 

Perhaps something like [Libre Translate](https://libretranslate.com/) ran through https://github.com/mjpost/sacrebleu?

**Comment by harshau007** [comment]
Hello @sshane 

Can I pick this issue and if possible, can you point me the initial file where to begin as I am new to this project?

**Comment by adeebshihadeh** [comment]
Bounty is for a test we can run in CI on all commits. Requirements:
* check for any bad language
* (at least vaguely) checks for accuracy
* runs in CI on all commits
* can't add more than 30s of CI time

Be careful with using external APIs; it's unlikely we can merge something that relies on one, unless maybe it's free and doesn't require a token/auth.

**Comment by adeebshihadeh** [comment]
Splitting this into two bounties since it seems we'll want two different solutions for the two problems:
- [ ] $100 bounty for the bad language check
- [ ] $200 for the accuracy check
