### ISSUE TITLE
Ford maximum cruise speed incorrect

### ISSUE THREAD

**Issue by magicparty** [commaai/openpilot#29494]
### Describe the bug

my ford car shows the cruise speed in KPH, but when I change the openpilot display uint to metric the maximum cruise speed displayed on lefttop is wrong the current speed is correct only the maximum speed is wrong.

### Which car does this affect?

Ford Kuga 2022

### Provide a route where the issue occurs

32a35015aa4d5598|2023-08-20--18-22-54--21

### openpilot version

02e4e06

**Comment by chiachunli08** [comment]
Same situation here with Focus MK4 in Taiwan.

**Comment by incognitojam** [comment]
Is it off by 0-2 kph or completely incorrect?

**Comment by chiachunli08** [comment]
When I set 50km/h on the car, it shows MAX 80 on the openpilot screen

**Comment by incognitojam** [comment]
I've identified the problem, will need a little more work to implement a fix for you
