### ISSUE TITLE
SCons: use moc_files even when in cache_readonly

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#29504]
### Describe the bug

the qt moc files didn't respect the cache_readonly argument to scons before, and would write to the /tmp/scons_cache directory. So I made a PR to move the mocfiles to a safe local directory if we set the cache_readonly param: https://github.com/commaai/openpilot/pull/29437

This works, but it appears the scons won't use the cache if it's copied from another folder (ex if we first build without cache_readonly, then try rebuilding with --cache_readonly, then it will still rebuild all of the moc_files, even though I copied them locally in the scons script).

Need a way to reuse the moc_files while still respecting cache_readonly

**Comment by adeebshihadeh** [comment]
Should be fixed with #29528
