### ISSUE TITLE
CAN based wake-up signal

### ISSUE THREAD

**Issue by jakethesnake420** [commaai/openpilot#29577]
Feature 1: You walk up to the car, and open the door, 2 seconds later the comma device plays a nice little tone and displays the update available message. You press update and reboot and everything is great.

Feature 2: You walk up to your car after letting it sit and the comma device has been turned off. You car detects your key fob and the comma device begins to boot up and is ready by the time you start the car.

Feature 3: You are trying to upload logs on comma connect but your device is powered off because it has been sitting a while. You grab your keys and press the lock button. The device powers up and you are able to upload the logs without getting out of your chair. 

These are not three separate features. This is one feature.

On most new vehicles, when walking up to the car and/or opening the door, there are certain CAN signals that could be used to wake up the device. This would require more RE but it would be completely optional for each platform to implement.

**Comment by adeebshihadeh** [comment]
The device already stays up as long as it can. See thermald's power monitoring for context.
