### ISSUE TITLE
Mazda CX5 OP longitudinal support.

### ISSUE THREAD

**Issue by kothari-jay** [commaai/openpilot#29573]
CX5 relies on its radar for longitudinal driving.  We can enjoy the navigation and other comma longitudinal features if we have support for it. 

This would be a nice addition as CX5 is one of the mainstream car and OP features addition will makes more comma users.

Thanks looking forward to support for it.

**Comment by adeebshihadeh** [comment]
Closing this since it's not an issue. I believe some users have an experimental version of this on a fork somewhere - you can discuss this further in the community discord.
