### ISSUE TITLE
Subaru: inconsistent torque across platforms

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#29627]
### Describe the bug

We need to better unstand the torque differences across different subarus.

Here's a plot of 20,000 subaru segments:

![image](https://github.com/commaai/openpilot/assets/9648890/d7672e39-51af-4d56-aabe-d22264a51d08)

Green shades are the Legacy / Outback
Red shades are various other gen1 cars

I'm not seeing a significant difference between the two cars, even with some people who have manually increased the limits or were running before the torque was decreased. We also have stock ES routes that go up to 1400 on extreme turns before it gives up:

![image](https://github.com/commaai/openpilot/assets/9648890/1fc9147c-54a4-4201-90a4-3a7911fa0ff5)

Relevant (closed) PRs:
https://github.com/commaai/openpilot/pull/23530
https://github.com/commaai/openpilot/pull/29097

### Provide a route where the issue occurs

    f284f22298d498cc|2023-05-24--20-25-16--0 | Long drive with 2047

    f284f22298d498cc|2023-05-25--21-47-32--0 | Long drive with 3071

    f284f22298d498cc|2023-05-25--23-37-31--0 | Route 1: 3071

    f284f22298d498cc|2023-05-25--23-45-24--0 | Route 2: Stock Eyesight

    f284f22298d498cc|2023-05-26--00-20-30--0 | Route 3: 2047

Subarus

### openpilot version

all

**Comment by ClockeNessMnstr** [comment]
2017-2019? Impreza, 2018-2019 Crosstrek, 2020 Crosstrek hybrid are 3071 without errors. 
This was still less torque than the 2019 Forester which errors over 2047, but was fairly comparable at that point.

**Comment by Emalton** [comment]
What can I do on my preglobal Subaru to help out as well?

**Comment by AdamSLevy** [comment]
Any idea what the torque limit is for a 21 crosstrek?
