### ISSUE TITLE
Navigate on openpilot went haywire while driving

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#29686]
### Describe the bug

Shortly after I input a destination and started driving, navigate on openpilot went haywire. During this drive openpilot's performance was also slightly but noticeably degraded, presumably due to the bad map data being fed into the driving model, so I had to pull into a nearby parking lot and restart the car. Doing so fixed the problem and navigate on openpilot returned to normal.

https://github.com/commaai/openpilot/assets/85845724/b9a961eb-9849-4b5a-8552-57b560466df0

### Provide a route where the issue occurs

5c49984c8efb9c9c|2023-08-28--13-24-21--3

### openpilot version

0ac9b0ecc5d0e79c21e9e3f60759459da1ca924e

**Comment by haraschax** [comment]
We are trying to use our own GPS stack for nagivation. However it seems there are still some edge cases we haven't caught. Reverting until I figure out what happened on your drive.
https://github.com/commaai/openpilot/pull/29687
