### ISSUE TITLE
EV6: can packet inconsistent on startup

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29758]
noticed while checking out a fingerprinting issue where the camera failed to respond. The can packet drops out without the multiplexing mode being changed.

![image](https://github.com/commaai/openpilot/assets/25857203/3c457706-e7e5-4110-aa71-023875105d8c)

route: ff2bd20623fcaeaa|2023-08-30--08-05-08

**Comment by sshane** [comment]
@briskspirit can you check this out?

**Comment by briskspirit** [comment]
That's when CAN2 core (bus1/OBD) started to reset because of TEC going up and no ack on the bus. 
![Screenshot from 2023-09-05 14-32-51](https://github.com/commaai/openpilot/assets/11968822/382c8e61-bcb8-43b0-ac67-bde4d800d699)

**Comment by sshane** [comment]
ah, so a side effect of the issue causing https://github.com/commaai/openpilot/issues/29689? Certain ECUs on bus 1 (non-OBD) failed to respond.

**Comment by sshane** [comment]
@briskspirit are you saying that OBD issues caused an issue on bus 1? I can go swap out the comma power, I think it's been faulty for a while now.

**Comment by briskspirit** [comment]
emm, maybe as a side effect, idk. but sometimes there is no ack for our transmitted messages.

**Comment by adeebshihadeh** [comment]
Still an issue?

**Comment by sshane** [comment]
Hmm, a few recent routes looked fine, but this one still looks like it has issues. Also missing all responses from OBD multiplexed queries (VIN and FW):

3f1a6480f940cf9a|2023-12-07--09-02-54

![image](https://github.com/commaai/openpilot/assets/25857203/75ee25bd-68a9-4efa-88e1-d63f70e7bc2c)

**Comment by sshane** [comment]
Hasn't been an issue recently
