### ISSUE TITLE
Problem when delpy ./start_openpilot_docker.sh in tools/sim

### ISSUE THREAD

**Issue by Dragoadri** [commaai/openpilot#29751]
### Describe the bug

Im having a problem when deploying "sudo ./start_openpilot_docker.sh" I get the next error, saying tmux_script.sh is not found when yes, it is in the folder tools/sim: The error log: 
Just attend the last sentence 

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/commaai/openpilot-sim:latest
Error response from daemon: Cannot kill container: openpilot_client: No such container: openpilot_client
**_/bin/bash: ./tmux_script.sh: No such file or directory_**

I must say **sudo ./start_carla.sh** works fine, and some weeks ago, everything worked fine, just tried again and get this issue.

### Provide a route where the issue occurs

none

### openpilot version

0.9.14

**Comment by lihuixian001** [comment]
It seems to be a bug, you need to make the following modifications in  start_openpilot_docker.sh :

OPENPILOT_ DIR="/tmp/openpilot"

**Comment by Dragoadri** [comment]
THANK YOU SO MUCH! This solved it
