### ISSUE TITLE
Bridge.py is giving error timeout in devcontainer

### ISSUE THREAD

**Issue by bvss89** [commaai/openpilot#29760]
### Describe the bug

Hello, while trying to run openpilot in devcontainer bridge.py is giving the following error.
![error](https://github.com/commaai/openpilot/assets/31626320/4744ff6a-72cd-419b-b6ee-3817aa9198c0)

However, start_carla.sh and launch_openpilot.sh are working. Any suggestions please.

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Probably need to forward the ports from the CARLA server. @jnewb1 can you check this out?
