### ISSUE TITLE
Issue when running openpilot 0.9.14 with carla "Take control controls lagging immediately"

### ISSUE THREAD

**Issue by bvss89** [commaai/openpilot#29807]
### Describe the bug

Hello all, please find the attached picture. I am using the recent version of open pilot 0.9.14. When integrated with Carla I am facing this controls lagging issue. My GPU usage is 18 % and RAM usage is 8GB/56GB. It seems sufficient resources are available. I also tried to follow this #27257 thread. But of no use. Also, not maintaining a proper lane path. Any suggestions please. Thanks.
![controls_lagging](https://github.com/commaai/openpilot/assets/31626320/904c1d84-5266-41f7-96c9-668ff7156aaf)

### OS Version

Ubuntu 20.04

**Comment by jnewb1** [comment]
carla sim should run a lot better now, so I'm going to close this. Can you try it on the latest master and see if it resolves your issue? If not, you can reopen.
