### ISSUE TITLE
Vehicle parameter identification failed and car swerving

### ISSUE THREAD

**Issue by ncoop23** [commaai/openpilot#29812]
### Describe the bug

Yesterday while driving on the freeway, comma popped up with vehicle parameter identification failed and started swerving wildly.  On looking at connect, it looks like there may have been GPS interference? Unknown why error showed up. 

### Which car does this affect?

2022 Non SC Bolt EUV Premire

### Provide a route where the issue occurs

0def4a390f6fe5c0|2023-09-06--20-35-36--16

### openpilot version

Masrer fd3b8a3d7511ad3d7c5aa0b82a1e2c28505e5a7f

### Additional info

Vehicle started swerving uncontrollably on the freeway.

**Comment by ncoop23** [comment]
Comma is also coming up with GPS errors.

**Comment by ncoop23** [comment]
![GPS](https://github.com/commaai/openpilot/assets/1179525/40d64997-5f06-4525-aa6b-3ff249f4ce1a)

**Comment by haraschax** [comment]
https://github.com/commaai/openpilot/commit/55b391509d94c45000df6754f173ad446dc1b34c

Already fixed in master, yes it is GPS related.
