### ISSUE TITLE
[$100 bounty] CI: check PR target branch

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29845]
Automatically close any PRs that are made against a different branch than master:
* only for forks, not PRs from branches on this repo
* leave a comment to make the PR against the master branch
* add it to this workflow: https://github.com/commaai/openpilot/blob/master/.github/workflows/labeler.yaml

maybe this is good? https://github.com/Vankka/pr-target-branch-action

**Comment by AbhinavGoel9** [comment]
@adeebshihadeh  I'm interested in contributing to this issue and noticed that the provided solution uses the GitHub CLI (`gh`). Before I proceed, I wanted to confirm if it's okay to use `gh` for closing pull requests. If there are any preferences or specific alternatives you'd like me to consider, please let me know.

**Comment by jnewb1** [comment]
> @adeebshihadeh I'm interested in contributing to this issue and noticed that the provided solution uses the GitHub CLI (`gh`). Before I proceed, I wanted to confirm if it's okay to use `gh` for closing pull requests. If there are any preferences or specific alternatives you'd like me to consider, please let me know.

If it’s included in the Ubuntu 20.94 image then that’s fine
