### ISSUE TITLE
"CAN Bus Disconnected:  Likely Faulty Cable" after installing 3x [& stock OP release] inside 2022 Ford Explorer

### ISSUE THREAD

**Issue by DocBuzz** [commaai/openpilot#29874]
### Describe the bug

Just got a brand new Comma 3X installed a few days ago in a 2022 Ford Explorer.

I have seated and reseated all connections at least 3+ times, but this same "CAN Bus Disconnected" message persists, along with other error messages that the vehicle displays on the dash -- "Pre-Collision Assist Not Available" and "Front Camera Fault Service Required".

As soon as I disconnect all Comma 3X hardware and replace the stock Ford Explorer plug back into the stock camera, the dash error messages go away and the LKAS and radar cruise control features work as they did before.

### Which car does this affect?

2022 Ford Explorer

### Provide a route where the issue occurs

3dc276749fb12bfa|2023-09-11--11-54-16

### openpilot version

0.9.4-release / release3 / 2403525 / Jul 27

**Comment by landonh12** [comment]
Also seeing this on my 2022 Honda Civic, running OP 0.9.4 release3 branch.

**Comment by sshane** [comment]
Hi, can you put your device on Wi-Fi so we can upload relevant logs @DocBuzz? @landonh12 can you post a route we can check out?

**Comment by landonh12** [comment]
> Hi, can you put your device on Wi-Fi so we can upload relevant logs @DocBuzz? @landonh12 can you post a route we can check out? Did this just start?

Yes, it just started today. I installed my C3X on September 1st. I left town this past weekend and it stayed mounted in my car over the weekend, exposed to the Texas heat (~97+F). I can upload logs when I get home.

**Comment by landonh12** [comment]
@sshane Here's a few routes. Logs are uploading.

e1322f187a15feaa|2023-09-11--14-31-14--0
e1322f187a15feaa|2023-09-11--14-48-22--0
e1322f187a15feaa|2023-09-11--13-29-09--0

**Comment by adeebshihadeh** [comment]
@landonh12 this is most likely a cable issue. Can you first try reseating all cables (OBD-C, harness, etc.)? If that doesn't fix it, open a ticket at https://comma.ai/support and we'll send you a new cable (reference this issue).

**Comment by adeebshihadeh** [comment]
@DocBuzz can you try out the latest openpilot using this URL: `installer.comma.ai/commaai/nightly`?

**Comment by DocBuzz** [comment]
> 
How can I upload the logs?

**Comment by landonh12** [comment]
@adeebshihadeh Done - thanks, new cable shipping soon. I do want to point out that I replaced my cable with an Apple Thunderbolt 3 cable and it seems to have resolved the issue, so it definitely looks like it was the cable.

**Comment by DocBuzz** [comment]
> Hi, can you put your device on Wi-Fi so we can upload relevant logs @DocBuzz?

Finally figured out how to upload the logs.  Most of them have been uploaded so far....  As soon as they're all uploaded, I'll try using the nightly build... but this definitely seems like a hardware issue to me.

**Comment by DocBuzz** [comment]
Log files have been completely uploaded.

I upgraded to the nightly build, and I'm still getting the same error message.

Only thing I can assume is that the harness is faulty??  Or this 2022 Ford Explorer managed to encrypt the CAN Bus somehow??

**Comment by calvarado22** [comment]
I am also having this exact problem on the same model vehicle and comma3x version.

**Comment by sshane** [comment]
@calvarado22 what is your dongle id?

**Comment by sshane** [comment]
I see no traffic from the camera and ack errors, so that's likely why the dash faults occur. @briskspirit can you check it out?

**Comment by DocBuzz** [comment]
> @DocBuzz I see no traffic from the camera and ack errors, so that's likely why the dash faults occur. @briskspirit can you check it out?

The only other response I've been able to get from someone on Discord was that all 3 CAN Buses are not communicating with OP.  But is there a solution??

**Comment by DocBuzz** [comment]
> @DocBuzz I see no traffic from the camera and ack errors, so that's likely why the dash faults occur. @briskspirit can you check it out?

I just realized that the route wasn't made public, so perhaps changing that will allow more people to identify the problem...

**Comment by calvarado22** [comment]
@sshane my Dongle ID is 61c2653dbfb9b38b

**Comment by ecambronerosaba** [comment]
Also having this issue on a Chevy bolt 2023

**Comment by DocBuzz** [comment]
I got a replacement USB-C ver 3.2 gen 2 cable today and ran into the same issue as my previous routes (bus 2 freezes after about 7 or 8 seconds)....

But I did manage to get 2 routes that gave a different error message:  "CAN Error:  Check Connections"....
3dc276749fb12bfa|2023-09-17--18-31-30
3dc276749fb12bfa|2023-09-17--20-50-40

I installed the Master-CI branch (which I'm assuming has the 'bus off fix' that briskspirit mentioned in his last post) and still experienced the bus 2 freezing issues after 7 or 8 seconds, but one thing I _did_ notice is that the speed displayed on the screen wasn't constantly swapping back to 0 about 5 times per second....
3dc276749fb12bfa|2023-09-18--03-23-07
3dc276749fb12bfa|2023-09-18--03-30-33

The randomness between when I get the CAN Bus Disconnected -vs- CAN Error messages makes me think this is a hardware issue, but I don't understand why getting the former error automatically freezes the bus 2 output.

Any tips or advice would be greatly appreciated.

**Comment by paulmg377** [comment]
Same issue 2022 escape.

**Comment by sshane** [comment]
@ecambronerosaba what is your dongle id?

**Comment by bowenpan17** [comment]
Same issue here. C3 with 21 ridgeline and 19 Corolla. The device is now back with Comma on RMA. Replaced 5 cables 2 harnesses and nothing helps.  Consistent CAN BUS error.  I live in Phoenix so the garage is consistently 120 degrees and when I am outside, the device probably gets really hot under the sun.

**Comment by vanillagorillaa** [comment]
@DocBuzz and @calvarado22 can you both open a support ticket for this if you are still having issues?

**Comment by DocBuzz** [comment]
> @DocBuzz and @calvarado22 can you both open a support ticket for this if you are still having issues?

Opened one over a week ago... "Request (62828)".

Haven't messed with it since, because I'm tired of unplugging, reseating over and over again.  Will probably try one more time in the next couple days and return by Friday if I can't get it to work.

**Comment by bowenpan17** [comment]
I returned mine last week after more than a month of emails.

**Comment by adeebshihadeh** [comment]
We've confirmed that this is a wiring issue with some Ford Q3 harnesses. Sorry for the back and forth on this one; it's particularly tricky one to debug remotely that involves different pieces of HW and some low level software drivers.

**Comment by paulmg377** [comment]
Getting the same error message on a ford q3 harness. Should I contact Comma to do a return or is there an option to get a replacement?

**Comment by adeebshihadeh** [comment]
Yes, open a support ticket at comma.ai/support and we'll get it swapped out for you.

**Comment by devsoftech** [comment]
Reproducing on a 2022 Ford Explorer, as advised in thread, raised request for harness fix. Had to fork as ecu ID  Nov/22, 2023 purchase. Wasn't expecting problematic harness. Is the ford q4 correct harness ?

**Comment by DocBuzz** [comment]
> Reproducing on a 2022 Ford Explorer, as advised in thread, raised request for harness fix. Had to fork as ecu ID Nov/22, 2023 purchase. Wasn't expecting problematic harness. Is the ford q4 correct harness ?

Q3 is the correct harness for the 2022 Explorer.  The ones that were sent out a few months back don't match the Q3 schematic, which is fairly easy to find with Google.

**Comment by wellsm511** [comment]
I am new here and I received this message and error today on my 21 Honda Pilot.  Any ideas

**Comment by Chillimayo** [comment]
Hello,

I have a 2021 Hyundai Santa Fe and I have received the same error message. “CAN bus disconnected: likely faulty wire”. I only recieved my comma 3 a week ago. 

When I tried using open pilot I could only get dashcam mode car unrecognised. So I tried using sunnypilot. Initially this error message came up , but i redownloaded sunny pilot and i finally got it to work.

after about 10 minutes though i get the same error message while driving. “CAN bus disconnected: likely faulty wire”. I selected my vehicle on the vehicle options on sunnypilot.

I thought perhaps I would need to select the 2020 model as my car was manufactured 2020 December but it’s compliance date is 2021. I did this it worked again for around 10 minutes then same again “CAN bus disconnected: likely faulty wire”.

Im really not sure if it’s hardware or firmware. I’m pretty bad when it comes to technical stuff and I have no idea how to generate logs (yet) as I just received
![Uploading IMG_1939.jpeg…]()
 it a few days ago.

**Comment by wellsm511** [comment]
My issue was unable to be resolved, and I was asked to ship the unit back for repair.  I received it back yesterday, but I have not hooked it up yet to see if the issue is fixed or not.  I hope to get the opportunity to do that this weekend.  I will keep you posted.

 

Mike
