### ISSUE TITLE
"Low on memory" 91% Memory Used Error

### ISSUE THREAD

**Issue by TacoBodaco** [commaai/openpilot#29916]
### Describe the bug

OpenPilot suddenly started beeping and flashing telling me to take over immediately due to being "Low on memory." After I took over, the issue appeared to go away for a minute before coming back up and saying that 91% of memory was being used and to reboot the device. I rebooted the device but my lane assist and cruise control were malfunctioned/disabled in my 2021 RAV4 Hybrid. After pulling over and starting my car again, everything appeared to work normally.

I am using the Comma 3X with stock OpenPilot 0.9.4. As this is only my 2nd week with my Comma, I posted on the Discord and was told that memory leak errors are definitely not common.

### Provide a route where the issue occurs

9b43a206d03afb12|2023-09-14--17-43-11

### openpilot version

0.9.4

**Comment by adeebshihadeh** [comment]
Thanks for reporting, it's a case of #29168
