### ISSUE TITLE
Hyundai CAN (EV): TCS13->DriverBraking doesn't describe brake pedal depressed status

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#29921]
It seems to describe whether the user has depressed far enough to actuate friction brakes. Before then it's using regen braking which is a different signal (that also has gas pressed!). User could possibly be fighting openpilot ACC during this time.

d3a039910163c67a|2023-09-07--22-59-30--4

![image](https://github.com/commaai/openpilot/assets/25857203/e115b410-c81d-40cd-9d31-25e12c8cdc3f)

**Comment by sshane** [comment]
@briantran33 can you get a route in dashcam mode with stock SCC activated and lightly and slowly press the brakes until it disengages? Try to test both when the stock system is accelerating an braking

**Comment by sshane** [comment]
On our EV6 it looks like the TCS's DriverBraking is actually DriverOverride (without the gas pressed status), as the brake bit from `BRAKE` looks similar to the CAN's version (doesn't capture low sens inputs). So only an issue on CAN EVs.

![image](https://github.com/commaai/openpilot/assets/25857203/f7abfbfa-e956-446e-806d-22ebb51cc011)

**Comment by briantran33** [comment]
> @briantran33 can you get a route in dashcam mode with stock SCC activated and lightly and slowly press the brakes until it disengages? Try to test both when the stock system is accelerating and braking

Sure, I will do that after I get back from the vacation.

**Comment by briantran33** [comment]
d3a039910163c67a|2023-09-22--22-09-24--0 - This should have both the scenarios. @sshane

**Comment by sshane** [comment]
It indeed looks like SCC uses DriverOverride, not DriverBraking!

![image](https://github.com/commaai/openpilot/assets/25857203/2377c36f-407a-40c0-8986-3c97cdc7486b)

**Comment by sshane** [comment]
Same with our Sonata (stock route):

ee11091550c9a627|2023-11-08--21-49-12

![image](https://github.com/commaai/openpilot/assets/25857203/7b0b0029-c24f-4852-84ae-f020fb53ecb7)
