### ISSUE TITLE
Openpilot unable to identify my 2019 Honda Ridgeline

### ISSUE THREAD

**Issue by jtooper** [commaai/openpilot#29987]
### Describe the bug

Openpilot unable to identify my 2019 Honda Ridgeline.
It is in Dashcam Mode.

### Which car does this affect?

Honda Ridgeline 2019

### Provide a route where the issue occurs

N/A

### openpilot version

Openpilot 0.9.4

**Comment by sshane** [comment]
Hi, I merged your missing combination meter firmware revision into master. Please stick on `nightly` branch until 0.9.16 comes out.

Installer URL: https://installer.comma.ai/commaai/nightly

**Comment by jtooper** [comment]
It was a cabling issue and I resolved it and my Comma 3X is working fine now.
Thank you for the support.
