### ISSUE TITLE
OP crashed with errors on dashboard an beeps from device.

### ISSUE THREAD

**Issue by abdulrahman004** [commaai/openpilot#29981]
### Describe the bug

On 9/17 when using OP on a drive; the software crashed with multiple beeps coming from logic board and UI went blank. My Toyota Sienna's dash had multiple warnings including radar cruise control not available, lane departure warning not available etc. Device had to be disconnected and capacitor discharged before the device booted up again. 
This has happened in the past few times but I was on a fork. Installed stock OP to get a repro
Logs have been uploaded for this drive.

### Provide a route where the issue occurs

29c3837b928fbd10|2023-09-17--20-40-56--12

### openpilot version

0.9.4

### Additional info

If additional logs (tombstone ?) are needed; let me know. i can ssh on the device or even have the device be online

**Comment by adeebshihadeh** [comment]
Thanks for getting a repro on stock. Unfortunately, there's nothing indicating what happened at the end of the route, and since you drained the caps, the subsequent bootlog also didn't have any info. This seems most likely to be a hardware issue, so let's move this to a ticket at comma.ai/support.
