### ISSUE TITLE
Comma power is connected to the vehicle, it automatically switches to ACC mode

### ISSUE THREAD

**Issue by chanhojung** [commaai/openpilot#29997]
### Describe the bug

To reiterate the ignition issue, when the car is completely off, connecting the comma power (OBD) and RJ45 cable to the harness box and then automatically powers the car and does not turn off when the ignition button is pressed.
I'll post a video about this phenomenon later.

### Which car does this affect?

AZERA Hybrid 6TH Generation

### Provide a route where the issue occurs

66189dd8ec7b50e6|2023-09-20--07-02-12

### openpilot version

0.9.5

**Comment by vanillagorillaa** [comment]
It's hard to tell exactly from your video, but it appears that you are using non official hardware (specifically the car harness). Can you confirm?

**Comment by vanillagorillaa** [comment]
We can't really provide support for non official hardware. If I had to guess, you (or whoever you bought this from) may have wired the camera ignition line into the 12v line on the harness. This would feed 12v constant from the OBDII port into the car and camera ignition line. Ensure that you are following the diagrams here and have the proper wiring. https://github.com/commaai/neo/blob/master/car_harness/black_panda_harness.jpg

**Comment by sshane** [comment]
Would be interesting to know what the smallest set of hardware causes this. Does just the comma power (no t

Does it happen with:
- comma power (no cable)
- comma power (with cable)
- + harness box
- + harness connector
- + 3X/device
