### ISSUE TITLE
Guiding the blind

### ISSUE THREAD

**Issue by nygman** [commaai/openpilot#3]
I am not a programer or an engineer, but I have relatives that have lost or impaired sight and I would like to develop an electronic seeing guide dog. I want to develop an opensource hardware reference design so anyone can build their own portable device with powersource, cameras, radar, GPS, audio in/out, etc. that would be able to use a modified version of this software to provide active descriptive narration of the environment and guidance via an audio and tactile interface. The system would interpret traffic signals, walk/dont walk signs, and help keep the user on the sidewalks and paths, avoiding dangers like sharp drops, uneven ground, large obstacles, dead ends, etc. Users can hear descriptions, and receive vibrations on their left and right sides, to assist navigation. The device can be programed, much like a modern in car GPS system does. 

The project needs to standardize the hardware requirements, and schematics, as well as develop this software to output to a human rather than a wheel, brake and accelerator.

**Comment by mgraczyk** [comment]
This sounds like worthwhile project to undertake, but unfortunately outside the scope of openpilot.
