### ISSUE TITLE
长城哈佛h6要加装什么才能实现自动驾驶？

### ISSUE THREAD

**Issue by honryhonry** [commaai/openpilot#30]
长城的车硬件没有达到你提到两种车的标准，我需要加装什么设备才可以用上您的软件呢？neo.我是个英文盲，现在用翻译软件在看你的网站，觉得您非常伟大！

**Comment by sunmoon9898** [comment]
装上后，兄弟，你敢开不，哈哈

**Comment by honryhonry** [comment]
当然敢开

**Comment by honryhonry** [comment]
你是那里人，朋友？

**Comment by sunmoon9898** [comment]
别人的地盘，私聊： sunmoon9898@hotmail.com

**Comment by honryhonry** [comment]
得了吧，我不觉得neo建立的这个平台是别人的地方，听到neo的讲解视频我觉得他非常伟大，值得信赖的人，知道他后我可是废寝忘食在他的网站研究了好多天，所有的问题都可以在这个上面讲。

**Comment by honryhonry** [comment]
Geohot，这个时候应该还在睡觉吧，希望您看到可以回复我！嘿嘿😁

**Comment by hywanghywang** [comment]
能留一下你的联系方式吗？

**Comment by honryhonry** [comment]
不留联系方式，就这上联系就很好，有好的建议，都可以提出来

**Comment by geohot** [comment]
Read this through a translator, still unclear what the issue is.

**Comment by honryhonry** [comment]
为什么只选择这一款车呢？那样不是很局限吗

**Comment by qkhhyga** [comment]
honry，他写得很明白了，目前只支持的车型是本田的，大概是因为这两款车的can协议公开的，现在有很多汽车的通信协议是封闭的，包括国产车

**Comment by 9crk** [comment]
哈氟H6没有ACC，控制不了你的方向盘。
