### ISSUE TITLE
Optimus Prime model broken with CUDAExecutionProvider

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#30074]
Optimus Prime model is currently broken with the onnxruntime CUDAExecutionProvider, possibly related to this issue: https://github.com/microsoft/onnxruntime/issues/12726

Here's a simple repl:

```
import matplotlib.pyplot as plt

import numpy as np
import onnxruntime as ort

cpu_provider = ('CPUExecutionProvider', {})
gpu_provider = ('CUDAExecutionProvider', {})

path = "selfdrive/modeld/models/supercombo.onnx"

inputs = dict(np.load("test.npz"))

options = ort.SessionOptions()
options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL

cpu_session = ort.InferenceSession(path, options, providers=[cpu_provider])
gpu_session = ort.InferenceSession(path, options, providers=[gpu_provider])

outputs_cpu = cpu_session.run(None, inputs)[0]
outputs_gpu = gpu_session.run(None, inputs)[0]

np.testing.assert_equal(outputs_cpu, outputs_gpu)
```

(this zip folder has the npz with sample inputs)
[test.zip](https://github.com/commaai/openpilot/files/12741803/test.zip)

**Comment by adeebshihadeh** [comment]
The model replay test in Actions doesn't catch this?

**Comment by jnewb1** [comment]
It's only with the CUDA execution provider, CPU works fine

**Comment by jnewb1** [comment]
> For pytorch -> ONNX, the layernorm module would be splitted into several operaters such as reduce sum, div etc., which may easily bring about FP16 overflow.
We can implement a LayerNorm operator by Welfold Algorithm rather than standard (reduce sum -> divide).
or replace related operator by some safe operators in ONNX model.

this is from the issue on onnxruntime
