### ISSUE TITLE
Powering Down

### ISSUE THREAD

**Issue by tglevrie** [commaai/openpilot#30088]
### Describe the bug

System would restart randomly, but now it it's powered down and won't power on. 

### Provide a route where the issue occurs

1c05783affe6641f/2023-09-23--23-04-54

### openpilot version

0.9.3

### Additional info

Sometimes would get stuck on comma logo, so I would pull the USB-c to force reset.

**Comment by adeebshihadeh** [comment]
This is likely a HW issue with the device. Open a ticket at https://comma.ai/support.
