### ISSUE TITLE
2018 Honda CRV not recognized

### ISSUE THREAD

**Issue by achanin00** [commaai/openpilot#30081]
### Describe the bug

New install into a 2018 Honda CRV with touring option.  The car natively has radar, line detection camera, and ACC.  OpenPilot is not recognizing the vehicle.  Please see the pictures below.

![OpenPilot1](https://github.com/commaai/openpilot/assets/102173319/68dc8c69-21b5-4f92-a755-45137c1b9a00)
![OpenPilot4](https://github.com/commaai/openpilot/assets/102173319/983fb353-3183-43dd-8e00-75c05281215c)
![OpenPilot2](https://github.com/commaai/openpilot/assets/102173319/28e23a45-8ad6-4e76-ba22-d238642ee12c)
![OpenPilot3](https://github.com/commaai/openpilot/assets/102173319/fa4b21ea-bc3d-44c1-aa5a-520eb458d4b6)

### Which car does this affect?

Honda CRV 2018

### Provide a route where the issue occurs

N/A

### openpilot version

latest downloaded from openpilot.comma.ai

### Additional info

N/A

**Comment by sshane** [comment]
Have you plugged in the comma power? It's required at this time to fingerprint.

**Comment by achanin00** [comment]
I am not sure what you mean by commapower.

I followed the installation video exactly. Device clearly has power since
the screen is working

**Comment by sshane** [comment]
This should have come with the device. It plugs into the OBD port of the car and connects to the harness box with the RJ45 cable https://www.comma.ai/shop/comma-power

Is it plugged in?

**Comment by achanin00** [comment]
Yes, of course it is plugged in. I assumed the comma power is coming from
that plug.

**Comment by sshane** [comment]
I see errors on canState1 when it's multiplexed to the OBD port, as well as transmit errors, so somewhere it's not able to communicate with the car's ECUs. Can you snap a photo of it installed?

I would try:

- Swap out OBD C (USB C) cable and/or ethernet cable to harness box (try OBD C first)
- Switch to master which has better logging
- If neither work, open a support ticket at https://comma.ai/support and we can migrate the issue over to there.

**Comment by achanin00** [comment]
I am traveling today.  Will take a look at the wiring when I get home
tomorrow.

The comma device is getting power.   Doesn't that imply that the USB-C
wiring is working correctly?

**Comment by achanin00** [comment]
Shane,

Thank you for your help.  The issue was with iffy connection of the
ethernet cable.  Openpilot now properly recognizes my car.

Thanks again,
Alex
