### ISSUE TITLE
car unreconized

### ISSUE THREAD

**Issue by ando005** [commaai/openpilot#30106]
### Describe the bug

just bought comma 3x with recommended harness on 9-22-23 from comma.  and it states my car is supported .. 
i have a 2023 Ioniq 5 limited with HDA 2  ..  and website states its fully supported .. however i plugged everything in and installed open pilot and it say my car is un recognized.  

i am not new to comma ..  i have comma  3  cross country on another car that works fine.. 

### Which car does this affect?

2023 Ioniq 5 limited 

### Provide a route where the issue occurs

0ef08dee6701f32d|2023-09-29--09-22-23

### openpilot version

0.9.4

**Comment by sshane** [comment]
Your car had a newer ADAS camera build date we hadn't yet seen. Your car works in master-ci, nightly branches with this PR: https://github.com/commaai/openpilot/pull/29307

Installer: https://installer.comma.ai/commaai/nightly
