### ISSUE TITLE
[$100 bounty] Scons: don't use abspath anywhere

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#30161]
### Describe the bug

any abspath that we use will cause cache invalidation in CI because the workspace folder changes

This is an issue in:
- jenkins (workspace folder is different every time)
- devcontainer (workspace is /workspaces/openpilot, whereas cache is /tmp/openpilot from regular CI)
- was an issue in the sim and docs images, until I moved the workspace to /tmp/openpilot

**Comment by adeebshihadeh** [comment]
I suspect this will be hard to test for. Does it only matter for the targets?

**Comment by jnewb1** [comment]
we can just test it by asserting that /tmp/openpilot doesn't appear in the build logs in CI

**Comment by adeebshihadeh** [comment]
Bounty is for writing a test for this and fixing all instances.

**Comment by wgenh** [comment]
Can we keep the abspath in selfdrive/controls/lib/longitudinal_mpc_lib?

**Comment by wgenh** [comment]
Can someone check [this](https://github.com/commaai/openpilot/pull/31816)?

**Comment by jnewb1** [comment]
see https://github.com/commaai/openpilot/pull/31816#issuecomment-2000183711

if someone has a better idea to solve this then we can reopen, perhaps with sub bounties
