### ISSUE TITLE
Comma 3. Car Unrecognized msg. Toyota Camry Hybrid 2021 (Thailand)

### ISSUE THREAD

**Issue by dwerty3** [commaai/openpilot#30164]
### Describe the bug

Hello.
I bought new Comma 3, install it but it showed messages after start:
1. Openpilot was unable to identify your car. Your car is either unsupported or ECUs are not recognized. Please submit a pull request to add the firmware version to the proper vehicle. Need support? Join discourd.comma.ai.
2. Unsupported car.
3. Car Unrecognized.

Also driver camera preview button didn't work and showed "Starting camera" only and nothing more.

I read [fingerprint manual](https://github.com/commaai/openpilot/wiki/Fingerprinting) then add my car fingerprint to [values.py](https://github.com/dwerty3/openpilot/blob/master/selfdrive/car/toyota/values.py) and reinstall from https://installer.comma.ai/dwerty3/master

<details><summary>**Fingerprint from "carParams" log:**</summary>

               'carFw': [{'address': 1968,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'abs',
                          'fwVersion': b'F152633214\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1976,
                          'subAddress': 0},
                         {'address': 1937,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'dsu',
                          'fwVersion': b'8821F0609100    ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1945,
                          'subAddress': 0},
                         {'address': 1920,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'srs',
                          'fwVersion': b'8917F06420\x00\x00\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1928,
                          'subAddress': 0},
                         {'address': 1924,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'srs',
                          'fwVersion': b'8917F06420\x00\x00\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1932,
                          'subAddress': 0},
                         {'address': 1953,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'eps',
                          'fwVersion': b'8965B33621\x00\x00\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1961,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'hvac',
                          'fwVersion': b'8865F3301101    ',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1996,
                          'subAddress': 0},
                         {'address': 1792,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'engine',
                          'fwVersion': b'\x018966306L9000\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'\x10\x01', b'\x10\x03', b'"\xf1\x81'],
                          'responseAddress': 1800,
                          'subAddress': 0},
                         {'address': 2002,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'hybrid',
                          'fwVersion': b'\x02899833325100\x00\x00\x00\x00899853310000\x00\x00\x00\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'\x10\x01', b'\x10\x03', b'"\xf1\x81'],
                          'responseAddress': 2010,
                          'subAddress': 0},
                         {'address': 1984,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'combinationMeter',
                          'fwVersion': b'\x03838000XF3128\x00\x00\x00\x00838000XF3222\x00\x00\x00\x00838000XF3322\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'\x10\x01', b'\x10\x03', b'"\xf1\x81'],
                          'responseAddress': 1992,
                          'subAddress': 0},
                         {'address': 1872,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'8821F0609100    ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1880,
                          'subAddress': 15},
                         {'address': 1872,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'8646F0601400    ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1880,
                          'subAddress': 109},
                         {'address': 1872,
                          'brand': 'toyota',
                          'bus': 0,
                          'ecu': 'epb',
                          'fwVersion': b'895DF33010\x00\x00\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'>', b'\x1a\x88\x01'],
                          'responseAddress': 1880,
                          'subAddress': 44}],

</details>

<details><summary>**New fingerprint in values.py**</summary>

```
  CAR.CAMRYH_TSS2: {
    (Ecu.eps, 0x7a1, None): [
      b'8965B33621\x00\x00\x00\x00\x00\x00', # notice that the firmware from car params is added here.
      b'8965B33630\x00\x00\x00\x00\x00\x00',
      b'8965B33650\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.abs, 0x7b0, None): [
      b'F152633D00\x00\x00\x00\x00\x00\x00',
      b'F152633D60\x00\x00\x00\x00\x00\x00',
      b'F152633214\x00\x00\x00\x00\x00\x00', # notice that the firmware from car params is added here.
      b'F152633310\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.engine, 0x700, None): [
      b'\x018966306Q6000\x00\x00\x00\x00',
      b'\x018966306Q7000\x00\x00\x00\x00',
      b'\x018966306T0000\x00\x00\x00\x00',
      b'\x018966306V1000\x00\x00\x00\x00',
      b'\x018966306L9000\x00\x00\x00\x00', #notice that the firmware from car params is added here.
      b'\x01896633T20000\x00\x00\x00\x00',
    ],
    (Ecu.fwdRadar, 0x750, 15): [
      b'\x018821F6201200\x00\x00\x00\x00',
      b'\x018821F6201300\x00\x00\x00\x00',
      b'\x018821F6201400\x00\x00\x00\x00',
      b'8821F0609100    ', #notice that the firmware from car params is added here.
    ],
    (Ecu.fwdCamera, 0x750, 109): [
      b'\x028646F3305200\x00\x00\x00\x008646G5301200\x00\x00\x00\x00',
      b'\x028646F3305300\x00\x00\x00\x008646G5301200\x00\x00\x00\x00',
      b'\x028646F3305300\x00\x00\x00\x008646G3304000\x00\x00\x00\x00',
      b'\x028646F3305500\x00\x00\x00\x008646G3304000\x00\x00\x00\x00',
      b'8646F0601400    ', #notice that the firmware from car params is added here.
    ],
  # START. notice that the firmware from car params is added here.
    (Ecu.dsu, 0x791, None): [
      b'8821F0609100    ',
    ],
    (Ecu.srs, 0x780, None): [
      b'8917F06420\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.srs, 0x784, None): [
      b'8917F06420\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.hvac, 0x7C4, None): [
      b'8865F3301101    ',
    ],
    (Ecu.hybrid, 0x7D2, None): [
      b'\x02899833325100\x00\x00\x00\x00899853310000\x00\x00\x00\x00',
    ],
    (Ecu.combinationMeter, 0x7C0, None): [
      b'\x03838000XF3128\x00\x00\x00\x00838000XF3222\x00\x00\x00\x00838000XF3322\x00\x00\x00\x00',
    ],
    (Ecu.epb, 0x750, 44): [
      b'895DF33010\x00\x00\x00\x00\x00\x00',
    ],    
  # END. notice that the firmware from car params is added here.
```

</details>

All of this doesn't help.

### Which car does this affect?

Toyota Camry Hybrid 2021 (Thailand)

### Provide a route where the issue occurs

2ed432126627c66a|2023-10-04--14-14-04

### openpilot version

0.9.5 master

### Additional info

I tried many times to reinstall and change parameters again but can't fix it. Spent already 18 months. Hope you can help me to fix it.

<details><summary>Photos</summary>

![20231004_211616.jpg](https://github.com/commaai/openpilot/assets/106430863/c5fadf82-06e8-46f5-9524-69c59ecb669e)

![20231004_211632.jpg](https://github.![20231004_211623.jpg](https://github.com/commaai/openpilot/assets/106430863/437d5733-eedb-4408-b172-1979692339a6)

![20231004_015331.jpg](https://github.com/commaai/openpilot/assets/106430863/97412d2c-7b04-4b94-b2b3-301d8664c14a)

![20231004_015322.jpg](https://github.com/commaai/openpilot/assets/106430863/ee14d4ac-a7b8-479c-960a-f294f015bff9)

![20231004_211623.jpg](https://github.com/commaai/openpilot/assets/106430863/85771fa9-42fe-44f4-bccd-bab262700427)

![20231004_211632.jpg](https://github.com/commaai/openpilot/assets/106430863/deb0f63b-a78d-4777-b8a2-d78824abc3b2)

![20231004_015331.jpg](https://github.com/commaai/openpilot/assets/106430863/9a0d38e0-5d8e-42ce-a256-236aa9e22ec7)

![20231004_015537.jpg](https://github.com/commaai/openpilot/assets/106430863/ade48b89-3e55-42d9-a56b-818759561385)

</details>

**Comment by jnewb1** [comment]
try this
installer.comma.ai/commaai/toyota-camry-hybrid-fingerprint

**Comment by sshane** [comment]
Your local model year might be 2021, but to openpilot it's a TSS-P Camry Hybrid so you had it in the wrong platform. Can you open a PR to add it to CAMRYH platform? If not just let me know. FYI https://github.com/commaai/openpilot/pull/28641 catches this

**Comment by dwerty3** [comment]
> Can you open a PR to add it to CAMRYH platform? If not just let me know. FYI 

- Thank you for answer. Sorry, but I don't know how to do this. Could you explain?

**Comment by sshane** [comment]
I added your missing engine FW to master. Please try `master-ci` or `nightly` until the next release!

https://installer.comma.ai/commaai/nightly

**Comment by dwerty3** [comment]
> I added your missing engine FW to master in  https://github.com/commaai/openpilot/pull/30177. Please try `master-ci` or `nightly` until the next release!

Hello, @sshane.

I updated it to openpilot nightly (12 Oct) but comma still show Camera Malfunction.

`
![20231012_211333.jpg](https://github.com/commaai/openpilot/assets/106430863/3b34426b-ad6d-46df-a1bc-3c1a060ac90d)

![20231012_210905.jpg](https://github.com/commaai/openpilot/assets/106430863/b316ae46-cd79-4775-8508-24688e469648)

![20231012_210946.jpg](https://github.com/commaai/openpilot/assets/106430863/c0add9d5-8203-4498-af67-d9e8a0a38bb7)

`

**Comment by sshane** [comment]
You should contact support at https://comma.ai/support
