### ISSUE TITLE
scons build fail with ubuntu 20.04. conda virtual enviroment python 3.11.8

### ISSUE THREAD

**Issue by VietPT3502** [commaai/openpilot#30179]
### Describe the bug

this is my log:
tools/ubuntu_setup.sh
.............................................
----   OPENPILOT SETUP DONE   ----
Open a new shell or configure your active shell env by running:
source ~/.bashrc

poetry shell:
Virtual environment already activated: /home/vietpt/miniconda3/envs/openpilot
scons -u -j$(nproc):
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang++ -o cereal/messaging/msgq_tests.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 cereal/messaging/msgq_tests.cc
clang++ -o cereal/messaging/test_runner.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 cereal/messaging/test_runner.cc
clang++ -o cereal/visionipc/test_runner.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 cereal/visionipc/test_runner.cc
clang++ -o cereal/visionipc/visionipc_tests.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 cereal/visionipc/visionipc_tests.cc
In file included from cereal/messaging/msgq_tests.cc:1:
third_party/catch2/include/catch2/catch.hpp:1:In file included from 1cereal/messaging/test_runner.cc:: 2error:
: third_party/catch2/include/catch2/catch.hppunknown type name 'version':
1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hppthird_party/catch2/include/catch2/catch.hpp::11::1414::  errorerror: : expected ';' after top level declaratorexpected ';' after top level declarator

version https://git-lfs.github.com/spec/v1version https://git-lfs.github.com/spec/v1

             ^             ^

             ;             ;

third_party/catch2/include/catch2/catch.hpp:2:1third_party/catch2/include/catch2/catch.hpp:: 2error:: 1unknown type name 'oid'; did you mean 'void'?:
 error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
third_party/catch2/include/catch2/catch.hpp:2:oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc11
:          ^ 
error          ;: 
expected ';' after top level declarator
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fcthird_party/catch2/include/catch2/catch.hpp
:           ^2
:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
6 errors generated.
In file included from cereal/visionipc/test_runner.cc:2:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
6 errors generated.
clang++ -o common/tests/test_runner.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 common/tests/test_runner.cc
clang++ -o common/tests/test_util.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 common/tests/test_util.cc
clang++ -o common/tests/test_swaglog.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 common/tests/test_swaglog.cc
clang++ -o common/tests/test_ratekeeper.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 common/tests/test_ratekeeper.cc
In file included from common/tests/test_runner.cc:2:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
6 errors generated.
In file included from common/tests/test_ratekeeper.cc:1:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
cereal/messaging/msgq_tests.cc:4:1: error: C++ requires a type specifier for all declarations
TEST_CASE("ALIGN"){
^
cereal/messaging/msgq_tests.cc:4:19: error: expected ';' after top level declarator
TEST_CASE("ALIGN"){
                  ^
                  ;
8 errors generated.
In file included from cereal/visionipc/visionipc_tests.cc:4:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
SETLEN=1 /home/vietpt/vietpt/code/openpilot/panda/crypto/sign.py panda/board/obj/panda.bin panda/board/obj/panda.bin.signed /home/vietpt/vietpt/code/openpilot/panda/certs/debug
In file included from common/tests/test_swaglog.cc:5:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
SETLEN=1 /home/vietpt/vietpt/code/openpilot/panda/crypto/sign.py panda/board/obj/panda_h7.bin panda/board/obj/panda_h7.bin.signed /home/vietpt/vietpt/code/openpilot/panda/certs/debug
arm-none-eabi-gcc -o panda/board/pedal/obj/bootstub.pedal.elf -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -O2 -DPEDAL -DALLOW_DEBUG -Wall -Wextra -Wstrict-prototypes -Werror -mlittle-endian -mthumb -nostdlib -fno-builtin -std=gnu11 -fmax-errors=3 -T/home/vietpt/vietpt/code/openpilot/panda/board/stm32fx/stm32f2_flash.ld panda/board/pedal/obj/startup_pedal.o panda/board/pedal/rsa-pedal.o panda/board/pedal/sha-pedal.o panda/board/pedal/bootstub-pedal.o
arm-none-eabi-gcc -o panda/board/pedal/obj/bootstub.pedal_usb.elf -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -O2 -DPEDAL -DPEDAL_USB -DALLOW_DEBUG -Wall -Wextra -Wstrict-prototypes -Werror -mlittle-endian -mthumb -nostdlib -fno-builtin -std=gnu11 -fmax-errors=3 -T/home/vietpt/vietpt/code/openpilot/panda/board/stm32fx/stm32f2_flash.ld panda/board/pedal/obj/startup_pedal_usb.o panda/board/pedal/rsa-pedal_usb.o panda/board/pedal/sha-pedal_usb.o panda/board/pedal/bootstub-pedal_usb.o
arm-none-eabi-gcc -o panda/board/pedal/obj/pedal.elf -Wl,--section-start,.isr_vector=0x8004000 -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -O2 -DPEDAL -DALLOW_DEBUG -Wall -Wextra -Wstrict-prototypes -Werror -mlittle-endian -mthumb -nostdlib -fno-builtin -std=gnu11 -fmax-errors=3 -T/home/vietpt/vietpt/code/openpilot/panda/board/stm32fx/stm32f2_flash.ld panda/board/pedal/obj/startup_pedal.o panda/board/pedal/main-pedal.o
arm-none-eabi-gcc -o panda/board/pedal/obj/pedal_usb.elf -Wl,--section-start,.isr_vector=0x8004000 -mcpu=cortex-m3 -msoft-float -DSTM32F2 -DSTM32F205xx -O2 -DPEDAL -DPEDAL_USB -DALLOW_DEBUG -Wall -Wextra -Wstrict-prototypes -Werror -mlittle-endian -mthumb -nostdlib -fno-builtin -std=gnu11 -fmax-errors=3 -T/home/vietpt/vietpt/code/openpilot/panda/board/stm32fx/stm32f2_flash.ld panda/board/pedal/obj/startup_pedal_usb.o panda/board/pedal/main-pedal_usb.o
gcc -o panda/tests/libpanda/panda.os -c -nostdlib -fno-builtin -std=gnu11 -Wfatal-errors -Wno-pointer-to-int-cast -fPIC -Ipanda/tests/libpanda -Ipanda/board panda/tests/libpanda/panda.c
clang++ -o rednose/helpers/common_ekf.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -Wno-#warnings -Wno-shadow -Wno-deprecated-declarations -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -I/home/vietpt/miniconda3/envs/openpilot/include/python3.11 -I/home/vietpt/.local/lib/python3.11/site-packages/numpy/core/include rednose/helpers/common_ekf.cc
clang++ -o rednose/helpers/common_ekf.os -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -fPIC -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 rednose/helpers/common_ekf.cc
clang++ -o rednose/helpers/ekf_sym.o -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 rednose/helpers/ekf_sym.cc
clang++ -o rednose/helpers/ekf_sym.os -c -std=c++1z -DSWAGLOG="\"common/swaglog.h\"" -g -fPIC -O2 -Wunused -Werror -Wshadow -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -Wno-error=unused-but-set-variable -DSWAGLOG="\"common/swaglog.h\"" -fPIC -I. -Ithird_party/acados/include -Ithird_party/acados/include/blasfeo/include -Ithird_party/acados/include/hpipm/include -Ithird_party/catch2/include -Ithird_party/libyuv/include -Ithird_party/json11 -Ithird_party/linux/include -Ithird_party/snpe/include -Ithird_party/mapbox-gl-native-qt/include -Ithird_party/qrcode -Ithird_party -Icereal -Iopendbc/can -Ithird_party/json11 rednose/helpers/ekf_sym.cc
scons: *** [cereal/messaging/test_runner.o] Error 1
scons: *** [cereal/visionipc/test_runner.o] Error 1
cythonize rednose/helpers/ekf_sym_pyx.pyx
scons: *** [common/tests/test_runner.o] Error 1
scons: *** [cereal/messaging/msgq_tests.o] Error 1
signing 65760 bytes
hash: 1334411ddc0978778219771635be1f6e665f555d
common/tests/test_ratekeeper.cc:6:1: error: C++ requires a type specifier for all declarations
TEST_CASE("RateKeeper") {
^
common/tests/test_ratekeeper.cc:6:24: error: expected ';' after top level declarator
TEST_CASE("RateKeeper") {
                       ^
                       ;
8 errors generated.
scons: *** [common/tests/test_ratekeeper.o] Error 1
signing 58508 bytes
hash: 50153c8413baeee514b4cfd6c5852c971d4d380e
In file included from common/tests/test_util.cc:12:
third_party/catch2/include/catch2/catch.hpp:1:1: error: unknown type name 'version'
version https://git-lfs.github.com/spec/v1
^
third_party/catch2/include/catch2/catch.hpp:1:14: error: expected ';' after top level declarator
version https://git-lfs.github.com/spec/v1
             ^
             ;
third_party/catch2/include/catch2/catch.hpp:2:1: error: unknown type name 'oid'; did you mean 'void'?
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
^~~
void
third_party/catch2/include/catch2/catch.hpp:2:5: error: variable has incomplete type 'void'
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
    ^
third_party/catch2/include/catch2/catch.hpp:2:11: error: expected ';' after top level declarator
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
          ^
          ;
third_party/catch2/include/catch2/catch.hpp:2:12: error: expected unqualified-id
oid sha256:27da57c7a06d09be8dd81fab7246b79e7892b6ae7e4e49ba8631f1d5a955e3fc
           ^
common/tests/test_util.cc:23:1: error: C++ requires a type specifier for all declarations
TEST_CASE("util::read_file") {
^
common/tests/test_util.cc:23:29: error: expected ';' after top level declarator
TEST_CASE("util::read_file") {
                            ^
                            ;
Compiling /home/vietpt/vietpt/code/openpilot/rednose/helpers/ekf_sym_pyx.pyx because it changed.
[1/1] Cythonizing /home/vietpt/vietpt/code/openpilot/rednose/helpers/ekf_sym_pyx.pyx
8 errors generated.
scons: *** [common/tests/test_util.o] Error 1
cereal/visionipc/visionipc_tests.cc:14:1: error: C++ requires a type specifier for all declarations
TEST_CASE("Connecting"){
^
cereal/visionipc/visionipc_tests.cc:14:24: error: expected ';' after top level declarator
TEST_CASE("Connecting"){
                       ^
                       ;
8 errors generated.
scons: *** [cereal/visionipc/visionipc_tests.o] Error 1
common/tests/test_swaglog.cc:40:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(buf[0] == CLOUDLOG_DEBUG);
    ^
common/tests/test_swaglog.cc:43:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(!msg.is_null());
    ^
common/tests/test_swaglog.cc:45:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(msg["levelnum"].int_value() == CLOUDLOG_DEBUG);
    ^
common/tests/test_swaglog.cc:46:50: error: use of undeclared identifier 'Catch'
    REQUIRE_THAT(msg["filename"].string_value(), Catch::Contains("test_swaglog.cc"));
                                                 ^
common/tests/test_swaglog.cc:47:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(msg["funcname"].string_value() == "log_thread");
    ^
common/tests/test_swaglog.cc:48:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(msg["lineno"].int_value() == LINE_NO);
    ^
common/tests/test_swaglog.cc:52:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(ctx["daemon"].string_value() == daemon_name);
    ^
common/tests/test_swaglog.cc:53:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(ctx["dongle_id"].string_value() == dongle_id);
    ^
common/tests/test_swaglog.cc:54:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(ctx["dirty"].bool_value() == true);
    ^
common/tests/test_swaglog.cc:56:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(ctx["version"].string_value() == COMMA_VERSION);
    ^
common/tests/test_swaglog.cc:59:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE(ctx["device"].string_value() == device);
    ^
common/tests/test_swaglog.cc:62:5: error: use of undeclared identifier 'REQUIRE'
    REQUIRE((thread_id >= 0 && thread_id < thread_cnt));
    ^
common/tests/test_swaglog.cc:67:21: error: invalid operands to binary expression ('const char [9]' and 'int')
    INFO("thread :" << i);
         ~~~~~~~~~~ ^  ~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
scons: *** [common/tests/test_swaglog.o] Error 1
scons: building terminated because of errors.




### OS Version

Ubuntu 20.04

### openpilot version or commit

_No response_

### Additional info

_No response_

**Comment by jnewb1** [comment]
we pushed several large files to lfs, try doing a git lfs pull

**Comment by VietPT3502** [comment]
but i was full clone with
git clone --recurse-submodules https://github.com/commaai/openpilot.git
