### ISSUE TITLE
Cabana DBC parse error - multiline signal description

### ISSUE THREAD

**Issue by dzid26** [commaai/openpilot#30175]
### Describe the bug

Cabana cannot load dbc if there are multiple lines in signal descriptions.
![image](https://github.com/commaai/openpilot/assets/841061/52664ddd-af37-430a-b806-a97fefce9e7b)

### Provide a route where the issue occurs

-

### openpilot version

@ 661edd7

### Additional info

_This_ doesn't work:
```
CM_ SG_ 558 STEER_MODE "Control mode request. 
Off - instant 0 torque,
TorqueControl - use steer_torque,
AngleControl - use steer_angle as relative target and steer_torque as feedforward
SoftOff - ramp torque to 0 in 1s,
Command Off after SoftOff to re-enable control.";
CM_ SG_ 558 COUNTER "Rolling counter";
```

_This_ works (removed returns):
```
CM_ SG_ 558 STEER_MODE "Control mode request. Off - instant 0 torque, TorqueControl - use steer_torque, AngleControl - use steer_angle as relative target and steer_torque as feedforward; SoftOff - ramp torque to 0 in 1s, Command Off after SoftOff to re-enable control.";
CM_ SG_ 558 COUNTER "Rolling counter";
```

Other tools I tried never complained about it, including CANdb++ from Vector.

**Comment by sshane** [comment]
We have a discussion for cabana related bugs where @deanlee, the biggest maintainer is pretty active. https://github.com/commaai/openpilot/discussions/26091
