### ISSUE TITLE
rawgpsd died during test run 

### ISSUE THREAD

**Issue by devtekve** [commaai/openpilot#30208]
### Describe the bug

RawGPS died and it forced me to take control, I don't know how to reproduce it reliably, sorry!

### Provide a route where the issue occurs

e1107f9d04dfb1e2|2023-10-09--21-02-26--0

### openpilot version

0.9.5

**Comment by devtekve** [comment]
Similar thing happened on sunnypilot too, I have a stacktrace, this was the issue I created https://github.com/commaai/openpilot/issues/30226 

Stacktrace: 
```
Traceback (most recent call last):
  File "/data/openpilot/openpilot/selfdrive/manager/process.py", line 40, in launcher
    mod.main()
  File "/data/openpilot/system/sensord/rawgps/rawgpsd.py", line 288, in main
    r = setup_quectel(diag)
        ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/system/sensord/rawgps/rawgpsd.py", line 223, in setup_quectel
    send_recv(diag, DIAG_SUBSYS_CMD_F, pack('<BHBBIIII',
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 65, in send_recv
    opcode, payload = diag.recv()
                      ^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 48, in recv
    unframed_message = self.hdlc_decapsulate(raw_payload)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 35, in hdlc_decapsulate
    assert payload[-2:] == pack('<H', ModemDiag.ccitt_crc16(payload[:-2]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by dimdom69** [comment]
Been getting this too on OPGM.

**Comment by adeebshihadeh** [comment]
I'm seeing 3 recent instances of this, all from your device. Still looking into this, but I suspect we'll have to add some more logging to get to the bottom of this.

**Comment by devtekve** [comment]
Could it be then a hardware issue ? 😭 this is where I hate being in Europe 😂 it happens quite often for me

**Comment by adeebshihadeh** [comment]
This is likely software.

**Comment by devtekve** [comment]
That's reassuring! I'd hate going through the customs process... Anything I can do to help?

**Comment by dimdom69** [comment]
I was getting this same error when I was working on a custom feature. I had a made a new daemon that updated once a minute. When I added 'liveLocationKalman' to the SubMaster, I would randomly get this error on startup. I re-implemented the feature using the 'LastGPSPosition' param and the error went away.

**Comment by devtekve** [comment]
@dimdom69 on the SunnyPilot failure I was doing something similar, and I was also subscribing to `liveLocationKalman` IIRC. However, on the stock route I didn't make any modification, maybe I was already on some sort of failure state that remained through the reinstall of stock perhaps? 

Also, thanks for hsaring about the `LastGPSPosition` I wasn't aware of it!

**Comment by adeebshihadeh** [comment]
> I was getting this same error when I was working on a custom feature. I had a made a new daemon that updated once a minute. When I added 'liveLocationKalman' to the SubMaster, I would randomly get this error on startup. I re-implemented the feature using the 'LastGPSPosition' param and the error went away.

I don't see how this could cause any issues with rawgpsd. If you have a branch that reproduces this reliably, that would be very helpful.

**Comment by dimdom69** [comment]
> > I was getting this same error when I was working on a custom feature. I had a made a new daemon that updated once a minute. When I added 'liveLocationKalman' to the SubMaster, I would randomly get this error on startup. I re-implemented the feature using the 'LastGPSPosition' param and the error went away.
> 
> I don't see how this could cause any issues with rawgpsd. If you have a branch that reproduces this reliably, that would be very helpful.

Reverted to using `liveLocationKalman` and now I don't get any errors. I guess I somehow got into an error state that resolved itself with a fresh install? Not sure.

**Comment by devtekve** [comment]
> > > I was getting this same error when I was working on a custom feature. I had a made a new daemon that updated once a minute. When I added 'liveLocationKalman' to the SubMaster, I would randomly get this error on startup. I re-implemented the feature using the 'LastGPSPosition' param and the error went away.
> > 
> > 
> > I don't see how this could cause any issues with rawgpsd. If you have a branch that reproduces this reliably, that would be very helpful.
> 
> Reverted to using `liveLocationKalman` and now I don't get any errors. I guess I somehow got into an error state that resolved itself with a fresh install? Not sure.

I don’t suggest using liveLocationKalman for any realtime gps stuff, it’s better to use gpsLocation and gpsLocationExternal (C3) otherwise the location won’t be updated properly :(
