### ISSUE TITLE
navigate on openpilot not shown

### ISSUE THREAD

**Issue by ildoonet** [commaai/openpilot#30212]
### Describe the bug

I use the lastest codes from master branch and enabled experimental features. 

Also I enabled 'map shown left side'.

But it doesn't show any navigate on openpilot related features. 

How should I access it?

### Provide a route where the issue occurs

1

### openpilot version

0.9.5

**Comment by sshane** [comment]
Do you have prime? If you tap on the screen while onroad, it will bring up the map. Use connect on your phone to choose a destination.

**Comment by ildoonet** [comment]
Thx for the reply

I dont have prime subscription 

Tapping on the screen gives me nothing. 

In comma connect page, I can not see any button for choosing destination. 

Is there any way to connect the device again with qr code? (I cannot find qr code to reconnect)

**Comment by Wolfybox** [comment]
> Do you have prime? If you tap on the screen while onroad, it will bring up the map. Use connect on your phone to choose a destination.

is a prime necessary if I only want to test navigate on openpilot?
