### ISSUE TITLE
Ubuntu setup cannot complete

### ISSUE THREAD

**Issue by ARidzuan** [commaai/openpilot#30225]
### Describe the bug

After multiple attempts of trying to execute ./ubuntu_setup.sh, the setup keeps getting stuck at the following: 

Requirement already satisfied: cryptography>=2.0 in /home/ladm/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from SecretStorage>=3.2->keyring>=21.2.0->poetry==1.2.2) (38.0.3)

Requirement already satisfied: more-itertools in /home/ladm/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from jaraco.classes->keyring>=21.2.0->poetry==1.2.2) (9.0.0)

Requirement already satisfied: cffi>=1.12 in /home/ladm/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->poetry==1.2.2) (1.15.1)

Requirement already satisfied: pycparser in /home/ladm/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring>=21.2.0->poetry==1.2.2) (2.21)

### OS Version

Ubuntu 20.04

### openpilot version or commit

0.9.4 d0ea8be95fd5900930070b55c8582bafd329639e

### Additional info

Using a commit that uses Python 3.8 since i am doing co-simulation, and the bridge script uses libraries that support uo to Python 3.10

**Comment by adeebshihadeh** [comment]
We don’t support anything besides the latest master.
