### ISSUE TITLE
Comma connect always offline

### ISSUE THREAD

**Issue by Mathewmoslow** [commaai/openpilot#30285]
### Describe the bug

My comma connect seems to always be offline even though I am subscribed for prime. There’s a secondary issue where I get a gps error and the skies are clear. The gps error resolves once I restart however comma connect does not 

### Provide a route where the issue occurs

579a37eaf974700c|2023-10-18--11-54-12--0

### openpilot version

0.8.6/lta /1935c9d/ sep 30

**Comment by adeebshihadeh** [comment]
Unfortunately, this is likely a hardware issue. Can you open a ticket at comma.ai/support and include routes with rlogs uploaded for both the GPS and LTE issues?
