### ISSUE TITLE
HKG: Car Port for Kia Sorento Hybrid 2021

### ISSUE THREAD

**Issue by colin-cho** [commaai/openpilot#30291]
### Describe the bug

Update values.py #30247

{'carParams': {'alternativeExperience': 33,
               'autoResumeSng': True,
               'carFingerprint': 'KIA SORENTO HYBRID 4TH GEN',
               'carFw': [{'address': 2000,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'\xf1\x00MQhe SCC FHCUP      1.00 1.04 99110-P4000         ',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2008,
                          'subAddress': 0},
                         {'address': 1971,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'hvac',
                          'fwVersion': b"\xf1\x00MQ4   97255-P4000CONTROL ASS'Y-DATC  1.02MQ4HEVDATC(-)1.0     ",
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1979,
                          'subAddress': 0},
                         {'address': 1975,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'cornerRadar',
                          'fwVersion': b'\xf1\x00MQ4 BCW RR 1.01 , 1.03 (rVg \x00\x97\x02`',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1983,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'\xf1\x00MQ4HMFC  AT KOR LHD 1.00 1.04 99210-P2000 200330',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1996,
                          'subAddress': 0},
                         {'address': 1969,
                          'brand': 'hyundai',
                          'bus': 0,
                          'ecu': 'parkingAdas',
                          'fwVersion': b'\xf1\x10MQ4H ADAS_PRK ADL 1.00 1.03 99910-P4200',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x10'],
                          'responseAddress': 1977,
                          'subAddress': 0}],

### Which car does this affect?

Kia Sorento Hybrid 2021

### Provide a route where the issue occurs

69944114dc509ea3|2023-10-18--17-00-07

### openpilot version

0.9.5.1

### Additional info

* harness type:
    * [Hyundai A](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)
*  architecture: CAN-FD
Link to all physical parts during installation
* [comma 3X](https://comma.ai/shop/comma-3x)
* [car harness kit](https://comma.ai/shop/car-harness)

**Comment by sshane** [comment]
https://github.com/commaai/openpilot/pull/30247
