### ISSUE TITLE
TraxCrossover can use openPilot

### ISSUE THREAD

**Issue by aabc88** [commaai/openpilot#30304]
![새_비디오_만들기-min (1) (1)](https://github.com/commaai/openpilot/assets/57650484/b7c33aec-e45d-400a-9031-227f301cac5c)
long contorl is also supported

**Comment by sshane** [comment]
Not an issue, if you would like to open a car port to support this car, feel free to do so! Is it a normal ASCM car?

**Comment by Verylukyguy** [comment]
The Chevy Trax is built in the same plant as the Chevy Trailblazer, so they might be similar. 
 I also found documentation that they are both on the VSS-F platform.  https://github.com/commaai/openpilot/pull/27830
