### ISSUE TITLE
Hyundai Tucson L 2023(CHINA)  CAN ERROR

### ISSUE THREAD

**Issue by 1okko** [commaai/openpilot#30338]
### Describe the bug

DEVICE :COMMA 3X
CAR:Hyundai Tucson L 2023(CHINA)  HAS SCC&LKA
When the vehicle starts, openpilot starts, C3X displays can error, and the dashboard displays various fault codes。

8ffe737851ca1b11|2023-10-25--19-59-10--0

### Which car does this affect?

Hyundai Tucson L 2023(CHINA，1.5T 8AT )

### Provide a route where the issue occurs

8ffe737851ca1b11|2023-10-25--19-59-10--0

### openpilot version

sunnypilot

### Additional info

I have tried the official version, but the problem and fault still persist

**Comment by adeebshihadeh** [comment]
We need a stock route to look into this; open a new issue once you have one.
