### ISSUE TITLE
2024 Hyundai Tusan hybrid

### ISSUE THREAD

**Issue by sohaib0004** [commaai/openpilot#30348]
### Describe the bug

Car not recognised

### Which car does this affect?

Hyundai tucsan 2024 hybrid

### Provide a route where the issue occurs

37d135f23ab1b623|2023-10-29--12-09-02

### openpilot version

0.9.5

**Comment by sshane** [comment]
This is one of the platforms with data codes we don't yet understand + duplicate platform codes with hybrid variants. Will add FP manually, but we should move to:

- automatically add fingerprints like this next day
- make fuzzy FP work

**Comment by sohaib0004** [comment]
So comma Ai will add FP next day?
