### ISSUE TITLE
Hyundai Tucson L 2023（china） can error

### ISSUE THREAD

**Issue by 1okko** [commaai/openpilot#30355]
### Describe the bug

After startup, openpilot prompts CAN ERROR and the car dashboard displays LKAS fault

### Which car does this affect?

Hyundai Tucson L 2023(CHINA，1.5T 8AT )

### Provide a route where the issue occurs

8ffe737851ca1b11|2023-11-01--01-26-25--0

### openpilot version

0.9.4

**Comment by 1okko** [comment]
![微信图片_20231101094454](https://github.com/commaai/openpilot/assets/136616964/43dfdbf5-52d6-4aec-803d-acea08b25912)
![微信图片_20231101094445](https://github.com/commaai/openpilot/assets/136616964/30e6e6bc-8f2e-4958-80ac-f6e7b03276d6)

**Comment by sshane** [comment]
Looks like you have the wrong harness, the messages exist on bus 2 (camera side):

![image](https://github.com/commaai/openpilot/assets/25857203/5cc02b6e-486c-41e5-84d8-0b4323716703)

Which harness did you buy?

**Comment by sshane** [comment]
openpilot reports everything is fine with that route if we flip the buses in the logs, so I recommend trying to flip the CAN bus on the harness. There should be users in Discord to help with that, or you can view the wiring diagram for your harness in the above link.

**Comment by 1okko** [comment]
When I haven't connected to C3X yet, everything is normal, indicating that the wiring harness should be fine，The model I am using is Hyundai N

**Comment by 1okko** [comment]
> openpilot reports everything is fine with that route if we flip the buses in the logs, so I recommend trying to flip the CAN bus on the harness. There should be users in Discord to help with that, or you can view the wiring diagram for your harness in the above link. You just take certain wires out and flip them.

HOW to flip?

**Comment by 1okko** [comment]
> openpilot reports everything is fine with that route if we flip the buses in the logs, so I recommend trying to flip the CAN bus on the harness. There should be users in Discord to help with that, or you can view the wiring diagram for your harness in the above link. You just take certain wires out and flip them.
fliped CAN2 AND CAN0 ,Problem solved，thank you

**Comment by sunnyhaibin** [comment]
> > openpilot reports everything is fine with that route if we flip the buses in the logs, so I recommend trying to flip the CAN bus on the harness. There should be users in Discord to help with that, or you can view the wiring diagram for your harness in the above link. You just take certain wires out and flip them.
> 
> HOW to flip?

Instructions can be found under Description -> harness type of this PR:
- https://github.com/commaai/openpilot/pull/27392

**Comment by sshane** [comment]
Great! Unfortunately we don't have any harness that is the opposite of this, @vanillagorillaa prefers not to add another variant just yet until we see more cars that require this harness. Feel free to check back in the future
