### ISSUE TITLE
Add Toggle to auto-enable hotspot tethering on car start/comma device wake

### ISSUE THREAD

**Issue by OngOlsen** [commaai/openpilot#30381]
Tethering is buried in the settings and need to be manually turned on every time. Suggesting to add a Toggle in settings to enable automatically turning on tethering on wake from starting the car. (or something similar like enable on drive, or on/off switch on main menu etc, but enable on wake from car start seem to make the most sense)

**Comment by adeebshihadeh** [comment]
We generally don't take feature requests like this in our issue tracker.
