### ISSUE TITLE
Drives Not Uploading 

### ISSUE THREAD

**Issue by adams1999-ai** [commaai/openpilot#30399]
### Describe the bug

Drives aren't uploading. Device is on WiFi 24/7. Just received my device back from you guys 7 days ago for a warranty replacement for the exact same issue. 
14:18 
Dongle id :  6275f1edbe80f045

### Provide a route where the issue occurs

6275f1edbe80f045|2023-11-06--13-37-04--0

### openpilot version

0.9.4

### Additional info

other drives did not upload despite being connected for hours

**Comment by adeebshihadeh** [comment]
Looks like the device is still having NVMe issues after the repair. Please open a new ticket and reference this GitHub issue, and I'll make sure to take care of it.
