### ISSUE TITLE
Stop trying to accelerate when traction is lost. 

### ISSUE THREAD

**Issue by jakethesnake420** [commaai/openpilot#30436]
When driving on slippery roads and traction is lost, openpilot continues to apply the throttle. Openpilot should detect traction is lost either by monitoring the wheel acceleration or through the cars internal traction control system and back off the throttle. 

It would be best if openpilot could recognize or remember the traction level and just request a lower accel to begin with.

This could be fun project to work on. I can upload drives where I accelerate too quickly and the wheels slip if there is interest in this enhancment.

**Comment by ErichMoraga** [comment]
https://discord.com/channels/469524606043160576/524328425415245827/702194645953806386

George said, "we disengage on traction control" ~2.5 years ago.  Has that changed?

**Comment by haraschax** [comment]
Issues need logs, please follow the issue format. We support hundreds of cars.

**Comment by jakethesnake420** [comment]
Sure it's easy to disengage but the point of the issue is to prevent the traction control from engaging in the first place. Human drivers accelerate slower when it's slippery.
