### ISSUE TITLE
GM message forwarding shows messages on incorrect bus

### ISSUE THREAD

**Issue by garrettpall** [commaai/openpilot#30445]
### Describe the bug

Messages being forwarded for GM cars show bus 2 messages being forwarded to 130 and 0 to 128. The vehicle behaves correctly, so I think the is a logging issue. Route below is from 2023 XT4, but is also seen for 2023 Bolt EV.

<img width="779" alt="Screen Shot 2023-11-11 at 8 53 11 AM" src="https://github.com/commaai/openpilot/assets/76917194/f1a2cbc1-6eae-4b28-9ca9-d35c370400df">

### Provide a route where the issue occurs

162796f1469f2f1b|2023-11-05--11-17-31

### openpilot version

Master

### Additional info

Also happened on 2023 Bolt EV: 599ef8fe5b42e9fc|2023-11-09--23-32-44

**Comment by sshane** [comment]
This is correct per the current logic, which records the source bus + 128. You can see here that it saves the source bus to the CANPacket, but is sent on the fwd bus:

https://github.com/commaai/panda/blob/5fe1d67b7729c843df7dd15df5d375d08ed410c6/board/drivers/bxcan.h#L201-L217
