### ISSUE TITLE
Low speed steering issue is back with 22' VW Arteon (US model). 

### ISSUE THREAD

**Issue by dukeajuke** [commaai/openpilot#30495]
### Describe the bug

I've been using Openpilot for about a year now, and originally run into a problem when I first started using it. I submitted a bug report, and user/dev jyoung8607 fix it in a custom branch for me. That branch was eventually merged into the following release. After the last release, the issue has come back. When the system tries to steer at very low speeds I get "Steering temporarily unavailable" shows up and steering is disabled until I restart the car. See on both these drives:

c34ef43981b6d888|2023-11-19--12-31-55--0
c34ef43981b6d888|2023-11-19--11-52-54--0

### Which car does this affect?

VW Arteon 2022 (US model)

### Provide a route where the issue occurs

c34ef43981b6d888|2023-11-19--12-31-55--0

### openpilot version

openpilot 0.9.4

### Additional info

See bug description

**Comment by sshane** [comment]
Do you have a link to the fix?

**Comment by dukeajuke** [comment]
Sorry I looked but can't find it. I stopped using that branch when the fix was merged into the master.
________________________________

**Comment by jyoung8607** [comment]
He's referring to #26694. It's specific to a new generation of EPS. I think it may be an angle-rate limit, still investigating.

**Comment by liltimtim** [comment]
Also having the same issue. 2018 VW Atlas SEL 

https://connect.comma.ai/9eab6bb0c76baa3d/1704842420631/1704843640843

Was at stop light and accelerated and turned under OP and my control. I felt a slight bump then steering became unavailable.

**Comment by Gyrohammer** [comment]
I'm experiencing similar symptoms: 2024 Jetta SE

[33f21a08ace10dde|2024-01-18--17-24-49--1](https://connect.comma.ai/33f21a08ace10dde/1705616689305/1705617351378)

In highway traffic car came to a stop, went along for a bit, then lost steering control/communication. Occurs at the end of the drive.

**Comment by jyoung8607** [comment]
Current thinking is the [effective default minSteerSpeed](https://github.com/commaai/openpilot/blob/eada51ec8ed570a4efe70909760460c976cd4f04/selfdrive/controls/lib/latcontrol.py#L6) is right on the edge of what the rack accepts. @Gyrohammer has been testing with a `minSteerSpeed` of 1.0 m/s for a few days with positive results. He's now testing with 0.5 m/s.

**Comment by Gyrohammer** [comment]
> He's now testing with 0.5 m/s.

I've been testing at this limit for the past six days with promising results. I have not had this fault occur at-all; everything has been running as expected!

**Comment by jyoung8607** [comment]
> I've been testing at this limit for the past six days with promising results. I have not had this fault occur at-all; everything has been running as expected!

Can we have you give it one more try at 0.4 m/s? If possible, I want to still show VW with a zero min steer speed in the official docs, but 0.5 m/s is just a shade over 1 mph. Thank you so much for your help testing so far!

**Comment by Gyrohammer** [comment]
> Can we have you give it one more try at 0.4 m/s? 

Will do! I'll update this post in about a weeks time.

**Comment by Gyrohammer** [comment]
> > Can we have you give it one more try at 0.4 m/s?
> 
> Will do! I'll update this post in about a weeks time.

Well its been about a week, I've had little to no issue with this modification. I was using it for about 10min in heavy stop and go traffic with zero issue as well, no issues.

**Comment by jyoung8607** [comment]
@dukeajuke There's a candidate fix in #31450. At your convenience, try installing it and see what you get!

@Gyrohammer If you've been seeing low speed takeover alerts during your tests, this fix should make stopping silent again.

To test, uninstall openpilot and reinstall from custom URL https://installer.comma.ai/jyoung8607/vw-min-speed

**Comment by dukeajuke** [comment]
Thanks! I'll try it tonight.
________________________________
