### ISSUE TITLE
Add ability to use voice with navigation

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#30502]
Would be a nice to have where you can activate voice with a phrase like 

`Hey Comma, take me home` which will route you to the preset home address

**Comment by Verylukyguy** [comment]
Something like this?
https://github.com/commaai/openpilot/wiki/iOS-OpenPilot-Navigation-Shortcuts

**Comment by adeebshihadeh** [comment]
Closing as this is not an issue. Features requests can be discussed in Discord.
