### ISSUE TITLE
Ford maverick 2022 master CI is broken

### ISSUE THREAD

**Issue by ayeganov** [commaai/openpilot#30527]
### Describe the bug

With the update from the last few days I am getting a report of radar malfunction. Once I disconnect OP the error goes away. In the current state no automaton of any kind is working, even plain cruise control. 

### Which car does this affect?

Ford maverick 2022 

### Provide a route where the issue occurs

Gjhgjh

### openpilot version

0.9.6

**Comment by ayeganov** [comment]
@adeebshihadeh My dongle id is [c251cea6f2c6d154](https://useradmin.comma.ai/?onebox=c251cea6f2c6d154)

**Comment by adeebshihadeh** [comment]
> @adeebshihadeh My dongle id is [c251cea6f2c6d154](https://useradmin.comma.ai/?onebox=c251cea6f2c6d154)

Can you upload the full logs from a route with the issue? I only need the first segment.

**Comment by adeebshihadeh** [comment]
Fixed on master, and should be on master-ci soon too.
