### ISSUE TITLE
Going into on-road mode when update screen is on display, permanently dismisses it until next reboot.

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#30521]
### Describe the bug

If there is an update available, and you go into drive mode with the update prompt on screen, the prompt won't return until the next reboot, and a manual update indicates that there is no update available.

The expected result would be that the update screen would return when back in off-road mode or that an update would show as being available when checking manually without needing to reboot.

### Provide a route where the issue occurs

dd154b34dc4d8c52|2023-11-25--00-38-50

### openpilot version

25924c5 and before.

### Additional info

The bug has been around for a while and I suspect it's more prevalent on my type of car as on-road mode happens at ignition on, being a manual. My understanding is other cars, on-road mode engages after shifting out of Park. Sorry for not reporting sooner.

Here's a video of it occuring: https://youtube.com/shorts/TrJhgIaBNXw

**Comment by adeebshihadeh** [comment]
This will be irrelevant after the updater rewrite in #31494
