### ISSUE TITLE
2020 Ford Escape

### ISSUE THREAD

**Issue by Bolender1983** [commaai/openpilot#30530]
### Describe the bug

Dashcam mode car unrecognized error

### Provide a route where the issue occurs

561745cc72a08831

### openpilot version

0.9.6

**Comment by Bolender1983** [comment]
0.9.5 is the version

**Comment by sshane** [comment]
Can you try this branch? https://github.com/commaai/openpilot/tree/escape-2020-fw

Installer URL:

https://installer.comma.ai/commaai//escape-2020-fw

**Comment by Bolender1983** [comment]
When I put this url in the comma started working but now it will not let
collusion asst stay on and diables my front view camera.

Thank you for your help.

**Comment by sshane** [comment]
The AEB disabled icon is shown in your cluster if you turn on openpilot longitudinal at this time. Can you try without that and see if everything works? Also, openpilot should still work in that state.

**Comment by sshane** [comment]
Oh I see the blocked msgs, hmm everything is getting blocked despite it passing offline tests on your route. Have you made any changes to panda safety? Try to re-flash it with `./panda/board/flash.py`

**Comment by Bolender1983** [comment]
I have not try to refresh the panda, I am not for sure how to do that

**Comment by sshane** [comment]
Try to factory reset and re-install that branch, then try without openpilot longitudinal (alpha).

**Comment by Bolender1983** [comment]
Ok, so I've reinstalled it, but this time it is now showing pilot
unavailable. Adapted cruise control disabled and it will not let my cruise
control to set

**Comment by sshane** [comment]
Okay great, no blocked messages now. I think you enabled normal "dumb" cruise control by accident. Try to reverse the actions of this video. Can you take a photo of that cruise control setting? https://www.youtube.com/watch?v=6c0SDhA1GP0

**Comment by sshane** [comment]
@Bolender1983 does your vehicle come with adaptive cruise control?

**Comment by drfrink** [comment]
I'm running into the same issue with 2022 ford escape, comma is in dashcam mode

**Comment by sshane** [comment]
Closing since you returned your device @Bolender1983.

**Comment by sshane** [comment]
@drfrink please make a new issue if you haven't already.
