### ISSUE TITLE
Ford Firmware Missing for Ecu.shiftByWire

### ISSUE THREAD

**Issue by gremlin961** [commaai/openpilot#30541]
### Describe the bug

After hard coding the fingerprint (export FINGERPRINT="FORD F-150 14TH GEN") in openpilot-launch.sh and commenting out the dashcam section (#ret.dashcamOnly = candidate in {CAR.F_150_MK14}) in interface.py, I started receiving errors for the camera, pre-collision assist and cruise control. Following the fingerprinting instructions at https://github.com/commaai/openpilot/wiki/Fingerprinting only returned a single ecu firmware for shiftByWire. 

I was able to resolve the issue by manually appending the shiftByWire firmware info to the CAR.F_150_MK14 section of values.py file. 

Hardware - C3x
Make - Ford
Model - 2023 F-150
OP Version and Branch - Stock OP v0.9.5, master-ci

### Which car does this affect?

Ford F-150 2023

### Provide a route where the issue occurs

906b419188978855|2023-11-27--19-08-57

### openpilot version

0.9.5

### Additional info

Here is the full CAR.F_150_MK14 section of selfdrive/car/ford/values.py that resolved the issue.

  CAR.F_150_MK14: {
    (Ecu.eps, 0x730, None): [
      b'ML3V-14D003-BC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.abs, 0x760, None): [
      b'PL34-2D053-CA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.fwdRadar, 0x764, None): [
      b'ML3T-14D049-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.fwdCamera, 0x706, None): [
      b'PJ6T-14H102-ABJ\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.engine, 0x7E0, None): [
      b'PL3A-14C204-BRB\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.shiftByWire, 0x732, None): [
      b'ML3P-7P470-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
  },

**Comment by sshane** [comment]
I doubt that adding a FW version would fix an issue like this, if the end result is fingerprinting as the same vehicle. Can you provide two routes, one with faults and one without? Closing since this car isn't yet supported, and https://github.com/commaai/openpilot/issues/29085 is mostly the issue here.
