### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by phuie1** [commaai/openpilot#30657]
### Describe the bug

Device won't turn on, stuck on loading screen. 
![20231208_192610](https://github.com/commaai/openpilot/assets/48443645/360cfc8d-7051-4198-9b44-3906bb10f49c)

### Provide a route where the issue occurs

N/A

### openpilot version

Current release

**Comment by sshane** [comment]
What is your dongle id/email you registered with the device?

**Comment by Elmariachi156** [comment]
im log in

**Comment by phuie1** [comment]
I got it working after a factory reset.

**Comment by Elmariachi156** [comment]
I tried this but nothing Sent from iPhone On Dec 9, 2023, at 8:01 AM, phuie1 ***@***.***> wrote:﻿
I got it working after a factory reset.

**Comment by Elmariachi156** [comment]
I can’t get the comma to boot up
