### ISSUE TITLE
[$500 bounty] Drive a loop in MetaDrive

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#30694]
Extend the MetaDrive test to drive a defined course and ensure it stays in the line. Requirements:
* at least 1 minute of driving
* passes reliably: 20+ times in a row
* test fails if a reasonable user would have disengaged during the loop (drives out of lane, etc.)

Ideally, we can also configure the distance and/or runtime of the test with a simple parameter so that we can run a quick one in CI, and perhaps a longer version on master.

https://github.com/commaai/openpilot/blob/master/tools/sim/tests/test_sim_bridge.py

**Comment by jnewb1** [comment]
would also be cool if the route is logged as a github actions artifact that can be viewed in the openpilot tools if it fails

**Comment by adeebshihadeh** [comment]
Good idea, added to the list
