### ISSUE TITLE
Hyundai Staria 4Gen 2022

### ISSUE THREAD

**Issue by itkairos2023** [commaai/openpilot#30760]
This is my Staria 4Gen 2022 vehicle information. 
I would like to ask you to update this information as well. 
Thank you for always.

comma3x
0.9.5

https://useradmin.comma.ai/logs?url=https://commadata2.blob.core.windows.net/qlog/3fd99d7c0a0d9c5f/2023-12-15--17-36-00/0/qlog.bz2?se%3D2023-12-16T08%253A18%253A50Z%26sp%3Dr%26sv%3D2018-03-28%26sr%3Db%26rscd%3Dattachment%253B%2520filename%253D3fd99d7c0a0d9c5f_2023-12-15--17-36-00--0--qlog.bz2%26sig%3De7/4hHQQyo7Bz42CJ/2N38yDWewoyWU//DhEjGxegX4%253D

Device(dongle id) : 3fd99d7c0a0d9c5f

comma@comma-1109afe7:/data/openpilot$ ./selfdrive/debug/dump.py carParams
( logMonoTime = 345935056757,
  valid = true,
  carParams = (
    carName = "hyundai",
    carFingerprint = "HYUNDAI STARIA 4TH GEN",
    enableGasInterceptor = false,
    pcmCruise = true,
    enableCameraDEPRECATED = false,
    enableDsu = false,
    enableApgsDEPRECATED = false,
    minEnableSpeed = -1,
    minSteerSpeed = 16.67,
    safetyModelDEPRECATED = silent,
    safetyParamDEPRECATED = 0,
    mass = 2341,
    wheelbase = 3.273,
    centerToFront = 1.3092,
    steerRatio = 11.94,
    steerRatioRear = 0,
    rotationalInertia = 5882.4541,
    tireStiffnessFront = 307676.56,
    tireStiffnessRear = 324249.31,
    longitudinalTuning = (
      kpBP = [0],
      kpV = [0.1],
      kiBP = [0],
      kiV = [0],
      deadzoneBP = [0],
      deadzoneV = [0],
      kf = 1 ),
    lateralTuning = (
      torque = (
        useSteeringAngle = true,
        kp = 1,
        ki = 0.1,
        friction = 0.15,
        kf = 1,
        steeringAngleDeadzoneDeg = 0,
        latAccelFactor = 1.8,
        latAccelOffset = 0 ) ),
    steerLimitAlert = false,
    vEgoStopping = 0.7,
    directAccelControlDEPRECATED = false,
    stoppingControl = true,
    startAccel = 1,
    steerRateCostDEPRECATED = 0,
    steerControlType = torque,
    radarUnavailable = true,
    steerActuatorDelay = 0.36,
    openpilotLongitudinalControl = false,
    carVin = "00000000000000000",
    isPandaBlackDEPRECATED = false,
    dashcamOnly = false,
    safetyModelPassiveDEPRECATED = silent,
    transmissionType = unknown,
    carFw = [
      ( ecu = fwdRadar,
        fwVersion = "\361\000US4_ RDR -----      1.00 1.00 99110-CG000         ",
        address = 2000,
        subAddress = 0,
        responseAddress = 2008,
        request = ["\"\361\000"],
        brand = "hyundai",
        bus = 0,
        logging = false,
        obdMultiplexing = true ),
      ( ecu = cornerRadar,
        fwVersion = "\361\000US4 BCW RR 1.00 , 1.00 (uC\202\"\001E\000c",
        address = 1975,
        subAddress = 0,
        responseAddress = 1983,
        request = ["\"\361\000"],
        brand = "hyundai",
        bus = 0,
        logging = true,
        obdMultiplexing = true ),
      ( ecu = fwdCamera,
        fwVersion = "\361\000US4 MFC  AT KOR LHD 1.00 1.04 99211-CG000 210819",
        address = 1988,
        subAddress = 0,
        responseAddress = 1996,
        request = ["\"\361\000"],
        brand = "hyundai",
        bus = 0,
        logging = false,
        obdMultiplexing = true ),
      ( ecu = parkingAdas,
        fwVersion = "\361\020\000\000\377\377\000\000\000\006|#\225?\353\371\n?x}\300>[@!\301w1\304B\203j\315AI\323[@\000\000\377\377\000\000\000\006\344+\201?:\003|\277\305\256\257\276\340K2B\020\361\306B\004i\313A+\322[@\000\000\377\377\000\000\000\006N\263\022?:\273\264?xt\324?\316=-B%\321\307B\266n\365A\240\\d@\000\000\377\377\000\000\000\006\343\372\v?\"P\277?\002D\256\277\323\217\317A1\313\307B\374\205\312AL\277J@8\230\324K\232\026\026J\2361\202H9*\202G\266n\365A\240\\d@\262\271\267B",
        address = 1969,
        subAddress = 0,
        responseAddress = 1977,
        request = ["\"\361\020"],
        brand = "hyundai",
        bus = 0,
        logging = true,
        obdMultiplexing = true ) ],
    radarTimeStep = 0.02,
    communityFeatureDEPRECATED = false,
    steerLimitTimer = 1,
    fingerprintSource = can,
    networkLocation = fwdCamera,
    minSpeedCanDEPRECATED = 0,
    stoppingDecelRate = 0.8,
    startingAccelRateDEPRECATED = 0,
    maxSteeringAngleDegDEPRECATED = 0,
    fuzzyFingerprint = false,
    enableBsm = true,
    hasStockCameraDEPRECATED = false,
    longitudinalActuatorDelayUpperBound = 0.5,
    vEgoStarting = 0.1,
    stopAccel = -2,
    longitudinalActuatorDelayLowerBound = 0.5,
    safetyConfigs = [
      ( safetyModel = hyundaiCanfd,
        safetyParamDEPRECATED = 0,
        safetyParam2DEPRECATED = 0,
        safetyParam = 40 ) ],
    wheelSpeedFactor = 1,
    flags = 14,
    alternativeExperience = 1,
    notCar = false,
    maxLateralAccel = 2,
    autoResumeSng = true,
    startingState = true,
    experimentalLongitudinalAvailable = false,
    tireStiffnessFactor = 1,
    passive = false,
    experimentalLong = false,
    experimentalLongAlt = false,
    smoothSteer = (
      method = 0,
      maxSteeringAngle = 90,
      maxDriverAngleWait = 0.002,
      maxSteerAngleWait = 0.001,
      driverAngleWait = 0.001 ),
    mdpsBus = 0,
    sasBus = 0,
    sccBus = 0,
    fcaBus = 0,
    bsmAvailable = false,
    lfaAvailable = false,
    lvrAvailable = false,
    evgearAvailable = false,
    emsAvailable = false,
    standStill = false,
    vCruisekph = 0,
    resSpeed = 0,
    vFuture = 0,
    aqValue = 0,
    aqValueRaw = 0,
    vFutureA = 0,
    autoHoldAvailable = false,
    scc13Available = false,
    scc14Available = false,
    lfaHdaAvailable = false,
    navAvailable = false ) )

**Comment by adeebshihadeh** [comment]
Our issue tracker is not for help getting started; check out the community Discord instead: https://discord.comma.ai.
