### ISSUE TITLE
"LTE" "CONNECT OFFLINE"

### ISSUE THREAD

**Issue by haram-KONA** [commaai/openpilot#30784]
### Describe the bug

I am using "Prime Lite" and live in Korea. 
Since some time ago, the "LTE" connection status on the home screen appears to be normal, but the "CONNECT" status is maintained as "OFFLINE", and logs are not uploaded while driving. 
I don't know why. Before that, it was always connected and worked well.

### Provide a route where the issue occurs

1618132d68afc876

### openpilot version

0.9.6 master-ci

**Comment by haram-KONA** [comment]
![Uploading 20231218_113636.jpg…]()

**Comment by haram-KONA** [comment]
![20231218_113636](https://github.com/commaai/openpilot/assets/88036668/a6cf0ce6-696a-4175-a6a5-ccf82028dc9c)

**Comment by adeebshihadeh** [comment]
We do not provide support for getting your own SIM working with prime lite.
