### ISSUE TITLE
Hyundai Ioniq 5: Intermittent "Can Bus Disconnected"

### ISSUE THREAD

**Issue by JJeonbear** [commaai/openpilot#30815]
### Describe the bug

I drive a 2023 Ioniq 5, and since my fingerprint is not registered, I am using a fork to operate it.

Sometimes when I driving my car I get intermittent "controls are lagging" and "Can Bus Disconnected" error messages sometimes leading to a disengagement.
I have reloaded openpilot and still happens. I dont know how to reproduce the problem, but it has happened on everyday separate occasions.
There is no damage to the device always hangs on the window. Never took it apart either.

### Provide a route where the issue occurs

aad0fc7230a3066e|2023-12-15--15-56-50

### openpilot version

0.9.5

**Comment by adeebshihadeh** [comment]
Can you connect your device to Wi-Fi to upload the full logs?

**Comment by JJeonbear** [comment]
> Can you connect your device to Wi-Fi to upload the full logs?

aad0fc7230a3066e|2023-12-20--23-36-47

I drove again today to record the log.

I have uploaded the complete driving full log

**Comment by JJeonbear** [comment]
> Can you connect your device to Wi-Fi to upload the full logs?

Did you check the log after uploading? The use of Comma 3x is not possible due to CAN bus disconnection.

**Comment by adeebshihadeh** [comment]
I just added it to the milestone for the next openpilot release. I will look into it and hopefully fix for the next releaes.

**Comment by JJeonbear** [comment]
> I just added it to the milestone for the next openpilot release. I will look into it and hopefully fix for the next release.

Thank you

**Comment by royjr** [comment]
May be similar to https://discord.com/channels/469524606043160576/1152498009427419197/1204899591149981697

**Comment by adeebshihadeh** [comment]
Tracking in #32286
