### ISSUE TITLE
Ford Escape 2022 dashcam mode

### ISSUE THREAD

**Issue by drfrink** [commaai/openpilot#30865]
### Describe the bug

Running into issues with both main install and this branch, https://github.com/commaai/openpilot/tree/escape-2020-fw both say openpilot is unsupported and goes into dashcam mode 

### Which car does this affect?

Ford Escape 2022

### Provide a route where the issue occurs

a25d5d0b645d8bc3

### openpilot version

0.9.6

### Additional info

Tried default installer url as well as ford escape 2020 fw branch

**Comment by sshane** [comment]
@jnewb1 you can start to run the bot on issues like these

## ✅ Updating FW version database with FW from 1 dongles (1 platforms) in last 90.0 days:
<details open><summary>View table</summary><br>

| Dongle, platform, VIN                                                                                                          | Name from VIN 🆚 CarInfo                   | Segments                | Bad seg tags   | Good seg tags                                         |
|:-------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------|:------------------------|:---------------|:------------------------------------------------------|
| [a25d5d0b645d8bc3](https://useradmin.comma.ai/?onebox=a25d5d0b645d8bc3)<br><sub>FORD ESCAPE 4TH GEN<br>1FMCU9J96........</sub> | FORD Escape 2022 🆚<br>Ford Escape 2020-22 | 12 routes, 153 segments |                | - all lat active: 67<br>- no input all lat active: 53 |

Dongles to re-run category: `a25d5d0b645d8bc3`
</details>
