### ISSUE TITLE
Mazda 2024 CX5 Dashcam Mode , Car Unrecognized

### ISSUE THREAD

**Issue by hongsrich** [commaai/openpilot#30872]
### Describe the bug

After installing the release branch with all the wiring connected on my 2024 Mazda CX-5 Select, I am getting the issue Dashcam Mode Car Unrecognized.  I have tried uninstalling and trying again with the Master-CI branch but am still running into the same issue.  

### Provide a route where the issue occurs

https://connect.comma.ai/ad9d38124d3a3ef5/1703955559407/1703956202678

### openpilot version

0.9.5

### Additional info

Dongle ID:  ad9d38124d3a3ef5
Serial: f0014f8d

**Comment by hongsrich** [comment]
Have also tried fingerprinting with the following code here, but running into the same issue

https://github.com/hongsrich/openpilot/edit/master/selfdrive/car/mazda/values.py#L11C0-L12C0

**Comment by hongsrich** [comment]
Works now using the following branch:

https://github.com/TheOfficialJosh/openpilot/tree/24-mazda-cx5

**Comment by wenqian-ye** [comment]
I am facing the same problem. Is it merged in the latest openpilot 0.9.6?

**Comment by sshane** [comment]
@wenqian-ye what is your dongle id?

**Comment by wenqian-ye** [comment]
> @wenqian-ye what is your dongle id?

It is 833d1eb9ecc9b842

**Comment by wenqian-ye** [comment]
@sshane Hi Shane, are there any updates? Is the system supported on the Mazda CX-5 2024 model?
