### ISSUE TITLE
UI Feature Request - Trip Meter

### ISSUE THREAD

**Issue by mitchspano** [commaai/openpilot#30878]
As a driver who regularly makes 1000+ mile road trips using OpenPilot, I often find myself curious about how much of the trip OpenPilot was assisting me. It would be great if the system included a "trip-meter" which tells users the breakdown of miles driven using assistance vs manual driving.

The trip-meter would work similar to an odometer trip-meter; the user could create a new trip at any time and have two active trips (a and b) at one time. The trip-meter would be slightly more advanced though, as it would show both the overall miles driven as well as the percentage of distance driven with assistance for each of the two trips.

| Trip | Total Miles| Miles with Assistance | Assistance % | Action |
| --- | --- | --- | --- |  --- |
| A | 500 |  405 | 81% | (reset) |
| B | 1200 |  864 | 72% | (reset) |

**Comment by adeebshihadeh** [comment]
Closing this as it's not an issue. Feature requests can be discussed in the #feature-requests channel in the [community Discord](https://discord.comma.ai).
