### ISSUE TITLE
[$100 bounty] Script for doing UI translations with an LLM

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#30883]
Use an LLM (either OpenAI API or something local) to generate UI translations: https://github.com/commaai/openpilot/tree/master/selfdrive/ui/translations.

* local is preferred if possible (GPU required is fine), but we can use GPT4 if the translations are actually better
* there should be a flag for either doing all the translations or just filling in the unfinished ones

**Comment by hritikmunde** [comment]
Hi @adeebshihadeh , can you explain this a little bit more? What exactly do we need to implement?

**Comment by meirdev** [comment]
@adeebshihadeh I uploaded an example of automatic translation (currently using OpenAI) from an xml language file: https://gist.github.com/meirdev/fb63baa36dcaceebe7c74db07e9c339e

**Comment by sshane** [comment]
@meirdev would you like to open a PR?
