### ISSUE TITLE
M1 Mac - Unable to open rlog's on PlotJuggler

### ISSUE THREAD

**Issue by dbzx6r** [commaai/openpilot#30897]
### Describe the bug

Here are the exact start to finish I've followed:

1) `git clone --filter=blob:none --recurse-submodules --also-filter-submodules https://github.com/commaai/openpilot.git`

2) `cd openpilot`

3) `git lfs pull`

4) `tools/mac_setup.sh`

5) `poetry shell`

6) `scons -u -j$(nproc)`

7) `cd tools/plotjuggler && ./juggle.py --install`

8) `./juggle.py "a2a0ccea32023010|2023-07-27--13-01-19"`

Here are the errors I receive:

![Screenshot 2024-01-02 at 7 33 18 PM](https://github.com/commaai/openpilot/assets/81520155/0dab0248-d799-42ff-b81f-5ddc86c20332)

![Screenshot 2024-01-02 at 7 45 49 PM](https://github.com/commaai/openpilot/assets/81520155/9f27998a-84bc-40b0-beeb-87b2e858321b)

![Screenshot 2024-01-02 at 7 46 21 PM](https://github.com/commaai/openpilot/assets/81520155/57c008ce-3ccf-4f08-bbb6-6d0be3d6070d)

After opening PlotJuggler and manually trying to enter data using the button, I receive:

<img width="353" alt="Screenshot 2024-01-02 at 7 47 36 PM" src="https://github.com/commaai/openpilot/assets/81520155/acacbacf-ccb6-4fa9-aa5d-3b4d6732953f">

### OS Version

Mac OS Sonoma 14.2

### openpilot version or commit

3b1e901

### Additional info

I have previously used it before it was officially supported, and had deleted everything, did a fresh clone, and now I am getting this error. I'm not sure if the how-to file needs to be updated or a dependency is being missed during install, but I don't receive any errors during the install.

**Comment by adeebshihadeh** [comment]
We no longer natively support Mac. See tools/README.me for the full explanation.
