### ISSUE TITLE
Indicated to change lane, cancelled OP to cancel lane change, re-engaged OP and OP continued to attempt to lane change - potential safety issue

### ISSUE THREAD

**Issue by sunilm1992** [commaai/openpilot#30892]
### Describe the bug

Indicated to change lane, cancelled OP to cancel lane change, re-engaged OP and OP continued to attempt to lane change - potential safety issue

I believe that when you turn off OP it should not attempt to change lane again when you re-engage 

### Provide a route where the issue occurs

0662797832aac2eb|2023-12-31--15-12-22--33

### openpilot version

release

### Additional info

please see route, I have flagged

**Comment by adeebshihadeh** [comment]
This is expected behavior at the moment. RE: safety, please refer to docs/SAFETY.md
