### ISSUE TITLE
OP won't activate, “paramsd temporary error”

### ISSUE THREAD

**Issue by exik23** [commaai/openpilot#30914]
### Describe the bug

Tried to use toyota-disable-radar on 2024 Rav4 hybrid, per Shane's request. The installation is fine and calibration is done. But the can't set cruise control, “paramsd temporary error”. 

Shane's note,. "the param estimator says roll is invalid, can you open a new issue with that route?"

### Which car does this affect?

Toyota Rav4 2024

### Provide a route where the issue occurs

061932dac503c0f7|2024-01-04--19-39-11--4

### openpilot version

toyota-disable-radar

**Comment by sshane** [comment]
@exik23 does this still happen? any updates @nuwandavek?

**Comment by sshane** [comment]
@exik23 does this still occur?

**Comment by exik23** [comment]
Nope it’s fixed!Sent from my mobile device On Aug 20, 2024, at 5:33 PM, Shane Smiskol ***@***.***> wrote:﻿
@exik23 does this still occur?

**Comment by Sanad2014** [comment]
I have the same problem with rav4 2024 hybrid
