### ISSUE TITLE
2023 Kia Forte (Car Unrecognized) with C3x

### ISSUE THREAD

**Issue by ahr2435tech** [commaai/openpilot#30936]
### Describe the bug

I received a Comma 3x for Christmas so I'm new to the hardware and OP. I've tried multiple versions of stock OP and Sunnypilot including a version that is for a 2023 Forte. I've checked my cables and connections multiple times and everything is solid. I started the fingerprinting process following the guide but I'm stumped after step 3. I've attached the FW results I pulled following the guide info. 

['carFw' [{'address' 2001,.txt](https://github.com/commaai/openpilot/files/13857400/carFw.address.2001.txt)
Sorry but I'm a noob and realized I'm probaby missing something simple. I just want to enjoy my Christmas gift and really need some help.

### Which car does this affect?

2023 Kia Forte GT-Line

### Provide a route where the issue occurs

b057fc7b43ade5f2%7C2024-01-08--06-23-10

### openpilot version

currently on 0.96 but have tried many others

### Additional info

![unrecognized](https://github.com/commaai/openpilot/assets/140851930/99ca5eb6-a393-4d95-954e-20116e02e157)
![unrecognized2](https://github.com/commaai/openpilot/assets/140851930/19c6f53f-1fee-4939-9034-53243120ffa9)

**Comment by vesenwa** [comment]
same - different error message, can error - check connections. Posted request for firmware update, not work for forte 2023
