### ISSUE TITLE
navd: validate mapbox api responses

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#30957]
navd makes a lot of assumptions about the mapbox API response. this should be rewritten to be robust to bad API responses

**Comment by su-per-man** [comment]
can I get assigned to this?

**Comment by adeebshihadeh** [comment]
We don’t assign issues to external contributors, but feel free to pick this one up

**Comment by su-per-man** [comment]
No problem, thank you for your response. I'm working on it. Will do a pull request.

**Comment by adeebshihadeh** [comment]
Immediate issues addressed in #30977
