### ISSUE TITLE
Does Open pilot support 2018 Accord Hybrid?

### ISSUE THREAD

**Issue by youngjedi13** [commaai/openpilot#310]
On supported vechiles page the 2018 Honda Accord is listed for all trims.  I was wondering if that included the Hybrid model.  I've read that the Regen breaking can be a factor with this system.

**Comment by jfrux** [comment]
Check out this link i've put together.
Openpilot requires LKAS / ACC features to be present to work the easiest.

From this link: https://opc.ai/research/300#!tab-trim_styles
It appears that ACC/LKAS comes standard on all 2018 Honda Accord trims.

It also appears to be standard on all trims of the Hybrid as well:
https://opc.ai/research/519#!tab-trim_styles

A bonus feature of the 2018 Honda Accord is the fact that it steers down to 3mph for stop and go capabilities which is unique to this model.
