### ISSUE TITLE
Unrecognized Supported Vehicle

### ISSUE THREAD

**Issue by ALFnotELF** [commaai/openpilot#31050]
### Describe the bug

Says "Dashcam Mode - Car Unrecognized" when using the openpilot.comma.ai and the master-ci link.

### Which car does this affect?

2022 Ford Bronco Sport Badlands w/Assist +

### Provide a route where the issue occurs

d1aacbb70e8a9d4b|2024-01-18--19-16-13--0

### openpilot version

0.9.6 / master-ci / 524abb2 / Jan 18

### Additional info

Dongle id: d1aacbb70e8a9d4b

Restarted device with car off and got rid of panda not connected error

New Comma 3x purchased from Comma website

**Comment by sshane** [comment]
Yes your car should be supported, after https://github.com/commaai/openpilot/pull/31195 it will match.
