### ISSUE TITLE
Honda Civic 2019 suddenly unrecognized after a year

### ISSUE THREAD

**Issue by themilkrat** [commaai/openpilot#31085]
### Describe the bug

I have been using openpilot for over a year. Sometime in the last couple of weeks I noticed that the car is now in
"Dashcam mode
car unrecognized"

### Provide a route where the issue occurs

90d56ac785678835

### openpilot version

0.9.5-release / release3 / 0df6464/ Nov 27

### Additional info

2019 Honda Civic EX (not hatchback)
Dongle ID: 90d56ac785678835
Version 0.9.5-release / release3 / 0df6464/ Nov 27
I have tried:
rebooting the device
unplugging and replugging
reinstalling openpilot

**Comment by sshane** [comment]
This car can fingerprint without the OBD port with: https://github.com/commaai/openpilot/pull/31501
