### ISSUE TITLE
Corolla support

### ISSUE THREAD

**Issue by atxfz09** [commaai/openpilot#311]
I am having issues with my giraffe and panda not supplying power to the neo, causing it not to work

**Comment by mtourangeau** [comment]
Follow this procedure: https://community.comma.ai/wiki/index.php/Panda_Flashing

The easiest way to flash panda via EON is as follows: 
Disconnect Panda from Giraffe
Plug Panda into OBD2 Port of car (Car powered off)
Start with EON powered off and connect via USB to Panda
Once EON powers up the Panda will begin flashing and green LED will flash for a few seoncds
Flashing is complete when Panda shows red pulsing LED (heartbeat)
Plug Panda back into Giraffe

**Comment by mtourangeau** [comment]
you can use your phone camera to check the flashing light

**Comment by atxfz09** [comment]
I got the panda to flash but now I keep getting a cruise malfunction warning

**Comment by mtourangeau** [comment]
Ask your question in the community forums. 

https://community.comma.ai/viewforum.php?f=19&sid=4047bd9da6f83dfcebd2630915ff825b

**Comment by rbiasini** [comment]
And join comma.slack.com!
