### ISSUE TITLE
Missing public key

### ISSUE THREAD

**Issue by belimedo** [commaai/openpilot#31157]
### Describe the bug

After cloning and building the Openpilot project as described in [tools](https://github.com/commaai/openpilot/tree/master/tools) section for the Native Ubuntu 20.04 build, I tried running the launcher and Metadrive simulation. While running the launcher I got the following output:

> (openpilot-py3.11) milan@milan-virtual-machine:~/projects/openpilot$ ./tools/sim/launch_openpilot.sh 
system/loggerd/bootlog.cc: bootlog to /home/milan/.comma/media/0/realdata/boot/2024-01-25--11-25-33
missing public key: /home/milan/.comma/persist/comma/id_rsa.pub
ui deleter thermald statsd
ui deleter thermald statsd
ui deleter thermald statsd

After launching `./tools/sim/launch_openpilot.sh`, as stated in the [simulator tutorial](https://github.com/commaai/openpilot/tree/9807bd99dbc526ba92bb68c503d5108b9f892dd1/tools/sim) in second terminal I run following command: `./tools/sim/run_bridge.py`. Without `--simulator metadrive` as it is no longer required from version 0.95. After running this command output in first terminal now looks like this:

> ui deleter thermald statsd
waiting for dmonitoringmodeld to initialize
Failed to generate mapbox token due to missing private key. Ensure device is registered.
Traceback (most recent call last):
  File "/home/milan/projects/openpilot/selfdrive/navd/navd.py", line 56, in __init__
    self.mapbox_token = Api(self.params.get("DongleId", encoding='utf8')).get_token(expiry_hours=4 * 7 * 24)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milan/projects/openpilot/openpilot/common/api/__init__.py", line 13, in __init__
    with open(Paths.persist_root()+'/comma/id_rsa') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/milan/.comma/persist/comma/id_rsa'

After running the `./run_bridge.sh` command, Metadrive window shows up and crashes in a second. I believe that the reason for crashing isn't the missing key but other exceptions that I've got for `Onnx` provider which firstly tries CUDA and then moves onto `CPUExceutionProvider`. But still, first error is `id_rsa` key which is missing and the whole `persist` directory from `.comma` directory.

I wrote about this issue on Discord channels as well and saw that there are other people with the same issue, but no solution was given to us.

### OS Version

Ubuntu 20.04

### openpilot version or commit

8472ae5317d98a41dae28b2cd1e72ac05b5cae04

### Additional info

I'm on the latest master. Many issues/bugs before this were cleared but I saw and on the discord channel for the simulator that other people are experiencing the same issue as me.

**Comment by jnewb1** [comment]
you will either need a mapbox token or to disable mapsd. https://github.com/commaai/openpilot/pull/31162

**Comment by qingwan7** [comment]
hi,Can you give me your sucess env？
