### ISSUE TITLE
Update docs/WORKFLOW.md

### ISSUE THREAD

**Issue by grottiTT** [commaai/openpilot#31209]
### Describe the bug

It seems like there is a discrepancy between the setup guide versus the Quick Start guide. 

Before building openpilot, the user should activate a poetry shell with the python dependencies installed, or else the build process runs into a `ModuleNotFoundError`
![Screenshot from 2024-01-29 11-34-53](https://github.com/commaai/openpilot/assets/93344990/6b895349-6c09-4e4a-862b-b12f94373271)

Please update the Quick Start guide so it reflects this.

### OS Version

Ubuntu 22.04

### openpilot version or commit

80db6f0e28aa9ca55488c991d62bed65986624db

**Comment by adeebshihadeh** [comment]
I think managing your Python environment is up to the user. The tools README just suggests one way to do it.
