### ISSUE TITLE
[$100 bounty] test more LogReader scenarios

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#31223]
```auto_source``` and ```auto_strategy``` have introduced quite a few cases into logreader that can easily break, we want to test each one with a unit test in [```test_logreader```](https://github.com/commaai/openpilot/blob/master/tools/lib/tests/test_logreader.py). All api queries and downloading should be mocked to make this a proper unit test with no network or specific route dependence.

Required tests:
- [ ] rlog not available on comma api, but is available from another source (openpilot ci bucket, commaCarSegments), rlogs should be parsed
- [ ] rlogs not available, but qlogs are: should error with ```/r```, pass with ```/q``` and ```/a```
- [ ] rlogs only available for specific segments, but qlogs are available for the rest: should error with ```/r```, pass with ```/a```
- [ ] no logs available -> should error for all query types

**Comment by grottiTT** [comment]
I don't see `def auto_fallback` in `logreader.py`; I checked the most recent master and I don't see it in there.

Can you please explain what you meant by that?

**Comment by jnewb1** [comment]
> I don't see `def auto_fallback` in `logreader.py`; I checked the most recent master and I don't see it in there.
> 
> Can you please explain what you meant by that?

meant auto_strategy, fixed

**Comment by grottiTT** [comment]
For the second scenario, where we're passing a qlog file, is the `segment_range` found in the `QLOG_FILE` constant? This constant is at the top of the unit test file.
I see "0375fdf7b1ce594d/2019-06-13--08-32-25/3" which means 3 segments from this specific route?

@jnewb1 idk if my question makes sense, but we need to pass a SegmentRange to the `auto_source` function.

**Comment by jnewb1** [comment]
A SegmentRange can be created from a string easily with

> SegmentRange('0375fdf7b1ce594d/2019-06-13--08-32-25")

**Comment by adeebshihadeh** [comment]
Still interested, but closed due to low quality PRs. If someone wants to make a high quality PR, bounty is still up for grabs.
