### ISSUE TITLE
Honda CR-V 5G fails to fingerprint without comma power

### ISSUE THREAD

**Issue by richardalexdominguez** [commaai/openpilot#31244]
please feel free to re-open with a route so we can check this out

_Originally posted by @sshane in https://github.com/commaai/openpilot/issues/31006#issuecomment-1918317971_

**Comment by richardalexdominguez** [comment]
Wish I knew how to put a route in here for you. Any steps I can take to get Dashcam mode to recognize my car? Would love to see what comma 3X can help me do…

**Comment by sshane** [comment]
In the device settings it will have a dongle ID. You can post that here

**Comment by richardalexdominguez** [comment]
It has the dongle ID: 54f2cff3e445c51e 
On the 3X but I see no way to download drives… 
Can you send a screenshot or more detailed directions?

**Comment by johnnathanwood** [comment]
> It has the dongle ID: 54f2cff3e445c51e On the 3X but I see no way to download drives… Can you send a screenshot or more detailed directions?

You can find the drives on connect.comma.ai

### 1. Click on a drive and you will see two menu items (Select menu item ```More info```:
<img width="701" alt="Screenshot 2024-01-31 at 1 44 10 PM" src="https://github.com/commaai/openpilot/assets/39569384/ed224fdc-e337-496c-9b11-593ebebb2cd9">

### 2. Select the preserve toggle 

<img width="363" alt="Screenshot 2024-01-31 at 1 45 26 PM" src="https://github.com/commaai/openpilot/assets/39569384/32c4e794-535f-4fbc-a10a-3dacc4859b7f">

<img width="361" alt="Screenshot 2024-01-31 at 1 46 10 PM" src="https://github.com/commaai/openpilot/assets/39569384/5900b507-1296-4172-8c80-17b31840de68">

### 3. Select menu item ```Files```

### 4. Upload all logs (Make sure your comma device is connected to wifi)

<img width="300" alt="Screenshot 2024-01-31 at 1 48 06 PM" src="https://github.com/commaai/openpilot/assets/39569384/51d55d87-6114-460f-a3ed-8318528fcc2d">
<img width="303" alt="Screenshot 2024-01-31 at 1 48 36 PM" src="https://github.com/commaai/openpilot/assets/39569384/9e44184a-cfbe-454c-81aa-99ae00f688d7">

**Comment by sshane** [comment]
Is there a reason you tried to fingerprint as a Civic Bosch?

**Comment by sshane** [comment]
Please try this branch and let me know if it works:

Installer URL: https://installer.comma.ai/commaai/civic-bosch-no-obd

**Comment by richardalexdominguez** [comment]
I did not intend for to fingerprint as a civic... 

YES the civic-bosch-no-obd branch is working. Thank you.

Are there any next steps you recommend so that I can take full advantage of the tech?

**Comment by sshane** [comment]
Make sure you put your device on WiFi so we can check out the logs.

**Comment by richardalexdominguez** [comment]
Whenever the car is home it connects to WiFi.

**Comment by sshane** [comment]
Done in https://github.com/commaai/openpilot/pull/31259!

I noticed a few routes your camera and radar failed to respond (each in separate routes). Can you let me know when the device is on WiFi again?
