### ISSUE TITLE
HKG: combine platforms

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#31323]
Combining the platforms and detecting features on Hyundai will allow us to improve fingerprinting by aggregating as many FW versions as possible to fewer platforms. It also forces us to define the platforms/API in such a way that is agnostic to minor differences in the cars (like if it's hybrid, plug-in hybrid, ICE, EV), etc. We can use the platform code or CAN message presence to differentiate these if needed.

- [ ] Niro Hybrid and Plug-in Hybrid platforms (different platform codes, but fwdCamera dates are shared. we already had the hybrid 2021, but not phev 2021): https://github.com/commaai/openpilot/pull/31275
- [ ] G70 platforms https://github.com/commaai/openpilot/pull/31366
- [ ] All CAN platforms
- [ ] All CAN FD platforms

**Comment by adeebshihadeh** [comment]
@sshane still an issue?

**Comment by sshane** [comment]
yes, but doesn't need to be an unactionable issue
