### ISSUE TITLE
[$100 bounty] mapsd: switch to static render mode

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#31333]
Now that we're on MapLibre (https://github.com/commaai/openpilot/pull/31185), hopefully we can use the static rendering mode here: https://github.com/commaai/openpilot/blob/03c183cb052ff1d9da5c7a927f0abbb37434fe2a/selfdrive/navd/map_renderer.cc#L117.

Currently, the map renderer abuses the Qt event loop and forces it to process the full event queue to achieve behavior that we'd expect from the static rendering. The goal is to replace that janky logic with the proper static rendering mode.

**Comment by MickyG03** [comment]
Hello, I am new to Open Pilot, and I would like to work on this issue, for starters I have simply removed the for loop, just kept the update function and if (rendered()) condition in map_renderer.cc. However while testing the files and running "mapsd", I get these errors (I have created the Mapbox api token and added it to environment variable ), can you please tell me if I am going in right direction, thank you. 

> Starting listener for: navd
: [ ERROR ]  "{unknown}[General]: The resource `https://api.mapbox.com/styles/v1/commaai/ckvmksrpd4n0a14pfdo5heqzr/bkx9h9tjdf3xedbnjvfo5xnbv/sprite.json` not found"
: [ ERROR ]  "{unknown}[General]: The resource `https://api.mapbox.com/styles/v1/commaai/ckvmksrpd4n0a14pfdo5heqzr/bkx9h9tjdf3xedbnjvfo5xnbv/sprite.png` not found"
: [ ERROR ]  "{unknown}[Style]: Failed to load sprite: HTTP status code 404"
: [ ERROR ]  "{unknown}[Style]: Failed to load sprite: HTTP status code 404"
