### ISSUE TITLE
Low Communication Rate between Processes/Communication Issue Between Processes: deviceState

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#31407]
### Describe the bug

A few seconds after engaging, openpilot threw a Low Communication Rate between Processes alert, rendering it unavailable for about two minutes.

### Provide a route where the issue occurs

b76c43f138cb09ac|2024-02-11--07-05-24--4

### openpilot version

c01f5e8f78f2ce08a24ffacce61da55c05d08805

**Comment by adeebshihadeh** [comment]
Took a quick look and seems to be related to the UFS/disk stuff going on in #31219. Gonna close this and continue tracking the issue there.
