### ISSUE TITLE
[$100 bounty] fix docker caching on submodules

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#31420]
this bounty is to fix docker caching on the core openpilot submodules

https://github.com/commaai/cereal
https://github.com/commaai/opendbc
https://github.com/commaai/panda
https://github.com/commaai/rednose

cached docker image should be pushed to the ghcr.io docker repo, similar to how openpilot does it. currently this takes 3-4 minutes for every job on the submodules. Open a PR in each of these submodules

**Comment by bongbui321** [comment]
I believe docker cache in panda is already enabled

**Comment by jnewb1** [comment]
> I believe docker cache in panda is already enabled

nice, so we just need the others then?

**Comment by bongbui321** [comment]
@jnewb1 Yeah I submitted PRs in all of them waiting for rednose to merge and bounty solved

**Comment by jnewb1** [comment]
just merged the rednose one, think this is solved now! thanks!

**Comment by jnewb1** [comment]
hmm, just made a PR in cereal and it doesn't seem to have cached... https://github.com/commaai/cereal/pull/593

**Comment by bongbui321** [comment]
I wonder why it can pull the cache here https://github.com/bongbui321/cereal/actions/runs/8015514916/job/21895802617. I'll look into it

**Comment by jnewb1** [comment]
![image](https://github.com/commaai/openpilot/assets/9648890/ab0b8921-84d9-46ff-8dbe-5fdab0bed0f1)
seems like the package is there?

**Comment by jnewb1** [comment]
caching seems to work locally too...
![image](https://github.com/commaai/openpilot/assets/9648890/3f102659-c0ec-4f08-ae27-4bc4fefe5990)

**Comment by bongbui321** [comment]
How about permission of which repo can use the package? though I'm sure `commaai/cereal` has `Admin` permission already since it is the one that pushes the image. 
Earlier I deleted a new image and push a new one, and it can pull docker cache on my cereal repo. if possible can you try pushing a new image and see if it works?
