### ISSUE TITLE
"Radar error: restart the car" on 2/13 master-ci

### ISSUE THREAD

**Issue by TheOfficialJosh** [commaai/openpilot#31435]
### Describe the bug

Openpilot will not engage on 2/13 build of master-ci. Shows message similar to "radar error: restart the car. Worked previously on 2/12 build.

### Provide a route where the issue occurs

5130484aa8069bad|2024-02-13--16-06-18--0

### openpilot version

0.9.6 / master-ci / 6834188 / Feb 13

**Comment by adeebshihadeh** [comment]
Fixed by 7f7f1fd21b293901fa003dce8656db89e15726aa
