### ISSUE TITLE
can/pandaStates skips on 2024 Hyundai ports

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#31563]
### Describe the bug

can/pandaStates skip occasionally on 3X on 2024 Elantra/Kona ports.

From https://discord.com/channels/469524606043160576/1159432092564869161/1209061778076598302

https://connect.comma.ai/c2fd040a5e34f3ad/1708566924729/1708568151988
https://connect.comma.ai/c2fd040a5e34f3ad/1708568603223/1708569334131

![image](https://github.com/commaai/openpilot/assets/1976269/ea86807a-447f-420b-863a-e64fe285c9bb)

### Which car does this affect?

2024 Elantra/Kona

### Provide a route where the issue occurs

c2fd040a5e34f3ad/2024-02-21--17-55-25

### openpilot version

master

**Comment by adeebshihadeh** [comment]
#32286
