### ISSUE TITLE
tici: camera feed too dark

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#31627]
### Describe the bug

Seems to have started around around december, might be software related with users noticing these issues possibly after an update pushed to release.

firstsrif (12/12/2023) - https://discord.com/channels/469524606043160576/954493346250887168/1184142288583143507
![image](https://github.com/commaai/openpilot/assets/1976269/0815d122-3b91-4d58-8f13-c0183ee0c981)

BIGram (12/13/2013) - https://discord.com/channels/469524606043160576/871838269405556736/1184670185232277514
![image](https://github.com/commaai/openpilot/assets/1976269/da2949cc-fb5b-4950-b8f8-a7b66462946e)

Simon Kuang (1/13/2024) - https://discord.com/channels/469524606043160576/871838269405556736/1195936661922652170
![image](https://github.com/commaai/openpilot/assets/1976269/e3944ed2-a6a0-4b0f-987d-0483814dccb3)

mikejakes (2/28/2024) - https://discord.com/channels/469524606043160576/871838269405556736/1212501848699838465
![image](https://github.com/commaai/openpilot/assets/1976269/a89b443a-c21e-49fc-9d3d-21a00b349f04)

firstsrif (2/28/2024) - https://discord.com/channels/469524606043160576/871838269405556736/1212534755388690514
![image](https://github.com/commaai/openpilot/assets/1976269/7659a635-3ade-4a2d-ade2-0497bf2760e5)

### Provide a route where the issue occurs

master

### openpilot version

master

**Comment by adeebshihadeh** [comment]
This only affects displaying the camera feed in some night time scenes. Since the recorded video looks fine, we've decided not to put any effort into at this time.

**Comment by Miniz199922** [comment]
I have issues in the daytime. The cars are hard to see.
