### ISSUE TITLE
LogReader: asks to use qlogs before checking all sources

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#31662]
When not specifying a read mode.

It checks internal source, doesn't find it, then asks if you want to use qlogs even though it is available on the openpilotci source. Potentially confusing as I always ctrl+c'd out instead of typing N which used to exit juggle.py

**Comment by jnewb1** [comment]
ah yes this is an issue with auto_interactive + auto_source. auto_source needs to first check rlogs for all sources before then falling back to auto

**Comment by jnewb1** [comment]
also, I think if only qlogs exists on some source, auto_source will choose that first even if all the rlogs exist in a later source. Seems like auto_source should always check if rlogs exist first for any soruce

**Comment by sshane** [comment]
`5e75f47a17ee2815/00000000--9f9cb10dc2` this says there are some missing rlogs but all are there

**Comment by gregjhogan** [comment]
Listing all files for a route or segment prefix should be very fast on any source and knowing all files for all sources up front may make things easier/simpler (instead of checking if individual files exist)
