### ISSUE TITLE
Window content can be bigger that screen size

### ISSUE THREAD

**Issue by mimi89999** [commaai/openpilot#31683]
### Describe the bug

Hello,
I noticed that the window content can be bigger than my screen size when running the simulator (`./tools/sim/launch_openpilot.sh`).

![Capture d’écran du 2024-03-02 13-25-57](https://github.com/commaai/openpilot/assets/8530546/4616f140-ffcd-42b9-93f1-9b5ab4fad58f)

Setting the `QT_SCALE_FACTOR` env variable to something smaller than one can downsize the UI. However setting the `QT_SCALE_FACTOR` to anything other than `0.5` causes the camera view to not be aligned with the traced path.

![Capture d’écran du 2024-03-02 13-32-36](https://github.com/commaai/openpilot/assets/8530546/4a07d9b9-f909-4eff-a064-f4711fe91b63)

### OS Version

Debian Trixie

### openpilot version or commit

3b5f6cd6b2e695c7be321ff3ce863d98589ff1e1

**Comment by adeebshihadeh** [comment]
`QT_SCALE_FACTOR` is an ugly hack to get the ui working on small screens. I'd merge clean PRs to fix this, but I wouldn't call this a bug.
