### ISSUE TITLE
Strange behavior of OpenPilot experimental mode in the simulator

### ISSUE THREAD

**Issue by mimi89999** [commaai/openpilot#31711]
### Describe the bug

Hello,
When working on the MetaDrive integration, I notice that OpenPilot behaves very strangely in the simulator. It randomly attempts to cross the solid yellow lane and make a U turn on the road. I inspected the data sent drom the bridge with Cabana and everything seems fine, so I don't think that it is an issue with the simulation itself. I suspect that maybe missing inputs to the model might be causing it. The simulation doesn't have mapsd and other services.

### OS Version

Debian Trixie

### openpilot version or commit

deb79a9c443fa1fc1499e40a97757c7d8b6af735

### Additional info

https://github.com/commaai/openpilot/assets/8530546/8ab2f07a-7d85-4dcb-abc8-0bf251fe3395

https://github.com/commaai/openpilot/assets/8530546/3578428d-d3c0-4f8e-bed8-dc1a3384a86b

The error at the end is due to the simulation ending

**Comment by OxygenLiu** [comment]
the experimental mode works only when `Driving Personality` is `Relaxed`.

**Comment by adeebshihadeh** [comment]
Simulator is still pretty early, so it's not ready for bug reports like this yet. Join the Discord for further sim discussion.
