### ISSUE TITLE
[$100 bounty] ability to modify any part of a platformconfig with python

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#31713]
we'd like the ability to modify the platform configs automatically using python, for automating spec updates, new model years, etc.

example:

```python
from selfdrive.car.honda.values import CAR

original_config = CAR.HONDA.config

new_config = original_config.copy()

new_config.specs.mass = 1400
new_config.flags |= HondaFlags.EXAMPLE_FLAG

save_config(CAR.HONDA, new_config)
```

and values.py reflects this change with no other diffs, and ideally the formatting remains exactly the same.

must be simple and expand easily expand to more fields within the PlatformConfig as they are introduced

**Comment by webbdays** [comment]
I would like to work on this issue.
And also i would like to know more on this platform config.
where is this config file located.
Please provide any example use case.

**Comment by jnewb1** [comment]
@webbdays `selfdrive/car/honda/values.py` is one example

**Comment by teodoramilanovic** [comment]
#32327

**Comment by teodoramilanovic** [comment]
#32327 - Could you check out this PR?
