### ISSUE TITLE
Multiple camera streams to openpilot

### ISSUE THREAD

**Issue by ebellumat** [commaai/openpilot#31770]
We are developing new afoordable eletric car in Brazil and we are creating the vehicle to be compatible with openpilot from the factory. 

I have some questions, 

This is something new for this software, instead hacking the car to make the openpilot runs, we want to make the car compatible to openpilot from scratch. 

So, i came here to the community to know how we could do it in the best way possible to support openpilot. 

I have some doubts like: 

- How we could use the cameras around the car to make the openpilot don't have blind spots at all?
- What the best places to have câmeras around the car
- What kind of sensors we could add to make openpilot better, like sonnars, lidars and etc.
- What we could do to have openpilot like an app, integrated to the Car multimedia center instead have the device on the Windshield? 
- Are there any specific hardware integration challenges or compatibility issues that we should anticipate when integrating Openpilot with our electric car's existing systems and components
- What the best way to connect those cameras to the comma device (or a new device if needed) to make this work?

As an engineer, I am delighted that we don't need to resort to hacking the car to decipher CAN messages for Openpilot functionality. Instead, we have the opportunity to create the most seamless experience ever for this software.

**Comment by adeebshihadeh** [comment]
Welcome! Happy to discuss this further on the community [Discord](https://discord.comma.ai) - our issue tracker here is for bugs.
