### ISSUE TITLE
openpilot Target Branch/updates stopped working

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#31867]
### Describe the bug

Occasionally, openpilot will fail to download updates, with the “failed to check for update” message after being stuck on “downloading” for a few minutes. This occurs most often when I try to switch to a different branch using the target branch feature, despite updates having worked for weeks prior. I have encountered this issue on several occasions, over multiple comma three/3X devices.

Rebooting and connecting to different networks,   including my phone’s hotspot and my home WiFi network, does not resolve this issue.

This can be remedied by uninstalling openpilot and then reinstalling by entering my desired branch in the setup menu, but doing so is tedious as I have to enter all of my WiFi networks’ passwords and redo training/settings/calibration all over again.

### Provide a route where the issue occurs

N/A

### openpilot version

7e224dd1dc4834677db13615e73b66ecf7416c25

### Additional info

dongleID: ed882557605319f9

**Comment by adeebshihadeh** [comment]
We're rewriting the entire updater for 0.9.7, so gonna close this. Once that's in, stress it all you want, post about it, and we'll fix all the bugs!
