### ISSUE TITLE
Comma ai 3 x - error - CAN error Check connections, Kia Forte 2023 LXS 

### ISSUE THREAD

**Issue by vesenwa** [commaai/openpilot#31863]
### Describe the bug

Same unit worked in crv 2020. Tried forte 2023, guess fw issue. Error - can error, check connections.

dongle id bbc520c51098bebc

### Which car does this affect?

Kia Forte 2023 LXS

### Provide a route where the issue occurs

https://useradmin.comma.ai/?onebox=google_116050050349953316707

### openpilot version

sunny pilot c3

**Comment by sunnyhaibin** [comment]
The trim for this car's model and model year does not have Smart Cruise Control from the factory. It will not receive official openpilot support at the moment. Custom forks such as sunnypilot supports steering only for this trim.
