### ISSUE TITLE
cars: remove all random tuples within carcontroller and carstate

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#31928]
remove all the random tuples of cars spread throughout the car stack. example:

```python
  elif CP.carFingerprint in (CAR.GENESIS_G80, CAR.GENESIS_G90, CAR.ELANTRA, CAR.ELANTRA_GT_I30, CAR.IONIQ,
                               CAR.IONIQ_EV_LTD, CAR.SANTA_FE_PHEV_2022, CAR.SONATA_LF, CAR.KIA_FORTE, CAR.KIA_NIRO_PHEV,
                               CAR.KIA_OPTIMA_H, CAR.KIA_OPTIMA_H_G4_FL, CAR.KIA_SORENTO):
      self.STEER_MAX = 255
```

everything should be a flag instead, example

```python
HyundaiFlags.ALT_EPS_LIMITS
```

**Comment by sshane** [comment]
For this specific case, note that I want to entirely remove this tuple and detect this--it's preventing the merging of a lot of Hyundai platforms. Maybe we wait for that so we don't need to add and remove a flag (and handle the migration)?
