### ISSUE TITLE
Subaru: Increase RPM Limit

### ISSUE THREAD

**Issue by jackmerrill** [commaai/openpilot#31959]
I have noticed in certain circumstances, that the Subaru RPM limit of 2400 is too low to keep higher speeds. I have had to manually take over the gas/brake (MADS on SP) numerous times on the highway, in order to keep a good speed with surrounding traffic. (MA left lanes typically go 80-85, OP usually keeps up at 75-79).

I believe increasing the RPM limit to 3600 would be enough to keep up at higher speeds.

**Comment by adeebshihadeh** [comment]
Closing as this isn't an immediately actionable. Subaru longitudinal is behind the alpha toggle.
