### ISSUE TITLE
Mazda 2024 CX5 Carbon Dashcam Mode, Car Unrecognized

### ISSUE THREAD

**Issue by wenqian-ye** [commaai/openpilot#31987]
### Describe the bug

See https://github.com/commaai/openpilot/issues/30872#issuecomment-2008482381.

dongle id: 833d1eb9ecc9b842

### Which car does this affect?

Mazda 2024 CX5 Carbon

### Provide a route where the issue occurs

833d1eb9ecc9b842/2024-03-23--05-59-28/3

### openpilot version

0.9.6-release

### Additional info

This issue happens on all the recorded drives. I have double checked the connection of cables.

**Comment by sshane** [comment]
Your car should be supported on master

**Comment by wenqian-ye** [comment]
Could you provide the url corresponding to the branches? I was using the default openpilot.comma.ai

**Comment by sshane** [comment]
openpilot-nightly.comma.ai

**Comment by wenqian-ye** [comment]
Thanks! I will take a try and let you know how it works.

**Comment by wenqian-ye** [comment]
It works on my car with the master branch. Thank you again!
