### ISSUE TITLE
when support mazda3 for 2014 ? 

### ISSUE THREAD

**Issue by justinyaoqi** [commaai/openpilot#32]

**Comment by honryhonry** [comment]
不支持，要自己加装硬件设备，还得在程序上再开发

**Comment by adam-nelson** [comment]
I think he said

Does not support, you want to install their own hardware, have to develop the program

**Comment by geohot** [comment]
comma.ai doesn't have plans to support cars beyond Honda's, but if people show initiative doing the port, we can help support and upstream
