### ISSUE TITLE
Why laika module disappear at > 0.9.5 version?

### ISSUE THREAD

**Issue by datvuthanh** [commaai/openpilot#32037]
### Describe the bug

Dear all,

I'm trying to understand how the Laika module works, but I couldn't find any scripts related to Laika in the locationd module. Could it be that Laika is no longer being used?

Thank you

### Provide a route where the issue occurs

github_44630913

### openpilot version

0.9.6

**Comment by adeebshihadeh** [comment]
This is not a bug; check out the community Discord for discussion instead: https://discord.comma.ai.
