### ISSUE TITLE
Cruise fault 

### ISSUE THREAD

**Issue by Ohiovolt** [commaai/openpilot#32052]
### Describe the bug

Cruise fault. C3x throws cruise fault 5 seconds after boot up. Renders acc useless. 

### Which car does this affect?

2017 Chevy volt

### Provide a route where the issue occurs

https://connect.comma.ai/8c4958bc2fe68698/1711669072782/1711669379513

### openpilot version

Release3

### Additional info

https://github.com/commaai/openpilot/assets/165112206/0ec23138-fe73-48df-b7d3-289c9023af2a

**Comment by sshane** [comment]
You already have an issue here: https://github.com/commaai/openpilot/issues/32023
