### ISSUE TITLE
"Unrecognized car" Mazda CX-5 2024 PP

### ISSUE THREAD

**Issue by qleon314** [commaai/openpilot#32057]
### Describe the bug

I'm testing a newly purchased C3x on my 2024 CX-5 PP and encountered the "car unrecognized, dashcam mode only" exception. 

### Which car does this affect?

Mazda CX-5 2024 Premium Plus

### Provide a route where the issue occurs

b830dd79ab37754c/2024-03-29--16-37-40

### openpilot version

0.9.6

### Additional info

`dongle_id	      serial	    device_type	alias	sim_id	    prime	   prime_type	    last_ping`
[b830dd79ab37754c](https://useradmin.comma.ai/?onebox=b830dd79ab37754c)	ddfe2c1f	threex	None	89852350823020025713	False	0	2024-03-29 17:08:00	uploads accepted`

**Comment by sshane** [comment]
Your fingerprints were added in https://github.com/commaai/openpilot/pull/30882
