### ISSUE TITLE
Ford is moving too slowly and needs your help

### ISSUE THREAD

**Issue by ya787499883** [commaai/openpilot#32062]
### Describe the bug

Ford's progress is too slow. I really hope you can expedite the process. We can provide Ford Edge, Mondeo, and Lincoln Nautilus 2020-2023 as test vehicles. I will try and report the test results. I have a friend who bought the C3X model MKX from China, but he can't get support. In the end, the equipment was damaged and I sent it to you for repair. A large number of Fords in China did not receive your support, all of which were Q3, requests from modification shops.

### Provide a route where the issue occurs

ac88836411233dff

### openpilot version

0.961

**Comment by adeebshihadeh** [comment]
This isn't a bug - check out our [Discord](https://discord.comma.ai) or GitHub Discussions instead.
