### ISSUE TITLE
LKA error on 2018 RAV4 at around 1:10 min after the car started

### ISSUE THREAD

**Issue by TiggerBB** [commaai/openpilot#32068]
### Describe the bug

Device: Comma 3
Car: 2018 rav4
Openpilot version: 0.9.6
(Also tried latest sunnypilot and frogpilot, with same problem)
 
 Issues:
Comma Device show:  
LKA failure, restart car to re-engage openpilot
RAV4 display show:  front camera failure & lane keep assist failure (something like that, I forgot the exact wording)

Reproduce the issue:
After the car started about 1 hr 10min.  This error show up.  It will show up with openpilot, sunny pilot, frogpilot (latest version). It will also have issues regardless of the cruse control is engaged or not.

Extra test that I did to eliminate it was the car problem.  I unplug the USB on the comma 3 and driven the car for 2 hours with cruise control engaged, disengaged and turn on and off the LKA button without any error.

Hope this report help to locate the bug.  I think the 1:10 after car start error play a big part on this bug hunting.  

### Provide a route where the issue occurs

64de1f0143663494

### openpilot version

0.9.6

### Additional info

I cannot locate the route that is long enough. But it will be on Mar29, 24 between 1600 - 2300 PST.
And Mar31, 24 between 1300 - 2000 PST.

I have to make multiple stop to restart the car to re-engage the open pilot.

**Comment by adeebshihadeh** [comment]
This is an issue with your 3rd party SDSU hardware.
