### ISSUE TITLE
Compiling Openpilot on Mac

### ISSUE THREAD

**Issue by srik901** [commaai/openpilot#32067]
### Describe the bug

Followed the directions at https://github.com/commaai/openpilot/tree/master/tools

When running 
scons -u -j$(nproc)

I get error about libdbc.dylib. Looks like rpath error

ImportError: dlopen(/Users/srik/openpilot/opendbc/can/parser_pyx.so, 0x0002): Library not loaded: opendbc/can/libdbc.dylib
  Referenced from: <2ACCD76B-E2BF-31CA-86C8-7506C49F2C9A> /Users/srik/openpilot/opendbc/can/parser_pyx.so
  Reason: tried: 'opendbc/can/libdbc.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSopendbc/can/libdbc.dylib' (no such file), 'opendbc/can/libdbc.dylib' (no such file)

This is on Macbook Pro (M1 Pro; 32 GB) with Sonoma 14.1.1

### OS Version

Mac OS Sonoma 14.1.1

**Comment by adeebshihadeh** [comment]
macOS native build isn't supported. See [here](https://github.com/commaai/openpilot/tree/master/tools#system-requirements)
