### ISSUE TITLE
qlog option is no longer there in juggle.py

### ISSUE THREAD

**Issue by srik901** [commaai/openpilot#32075]
### Describe the bug

https://github.com/commaai/openpilot/tree/master/tools/plotjuggler readme shows how to use juggle.py 

In the demo it uses the option --qlog which is no longer available. 

### OS Version

Ubuntu 20.04

**Comment by jnewb1** [comment]
the --qlog option was removed in favor of a more generic [segment range](https://github.com/commaai/openpilot/tree/master/tools/lib#segment-ranges)
