### ISSUE TITLE
2021 Subaru Crosstrek Hybrid Fingerprint & Port Help

### ISSUE THREAD

**Issue by joshgong94** [commaai/openpilot#32135]
### Describe the bug

I've run stock open-pilot and other forks that have claimed to support Subaru crosstrek hybrids. I have, however, run into "dashcam mode: car unrecognized" errors. I have tried going through the fingerprint instructions, but am still running into issues. I need help fingerprinting and porting my 2021 Subaru Crosstrek Hybrid. Thanks! 

Dongle id: 44b8b200a9e83d43
Route: 44b8b200a9e83d43/00000000--4bbd3cd40a

### Which car does this affect?

Subaru Crosstrek Hybrid 2021

### Provide a route where the issue occurs

44b8b200a9e83d43/00000000--4bbd3cd40a

### openpilot version

 0.9. 6

**Comment by jnewb1** [comment]
hybrid models are not currently supported upstream. I believe subaru-community has them somewhat working
