### ISSUE TITLE
Can errors check connections. Flipped wires at obd2 and comma unit. Pscm not seen on did recalibrate and learn. I fingerprinted fine. 

### ISSUE THREAD

**Issue by mikeblackbaby** [commaai/openpilot#32159]
### Describe the bug

Can errors check connections. Flipped wires at obd2 and comma unit. Pscm not seen on did recalibrate and learm. 2017 Chevy volt 

### Provide a route where the issue occurs

42af5421cf2ec76e

### openpilot version

0.9.7 frog pilot

### Additional info

Wondering if hardware issue right angle usb c little bent. Tried not using also.

**Comment by adeebshihadeh** [comment]
We can't look into issues from forks. Report the issue to the fork maintainers instead. Feel free to open a new issue if you can reproduce this with stock openpilot.

**Comment by mikeblackbaby** [comment]
Stock open pilot does same thing can errors check connections Sent from my iPhoneOn Apr 10, 2024, at 22:12, Adeeb Shihadeh ***@***.***> wrote:﻿
We can't look into issues from forks. Report the issue to the fork maintainers instead. Feel free to open a new issue if you can reproduce this with stock openpilot.
