### ISSUE TITLE
Toyota RAV4 XLE hybrid 2024 error my vehicle is not recognized.

### ISSUE THREAD

**Issue by yahaplus** [commaai/openpilot#32179]
### Describe the bug

![Изображение WhatsApp 2024-04-10 в 20 52 30_be1ebaba](https://github.com/commaai/openpilot/assets/166684589/b9b3f353-bb9d-41d4-a3e7-75e4cec586d1)
![Изображение WhatsApp 2024-04-10 в 20 52 32_2671d19a](https://github.com/commaai/openpilot/assets/166684589/a906b7d2-d2f1-49eb-a6ea-df9b9b7a414e)
![Изображение WhatsApp 2024-04-10 в 20 52 33_b577629b](https://github.com/commaai/openpilot/assets/166684589/8564f9c0-ad34-4c2d-a679-cde5b677de9e)
![Изображение WhatsApp 2024-04-10 в 20 52 35_871903a0](https://github.com/commaai/openpilot/assets/166684589/517f3029-f2d6-4432-a389-563e5abbd620)
![Изображение WhatsApp 2024-04-10 в 20 52 35_e6b7eb3f](https://github.com/commaai/openpilot/assets/166684589/e31a0f80-7ad2-4668-b190-98f026862658)
![Изображение WhatsApp 2024-04-10 в 20 52 37_13e3bc90](https://github.com/commaai/openpilot/assets/166684589/9cd4079a-2573-49aa-b897-6e8377645f6b)
![Изображение WhatsApp 2024-04-11 в 08 46 26_de0ee634](https://github.com/commaai/openpilot/assets/166684589/08f15ae5-6c42-40fb-899b-c759008fd99a)
![Изображение WhatsApp 2024-04-11 в 08 46 27_011da2fa](https://github.com/commaai/openpilot/assets/166684589/e3c1b91a-030d-4fcf-be0b-bb2efe27e8d1)
![Изображение WhatsApp 2024-04-11 в 08 46 28_28460d73](https://github.com/commaai/openpilot/assets/166684589/270bd5db-5289-461c-bd84-fcc3934a3e69)
![Изображение WhatsApp 2024-04-11 в 08 46 29_b02a0ec6](https://github.com/commaai/openpilot/assets/166684589/45e756db-af83-49bd-ad7b-769f4f0e75c0)
![Изображение WhatsApp 2024-04-11 в 18 51 26_9ffef863](https://github.com/commaai/openpilot/assets/166684589/fd265c02-6ec7-4d56-aecd-460267733caa)

Good afternoon. Toyota RAV4 XLE hybrid 2024 (VIN: JTME6RFV6RD557044) error my vehicle is not recognized.
Received the Comma 3X yesterday. I set it up and went to connect it to my car Toyota RAV4 XLE hybrid 2024. Before buying it, I checked the information regarding compatibility and on the website it was indicated that everything is compatible and works. The installation was done according to the video instructions on the official Comma website. After connecting and the first startup an error popped up that my car is not recognized. I rebooted Comma 3x several times......tried to drive the car but all was unsuccessful. Comma 3x did not work properly + ACC/LKAS errors appeared on the dashboard monitor. After returning all the chips to the place of the factory connection errors disappeared and the car worked in normal mode. photos attached.
Please help me solve my problem. Thank you. Have a nice day.
Perhaps I write with this problem not where it is necessary...... but it is really difficult for me to understand as I do not know English well yet. I am writing this message through a translator. I came to the USA from Ukraine with my family due to the military situation in my country. I apologize in advance for the inconvenience. But please, please help me with this problem. Is it possible to fix it remotely or will I have to return the product?

### Which car does this affect?

Toyota RAV4 XLE hybrid 2024 (VIN: JTME6RFV6RD557044)

### Provide a route where the issue occurs

results: google_104000190100648345810

### openpilot version

0.9.6

### Additional info

I can come over if you need me to? Maybe someone can set me up with the right work. Thank you very much. 
Tried reinstalling the firmware many times nothing helped. Also on the forum https://discord.com/ I was recommended to install some other firmware "installer.comma.ai/commaai/master-ci" but nothing worked. The car is also not recognized. I went back to the original firmware "openpilot.comma.ai". I also drove the car with this firmware in the hope that something will change, but unfortunately nothing changed.

**Comment by sshane** [comment]
This does not seem to be a software bug, I see errors reported by panda. I would open a support ticket here: https://comma.ai/support

**Comment by yahaplus** [comment]
Hi. Thank you so much for your help and your time.  Yes. There are errors on the dashboard when the unit itself is not connected. What does that mean? 
![Изображение WhatsApp 2024-04-12 в 11 11 32_572e959e](https://github.com/commaai/openpilot/assets/166684589/204ec95a-2378-4b91-9312-37c9857a7fdd)
![Изображение WhatsApp 2024-04-12 в 11 11 33_9524d66b](https://github.com/commaai/openpilot/assets/166684589/2d63a828-be92-416c-9836-f295ae3130cd)
![Изображение WhatsApp 2024-04-12 в 11 11 33_23996251](https://github.com/commaai/openpilot/assets/166684589/f372e56e-fc9b-4c2f-87af-060e0646fd6b)
![Изображение WhatsApp 2024-04-12 в 11 11 34_a0c801e4](https://github.com/commaai/openpilot/assets/166684589/c05cd4cc-d6d6-4c27-81d0-cef9351f511d)
![Изображение WhatsApp 2024-04-12 в 11 11 34_d46a7d43](https://github.com/commaai/openpilot/assets/166684589/7a31b134-f176-4bde-97d3-9650741ad060)
![Изображение WhatsApp 2024-04-12 в 11 11 35_24040030](https://github.com/commaai/openpilot/assets/166684589/0a327375-4b77-4f3c-b84d-0c671d8aa80e)
![Изображение WhatsApp 2024-04-12 в 11 11 35_e9523a38](https://github.com/commaai/openpilot/assets/166684589/3ab87d2e-05ee-4026-b6f9-29b3ae075c3f)

**Comment by yahaplus** [comment]
> Похоже, это не программная ошибка, я вижу ошибки, о которых сообщила панда, и все встроенное ПО отсутствует. Я бы открыл заявку в службу поддержки здесь: https://comma.ai/support
> 
> Можешь сфотографировать ремень? Есть ли неисправности приборной панели автомобиля, когда кабель USB C comma 3X отсоединен, а жгут проводов подключен?

![Изображение WhatsApp 2024-04-11 в 18 51 26_9ffef863](https://github.com/commaai/openpilot/assets/166684589/ca485544-ec69-4e8d-9021-9728525e1bfa)

**Comment by yahaplus** [comment]
> Похоже, это не программная ошибка, я вижу ошибки, о которых сообщила панда, и все встроенное ПО отсутствует. Я бы открыл заявку в службу поддержки здесь: https://comma.ai/support
> 
> Можешь сфотографировать ремень? Есть ли неисправности приборной панели автомобиля, когда кабель USB C comma 3X отсоединен, а жгут проводов подключен?

Toyota RAV4 XLE hybrid 2024 (VIN: JTME6RFV6RD557044) purchased from an authorized dealer 3 weeks ago.
The Comma 3X autopilot was purchased two days ago. At the first connection all requirements and instructions were observed......by installed the latest firmware "openpilot.comma.ai". On this firmware error....... that my car is not recognized. 
The following firmware was installed in search of the problem elimination 
https://installer.comma.ai/hardcoded-fp/release3-toyota-rav4-2023
https://installer.comma.ai/commaai/nightly https://installer.comma.ai/commaai/master-ci
All the above firmware did not change anything. My car is still not recognized. 
Also it was found that when the wiring harness is connected according to the requirements in the standard places on the car, there were still errors on ACC/LKAS without connecting the autopilot itself. I don't know if it should be like this or not? Maybe the harness itself was put to me in the wrong place ? Who has the wrong harness? Thank you all very much. Have a good day, everybody.

**Comment by sshane** [comment]
I would try a new USB C cable 3.1 gen 2 in the mean time while you are waiting for a response to your support ticket.

**Comment by yahaplus** [comment]
What's this cable going to change? Isn't it just a power cable to the autopilot itself? 


Отправлено из Yahoo Почты на iPhone


Пользователь суббота, апреля 13, 2024, 00:41 написал Shane Smiskol ***@***.***>:




I would try a new USB C cable 3.1 gen 2 in the mean time while you are waiting for a response to your support ticket.

**Comment by nelsonjchen** [comment]
It's not just power. The cable also handles transporting data as well.

**Comment by nelsonjchen** [comment]
Met up with Yan at a local parking lot near where I am living.


First thing we did was swap ODB-C cables. That did not work. My known good cable still caused errors to be thrown.


Then we tried swapping my comma three in place of his comma threex. This also did not work. The errors also showed on my device.


So, we went further up the cables. We swapped the harness box. This made it work! That's a good sign but we continued to swap.


We kept my harness box and installed his harness connector cables. It continued to work. This meant his connector cables are working fine.


And for giggles, we installed his harness box in my Corolla. It causes the same or similar errors to be thrown in my car.



All to say, I believe the harness box is faulty and should be replaced.

**Comment by arifgarayev** [comment]
@nelsonjchen are you sure about that replacement?

**Comment by nelsonjchen** [comment]
Yes, very.

**Comment by yahaplus** [comment]
We swapped everything around and that's the method we used to identify the malfunction. It's all caused by this unit in the photo. Thank you so much Nelsonjchen. 
![Изображение WhatsApp 2024-04-13 в 15 36 05_d04574ba](https://github.com/commaai/openpilot/assets/166684589/e1a37743-5785-4bd9-a647-ce19ac000428)
![Изображение WhatsApp 2024-04-13 в 15 36 07_64557623](https://github.com/commaai/openpilot/assets/166684589/05760583-f015-42e2-bcee-2bbd65d27040)
![Изображение WhatsApp 2024-04-13 в 15 36 08_6b15b77a](https://github.com/commaai/openpilot/assets/166684589/bd83dd14-34c5-43a1-a6d0-f9a04f8c214e)
![Изображение WhatsApp 2024-04-13 в 15 36 08_cc75515c](https://github.com/commaai/openpilot/assets/166684589/2ab07a39-8fe8-4c06-9ad9-22cfae324924)

**Comment by yahaplus** [comment]
![Снимок экрана 2024-04-13 154223](https://github.com/commaai/openpilot/assets/166684589/2ca38ca8-0fde-4fcf-a24a-6fc1e8d1c2a7)
I hope I get this part replaced as soon as possible. Without any problems or complaints to me.

**Comment by yahaplus** [comment]
Hi. Yes, 10000000%. 

Отправлено из Yahoo Почты на iPhone


Пользователь суббота, апреля 13, 2024, 14:47 написал Arif Garayev ***@***.***>:




@nelsonjchen are you sure about that replacement?

**Comment by yahaplus** [comment]
Yes. Replace that part and everything will work. 


Отправлено из Yahoo Почты на iPhone


Пользователь суббота, апреля 13, 2024, 14:47 написал Arif Garayev ***@***.***>:




@nelsonjchen are you sure about that replacement?

**Comment by sshane** [comment]
Make sure to send this thread to our support. Closing here since GitHub is primarily for software issues with openpilot.
