### ISSUE TITLE
Get qlogs back to 500k

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32172]
0.9.6-release qlogs are nearly 1M
- [ ] `liveLocationV2` @nuwandavek

**Comment by sshane** [comment]
Random recent route: 
![image](https://github.com/commaai/openpilot/assets/25857203/3b4d9e5d-a9b6-4562-859b-74839475bfd9)

**Comment by sshane** [comment]
@adeebshihadeh can we close?

**Comment by adeebshihadeh** [comment]
This is great for 0.9.8. 

However, the new goal is 100k for 0.10: https://docs.comma.ai/contributing/roadmap/#openpilot-010. 100k should be sustainable as we scale up.

**Comment by sshane** [comment]
closing since this is part of the 0.9.8 milestone
