### ISSUE TITLE
Brand says Toyota when it’s supposed to say gm. Also panda firmware is outdated. I tired with help from discord no help. 

### ISSUE THREAD

**Issue by mikeblackbaby** [commaai/openpilot#32198]
### Describe the bug

After my drive and my log under car parameters, my fingerprint is fine, but the brand is staying Toyota on the engine and also on the transmission I can’t figure out how to change it to GM. Also, it said my panda firmware is outdated. Help please either ssh into my device I’ll send GitHub ssh keys 

### Provide a route where the issue occurs

42af5421cf2ec76e

### openpilot version

0.9.6

### Additional info

Stock open pilot comma connect 
![IMG_8456](https://github.com/commaai/openpilot/assets/165347539/f1d7124e-90d8-4f1b-8409-62807baafc12)

**Comment by adeebshihadeh** [comment]
Your car is just responding to a request defined for Toyotas, which is expected. The actual fingerprint is corect.
