### ISSUE TITLE
VW California T6.1 - getting a error: "Unable to identify your car"

### ISSUE THREAD

**Issue by peter-patagon** [commaai/openpilot#32194]
### Describe the bug

After installing my new comma on supported cat VW California T6.1 with the latest sw (0.9.6) Im getting an message, that my car is not suppoted or its ECUs are not recognized. Comma swithes to dashcam mode only. 

### Which car does this affect?

Volkswagen Califonia T6.1 2023

### Provide a route where the issue occurs

e4a43dfbf93199b4/2024-04-12--18-07-03

### openpilot version

0.9.6

**Comment by sshane** [comment]
Your car should be supported on master branch now after https://github.com/commaai/openpilot/pull/32148
