### ISSUE TITLE
2017 chevy volt pscm not seen. 

### ISSUE THREAD

**Issue by mikeblackbaby** [commaai/openpilot#32215]
### Describe the bug

I’m getting a PSCM not seen on a bug reported. i’m getting it on, yeah I official download 0.9.6 even Forks the same issue. There’s no codes on my car. And you can see my steering wheel. Rotate the torque being registered.
![IMG_8526](https://github.com/commaai/openpilot/assets/165347539/22fb0123-871b-4434-b8fc-d71de410120c)

### Which car does this affect?

2017 Chevy volt 

### Provide a route where the issue occurs

Car parameters

### openpilot version

0.9.6

### Additional info

Also it says to update my panda firmware can someone please help me I’ve tired all docs online and python commands. I’ve tried to reflash panda.

**Comment by adeebshihadeh** [comment]
That picture isn't stock openpilot. Check out our [Discord](https://discord.comma.ai) for help getting started.
