### ISSUE TITLE
Toyota: rare inconsistencies in FW response timing

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#32242]
On very rare occasions, we will time out the eps because it is taking too long to respond (on the order of ~100ms, and our timeout is 100ms). This is commonly after it has already responded to the beginning of the query:

```python
    Request(
      [StdQueries.TESTER_PRESENT_REQUEST, StdQueries.DEFAULT_DIAGNOSTIC_REQUEST, StdQueries.EXTENDED_DIAGNOSTIC_REQUEST, StdQueries.UDS_VERSION_REQUEST],
      [StdQueries.TESTER_PRESENT_RESPONSE, StdQueries.DEFAULT_DIAGNOSTIC_RESPONSE, StdQueries.EXTENDED_DIAGNOSTIC_RESPONSE, StdQueries.UDS_VERSION_RESPONSE],
      ...
      ),
```

so a potential solution could be to double the timeout we add after we get a successful response from any ECU.

We don't want to double the global timeout as that would double the time taken for a lot of the queries that we rely on timing out (VIN queries for other brands, tester present ECU scan query, not perfectly whitelisted requests, etc.).

---

`./debug_fw_fingerprinting_offline.py 297b4b460f361603/2023-06-14--16-55-16/0 0x7a1`:

Here there was 115ms between the single frame query sendcan and the first consecutive frame response (we only extend timeout on consecutive frames due to fake first frames accidentally extending timeout to 60s on a few cars). We can also improve the uds library's handling of duplicate first frames to get a reliability improvement, as that would solve this case:

```python
sendcan: rxaddr=1953, bus=0, 1280.63 ms, 0x031a880100000000, b'\x03\x1a\x88\x01\x00\x00\x00\x00', len(can.dat)=8

    can: rxaddr=1953, bus=128, 1289.88 ms, 0x031a880100000000, b'\x03\x1a\x88\x01\x00\x00\x00\x00', len(can.dat)=8
    can: rxaddr=1953, bus=2, 1289.88 ms, 0x031a880100000000, b'\x03\x1a\x88\x01\x00\x00\x00\x00', len(can.dat)=8

    can: rxaddr=1961, bus=2, 1329.98 ms, 0x10135a8801383936, b'\x10\x13Z\x88\x01896', len(can.dat)=8
    can: rxaddr=1961, bus=0, 1329.98 ms, 0x10135a8801383936, b'\x10\x13Z\x88\x01896', len(can.dat)=8

sendcan: rxaddr=1953, bus=0, 1330.54 ms, 0x30000a0000000000, b'0\x00\n\x00\x00\x00\x00\x00', len(can.dat)=8

    can: rxaddr=1953, bus=128, 1364.22 ms, 0x30000a0000000000, b'0\x00\n\x00\x00\x00\x00\x00', len(can.dat)=8
    can: rxaddr=1953, bus=2, 1364.22 ms, 0x30000a0000000000, b'0\x00\n\x00\x00\x00\x00\x00', len(can.dat)=8

    can: rxaddr=1961, bus=2, 1395.28 ms, 0x2135423333363330, b'!5B33630', len(can.dat)=8
    can: rxaddr=1961, bus=0, 1395.28 ms, 0x2135423333363330, b'!5B33630', len(can.dat)=8

    can: rxaddr=1961, bus=2, 1425.39 ms, 0x2200000000000000, b'"\x00\x00\x00\x00\x00\x00\x00', len(can.dat)=8
    can: rxaddr=1961, bus=0, 1425.39 ms, 0x2200000000000000, b'"\x00\x00\x00\x00\x00\x00\x00', len(can.dat)=8
```

**Comment by adeebshihadeh** [comment]
Adding to the milestone. We have to fix ASAP.

**Comment by sshane** [comment]
Sounds good. The first solution could handle everything and is the easiest and most generic, so I'll get that in first.

---

TODO:
- [ ] Apply temporal checks to first frame responses in IsoTpMessage. This is similar to the consecutive frame ID assertion that disallows just getting infinite consecutive frames from a bad ECU
- [ ] If the above doesn't fix all cases, double the timeout on receive of any valid response. This works because we preface all Toyota queries with tester present+
