### ISSUE TITLE
Ioniq 6 CAN Bus Disconnected Message

### ISSUE THREAD

**Issue by limatango79** [commaai/openpilot#32286]
### Describe the bug

I drive the Hyundai Ioniq 6 2023 with HDA II and I've tested Comma 3X with OP 0.9.6, 0.9.7 master-ci, SP release, staging and dev. Regardless of the software, I get the same error.
Every now and then I get the message "CAN bus disconnected". I can't reproduce it either.
I also get the message "Controls Lagging".

I have checked all the cables several times. The device is new and undamaged.

### Which car does this affect?

Hyundai Ioniq 6 2023 HDA II

### Provide a route where the issue occurs

78e8c2388cf1ce49/00000000--09dfcd3706/0

### openpilot version

0.9.6 and 0.9.7 master-ci

**Comment by sshane** [comment]
@briskspirit do you have any time to check this out? Looks like this was hit after boardd stopped sending can messages for 200 ms:

https://github.com/commaai/openpilot/blob/d56f188854135ff4d1cf2cb6bf184a8301a82edd/selfdrive/boardd/panda.cc#L248-L253

![image](https://github.com/commaai/openpilot/assets/25857203/2388bb85-5113-436d-816d-91510f441487)

**Comment by adeebshihadeh** [comment]
I'll check it out before 0.9.7.

**Comment by royjr** [comment]
I have the same exact messages daily on a 2024 Kona, may be related to..
- https://github.com/commaai/openpilot/issues/31563
- https://github.com/commaai/openpilot/issues/31822
- https://github.com/commaai/openpilot/issues/30815

**Comment by limatango79** [comment]
I get the message "CAN Bus Disconnected" about once an hour. The message "Controls Lagging" appears about 3 to 4 times an hour. If desired, I can load more routes in which this occurs.

**Comment by thftgr** [comment]
It also happens once or twice a week in KIA K8 HEV 2024 HDA II

**Comment by adeebshihadeh** [comment]
Working on this now. I'll have a branch for you guys to try soon!

**Comment by adeebshihadeh** [comment]
Closed all the related issues

There's a few things going on here:
- [x] subtle boardd bugs that made edge cases worse #32401, #32404
- [ ] out of sync slave/master, with slave trying to TX a large buffer but master is clocking out a few bytes at a time trying to get an ACK 
- [ ] in some cases, boardd + (`spi0` kernel thread) can saturate a core #32402

**Comment by royjr** [comment]
Can't specifically remember, but does it make sense that I see these errors less frequently now?

**Comment by limatango79** [comment]
Unfortunately, that doesn't apply to me.
On a 4-hour drive two days ago, I had “Controls Lagging” about every 15 minutes and “CAN Bus Disconnected” every 25 minutes.
And just yesterday, on a 10-minute drive, I had “Controls Lagging” exactly 4 times.
Somehow you get used to it, but it is annoying. And you become numb to “real” error messages.
I also rarely get the message “Communication Issue between Processes” and “Locationd Error”. But I don't think that has anything to do with the other messages.

**Comment by adeebshihadeh** [comment]
We're blocking the next release on this, and it's one of the last TODOs. I should have a fully fixed branch for you guys to try in a day or two. 

> Can't specifically remember, but does it make sense that I see these errors less frequently now?

Yes, I shipped one fix already, but there's still a couple things.

**Comment by adeebshihadeh** [comment]
@royjr @limatango79 @JJeonbear @MarcoTheDingo @CruiseBrantley @crwayman7

Can you guys try this branch: `installer.comma.ai/commaai/pandad-max-mode`

**Comment by crwayman7** [comment]
> @royjr @limatango79 @JJeonbear @MarcoTheDingo @CruiseBrantley @crwayman7
> 
> Can you guys try this branch: `installer.comma.ai/commaai/pandad-max-mode`

I just tried to install this bad larry, and I am stuck at 0% Installing. Anyone else have this issue? Don't know if it's going to pull through but I will give it some time because usually when a software/firmware is installing or flashing I'd rather it error out than disconnect/power off.

waymo

**Comment by limatango79** [comment]
> @royjr @limatango79 @JJeonbear @MarcoTheDingo @CruiseBrantley @crwayman7
> 
> Can you guys try this branch: `installer.comma.ai/commaai/pandad-max-mode`

I've just been on a one-hour test drive with this branch. I did not get any error messages such as “CAN bus disconnected” or “control lagging”. 
Here is the corresponding route: 78e8c2388cf1ce49/00000000--e86f98e678

I will take an even longer drive tomorrow, but I think the problem seems to be solved.

Thanks for the hard work.

**Comment by JJeonbear** [comment]
> @royjr @limatango79 @JJeonbear @MarcoTheDingo @CruiseBrantley @crwayman7
> 
> Can you guys try this branch: `installer.comma.ai/commaai/pandad-max-mode`

I will install it today and test drive it.

**Comment by JJeonbear** [comment]
> @royjr @limatango79 @JJeonbear @MarcoTheDingo @CruiseBrantley @crwayman7
> 
> Can you guys try this branch: `installer.comma.ai/commaai/pandad-max-mode`

I drove for about two hours without any errors. However, the system doesn't detect vehicles in the adjacent lane very well. When a vehicle from the adjacent lane merges into mine, it often goes unnoticed, forcing me to frequently apply the brakes.

**Comment by adeebshihadeh** [comment]
Merged! Thanks for testing. Let us know if you have any more issues.
