### ISSUE TITLE
Open Pilot now unuseable

### ISSUE THREAD

**Issue by Deltic9009** [commaai/openpilot#32288]
### Describe the bug

I own a 2018 Honda c-rv. I've used open pilot for 4 months now. Every two or three weeks, on starting the card, all of the vehicle warning messages are displayed in sequence on the screen, accompanied by a warning tone every 2 or 3 seconds. After driving for 15 mins. or so the problems disappear and everything works normally.

Unfortunately, since the most recent update, the problem with the warning etc are permanent, meaning the system is now unusual.

Has anyone else experienced this? Is there a fix or should I return the system to Comma.ai

Thanks for any suggestions.

Steve

### Which car does this affect?

Honda C-RV 2018

### Provide a route where the issue occurs

?

### openpilot version

Latest version

### Additional info

See above

**Comment by adeebshihadeh** [comment]
We'll need your device's dongle ID to look into this.

**Comment by Deltic9009** [comment]
Thanks for your swift reply. Where do I find this ID?Thanks, SteveSent from my iPadOn Apr 24, 2024, at 17:33, Adeeb Shihadeh ***@***.***> wrote:﻿
We'll need your device's dongle ID to look into this.

**Comment by adeebshihadeh** [comment]
It's in comma connect or the device settings.

**Comment by sshane** [comment]
Any updates @Deltic9009?
