### ISSUE TITLE
can bus disconnected (Subaru outback 2019)

### ISSUE THREAD

**Issue by Carrot7128** [commaai/openpilot#32321]
### Describe the bug

Dongle ID: 34965c7ca92c9522
Vehicle: Subaru Outback 2019
Harness: Subaru A
Openpilot version: 0.9.4/subaru-community

Since first installing, the device gives me a CAN Bus disconnected error. Can i get some help regarding this?

What I tried
reconnecting all wire/harnesses
replacing entire harness system
tried using 3rd party usb c 3.2 cable
reinstalling openpilot

Thanks in advance. 

### Provide a route where the issue occurs

34965c7ca92c9522/2024-04-26--22-01-12.bz2

### openpilot version

0.9.4/subaru-community

**Comment by adeebshihadeh** [comment]
We can't look into issues from forks. Report the issue to the fork maintainers instead. Feel free to open a new issue if you can reproduce this with stock openpilot.
