### ISSUE TITLE
Can error check connection - iqonic 5 2023

### ISSUE THREAD

**Issue by wanderer** [commaai/openpilot#32351]
### Describe the bug

I installed openpilot and commia 3 and I get the message "Can error check connection" when I turn on my car. Nothing seems to work. I have tried turning the USB cable around. 

### Which car does this affect?

Hyundai iqonic 5 2023

### Provide a route where the issue occurs

2fa352365f86a9b2|2024-05-04--16-17-56

### openpilot version

0.9.6

**Comment by sshane** [comment]
Can you try this branch? The bus structure looks like an HDA 2 variant, do you know if they market HDA and HDA 2 in your region? And which do you have?

https://installer.comma.ai/commaai/ioniq-5-fix

**Comment by wanderer** [comment]
@sshane thank you for the quick replay. I have a UK 2023 Ioniq. After digging around I read that I probably don't have HDA2. (from this post https://www.reddit.com/r/Ioniq5/comments/1bcwf16/hda_15_on_a_top_spec_2023/) I might have HDA "1.5". But I have not figured out how to tell exactly.

**Comment by wanderer** [comment]
As for ADAS Features i think I have
- Driving Convenience
- Forward Safety
- DAW
- Parking Safety
- Blind-spot Safety

![signal-2024-05-06-173823_002](https://github.com/commaai/openpilot/assets/158211/bea31379-fee2-4db4-bfc1-ac4f394dea8c)
![signal-2024-05-06-173823_003](https://github.com/commaai/openpilot/assets/158211/b5532823-a11e-4077-bc24-22b013375d42)
![signal-2024-05-06-173823_004](https://github.com/commaai/openpilot/assets/158211/d91438fa-ba40-4e58-97dc-4e4023d09695)
![signal-2024-05-06-173823_005](https://github.com/commaai/openpilot/assets/158211/5892ecfc-d49a-48c2-b4aa-5569868cb11d)

**Comment by sshane** [comment]
I believe you ordered the Hyundai Q harness which is meant for HDA2 vehicles, but your bus structure looks to be more similar to HDA. You will want to contact support or open a return to get the Hyundai K harness that is meant for non-HDA2 variants.

Once you have that harness, the missing camera message isn't a requirement as that's only for HDA2.

As an alternate option (and at your own risk), some community members have swapped the wires for CAN 1 and CAN 2 so you won't need to return the harness. See the diagrams for both:

https://github.com/commaai/neo/blob/master/car_harness/Sonata_Harness.sch.pdf

https://github.com/commaai/neo/blob/master/car_harness/EV6_Harness.sch.pdf
