### ISSUE TITLE
Hyundai Kona 2022 compatibility

### ISSUE THREAD

**Issue by mpuri1** [commaai/openpilot#32435]
From the [documentation](https://www.comma.ai/vehicles#hyundai) on compatibility, it looks like Comma3X is only compatible with Kona 2022 and previous verions.  An enhancement/update is required to make it compatible with recent Kona versions.

**Comment by adeebshihadeh** [comment]
This isn't a bug - check out our [Discord](https://discord.comma.ai) or GitHub Discussions instead.
