### ISSUE TITLE
[$100 bounty] tools: split out dev apt dependencies

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32470]
`tools/install_ubuntu_dependencies.sh` installs *all* dependencies one might want for developing openpilot, including some that most will never need (e.g. `clinfo`). 

Split out those dependencies and prompt the user to select whether they want the extra packages installed. Needs to support an non-interactive mode via environment variable for cases like our docker build.

**Comment by macdoos** [comment]
@adeebshihadeh The PR is green and ready for review. LMK if the listed extra packages are enough or if any should be added or removed.
