### ISSUE TITLE
[$250 bounty] Update to Python 3.12

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32516]
This is a pre-requisite to updating to Ubuntu 24.04.

Here's a starting point: https://github.com/commaai/openpilot/pull/32296.

Main blocker is upstreaming 3.12 support to MetaDrive: https://github.com/metadriverse/metadrive.

**Comment by BBBmau** [comment]
@adeebshihadeh requesting this to be locked since I have a PR on upstream metadrive to support 3.12:
https://github.com/metadriverse/metadrive/pull/720

I'll work on the 3.12 update for openpilot soon.

**Comment by BBBmau** [comment]
isn't another major blocker coming from this not being merged? https://github.com/vpelletier/pprofile/pull/51

Doesn't seem like it'll be happening anytime soon.

**Comment by adeebshihadeh** [comment]
We can just remove it for now. We don’t use it that much.
