### ISSUE TITLE
[$100 bounty] Switch to uv package manager

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32522]
Switch the default package manager from poetry to uv. uv is quite new, so it might be not be ready for us yet. Let's try it out though.

https://github.com/astral-sh/uv

**Comment by hernantech** [comment]
Requesting lock on this bounty with a [draft PR](https://github.com/commaai/openpilot/pull/32527). Exporting req's and setting them up in uv then testing validity and performance. Need to migrate checks to uv as well.

**Comment by adeebshihadeh** [comment]
Unfortunately, we can't switch quite yet due to the lack of locking, but @signed-long's PR is a sizable speedup. Looking forward to switching once it has multi platform locking!

**Comment by signed-long** [comment]
Subbed to https://github.com/astral-sh/uv/issues/3350, if I hear anything I'll shout
