### ISSUE TITLE
Setup script fails on Ubuntu 20.04 due to missing apt_pkg module

### ISSUE THREAD

**Issue by bushand1990** [commaai/openpilot#32529]
### Describe the bug

The setup script locally for OpenPilot on Ubuntu 20.04 fails due to missing apt_pkg module. This issue occurs during the execution of the tools/ubuntu_setup.sh script, which results in a traceback error indicating that the apt_pkg module is not found. This prevents the completion of the setup process for OpenPilot, causing issues for developers attempting to set up the environment as per the official guidelines.
![Openpilot error setup](https://github.com/commaai/openpilot/assets/156022014/e137e5fe-9ecc-473b-8352-0040427af977)

### OS Version

Ubuntu 20.04

**Comment by adeebshihadeh** [comment]
Fixed by f4322666c6adc4dd2da569f483f6e108f18fe32a
