### ISSUE TITLE
Build on Apple silicon fails after fresh git pull

### ISSUE THREAD

**Issue by SurferSD** [commaai/openpilot#32554]
### Describe the bug

Homebrew setup and Python dependencies install without issue.

[mac_setup.log](https://github.com/commaai/openpilot/files/15461576/mac_setup.log)

Build fails on Apple Mx hardware during `scons -u -j$(nproc)` execution.

[scons.log](https://github.com/commaai/openpilot/files/15461579/scons.log)

### OS Version

macOS Sonoma v14.5 (23F79)

### Additional info

Steps to reproduce:

```
brew update
brew upgrade
brew cleanup
brew install git-lfs 
git lfs install
brew install gcc@13
cd ~/GitHub
git clone --filter=blob:none --recurse-submodules https://github.com/commaai/openpilot.git
cd openpilot
git-lfs pull
pyenv global 3.11.4
tools/mac_setup.sh
poetry shell
scons -u -j$(nproc)

```

**Comment by adeebshihadeh** [comment]
This is noted in mac_setup.sh: https://github.com/commaai/openpilot/blob/30792577cd6c65c243f22bf1013a012e22b1da38/tools/mac_setup.sh#L6
