### ISSUE TITLE
[$200 bounty] New Ubuntu setup flow

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32553]
See the current setup at `tools/ubuntu_setup.sh`. The goal of this bounty is to make the whole setup more interactive and describe what it's going to do. 

In the setup README, we'll offer two paths:
1. manually install/setup everything, for those who like to manage their own env and tooling
2. an interactive script that'll get you setup from scratch

The interactive script will go something like this:
* do you want to install these runtime apt dependencies?
* do you want to install apt development dependencies?
* do you want to install apt nice-to-haves (e.g. valgrind)?
* detect minimum python version
* start a venv
* install python dependencies inside venv
* show how to active venv

**Comment by am2024ma** [comment]
Is it OK to test in virtual machine Ubuntu latest LTS.

**Comment by navistonks** [comment]
What should be the optional nice-to-have packages?
And isn't the current script already using venvs, since poetry uses them?

**Comment by adeebshihadeh** [comment]
> What should be the optional nice-to-have packages?

The important thing is to get the groups setup, then we can sort everything out later. Just find at least one to move to nice to have. 

> And isn't the current script already using venvs, since poetry uses them?

Yes, but the script should explain what it's going to do and ask if you want to do it. In this case, some users may not want to install poetry and just want to `pip install .`.
