### ISSUE TITLE
Sharing of the openpilot porject 

### ISSUE THREAD

**Issue by aeonSolutions** [commaai/openpilot#32575]
hi @commaci-public 
great work! 

I'm sharing the open pilot project on my own "Open Hardware Electronics for the Volvo P2 platform" here on GitHub. 

[https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki](https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki)

![image](https://github.com/commaai/openpilot/assets/7936768/23e9f4e6-5c09-40e5-852d-176c2edd7366)

**Comment by adeebshihadeh** [comment]
Cool! Closing as this is not an issue.
