### ISSUE TITLE
2022 Lincoln Aviator: Comma 3x Not Recognizing Vehicle

### ISSUE THREAD

**Issue by abdbkn** [commaai/openpilot#32588]
### Describe the bug

I have installed OpenPilot on my 2022 Lincoln Aviator. According to the supported cars list, my vehicle should be compatible. However, the system is not recognizing my car. 

**Dongle ID:** 37f7f485c5a6fd70

**Steps to Reproduce:**
1. Buy a Lincoln Aviator
2. Install OpenPilot on a 2022 Lincoln Aviator.
3. Connect Comma 3x dongle.
4. Observe the error message stating that the car is unrecognized.

**Expected Behavior:**
The Comma 3x should recognize the 2022 Lincoln Aviator as it is listed under supported vehicles.

**Actual Behavior:**
The system fails to recognize the vehicle, displaying an error message.

**Notes:**
Please advise on any potential troubleshooting steps or if additional information is needed to resolve this issue. Thank you for your assistance.

**Environment:**
- Operating System: [Include your OS details]
- Software Version: [Include software version details]
- Hardware: Comma 3x
```

### Provide a route where the issue occurs

NA

### openpilot version

0.9.6-release / release3 / e5d2ce5 / Feb 27

### Additional info

**Additional Information:**
- Model: 2022 Lincoln Aviator
- Comma 3x Dongle ID: 37f7f485c5a6fd70
- Software version: 0.9.6-release / release3 / e5d2ce5 / Feb 27
- Logs: [Attach any relevant logs if available]

**Comment by sshane** [comment]
We shipped an upgrade to fingerprinting to master, master-ci, and nightly branches that hasn't yet made it to release. Please try one of those branches
