### ISSUE TITLE
secretgoodopenpilot paramsd temporary error after lengthy calibration process

### ISSUE THREAD

**Issue by goodchoom** [commaai/openpilot#32649]
### Describe the bug

secretgoodopenpilot took much longer than usual to calibrate. After the calibration process finished, openpilot was unavailable due to paramsd temporary error for about a minute or so.

### Provide a route where the issue occurs

ed882557605319f9/00000001--43c085bbb0/4

### openpilot version

217373a9874637a4ac1e22087fbedb6172005344

**Comment by adeebshihadeh** [comment]
Development branch feedback should just be posted to Discord.
