### ISSUE TITLE
[$100 bounty] Speedup docs build in CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32687]
The `build docs` job in CI takes 3-5m each run. Last run from master: https://github.com/commaai/openpilot/actions/runs/9454981147/job/26043750673

This can probably be done by caching the build results, but non-cache speedups are even better. `Build docs` step must finish in <30s for the average run to qualify for the bounty.

**Comment by dpeachpeach** [comment]
I took a crack at this in #32766, is that kind of what you were looking for? It's a bit simplistic and doesn't speed anything up in case there is a cache miss so I can work to find other ways of speeding the actual build as well. Any feedback welcome!

**Comment by adeebshihadeh** [comment]
Closing since we're entirely redoing the docs
