### ISSUE TITLE
Enforce using `python3` instead of `python`

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32761]
I'm trying out 24.04 where we want to be able to use the system python, but I'm hitting this:
```
adeeb:~$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
```

What do other projects do?

**Comment by BBBmau** [comment]
Looks like they opted out of including use/bin/python in 24.04

https://utcc.utoronto.ca/~cks/space/blog/python/Ubuntu2404PythonState

We could include a step in the setup to do some kind of aliasing

**Comment by adeebshihadeh** [comment]
That's not the problem here. AFAIK `python` is always supposed to be python2 (or at least ambiguous) and `python3` should be preferred. We used pyenv to make `python` always refer to our python install, however we want to drop the need for pyenv soon.

**Comment by AbhishekChaudharii** [comment]
Installing python-is-python3 package might solve your issue.
`sudo apt install python-is-python3`

The package includes a symbolic link that directs the `/usr/bin/python` interpreter to the current default python3 version.

**Comment by adeebshihadeh** [comment]
@maxime-desroches is this done?

**Comment by maxime-desroches** [comment]
@adeebshihadeh Yes

**Comment by adeebshihadeh** [comment]
Oh, weird still shows as open in the project view for some reason.

**Comment by maxime-desroches** [comment]
Yes, weird bug. I've tried many times to make it purple
