### ISSUE TITLE
Navigation pane not loading offroad or onroad

### ISSUE THREAD

**Issue by MarcoTheDingo** [commaai/openpilot#32781]
### Describe the bug

The navigation widget/pane is completely black on the offroad home screen after the June 18th master-ci build. When going onroad, tapping the screen just cycles between the status bar and full screen, no navigation 50/50 split.
Tried re-installing master-ci, same issue.
![PXL_20240618_121506447](https://github.com/commaai/openpilot/assets/1631602/d5165899-1975-45de-92d3-2e7b71534074)

### Provide a route where the issue occurs

5130484aa8069bad/00000006--564c06df19

### openpilot version

0.9.8 | master-ci | e4fcf42ada2206b8cd4d5c9927d8792c7701faa8

**Comment by eFiniLan** [comment]
@MarcoTheDingo Relevent:

https://github.com/commaai/openpilot/pull/32773/files

https://github.com/commaai/openpilot/blob/5c4ea14a3cb7bcb443fbee8c5b1d52c10788c9e8/selfdrive/ui/SConscript#L11

**Comment by adeebshihadeh** [comment]
#32773
