### ISSUE TITLE
[$100 bounty] Bring back macOS CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#32791]
We had macOS CI for a long time but it was hard to maintain, in part due to the package cache breaking all the time. Now that dependencies are down, let's see how fast it is without a package cache.

Just run `tools/mac_setup.sh` and `scons -h` after to make sure it vaguely worked. If that's fast enough to leave enabled on master, we can slowly bring back compiling openpilot, running tests, etc.

**Comment by adeebshihadeh** [comment]
I'm thinking just Apple Silicon.

**Comment by leomonde** [comment]
Sorry, I don't understand, issue is closed but after git pull I still get error compiling (scons -u -j$(nproc)) in OSX 14.5 or Ubuntu 22.04 or Ubuntu 24.04. Did I miss something?
My CPU is Apple Silicon (ARM M2), I run Ubuntu over Parallel VM. Thanks.

**Comment by adeebshihadeh** [comment]
macOS setup is run, but it doesn't build yet

**Comment by leomonde** [comment]
> macOS setup is run, but it doesn't build yet

Is there a way to build at least tools?
With Ubuntu in VM, neither 22 or 24, it doesn't even finish install. Is my CPU the problem?
