### ISSUE TITLE
Fingerprints CAN source

### ISSUE THREAD

**Issue by dzid26** [commaai/openpilot#328]
Is there a reason why fingerprints couldn't be searched on other CAN sources 0, **1**, **2** to make it more universal with OBD2. 
In OBD2 socket in some cars, the hardcoded CAN0 happens to be diagnostic-CAN, that only is required to have 0x130 message id, making it imposible to fingerprint.

**Comment by emmertex** [comment]
Fingerprinting from OBD2 isn't really the intention of the fingerprint.
If you are not intercepting the stock camera, meaning directly on that particular CAN bus, the fingerprinting process is basically pointless.

**Comment by pd0wm** [comment]
We also fingerprint on bus 1 now: https://github.com/commaai/openpilot/blob/devel/selfdrive/car/car_helpers.py#L82
