### ISSUE TITLE
ubuntu_setup.sh failure installing casadi (Ubuntu 24.04 and ARM M2 CPU)

### ISSUE THREAD

**Issue by leomonde** [commaai/openpilot#32809]
### Describe the bug

Installing casadi (3.6.5) Failed
ChefBuildError
Backend subprocess exited when trying to invoke build_wheel

### OS Version

Ubuntu 24.04 LTS

**Comment by leomonde** [comment]
Ubuntu 24.04 running in VM environment (Parallel)

**Comment by maxime-desroches** [comment]
We dropped support for arm macOS during the transition to python3.12/ubuntu24.04 and one of the reasons was casadi having problems building. An issue (https://github.com/commaai/openpilot/issues/32791) is open to bring it back.

**Comment by leomonde** [comment]
> We dropped support for arm macOS during the transition to python3.12/ubuntu24.04 and one of the reasons was casadi having problems building. An issue (https://github.com/commaai/openpilot/issues/32791) is open to bring it back.

I am not using MacOS.
I am using Ubuntu 24.04!

**Comment by athaarvv** [comment]
is there any resolution found for casadi issue ?

**Comment by leomonde** [comment]
> is there any resolution found for casadi issue ?

I don't know.
I tried to go back to commit cb63f10 (git reset), to use an old OP version in Ubuntu 22 but it didn't work.
Strange... as it used to work months ago.

**Comment by adeebshihadeh** [comment]
New casadi release is out which should fix this.
