### ISSUE TITLE
Overflow error for non-linear torque GM cars

### ISSUE THREAD

**Issue by twilsonco** [commaai/openpilot#32841]
### Describe the bug

When stationary, and specifically for Silverado, if the observed curvature is close to or less than `-1.0`, the resulting `low_speed_factor`-adjusted "measured" lateral acceleration can be high enough to cause an overflow error in the `sig` function defined at line 51 in gm/interface.py

This error was experienced by @not1454 on discord. Although he was running a fork at the time, the relevant code and call stack is identical to `master`.

```python
def sig(val):
  return 1 / (1 + exp(-val)) - 0.5
```

When the curvature is close to or less than `-1.0`, the measured lat accel is high enough that, after being multiplied by the non-linear torque parameter `a` (which is ~3.3), the `val` argument to `sig` will be less than `-710`, causing an overflow error when `exp(-val)` is evaluated.

Here's a screenshot of such an error (though not on master, the code is identical to the code in `master` in this regard. Line 65 here is identical to line 51 in the same file in `master`)
![image](https://github.com/commaai/openpilot/assets/7284371/27f8dc68-ba35-42da-803c-3bd718c60f6d)

One workaround for this could be:

```python
from math import expm1

def sig(val):
    if val < -709:
        return -0.5
    else:
        return 1 / (1 + expm1(-val)) - 0.5
```

### Which car does this affect?

Chevy Silverado

### Provide a route where the issue occurs

(can try to reproduce if requested)

### openpilot version

0.9.7

**Comment by sshane** [comment]
thanks for bringing this to our attention!
