### ISSUE TITLE
crash in car daemon results in confusing error

### ISSUE THREAD

**Issue by jyoung8607** [commaai/openpilot#32901]
### Describe the bug

While developing the Alfa Romeo port, I made an error which resulted in `card` crashing on startup.

Before `card` was introduced, when `controlsd` would crash at startup, you would see "waiting for controls to start". For any other service crash, there would be a Process Not Running alert.

With `controlsd` and `card` separated, when there is a crash in car port code, it's now manifesting as "CAN error: check connections".  This resulted in quite a lot of confusion and time spent troubleshooting by both myself and the Alfa Romeo owner.

It is desired that a `card` crash show a Process Not Running or similar more clear alert.

### Provide a route where the issue occurs

12b6b35de7477fcc/00000003--1af65ad310

### openpilot version

this week's master + a car port

**Comment by adeebshihadeh** [comment]
It's now "waiting for controls to start" and "process not running".
