### ISSUE TITLE
`ubuntu_setup.sh` is never actually used in docker container setup, but claims to be used for docker container setup

### ISSUE THREAD

**Issue by renxida** [commaai/openpilot#32915]
### Describe the bug

See: https://github.com/commaai/openpilot/blob/master/tools/ubuntu_setup.sh

### Provide a route where the issue occurs

https://github.com/commaai/openpilot/blob/master/tools/ubuntu_setup.sh

### openpilot version

HEAD

**Comment by maxime-desroches** [comment]
Not an issue
