### ISSUE TITLE
controlsd crash in capnp

### ISSUE THREAD

**Issue by jyoung8607** [commaai/openpilot#32928]
### Describe the bug

Experienced "Controls Unresponsive" immediate disable while engaged, after 2.5 hours of driving.

![image](https://github.com/commaai/openpilot/assets/46612682/cc8ae03f-d1ea-4b9d-9595-a40dbae9b345)

### Provide a route where the issue occurs

04836f13759962ab/0000005d--c45a20d978/155

### openpilot version

today's master + very mild specialsauce

### Additional info

I'm running a very small set of changes from master, but I can't think of how any of this could be related.

https://github.com/commaai/openpilot/compare/master...jyoung8607:openpilot:x-jy-temp

Won't have connectivity to upload rlogs right away.

**Comment by deanlee** [comment]
I don't think it has anything to do with your changes.  it appears to be a bug in the op itself. https://github.com/commaai/openpilot/pull/32929/files
