### ISSUE TITLE
docs: setup glossary 

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#33117]
This bounty is for both setting up the glossary infrastructure and populating it with most openpilot terms.

Requirements:
* a master definition file
* "glossary page" under the concepts section
* nice to have: click or hover on words defined in the glossary to get the definition on any docs.comma.ai page. bounty value doubles if this is done

wiki has a good starting point on definitions: https://github.com/commaai/openpilot/wiki/General-Terms

**Comment by mawutory** [comment]
hi @adeebshihadeh want to take this up. please can you provide more details?

**Comment by devSuryansh** [comment]
Hey @adeebshihadeh,
I'd like to work on this issue. Could you please assign this issue to me?

**Comment by mawutory** [comment]
@devSuryansh you're free to work on it.

**Comment by Pious1020** [comment]
hey, is the bounty for this still open?

**Comment by dupelx** [comment]
hey can i work on this issue?

**Comment by dupelx** [comment]
@adeebshihadeh ?

**Comment by LouisVelez** [comment]
@adeebshihadeh whenever you have a chance please let me know if this meets your requirements #34155
