### ISSUE TITLE
Replace `pre-commit` with something fast

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#33173]
pre-commit is super slow, doesn't exactly match CI on my machine (what does the slowness get me?), and I've found myself fighting with its config on a few occasions. And sometimes it even corrupts my git repo.

I'm thinking something like `op` that runs ruff, mypy, etc. Something you don't want to `git commit -n`.

Essentials to start, rest can be added later:
* ruff
* codespell
* import-linter? maybe @sshane can just run this locally?

**Comment by maxime-desroches** [comment]
Turns out that codespell was never configured correctly (ironically a typo) in the pre-commit-config.yaml and only ran against 2 dictionaries instead of the 7 specified. It now flags 400+ "errors"

**Comment by maxime-desroches** [comment]
@sshane Still have to add an actual pre-commit hook using the new `lint.sh`
