### ISSUE TITLE
CI: test building without cache/random order

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#33201]
Fails on master: https://github.com/commaai/openpilot/actions/runs/10260839111/job/28387533467

I suppose everything but common had msgq/cereal dependencies, when I [changed params](https://github.com/commaai/openpilot/commit/87c6afccf71788ba58685f43d967290816d4dfbf) it caused it to be rebuilt, possibly before it had gotten msgq from cache.

Broken since e71ec4e8d7e39a56235f590227e7cb361cd8b79d

**Comment by adeebshihadeh** [comment]
This test was too slow and flaky. We need to get build times down before bringing this back.
