### ISSUE TITLE
Coma ai Device disconnected from my account 

### ISSUE THREAD

**Issue by Deivis1298** [commaai/openpilot#33228]
### Describe the bug

Coma ai Device disconnected from my account , can't connect it back Deivis12982011@gmail.com

### Provide a route where the issue occurs

All the time 

### openpilot version

0.9.7

### Additional info

Coma ai Device disconnected from my account , can't connect it back Deivis12982011@gmail.com

**Comment by sshane** [comment]
Please contact support for this request at https://comma.ai/support

Make sure to tell them your device's dongle ID (found in Device settings)

**Comment by Deivis1298** [comment]
How can I reconnect the comma 3 to a new account
