### ISSUE TITLE
`sudo systemctl restart comma` frozen

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#33224]
### Describe the bug

`sudo systemctl restart comma` doesn't restart openpilot successfully, freezes here..

```
waiting for weston
weston ready after 0s
ln: failed to create symbolic link '/home/comma/.vscode-server/vscode-server': File exists
Valid overlay update found, installing
Restarting launch script /data/openpilot/launch_chffrplus.sh
Using Wayland-EGL
qt.qpa.wayland: "wl-shell" is a deprecated shell extension, prefer using "xdg-shell-v6" or "xdg-shell" if supported by the compositor by setting the environment variable QT_WAYLAND_SHELL_INTEGRATION
Using the 'wl-shell' shell integration
```

after running the following, op completes "boot" with `scons: done building targets.`

`echo "894000.i2c" | sudo tee /sys/bus/platform/drivers/i2c_geni/unbind && echo "894000.i2c" | sudo tee /sys/bus/platform/drivers/i2c_geni/bind`

but another `sudo systemctl restart comma` and the home screen loads but isn't responsive and goes blank after a while

`tmux kill-session -t comma; rm -f /tmp/safe_staging_overlay.lock; tmux new -s comma -d "/data/openpilot/launch_openpilot.sh"` used to always work

### openpilot version

master

**Comment by adeebshihadeh** [comment]
That service isn't intended to be restarted, see here: https://github.com/commaai/agnos-builder/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aclosed+restart
