### ISSUE TITLE
Automatic Windshield Wipers Toyota Corolla Hybrid ($150 reward) 

### ISSUE THREAD

**Issue by qf0** [commaai/openpilot#33313]
Using the Comma 3x camera, I would like a feature to automatically turn on my cars (Toyota Corolla Hybrid 22) windshield wipers when it detects rain via can messages. I'm willing to pay $150 as a reward.

**Comment by adeebshihadeh** [comment]
This isn't a bug - check out our [Discord](https://discord.comma.ai) instead.
