### ISSUE TITLE
Plotjuggler --can not looking in dbc folder for dbc files

### ISSUE THREAD

**Issue by garrettpall** [commaai/openpilot#33330]
### Describe the bug

When loading a route with plotjuggler, no dbc are shown on the lastest master unless they are copied into the higher level folder for opendbc.

### Provide a route where the issue occurs

N/A

### openpilot version

master

**Comment by garrettpall** [comment]
<img width="162" alt="Screenshot 2024-08-19 at 7 10 53 PM" src="https://github.com/user-attachments/assets/91274096-ca01-4dff-be32-d68bac6d28ff">

**Comment by sshane** [comment]
Is this WSL? Make sure the symlink is properly created for opendbc to opendbc_repo/opendbc

**Comment by garrettpall** [comment]
> Is this WSL? Make sure the symlink is properly created for opendbc to opendbc_repo/opendbc

Ubuntu 20.04 on a VM. If it’s just a me issue I’ll work around it

**Comment by sshane** [comment]
Also try to update PJ with ./juggle.py --install, this fixed it for incognitojam
