### ISSUE TITLE
ui: add comparison against master to screenshotter

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#33430]
All we want here is to say either "MATCHES" or "DOESN'T MATCH" next to each screenshot: https://github.com/commaai/openpilot/pull/33429#issuecomment-2323431303.

When it doesn't match, it would also be nice to show the baseline image and a pixel diff.

I'm thinking we do this by pushing a master reference to https://github.com/commaai/ci-artifacts on all pushes to master.

**Comment by deanlee** [comment]
How about calc the pixel differences using PIL's ImageChops.difference()? Then Highlight the differences by creating a mask and overlaying a specific color (like red in this example) onto the original image. which shows the original with highlighted differences.

This approach relies solely on PIL, without needing additional libraries like OpenCV etc.

Example:

| master  | pr |
| ------------- | ------------- |
| ![onroad](https://github.com/user-attachments/assets/cd9dd54d-01e4-4741-a2df-044788be366e)  | ![onroad2](https://github.com/user-attachments/assets/625708a4-babd-4877-ba5f-b79245a17bb0)  |

the diff
![diff_image](https://github.com/user-attachments/assets/550ae2ee-ce8f-4c9e-ae46-962bc2d0051a)
