### ISSUE TITLE
Cannot download dash cam or autopilot 

### ISSUE THREAD

**Issue by Tomer27385** [commaai/openpilot#33450]
### Describe the bug

I changed cars And moved my, AI from a Toyota Prius to my Ford Maverick with 360 Co-Pilot system 

I I did a hard reset to my coma AI 
And now I cannot download the software again 

I tried to do it only on dash cam mode and it does not download the dash cam mode. It just restarting itself again and again 

I tried also to download the autopilot with the, comma  AI URL 
And it does a similar problem

Before I changed a vehicle, indeed the reset everything was working perfectly

### Provide a route where the issue occurs

Ghccc

### openpilot version

Nothing at the moment 

### Additional info

Your requested to provide a route where the issue is occurs and dongle ID 

But the device does not provide anything 
I have no idea. No routes 

Please assist. I can also mail it to you

**Comment by adeebshihadeh** [comment]
Check out our [Discord](https://discord.comma.ai) help getting started.
