### ISSUE TITLE
CAN bus disconnected: Likely faulty cable on supported and recommended Toyota Corolla Hybrid LE 22

### ISSUE THREAD

**Issue by qf0** [commaai/openpilot#33484]
### Describe the bug

I randomly have started to get this issue, and LKA/headlights malfunctions errors on my dashboard starts popping up. I drove across country (900+ miles) which went fine and then it just started randomly giving me this error. I've tried replugging everything and even pulled the OBD port out. Also, yes I tried inserting the USB C Cable twice in different ways. It started to work for a few minute drive, then reoccured. I've been unable to use openpilot for over a week and it's annoying. I've reached out to support, and they said the engineering team is looking in to it, but just posting on GitHub so maybe others can report similar experiences.

### Which car does this affect?

Toyota Corolla Hybrid LE 22

### Provide a route where the issue occurs

089df2428c0645bf/00000004--b2fc92cf01/2

### openpilot version

0.9.7

**Comment by adeebshihadeh** [comment]
Gonna close since ti's being handled in support. They should get back to you soon.

@lukasloetkolben has one on a desk and is root causing it!
