### ISSUE TITLE
Add 2024 Dodge Durango

### ISSUE THREAD

**Issue by streis** [commaai/openpilot#33546]
Request for 2023/2024 Dodge Durango to be added.   I've attached a comma 3x that I moved from a 2020 Grand Cherokee and it functions well in the 2024 Durango, same cable.   How can I contribute to incorporate this model year?

**Comment by adeebshihadeh** [comment]
Closing as this isn't a bug - check out the #chrysler channel in [Discord](https://discord.comma.ai).
