### ISSUE TITLE
QSocketNotifier: Can only be used with threads started with QThread

### ISSUE THREAD

**Issue by zhengyb** [commaai/openpilot#33547]
### Describe the bug

I am running openpilot on Ubuntu24.04.01 in Virtual Box.  There is a warning/error after starting the ui command:

```
/selfdrive/ui/ui 
: QSocketNotifier: Can only be used with threads started with QThread
```

Does anyone know how to fix it?

### OS Version

Ubuntu 24.04

**Comment by adeebshihadeh** [comment]
Doesn't look like this affects anything?
