### ISSUE TITLE
update sentry implementation to 2.x

### ISSUE THREAD

**Issue by andiradulescu** [commaai/openpilot#33573]
```
Manager failed to start
Traceback (most recent call last):
  File "/data/openpilot/system/manager/manager.py", line 208, in ‹module>
    main()
  File "/data/openpilot/system/manager/manager.py", line 177, in main
    manager_init()
  File "/data/openpilot/system/manager/manager.py", line 88, in manager_ init
    sentry. init(sentry.SentryProject.SELFDRIVE)
  File "/data/pythonpath/openpilot/system/sentry.py", line 76, in init
    sentry_sdk.Hub.current.start_session()
  File "/usr/local/venv/lib/python3.12/site-packages/sentry_sdk/hub.py", line 100, in current 
    warnings.warn(SentryHubDeprecationWarning(), stacklevel=2)
sentry_sdk. hub.SentryHubDeprecationWarning: sentry_sdk. Hub is deprecated and will be removed in a future https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
```

`sentry-sdk` got updated to `2.x` so the sentry implementation needs to be updated - I traced `sentry-sdk` in openpilot as back as moving to uv (still `2.x` then).

I couldn't straight figure out what this [line](https://github.com/commaai/openpilot/blob/23716986011814e4ef1c4ea72c5e2d2afc8184b0/system/sentry.py#L76) is doing or better said how should it be migrated to [2.x](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x) - since it's not cloning the hub as stated [here](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#activating-current-hub-clone).

The deprecated [function](https://github.com/getsentry/sentry-python/blob/4f6ccc45af0e0cc0a09f3b38c76f02b49e469feb/sentry_sdk/hub.py#L600) does this:
```
    def start_session(self, session_mode="application"):
        get_isolation_scope().start_session(
            session_mode=session_mode,
        )
```

Compared to sentry [1.x](https://github.com/getsentry/sentry-python/blob/282b8f7fae3da3c3ec26e5ee5e1599fc74661a72/sentry_sdk/hub.py#L619):
```
    def start_session(self, session_mode="application"):
        client, scope = self._stack[-1]
        scope.start_session(
            client=client,
            session_mode=session_mode,
        )
```

**Comment by adeebshihadeh** [comment]
7aa4ef5fd6b293e52a125101dc774da73fcbd57d
