### ISSUE TITLE
Failed to create specified HW device

### ISSUE THREAD

**Issue by zhengyb** [commaai/openpilot#33572]
### Describe the bug

I run openpilot on a Ubuntu PC with Navida GPU. When I run the 'replay' command, there is a log like this:

  │Seeking to 0 s, segment 0                                                                                                                                                         │
  │loading segment 0...                                                                                                                                                              │
  │Failed to create specified HW device -542398533.                                                                                                                                  
  │
  │No device with hardware decoder found. fallback to CPU decoding.                                                                                                                  
  │
  │loading segment 1...                                                                                                                                                              │
  │merge segments 0                                                                                                                                                                  │
  │camera[0] frame size 1928x1208                                                                                                                                                    │
  │loading segment 2...r: camerad                                                                                                                                                    │
  │merge segments 0, 1                                                                                                                                                               │
  │loading segment 3...                                                                                                                                                              │
  │merge segments 0, 1, 2                                                                                                                                                            │
  │loading segment 4...                                                                                                                                                              │
  │merge segments 0, 1, 2, 3                                                                                                                                                         │
  │merge segments 0, 1, 2, 3, 4                                                                                                                                                      │
  │                            

Does anyone can help me?

### OS Version

Ubuntu 24.04

**Comment by adeebshihadeh** [comment]
Check out our [Discord](https://discord.comma.ai) for help getting started.
