### ISSUE TITLE
Enhanced longitudinal support for ioniq 6 and other HKG CAN-FD vehicles

### ISSUE THREAD

**Issue by apar509** [commaai/openpilot#33730]
Longitudinal open pilot support for ioniq 6 and other HKG CAN-FD vehicles that utilize the radar or at the very least doesn't disable FCW/AEB when enabling longitudinal control on open-pilot. Currently vision only adaptive cruise control is possible on the vehicles but at the cost of key safety functionality native to the vehicle.

**Comment by jyoung8607** [comment]
This isn't a bug - feature requests can be discussed in the community discord.
