### ISSUE TITLE
CAN Bus Disconnected. Likely Faulty Cable

### ISSUE THREAD

**Issue by BriungRi** [commaai/openpilot#33754]
### Describe the bug

I drive a 2023 Toyota RAV4. I had no problems with the unit on my first two trips. Then, during one of my trips, I received this error. Now I consistently get this error when I start up my car / openpilot. I also get car lights on (collision detection and LTA disables)

When I start up my car without the comma device plugged in but with the harness attached, I do not get these warning lights.

### Which car does this affect?

Toyota RAV4 2023

### Provide a route where the issue occurs

299aeca224cb4172/00000009--e1ed06b726/16

### openpilot version

0.9.7

**Comment by adeebshihadeh** [comment]
Open a ticket at comma.ai/support and we'll take care of it there.
