### ISSUE TITLE
Developer panel in settings

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#33800]
This should make it super easy to run the new longitudinal maneuver report and joystick mode.

It should have:
* SSH key setting (move from the Network tab)
* [Joystick mode](https://github.com/commaai/openpilot/tree/master/tools/joystick)
* [longitudinal maneuver report mode](https://github.com/commaai/openpilot/tree/master/tools/longitudinal_maneuvers)

Joystick and longitudinal maneuvers should be hidden on release branches.

**Comment by jyoung8607** [comment]
* Start and stop ZMQ bridge

**Comment by adeebshihadeh** [comment]
We should also think about moving the "openpilot long alpha" toggle. I'm leaning towards moving it.

**Comment by AarjavPatni** [comment]
Should the joystick mode provide an option for the user to choose between comma and laptop? Or should it detect whether the comma is plugged in?

I'm not sure how that should look like. A description would be great.

**Comment by AarjavPatni** [comment]
@adeebshihadeh Are we adding the option to start and stop ZMQ bridge or is it TBD? What about the "openpilot long alpha" toggle?

**Comment by adeebshihadeh** [comment]
Ah yeah, let's move that one too. @BBBmau or @AlexandreSato want to move that?

**Comment by AlexandreSato** [comment]
> Ah yeah, let's move that one too. @BBBmau or @AlexandreSato want to move that?

moved in #33885

**Comment by AlexandreSato** [comment]
@adeebshihadeh 

#33885 Also fix two design issues in #33803 :
1 - the release toggles would only disappear after ignition on the release branch;
2 - cars without longitudinal control could activate longitudinal maneuvers.
