### ISSUE TITLE
[AGNOS] Downgrading from 11 is not possible without reflash

### ISSUE THREAD

**Issue by coffee-cake-isaac** [commaai/openpilot#33811]
### Describe the bug

1. Have any version of AGNOS 10 installed (release3 suggested)
2. Upgrade to AGNOS 11 using latest master or master-ci)
3. Perform the AGNOS 11 Upgrade when prompted after install
4. Restart your Comma device
5. During reboot, tap on the Comma logo to trigger a reset
6. Confirm the reset
7. After finished resetting, attempt to install openpilot again using Option 1 from the "openpilot" or "Custom Software" buttons
8. Notice that the device hangs here and requires a reflash

### Provide a route where the issue occurs

Dongle ID: 112e4d6e0cad05e1

### openpilot version

0.9.8

**Comment by jyoung8607** [comment]
As described, that doesn't sound like a downgrade issue, more like the downloaded installer won't run on AGNOS 11.

Try to SSH in with the default key after the WiFi connection step, there may be something interesting visible in tmux.

**Comment by adeebshihadeh** [comment]
No need, already repro'd.
