### ISSUE TITLE
Refactor tools/replay: Eliminate Qt Dependency 

### ISSUE THREAD

**Issue by deanlee** [commaai/openpilot#33813]
Refactors the tools/replay to eliminate its dependency on the Qt framework, making the tool lighter and more portable.

- [x] #33812
- [ ] Replace HttpRequest with a libcurl implementation to load route info from https://api.commadotai.com/.
- [ ] Remove the use of Qt's signal/slot mechanism and replace it with standard C++ function callbacks.
- [ ] Replace QThread with std::thread to manage threading in a platform-independent way.
- [ ] Replace Qt-specific data types (QString, QVector, etc.) with standard C++ data types (std::string, std::vector, etc.).
- [ ] Update Cabana to use callback functions from Replay instead of relying on Replay's signals.

**Comment by maxime-desroches** [comment]
Oh sorry I didn't realize that I closed this by accident!

**Comment by deanlee** [comment]
:D I made the connection by accident.
