### ISSUE TITLE
DISTORTION PARAMETER for WideView camera

### ISSUE THREAD

**Issue by git-sachin1066** [commaai/openpilot#33874]
Hi, if anyone have the distortion parameter of wideview camera , such that i ammlooking forward to convert  fisheye images into a format similar to standard perspective image.
I assume the intrinsic matrix for the wideView camera is : 

```

  tici_ecam_intrinsics = {{620.0, 0.0, 1928.0 / 2,​

                                          0.0, 620.0, 1208.0 / 2,​

                                          0.0, 0.0, 1.0}}; 
``` 

_source : https://github.com/commaai/openpilot/pull/22238/commits/1da419b67f8b2e1360f1c0d7ec02624d80bed3d4​_

**Comment by adeebshihadeh** [comment]
Closing as this isn't a bug - check out our [Discord](https://discord.comma.ai) instead.
