### ISSUE TITLE
allow user-provided upload buckets, with or without Prime

### ISSUE THREAD

**Issue by mdaniel** [commaai/openpilot#33873]
Currently, it uploads to `upload.commadotai.com` and I believe the retention of that data is determined by the Prime status of the account

The desired outcome would be to allow the user to provide their own cloud storage coordinates (e.g. `(provider, bucket, optionalPrefix, credential+)`) to allow routes to be persisted within their own data boundary (which necessarily would include their own retention settings -- that is, the uploader would not deal with route/data GC, since that's one extra bit of complexity and an opportunity for bugs/misunderstandings)

I am open to leaving the existing upload.commadotai process in place, since it doesn't bother me if Comma _also_ has the routes (moar training, moar better, I guess) but it would make me much happier if I ultimately had ownership over the recording and data from my routes

I wanted to open an issue about this before I started typing to implement it in case (a) it's already been discussed and rejected and my search-fu just didn't find it (b) it _will_ be rejected (c) there are considerations that would make the PR more likely to land

In my _specific_ case I would want to target Backblaze B2 (which is in the family of "honors the AWS S3 API") but I believe Comma uses Azure, so I'm also open to starting with just "provide your own Blob Storage and credentials" and expand out from there if it would be more readily accepted

Since I'm guessing the audience who would care about this kind of thing are likely to be pretty tech savvy, I'm also guessing this change will not to carry a UI element, rather something they would do by toggling on "SSH access" and monkeying with a file in their filesystem

I've also thought about just cross-compiling rclone and calling it done, which is what I suspect will happen if the issue gets closed as "wontfix"

**Comment by adeebshihadeh** [comment]
This isn't something we will implement, though we would consider (minimal) PRs to refactor things towards this.

Some community forks support an alternate backend that can be pointed to through the `API_HOST` environment variable.
 https://github.com/commaai/openpilot/blob/1570aa79610bd26bad06286fd085113db8695e27/common/api/__init__.py#L8
