### ISSUE TITLE
Did we stop doing release tags?

### ISSUE THREAD

**Issue by jfrux** [commaai/openpilot#339]
The reason I ask is because I'm using GitHub API to track releases and things on https://database.opc.ai/ and I'm not seeing 5.1 or 5.2 so I checked here and they do appear to be missing.

Just curious...

**Comment by ch4se** [comment]
Looks like they missed adding the release tags since 5.0

**Comment by jfrux** [comment]
No? Nothing? Still trying to ensure I'm properly tracking versions for opc.ai.
I want to ensure that Guides, Comments, etc, are relative to the version at that time and allow us to maintain what guides still are relevant to particular versions but I want to also know what versions have been pushed to release2.

Tags is generally how this is done but tags are missing since 0.5.

**Comment by jfrux** [comment]
Nope, cool... just was curious! Thx for the info. 🥇🤣❤️

**Comment by energee** [comment]
If you want tags for opdb, energee repo has release tags 👍

**Comment by kmacpher67** [comment]
Why doesn't the main comma.ai repo have Release tags/branches anymore?
Isn't there a release build script that does this automatically?
Are the test failing and the release tag is not getting cut?
Idk enough about this project pipeline process, but who is that controls those decisions?
Is there an architecture or devops review committee/team for these things?

**Comment by jfrux** [comment]
lol

**Comment by vanillagorillaa** [comment]
Release Tags are back! all releases in release2 are tagged and will be tagged from now on with each release!

**Comment by jfrux** [comment]
It’s so sexy when you talk taggy to me.
