### ISSUE TITLE
Options spacing wrong on release branches

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#34000]
See the spacing for the options in Settings and Developer

![PXL_20241112_210752706](https://github.com/user-attachments/assets/d38c47c6-7761-4f8b-821a-88a125d5cddd)
![PXL_20241112_210730296](https://github.com/user-attachments/assets/07ca183a-d755-4c58-9ba6-04fafa9e3691)

**Comment by AlexandreSato** [comment]
> @AlexandreSato want to fix the developer panel?

I tried but I couldn't, but a strange thing happens lol, if I add another toggle the spacing is correct.

**Comment by AlexandreSato** [comment]
> is it relying on stretch for the sizing?

I tried killing the automatic mechanic and also forcing a fixed size, but none of the attempts worked.

**Comment by AlexandreSato** [comment]
The non-release toggles only disappeared after an onroad transition, right? I fixed this in the alphalong toogle PR as well. Cars without longitudinal are also able to activate the longManeuver. I also corrected this in the PR on alphalong toggle
