### ISSUE TITLE
Recording a drive cycle and "playing it back"

### ISSUE THREAD

**Issue by tadasvip** [commaai/openpilot#34068]
Hi, we have Toyota RAV4 Hybrid 2017 on the dyno packs and we want to record the driving cycle (different car speeds and time, no need of self driving). After that, we would like to "play it back" to the same car as speed setpoints of cruise control (same speeds at same times). Would this be possible with Comma setup we already have? The idea is to run the same driving cycle over again for the scientific research of fuel consumption.

Could anybody tell us if it is possible to achieve using our setup? I attach a photo of what we have.

![Panda RED](https://github.com/user-attachments/assets/5816071e-4959-4bc0-aee2-833731cf27a3)

**Comment by adeebshihadeh** [comment]
Closing as this isn't a bug - check out our [Discord](https://discord.comma.ai) instead.
