### ISSUE TITLE
openpilot wanted to steer max left after high curvature at low speeds 

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#34128]
Toyota angle offset bug? Persisted for about a minute

https://connect.comma.ai/6483a59cd49b6650/000000c6--3f756b2b70/8415/8643

**Comment by haraschax** [comment]
This is because the NP model outputs massive curvatures at low speed and then the jerk clipping keeps that curvature super high in controlsd. Fixed with: https://github.com/commaai/openpilot/pull/34111/commits/ffa96c61b65bd61cdcc54bca2fdeae94fe1c35c8
