### ISSUE TITLE
Raylib precompiled x86 library doesn't work on 20.04

### ISSUE THREAD

**Issue by robbederks** [commaai/openpilot#34144]
### Describe the bug

The version in the repo now doesn't work with the old glibc in 20.04. Compilation was fixed by running the `setup.sh`, but wasn't immediately obvious.
Any way we can check in a version compiled with an older version or compile dynamically?

### OS Version

Ubuntu 20.04

**Comment by maxime-desroches** [comment]
I disabled the build of raylib for focal in https://github.com/commaai/openpilot/pull/34150 since we plan on dropping support for it as soon as possible
