### ISSUE TITLE
WSL2 Ubuntu webcam support broken

### ISSUE THREAD

**Issue by MikeBusuttil** [commaai/openpilot#34216]
### Describe the bug

Note: Depends on #34215

When running openpilot with webcam support and previewing the driver camera, the camera fails to stream (see [bottom image](https://github.com/user-attachments/assets/034e96ec-001c-4c54-b3cb-5053668b9180)).

We would expect to see `opening driverCameraState at /dev/video2` and `Starting listener for: camerad` in the console but instead it appears to get stuck at `opening roadCameraState at /dev/video0`

### Reproduction steps:
```
git clone git@github.com:MikeBusuttil/openpilot.git
git checkout dehack-webcam
ROAD_CAM=4 DRIVER_CAM=2 system/manager/manager.py
```
Note: your camera numbers may differ from mine

### Here it is working as expected on native Ubuntu 24.04
![Screenshot from 2024-12-11 22-03-35](https://github.com/user-attachments/assets/2081f2e4-b844-4e04-bd8e-ebc3e06f0b8b)

### Here it is failing to work onUbuntu 24.04 WSL2
![image](https://github.com/user-attachments/assets/034e96ec-001c-4c54-b3cb-5053668b9180)

### OS Version

Ubuntu 24.04 (WSL2)

**Comment by jyoung8607** [comment]
This isn't a bug. There was never "support" for webcam mode on WSL2.

**Comment by MikeBusuttil** [comment]
![Untitled-1](https://github.com/user-attachments/assets/426841bf-3d6f-4a8e-be97-cdeee47787cf)

**Comment by andiradulescu** [comment]
Webcam in WSL2 should work with: https://askubuntu.com/questions/1405903/capturing-webcam-video-with-opencv-in-wsl2
