### ISSUE TITLE
fingerprint

### ISSUE THREAD

**Issue by thabet33** [commaai/openpilot#34222]
### Describe the bug

i folowed the steps in https://github.com/commaai/openpilot/wiki/Fingerprinting#fingerprinting-20 
to fingerprint my santafe but icant edit file on opendbc_repo/opendbc/car/<car make> because the opendbc_repo is another repo can you help please

**Comment by adeebshihadeh** [comment]
Closing as this isn't a bug - check out our [Discord](https://discord.comma.ai) instead.
