### ISSUE TITLE
3X doesn't connect to first-time connections until rebooted

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#34271]
This is because the time to add the connection takes ~2s, so our dbus `call` method times out in 0.1s and doesn't save it as a connection. We can fix this by first saving it to memory `save no`, then write it out later by using the `Save` method. This does take 0.2s though, so we'll want to raise the dbus timeout a bit.

@deanlee this should be a pretty simple fix if you want to do it!

**Comment by sshane** [comment]
Actually an issue for normally connecting to APs too

**Comment by sshane** [comment]
That sounds like a separate change we can evaluate later. This should be a ~4 line change

**Comment by deanlee** [comment]
The two-step approach of calling AddConnectionUnsaved, followed by the Save() method on the returned connection object, can still result in timeout issues, particularly depending on the configured timeout settings.
A better solution is to use asyncCall to handle these operations asynchronously. This approach ensures the UI remains responsive, as it doesn’t block while waiting for the operation to complete. By doing so, we can avoid timeouts while still successfully saving the connection: https://github.com/commaai/openpilot/pull/34273

**Comment by sshane** [comment]
cant repro the general connection issue, only tethering. fixed by https://github.com/commaai/openpilot/pull/34274
