### ISSUE TITLE
Brake sounds on some cars with comma pedal and sometimes even with Stock

### ISSUE THREAD

**Issue by jfrux** [commaai/openpilot#344]
Tried to dig into it but cannot figure it out.
In my video below I engage and disengage without moving the vehicle.  It's a very isolated test case so we can see the brake signals engage and disengage when I press the brake pedal it freaks out so I'm trying to figure out how to eliminate or at least lower this "freak out".  The brakes feel a lot like ABS or something but I've been told its all the same so maybe its fixable if given the right clean data.

If anyone needs me to try something specific to make it clearer to see maybe let me know.

https://www.youtube.com/watch?v=mT6aB_OZHs8

Cabana:
https://community.comma.ai/cabana/?route=0812e2149c1b5609|2018-08-28--21-15-17

I thought we used to be able to share queued up links but it seems to not do that anymore.
The specific time it is at when I test it from the YouTube video is at `21:39:17 - 21:42:17`.

![image](https://user-images.githubusercontent.com/171077/44961231-b571b900-aedb-11e8-86b2-4b5ff048b169.png)

![image](https://user-images.githubusercontent.com/171077/44961290-f918f280-aedc-11e8-8a63-d68961ff9987.png)

**Comment by jfrux** [comment]
Been happening since like v0.4.6 which is when I got pedal but not sure if it existed before then obviously.

**Comment by jfrux** [comment]
This is the share link from cabana:
https://community.comma.ai/cabana/?route=0812e2149c1b5609%7C2018-08-28--21-15-17&max=27&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F0812e2149c1b5609%2F385d313ffa52569aabd4857acbb0b32e_2018-08-28--21-15-17

Skip to the very last segment: `21:39:17 - 21:42:17`

**Comment by shameed123** [comment]
I have seen hard brake pedal even without pedal.  I've noticed it mostly when OP decides to hard brake (due to a car close up front for exampel) and I also brake at the same time.  It disengages it but brake pedal feels very hard.  I have to let it go and then brake again to get a softer brake.  It might be related.

**Comment by bugsy924** [comment]
That's because the brake pump pressurized the brake lines and you're pushing against that already built up pressure.
The same thing should happen with stock ACC

**Comment by jfrux** [comment]
That’s the thing… it doesn’t.

Honda stock system disengages quickly and painlessly.
When Honda is braking, if I brake its smooth and disengages and the pedal pressure feels natural.

With OP + Pedal stop and go anytime I touch brake while OP is braking it gives me a tiny bit of grind.  Way worse when at a full stop obviously.

**Comment by jfrux** [comment]
Although it's difficult for me to admit... and quite embarrassing... it must be said...  
The car does this exact thing when in stock setup.  It has been so long since I had used the stock system I sadly made a terrible assumption that it had something to do with Pedal or Openpilot.  I have even been quoted in saying "IT DOESN'T DO THIS WITH REGULAR OPENPILOT, JUST WHILE PEDAL IS PLUGGED IN".  

So if you no longer believe a word I say... I'm okay with that.

And for all of this, I apologize.

Everyone at Comma probably going `smh` right now... and if they aren't... its because they are ignoring me all together which is wise.

Although I don't fully understand the hardware (shock that I don't understand something yet I continue to speak in definitives), I'm guessing it's a physical issue that cannot be addressed by hacking CAN messages so I suppose maybe we should just close this?

Vote to close? Yay or nay?

**Comment by vanillagorillaa** [comment]
This should be resolved with 0.5.6, @jfrux closing this but reopen if you need to
