### ISSUE TITLE
2016 Honda Pilot Touring with LKAS and ACC

### ISSUE THREAD

**Issue by Compnerd01** [commaai/openpilot#365]
I have a 2016 Honda Pilot Touring with LKAS and ACC (Honda Sensing pkg). I do not see this on the supported vehicle list. What is the issue with the 2016 Pilot?

**Comment by jfrux** [comment]
It’s just not tested I don’t think but it should be fine...
Check https://opc.ai/vehicles/2016-honda-pilot-e24fbo#!tab-trim_styles

**Comment by ballerabdude** [comment]
I was able to get this tested on a 2016 model it works. We can close this. @Compnerd01

**Comment by energee** [comment]
Actually was just merged!
