### ISSUE TITLE
Where is the code that detects road lines?

### ISSUE THREAD

**Issue by sadboigang** [commaai/openpilot#432]
Where is the code that detects road lines?

Thank you,
G

**Comment by tegk** [comment]
There is no code as this happens in visiond which utilises a neural network. Further more its not clear how exactly they are detecting road lines and if they are used for the actual planning of of driving path.

**Comment by sadboigang** [comment]
Thank you so much for your answer! 
G

**Comment by brubakerjeff** [comment]
There is some information here https://youtu.be/lM2_E2y4eCg?t=486
