### ISSUE TITLE
OpenPilot for BMW's

### ISSUE THREAD

**Issue by kaeferfreund** [commaai/openpilot#44]
Hey George,

I love to see what you are doing here and I'd wish to try the system. But at my place we only got BMW's. These also have radar-sensors and adaptive cruise control.

What is needed to add a BMW Port to open pilot?
I could do a can-log/-dump for you on F10, F20 (LCI) and other models, if that helps...

**Comment by geohot** [comment]
It would take a bit of engineering. It's very doable by an outside party given what we've released.

**Comment by derek99401** [comment]
I got a F32, the car's can msg from ODBII port (using Panda) only gives heartbeat message with msg ID 0:130. Some research online shows that you have to tap into other port in order to get more useful data stream.

**Comment by triscb82** [comment]
I have a fully loaded G30 along with all the technical documentation.  I am looking for someone who has programming knowledge to help me get OpenPilot running on it.  Who’s game??

**Comment by greutair** [comment]
Would it be working with the BMW i3 not having built in a radar?

**Comment by jfrux** [comment]
You can lookup the current “status” of any given vehicle year, make, model, trim at https://opc.ai/lookup

**Comment by MrQwertyDude07** [comment]
Hello! Would this work on a fully loaded 2021 BMW Z4

**Comment by kaeferfreund** [comment]
I found the latest BMW ADAS with iStep 03/2021 to be very close to open pilot in regards of lane keeping + there are more functions e.g. reading the speed signs and using that as the acc set speed

@geohot try the latest BMW ADAS (I know, its mobileye) but since the 03/2021 OTA update (yes they update the whole car!) it really made OP a lot less attractive :/

**Comment by triscb82** [comment]
This got abandoned due to significant issues supporting FlexRay.  The
industry has abandoned the protocol but getting the DBC’s for the vehicles
has proven to be near impossible.  The key guy I had working on the project
fell off the face of the earth and we ran out of funding and resources.  I
honestly don’t see any flexray vehicle being supported.  I was super
optimistic and excited but have utterly lost hope due to there being so
many variables in reliably being able to talk on the flexray bus.

**Comment by Pecacheu** [comment]
Ah, I see. I honestly didn't know that all modern cars don't use CANBUS. So I take it from Wikipedia, FlexRay is an alternative protocol that some vehicles used to use, including BMWs. I was able to find [this rather relevant thread](https://www.mybmwi3.com/forum/viewtopic.php?t=16472) just form a search for 'FlexRay BMW', actually.

And yeah, that sucks. Something tells me you can't just go out and buy an Arduino shield for this like you can with CANBUS (in fact I already have one, as I mentioned). I couldn't find any shields in a quick search, though I did find mention of a a FlexRay library, and [whatever the heck this is](https://www.aliexpress.com/item/32912039329.html).

**Comment by Pecacheu** [comment]
If anyone has any info on FlexRay development, I could give a crack at it. I don't think an Arduino has enough CPU power to handle the throughput, but a Raspberry Pi surely should. But I can find little info about the protocol or adapters available. And without the ability to use software like SAVVYCAN, reverse engineering might be difficult. Honestly, I almost just want to rip the car apart and hook wires straight up to the power steering motor.

On the plus side, folks in the i3 development Discord have figured out the steering angle sensor and some other sensors available on the CANBUS lines. I have given this a test in SAVVYCAN and can confirm it works. Power steering control is definitely on the FlexRay bus though, not CAN.
