### ISSUE TITLE
good place to subscribe for vision model output?

### ISSUE THREAD

**Issue by darvin** [commaai/openpilot#452]
From my understanding, UI gets the info to draw from visiond via zeromq (specifically projected path of the car following the curves of the road). Is it correct?

could somebody please point out the code where parsing of this data is happening?

**Comment by rjeli** [comment]
Subscribe to model:
https://github.com/commaai/openpilot/blob/9d76070ab71bb46dd5b62abe58554eb24521c5c5/selfdrive/ui/ui.c#L395

Parse:
https://github.com/commaai/openpilot/blob/9d76070ab71bb46dd5b62abe58554eb24521c5c5/selfdrive/ui/ui.c#L1307

Draw the path & lanes:
https://github.com/commaai/openpilot/blob/9d76070ab71bb46dd5b62abe58554eb24521c5c5/selfdrive/ui/ui.c#L864
