### ISSUE TITLE
Chffr app won´t record in background

### ISSUE THREAD

**Issue by nirodg** [commaai/openpilot#460]
Recording in background work as expected if, firstly you have Chffr opened and ready to record, then when starts recording you switch to a different app, keeps recording. 

But it wont work if, before Chffr starts recording, you switch to a different app. If will begin recoding once you switch back to Chffr.

Device SM-G960F Android 8.0.0 - Samsusung Experience 9.0
chffr 2.2.3.88

**Comment by omerjerk** [comment]
Is the source code of this app open by any chance? I can look into this issue.

**Comment by andy867** [comment]
The reason that chffr app won't record in the background, at least per apple terms for the ios app, is that Apple requires any still imagery/videography to be the active application so if running said app and switch to another app, it stops recording as it's no longer the active application.

**Comment by legonigel** [comment]
Closing as wontfix.  The app will not be open source
