### ISSUE TITLE
Need a 3rd steering control type

### ISSUE THREAD

**Issue by Gernby** [commaai/openpilot#493]
While working through the latcontrol issues that some Toyota's experience, I noticed that almost all cars have yaw sensor data defined in their DBC's (not Honda), but it seems that all OP-compatible cars will have it available (like my Honda Accord).  After researching the value of yaw rate in modern vehicles for ADAS systems, I really think that there needs to be a third control type added for steering that is based on actual / desired yaw rate.  

Obviously, angle-type steering simplifies the control logic greatly.  Also, torque-type steering works well for straight-rate vehicles that have high resolution steer-rate data on the CAN bus.  However, for all the other vehicles, there's too much error to really make it work well.

With a new yaw-type steering classification, I think that "problem cars", like the Toyota Prius Prime can be made as ideal as any other.  The reason why I think this will be better is because it won't rely so much on the steering angle sensor, which seems to introduce a ton of error.  It would also eliminate error caused by variable steering rates, and reduce lag caused by sticky / heavy / springy steering columns.  

I've already started working on this, but won't have it ready for a few days.

**Comment by pd0wm** [comment]
I assume this issue is now solved by the new INDI controller.
