### ISSUE TITLE
Adjust OpenPilot’s CC speed via bluetooth

### ISSUE THREAD

**Issue by tritchie** [commaai/openpilot#498]
The car’s built-in CC stalk is an acceptable, but inefficient, way to adjust OpenPilot’s target speed. It only has two adjustment commands (+1 and -1) and  it’s placed next to the steering wheel, which is great if you’re steering with your hands, but not so great if speed is the only thing you’re controlling manually. 

It would be more convenient and ergonomic if the driver had the option to attach a small Bluetooth media button like this one somewhere (e.g. an armrest):
https://www.ebay.com/itm/Bluetooth-Media-Audio-Music-Remote-Control-Button-Car-Steering-Wheel-Bike-Mount-/391940366086
And use it to adjust the cruise control speed.

An example button scheme would be:
[>]=[increase cruise control by 5]
[<]=[cc -5]
[+]=[cc +1]
[-]=[cc -1]
[play/pause button] = [set cc to speed limit + delta, if applicable]

https://www.bountysource.com/issues/68575431-change-cc-speed-via-bluetooth

**Comment by tritchie** [comment]
https://www.bountysource.com/issues/68575431-change-cc-speed-via-bluetooth

**Comment by arne182** [comment]
Bluetooth is quite secure now a days. If you are scared then switch off the biggest vector the internet connection.

**Comment by tritchie** [comment]
Also, there's a whole world of further opportunity if you incorporate long presses. For instance:
Press [>] = [cc+1mph]; Press [<]=[-1mph]
Hold [>;<] = [+5;-5], then +5/-5 every 1/2 second till button is released
Press [Play/pause button] = [set cc to 0]
Hold 2 seconds [play/pause] = [set to speed limit + offset]
Press [+] = [increase offset by 1]; press [-] = [decrease offset by 1]

**Comment by ShaneSmiskol** [comment]
@tritchie How does this work? https://github.com/ShaneSmiskol/op-speed-controller-app

**Comment by pd0wm** [comment]
Sounds like a nice gimmick, but not something we would upstream.

This issue has been inactive for a while, so I'm closing it.
