### ISSUE TITLE
Get nothing after running on pc

### ISSUE THREAD

**Issue by susan987321** [commaai/openpilot#499]
Hi, I am trying to use openpilot on PC. After I run ./run_docker_tests.sh on PoweShell, I saw that the window for run_docker_tests flash across then disappear, and nothing is displayed in selfdrive/test/tests/plant/out/longitudinal/index.html, meanwhile there is not a folder /out in selfdrive/test/tests/plant/.
have someone get the same problem?

**Comment by dorkmo** [comment]
yup i got the same

**Comment by susan987321** [comment]
I found that this problem was caused by the old version of docker.
