### ISSUE TITLE
Questions about the Toyota 2018 Corolla

### ISSUE THREAD

**Issue by Yifanny** [commaai/openpilot#506]
My car is Toyota 2018 Corolla with Electric Power Steering System and Auto Cruise Control System, and it is a hybrid car.

I have bought panda, giraffe, and EON. Since the model name of the Toyota in China is different from the USA, I do not know if there is TSS-P module in my car. In the introduction of my car, it does not indicate if it has TSS-P or not.

Could anyone inform me whether my car is supported by openpilot? 

Thanks.

**Comment by lxalano** [comment]
Hi, I also want to consult, my car is a Chinese-made Corolla 2018, whether he is supported.

**Comment by muyufan** [comment]
不支持，国内新一代卡罗拉还得等半年。

**Comment by ucolchen** [comment]
问一下经销商，是否支持tss-p

**Comment by hao-fu** [comment]
Is there any Corolla driver working on openpilot? I am open to communicate.

有没有卡罗拉车主交流交流怎么搞

**Comment by bugsy924** [comment]
https://github.com/commaai/openpilot#supported-cars

**Comment by legonigel** [comment]
I think this car might just require a new fingerprint. If so check out https://github.com/commaai/openpilot#how-can-i-add-support-for-my-car

**Comment by ucolchen** [comment]
Hao-fu, please join the discord, there’s a lot of info and also a Chinese language sub group you might find people used same car

**Comment by hao-fu** [comment]
@ucolchen Yes I joined discord. I guess you are "ucol", just sent you a friend request.
