### ISSUE TITLE
Toyota Tacoma 2019 TSS-P

### ISSUE THREAD

**Issue by tlf30** [commaai/openpilot#518]
Quick question,
with the Toyota Tacoma 2019 getting TSS-P, does that mean it will be supported?

Thanks,
Trevor

**Comment by vanillagorillaa** [comment]
It looks like the Tacoma still only has LDA (Lane Departure Alert) and no steering assist, which is needed to run openpilot. Looks like 2019 Tacoma still won't cut it

**Comment by tlf30** [comment]
Ah, alright. Thank you.
