### ISSUE TITLE
Repository growing by 15Mb on every release

### ISSUE THREAD

**Issue by ingenieroariel** [commaai/openpilot#52]
visiond is 15Mb, everytime there is a release the repo grows by that amount. People download all previous versions of visiond as part of the git repo and right now it is 66Mb.

My suggestion is to ship `visiond` differently using a different method.

(edited to add the suggestion)

**Comment by energee** [comment]
Sounds like @ingenieroariel is suggesting tracking binary files with `git lfs`

**Comment by geohot** [comment]
We do this internally, will switch for the next release.

**Comment by pd0wm** [comment]
Visiond is now open source, so git lfs is not needed anymore.
