### ISSUE TITLE
2019 Honda Pilot Fingerprint Issue

### ISSUE THREAD

**Issue by aleenoor1** [commaai/openpilot#521]
Hi, There is a fingerprint issue with all 2019 Honda Pilot. The car throws all kind of errors if a Comma Pedal is installed. Basically, the 512: 6, 513: 6 from the section CAR.PILOT_2019:[{ ~~~~

This goes in the file: /data/openpilot/selfdrive/car/honda/values.py

@wocsor can provide additional details but feel free to check with @aleenoor as well.

Thanks,

**Comment by vanillagorillaa** [comment]
@aleenoor See above comments regarding adding fingerprint for Pilot

**Comment by marcbou** [comment]
see https://github.com/commaai/openpilot/pull/613

with these changes the pedal works pretty well on my Passport 2019 which should be mostly identical to the Pilot 2019.

**Comment by vanillagorillaa** [comment]
Fixed in next release, closing
