### ISSUE TITLE
OpenPilot name is not completely defunct... please respect it

### ISSUE THREAD

**Issue by MAVProxyUser** [commaai/openpilot#53]
Some of us are still around and even *selling* hardware using the OpenPilot name, thanks! 

OpenPilot ground / flight controller: 
https://sasquatchlabs.org/product/genuine-nano-flight-controller-w-case
OpenPilot 433mhz telemetry radio aka OPLink:
https://sasquatchlabs.org/product/openpilot-oplink-mini-modem-bundle

**Comment by MAVProxyUser** [comment]
The name is also Trademarked... 
https://search.ipaustralia.gov.au/trademarks/search/view/1362707?q=openpilot

**Comment by geohot** [comment]
According to the docs, http://opwiki.readthedocs.io/en/latest/user_manual/gcs_install_op.html I quote (sorry about the caps), "OPENPILOT WAS DISCONTINUED!". 

openpilot.org is also down as of April last year.

**Comment by MAVProxyUser** [comment]
What part of those are NOT the docs do you fail to comprehend? If I put up a random web page and say that Comma AI was discontinued does that make it so? Of course not!?

**Comment by MAVProxyUser** [comment]
Likewise that has NOTHING to do with the Trademark...

**Comment by MAVProxyUser** [comment]
Yes... the web server has been pulled, that does not give you the right to acquire the name... Nor does it make is classy. 

https://github.com/openpilot/OpenPilot

You can see here the official project Wiki *was* at:
Wiki, docs and manuals:	http://wiki.openpilot.org/

NOT The random readthedocs.io website you furnished...

**Comment by MAVProxyUser** [comment]
I hear your project is defunct... did you read the docs? 
https://readthedocs.org/projects/openpilot-by-comma-ai/

**Comment by geohot** [comment]
![haters](https://cloud.githubusercontent.com/assets/72895/23197888/45d6d960-f878-11e6-8eb9-8a06ae9358b5.jpg)

**Comment by MAVProxyUser** [comment]
Actually Geo... I used to respect you and have helped you in a former life... right now you are simple being flat out disrespectful and hovering over the corpse of another successful autopilot name.. lets be honest.

**Comment by geohot** [comment]
That github you linked hasn't been updated since 2015. That link you posted is dead. And you filed 3 issues, not a very respectful way to address something.

**Comment by MAVProxyUser** [comment]
I saw how you blew the first guy off... clearly you had no respect why should I come in doing anything other than calling a spade a spade? 

Again... keep acting like you don't know it is trademarked... project status has NOTHING to do with the name being trademarked and you know it. 

I mean come on you keep citing some BS documentation as if you knew ANYTHING about the original project.

**Comment by MAVProxyUser** [comment]
Hey guys... I have this new project called Blackra1n (no one uses that project any more so I can just snag the name!)... you should come check it out! *roll eyes*
