### ISSUE TITLE
Uncommanded disengagement

### ISSUE THREAD

**Issue by zeeexsixare** [commaai/openpilot#555]
On my drive in to work this morning, I was engaged and OP was functioning normally for about 10 seconds.  Ideal conditions. Then it suddenly disengaged and I couldn't tell except I started drifting out of the lane. And Green eon outline went away. Maps off. Path was dead straight. Speeds were around 40mph.  No sounds but I have engage/disengage sounds turned off. Cabana uploading, will share later.  This had happened before on a drive a few weeks ago but didn't occur again until now. 0.5.8

**Comment by adhintz** [comment]
What car are you using? Do you have a cabana share link you can share?

**Comment by zeeexsixare** [comment]
Hey Drew, the car is a 2017 Toyota Highlander ICE.  I've sent you a cabana link privately via Discord.

**Comment by rbiasini** [comment]
@zeeexsixare normally we would dig into these issues (sorry we did not follow up months ago). However, the OP version you had the issue with is quite old now and it would not make much sense looking into it now. Closing the ticket.
