### ISSUE TITLE
Can openpilot determine turn left or right in next cross?

### ISSUE THREAD

**Issue by jinfagang** [commaai/openpilot#568]
Just wonder, does it knows where I (my car) am? Will it continue determine which cross to turn ? How did it knows where I will go?

**Comment by bugsy924** [comment]
No

**Comment by jinfagang** [comment]
@bugsy924 Then it just L2

**Comment by jfrux** [comment]
Correct, it’s always been L2 and will be for quite some time.
There aren’t any L3 cars available for purchase.
The good news is, that the software can reach L3 long before your car will ever be L3.
So if you switch cars, you can port it and upgrade any supported car with this at any time.

**Comment by jinfagang** [comment]
@jfrux I wanna build my own self driving car (whole car tiny not just a plugger) with L3 capable

**Comment by jfrux** [comment]
You and the rest of the world mate!
Best of luck to you!

**Comment by dorkmo** [comment]
@jinfagang join the discord, there is a channel discussing traffic light and stop sign detection. Possiblly L2.5

**Comment by icmma** [comment]
@jinfagang  by end of the year OP will be L3:)

**Comment by jinfagang** [comment]
@dorkmo  I am not mean that, without navigation and location it can not know where to go

**Comment by ucolchen** [comment]
I think that's part of the big picture, i see right now peoples are working hard on the puzzle piece by piece, and achieved great milestones, lkas, acc, stop and go, auto lane change, hd maps...great job comma community doing here!

**Comment by jinfagang** [comment]
BTW, does there any deeplearning models summary used in comma? such as object detection model, lane   and drivable area segmentation model, and lidar & camera fusion model etc.

**Comment by legonigel** [comment]
No. If you want to see what models currently are used, you can check out the code in `selfdrive/visiond`
