### ISSUE TITLE
Support Multi-Port CAN BUS Forwarding

### ISSUE THREAD

**Issue by sumitbinnani** [commaai/openpilot#570]
It seems a few cars may be helped if the infrastructure would allow incoming messages to be forwarded to multiple ports.

E.g. Camry Hybrid needs incoming message forwarding from CAN0 to both CAN1 and CAN2 (from what I could glean from Discord Community).

I believe that a little refactoring could help this. E.g. changing the structure of `fwd_hook` in `safety.h` to handle array instead of a single int and then handling it as shown in this PR:  https://github.com/bugsy924/openpilot/pull/22

**Comment by legonigel** [comment]
This looks like an issue in Panda. Please open in https://github.com/commaai/panda
