### ISSUE TITLE
Hummer H2

### ISSUE THREAD

**Issue by supergenio** [commaai/openpilot#576]
Hi I’m pretty new at this but does anyone know if there’s a way to make it work on a Hummer H2 2003

**Comment by energee** [comment]
My guess that might be a stretch as 2003 is pretty old, does H2 have adaptive cruise control and lane keeping assist?

**Comment by legonigel** [comment]
I think you might want to check out the [discord](discord.comma.ai). You can find channels there to discuss with the community. You might want to checkout the channel `#topic-without-lkas`

**Comment by ucolchen** [comment]
> My guess, that might be a stretch as 2003 is pretty old, does H2 have adaptive cruise control and lane keeping assist?

learned from discord, #topic-without-lkas, as soon as the car has EPS, there's chance op will support in future.

**Comment by icmma** [comment]
it will be :) SoonTM @ucolchen
