### ISSUE TITLE
Wireless Towing

### ISSUE THREAD

**Issue by ememisya** [commaai/openpilot#58]
So you're out drinking and you find a buddy to drive you home, unfortunately you brought your car to the party and will have to somehow get to it in the morning.  Unless of course you could get it towed home, but that's not very affordable.  But what if there existed a software running in both cars, which would relay the signals from the car in the front, to a car right behind it?  You'd line up the car you want to wirelessly tow right behind yours, link up the cars, and drive the two cars plus your drunk friend home.  If there were features such as openpilot for additional safety, like if the link was broken, the driverless car kept in lane, turned on emergency signals, and pulled to the side of the road?  Thoughts?

**Comment by geohot** [comment]
Rare use case and not legal anywhere right now.
