### ISSUE TITLE
Middle line missing

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#586]
If the middle line is unavailable then the car should hug right.
Especially if the lane width now measures double the standard at that speed.

**Comment by BatmanTSLA** [comment]
Vote on that, common „issue“ in germany. Narrow streets, no center line. Car is tends to move to the middle of the road.

**Comment by Martint1980** [comment]
please add it to the new version

**Comment by ErichMoraga** [comment]
Ugh, just when we're ranting about all the hugging issues, you want MORE hugging. :sad:

**Comment by arne182** [comment]
I have an idea for a fix for this issue. Something like, if OSM has 2 lanes for this street and vision measures a value that is obviously double  that of a narrow road width, it ignores the left lane line. 

Or just get a bucket of paint and paint the middle lane line.

**Comment by ErichMoraga** [comment]
Bucket of paint has been on my "bucket list" of things to do...

**Comment by pd0wm** [comment]
0.6.3 has improved behavior for lines wider than a normal lane
