### ISSUE TITLE
Support Lexus RX300 2018?

### ISSUE THREAD

**Issue by but0n** [commaai/openpilot#594]
Hi,
I've bought a EON DevKit, panda and giraffe. I wonder is this tools support on the Lexus RX300 2018? I didn't seen this car on the list.

**Comment by ucolchen** [comment]
have you tried on the car? discord is a better place to discuss and for more information. 
https://opc.ai/discord

**Comment by but0n** [comment]
@ucolchen 
No, I haven't. I asked on discord, seems like nobody tried on the car.

**Comment by eFiniLan** [comment]
@but0n it will probably not work out of box but since OP already support RX450h, it won't be too hard to make it work on your car.

**Comment by but0n** [comment]
@eFiniLan Thanks! I want to join the wechat group, can you share me the QR code?

**Comment by eFiniLan** [comment]
This can be closed, RX300 (China version)  can use rx450h port with minor modification (checks[] in carstate.py)
