### ISSUE TITLE
Travis CI to test all car types

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#597]

**Comment by arne182** [comment]
The test script should test not just a Honda but also a Toyota GM Chrysler etc

**Comment by pd0wm** [comment]
We already have an internal test that runs openpilot for 30 seconds on all supported car models. We are currently working on getting a list of routes than we can release publicly so we can opensource this test.

**Comment by arne182** [comment]
That would be great. It would help to test for all the now supported car types

**Comment by fabio71c** [comment]
As I'm digging into the test model, I will try to figure out a way to test other models more easily.

**Comment by pd0wm** [comment]
This was open sourced in 0.6.3
