### ISSUE TITLE
traffic lights, traffic mark，are being planned？

### ISSUE THREAD

**Issue by leo333** [commaai/openpilot#60]
The car stopped at the red signal, See the speed limit sign,  slowed down。

**Comment by geohot** [comment]
It's open source! Feel free to add.

**Comment by leo333** [comment]
I'll add

**Comment by Martint1980** [comment]
Please for Germany as well 👍🏻

**Comment by arne182** [comment]
Slow down for traffic signs are already in my fork. Traffic lights are not too far away as well
