### ISSUE TITLE
Support for Kia and oscc.io

### ISSUE THREAD

**Issue by droter** [commaai/openpilot#61]
Hi,

Is anyone working on OpenPilot support for the Kia Soul and the http://oscc.io/ open source car controller kit?

Thanks,

Matt

**Comment by geohot** [comment]
I caution you about the OSCC steering. Afaik, they are passing the torque sensor through an Arduino, giving untrusted hardware and software the ability to put high steering torque on the wheel. One of the core safety assumptions in openpilot is that the car's ASIL-D firmware is limiting steering torque. If someone undertakes this project, it's something to keep in mind.
