### ISSUE TITLE
Username and password in selfdrive/crash.py

### ISSUE THREAD

**Issue by Javantea** [commaai/openpilot#640]
There is a hardcoded username and password in [selfdrive/crash.py line 21](https://github.com/commaai/openpilot/blob/devel/selfdrive/crash.py#L21). It appears to be an HTTP crash handler. This should be a config value taken from user input perhaps.

**Comment by arne182** [comment]
Interesting idea.

**Comment by pd0wm** [comment]
I don't see a problem with hard coding this. If you want to receive your own crashlogs you're running your own fork anyway.
