### ISSUE TITLE
Create an issue template for sane creation of issues with most commonly needed information 

### ISSUE THREAD

**Issue by zorrobyte** [commaai/openpilot#645]
**Notes for successful issue creation (delete this section after reading)**
Please title your issue as: OP Version - Make - Model - short description of the issue.

Example:
0.5.12 - Toyota Prius Prime Advanced - OEM self park functionality is terrible

/*OP Repo Maintainers, it would be incredible to have tags for this, such as:
OP Version
Make
Needs Replication
Replicated*/

# Description

A concise description of what the issue is.

## Actual behavior

What is actually happening.

## To Reproduce

1. 
2. 
3. 

## Troubleshooting / Investigation details

What have you tried already? Have you attempted any codebase modifications? If so, please share a link to your PR/commit.

## Cabana Explorer Segment ID (please attempt sharing the segment where the issue can be readily observed, scrub video to section then "Copy Current Segment"), Cabana Link
Segment ID, Cabana share link

**Comment by theantihero** [comment]
We definitely need this to become a thing +1

**Comment by ErichMoraga** [comment]
We already had a page for this stuff, but... this would probably be better.

**Comment by ErichMoraga** [comment]
BTW - The page I was referring to is cited by the wiki...
https://community.comma.ai/wiki/index.php/Openpilot_Events

**Comment by vanillagorillaa** [comment]
I know you know about this, but,  https://github.com/commaai/openpilot/blob/devel/.github/ISSUE_TEMPLATE/bug_report.md 

closing
