### ISSUE TITLE
Turn off video logging in Germany

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#653]
In Germany it is Illegal to constantly record people and cars on the road without written approval. Especially if it is transferred into the internet.

Here is an example of how to do this.

https://github.com/arne182/openpilot/commit/d691260bc68442000fb16a0f0799e4f3dda920a7#diff-a09ff212f870eaece6714ccb529be966

Having this done in loggerd with only the video feed would be better than completely stopping the logger.

**Comment by geohot** [comment]
We don't plan on supporting regionalizations like this due to complexity of complying with them all, this is best served via a fork. In the openpilot readme, we state "YOU ARE RESPONSIBLE FOR COMPLYING WITH LOCAL LAWS AND REGULATIONS"
