### ISSUE TITLE
v0.2.8 visiond crash

### ISSUE THREAD

**Issue by jeankalud** [commaai/openpilot#66]
Latest version pushed yesterday crash on startup.

No camera UI running. Just the fan at high speed.

Copied over just visiond version v0.2.7 and it works fine.

Can't really tell where as its a binary. All I can see is this:

`**starting process visiond**
starting in dir '/sdcard/realdata/2017-03-01--11-17-52--0'
*** init GPS
creating thread: Loc_hal_worker
OrderedDict([('event', 'alert_add'), ('alert_type', 'startup'), ('enabled', False)])
diag diag_get_max_file_size size=200,max_file_size=209715200,min_file_size=167772160
*** sensor loop
pid 31480's current scheduling policy: SCHED_OTHER
pid 31480's current scheduling priority: 0
pid 31480's new scheduling policy: SCHED_FIFO
pid 31480's new scheduling priority: 2
**Always Keep Hands on Wheel/Be Ready to Take Over Any Time 1  none none**
**controlsd lagging by 3.10 ms**
vendor: 'QUALCOMM'
platform version: 'OpenCL 2.0 QUALCOMM build: commit #cababe8 changeid #I8a8f1b7e8f Date: 07/16/16 Sat Local Branch:  Remote Branch: '
profile: 'FULL_PROFILE'
name: 'QUALCOMM Adreno(TM)'
device version: 'OpenCL 2.0 Adreno(TM) 530'
type = 0x0004 = CL_DEVICE_TYPE_GPU

**clutil.c:307: cl_program_from_index: assertion "err == 0" failed**
40 sensors found
`

**Comment by geohot** [comment]
Fixed in 0.2.9. 0.2.8 didn't work on NEOS v1
