### ISSUE TITLE
Hyundai Ioniq? Already has ACC & LKAS

### ISSUE THREAD

**Issue by phr00t** [commaai/openpilot#68]
If I were to get a Hyundai Ioniq, is it possible to use this software with it, considering it already has these features? I see something about the CAN-bus hacking... wondering if anyone has ever tried this on a Hyundai or know how to get started.

**Comment by mniami** [comment]
I will love to use test it with my Hyundai i30, let us know is it feasible.

**Comment by lambaek** [comment]
Same goes for me. Would love to test on hyundai i30

**Comment by cori2000** [comment]
I would test it for my Hyundai i40. Could you share some more info. on it?

**Comment by VincentVonPark** [comment]
is it possible to test with Hyundai Accent Manual?

**Comment by bugsy924** [comment]
You can only control a car that already has built in safety features

Built in LKAS means you can add steering
Built in ACC means you can add accelerator+brake

**Comment by emmertex** [comment]
IONIQ shoudln't be any issue.
as for i30 and i40, only if they have stock LKAS

If so, safe to assume they will work fine.
join hyundai-kia-genesis on Discord

**Comment by Growiel** [comment]
I see that this is closed, is the Ioniq now supported ? I'm getting an Electric Ioniq soon and am interrested in Openpilot. Thanks !

**Comment by soulslicer** [comment]
any luck? its been a year?
