### ISSUE TITLE
Update very old version of qpOASES library

### ISSUE THREAD

**Issue by jqnatividad** [commaai/openpilot#683]
Bundled version is 1.3
https://github.com/commaai/openpilot/blob/devel/phonelibs/qpoases/VERSIONS.txt

Latest version is 3.1
https://projects.coin-or.org/qpOASES/browser/trunk/VERSIONS

**Comment by pd0wm** [comment]
Unfortunately version 1.3 is the only version supported by the code generation part of Acado, our Non-Linear Model Predictive Control library.

Unfortunately it looks like acado is no longer being developed. However, there is not much choice in NPMC libraries that can run real-time on embedded hardware. At some point I might decide to write a subset of acado functionality for use in openpilot, but that is a huge undertaking.

**Comment by renegadephysicist** [comment]
FYI Acado does support the C version of qpOASES 3.1.

Just use:
mpc.set(QP_SOLVER, QP_QPOASES3);

**Comment by pd0wm** [comment]
Good catch, I'll check it out!
