### ISSUE TITLE
Update OpenCV

### ISSUE THREAD

**Issue by jqnatividad** [commaai/openpilot#686]
Pinned version is a bit dated (Dec 2017)

https://github.com/commaai/openpilot/blob/65e1342e41d2cdc21e4651a7d18610863e1fb0b3/requirements_openpilot.txt#L34

https://pypi.org/project/opencv-python/#history

It seems v4.x of OpenCV also has optimizations that take advantage of SnapDragon SoC without having to resort to using something like Qualcomm’s [FastCV](https://developer.qualcomm.com/docs/fastcv/api/fastcv_8h.html) with OpenCV’s “wide universal intrinsics.”

https://www.phoronix.com/scan.php?page=news_item&px=OpenCV-4.0-Released
https://github.com/opencv/opencv/wiki/ChangeLog

**Comment by pd0wm** [comment]
OpenCV is not actually used anymore. The requirements files just reflects what's currently installed on the EON.

I'm working on a complete rebuild of all the libraries shipping with NEOS, and removing all the stuff that is no longer used.
