### ISSUE TITLE
Pegeout 3008 openpilot ?

### ISSUE THREAD

**Issue by DevJoseWeb** [commaai/openpilot#688]
Pegeout 3008 openpilot ?

**Comment by njbrown09** [comment]
?

**Comment by DevJoseWeb** [comment]
Can this system and the hardware be adapted to the Pegeout 3008?

**Comment by geohot** [comment]
Possibly, see https://medium.com/@comma_ai/how-to-write-a-car-port-for-openpilot-7ce0785eda84
