### ISSUE TITLE
comment stating opposite of code. bug?

### ISSUE THREAD

**Issue by LucidObscurity** [commaai/openpilot#69]
It looks to me like the programmer wrote one thing in the comment but coded the opposite (or visa versa). 

/selfdrive/car/honda/carcontrols.py line 179:

    # radar at 20Hz, but these msgs need to be sent at 50Hz on ilx (seems like an Acura bug)
    if CS.civic:
      radar_send_step = 5
    else:
      radar_send_step = 2

**Comment by geohot** [comment]
Send step is the number of steps between the sends. So I believe it is right :)
