### ISSUE TITLE
Bounty visiond

### ISSUE THREAD

**Issue by eugesd** [commaai/openpilot#697]
https://github.com/commaai/openpilot/blob/dd34ccfe288ebda8e2568cf550994ae890379f45/selfdrive/visiond/visiond.cc#L1358

I'm interested in collecting this bounty and contributing to the source code. Where does this streamed video feed come from if I don't already have an EON? Are there sample videos that can be used to build this out?

If y'all could list out some requirements and what is expected of this, I'd love to get started working on this.

Thanks,
Eugenio

**Comment by geohot** [comment]
Already done #544

**Comment by eugesd** [comment]
Any other bounty I could contribute to with this reward?
