### ISSUE TITLE
Honda Insight 2019

### ISSUE THREAD

**Issue by nagolinc** [commaai/openpilot#701]
I have a 2019 Honda Insight EX.  LKAS and ACC are both standard.  Will this work with the Honda Bosch, or what do I need to get started?

**Comment by jasonhc73** [comment]
I have the Touring of the 2019 Honda Insight, it is not supported, yet.

**Comment by csouers** [comment]
Energee had a port for this. It has a conflicting fingerprint thus why it’s not upstreamed yet. I think kegman also has a fork for it.

**Comment by dustinfields** [comment]
@nagolinc @jasonhc73 

We have an insight group with a working port
Join discord and add me as a friend ill invite you into the group

dustinfields

**Comment by nagolinc** [comment]
@dustinfields  Not super familiar with Discord.  It says I need a "four digit tag" to add you

**Comment by dustinfields** [comment]
Ironworm#8498

⁣Get BlueMail for Android ​

**Comment by rbiasini** [comment]
Discussion moved to discord. For support we'll need a VIN based fingerprint.
