### ISSUE TITLE
Support for Business Vehicles like Trucks?

### ISSUE THREAD

**Issue by franz101** [commaai/openpilot#706]
Is consumer electronics just far ahead of the the B2B technology? I would guess this could be interesting for truck drivers. Also because they generate a lot of data too, even though a very different kind of data.

**Comment by icmma** [comment]
coming soon unofficially

**Comment by franz101** [comment]
Where I can see if a truck could be supported?

**Comment by rbiasini** [comment]
Openpilot could support trucks. Just need a PR with a good quality port
