### ISSUE TITLE
Add 2017 Acura MDX with AcuraWatch

### ISSUE THREAD

**Issue by easel** [commaai/openpilot#71]
I'm opening this to capture interest and find out if anybody else has attempted it. I assume the system should be exceptionally similar to the already supported vehicles, and the low speed ACC should resolve the speed control issue limitation reported on the ILX. 

Will report back as I learn more, I'm new to the space.

**Comment by geohot** [comment]
I believe this car is the same as the Accord with steering. Needs a k-line transceiver

**Comment by easel** [comment]
Thanks @geohot, any pointers to where I could start verifying this stuff? Are there some discussions about the accord floating around somewhere?

**Comment by energee** [comment]
You need something to read the messaging on the Canbus like usb2can, pican2, CAN-BUS Shield or similar... sniff the packets on the CAN to track down the message and message ID that is fired for a particular event.

You'll have to look into the k-line transceiver, i'm assuming that means the NEO would need more hardware to control steering if the steering isn't controlled over CAN.

**Comment by zhaohuaqing1993** [comment]
@geohot  Hi，i run the ./view_generative_model.py transition --name transition and always see the string "loading weights...",what should i do?thanks

**Comment by geohot** [comment]
If you show me a NEO running with the gas and brakes working, we can help you out with some K-Line hardware.

**Comment by JasonGiedymin** [comment]
For reference, the 2014 through to today’s 2019 could have a lot of the same hardware. I’ve driven every model year and the running characteristics of ACC and LKAS feel very close if not the same. 

I’d be willing to also capture bus traffic over these model ranges.

Why will be needed?

**Comment by JasonGiedymin** [comment]
Sorry for the laaaate reply. I’ll joinnslack today and try to see if I can help out.
