### ISSUE TITLE
LKAS without ACC

### ISSUE THREAD

**Issue by kavalpatel23** [commaai/openpilot#724]
I was wondering if it would be possible for OpenPilot to maintain lane keep but disengage cruise control. Sometimes in traffic, I'd like to maintain the speed and braking, but have OpenPilot assist with lane keeping. Without OpenPilot, in my Honda CRV, if I press the LKAS button, the car starts assisting with lane keep, but it does not engage cruise. I was wondering if something similar would be possible with openpilot.
Edit: arne's fork does this! https://github.com/arne182/openpilot

**Comment by icmma** [comment]
anything is possible with code

**Comment by Martint1980** [comment]
Please add it to a new version. Also that OP doesn't disengage when push the acceleration pedal.

**Comment by ErichMoraga** [comment]
Not gonna' happen.  @geohot has mentioned this many times.  You can try Arne's fork, though.

**Comment by arne182** [comment]
Arne to the rescue.
https://github.com/arne182/openpilot

**Comment by ErichMoraga** [comment]
Yeahhh!
