### ISSUE TITLE
test_longitudinal.py from run_docker_tests.sh is failing

### ISSUE THREAD

**Issue by adhintz** [commaai/openpilot#727]
When running /test_longitudinal.py from run_docker_tests.sh I get this error:
```
can_list_to_can_capnp.cc:22:9: error: no member named 'setValid' in 'cereal::Event::Builder'
  event.setValid(valid);
  ~~~~~ ^
1 error generated.
Makefile:98: recipe for target 'can_list_to_can_capnp.o' failed
```

mlp on Discord is seeing the same behavior. Note that just doing run_docker_tests.sh will not surface this error because set -e stops at the first failing test. To see this, you'll need to run the test manually or reorder the tests.

**Comment by pd0wm** [comment]
This should be fixed by #730. I updated run_docker_tests.sh, and pointed CI to that script.
