### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Nahida-IUPUI** [commaai/openpilot#73]
Hi, I was wondering do you have any kind of documentation based on the APIs that you have developed for openPilot system, which may have the list of APIs and their functionalities (such as dependency, parameters, etc.)?

**Comment by geohot** [comment]
Car APIs: https://github.com/commaai/openpilot/blob/master/cereal/car.capnp
Internal APIs: https://github.com/commaai/openpilot/blob/master/cereal/log.capnp
