### ISSUE TITLE
visiond statically links with opencv but doesn't come with opencv's license file

### ISSUE THREAD

**Issue by bobpoekert** [commaai/openpilot#74]
The OpenCV license (http://opencv.org/license.html, 3-clause BSD) requires that it be distributed with its copyright notice. Since visiond contains all or part of opencv (the symbols are still in there), you need to say so in the readme.

**Comment by geohot** [comment]
Will add in next release.

**Comment by ingenieroariel** [comment]
I think this is fixed.

**Comment by espes** [comment]
Yup!
