### ISSUE TITLE
Network information not available in UI

### ISSUE THREAD

**Issue by deftdawg** [commaai/openpilot#742]
IP addresses and networks that the EON are connected to should be viewable in the UI somewhere to make it easier to connect/shell in when the car is not next to a workbench.

[EDIT: Fair point, this is not new to 0.6.0... so it's an RFE]

**Comment by ErichMoraga** [comment]
You've asked several questions via GitHub that have already been answered in Discord.  Nothing has changed in 0.6 regarding how to retrieve the IP address.

**Comment by theantihero** [comment]
There's custom UIs that lets you do this. Check out kegman's or arne's repos.

**Comment by ErichMoraga** [comment]
Exactly, that's why we have custom repos.  Just because your IP is apparently changing all the time, and you want to see it without drilling into a couple menus, doesn't mean the masses need it plastered on the UI (which Comma generally wants to keep clean).

**Comment by rbiasini** [comment]
IP address is available from `Advanced Settings->Networks->Open WiFi Networks->Advanced`
