### ISSUE TITLE
Would it be possible to use openpilot in a game such as ETS2?

### ISSUE THREAD

**Issue by sidbmw** [commaai/openpilot#748]
Hi,

I'd like to jump into the wold of self driving/autonomous systems and was wondering if it would be possible to get openpilot to run on a PC and get a car/truck to stay in it's lane, change lanes, maintain distance etc....in a game such as Euro Truck Sim 2.

Thanks

**Comment by rbiasini** [comment]
Yeah, I don't see why not. You can run most of the openpilot processes on a pc.
