### ISSUE TITLE
Unusable  .6 load on 2018 Camry

### ISSUE THREAD

**Issue by mikecboyd** [commaai/openpilot#750]
Idk who touched the code but good god this load is unusable. Severe pull to the right anytime it is engaged rendering unusable. Prior load did not have this issue.

**Comment by ErichMoraga** [comment]
Known issue.  Start your car with the wheels straight.

**Comment by illumiN8i** [comment]
The fix is in the devel branch now.

**Comment by ErichMoraga** [comment]
Yuuup!  Saw that this morning.  Hopefully that'll keep the kiddos happy until Christmas!

**Comment by ErichMoraga** [comment]
@mikecboyd https://github.com/commaai/openpilot/pull/751

**Comment by mikecboyd** [comment]
Awesome, will wait for release. Estimates on when next one will be?

**Comment by ErichMoraga** [comment]
It's already in devel.

**Comment by mikecboyd** [comment]
How do I point install to the devel? I’m used to just typing in the normal link for install when needed.

**Comment by ErichMoraga** [comment]
Please check Discord and the wikis, since you might have follow up questions, and this isn't really the right place for them.

**Comment by rbiasini** [comment]
fix merged both in devel and release2.
