### ISSUE TITLE
Supported cars list is wrong, 2020 Toyota Corolla is not fully supported

### ISSUE THREAD

**Issue by meritus** [commaai/openpilot#754]
I found out the 2020 Toyota Corolla LE is not fully support even though it says under supported cars: "All". Found this out after getting the vehicle. Please fix.

**Comment by rbiasini** [comment]
This is most likely a fingerprint issue, i.e. your vehicle might generate CAN messages that we have not seen before on that vehicle model. This is always a possibility on every vehicle model.

You can join dicord.comma.ai for a more in-depth discussion.

**Comment by meritus** [comment]
There has been discussion on this, there doesn't seem to be support for the 2020 Corolla LE out of the box and trying to run get_fingerprint.py does not yield anything useful.

<img width="1171" alt="Screen Shot 2019-07-22 at 10 36 19 PM" src="https://user-images.githubusercontent.com/1149510/61678599-4c508b00-acd1-11e9-87c2-b09c4562556d.png">

**Comment by rbiasini** [comment]
@meritus do you still have issues?
