### ISSUE TITLE
how to understand the vanishing point formula

### ISSUE THREAD

**Issue by gucasbrg** [commaai/openpilot#760]
```
new_vp = eon_intrinsics.dot(view_frame_from_device_frame.dot(trans))
```
trans means speed? can you provide some article to explanation  these formula

**Comment by dekerr** [comment]
trans as in translation of the camera frame. 
this is probably a decent start to understand frames and camera properties
http://ksimek.github.io/2013/08/13/intrinsic/

**Comment by gucasbrg** [comment]
@dekerr 
> ```python
> def handle_cam_odom(self, log):
> trans, rot = log.cameraOdometry.trans, log.cameraOdometry.rot
> if np.linalg.norm(trans) > MIN_SPEED_FILTER and abs(rot[2]) < MAX_YAW_RATE_FILTER:
>   new_vp = eon_intrinsics.dot(view_frame_from_device_frame.dot(trans))
> ```

the defination of  **trans** in  CameraOdometry,looks like  **m/s in device frame**

>
> ```
> struct CameraOdometry {
>   trans @0 :List(Float32); # m/s in device frame
>   rot @1 :List(Float32); # rad/s in device frame
>   transStd @2 :List(Float32); # std m/s in device frame
>   rotStd @3 :List(Float32); # std rad/s in device frame
> }
> 
> ```

**Comment by gucasbrg** [comment]
![1566294427109](https://user-images.githubusercontent.com/3182658/63746076-77348d00-c8d6-11e9-9ce9-a7cd2634a5a1.png)
