### ISSUE TITLE
EON appears to have panic'd during the middle of drive

### ISSUE THREAD

**Issue by billma12** [commaai/openpilot#771]
Sorry not sure where else to address this besides github issues.

Yesterday, was cruising like 75mph on highway.

Then openpilot disengaged and I got a bunch of warnings on my dashboard. Which was weird because EON Was still green.

But actually I realized EON froze (and later rebooted itself)

https://my.comma.ai/cabana/?route=cb38ea752c72da81%7C2019-07-30--10-10-47&max=16&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fcb38ea752c72da81%2Ffd2cb58b6d81c4f0b71167bc3b6b5a66_2019-07-30--10-10-47

This is the link I found from Cabana that shares data from the drive. Time of interest would be at the end when the system disengaged itself.

Let me know if need more information or there's a better place to post this issue.
Been using openpilot for like 6 months without any hiccups until this happened.

Thanks.

Build: 6.1 dev 
Car: 2017 Toyota Corolla
Pedal: Yes

**Comment by cydia2020** [comment]
I've ran into this issue once before, OpenPilot 0.6 was running at the time, Toyota Prius 2018

**Comment by bugsy924** [comment]
Any chance your EONs are overheating?

**Comment by ErichMoraga** [comment]
I'm sure everyone has had an issue at some point, but considering there've been several NEOS revisions in the last few months, please upgrade to the latest... and we'll go from there if your issues persist.

**Comment by cydia2020** [comment]
> Any chance your EONs are overheating?

No, it's bloody cold here in victoria😂

**Comment by pd0wm** [comment]
Closing this issue now since there have been many stability improvements over the past months. Feel free to open a new issue if you still have random reboots/freezes.
