### ISSUE TITLE
OpenPilot 0.6x can not go back to 0.5x?(I have tried many ways)

### ISSUE THREAD

**Issue by gzjackar** [commaai/openpilot#779]
Because the poor turning ability of steer turning (Honda CRV-Hybrid) I get by OpenPilot 0.6x,I need to go back to 0.5x,I have tried many ways:
1、Thanks to @arne182, downgrade NEOS with one command
2、Manual Instructions to flash back to v9 NEOS for downgrading back to 0.5.xx:（Kegman）
3、Download V9 NEOS and flash.py (official method)
I have downgraded the NEOS from 10 to 9 and panda from 1.4.1 to 1.2.1, but I still can not get the op works properly ,now the eon can show the car speed ,and the panda is also active , but the car will show ACC,LKAS error, openpilot can not be enable either. Do some know the root caused?
I get the error message below :
![image](https://user-images.githubusercontent.com/48777459/62512691-9f871980-b84b-11e9-82bd-0e8ee62bab24.png)
![image](https://user-images.githubusercontent.com/48777459/62512701-a877eb00-b84b-11e9-9b65-3da581ce2891.png)
![image](https://user-images.githubusercontent.com/48777459/62512725-bfb6d880-b84b-11e9-8c77-2fb7600220c4.png)
![image](https://user-images.githubusercontent.com/48777459/62512744-d1987b80-b84b-11e9-942a-7f076c5b5d1d.png)

**Comment by gzjackar** [comment]
I replug the panda , the miracle appears , issue is closed

**Comment by gzjackar** [comment]
I replug the panda , the miracle appears , issue is closed

**Comment by ErichMoraga** [comment]
Yup, just needed to be power cycled.
