### ISSUE TITLE
variable associated to a variety of coordinate systems

### ISSUE THREAD

**Issue by gucasbrg** [commaai/openpilot#782]
1. what mean the defination of **dRel\yRel?** and is the following explanation correct?
![微信图片_20190807145452](https://user-images.githubusercontent.com/3182658/62601501-15f74a80-b924-11e9-8f1d-448a45390abb.jpg)

2. in this project, associated to a variety of coordinate systems, **car to model\car to bb\pt to car\pt from car ex,** can you explain some principle?

3. Pathplanner ,Convert the MPC control result to zmp, then use ui.c to plot x, y to the method Car_space_to_full_frame **vec4 p_car_space = (vec4){{px, py, 0., 1.}}; How to convert to this format?** Car_space_projective can be seen as a world coordinate system (xw, yw, zw, 1), Then use the external parameter matrix extrinsic_matrix to get the camera coordinate system Ep Then use the internal parameter matrix to get p_image 

 I am very sorry to delay your time and look forward to your reply.

**Comment by ErichMoraga** [comment]
See... https://github.com/commaai/openpilot/issues/27

**Comment by gucasbrg** [comment]
> See... #27
![xx](https://user-images.githubusercontent.com/3182658/62620695-929e1f00-b94c-11e9-8938-aee0126252a5.jpg)

I see the file in "car/*/radar_interface.py", in gm, the code
```
self.pts[targetId].dRel = distance # from front of car
# From driver's pov, left is positive
deg_to_rad = np.pi/180.
self.pts[targetId].yRel = math.sin(deg_to_rad * cpt['TrkAzimuth']) * distance		、
```
Seemingly contradictory

**Comment by pd0wm** [comment]
Interesting find. Not exactly sure why it is done this way. Since the angles are small this is not really a problem though, if dRel is 10m and the angle is 10 degrees the error is only 3 cm.
