### ISSUE TITLE
./update-refs.py --no-upload not working

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#810]
When trying the command there is an error azure.starage.blob import error.

**Comment by pd0wm** [comment]
Can you try running this inside the docker container? That should install all the proper dependencies.

In this case you're probably missing `azure-batch==4.1.3 azure-common==1.1.16 azure-nspkg==3.0.0 azure-storage-blob==1.3.1 azure-storage-common==1.3.0 azure-storage-nspkg==3.0.0`
