### ISSUE TITLE
Head light system malfunction after flooring the acceleration pedal

### ISSUE THREAD

**Issue by cydia2020** [commaai/openpilot#822]
Car: Toyota Prius 2018, ZVW50
OpenPilot version: 0.6.x (all experiencing this)

Steps to reproduce the problem:
1. Disengage OpenPilot
2. Stop the car
3. Floor the acceleration pedal
4. If you're lucky, you get a headlight system malfunction error on the MID

Resolution:
Restart the car

Note: this doesn't happen all the time, it only happens on very rare occasions, but it does happen and I can experience it around once a fortnight.

**Comment by illumiN8i** [comment]
I had the same thing happen once when braking hard on 2018 Prius Prime. I believe the sudden deceleration caused the connection to the lane keep camera to come slightly lose. Make sure all your connections are solid.

**Comment by arne182** [comment]
I agree. Loose connection.

**Comment by cydia2020** [comment]
Thanks for the suggestion, I'll go ahead and make sure the connection is solid.

Sincerely
Cheng Chi

________________________________

**Comment by ErichMoraga** [comment]
I hate to break it to you, but I believe this is the bug I've ranted about a few times in Discord over the last few months affecting us when we use CAN forwarding with the DSU disconnected.

**Comment by illumiN8i** [comment]
I have an example of it occurring if it helps at all. b29e3bc918751697|2019-08-10--18-14-38--32

**Comment by cydia2020** [comment]
Yeah it's probably a bug the connection is quite solid

**Comment by cydia2020** [comment]
Seems to be fixed in 0.6.5, closing
