### ISSUE TITLE
Is it possible to communicate with lgsvl in openpilot?

### ISSUE THREAD

**Issue by BatuhanUlucay** [commaai/openpilot#824]
If it is possible, can you explain how to do that?

**Comment by pd0wm** [comment]
You would have to write your own fake car. The carInterface can contain the code for interfacing with the simulator.

**Comment by lemketron** [comment]
There's a video demonstrating this (posted just before this issue was created) here: https://vimeo.com/359211939

Curious if the code has been shared anywhere or upstreamed...

**Comment by vchadha** [comment]
This is very late so sorry for the necro bump, but if anyone else stumbles here, there is a really awesome paper by Sato et. al. titled "Hold Tight and Never Let Go: Security of Deep Learning based Automated Lane Centering under Physical-World Attack" where they accomplish this.

I believe they said they would opensource their bridge code between LGSVL and OP, but I am not sure if they have done this yet. Regardless, I am sure they would be open to communication.

Though OP now has a really sweet CARLA sim bridge file, so you could always use that instead.
