### ISSUE TITLE
The file "visionbuf_cl.cc" or "visionbuf_cl.c" is missing

### ISSUE THREAD

**Issue by susan987321** [commaai/openpilot#834]
When I tried to build "visiond.cc" on Ubuntu, an error occurred,
make: *** No rule to make target '../common/visionbuf_cl.o', needed by 'visiond'.  Stop.

I searched "visionbuf_cl" in the directory of openpilot, nothing can be found.

Is there somebody who accounted the same problem? Thank you very much!

**Comment by BatuhanUlucay** [comment]
I have the same problem

**Comment by pd0wm** [comment]
Does it work when you check out this branch? https://github.com/commaai/openpilot/pull/874

To feed it actual frames use `unlogger.py`, make sure you check out the `v0.6.6` tag of `openpilot-tools`.

**Comment by susan987321** [comment]
It works. Thank you very much for helping!@pd0wm
