### ISSUE TITLE
When approaching a fork in the road

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#851]
**Describe the bug**
If the model is able to do lane changes then it should also be able to know which way to take when a road forks.

**How to reproduce or log data**
At the moment it is a hit and miss. Sometimes right sometimes left, sometimes even worse is straight into the barrier.

**Expected behavior**
The model should favour the right lane of the right blinker is on momentarily or favour the left lane if the blinker is on momentarily.

** Device/Version information (please complete the following information):**
 - Device: all
 - Version: n/a
 - Car make: all

**Additional context**
Could probably be coded like I explained above but maybe you guys have a better idea how to use the model to decide which way to go if there are two ways seen.

**Comment by geohot** [comment]
We have plans for this, but it isn't very easy. We don't consider this a bug, we consider it a feature request, hence closing the issue.
