### ISSUE TITLE
OpenPilot is still engaged after car shuts off

### ISSUE THREAD

**Issue by cydia2020** [commaai/openpilot#854]
**Describe the bug**
Prius 2018 i-Tech
OpenPilot sometimes keep itself engaged after the car is fully shutted-off. OpenPilot no longer communicates with the car if the car is restarted and the car will display DSU errors.

**How to reproduce or log data**
Shut off car with OpenPilot in "ready to engage" mode

**Expected behavior**
EON should display ride completed

** Device/Version information (please complete the following information):**
 - Device: EON
 - Version: 0.6.5
 - Car make/model: Prius 2018 i-Tech

**Additional context**
Photo: 
![IMG_20191017_161313](https://user-images.githubusercontent.com/12470297/67000049-d1a5d900-f122-11e9-8dc5-6c47bdacff0c.jpg)

**Comment by ErichMoraga** [comment]
It sounds like you have Comma Power connected while DIP 3 is on.

**Comment by cydia2020** [comment]
Negative, DIP 3 is off when it happened

**Comment by ErichMoraga** [comment]
Is your DSU connected?

**Comment by ErichMoraga** [comment]
It sounds like your DSU is disconnected (which is fine), although you'll be more prone to odd issues.

**Comment by cydia2020** [comment]
Yes, DSU is disconnected as I don't like the factory braking model

**Comment by ErichMoraga** [comment]
Your issue only happened once, or does it occur consistently?

**Comment by cydia2020** [comment]
Only once, and I can't reproduce it anymore

**Comment by rbiasini** [comment]
Thanks. Other users reported this issue. We are looking into it.

**Comment by jpancotti** [comment]
I’ve also had this happen a few times with different versions of stock op on a 2017 CR V

**Comment by rbiasini** [comment]
Should be fixed in the upcoming 0.6.6

**Comment by cydia2020** [comment]
Thanks, closing

**Comment by cydia2020** [comment]
Still happened today, though the alert quickly went away
