### ISSUE TITLE
how can I feed visiond with a custom frame?

### ISSUE THREAD

**Issue by BatuhanUlucay** [commaai/openpilot#860]
Is it possible to test visiond with custom image?

**Comment by ErichMoraga** [comment]
Evet mümkün... although most people would feed it video via OpenPilot Tools.

**Comment by BatuhanUlucay** [comment]
Actually, I want to use the function named "model_eval_frame()" in driving.cc at line 54. Is that possible to test this functions output? 

I need to get frames from my own camera, not EON or driving datas. 

And yes, the issue #834 is another problem for me.
