### ISSUE TITLE
120ohm resistor for Panda+Giraffe

### ISSUE THREAD

**Issue by Prj1508** [commaai/openpilot#869]
Hi,
I have connected combination of Giraffe and Panda into front camera module connector in FCA pacifica. I am experiencing up to 10 seconds delays in reading CAN messages on my Ubuntu 16.04 machine and I suspect this could be due to 120 ohm terminal resistance missing in Panda (Giraffe documentation says it has this terminal resistance). Do I have to procure a 120ohm resistor and connect to make this work or Giraffe/Panda combination off the shelf should suffice? Any other suggestions to debug this will be helpful
thanks

**Comment by adhintz** [comment]
No need for a 120 ohm resistor on my 2017 Pacifica nor any other FCA on the supported car list.

Ensure the car is on, the giraffe switches are correct, hardware is in all the way, [linux udev is configured](https://community.comma.ai/wiki/index.php/Panda#Linux_udev_rules) properly and you're using something like [can_logger.py](https://github.com/commaai/panda/blob/master/examples/can_logger.py)
