### ISSUE TITLE
how to explain 100hz in file controld.py

### ISSUE THREAD

**Issue by gucasbrg** [commaai/openpilot#885]
In the file "controld.py", how does Hertz control to 100?
If it is exceeded, control it in "boardd.cc", this can be understood
If it is far from 100hz, what will happen to this,and I think the number of minutes is high probability uncertain.

**Comment by zorrobyte** [comment]
So while controlsd may run at 100Hz (which makes PID/INDI/LQR also run at 100), other parts of the stack run at different frequencies. MPC, for example, runs at the FPS of the model. CAN for toyota runs at 80Hz~. Interprocess communication is handled by ZMQ over a networking bus in a pub/sub model. Not sure if this is helpful to your use case, but different parts of the stack can run at different frequencies.
