### ISSUE TITLE
Battery low voltage

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#887]
Car battery dies in winter.

**How to reproduce or log data**
Have a car outside in the cold conditions with not a full battery

**Expected behavior**
The voltage of the car should override the switching off of the charging and send a message to the comma app that the car battery voltage is low

** Device/Version information (please complete the following information):**
 - Device:  EON/EON Gold
 - Version: 0.6.6
 - Car make/model: all

**Comment by pd0wm** [comment]
This should all be implemented now.
