### ISSUE TITLE
Camera radar vs steering angle

### ISSUE THREAD

**Issue by arne182** [commaai/openpilot#890]
At high steering angles 100-400° detected objects should be ignored at a distance where the car will safely pass the object.

**How to reproduce or log data**
Drive at low speed and turn into a road with parked traffic on both sides.

**Expected behavior**
If the object is inside the view of the camera. Reduce the distance of detectable objects with steering angle. I.e. if making a U-turn with steering angle at 400°. Do not brake for an object 10m away as this object will not be reached at that steering angle.

** Device/Version information (please complete the following information):**
 - Device: EON/EON Gold
 - Version: 0.6.6
 - Car make/model: all with low speed engagable and longitudinal control.

**Comment by HaraldSchafer** [comment]
This is one of the many problems inherent to ACC type longitudinal control. Will be fixed as e2e longitudinal control gets phase in
