### ISSUE TITLE
Unable to build NEOS from source

### ISSUE THREAD

**Issue by cschech** [commaai/openpilot#892]
Looking at the history, at one point there appears to have been a NEOS build system. Since it is using a lot of open source components, why isn't the source and the build system for the OS released anymore? Being able to build the complete system from source would be a big selling point IMO.

**Comment by ErichMoraga** [comment]
This has been discussed in Discord already.

**Comment by pd0wm** [comment]
At the moment the build system is open source. We might open source it again in the future.
