### ISSUE TITLE
break speed limit

### ISSUE THREAD

**Issue by Primus-zhao** [commaai/openpilot#9]
Hi Hotz, 

Saw that the speed limit is 25kmh due to ACC limitation, to overcome this,  you can cut ACC controller from powertrain CAN loop and generate faked ACC signal(especially torque and deceleration request), then you can play with full speed range. Hope this helps.

**Comment by Primus-zhao** [comment]
Sorry, my mistake. Of course you've overcome this, the limit is just for the usrs.

**Comment by mgraczyk** [comment]
Thanks for your input! As you pointed out, we are already generating our own ACC CAN messages.
