### ISSUE TITLE
help to explain mpc generator.cpp code. thanks

### ISSUE THREAD

**Issue by vangogh0318** [commaai/openpilot#900]
Recently I was looking at the mpc related code in the controls directory.
But I met some problem, I need help to explain the formula below. thanks 

in file lateral_mpc/generator.py
**f << dot(delta) == t; is derivative of delta time ?** 

**// Angular rate error 
h << (v_ref + 1.0 ) * t; it's mean speed*time?** 

in file longitudinal_mpc/generator.py
#define RW(v_ego, v_l) (v_ego * TR - (v_l - v_ego) * TR + v_egov_ego/(2G) - v_lv_l / (2G))
 #define NORM_RW_ERROR(v_ego, v_l, p) ((RW(v_ego, v_l) + 4.0 - p)/(sqrt(v_ego + 0.5) + 0.1)) 
**how to proof these formula?**

**Comment by pd0wm** [comment]
t is the control action (somewhat correlated to EPS motor torque). So the change in wheel angle is the control input: <img src="https://render.githubusercontent.com/render/math?math=\dot{\delta} = t">

The angular rate error has a multiplier with speed. At low speed we want less penalty for changing the steering angle.

Those formulas describe the desired following distance. It's how much distance you need if the car in front starts braking at G m/s^2, then TR (seconds) later you start braking too a G m/s^2 and not crash
