### ISSUE TITLE
'17 Corolla long tuning can't be well optimized for braking and gas

### ISSUE THREAD

**Issue by ShaneSmiskol** [commaai/openpilot#903]
**Describe the bug**
When a user installs the comma pedal on their 2017 Toyota Corolla to get full stop and go under 19 mph, braking and gas performance degrades significantly (as the pedal tuning changes the long PID loop output for both gas and brake). I've tried to tune for gas so that it doesn't accelerate over my set speed, or get closer than the 1.8 second following distance, however when I do that, braking is late and hard.

I've just tried using two PID loops with different tuning to control gas and brake independently and on my short test drive I took it feels like both gas and brake performance, or how smooth it is, has greatly increased. I set the brake PID loop to non-pedal stock Corolla tuning and gas is controlled by the pedal-tuned loop.

I know it's not the cleanest solution, but that stood out to me as the easiest way to isolate the two different tunes so let me know if anyone has any other ideas about this

** Device/Version information (please complete the following information):**
 - Device: EON Gold
 - Version: e.g. stock 0.6.6
 - Car make/model: 2017 Toyota Corolla

**Comment by pd0wm** [comment]
Duplicate #930
