### ISSUE TITLE
Model files in a format other than DLC?

### ISSUE THREAD

**Issue by gamarakone** [commaai/openpilot#905]
We are trying to use phones other than ones with QCOM chipset.  Can we get the model files in a generic format?

**Comment by ErichMoraga** [comment]
Nope, and calling this a "bug" is quite a stretch.

**Comment by gamarakone** [comment]
Perhaps we can rename the bug to read unable to run model in SOCs other
than QCOM.   We can label it a bug or a feature request but the community
will benefit from this being supported.

**Comment by pd0wm** [comment]
We release the tensorflow files:
https://github.com/commaai/openpilot/blob/master/models/supercombo.dlc.pb
