### ISSUE TITLE
why my commaai system can not be controled by the honda civic2017？

### ISSUE THREAD

**Issue by lovewhene** [commaai/openpilot#91]
this is messages of the serial port print:
whether i can think the hardware is working naturally?
when i test on the car,the ACC and LKAS do not work .

 80000000 resetting PHY
AHB idle
reset done
CAN initting
CAN init done
CAN initting
CAN init done
**** INTERRUPTS ON ****
USB reset
enumeration done 00000006
start request
ESUSP detected
80000000 resetting PHY
AHB idle
reset done
CAN initting
CAN init done
CAN initting
CAN init done
**** INTERRUPTS ON ****
USB reset
enumeration done 00000006
start request
ESUSP detected

**Comment by xeondriving** [comment]
Is that civic touring ?
