### ISSUE TITLE
v6.6 causes no longer works for 2016 RDX

### ISSUE THREAD

**Issue by npvk** [commaai/openpilot#911]
**Describe the bug**
Creates a "cruise fault now.  It worked perfectly fine a couple days ago.

**How to reproduce or log data**
When I turn on car comma no longer works.

**Expected behavior**
When I turn on the car comma work.

** Device/Version information (please complete the following information):**
 - Device: EON Gold
 - Version: 0.6.6
 - Acura RDX 2016

**Comment by ErichMoraga** [comment]
Have you discussed this in Discord yet?

**Comment by npvk** [comment]
I'm sorry, have not.  Is it on there?

**Comment by npvk** [comment]
I'll re-open after
