### ISSUE TITLE
Question: Get raw data to control

### ISSUE THREAD

**Issue by tausday** [commaai/openpilot#918]
Hello,

i have a Pontiac G8 and want to control the car by myself with actuator for brake, gas and steering wheel.

It is Possible to get the raw data from copilot for target angle , distance, realtive distance and more over Bluetooth or can.

Are maybe any Information where i can read.

Thanks

**Comment by tausday** [comment]
any help?

**Comment by ErichMoraga** [comment]
#old-cars on Discord
