### ISSUE TITLE
Honda Ridgeline

### ISSUE THREAD

**Issue by leh263** [commaai/openpilot#92]
Realize a lot of threads are vehicle requests but just wondering if the ridge line will be a feasible future platform. Would be great to have a self driving pickup.

**Comment by energee** [comment]
If it has honda sensing, then it is very possible.

**Comment by geohot** [comment]
Should be possible on the RTL-E

**Comment by leh263** [comment]
Thanks for getting back! In Canada it seems even the base model ridgeline has sensing. Do you think it will be possible to add support for other Hondas in 2017?

**Comment by geohot** [comment]
It's open source! We have no plans for that port, but you can.

**Comment by vanillagorillaa** [comment]
Added support in 0.4.4. Closing
