### ISSUE TITLE
explain the new_exposure  calculation method

### ISSUE THREAD

**Issue by vangogh0318** [commaai/openpilot#929]
hi, everyone, now I read the code in selfdrive/visiond/cameras/camera_qcom.c (version=0.6.6)

I meet a problem. in do_autoexposure function, why  does   new_exposure calculate in this way？ 
`new_exposure *= pow(1.05, (target_grey - grey_frac) / 0.05 );`
I know grey_frac is calculated in visiond.c

thanks

**Comment by geohot** [comment]
Not an issue, please ask questions on discord. discord.comma.ai
