### ISSUE TITLE
【visionimg】RGB image memory alloc alignment

### ISSUE THREAD

**Issue by luovang** [commaai/openpilot#932]
Hello，brainbox
 I have a question about OP's camera  rgb image alignment when alloc visionimg buffer. see as below:
```
void visionimg_compute_aligned_width_and_height(int width, int height, int *aligned_w, int *aligned_h) {
#ifdef QCOM
  compute_aligned_width_and_height(ALIGN(width, 32), ALIGN(height, 32), 3, 0, 0, 512, aligned_w, aligned_h);
#else
  *aligned_w = width; *aligned_h = height;
#endif
}
``` 
Could you tell what the meaning is of "ALIGN(width, 32)" and the function "compute_aligned_width_and_height".  
I guess this operation intents to align with system bytes when alloc memory and i haven't found the souce file "adreno_utils".  Could you give me some references about these questions？

thx

**Comment by geohot** [comment]
This is not an issue, please direct questions to discord.
