### ISSUE TITLE
rgb to yuv code

### ISSUE THREAD

**Issue by vangogh0318** [commaai/openpilot#936]
hello everyone!
about rgb_to_yuv.cl , I have two questions:
1. I know convert RGB images to YUV images, using this formula:

`Y = ( (  66 * R + 129 * G +  25 * B + 128) >> 8) +  16  
U = ( ( -38 * R -  74 * G + 112 * B + 128) >> 8) + 128  
V = ( ( 112 * R -  94 * G -  18 * B + 128) >> 8) + 128`

but, in selfdrive/camerad/transforms/rgb_to_yuv.cl, the formula is:
`#define RGB_TO_Y(r, g, b) ((((mul24(b, 13) + mul24(g, 65) + mul24(r, 33)) + 64) >> 7) + 16)
#define RGB_TO_U(r, g, b) ((mul24(b, 56) - mul24(g, 37) - mul24(r, 19) + 0x8080) >> 8)
#define RGB_TO_V(r, g, b) ((mul24(r, 56) - mul24(g, 47) - mul24(b, 9) + 0x8080) >> 8)`

the RGB_TO_Y is same, but RGB_TO_U, RGB_TO_V is different. who can explain that? thanks

2.Can anyone give some reference  to explain the rgb_to_yuv.cl code. thanks

**Comment by geohot** [comment]
Not an issue, please ask on discord.
