### ISSUE TITLE
debayer10 function

### ISSUE THREAD

**Issue by vangogh0318** [commaai/openpilot#937]
I Can't understand debayer10 function, can you give some references. thanks

> selfdrive/camerad/cameras/debayer.cl

**Comment by Jonty16117** [comment]
So this function basically fills up the unfilled colours from the camera's raw image. It also corrects the already present colours on that image.

**Comment by Jonty16117** [comment]
Here is the link to get more information about debayering:
https://en.m.wikipedia.org/wiki/Demosaicing

**Comment by geohot** [comment]
Not an issue, please ask on discord.
