### ISSUE TITLE
Peugeot 208 / e208 support

### ISSUE THREAD

**Issue by YamineRL** [commaai/openpilot#947]
Hey there,
Peugeot is releasing it's brand new 208, that also come in a electric version, the e208.
I'd love to gather some information about the steps to make it compatible with openpilot.

Anyone is free to help with this matter, e208 owners especially.
Thanks!

**Comment by ErichMoraga** [comment]
Being electric isn't important.  You'll need to confirm it has LKAS, otherwise go straight to #old-cars in our Discord community.

**Comment by geohot** [comment]
Closing issues requesting car ports. Pull requests with car ports in them will be reviewed!

Get started on discord: discord.comma.ai
