### ISSUE TITLE
Peugeot 3008 

### ISSUE THREAD

**Issue by cristianku** [commaai/openpilot#951]
Hi, do you plan to have it compatible with Peugeot 3008 ?

**Comment by ErichMoraga** [comment]
Some would have to port it.  If it has LKAS, you can certainly attempt it yourself.

**Comment by cristianku** [comment]
I can help port it. I am a developer. but what about LKAS, how can I find out about this LKAS ?

**Comment by cristianku** [comment]
I mean it has a form on lane keep assist that does not keep in the lane but it correct the steering to bring back into the middle of the lane if I am near to surpass it

**Comment by cristianku** [comment]
And the porting require some reverse engineering on the car protocol to understand how interact with the electric steering wheel or what ?

**Comment by bugsy924** [comment]
Send me a message on discord.comma.ai (Bugsy) and I'll show you the ropes assuming your camera and EPS communicate over a standard CAN bus. If the assumption is true, then you should be able to get it steering in a few days after receiving the hardware

**Comment by geohot** [comment]
Closing issues requesting car ports. Pull requests with car ports in them will be reviewed!

Get started on discord: discord.comma.ai

**Comment by jcmichot** [comment]
any feedback about Peugeot 3800/5800 ?

**Comment by dv336699** [comment]
> I would be very much interested in this. I have a 2017 5008 and it seems to me it is equipped with everything needed for a module like this. Unfortunately no support yet. Is it planned?

I don't think commaai is going to implement it by themselves, so it's down to the community to do it I'm afraid
