### ISSUE TITLE
UI does not draw leadTwo

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#969]
When a cut-in happens (which will be present in `radarState.leadTwo`) this is not drawn on the UI. The car will start braking before the lead car shows up in the ui.

**Comment by pd0wm** [comment]
When there is no cut-in leadOne ad leadTwo have very similar or exactly the same values. When any of the position variables dRel/yRel diverges more than 0.1 meter they can be considered different.

**Comment by AravindaDP** [comment]
Does this issue still open to be picked up?

Like to contribute doing this. Per my understanding;
Current behavior: Planner already accounts for both leadOne and leadTwo but UI only draws leadOne
Expected change: Change appropriate code in selfdrive/ui (paint.cc, ui.c and ui.hpp I suppose)

I see that lead will be accounted for both drawing chevron and track height. Does track height should be based on nearest lead in this case?

Thanks in advance

**Comment by arne182** [comment]
https://github.com/commaai/openpilot/pull/1133

Done!

![image](https://user-images.githubusercontent.com/844102/74916447-29e93200-53c6-11ea-9bb8-95b9deb61fc8.png)
Tested!
Working!
