### ISSUE TITLE
Importing selfdrive.version writes to .git

### ISSUE THREAD

**Issue by pd0wm** [commaai/openpilot#973]
Importing selfdrive.version writes to the .git directory. Probably due to:
`        subprocess.check_call(["git", "update-index", "--refresh"])`

Writing to disk during the startup process could cause disk corruption on the comma two if were to unplug it during this write operation.

Writing to the `.git` directory also causes the updater to reinitalize the overlay.

**Comment by geohot** [comment]
Ahh, do we need this? With release2 being binaries, maybe the dirty flag doesn't matter.

**Comment by geohot** [comment]
We should probably strace manager to see if there's any other writes on release2
