### ISSUE TITLE
InitData.gitBranch has extra junk bytes in 0.7.1 release2

### ISSUE THREAD

**Issue by andyh2** [commaai/openpilot#992]
Reading initData.gitBranch from a 0.7.1 release2 log will throw `UnicodeDecodeError` as logged data in that field is `release2\xd0\x03\t\x99` . Let's figure out where the extra four bytes are coming from and fix the issue.

**Comment by pd0wm** [comment]
Is this happening on all routes, or just a few?

**Comment by andyh2** [comment]
All 0.7.1 routes running release2 are affected. Most forks seem to not have the issue. 

Also, the extra data at the end of the branch field is not consistently `\xd0\x03\t\x99`, I see many variants among 0.7.1 routes.

**Comment by pd0wm** [comment]
Loggerd.cc makes the wrong assumption that the values from `read_db_value` are NULL terminated. Which there are not. This causes random junk to be appended.

**Comment by pd0wm** [comment]
Should be fixed by: https://github.com/commaai/openpilot/commit/393c4987c8f1f8744cf2315f04ce9f14a5efc116

@andyh2, can you confirm?

**Comment by andyh2** [comment]
LGTM and branch field is now clean. Verified in a log produced by running that commit in a local branch named 'release2'.
